### ISSUE TITLE
Bug in FMWInfrastructure

### ISSUE THREAD

**Issue by ollyando** [oracle/docker-images#1000]
When running the following command to extend the FMW , the wlst script seems to have an issue creating a folder.

See command and output below.

docker run -d -p 7001:7001 --network=InfraNET -v $HOST_VOLUME:/u01/oracle/user_projects --name InfraAdminContainer --env-file ./infraDomain.env.list oracle/fmw-infrastructure:12.2.1.3

AdminContainer
Configuring Domain for first time
If Domain has already been Configured
Start the Admin and Managed Servers
CONNECTION_STRING=******:1521/ORCLPDB1.localdomain 
RCUPREFIX=INFRA6
DOMAIN_NAME=InfraDomain
Loading RCU Phase
CONNECTION_STRING=1521/ORCLPDB1.localdomain
RCUPREFIX=INFRA6
DB_PASSWORD=*
jdbc_url=jdbc:oracle:thin:@:1521/ORCLPDB1.localdomain
ADMIN_PASSWORD=
DB_SCHEMA_PASSWORD=****
DB_USERNAME=sys
DOMAIN_HOME:
MW_HOME: /u01/oracle
WL_HOME: /u01/oracle/wlserver
ADMIN_USER: weblogic
DOMAIN_ROOT: /u01/oracle/user_projects/domains
DOMAIN HOME: /u01/oracle/user_projects/domains/InfraDomain
Loading SOA RCU into database
RCU has some error
RCU has already loaded schemas into the Database
RCU Ignore error
Domain Configuration Phase

==========================

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

/u01/oracle/container-scripts/createInfraDomain.py called with the following sys.argv array:
sys.argv[0] = /u01/oracle/container-scripts/createInfraDomain.py
sys.argv[1] = -oh
sys.argv[2] = /u01/oracle
sys.argv[3] = -jh
sys.argv[4] = /usr/java/default
sys.argv[5] = -parent
sys.argv[6] = /u01/oracle/user_projects/domains
sys.argv[7] = -name
sys.argv[8] = InfraDomain
sys.argv[9] = -user
sys.argv[10] = weblogic
sys.argv[11] = -password
sys.argv[12] = welcome1
sys.argv[13] = -rcuDb
sys.argv[14] = dockerubuntuceres.cloudapp.net:1521/ORCLPDB1.localdomain
sys.argv[15] = -rcuPrefix
sys.argv[16] = INFRA6
sys.argv[17] = -rcuSchemaPwd
sys.argv[18] = manager
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 270, in ?
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 55, in __init__
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 175, in validateDirectory
  File "/u01/oracle/wlserver/common/wlst/modules/jython-modules.jar/Lib/javaos.py", line 158, in makedirs
OSError: [Errno 0] couldn't make directories: /u01/oracle/user_projects/domains

**Comment by jwwallac** [comment]
This is the exact same issue I'm having. Why did you close it? Did you find an answer?

**Comment by ollyando** [comment]
> This is the exact same issue I'm having. Why did you close it? Did you find an answer?

Hi jwwaallac, I did fix it. The documentation was not clear but I think it was pilot error.

The FMW uses local storage to persist the domain and app data.

so create a directory on your localhost running docker

then in the docker run command , replace the variable $HOST_VOLUME with your local directory just created.

docker run -d -p 7001:7001 --network=InfraNET -v $HOST_VOLUME:/u01/oracle/user_projects --name InfraAdminContainer --env-file ./infraDomain.env.list oracle/fmw-infrastructure:12.2.1.3

to

docker run -d -p 7001:7001 --network=InfraNET -v <some local directory>:/u01/oracle/user_projects --name InfraAdminContainer --env-file ./infraDomain.env.list oracle/fmw-infrastructure:12.2.1.3

The instructions could be a bit clearer that it used a docker volume and you need to make a local directory.

See if it works for you.

**Comment by jwwallac** [comment]
Thanks for the response...

I created a local directory as the user=1000; group=1000 with the
permissions on the directory 777

mkdir -p /scratch/DockerVolume/InfaVolume

I executed the following command as the 1000 user.

docker run -d -p 7001:7001 --network=SOANet -v
/scratch/DockerVolume/InfaVolume:/u01/oracle/user_projects --n
ame InfraAdminContainer --env-file ./infraDomain.env.list
oracle/fmw-infrastructure:12.2.1.3

And received the same error as you. So this might be another issue.

I'm thinking that it might because that the user with 1000 id on my system
isn't oracle... so I'm tracking that down to see if I can address it.

**Comment by ollyando** [comment]
I just logged into my container to check, that is the command I used,

  docker run -d -p 7001:7001 --network=InfraNET -v /home/orlandokelly/oracle:/u01/oracle/user_projects --name InfraAdminContainer --env-file ./infraDomain.env.list oracle/fmw-infrastructure:12.2.1.3

and the directory had these permissions drwxrwxr-x


hope that helps

**Comment by ollyando** [comment]
BTW, are you trying to get a SOA env up and running?
