### ISSUE TITLE
Configure password for user in domain consider only 'weblogic'

### ISSUE THREAD

**Issue by maidirepelle** [oracle/docker-images#1004]
https://github.com/oracle/docker-images/blob/f847a255a384fd78b187fb0ae7aecee528c36af5/OracleWebLogic/dockerfiles/12.2.1.3/container-scripts/create-wls-domain.py#L58

Hi, I think an adjustement in this script is necessary to manage a different user instead of weblogic. For example in https://github.com/oracle/docker-images/blob/f847a255a384fd78b187fb0ae7aecee528c36af5/OracleWebLogic/samples/wls-K8s/wls-12213-domain/container-scripts/provision-domain.py#L54 the username is parametric.

I am trying to configure a different user instead of 'weblogic' but I'm failing every time.
Am I missing something?

**Comment by maidirepelle** [comment]
I would definetely change this
https://github.com/oracle/docker-images/blob/f847a255a384fd78b187fb0ae7aecee528c36af5/OracleWebLogic/samples/wls-K8s/wls-12213-domain/container-scripts/provision-domain.py#L54

in this

`# Define the user password for weblogic
# =====================================
cd(('/Security/%s/User/weblogic') % domain_name)
cmo.setName(user_name);
cmo.setPassword(password)`

So the new default user will became the one sent as parameter.

**Comment by mriccell** [comment]
@maidirepelle you are correct, thanks for pointing it out.  I will create a PR to fix this.

**Comment by mriccell** [comment]
Fixed in PR 1017
