### ISSUE TITLE
Oracle linux 6.10, Docker port mapping fails 

### ISSUE THREAD

**Issue by melias77** [oracle/docker-images#1005]
Hi,
Im strugling with weblogic 12.2.1.3 server on docker. I cant do "- p 8001:7001" with docker run. Do u anyone know how to make oracle linux base image 6.10 ready for port mapping or is there a dedicated one with no firewall etc. Can anyone tell me what to disable to make port mapping work with docker and oracle linux image?
Kind
Regards
Elias

**Comment by Djelibeybi** [comment]
I'm not sure I understand your issue: are you trying to run the WebLogic image on Oracle Linux 6 Update 10? If so, that's unsupported. We only support Oracle Linux 7 as a Docker host.

If you're trying to run a custom WebLogic container using the `oraclelinux:6.10` base image, then I suggest you try running one of the images in this repo instead, based on `oraclelinux:7-slim` as they have been authored by Oracle staff and have been tested internally and by our users.

**Comment by melias77** [comment]
We have to create our own docker image, because we need to install additional application and customer specific things before installing weblogic. Do anyone have any experience with port mapping on oracle linux 6.10 base  image? Im kinda stuck now :(

**Comment by melias77** [comment]
Okay I will try to look through this docker image and see how this is done. Thx a lot :)

**Comment by Djelibeybi** [comment]
I'm pretty sure the port mapping issue is a WebLogic problem, i.e. you have to port map the same external and internal ports.

See if https://github.com/oracle/docker-images/issues/46 or https://github.com/oracle/docker-images/issues/575 provide any useful tips. 

BTW, this is not an official support resource. If you have a WebLogic support contract, you're beter off opening an SR, but I think you'll find that WebLogic is only certified in a Docker container when using the `oraclelinux:7-slim` base image. 

It's also Sunday in the USA so it's unlikely anyone from the WLS team will see this issue today.

**Comment by Djelibeybi** [comment]
To be clear, all the base images have no firewall configured so port mapping should just work, assuming the target port is open and accepting connections.

**Comment by melias77** [comment]
good to know about the weblogic issue, it definitely saved me some time. Thx again :)

**Comment by mriccell** [comment]
The problem relates to t3 using the default channel to connect to the servers in the container where the internal server port and the external host port are different. Configure a channel in WebLogic and specify the external address and external port and then use the channel to make your t3 connection.
Please look at https://docs.oracle.com/cd/E72987_01/wls/WLACH/taskhelp/channels/ConfigureCustomNetworkChannelsForNonclusteredServers.html leave the address blank and only configure your port to the host port that you are mapping. Can you please try it and let me know the results?  If this still does not work for you can you please share your config.xml?
Thanks
Monica

**Comment by melias77** [comment]
@mriccell, yes I will try. I already succeded with reaching weblogic outside on port 9002, but yes I still have figure out how this nodemanager now works, because I cant start my managed server from console now, it might relate to what you mention. It fails with Incompatibility states. I have a fairly simple setup. One adminserver and one managed server + nodemanager. The adminserver part is now :) thx for helping

**Comment by melias77** [comment]
@mriccell, I dont think I clearly understand how this works. My overall misssion is a py script that creates adminserver and one managed server + datasource configuration. I am done with the script now and everything seems to be generated correctly. I added this "9002" stuff in the py script. So now I can reach the console on port 9002 from outside the docker container, but I cant start my managedserver from the console and it might be because of this adm listenaddress being blank and then the nodemanager cant connect or smth.? The channel, I guess is what solves it? i

**Comment by mriccell** [comment]
@melias77 do you still have questions?

**Comment by melias77** [comment]
No, everything is solved. Thanks for all the help.
