### ISSUE TITLE
How to map - log files to local folder?

### ISSUE THREAD

**Issue by rajachinnanchetty** [oracle/docker-images#1013]
docker run -d -v /d/dockerlogs:/u01/oracle/user_projects/domains/base_domain/servers/AdminServer/logs -p 8001:8001 localdomain

i am mapping the Weblogic logs running in docker to local folder. I just want to make it generic - instead of specifying the domain/server name etc. How can i do it?

docker run -d -v /d/dockerlogs:/u01/oracle/user_projects/domains/base_domain/servers/AdminServer/logs -p 8001:8001 localdomain

**Comment by mriccell** [comment]
Well you know the name of the server you are starting which can be passed using the -e option
ADMIN_NAME="${ADMIN_NAME:-AdminServer}" 
MS_NAME="${MS_NAME:-""}" 
Set an env var export ADMIN_NM=MyAdminServer and then
docker run -d -e ADMIN_NAME=$ADMIN_NM -v /d/dockerlogs:/u01/oracle/user_projects/domains/base_domain/servers/$ADMIN_NM/logs -p 8001:8001 localdomain

You could also map to /u01/oracle/user_projects/domains/base_domain/servers but then you get logs, diagnostics, stores for all the servers in the domain.  If you depend on the store for migration then the volume has to be shared to all servers in the cluster.

**Comment by mriccell** [comment]
@rajachinnanchetty were you able to map?

**Comment by rajachinnanchetty** [comment]
I think i am going wrong somewhere.
I have this in my docker file 
FROM 1221-domain 
RUN export ADMIN_NM="AdminServer"
and this is how i start the container - but don't see the logs though.
docker run -d -e ADMIN_NAME=$ADMIN_NM -v 
/d/dockerlogs:/u01/oracle/user_projects/domains/base_domain/servers/$ADMIN_NM/logs -p 8001:8001 1221-domain-with-resources

**Comment by mriccell** [comment]
@rajachinnanchetty  bash into the container and look at the value env variable $ADMIN_NM then cd to the directory /u01/oracle/user_projects/domains/base_domain/servers/$ADMIN_NM/logs and see if the log files are there.  Did you change the domain name?

**Comment by rajachinnanchetty** [comment]
ADMIN_NAME=$ADMIN_NM is what i see when i bash and printenv.

I think it consider $ADMIN_NM as a foldername and i see all logs under it and not  $ substituted.

bash-4.2$ dir
$ADMIN_NM  AdminServer

logs are under $ADMIN_NM
