### ISSUE TITLE
Standalone WebLogic Docker Container with JRF/ADF Libraries

### ISSUE THREAD

**Issue by sandeepm152** [oracle/docker-images#1016]
Hi Monica,

I'm trying to deploy an ADF application into Weblogic Docker container. I'm able to run Standalone WebLogic Docker container. However, it does not have any ADF libraries. I have tried to run fmw-middleware docker. But it requires RCU to be setup.

Can you please let me know me how I can have a WebLogic Docker Container with JRF/ ADF Runtime libraries installed?

Thanks
Sandeep

_Originally posted by @sandeepm152 in https://github.com/oracle/docker-images/issues/763#issuecomment-430699176_

**Comment by ollyando** [comment]
Same issue here, I had to do the full FMW install with a oracle database.  For developers, we need a weblogic docker container with ADF, for both 11g and 12c ADF.

**Comment by mriccell** [comment]
@ollyando at this time we do not have or support 11g images of WebLogic or ADF.  You should also know that as of today the FMW Infrastructure image is only supported in development and testing, only the WebLogic images are supported in production.  
What is your use case, do you need ADF images supported in production?  Who is the customer?
Thanks
Monica

**Comment by Djelibeybi** [comment]
Please do not discuss customer details via GitHub. 

However, I don't believe either @sandeepm152 or @ollyando are Oracle employees. Neither are members of the Oracle organisation on GitHub.

**Comment by sandeepm152** [comment]
Hi,

I'm an Oracle Employee. I was able to reach out to Monica via email.

Here is our use case:
We provide support of Oracle Retail products for the customers. If customers raises an issue on any version which is compatible with some specific FMW stack, we will have to request a specific team to get the environment ready with corresponding Tech Stack (WebLogic, ADF) . This would take some time (approx 1-2 days).

We are trying to cut down this time so that we can eliminate the dependency and get the application running with underlying infrastructure in a Docker Container.

Thanks
Sandeep

**Comment by Djelibeybi** [comment]
Please get your GitHub account added to the Oracle GitHub Organisation to avoid future confusion. 😁

**Comment by anudeeparla** [comment]
@mriccell as you mentioned ADF supported by only FMW infrastructure image, i have a requirement where i have to put SOA, BPM composites with ADF Application in weblogic. which image we should use in this purpose? i see two separate images for SOA and FMW infrastructure.

**Comment by mriccell** [comment]
ADF, SOA, and BPM images are all based on the FMW Infrastructure image.  So when you build the SOA image one of its lower layers is FMW Infra, so in this example you use the SOA image.  When you deploy an ADF app you are deploying on a domain on the FMW Infrastructure image, in this example you use the FMW Infra image.
