### ISSUE TITLE
Docker Run Issue: container_linux.go:348

### ISSUE THREAD

**Issue by vnaprasad** [oracle/docker-images#1019]
Hi Team,

I have create docker Image for Oracle database 12.2.0.1-ee.  when I execute docker run command I am getting following error. I have installed docker on OEL7.

docker run --name oracle-ee -p 1521:1521 -v /home/oracle/oradata:/opt/oracle/oradata oracle/database:12.2.0.1-ee ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: 3y4RL1K7org=1

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"ORACLE\": executable file not found in $PATH": unknown.

Regards
Prasad

**Comment by Djelibeybi** [comment]
That command is incorrect. Why are you adding `ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: 3y4RL1K7org=1` to the end?

**Comment by Djelibeybi** [comment]
Please review the documentation and use the correct `run` command: https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md
