### ISSUE TITLE
Facing problem in 1221-medrec

### ISSUE THREAD

**Issue by suniljav** [oracle/docker-images#102]
Hi Sir

I am facing problem while running command for sample/1221-medrec " $ docker run -d -p 7001:7001 1221-medrec" on ubuntu , I am getting below error.

WLST-WLS-1464625798480: <May 30, 2016 4:29:59 PM UTC> <Info> <Management> <BEA-141107> <Version: WebLogic Server 12.2.1.0.0 Tue Oct  6 10:05:47 PDT 2015 1721936> 
     [java] ..........................WLST-WLS-1464625798480: <May 30, 2016 4:31:29 PM UTC> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to STARTING.> 
     [java] WLST-WLS-1464625798480: <May 30, 2016 4:31:29 PM UTC> <Info> <WorkManager> <BEA-002900> <Initializing self-tuning thread pool.> 
     [java] WLST-WLS-1464625798480: <May 30, 2016 4:31:29 PM UTC> <Info> <WorkManager> <BEA-002942> <CMM memory level becomes 0. Setting standby thread pool size to 256.> 
     [java] WLST-WLS-1464625798480: <May 30, 2016 4:31:30 PM UTC> <Notice> <Log Management> <BEA-170019> <The server log file weblogic.logging.FileStreamHandler instance=1445671714
     [java] WLST-WLS-1464625798480: Current log file=/u01/oracle/user_projects/domains/medrec/servers/AdminServer/logs/AdminServer.log
     [java] WLST-WLS-1464625798480: Rotation dir=/u01/oracle/user_projects/domains/medrec/servers/AdminServer/logs
     [java] WLST-WLS-1464625798480:  is opened. All server side log events will be written to this file.> 
     [java] WLST-WLS-1464625798480: <May 30, 2016 4:31:30 PM UTC> <Notice> <Security> <BEA-090946> <Security pre-initializing using security realm: myrealm> 
     [java] java.io.IOException: Stream closed
     [java] 	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
     [java] 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:283)
     [java] 	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
     [java] 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
     [java] 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
     [java] 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
     [java] 	at java.io.InputStreamReader.read(InputStreamReader.java:184)
     [java] 	at java.io.BufferedReader.fill(BufferedReader.java:161)
     [java] 	at java.io.BufferedReader.readLine(BufferedReader.java:324)
     [java] 	at java.io.BufferedReader.readLine(BufferedReader.java:389)
     [java] 	at weblogic.management.scripting.utils.WLSTProcess.run(WLSTProcess.java:82)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Problem invoking WLST - Traceback (innermost last):
     [java]   File "/u01/oracle/wlserver/samples/server/medrec/install/common/startAdminServer.py", line 11, in ?
     [java]   File "<iostream>", line 366, in startServer
     [java]   File "<iostream>", line 553, in raiseWLSTException
     [java] WLSTException: Error occurred while performing startServer : Could not start the server, the process might have timed out or there is an Error starting the server. Please refer to the log files for more details.
     [java] 
     [java] .........**Could not connect to the server to verify that it has started. The error returned is: javax.naming.CommunicationException: t3://localhost:7001: [RJVM:000575]Destination 0:0:0:0:0:0:0:1, 7001 unreachable**.; nested exception is: 
     [java] 	java.net.ConnectException: Connection refused; [RJVM:000576]No available router to destination.; nested exception is: 
     [java] 	java.rmi.ConnectException: [RJVM:000576]No available router to destination. [Root exception is java.net.ConnectException: t3://localhost:7001: [RJVM:000575]Destination 0:0:0:0:0:0:0:1, 7001 unreachable.; nested exception is: 
     [java] 	java.net.ConnectException: Connection refused; [RJVM:000576]**No available router to destination**.; nested exception is: 
     [java] 	java.rmi.ConnectException: [RJVM:000576]No available router to destination.]
     [java] WLST-WLS-1464625798480: IOException when running WLSTProcess
     [java] WLST-WLS-1464625798480: Stopped draining WLST-WLS-1464625798480
     [java] No stack trace available.

BUILD FAILED
/u01/oracle/wlserver/samples/server/medrec/build.xml:27: The following error occurred while executing this line:
/u01/oracle/wlserver/samples/server/medrec/install/build.xml:10: The following error occurred while executing this line:
/u01/oracle/wlserver/samples/server/medrec/install/non-mt-single-server/build.xml:21: The following error occurred while executing this line:
/u01/oracle/wlserver/samples/server/medrec/install/non-mt-single-server/build.xml:39: The following error occurred while executing this line:
/u01/oracle/wlserver/samples/server/medrec/install/common/build.xml:27: Java returned: 1

I ran the command for oracle/weblogic:12.2.1-developer but build command "$ docker build -t 1221-medrec ." ran successful.

But sample/1221-domain "$ docker run -d --name=wlsadmin -p 8001:8001 1221-domain" is running successfully, I didn't face any such exception "unreachable port" .

I tried 1221-medrec by changing port 7001 to 8001 but got same exception "javax.naming.CommunicationException: t3://localhost:8001: [RJVM:000575]Destination 0:0:0:0:0:0:0:1, 8001 unreachable" 

Here would like to know, 
1. why 1221-medrec is not able to open port 7001/8001 while 1221-domain is able to open port 8001 ?
2. If I need to set any extra env/file variable to enable port 7001 please let me know.
3. is there any proxy setting? if yes please let me know where to set and what variable need to set.
4. where to set "XX:+UnlockCommercialFeatures -XX:+ResourceManagement" to enable "ResourceManagement" ?

Thanks Sir

**Comment by brunoborges** [comment]
`1221-medrec  sample actually starts AdminServer on port 7001, as per its [README](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/1221-medrec/README.md), and it does not extend `1221-domain`.

You must access AdminServer through port 7001.

It is also up to you how to adjust the container to decide access type to the container port.

There shouldn't be any proxy settings.

Finally, to enable RM, read [WebLogic documentation](https://docs.oracle.com/middleware/1221/wls/WLSMT/config_rcm.htm#WLSMT630).
