### ISSUE TITLE
403 Permission Denied - WLS Administration Console

### ISSUE THREAD

**Issue by ynraju4** [oracle/docker-images#1026]
Hello,

I ran below docker command and my container started. Buy when I try to access console I am getting below error. Please suggest how can avoid this and access weblogic console. 

Docker command : docker run -d -p 7002:7001 -p 9004:9002 -v $PWD::/u01/oracle/properties container-registry.oracle.com/middleware/weblogic:12.2.1.3-dev

Error while accessing weblogic console: 403 Permission Denied - WLS Administration Console

Permission Denied 

 The console is not available at this address, or the user is not authorized to use this feature. If an administration port is enabled (as is the case in secure mode), then that port must be used to access the console.

Please correct the URL or LOGIN again. 

Regards,
Nagaraju

**Comment by mriccell** [comment]
With this new image by default the Administration port with SSL is enabled.  There is a note in the README that indicates  "In your browser, enter https://xxx.xx.x.x:9002/console. Your browser will request that you accept the Security Exception. To avoid the Security Exception, you must update the WebLogic Server SSL configuration with a custom identity certificate."  
If you do not want the security  of using the Administration Port you can disable it by adding -e ADMINISTRATION_PORT_ENABLED=false.
Thanks
Monica

**Comment by mriccell** [comment]
@ynraju4 Did this fix your problem?

**Comment by ynraju4** [comment]
Wow, @mriccell , I am able to access brand new 12c console, Thanks a lot for the support. I'll continue with my R&D, I'll reach you if any doubts. :)
