### ISSUE TITLE
Oracle Database 11g XE APEX Connection 

### ISSUE THREAD

**Issue by utkudarilmaz** [oracle/docker-images#1028]
Hi,
On Oracle11g Express Edition, i can connect to APEX via Chromium browser but i can't connect to APEX via Firefox. When i try the connect APEX via Firefox, i entering username and password  then the spinner always turning around but never loading site. 

Firefox version : 62.0.3 64Bit

Wanted to report the bug.

Best regards.

**Comment by Djelibeybi** [comment]
This is not the right place to log bugs for Oracle XE. Please open an SR via My Oracle Support to do that.
