### ISSUE TITLE
Create Machine and Server on Images

### ISSUE THREAD

**Issue by danyfauzi** [oracle/docker-images#1030]
Hi, Is is possible to create the images with together creating domain as well as adding the server and machine together from 1221-domain using script on the container script for createServer.sh?

**Comment by mriccell** [comment]
@danyfauzi Could you please rephrase your question?  Are you asking can I create a 12.2.1.3 image including the domain in the image as done in 1221-domain?

**Comment by danyfauzi** [comment]
Thanks for the reply @mriccell  my question is, after creating the 1221-domain images. Can we extend it with create the server. So on the latest image created, there will be a domain created, 1 Administrator and 1 managed server created and 1 machine created.

**Comment by mriccell** [comment]
Yes you can extend the image to have any configuration you want just provide the WLST to create the domain configuration.
