### ISSUE TITLE
fix in runOracle.sh

### ISSUE THREAD

**Issue by burtsevyg** [oracle/docker-images#1033]
symLinkFiles does not create link if file exist
add -f to to ln command

**Comment by Djelibeybi** [comment]
There isn't nearly enough information to know what you're talking about. Which `runOracle.sh`? What's `symLinkFiles`? Add `-f` to which `ln` command?

**Comment by burtsevyg** [comment]
@gvenzl You are right I mean https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/runOracle.sh

In my oracle image I create default /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/sqlnet.ora and then get
`ln: failed to create symbolic link ‘/opt/oracle/product/12.2.0.1/dbhome_1/network/admin/sqlnet.ora’: File exists`

After remove default sqlnet.ora all work perfect.
Thank you!
