### ISSUE TITLE
Missing rights to execute install script for 12.2.0.1-EE

### ISSUE THREAD

**Issue by lookyflashbecki** [oracle/docker-images#1037]
Hi, 
There was a problem with executing install script during build of docker image 12.2.0.1-EE.
It seems that there is missing execution bit set on  installDBBinaries.sh.
Line related to that issue:
83 RUN $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE $DB_EDITION

Fix to have a complete and successful build is to add line as below before switching to user oracle:
**RUN chmod ug+x $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE**

Working part of code:
`# Copy DB install file`
COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/

RUN chmod ug+x $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE

`# Install DB software binaries`
USER oracle
RUN $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE $DB_EDITION`

Regards

**Comment by gvenzl** [comment]
Analysis: The `chmod` was lost with the introduction of multi-stage builds which happens in the stage before the DB binaries installation.
