### ISSUE TITLE
Issue creating 18.3.0 XE Image

### ISSUE THREAD

**Issue by MarkusHaslinger** [oracle/docker-images#1038]
I'm attempting to create an image for the new 18.3.0 XE database.
However, the docker build fails:
```
./buildDockerImage.sh -v 18.3.0 -x -i
[...]
Step 11/24 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
COPY failed: stat /var/lib/docker/tmp/docker-builder397757922/LINUX.X64_180000_db_home.zip: no such file or directory
```
I checked and the /var/lib/docker/tmp directory really is empty. 

Is that something I can fix on my end?

**Comment by Djelibeybi** [comment]
If you read the documentation, you'll see that only Enterprise and Standard are currently supported for 18.3. If you want XE, you need to use the 11gR2 version until support for 18.3 is added.

**Comment by MarkusHaslinger** [comment]
Ah! When I went to download XE files today I realized the 18.3 XE had been released and then I checked here and saw the commit that added 18.3.0 functionality somehow assuming that would include Express as well.
My bad, thanks for the heads-up.
