### ISSUE TITLE
Docker Multi Host Workshop

### ISSUE THREAD

**Issue by sguntur-juniper** [oracle/docker-images#104]
@Bruno I am struggling to run wls on multi-host, followint your github workshop link https://github.com/oracle/docker-images/tree/master/OracleWebLogic/workshops/multihost.

runnung into issues when Iam running bootstrap.sh , docker-machine create -d virtualbox . 

I am trying your workshop on VirtualBox VM , also tried installing virtualbox inside that VM , still not able to run successfully.

Iam I missing regarding this part ? to be taken care before starting on this workshop ? (I am running this on VirtualBox VM with CentOS 7)

**Comment by brunoborges** [comment]
You have to make sure Docker Machine is properly installed and working before trying the workshop. Please follow Docker Machine documentation and "hello world"-like tutorials available online.

If Docker Machine is working fine, then please go ahead and submit more details about your particular issue with the workshop material.

**Comment by somu4git** [comment]
Hi Bruno, 
Docker Machine was installed properly , trying to run sample command, and running into issue: 

$ docker-machine version
docker-machine version 0.7.0, build a650a40
$ docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

]$ docker-machine create --driver virtualbox default
Running pre-create checks...
Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"

But I have enabled Acceleration properly on VM settings :

screenshot :

![image](https://cloud.githubusercontent.com/assets/19274288/16093363/7c164072-32f0-11e6-8a32-350138dfaa6a.png)

**Comment by brunoborges** [comment]
Hi @somu4git, I am sorry but I can't help you with Docker Machine issues. Please submit this issue to the [Docker Machine](https://github.com/docker/machine) project.

**Comment by somu4git** [comment]
thanks for the reply Bruno. 

The workshop  you created  ran successfully on ubuntu VM (running on virtualBox ) ?

**Comment by brunoborges** [comment]
Yes, it works fine on Ubuntu.
