### ISSUE TITLE
checkDBStatus.sh script is returning negative result if DB has multiple Plugged DB

### ISSUE THREAD

**Issue by YuriyGorvitovskiy** [oracle/docker-images#1041]
docker-images/OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/checkDBStatus.sh

When I restart container, after creation of a new plugged DataBase, container spills the following error message and stops:
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
#####################################

Analyzing logs and scripts, it ends up that query to checks Status is not handling multiple values received from the shell script command:

ORACLE_PDB="`ls -dl $ORACLE_BASE/oradata/$ORACLE_SID/*/ | grep -v pdbseed | awk '{print $9}' | cut -d/ -f6`"

SELECT open_mode FROM v\\$pdbs WHERE UPPER(name) = UPPER('$ORACLE_PDB');

**Comment by antoninoromeo** [comment]
Hi,
fow now i resolved in thath way:
 ORACLE_PDB="ls -dl $ORACLE_BASE/oradata/$ORACLE_SID/*/ | grep -v pdbseed | awk '{print $9}' | cut -d/ -f6| xargs -I{} echo "'{}',"" 
and
status=`su -p -c - oracle "sqlplus -s / as sysdba" << EOF set heading off; set pagesize 0; SELECT distinct(open_mode) FROM v\\$pdbs WHERE name COLLATE BINARY_CI in ( $ORACLE_PDB ''); exit; `EOF



> docker-images/OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/checkDBStatus.sh
> 
> When I restart container, after creation of a new plugged DataBase, container spills the following error message and stops:
> #####################################
> ########### E R R O R ###############
> DATABASE SETUP WAS NOT SUCCESSFUL!
> Please check output for further info!
> ########### E R R O R ###############
> #####################################
> 
> Analyzing logs and scripts, it ends up that query to checks Status is not handling multiple values received from the shell script command:
> 
> ORACLE_PDB="`ls -dl $ORACLE_BASE/oradata/$ORACLE_SID/*/ | grep -v pdbseed | awk '{print $9}' | cut -d/ -f6`"
> 
> SELECT open_mode FROM v\$pdbs WHERE UPPER(name) = UPPER('$ORACLE_PDB');
