### ISSUE TITLE
How to enable production mode with WebLogic sample 1221-domain

### ISSUE THREAD

**Issue by guhuajun** [oracle/docker-images#1049]
Greetings,

I am helping my customer to dockerize their application with WebLogic. I was a Python developer with less Java and WebLogic experience. @mriccell Thanks a lot for sharing these examples, thus I can deploy a sample application with WebLogic in two days.

Here is my demo project.
https://github.com/guhuajun/weblogic-docker

I tried to auto-deploy the application after reading following pull request.
https://github.com/oracle/docker-images/pull/320

The demo application is deployed and can be visited via browser.

My next question is how to enable Production mode? I tried to use "PRODUCTION_MODE=-prod" in my docker-compose.yaml file, but still got a warning in admin console.

By the way, I got an error when using domain-12213 sample.
![image](https://user-images.githubusercontent.com/14121694/48404554-6cf03a80-e76b-11e8-9d8e-3dea1c9c60df.png)

Thanks,
Greg

**Comment by mriccell** [comment]
@guhuajun What is your WebLogic image you are extending?  If it is the weblogic:12.2.1.3-dev that image has ENV PRODUCTION_MODE=dev  so you need to override that setting.  Can you give me more details of how you are setting PRODUCTION_MODE and what image you are extending?

**Comment by mriccell** [comment]
In the 1221-domain the PRODUCTION_MODE is an ARG and you probably can not override the setting from the weblogic:12.2.1-dev.  Change the ARG name
ARG DOM_PRODUCTION_MODE
ENV PRODUCTION_MODE="${DOM_PRODUCTION_MODE:-prod}"

and when you build the image invoke --build-arg DOM_PRODUCTION_MODE=prod.

**Comment by guhuajun** [comment]
@mriccell Thanks for sharing. Let me have a try.

**Comment by mriccell** [comment]
Glad to her that you were able to deploy your application successfully!
