### ISSUE TITLE
docker build -t 1221-domain fails - /bin/sh: /u01/oracle/wlst: /bin/sh^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by ckbridge** [oracle/docker-images#105]
running on Windows.. using Powershell.

I got as far running:
docker build -t 1221-domain --build-arg ADMIN_PASSWORD=welcome1 .

Sending build context to Docker daemon 22.53 kB
Step 1 : FROM oracle/weblogic:12.2.1-developer
 ---> 7512c3300af1
Step 2 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in 5496153d1e2f
 ---> c0ab738d1bb9
Removing intermediate container 5496153d1e2f
Step 3 : ARG ADMIN_PASSWORD
 ---> Running in 3dd7f1ec0fb9
 ---> 9e1ab006e4ab
Removing intermediate container 3dd7f1ec0fb9
Step 4 : ENV DOMAIN_NAME "base_domain" DOMAIN_HOME "/u01/oracle/user_projects/domains/base_domain" ADMIN_PORT "8001" ADM
IN_HOST "wlsadmin" NM_PORT "5556" MS_PORT "7001" CLUSTER_NAME "DockerCluster" CONFIG_JVM_ARGS "-Dweblogic.security.SSL.i
gnoreHostnameVerification=true" PATH $PATH:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/ora
cle/user_projects/domains/base_domain/bin:/u01/oracle
 ---> Running in 5021c81631c8
 ---> d2c06893259f
Removing intermediate container 5021c81631c8
Step 5 : USER oracle
 ---> Running in e5fd462789c9
 ---> 7153e1b0f14d
Removing intermediate container e5fd462789c9
Step 6 : COPY container-scripts/* /u01/oracle/
 ---> d96317ce7b6b
Removing intermediate container a5d04c94698d
Step 7 : RUN /u01/oracle/wlst /u01/oracle/create-wls-domain.py &&     mkdir -p /u01/oracle/user_projects/domains/base_do
main/servers/AdminServer/security &&     echo "username=weblogic" > /u01/oracle/user_projects/domains/base_domain/server
s/AdminServer/security/boot.properties &&     echo "password=$ADMIN_PASSWORD" >> /u01/oracle/user_projects/domains/base_
domain/servers/AdminServer/security/boot.properties &&     echo ". /u01/oracle/user_projects/domains/base_domain/bin/set
DomainEnv.sh" >> /u01/oracle/.bashrc &&     echo "export PATH=$PATH:/u01/oracle/wlserver/common/bin:/u01/oracle/user_pro
jects/domains/base_domain/bin" >> /u01/oracle/.bashrc
 ---> Running in aed231110c4f
/bin/sh: /u01/oracle/wlst: /bin/sh^M: bad interpreter: No such file or directory
The command '/bin/sh -c /u01/oracle/wlst /u01/oracle/create-wls-domain.py &&     mkdir -p /u01/oracle/user_projects/doma
ins/base_domain/servers/AdminServer/security &&     echo "username=weblogic" > /u01/oracle/user_projects/domains/base_do
main/servers/AdminServer/security/boot.properties &&     echo "password=$ADMIN_PASSWORD" >> /u01/oracle/user_projects/do
mains/base_domain/servers/AdminServer/security/boot.properties &&     echo ". /u01/oracle/user_projects/domains/base_dom
ain/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc &&     echo "export PATH=$PATH:/u01/oracle/wlserver/common/bin:/u01/orac
le/user_projects/domains/base_domain/bin" >> /u01/oracle/.bashrc' returned a non-zero code: 126

**Comment by brunoborges** [comment]
We don't have Windows to test it, and these files are not supported by Oracle. We publish them to help users get started, but they are free to deploy WebLogic on Docker however they want (even by writing their own Dockerfiles).

If you find a way to fix the sample files here, in a way it works both on Linux/Mac/Windows, please let us know.

**Comment by philipstaffordwood** [comment]
Problem is line ending difference between linux/windows.
The files in copied into the container with
`COPY container-scripts/* /u01/oracle/`
have been mangled.
I used cygwin with d2u on the files to fix them (i.e. make the line ending unix style as opposed to windows style)
