### ISSUE TITLE
Oracle DB 12C 12.0.1 Windows docker image/container install

### ISSUE THREAD

**Issue by JuanPerezActivus** [oracle/docker-images#1054]
Oracle setup installer and response files ready, I run the setup command with my response file on my own PC from an elevated cmd window and Oracle is installed, no problems found and oracledb installs according to my reponsefile

CMD command
setup -silent -responsefile d:\temp\database\response\db.rsp -skipPrereqs -noconfig -waitForCompletion

But even with silent switch the **Oracle Universal Installer** and some configuration still popping up, that will not work when installing from an image or within a container itself
(see picture attached)

![](https://discourse-cdn-sjc1.com/docker/uploads/default/original/3X/8/7/87af8cc17388e5294946fb0f60b692ce77543cb0.png)

When try to replicate using my dockerfile or an error or nothing happens

Docker file
#Sample Dockerfile

#Indicates that the windowsservercore image will be used as the base image.
FROM microsoft/windowsservercore

#Create the working folder
RUN mkdir c:\temp\database

#Copy Oracle installers and response file to the working directory previously created
COPY database /temp/database

#Run the command
RUN Powershell.exe Start-Process -FilePath ‘C:\temp\database\setup.exe’ -argumentlist ‘-responsefile c:\temp\database\response\db.rsp’, ‘silent’ -wait

Once ready I run on an elevated powershell Window

PS D:\docker\dockerfiles> docker image build -t 2016oracle -f dockerfile .

As I said even that the build might finish successfully and without errors the application it is not installed or the container run for a moment and then exits few seconds later

_Originally posted by @JuanPerezActivus in https://github.com/oracle/docker-images/issue_comments#issuecomment-439379674_

**Comment by ebellumat** [comment]
‘C:\temp\database\setup.exe’ - Where you Download these files? I stay stuck 3 days to install Oracle Instant Client on Windows Container. And Nothing.

**Comment by JuanPerezActivus** [comment]
Hi Ebellumat,

This is pretty much my workflow using a dockerfile for this case

![image](https://user-images.githubusercontent.com/45098105/49927631-43cfe080-feb6-11e8-8709-762f69cdfdcd.png)

**Comment by ebellumat** [comment]
Thanks, but, you get this files from where? "c:\temp\database\response\db.rsp" - Where i download this?

**Comment by ebellumat** [comment]
Resuming: Where folder i will put the "database" files to copy path?

**Comment by ebellumat** [comment]
SOLVED!

FROM microsoft/aspnet:4.7.2-windowsservercore-ltsc2016

RUN mkdir c:\temp\database

ARG source
COPY ${source:-database} /temp/database
WORKDIR /inetpub/wwwroot
COPY ${source:-obj/Docker/publish} .

**Comment by JuanPerezActivus** [comment]
With this you have the install files copied over, don’t understand the last step COPY ${source:-obj/Docker/publish} . but how do you run the oracle database installer?



Kind Regards

Juan


        [cid:image007.jpg@01D496E2.DD795A40]





Juan Perez
IT Infrastructure and Support, International Division

Brandon Park House • 25 Great George Street • Bristol • BS1 5QT • UK
Tel : +44 (0)117 316 9094
juan.perez@cegedim.com<mailto:juan.perez@cegedim.com>

        [Afficher l'image d'origine] <https://www.linkedin.com/company/cegedim-assurances>              [Afficher l'image d'origine] <https://twitter.com/cegedimis>


Follow us online – www.cegedim-insurance.com<http://www.cegedim-insurance.com/> -
PARIS •  BRISTOL • LILLE • LYON • MARSEILLE • MONTARGIS • NANTES • TOULOUSE • RABAT • VELIZY

**Comment by JuanPerezActivus** [comment]
I created a response file manually from an installation, instead of proceed you can safe the file and use it for unattended and silent install


Kind Regards

Juan


        [cid:image007.jpg@01D496E3.06AA3E70]





Juan Perez
IT Infrastructure and Support, International Division

Brandon Park House • 25 Great George Street • Bristol • BS1 5QT • UK
Tel : +44 (0)117 316 9094
juan.perez@cegedim.com<mailto:juan.perez@cegedim.com>

        [Afficher l'image d'origine] <https://www.linkedin.com/company/cegedim-assurances>              [Afficher l'image d'origine] <https://twitter.com/cegedimis>


Follow us online – www.cegedim-insurance.com<http://www.cegedim-insurance.com/> -
PARIS •  BRISTOL • LILLE • LYON • MARSEILLE • MONTARGIS • NANTES • TOULOUSE • RABAT • VELIZY

**Comment by JuanPerezActivus** [comment]
I copied from my repository to the root of the container


Kind Regards

Juan


        [cid:image007.jpg@01D496E3.1F0C4F30]





Juan Perez
IT Infrastructure and Support, International Division

Brandon Park House • 25 Great George Street • Bristol • BS1 5QT • UK
Tel : +44 (0)117 316 9094
juan.perez@cegedim.com<mailto:juan.perez@cegedim.com>

        [Afficher l'image d'origine] <https://www.linkedin.com/company/cegedim-assurances>              [Afficher l'image d'origine] <https://twitter.com/cegedimis>


Follow us online – www.cegedim-insurance.com<http://www.cegedim-insurance.com/> -
PARIS •  BRISTOL • LILLE • LYON • MARSEILLE • MONTARGIS • NANTES • TOULOUSE • RABAT • VELIZY

**Comment by JuanPerezActivus** [comment]
Left 12c cannot make it work, opened a public repository here

https://github.com/JuanPerezActivus/Oracle-18c-db-in-Windows-docker-container

**Comment by Djelibeybi** [comment]
Oracle products are not supported in Windows containers so this issue is beyond the scope of this repository.

**Comment by JuanPerezActivus** [comment]
> Oracle products are not supported in Windows containers so this issue is beyond the scope of this repository.

A little harsh but I understand, I have just a couple of questions for you working at Oracle:

Is there any support in the roadmap for this? 

Windows and Linux containers do not work very well together in Windows Docker setups, is there not support for Wintel environment in Oracle?

**Comment by JuanPerezActivus** [comment]
I fully disagree with this closure


Kind Regards

Juan

[cid:image007.jpg@01D51080.46BE42B0]





Juan Perez
IT Infrastructure and Support Engineer, International Division

Brandon Park House • 25 Great George Street • Bristol • BS1 5QT • UK
Tel : +44 (0)117 316 9094
juan.perez@cegedim.com<mailto:juan.perez@cegedim.com>
[Afficher l'image d'origine]<https://www.linkedin.com/company/cegedim-assurances>               [Afficher l'image d'origine] <https://twitter.com/cegedimis>


Follow us online – www.cegedim-insurance.com<http://www.cegedim-insurance.com/> -
PARIS •  BRISTOL • LILLE • LYON • MARSEILLE • MONTARGIS • NANTES • TOULOUSE • RABAT • VELIZY

**Comment by Djelibeybi** [comment]
I don't believe this is on our roadmap, but I'll let @gvenzl confirm as the DB product manager.
