### ISSUE TITLE
mkdir: cannot create directory '/u01/oracle/properties': File exists A properties file with the username and password needs to be supplied.

### ISSUE THREAD

**Issue by gcstang** [oracle/docker-images#1057]
When starting my docker container via:

oracle/weblogic:12213-p27117282 is a 12.2.1.3-developer image that has been patched.

docker run -d --restart=always \
	-p 7001:7001 \
	-p 9002:9002  \
	-v `pwd`/domain.properties:/u01/oracle/properties \
	-e ADMINISTRATION_PORT_ENABLED=true \
	-e DOMAIN_NAME=abc_domain \
	oracle/weblogic:12213-p27117282

I receive the aforementioned error:
mkdir: cannot create directory '/u01/oracle/properties': File exists
A properties file with the username and password needs to be supplied.

If I instead start it like this without the properties file and copy it to the container then start it works but a password error is declared.
docker run -d --restart=always \
        -name weblogic \
	-p 7001:7001 \
	-p 9002:9002  \
	-e ADMINISTRATION_PORT_ENABLED=true \
	-e DOMAIN_NAME=abc_domain \
	oracle/weblogic:12213-p27117282

docker cp domain.properties weblogic:/u01/oracle/properties
docker start weblogic

-- domain.properties example --
username=myadminusername
password=Myadm1np399w0rd 

`A properties file with the username and password needs to be supplied.
Domain Home is:  /u01/oracle/user_projects/domains/abc_domain

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

domain_name                 : [abc_domain]
admin_listen_port           : [7001]
domain_path                 : [/u01/oracle/user_projects/domains/abc_domain]
production_mode             : [dev]
admin name                  : [AdminServer]
administration_port_enabled : [true]
administration_port         : [9002]
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/create-wls-domain.py", line 60, in ?
60455: The password must be at least 8 alphanumeric characters with at least one number or special character.
60455: Correct the password.
	at com.oracle.cie.domain.script.jython.WLSTSecurityPrincipal.set(WLSTSecurityPrincipal.java:73)
	at com.oracle.cie.domain.script.jython.WLSTSecurityUser.setPassword(WLSTSecurityUser.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: 60455: Invalid password.
60455: The password must be at least 8 alphanumeric characters with at least one number or special character.
60455: Correct the password.

/u01/oracle/createAndStartEmptyDomain.sh: line 65: /u01/oracle/user_projects/domains/abc_domain/bin/setDomainEnv.sh: No such file or directory
/u01/oracle/createAndStartEmptyDomain.sh: line 69: /u01/oracle/user_projects/domains/abc_domain/startWebLogic.sh: No such file or directory
touch: cannot touch '/u01/oracle/user_projects/domains/abc_domain/servers/AdminServer/logs/AdminServer.log': No such file or directory
tail: cannot open '/u01/oracle/user_projects/domains/abc_domain/servers/AdminServer/logs/AdminServer.log' for reading: No such file or directory`

**Comment by keithdwilliams** [comment]
I am having the same issue, is there an answer?

**Comment by mriccell** [comment]
I will take a look at the permissions when creating the properties file in the image.

**Comment by mriccell** [comment]
Oh I see I need to make it more generic to only create the directory for the properties if it is not already existent.  Let me create a PR to fix this!

**Comment by ankushgarg28794** [comment]
@mriccell , Even i am getting the same error while executing the below command. Please help

[root@localhost 12.2.1.3]# docker run -d -p 8001:8001 -p 9003:9003  -v /home/MyWeblogic/docker-images-master/OracleWebLogic/dockerfiles/12.2.1.3/properties/domain.properties:/u01/oracle/properties -e ADMINISTRATION_PORT_ENABLED=true -e DOMAIN_NAME=base_domain oracle/weblogic:12.2.1.3-developer
7b9dd967234daf40a5843527b046d91e7e52106af870ed35456bc671fabffc70
[root@localhost 12.2.1.3]# docker logs 7b9dd967234daf40a5843527b046d91e7e52106af870ed35456bc671fabffc70
Domain Home is:  /u01/oracle/user_projects/domains/base_domain
mkdir: cannot create directory '/u01/oracle/properties': File exists
A properties file with the username and password needs to be supplied.

**Comment by krishna36** [comment]
This issue is affecting on all webLogic docker containers. I have the same issue.

**Comment by sanagareddy** [comment]
I'm having same issue. 
Domain Home is:  /u01/oracle/user_projects/domains/base_domain
A properties file with the username and password needs to be supplied

**Comment by krishna36** [comment]
I was able to get this to work by following samples..
12213-domain, which has scripts
"We are supplying scripts run_admin_server.sh and run_managed_server.sh to facilitate setting the environment variables defined in the property files and running the admin server and managed server containers."

**Comment by rguptan** [comment]
The Volume needs to be the folder containing the property file.

docker run -d -p 8001:8001 -p 9003:9003 -v /home/MyWeblogic/docker-images-master/OracleWebLogic/dockerfiles/12.2.1.3/properties:/u01/oracle/properties -e ADMINISTRATION_PORT_ENABLED=true -e DOMAIN_NAME=base_domain oracle/weblogic:12.2.1.3-developer
