### ISSUE TITLE
Use hugepages inside database container?

### ISSUE THREAD

**Issue by difu** [oracle/docker-images#1059]
Is it possible to use hugepages inside the database container and run an Oracle DB with USE_LARGE_PAGES=only?

Thanks
Dirk # #

**Comment by gvenzl** [comment]
According to https://superuser.com/questions/1309438/how-to-enable-huge-page-support-in-a-dockerfile and https://stackoverflow.com/questions/34787506/how-to-mount-hugepages-inside-docker you should be able to mount hugepages into the container via `docker run --device=/dev/hugepages:/dev/hugepages`.
From there on, the container and the database inside should be able to just consume them.

@Djelibeybi, do you have any more insights as to how to use hugepages inside a Docker container?

Thx,

**Comment by Djelibeybi** [comment]
@gvenzl nope. :)

**Comment by gvenzl** [comment]
@difu, I will close this issue for now thinking that it has been answered.
If that is not the case, please reopen it.
