### ISSUE TITLE
1221-appdeploy gets autokilled with high BLOCK I/O

### ISSUE THREAD

**Issue by ppora** [oracle/docker-images#106]
Hi,

I have built Weblogic images 1221-domain and 1221-domain-with-resources and both are working fine.
Now when i create appdeploy image based on 1221-domain-with-resources , it builds. But when i run image to deploy ear it get auto killed with high BLOCK I/O.

Docker stat mycontainer is showing block I/O increasing from 10 MB to 13 GB and server is stopping automatically after that.

Same ear file is successfully getting deployed on local WL server.

Pls. guide on how to resolve this.

Thanks

**Comment by brunoborges** [comment]
I will give it a try, but workaround is to merge 1221-domain-with-resources files with 1221-appdeploy files.

**Comment by ppora** [comment]
Looks like there is too much of disk I/O happening...accessing WL console without any ear/war is also generating 80-100MB block I/O , have tried to set logging level to WARNING instead of FINEST in create domain file but didn't help.

**Comment by brunoborges** [comment]
@ppora I've tested it and didn't see any issues. Please provide detailed steps to reproduce the problem. Otherwise I'll close this issue.

**Comment by ppora** [comment]
Hi Bruno..thanks lot for looking into this issue..i figured out issue, issue was with VM memory settings..

You can close this.
