### ISSUE TITLE
checkDBStatus.sh does not work during first startup when deploying as Swarm stack

### ISSUE THREAD

**Issue by marcelo-ochoa** [oracle/docker-images#1060]
When deploying 18c EE/XE using a swarm stack checkDBStatus.sh does not check that dbca is creating the RDBMS, if creation step is long (more than 5"), docker swarm healthcheck think that the container is not healthy and shutdown it, so the creation step never end successful. Stack example:
> version: '3.6'
> services:
>   pc:
>     image: oracle/database:18.4.0-xe
>     hostname: pc
>     volumes:
>       - db_data:/opt/oracle/oradata # persistent oracle database data.
>       - type: tmpfs
>         target: /dev/shm
>         tmpfs:
>           size: 2147483648
>     ports:
>       - 1521:1521
>       - 5500:5500
>     environment:
>       - ORACLE_PWD=Oracle_2018
>     deploy:
>       mode: replicated
>       replicas: 1
>       restart_policy:
>         condition: on-failure
>         max_attempts: 3
>         window: 120s

as a workaround by overriding container healthcheck definition to the above stack during first startup solve the problem, for example:

>     healthcheck:
>       test: exit 0
>       interval: 60s
>       timeout: 3s

once the RDMBS is created container default healthcheck based on checkStatus.sh works OK, so updating the stack without above entry is working.
Modifying checkStatus.sh to see if dbca is running could solve the problem
Best regards, Marcelo.

**Comment by gvenzl** [comment]
HI @marcelo-ochoa, unfortunately there is no way for the script to tell the container runtime that the container is still starting, there is [only a binary decision for `HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#healthcheck) whether it's working or not:

```
The options that can appear before CMD are:

--interval=DURATION (default: 30s)
--timeout=DURATION (default: 30s)
--start-period=DURATION (default: 0s)
--retries=N (default: 3)
```

The one thing that we can do is to increase the startup timeout. Even with a larger timeout, once the healthcheck script returns up and running the container reports that as such.
Would that solution solve your use case?
