### ISSUE TITLE
Unable to launch new container from prebuilt Oracle Docker Image, if provide new name for ORACLE_SID/PDB and provoke error "ORA-01034"

### ISSUE THREAD

**Issue by vtotare-mdsol** [oracle/docker-images#1061]
Detailed Background:-
A) I am successfully able to create Oracle Docker Image for 12.2.0.1 version using github repository -https://github.com/oracle/docker-images

B) As soon as I created image, am able to launch/run Oracle DB by giving customize parameters like ORACLE_SID/PDB and container is running as expected.

C) However, afterwards if I stop and commit container and save that container with respective changes as image. Using below commands...
#docker ps -a - (Find the ID of the container that you would like to move using)
#docker commit <container id> <new image name> - (Commit the changes and save the container to a image using)
#docker save <new image name> > /tmp/<new image name>.tar (Save the image to a tar file which can be used to load it in another host)

D) And then try to run the container on another machine by passing new customize parameters then it failing and getting mentioned error.

Additional Information:-

I followed the steps mentioned in this forum to resolve this issue but no luck..That is removing VOLUME from Dockerfile but still it does not work..
https://github.com/oracle/docker-images/issues/269
https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/prebuiltdb

Hence, can you please look into this issue on high priority and unblock me.

**Comment by vtotare-mdsol** [comment]
Note:- I have comment out "VOLUME" dockerfile as well but still getting below error everytime..

oracle@ip-10-0-0-89:~$ docker run --name oracle12cimage -p 1521:1521 -p 5500:5500 -e ORACLE_SID=medssb01r1 -e ORACLE_PDB=MEDSSB01 -e ORACLE_CHARACTERSET=AL32UTF8 oracle12cimage
ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: aqlIk46SQhU=1

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 26-NOV-2018 15:35:52

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/308b1b2a3643/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                26-NOV-2018 15:35:52
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/308b1b2a3643/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
   CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
   ACTION: Select a listener to be registered or created with the database.
Copying database files
1% complete
13% complete
25% complete
Creating and starting Oracle instance
26% complete
30% complete
31% complete
35% complete
38% complete
39% complete
41% complete
Completing Database Creation
42% complete
43% complete
44% complete
46% complete

47% complete
50% complete
Creating Pluggable Databases
75% complete
Executing Post Configuration Actions
DBCA Operation failed.
Look at the log file "/opt/oracle/cfgtoollogs/dbca/MEDSSB01R1/MEDSSB01.log" for further details.

SQL*Plus: Release 12.2.0.1.0 Production on Mon Nov 26 15:41:56 2018

Copyright (c) 1982, 2016, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL> 
System altered.

SQL>    ALTER PLUGGABLE DATABASE MEDSSB01 SAVE STATE
*
ERROR at line 1:
ORA-65011: Pluggable database MEDSSB01 does not exist.


SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
ls: cannot access MEDSSB01R1/*/: No such file or directory
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/checkDBStatus.sh: line 27: sqlplus: command not found
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
==> /opt/oracle/diag/rdbms/medssb01r1/MEDSSB01R1/trace/alert_MEDSSB01R1.log <==
Shared IO Pool defaulting to 64MB. Trying to get it from Buffer Cache for process 1981.
===========================================================
Dumping current patch information
===========================================================
No patches have been applied
===========================================================
2018-11-26T15:41:56.605629+00:00
ALTER SYSTEM SET control_files='/opt/oracle/oradata/MEDSSB01R1/control01.ctl' SCOPE=SPFILE;
   ALTER PLUGGABLE DATABASE MEDSSB01 SAVE STATE
ORA-65011 signalled during:    ALTER PLUGGABLE DATABASE MEDSSB01 SAVE STATE...

==> /opt/oracle/diag/rdbms/oradocker/ORADOCKER/trace/alert_ORADOCKER.log <==
ALTER DATABASE DISMOUNT
Shutting down archive processes
Archiving is disabled
Completed: ALTER DATABASE DISMOUNT
2018-11-26T15:32:40.657779+00:00
ARCH: Archival disabled due to shutdown: 1089
Shutting down archive processes
Archiving is disabled
2018-11-26T15:32:41.660171+00:00
JIT: pid 2833 requesting stop

==> /opt/oracle/diag/rdbms/medssb01r1/MEDSSB01R1/trace/alert_MEDSSB01R1.log <==
2018-11-26T15:41:57.255611+00:00
Resize operation completed for file# 4, old size 61440K, new size 66560K
2018-11-26T15:41:58.227665+00:00
Resize operation completed for file# 4, old size 66560K, new size 71680K

**Comment by vtotare** [comment]
oracle@ip-10-0-0-89:~$ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1021-aws
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.66GiB
Name: ip-10-0-0-89
ID: XYZP:AXNG:B2AJ:OAPM:YHP3:EPML:4AL4:QPOE:M4RF:VRZ7:AP6P:LLF2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

**Comment by vtotare-mdsol** [comment]
Can someone please help me on this issue.

**Comment by vtotare** [comment]
Thanks @gvenzl for looking into this !

**Comment by gvenzl** [comment]
@vtotare-mdsol, your database creation failed, you will have to look at the log file what went wrong:

```
Executing Post Configuration Actions
DBCA Operation failed.
Look at the log file "/opt/oracle/cfgtoollogs/dbca/MEDSSB01R1/MEDSSB01.log" for further details.
```

**Comment by vtotare-mdsol** [comment]
this is not something with DB, whenever i try to create new database using this SID=MEDSSB01R1 and PDB=MEDSSB01, it gets failed.

Can we have a quick session so can execute the exact issue

**Comment by wallhided** [comment]
excuse me, there are no solution nowadays?

**Comment by gvenzl** [comment]
This is most likely an issue that the `ORACLE_SID` is too long, it can only be up to 8 characters. Ideally `dbca` should not create a database with a SID that is too long but alternatively, the `createDB.sh` script could check for the length of the SID and abort if it is too long.

@yunus-qureshi, @rishabh20, can you please take a look at this?

**Comment by yunus-qureshi** [comment]
@vtotare-mdsol is your issue resolved?
