### ISSUE TITLE
OracleJDE not found

### ISSUE THREAD

**Issue by akshayatuldeshmukh31** [oracle/docker-images#1066]
I am trying to install JD Edwards by following this documentation: https://www.oracle.com/webfolder/technetwork/tutorials/jdedwards/White%20Papers/Deploying%20Containerized%20JD%20Edwards%20EnterpriseOne%20on%20Oracle%20Cloud%20Infrastructure.pdf

I can't find an entry for JD Edwards on this repo. Please help me.

**Comment by mriccell** [comment]
There has never been a JD Edwards image in this repository.  In the white paper which you have included a link  has a section "How to Build JD Edwards EnterpriseOne Docker Images" and describes layering over the WebLogic image which is in this repository.

**Comment by akshayatuldeshmukh31** [comment]
In the same whitepaper at page 64, there is a section for building JDE (JD Edwards):

Build the JDE Base Images
$ cd OracleJDE/dockerfiles
$ ./build‐base‐images.sh

This folder seems to be a part of the repo. Could you tell me where I can get JDE Docker images. I can't find the dockerfiles for provisioning server, AIS server, etc.

**Comment by Djelibeybi** [comment]
I am trying to find the authors of that whitepaper to see why they haven't submitted the images to this repo.

**Comment by noeldcosta** [comment]
The build scripts for JD Edwards referenced in the whitepaper are not yet available on GitHub. Kindly reach out to support to get access to the scripts.
