### ISSUE TITLE
/ORCL: Permission denied - when host directory is mapped to /ORCL

### ISSUE THREAD

**Issue by pcramasamy** [oracle/docker-images#1067]
I have referred issues #439, #736, #783 and also the FAQ. But even after changing the ownership of the host directory to 54321:54321, the /ORCL cannot be accessed:

$ sudo mkdir -p /oradata/db8
$ sudo chown -R 54321:54321 /oradata
$ sudo chmod 777 /oradata/db8
$ sudo docker run -it --name testdb8 -v /oradata/db8:/ORCL store/oracle/database-enterprise:12.2.0.1 ls -al /ORCL
ls: cannot open directory /ORCL: Permission denied

I can create the docker volume with a local directory and run the image without any issue. But wanted to clarify on this one. Anything I am missing here?

**Comment by gvenzl** [comment]
Can it be that SELinux is blocking you accessing `/ORCL`?

**Comment by pcramasamy** [comment]
Yes! chcon -Rt svirt_sandbox_file_t /oradata/db8 resolves it. Thank you!
