### ISSUE TITLE
Enable archivelog and share it as a volume

### ISSUE THREAD

**Issue by xtender** [oracle/docker-images#1069]
Could you enable archivelog by default and mount directoty for archivelogs as a volume, please?

I need it for cross-platform migration of PDB using RMAN restore foreign pdbs

**Comment by gvenzl** [comment]
No, not everybody needs archive logging or wants it and certainly also not the volume associated with it.
If your use case needs archive logging you can turn it on yourself, use a custom setup script, or extend the image to your needs.
