### ISSUE TITLE
Installing Java to oracle docker image and set up

### ISSUE THREAD

**Issue by mattadamson** [oracle/docker-images#1072]
Hi

After using a base image to install oracle within docker I noticed the Java components aren't installed.  What's the best approach to install this post install please? 

I used these files in the installation 

linuxamd64_12102_database_1of2.zip 
linuxamd64_12102_database_2of2.zip 

Many thanks

**Comment by BBKing5x2** [comment]
U mite want too take the file and send it too upir cloud drive then try and uninstall then re install

**Comment by psoares** [comment]
Same issue here. The docs instruct to make sure we download a file called "linuxx64__database.zip", but the release is currently split into 2 different files, making the build script fail with the following error message:

```
COPY failed: stat /var/lib/docker/tmp/docker-builder596911665/oracle-xe-11.2.0-1.0.x86_64.rpm.zip: no such file or directory

ERROR: Oracle Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.
```

The Dockerfile is actually expecting an rpm file...

**Comment by gvenzl** [comment]
Hi @mattadamson, which Java components are you expecting and what do you need them for?
