### ISSUE TITLE
Own Oracle DB Image

### ISSUE THREAD

**Issue by nan140114** [oracle/docker-images#1079]
Hello. 
Is it possible to build my own oracle12.1.0.2-ee  image, push it to my docker hub profile and use it in development and staging environments running on AWS?
There are some License restrictions?

**Comment by Djelibeybi** [comment]
You are not allowed to push any image to the Docker Hub that contains Oracle proprietary binaries. This is not permitted by the license you agreed to when you download the binaries from OTN.
