### ISSUE TITLE
Docker Windows image for Oracle Instant Client 

### ISSUE THREAD

**Issue by ebellumat** [oracle/docker-images#1080]
Im using the image microsoft/aspnet:4.7.2-windowsservercore-ltsc2016 to run a .Net 4.7.2 Application, but i need Oracle Instant Client running on it. Searching here, i only found this Image to Linux Containers. How i can run Oracle Instant Client on Windows based container?

![inigk](https://user-images.githubusercontent.com/26942680/49890173-9499f780-fe2a-11e8-9ab4-100df6fd0e84.png)

**Comment by alokranjan1234** [comment]
@ebellumat did you get any sloution for your problem? I am also facing the same issue

**Comment by ebellumat** [comment]
> @ebellumat did you get any sloution for your problem? I am also facing the same issue

Yes man! Look my repo, i create the docker file to solve this problem.

**Comment by Djelibeybi** [comment]
Unfortunately we cannot publish Windows-based Dockerfiles/images but I'm glad you solved this issue.
