### ISSUE TITLE
OracleFMWInfrstructure: AdministrationServer Container run error

### ISSUE THREAD

**Issue by derfybzh** [oracle/docker-images#1085]
Hi

When I launch the 
docker run -d -p 9001:7001 --network=InfraNET -v $HOST_VOLUME:/u01/oracle/user_projects --name InfraAdminContainer --env-file ./infraDomain.env.list oracle/fmw-infrastructure:12.2.1.3

I run into an error I've changed my infraDomain.env.list to

CONNECTION_STRING=InfraDB:1521/InfraPDB1.us.oracle.com
RCUPREFIX=INFRA6
DB_PASSWORD=MyDBP@sswd123!
DB_USERNAME=sys
ADMIN_PASSWORD=MyWLS@dminPassword123!
DB_SCHEMA_PASSWORD=MyDBPasswd
DOMAIN_NAME=InfraDomain

Password seems to match weblogic security 

https://docs.oracle.com/middleware/1213/wls/SECMG/password_atn.htm#SECMG211

Am I missing something ?

Best Regards

Configuring Domain for first time 
If Domain has already been Configured
Start the Admin and Managed Servers  
=====================================
CONNECTION_STRING=InfraDB:1521/InfraPDB1.us.oracle.com
RCUPREFIX=INFRA6
DOMAIN_NAME=InfraDomain
Loading RCU Phase
=================
CONNECTION_STRING=InfraDB:1521/InfraPDB1.us.oracle.com
RCUPREFIX=INFRA6
DB_PASSWORD=MyDBP@sswd123!
jdbc_url=jdbc:oracle:thin:@InfraDB:1521/InfraPDB1.us.oracle.com
ADMIN_PASSWORD=MyWLS@dminPassword123!
DB_SCHEMA_PASSWORD=MyDBPasswd
DB_USERNAME=sys
DOMAIN_HOME: /u01/oracle/user_projects/domains/InfraDomain
MW_HOME: /u01/oracle
WL_HOME: /u01/oracle/wlserver
ADMIN_USER: weblogic
DOMAIN_ROOT: /u01/oracle/user_projects/domains
DOMAIN HOME: /u01/oracle/user_projects/domains/InfraDomain
Loading SOA RCU into database

Domain Configuration Phase
==========================
2018-12-13T09:38:28.321540200Z 
Initializing WebLogic Scripting Tool (WLST) ...
2018-12-13T09:38:28.330617000Z 
Welcome to WebLogic Server Administration Scripting Shell
2018-12-13T09:38:43.270478600Z 
Type help() for help on available commands
2018-12-13T09:38:43.270489600Z 
/u01/oracle/container-scripts/createInfraDomain.py called with the following sys.argv array:
sys.argv[0] = /u01/oracle/container-scripts/createInfraDomain.py
sys.argv[1] = -oh
sys.argv[2] = /u01/oracle
sys.argv[3] = -jh
sys.argv[4] = /usr/java/default
sys.argv[5] = -parent
sys.argv[6] = /u01/oracle/user_projects/domains
sys.argv[7] = -name
sys.argv[8] = InfraDomain
sys.argv[9] = -user
sys.argv[10] = weblogic
sys.argv[11] = -password
sys.argv[12] = MyWLS@dminPassword123!
sys.argv[13] = -rcuDb
sys.argv[14] = InfraDB:1521/InfraPDB1.us.oracle.com
sys.argv[15] = -rcuPrefix
sys.argv[16] = INFRA6
sys.argv[17] = -rcuSchemaPwd
sys.argv[18] = MyDBPasswd
Creating cluster...
Creating Node Managers...
Creating Servers...
Writing base domain...
Base domain created at /u01/oracle/user_projects/domains/InfraDomain
Extending domain at /u01/oracle/user_projects/domains/InfraDomain
Applying JRF templates...
Extension Templates added
Configuring the Service Table DataSource...
Getting Database Defaults...
Targeting Server Groups...
Set CoherenceClusterSystemResource to defaultCoherenceCluster for server:infra_server1
Set CoherenceClusterSystemResource to defaultCoherenceCluster for cluster:infra_cluster
Set WLS clusters as target of defaultCoherenceCluster:[infra_cluster]
Preparing to update domain...
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 271, in ?
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 60, in createInfraDomain
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 161, in extendDomain
  File "/tmp/WLSTOfflineIni5478757830094901218.py", line 139, in updateDomain
  File "/tmp/WLSTOfflineIni5478757830094901218.py", line 19, in command
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: SecurityContext:
 Domain Name: InfraDomain
 JDBC URL: opss-audit-DBDS:jdbc:oracle:thin:@//InfraDB:1521/INFRAPDB1.US.ORACLE.COM
 JDBC URL: opss-data-source:jdbc:oracle:thin:@//InfraDB:1521/INFRAPDB1.US.ORACLE.COM
 JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
 JNDI Name: opss-data-source:jdbc/OpssDataSource
 Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
 Driver Name: opss-data-source:oracle.jdbc.OracleDriver
 Persistence Type: DATABASE
 Platform: WLS
 Scratch Dir: scratch
 Reconfig Domain: false
 Shared Secret Store: null
 Extension: true
 DisableManagementOperations: falseJDBC Properties: 
user:INFRA6_IAU_APPEND
username:INFRA6_IAU_APPENDJDBC Properties: 
user:INFRA6_OPSS
username:INFRA6_OPSS
64254: Check log for more detail.
null
	at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
	at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2983)
	at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:735)
	at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
2018-12-13T09:39:11.356828800Z 
com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Error updating domain:
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: SecurityContext:
 Domain Name: InfraDomain
 JDBC URL: opss-audit-DBDS:jdbc:oracle:thin:@//InfraDB:1521/INFRAPDB1.US.ORACLE.COM
 JDBC URL: opss-data-source:jdbc:oracle:thin:@//InfraDB:1521/INFRAPDB1.US.ORACLE.COM
 JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
 JNDI Name: opss-data-source:jdbc/OpssDataSource
 Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
 Driver Name: opss-data-source:oracle.jdbc.OracleDriver
 Persistence Type: DATABASE
 Platform: WLS
 Scratch Dir: scratch
 Reconfig Domain: false
 Shared Secret Store: null
 Extension: true
 DisableManagementOperations: falseJDBC Properties: 
user:INFRA6_IAU_APPEND
username:INFRA6_IAU_APPENDJDBC Properties: 
user:INFRA6_OPSS
username:INFRA6_OPSS
64254: Check log for more detail.
null
2018-12-13T09:39:11.356909600Z 
RetVal from Domain creation 1
Domain Creation Failed.. Please check the Domain Logs

**Comment by mriccell** [comment]
Try new image created with PR #1176
