### ISSUE TITLE
error while creating schema on oracle 18.3 docker image

### ISSUE THREAD

**Issue by monojitsaba** [oracle/docker-images#1087]
getting below errors when i login to container on oracle 18.3 image and try to create new schema

# docker exec -it oracle01 /bin/bash
[oracle@85a3d06aa38f oracle]$ sqlplus system/oracle@qadb

SQL*Plus: Release 18.0.0.0.0 - Production on Fri Dec 14 12:07:05 2018
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

Connected to:
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production
Version 18.3.0.0.0

SQL> grant connect, resource to sabamaster identified by sabamaster;
grant connect, resource to sabamaster identified by sabamaster
*
ERROR at line 1:
ORA-65049: Creation of local user or role is not allowed in this container.

SQL> create role saba_connect;
create role saba_connect
            *
ERROR at line 1:
ORA-65096: invalid common user or role name

**Comment by gvenzl** [comment]
You are trying to create a schema in the CDB while only [common users](https://docs.oracle.com/en/database/oracle/oracle-database/18/multi/overview-of-the-multitenant-architecture.html#GUID-3BB161DA-9CC0-4D61-A2C1-5D3662E0DECF) are allowed.

You will have to connect to the PDB and create your schema there.
