### ISSUE TITLE
Database license require for storing Docker Image

### ISSUE THREAD

**Issue by elygre** [oracle/docker-images#1089]
I understand that running Oracle in Docker is licensed exactly the same as running Oracle without docker on the same underlying system. However, it is not clear to me how the Docker image relates to this.

For example, we will run Oracle Database SE2 in Docker on properly licensed (and dimensioned) hardware. Along the way, I'd like to create a Dockerfile and store in a Docker registry for easy installation.

* Do I need to license the Oracle Database for the docker registry computer?
* Where can I find the canonical answer to this question?

Eirik

**Comment by Djelibeybi** [comment]
Unfortunately, we cannot answer licensing questions on GitHub. You'll need to ask your Oracle Sales team who can check with the Oracle Licensing team.
