### ISSUE TITLE
Put this on docker hub

### ISSUE THREAD

**Issue by saily** [oracle/docker-images#109]
Hi Oracle, why not putting these images on docker hub so people do not have to build theirselves? Please setup automated builds for docker hub. Thanks.

**Comment by brunoborges** [comment]
Hi @saily, we are first certifying our products and helping users to build their own images with these quickstart files, gather feedback, establish best practices and optimal default configurations as well customization points. 

We do have though in our roadmap intation to provide pre-built images, but is not our focus right now.

But thanks for your interest. You are not the [first](https://github.com/oracle/docker-images/issues/76) nor the [second](https://github.com/oracle/docker-images/issues/13) to give sign of interest on pre-built images. And I hope we get even more :-)

**Comment by saily** [comment]
Hi @brunoborges. What is your focus on right now?

Acutally we use custom built docker images to test and pre-build all oracle products like OracleDB, SOA appliaction and Commerce on premise. Having maintained images to start from would help a lot.

**Comment by brunoborges** [comment]
Focus is to dockerize even more Oracle technologies.  :-)

We certify and provide support for some products (the ones you see in this repo), but we do not require customers to use specific pre-built images. In fact, customers are allowed to come up with their own images, customizations, and parameters. 

Our recommendation is that you set up an internal Registry Server, and that you build images the way you like, and then you publish internally to share across your dev and ops teams.
