### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by nan140114** [oracle/docker-images#1093]
I set up the oracle image sucessfully, when i try to run a container next error is generated 

https://pastebin.com/4p2GH04K

The error is: 

`oracle_1_f0fff88c0b1d | /opt/oracle/oradata/ has enough space. Required space is 7665 MB , available space is 29285 MB.
oracle_1_f0fff88c0b1d | / has enough space. Required space is 0 MB , available space is 29285 MB.`

i have deleted unused images, containers and volumes, but the error persists. I'm using overlay2 and i have enough space on disk.

I don't understand the message "Required space is 0 MB , available space is 29285 MB".

Thank you.

**Comment by nan140114** [comment]
Inside the docker container the df -h command looks good:

![imagen](https://user-images.githubusercontent.com/5685675/50180565-f8fc0180-02d7-11e9-8c55-3a3ec2910e9c.png)

**Comment by gvenzl** [comment]
Actually, that is not the error.
The error is `ORA-03113: end-of-file on communication channel` but that doesn't give you the reason either. You will have to go into the container and find the trace file under `/opt/oracle/cfgtoollogs/dbca/ORCLCDB/*trc`, that should have the actual error message.

**Comment by nan140114** [comment]
It fails when i run it with another container through Compose, it's a Local Environment issue. I'm going to check my docker configuration, i will post news here, it can be useful for others.

**Comment by nan140114** [comment]
The error was caused, because i was limiting the container assigned memory to 2G. That's all folks!
