### ISSUE TITLE
Database license for ephemeral containers instances

### ISSUE THREAD

**Issue by Ldoppea** [oracle/docker-images#1096]
Hi,

I would like to integrate an Oracle Docker Image in a Continuous Integration server that regularly instantiates the docker container, populates the database with fake data, executes all our unit and integration tests and then destroy the container.

What are the licensing requirements for this use case?

Thanks

**Comment by Djelibeybi** [comment]
You should review the OTN License on the Software Download page for Oracle Database 18c: https://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html
