### ISSUE TITLE
Refused to connect to https://locahost:5500/em - 18.3c

### ISSUE THREAD

**Issue by Biggo6** [oracle/docker-images#1104]
I have managed to build oracle 18.3 ee on my server X.X.X.X, i.e 182.1.1.23,

But when i access https://182.1.1.23:5500/em it responses : refused to connect

**Comment by gvenzl** [comment]
Hi @Biggo6, can you share the `docker run` command, please?

**Comment by gvenzl** [comment]
Closing due to lack of response.

**Comment by dcdourado** [comment]
@gvenzl 
I'm having the same issue, but locally (https://localhost:5500/em) using v18.4.0

I'm using docker-compose as described:
`oracle:
    build: ./oracle
    ports:
      - "5500:5500"
      - "1521:1521"
    volumes:
      - "./oracle/oradata:/opt/oracle/oradata"
    environment:
      - ORACLE_PWD=${DEFAULT_PASSWORD}`

Default Dockerfile
