### ISSUE TITLE
COPY failed: stat /var/lib/docker/tmp/docker-builder123592292/LINUX.X64_180000_db_home.zip: no such file or directory

### ISSUE THREAD

**Issue by sudhakarchola** [oracle/docker-images#1105]
**Sudhakars-MacBook-Pro:dockerfiles sudhakarmani$ ./buildDockerImage.sh –v 11.2.0.2 –x –i

While executing the above command, it is installing the 18C instead of 11G XE..**

```
Ignored MD5 sum, 'md5sum' command not available.
==========================
DOCKER info:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: TMU6:IOG2:NXPR:NVHX:XS3Y:32L3:GEWS:WVGZ:FXML:7OMF:TDZS:4DRY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 50
 System Time: 2019-01-06T17:27:08.0351177Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

==========================
Building image 'oracle/database:18.3.0-' ...
Sending build context to Docker daemon  48.13kB

Removing intermediate container 8ba7b6108c13
 ---> 28da9bb08798
Step 8/24 : FROM base AS builder
 ---> 28da9bb08798
Step 9/24 : ARG DB_EDITION
 ---> Running in 37c45ef1cf39
Removing intermediate container 37c45ef1cf39
 ---> 2bbb451ee834
Step 10/24 : RUN yum -y install unzip
 ---> Running in 11d77603c473
Loaded plugins: ovl
Package unzip-6.0-19.el7.x86_64 already installed and latest version
Nothing to do
Removing intermediate container 11d77603c473
 ---> fe28bbf48750
Step 11/24 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
COPY failed: stat /var/lib/docker/tmp/docker-builder123592292/LINUX.X64_180000_db_home.zip: no such file or directory

ERROR: Oracle Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.
```

**Comment by ynixon** [comment]
I has the same problem and fixed it this way:
**Dockerfile:**
old:
`COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/`
new:
`RUN mkdir -p $INSTALL_DIR && chown oracle:dba $INSTALL_DIR
ADD --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/`
**installDBBinaries.sh**
old:
`mv $INSTALL_DIR/$INSTALL_FILE_1 $ORACLE_HOME/ && \
unzip $INSTALL_FILE_1 && \
rm $INSTALL_FILE_1    && \`
new:
`unzip $INSTALL_DIR/$INSTALL_FILE_1 -d $ORACLE_HOME/ && \
rm $INSTALL_DIR/$INSTALL_FILE_1    && \`

**Comment by gvenzl** [comment]
@subhashsutrave,

Your issue is that the `–` character is not the same as the `-` character.
Look:
`–` --> yours
`-` --> when typed on the keyboard.
See how the keyboard character is slightly smaller.

My guess is that you have copy/pasted this once into Microsoft Word, which has the annoying habit of expanding these dashes that is a different character to the shell.

Please try and type the exact command above and you will see that the script is working.

**Comment by broth-eu** [comment]
@gvenzl thank you. That did the trick. :-)

**Comment by ayanendude** [comment]
Hi @gvenzl @broth-eu ,

I am trying to build with below command.
./buildDockerImage.sh -v 18.3.0 -s

I am getting below error:
Step 12/25 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
COPY failed: stat /var/lib/docker/tmp/docker-builder271646069/LINUX.X64_180000_db_home.zip: no such file or directory

Which "-" do you suggest to change in Dockerfile? I tried ynixon's suggestion, but did not work for me.

**Comment by CodeSmolder** [comment]
Hi @ayanendude,

It is not the - in the Dockerfile, it is the - used for the arguments when calling buildDockerImage.sh

(e.g. if you copy and paste the buildDockerImage call form the article [Create and use a Docker container with Oracle XE on macOS](https://www.esentri.com/create-and-use-a-docker-container-with-oracle-xe-on-macos/) the wrong - character will be used.)

**Comment by TrinitaDewanti** [comment]
I had the same and it cost me the whole day, finally I found this article, thanks a lot guys !

**Comment by luizfernandoandrade1** [comment]
I'm using quarkus-container-image-docker and I have had the same problem. 
I just changed my Dockerfile to use baseDir
Dockerfile before
    COPY /zipped-ps.tar.gz /zipped-ps.tar.gz
Dockerfile after
    COPY ${basedir}/src/main/docker/zipped-ps.tar.gz /zipped-ps.tar.gz

Using the full path will help your plugin to find the file you need to COPY or ADD

**Comment by victormwenda** [comment]
Having the same issue:

So first running the command :

`./buildDockerImage.sh -v 19.3.0 -s`

Gives: 

```
Checking Docker version.
Checking if required packages are present and valid...
md5sum: LINUX.X64_193000_db_home.zip: No such file or directory
LINUX.X64_193000_db_home.zip: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 19.3.0.
```
When I ignore MD5SUM Check: 

`./buildDockerImage.sh -v 19.3.0 -s -i`

```
Checking Docker version.
Ignored MD5 checksum.
==========================
DOCKER info:

... Various Processes are performed as expected and then ....

Complete!
Removing intermediate container 215644422e51
 ---> 5ead39892f6c
Step 8/21 : FROM base AS builder
 ---> 5ead39892f6c
Step 9/21 : ARG DB_EDITION
 ---> Running in 4bff46b8a9eb
Removing intermediate container 4bff46b8a9eb
 ---> 755b45ac73cf
Step 10/21 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
COPY failed: stat /var/lib/docker/tmp/docker-builder899436003/LINUX.X64_193000_db_home.zip: no such file or directory

ERROR: Oracle Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.
```

**Comment by victormwenda** [comment]
Found a way out.

Download the Image : e.g` LINUX.X64_193000_db_home.zip` from Oracle Downloads (`https://www.oracle.com/database/technologies/oracle-database-software-downloads.html#19c`) - Pick the right file, .zip not .rpm

Copy this file in the directory 
`/docker-images/OracleDatabase/SingleInstance/dockerfiles/19.3.0`

Or based on the version you are building.

And rebuild your image now: 

`./buildDockerImage.sh -v 19.3.0 -s`

if all goes well, you should get 
```

Oracle Database Docker Image for 'se2' version 19.3.0 is ready to be extended: 
    
    --> oracle/database:19.3.0-se2

  Build completed in 438 seconds
```

**Comment by vinok88** [comment]
> https://www.oracle.com/database/technologies/oracle-database-software-downloads.html#19c

I'm getting this even with the 19.3 zip archive. Did you rename the zip?

**Comment by chengshifan** [comment]
@victormwenda 
Thank you. I have the same issue with you.
I will try your way.

**Comment by AjayKumaraj** [comment]
Step 11/22 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_FILE_2 $INSTALL_RSP $PERL_INSTALL_FILE $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
COPY failed: stat /var/lib/docker/tmp/docker-builder284152928/linuxamd64_12102_database_1of2.zip: no such file or directory

**./buildDockerImage.sh -v 12.1.0.2 -e -i**

Tried Above steps didn't help out

**Comment by gmanakavalan** [comment]
> Found a way out.
> 
> Download the Image : e.g` LINUX.X64_193000_db_home.zip` from Oracle Downloads (`https://www.oracle.com/database/technologies/oracle-database-software-downloads.html#19c`) - Pick the right file, .zip not .rpm
> 
> Copy this file in the directory
> `/docker-images/OracleDatabase/SingleInstance/dockerfiles/19.3.0`
> 
> Or based on the version you are building.
> 
> And rebuild your image now:
> 
> `./buildDockerImage.sh -v 19.3.0 -s`
> 
> if all goes well, you should get
> 
> ```
> 
> Oracle Database Docker Image for 'se2' version 19.3.0 is ready to be extended: 
>     
>     --> oracle/database:19.3.0-se2
> 
>   Build completed in 438 seconds
> ```

This worked for me. better download and place it there.

**Comment by muhammad-asn** [comment]
Awesome thank you
