### ISSUE TITLE
Unable to get Credentials to download Patch 

### ISSUE THREAD

**Issue by mommaroodles** [oracle/docker-images#1108]
Forgive me for using this platform to reach out, but I might be missing something - am I supposed to be a member of part of a paid Workshop or be a customer of a commercial product in order to be able to download the patches? I have registered at Oracle.  I just happened to stumble across this today.

**Comment by mriccell** [comment]
@mommaroodles  do you need the patches to run the WebLogic Kubernetes Operator 2.0?

**Comment by mommaroodles** [comment]
Hi Monica - I found all the files here - I just wanted to go through all the tutorials - I'm still learning - Unfortunately I don't have an Oracle product or paid support.
