### ISSUE TITLE
samples\1213-domain: nohup: failed to run command 'startNodeManager.sh': No such file or directory

### ISSUE THREAD

**Issue by askfor** [oracle/docker-images#1113]
https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/1213-domain/container-scripts/createServer.sh#L18

It will work if I change this line to 

nohup /u01/oracle/user_projects/domains/base_domain/bin/startNodeManager.sh > log.nm 2>&1 &

**Comment by mriccell** [comment]
@askfor Thanks for the input I will look into this and create a PR.

**Comment by mriccell** [comment]
Corrected, thanks for the input.
