### ISSUE TITLE
Weblogic Docker Container exits due to Domain Write Error

### ISSUE THREAD

**Issue by chayzgithub** [oracle/docker-images#1119]
Hello Weblogic Docker Team,

I am trying to run the Weblogic Downloaded 12213 domain Container in a RHEL platform (via vargrant) on my mac from the link below

https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain

After I execute the **command**

docker run -d --name wlsadmin --hostname wlsadmin -p 9001:9001 --env-file ./container-scripts/domain.properties -e ADMIN_PASSWORD=***** -v $PWD:/u01/oracle/user_projects 12213domain:users

Domain Home is:  /u01/oracle/user_projects/domains/base_domain
Domain Name is:  base_domain
      ----> 'weblogic' admin password: netcrkD0cker!
Initializing WebLogic Scripting Tool (WLST) ...
Welcome to WebLogic Server Administration Scripting Shell
Type help() for help on available commands
domain_name     : [base_domain]
admin name      : [AdminServer]
admin_port      : [9001]
cluster_name    : [DockerCluster]
domain_path     : [/u01/oracle/user_projects/domains/base_domain]
production_mode : [dev]
com.oracle.cie.domain.script.ScriptException: 60308: **Domain location not writable.**
60308: The domain location does not have write permission.
60308: Correct permissions or select different domain location.
	at com.oracle.cie.domain.script.ScriptExecutor.writeDomain(ScriptExecutor.java:2035)

I get the following error and the container simply exits. I have **verified the write permissions** on the directory specified in the -v value AND also the GID and UI which matched with the container's Oracle User ID/GID of **1000**.

Please let me know what should be done and I am stuck here for last three days and it has become a showstopper for my work.

I appreciate your help.

Thanks
Chad

**Comment by mriccell** [comment]
@chayzgithub If there are not the correct permission then WLST is encountering an error silently.  I will change the WLST script to catch the error.
All processes in containers that contain WebLogic Server instances run with user ID 1000 and group ID 1000. Proper permissions need to be set to the external  shared directory (volume) to make sure that user ID 1000 and group ID 1000 have read and write permission to the volume. 
I hope this blog helps you https://blogs.oracle.com/weblogicserver/docker-volumes-in-weblogic.
Please let me know if you still encounter the problem after adjusting owner and permissions.
Thanks
Monica

**Comment by rmaroldo-idexx** [comment]
Hi Weblogic Docker Team,
I'm encountering the same host permission issue on AWS cloud. AWS host image is built with default user ID (ec2-user) gid=1000(ec2-user) groups=1000.  Creating oracle ID on host with different UID/GID doesn't solve container permissions problem, nor does setting 777 directory permissions or ownership to oracle user. Also tried setting SELinux mode to 'permissive' without success. Do you have any suggestions on a workaround?
Thanks
Bob

**Comment by Djelibeybi** [comment]
That's weird, because the `oracle` user has the same UID/GID inside the container:

```
# id oracle
uid=1000(oracle) gid=1000(oracle) groups=1000(oracle)
```

This should work without any issue if the `ec2-user` has the same uid/gid.

**Comment by rmaroldo-idexx** [comment]
I changed host directory owner to ec2-user(1000) and it works now. I got hung up thinking the UID/GID had to be oracle(1000):oracle(1000) on the host. Thanks for pulling me out of my rut.
Bob

**Comment by Djelibeybi** [comment]
You're welcome. For others watching: as long as the uid/gid are the same, the actual username on host/container don't have to match. They're purely for readability purposes.
