### ISSUE TITLE
Unable start 12213-domain-home-in-image

### ISSUE THREAD

**Issue by jeejeejango** [oracle/docker-images#1122]
Hi WebLogic Team,

I have follow the sample/12213-domain-home-in-image to create and run the weblogic successfully. When I stop the wlsadmin or MS1/MS2 and try to start it again next time, it's not starting. I didn't find anything in the logs, and I assume it's missing the startup commands or unable to find the docker-run/domain.properties?

Thank you.

**Comment by mriccell** [comment]
are you invoking the same docker run command?  docker run -d --name MS1 --link wlsadmin:wlsadmin -p 8001:8001 \
      -v <HOST DIRECTORY TO PROPERTIES FILE>/properties/docker-run:/u01/oracle/properties \
      -e MANAGED_SERV_NAME=managed-server1 12213-domain-home-in-image startManagedServer.sh   
These images are used in our kubernetes project to start/stop/re-start pods with these containers.

**Comment by mriccell** [comment]
Are you just stopping the the container or are you killing the container?  Are you using the same docker run commands to restart the servers?

**Comment by mriccell** [comment]
Lack of response
