### ISSUE TITLE
Error when trying to build OracleRestDataServices

### ISSUE THREAD

**Issue by doberkofler** [oracle/docker-images#1123]
When trying to build the OracleRestDataServices image I get the following error message:
```
Building image 'oracle/restdataservices:18.4.0' ...
Sending build context to Docker daemon   59.8MB
Step 1/10 : FROM oracle/serverjre:8
pull access denied for oracle/serverjre, repository does not exist or may require 'docker login'
There was an error building the image.
```
I am sure to be logged in but I also cannot find an image `oracle/serverjre` when searching for it in the registry.

**Comment by gvenzl** [comment]
@doberkofler, please see the [ReadMe](https://github.com/oracle/docker-images/blob/master/OracleRestDataServices/README.md):

>Building Oracle REST Data Services Install Images
>IMPORTANT: You will have to provide the installation binaries of ORDS and put them into the dockerfiles folder. You only need to provide the binaries for the version you are going to install. The binaries can be downloaded from the Oracle Technology Network. Note that you must not uncompress the binaries. The script will handle that for you and fail if you uncompress them manually!

>The image builds on top of the oracle/serverjre:8 image which is also provided in this repository, see OracleJava. You will first have to build the oracle/serverjre:8 image before you can build this image!

You have to build the oracle/serverjre:8 image from the Dockerfile in this repository first.

**Comment by doberkofler** [comment]
I overlooked this part: 

> The image builds on top of the oracle/serverjre:8 image which is also provided in this repository, see OracleJava. You will first have to build the oracle/serverjre:8 image before you can build this image!

Thank you!
