### ISSUE TITLE
Oracle Database RAC Create Oracle Connection Manager Image failed (18.3)

### ISSUE THREAD

**Issue by scottwan** [oracle/docker-images#1124]
when I create Oracle Connection Manager Image get the erro information as below:
---------------------------------------------------------------------------------------------
Starting Oracle Universal Installer...

Checking Temp space: must be greater than 415 MB.   Actual 198475 MB    Passed
Checking swap space: must be greater than 150 MB.   Actual 2047 MB    Passed
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2019-01-23_01-16-45AM. Please wait ...[WARNING] [INS-13014] Target environment does not meet some optional requirements.
   CAUSE: Some of the optional prerequisites are not met. See logs for details. installActions2019-01-23_01-16-45AM.log
   ACTION: Identify the list of failed prerequisite checks from the log: installActions2019-01-23_01-16-45AM.log. Then either from the log file or from installation manual find the appropriate configuration to meet the prerequisites and fix it manually.
The response file for this session can be found at:
 /u01/app/oracle/product/18.3.0/client_1/install/response/client_2019-01-23_01-16-45AM.rsp

You can find the log of this install session at:
 /u01/app/oraInventory/logs/installActions2019-01-23_01-16-45AM.log
The installation of Oracle Client 18c was successful.
Please check '/u01/app/oraInventory/logs/silentInstall2019-01-23_01-16-45AM.log' for more details.

As a root user, execute the following script(s):
        1. /u01/app/oraInventory/orainstRoot.sh
        2. /u01/app/oracle/product/18.3.0/client_1/root.sh

Successfully Setup Software with warning(s).
Removing intermediate container 39a5d1631f28
The command '/bin/sh -c $INSTALL_DIR/install/$INSTALL_DB_BINARIES_FILE EE' returned a non-zero code: 6
There was an error building the image.
[root@rac01 dockerfiles]#
[root@rac01 dockerfiles]# docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
<none>                      <none>              974c8b1a1612        37 minutes ago      3.13GB
[MobaXterm_root@rac01docker-imagesOracleDatabaseRACOracleConnectionManagerdockerfiles_20190123_095238.txt](https://github.com/oracle/docker-images/files/2785434/MobaXterm_root%40rac01docker-imagesOracleDatabaseRACOracleConnectionManagerdockerfiles_20190123_095238.txt)

the whole screen log is attached.

**Comment by scottwan** [comment]
# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

**Comment by scottwan** [comment]
`# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
`

**Comment by scottwan** [comment]
`# cat /etc/os-release`
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

**Comment by scottwan** [comment]
`# docker info`
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.78GiB
Name: rac01
ID: BEYC:VJBX:GS54:GIY4:OZO2:P62G:ULYQ:4TFG:U4Y7:JY7T:KU47:YHND
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 com.docker.security.seccomp=enabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Unlicensed Enterprise Engine

**Comment by scottwan** [comment]
> # docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                     PORTS               NAMES
43c3301d0f29        9fc1a3f5b852                       "/bin/sh -c '$INSTAL…"   7 minutes ago       Exited (6) 2 minutes ago                       silly_raman

**Comment by psaini79** [comment]
I looked at it and it seems you have kernel version "3.10.0-693.11.6.el7.x86_64". Please try on UEK4 as RAC on docker will work only on UEK4.
