### ISSUE TITLE
OracleDatabase/SingleInstance/samples/prebuiltdb: Unable to commit a container that has been stopped

### ISSUE THREAD

**Issue by doberkofler** [oracle/docker-images#1127]
The example in `docker-images/OracleDatabase/SingleInstance/samples/prebuiltdb` first stops the container and then attempts to commit it.
This does not seem to be possible as the error message `Error response from daemon: No such container: oracle-build` suggests.

**Comment by gvenzl** [comment]
Hi @doberkofler,

Can you provide the output of the commands that you have performed, please?

**Comment by doberkofler** [comment]
Again a mistake on my site.
I forgot to comment out the VOLUME in the Dockerfile.
Sorry for bothering you!
