### ISSUE TITLE
error in resolving yum running dockerfile oracle 18.3

### ISSUE THREAD

**Issue by monojitsaba** [oracle/docker-images#1133]
Getting this error while using yum install inside dockerfile oracle 18.3

Loaded plugins: ovl
https://yum.oracle.com/repo/OracleLinux/OL7/UEKR4/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: yum.oracle.com; Unknown error"
Trying other mirror.

 One of the configured repositories failed (Latest Unbreakable Enterprise Kernel Release 4 for Oracle Linux 7Server (x86_64)),

**Comment by gvenzl** [comment]
Your container doesn't have access to the internet, hence why it cannot resolve host `yum.oracle.com`. Please make sure that your container has access to the internet.

**Comment by monjurmorshed793** [comment]
I was trying to build docker image with the following command.
`sudo ./buildDockerImage.sh -v 18.3.0 -e`
But, was getting the error. Is there any way to connect the internet? Or should I need to modify anything in buildDockerImage.sh file? Thanks

**Comment by monojitsaba** [comment]
What is the error? 
Any docker container should have internet access by default if your host machine has internet. Or else u can add  net.ipv4.ip_forward=1 to /etc/sysctl.conf and try running again.

**Comment by monjurmorshed793** [comment]
Okay, I am posting the detailed error log. Please note, I added net.ipv4.ip_forward=1, but, still getting the error. 
```
Step 7/24 : RUN chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE &&     rm -rf $INSTALL_DIR
 ---> Running in 54fbe2831142
Loaded plugins: ovl
https://yum.oracle.com/repo/OracleLinux/OL7/UEKR4/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: yum.oracle.com; Unknown error"
Trying other mirror.


 One of the configured repositories failed (Latest Unbreakable Enterprise Kernel Release 4 for Oracle Linux 7Server (x86_64)),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=ol7_UEKR4 ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable ol7_UEKR4
        or
            subscription-manager repos --disable=ol7_UEKR4

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=ol7_UEKR4.skip_if_unavailable=true

failure: repodata/repomd.xml from ol7_UEKR4: [Errno 256] No more mirrors to try.
https://yum.oracle.com/repo/OracleLinux/OL7/UEKR4/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: yum.oracle.com; Unknown error"
Removing intermediate container 54fbe2831142
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE &&     rm -rf $INSTALL_DIR' returned a non-zero code: 1

ERROR: Oracle Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.
```

**Comment by hohwille** [comment]
> Your container doesn't have access to the internet, hence why it cannot resolve host yum.oracle.com. Please make sure that your container has access to the internet.

This is not the reason for the error. If docker came to this point he had already downloaded various updates from the internet.

**Comment by hohwille** [comment]
FYI: I initially had the same error. Now its gone but I still get:
```
Failed to get D-Bus connection: Operation not permitted
...
failed to link /usr/share/man/man1/ksh.1.gz -> /etc/alternatives/ksh-man: No such file or directory
...
Step 11/24 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
COPY failed: stat /var/lib/docker/tmp/docker-builder872784679/LINUX.X64_180000_db_home.zip: no such file or directory

ERROR: Oracle Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.
```

Does not seem to be very robust.
I used this one instead:
https://github.com/fuzziebrain/docker-oracle-xe
Might be unoffical but works like a charm.

**Comment by kaessajidi** [comment]
In my case restarting docker service solved the issue 

sudo service docker restart

**Comment by koshyvarghese** [comment]
Was the issue resolved? I am also facing the same issue...Restarting the docker service did not help....

**Comment by brunocampos01** [comment]
> In my case restarting docker service solved the issue
> 
> sudo service docker restart

In my case (19.3) resolved !
