### ISSUE TITLE
OracleFMWInfrastructure 12.2.1.3 startManagedServer.sh hard code domain name

### ISSUE THREAD

**Issue by xiancao** [oracle/docker-images#1136]
In docker-images/OracleFMWInfrastructure/dockerfiles/12.2.1.3/container-scripts/startManagedServer.sh, it hard-codes the DOMAIN_HOME as:
export DOMAIN_HOME="/u01/oracle/user_projects/domains/InfraDomain" 

If I set different domain name other than "InfraDomain" in infraServer.env.list, the managed server will not be started. 

We need to change this to:

export DOMAIN_NAME=$DOMAIN_NAME
export DOMAIN_HOME="/u01/oracle/user_projects/domains/$DOMAIN_NAME"

**Comment by mriccell** [comment]
All properties are now customizable with PR #1176
