### ISSUE TITLE
java.lang.IllegalArgumentException: ONS configuration - Error while adding Oracle DB to Weblogic 12.2.1.3

### ISSUE THREAD

**Issue by RaghuTrivandrum** [oracle/docker-images#1139]
Hi,

When I try to create a new JDBC connection(Oracle DB) from Weblogic 12.2.1.3, I receive the below error.

Error:
java.lang.IllegalArgumentException: ONS configuration

Docker images used:
container-registry.oracle.com/middleware/weblogic:12.2.1.3
container-registry.oracle.com/middleware/weblogic:12.2.1.3-190111

I appreciate any suggestions to resolve it

Thanks

**Comment by anuj1790** [comment]
What I did was to modify the config_internal.sh to include -Doracle.jdbc.fanEnabled=false
