### ISSUE TITLE
 OracleDatabase/SingleInstance/dockerfiles/12.1.0.1 dockerfiles removed or replaced by 12.1.0.2

### ISSUE THREAD

**Issue by yanntoque** [oracle/docker-images#1150]
In the OracleDatabase/SingleInstance/README.md, it is mentionned that dockerfiles are provided for the : 
- **12.1.0.1** Oracle Database 12c Release 1 Enterprise Edition and Standard Edition 2

But, there are only dockerfiles for the **12.1.0.2** Oracle Database 12c Release 1 Enterprise Edition and Standard Edition 2.

**Comment by gvenzl** [comment]
PR #1151 merged, thank you very much!
