### ISSUE TITLE
pod/admin-server status is ErrImageNeverPull

### ISSUE THREAD

**Issue by grglzrv** [oracle/docker-images#1154]
Hello, 

I ama trying to deploy Weblogic from  wls-k8s-domain image that I've created, I ran these commands:

[vagrant@k8s1 wls-k8s-domain]$ kubectl create -f  k8s/secrets.yml
secret/wlsecret created
[vagrant@k8s1 wls-k8s-domain]$ kubectl create -f  k8s/pv.yml
persistentvolume/pv1 created
persistentvolume/pv2 created
persistentvolume/pv3 created
[vagrant@k8s1 wls-k8s-domain]$ kubectl create -f  k8s/pvc.yml
persistentvolumeclaim/wlserver-pvc-1 created
persistentvolumeclaim/wlserver-pvc-2 created
[vagrant@k8s1 wls-k8s-domain]$ kubectl create -f  k8s/wls-admin.yml
deployment.apps/admin-server created
service/admin-server created
[vagrant@k8s1 wls-k8s-domain]$ kubectl create -f  k8s/wls-stateful.yml
statefulset.apps/managed-server created
service/wls-subdomain created
service/wls-service created
[vagrant@k8s1 wls-k8s-domain]$ kubectl get all
NAME                                READY   STATUS              RESTARTS   AGE
pod/admin-server-654cc56ccd-68pst   0/1     ErrImageNeverPull   0          10s
pod/managed-server-0                0/1     ErrImageNeverPull   0          6s

NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/admin-server    NodePort    10.100.175.10   <none>        8001:30007/TCP   10s
service/kubernetes      ClusterIP   10.96.0.1       <none>        443/TCP          3h8m
service/wls-service     NodePort    10.98.248.195   <none>        8011:30009/TCP   6s
service/wls-subdomain   ClusterIP   None            <none>        8011/TCP         6s

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/admin-server   0/1     1            0           10s

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/admin-server-654cc56ccd   1         1         0       10s

NAME                              READY   AGE
statefulset.apps/managed-server   0/2     6s
[vagrant@k8s1 wls-k8s-domain]$ kubectl logs -f pod/admin-server-654cc56ccd-68pst
Error from server (BadRequest): container "admin-server" in pod "admin-server-654cc56ccd-68pst" is waiting to start: ErrImageNeverPull
[vagrant@k8s1 wls-k8s-domain]$

I saw that maybe I should to edit  wls-k8s-domain/k8s/pv.yml 
 hostPath:
    path: "<localpath1>"
  #nfs:
    #server: <nfs_server_ip>
    #path: <shared_path>

 hostPath:
    path: "<localpath2>"
  #nfs:
    #server: <nfs_server_ip> 
    #path: <shared_path> 
 hostPath:
    path: "<localpath3>"
  #nfs:
    #server: <nfs_server_ip> 
    #path: <shared_path> 

maybe I need to remove the created pv pods, then to modify pv.yml file ..

So, Could you please help me how to setup it or what kinda value to put for "path" if I should remove the comment #nfs and what   kinda value to put for "server:" and "path:" under "nfs:" ? 
Also I am wondering if pv.yml is related with this problem "ErrImageNeverPull"

Thank you very much in advance for your cooperation.

**Comment by mriccell** [comment]
@grglzrv the WebLogic team has created an Operator to help deploying a weblogic domain in Kubernetes.  I would direct you to that project  https://github.com/oracle/weblogic-kubernetes-operator to get started please take a look at the quick start guide https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/quickstart.md.  The quick start guide is based on the sample 12213-domain-home-in-image.  We have a public slack channel that you can register and ask question directly to the team https://weblogic-slack-inviter.herokuapp.com/.
The wls-k8s-domain was one of our first samples of running WebLogic on Kubernetes and we have evolved from that time.
Thanks
Monica

**Comment by grglzrv** [comment]
Hi Monica,

I solved my issue as changed the value ImagePullPolicy to "IfNotPresent"
and push my local images to my docker hub repo,  then put the image name
from my docker hub repo into .yml file. That is it.

I know for the WL operator, but I wanted to create my own WL docker images
for K8s.

Regards,
G.Lazarov

На нд, 3.03.2019 г., 7:44 Monica Riccelli <notifications@github.com> написа:

**Comment by vggarg96** [comment]
why can we use the local docker images??? I don't want to push the images to docker hub.
I try `ImagePullPolicy: IfNotPresent` and `ImagePullPolicy: Never` 
I have used both and get the `errimageneverpull` error in my pods description.
Why it is always trying to pull the images even it is present locally?????????

**Comment by rjeberhard** [comment]
@vggarg96, we'll need some more information to assist. There are lots of distributions of Kubernetes. Some have visibility to the local Docker repository and some do not. You do not have to push your images to Docker Hub or to any public repository, but you do need to make sure that your images are visible to your Kubernetes worker nodes. Often the easiest way to do this is to push your images to a public or private registry; however, you can also copy images using Docker save/load. Where are your Kubernetes worker nodes and what distribution are you using?
