### ISSUE TITLE
jdbc connection string not working inside docker container 18c

### ISSUE THREAD

**Issue by monojitsaba** [oracle/docker-images#1159]
I am trying to connect database to java web application using jdbc connection string inside docker container 18c, tried "jdbc:oracle:thin:@172.17.0.2:1521:frsh" and "jdbc:oracle:thin:@localhost:1521:frsh"
but its giving error 
[sql] java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 
My listener.ora looks like

LISTENER =
(DESCRIPTION_LIST =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1))
    (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
  )
)

DEDICATED_THROUGH_BROKER_LISTENER=ON
DIAG_ADR_ENABLED = off

and tnsnames.ora looks like

FRSH1=localhost:1521/FRSH1
FRSH=
(DESCRIPTION =
  (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
  (CONNECT_DATA =
    (SERVER = DEDICATED)
    (SERVICE_NAME = FRSH)
  )
)

and /etc/hosts looks like

127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      4a125243bc08

My sid is frsh and i can sqlplus <schema_name>/<schema_password>@frsh  and run queries.

**Comment by gvenzl** [comment]
Hi @monojitsaba,

I think your issue is that you connect to the SID, not the service.
Please change the `:` to a `/` in your JDBC connect string: `jdbc:oracle:thin:@localhost:1521/frsh`

**Comment by alecarlosjesus** [comment]
Amazing!!
Thx bro!!!
Still helping the needy!
