### ISSUE TITLE
12213-domain-home-in-image-wdt has empty war

### ISSUE THREAD

**Issue by jnarisant** [oracle/docker-images#1163]
The simple-app war deployed via the https://github.com/oracle/weblogic-kubernetes-operator quickstart pointed at 12213-domain-home-in-image-wdt is empty (save for a manifest). 

It looks to be because the script runs the build from the local directory (in this case .../weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image) and the build-archive.sh file does not cd before building, so the expansion of simple-app/* is empty. See:
`${JAVA_HOME}/bin/jar cvf ${scriptDir}/archive/wlsdeploy/applications/simple-app.war -C ${scriptDir} simple-app/* `

An option seems to be:
`${JAVA_HOME}/bin/jar cvf ${scriptDir}/archive/wlsdeploy/applications/simple-app.war -C ${scriptDir}/simple-app .`

**Comment by mriccell** [comment]
@CarolynRountree could you comment
