### ISSUE TITLE
ERROR : untar DB bits failed for store/oracle/database-enterprise:12.2.0.1

### ISSUE THREAD

**Issue by bkotos** [oracle/docker-images#1165]
Hello,

I am trying to run **Oracle Database 12c Enterprise Edition** using the official docker image provided by Oracle.  Following the instructions shown on Docker Hub after [checking out the image](https://hub.docker.com/_/oracle-database-enterprise-edition), I get the following error:
```bash
ERROR : untar DB bits failed, please check log /home/oracle/setup/log/untarDB.log for details!
```

I run into this issue when using the `12.2.0.1` image.  However, the `12.1.0.2` image works fine with a few non-fatal errors.  See my logs below.  My commands intentionally omit the `-d` flag for debugging purposes.

---
Failed output with `12.2.0.1` image:
```
bkotos@bkotos-linux-desktop:~/Projects/Oracle$ docker run -it --name bkotos-oracle-db store/oracle/database-enterprise:12.2.0.1
Setup Oracle Database
Oracle Database 12.2.0.1 Setup
Sun Feb 24 22:55:08 UTC 2019

Check parameters ......
log file is : /home/oracle/setup/log/paramChk.log
paramChk.sh is done at 0 sec

untar DB bits ......
log file is : /home/oracle/setup/log/untarDB.log
ERROR : untar DB bits failed, please check log /home/oracle/setup/log/untarDB.log for details!
tail: cannot open '/u01/app/oracle/diag/rdbms/orcl/ORCL/trace/alert_ORCL.log' for reading: No such file or directory
tail: no files remaining
```

---
Successful output with `12.1.0.2` image:
```bash
bkotos@bkotos-linux-desktop:~/Projects/Oracle$ docker run -it --name bkotos-oracle-db store/oracle/database-enterprise:12.1.0.2
User check : root.
Setup Oracle Database
Oracle Database 12.1.0.2 Setup
Sun Feb 24 23:20:19 UTC 2019

Check parameters ......
log file is : /home/oracle/setup/log/paramChk.log
paramChk.sh is done at 0 sec

untar DB bits ......
log file is : /home/oracle/setup/log/untarDB.log
untarDB.sh is done at 70 sec

config DB ......
log file is : /home/oracle/setup/log/configDB.log
ERROR : config DB failed, please check log /home/oracle/setup/log/configDB.log for details!
Sun Feb 24 23:20:19 UTC 2019
User check : root.
Setup Oracle Database
```

---
I am running Ubuntu 18.04:
```
bkotos@bkotos-linux-desktop:~/Projects/Oracle$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```

**Comment by bkotos** [comment]
If I snapshot the given container, I am able to access the filesystem and view the log file referenced by the error I posted.

---
To snapshot the container in question, I ran:
```
bkotos@bkotos-linux-desktop:~/Projects/Oracle$ docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                      PORTS               NAMES
8700806dac6a        store/oracle/database-enterprise:12.2.0.1   "/bin/sh -c '/bin/ba…"   2 minutes ago       Exited (1) 12 seconds ago                       bkotos-oracle-db
bkotos@bkotos-linux-desktop:~/Projects/Oracle$ docker commit 8700806dac6a bkotos/debug:latest
sha256:566b197da7004da9b1f7d3345690b8f02b904e0c9c15f5196e8677d295adc4d0
bkotos@bkotos-linux-desktop:~/Projects/Oracle$ docker run -it --name bkotos-debug bkotos/debug:latest bash
```

---
Once in the snapshot of the failed container, the `untarDB.log` file was as follows:
```bash
[oracle@65c2a1ddc1fc /]$ cat /home/oracle/setup/log/untarDB.log
Sun Feb 24 23:55:51 UTC 2019
External DB Files don't Exist. Setup DB Install area, Copy DB files and startup database instance

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
ERROR : untar DB bits failed, please check log /home/oracle/setup/log/untarDB.log for details!

```

**Comment by gvenzl** [comment]
Thank you for reporting this issue.

Unfortunately, the Docker image provided on the Docker Store is not the same as the one produced by the build files in this repository. This repository's issues are provided to help users solve issues with the build files of this repository.

Please report the issue regarding the 12.2 Docker Store image to Oracle Support.

Alternatively, you can build a 12.2 Docker image with the build files provided in this repository..

**Comment by enesusta** [comment]
I'm getting same error. After 1 year and 3 month, there is still no solution?

I currently have three images:

- 12.2.0.1
- 12.1.0.2
- 12.2.0.1-slim

I tried all of these. I can't get any results.
`External DB Files don't Exist. Setup DB Install area, Copy DB files and startup database instance
`

How can I solve this?
