### ISSUE TITLE
Proxy settings of Dockerfile

### ISSUE THREAD

**Issue by HenryXie1** [oracle/docker-images#1167]
Hi, there is issue on proxy when we build docker db images, it could be ER for dockerfile .
When we build a db image via Dockerfile in intranet,  docker build error out when running yum update.  I have checked proxy settings of docker daemon . Details in the note https://www.henryxieblogs.com/2018/09/proxy-settings-for-docker-daemon-and.html

docker itself access proxy well and docker login is working well but docker build still fails on yum update

eventually  i add below into Dockerfile to fix it
```
# add proxy
RUN echo "proxy=http://<proxy server ip address>:80" >> /etc/yum.conf
```

**Comment by gvenzl** [comment]
Hi @HenryXie1,

Proxy information is automatically passed on to the docker container as long as their are set.
Please set `https_proxy` (and `http_proxy`) before invoking `buildDockerImage.sh`:

```
export https_proxy=my.proxy.com:80
export http_proxy$https_proxy
./buildDockerImage.sh -e
```

You will see that the build script will propagate the proxy settings into the container.
