### ISSUE TITLE
Hello Oracle Developers

### ISSUE THREAD

**Issue by XtremePlayzCODE** [oracle/docker-images#117]
# Hello Oracle Developers
This issue has nothing to do with the following repository, and I am aware. Sorry for not posting this on the community support, the Create Account was asking for way too much info about me.
Anyways, I am currently developing a program which modifies the source code of Java, which I retrieved from the source code of JDK. I was wondering if I could modify the Java source code **and keep the oracle copyright notice in the files** and publish it, without getting into legalties.

I will, as I stated, include the copyright notice.

Thank you for your time.

and also if your not an oracle developer and your looking at this, move on!

**Comment by brunoborges** [comment]
Get in contact with Oracle Corp. For more information, visit [Oracle Contacts](https://www.oracle.com/corporate/contact/index.html)

**Comment by XtremePlayzCODE** [comment]
Thank you
