### ISSUE TITLE
Not able to pull docker-images/OracleWebLogic/dockerfiles/12.1.3/

### ISSUE THREAD

**Issue by aivl2018** [oracle/docker-images#1170]
Hi Team,
How can i download/pull these weblogic data.

**Comment by mriccell** [comment]
@aivl2018 You need to clone this repository git clone https://github.com/oracle/docker-images.git to your machine.  Once cloned then follow the README.md to build the image.
Thanks
Monica

**Comment by aivl2018** [comment]
Thanks Monica for your reply.
I have cloned it to my local machine. but how can i build docker image for weblogic 12.1.3.
Can you pls provide commands for that.

**Comment by aivl2018** [comment]
Thanks Monica for your response.
Can we create domain for Weblogic :12.2.1.3. for Generic distribution. As i can see there is only steps for Developer distribution is docker container registry. 
In sample dockerfile, there is also mention (FROM  oracle/weblogic:12.2.1.3-developer ) not a generic distribution .

Thanks in advance

**Comment by mriccell** [comment]
@aivl2018 We have prebuilt images of WebLogic 12.2.1.3 both dev and generic (no label) in Docker Store: https://hub.docker.com/_/oracle-weblogic-server-12c  and in the Oracle Container Registry https://container-registry.oracle.com under middleware.
If you want to build the image manually then in the FROM instead of extending oracle/weblogic:12.2.1.3-developer do oracle/weblogic:12.2.1.3.  The README should have the step by step instructions how to build images.  Lety me know if you have any other questions.
Thanks
Monica

**Comment by mriccell** [comment]
@aivl2018 The FROM clause can always change to point to the image you want to build on top of, e.g. if you are building the domain on top of the WLS 12.2.1.3 image you pulled from Docker Store then your clause would be something like "FROM store/oracle/weblogic:12.2.1.3".

**Comment by aivl2018** [comment]
Thanks Monica for instant reply.
Issue got solved.
Now i am stuck while creating container . Below error occurred.

 domain_name     : [base_domain]
 admin name      : [AdminServer]
 admin_port      : [7001]
 cluster_name    : [DockerCluster]
 domain_path     : [/u01/oracle/user_projects/domains/base_domain]
 production_mode : [prod]
 com.oracle.cie.domain.script.ScriptException: 60308: Domain location not writable.
 60308: The domain location does not have write permission.
 60308: Correct permissions or select different domain location.

        at com.oracle.cie.domain.script.ScriptExecutor.writeDomain(ScriptExecutor.java:2035)
        at com.oracle.cie.domain.script.jython.WLScriptContext.writeDomain(WLScriptContext.java:1793)

**Comment by mriccell** [comment]
If you are using 12213-domain sample the domain home gets mapped to a host volume on your machine.  This would be the -v clause in the docker run command.  That host volume myst have write priviledges so that the domain home is persisted there.
Thanks
Monica

**Comment by aivl2018** [comment]
Could you please elaborate it.
I have not mentioned -v clause in my docker run command.
Command used : 
docker run -d --name wlsadmin --hostname wlsadmin -p 7001:7001 --env-file ./container-scripts/domain.properties -e ADMIN_PASSWORD=w3bl0g1c 12213-domain

& where is " host volume myst" present. Can you pls mention command over here where to go & check it.

Thanks In Advance !!!!

**Comment by aivl2018** [comment]
Thanks **Monica** for your response.
Admin Server is in **running** state after giving 777 permission to my local domain.
Now my container is created.

But i am not able to access weblogic console in browser.
I have enabled All traffic in aws still not opening.
http://ec2-3-56-444-20.compute-1.amazonaws.com:7001/console
