### ISSUE TITLE
Use WDT version 0.17

### ISSUE THREAD

**Issue by tbarnes-us** [oracle/docker-images#1174]
For stability reasons, the WDT samples should use a specific version of WDT instead of always pulling the latest version.  Derek S recommends '0.17'.

**Comment by mriccell** [comment]
@CarolynRountree can you take a look at this issue?
Thanks
Monica

**Comment by CarolynRountree** [comment]
I will get this moved into the upcoming WDT sprint. The change with testing should not take more than 2 hours. Currently it looks for and downloads the latest release. Will change it to pull the desired release.

**Comment by mriccell** [comment]
This was implemented
