### ISSUE TITLE
Rename binary incorrect in the documentation

### ISSUE THREAD

**Issue by revdbrink** [oracle/docker-images#1175]
I followed this manual https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance and place the binaries in the right folder but i got this error after running `./buildDockerImage.sh -v 12.2.0.1 -e`

> Step 11/24 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
> COPY failed: stat /var/lib/docker/tmp/docker-builder061218326/linuxx64_12201_database.zip: no such file or directory

In the manual stood to name the binary linuxx64__database.zip 
After rename it to linuxx64_12201_database.zip it works.

Also the next text is not showed after a successfull installation.
> #########################
> DATABASE IS READY TO USE!
> #########################

**Comment by gvenzl** [comment]
The documentation appears to be correct:

> The needed file is named linuxx64_\<version\>_database.zip. You also have to make sure to have internet connectivity for yum. Note that you must not uncompress the binaries. The script will handle that for you and fail if you uncompress them manually!

`<version>` is a placeholder for the version of the database inside the zip file.
