### ISSUE TITLE
How to access this with sqlPlus once running?

### ISSUE THREAD

**Issue by skiwheelr** [oracle/docker-images#1177]
I want to log into this container from another container running sql*plus but I do not know the correct command. I just need to do basic things like Create and Alter tables for a class on my Macbook.

**Comment by mriccell** [comment]
@skiwheelr you can run instant client to run sqlplus take a look at the image https://github.com/oracle/docker-images/tree/master/OracleInstantClient.

**Comment by gvenzl** [comment]
You can just use SQL*Plus from the same running container, if all you need is a SQL connection.
Just run `docker exec -ti <container name> sqlplus / as sysdba`.

For more information check the ReadMe section [Running Sql*Plus in a Docker container].(https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance#running-sqlplus-in-a-docker-container)
