### ISSUE TITLE
Oracle RAC start container failing with error write /sys/fs/cgroup/cpu,cpuacct/docker/cpu.rt_runtime_us: invalid argument Error: failed to start containers: racnode1

### ISSUE THREAD

**Issue by mkumar01** [oracle/docker-images#1178]
Am getting error while trying to start the container for Oracle RAC on docker.
[root@192 docker]# docker start racnode1
Error response from daemon: linux init cgroups path: write /sys/fs/cgroup/cpu,cpuacct/docker/cpu.rt_runtime_us: invalid argument
Error: failed to start containers: racnode1

docker info as below:
[root@192 docker]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.09.1-ol
Storage Driver: devicemapper
 Pool Name: docker-8:1-1050147-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 53.69GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 18.26GB
 Data Space Total: 107.4GB
 Data Space Available: 42.74GB
 Metadata Space Used: 9.839MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.138GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
init version: fec3683
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.1.12-94.3.9.el7uek.x86_64
Operating System: Oracle Linux Server 7.4
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 11.34GiB
Name: 192.168.1.7
ID: RTXY:TKST:NILK:4GVX:ZHUJ:26K6:OKFD:REVW:4O3C:P7OR:FL6N:5YSO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: the devicemapper storage-driver is deprecated, and will be removed in a future release.
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
Registries: docker.io (secure)

I have gone through https://github.com/oracle/docker-images/issues/1143 but it is not helping.

Can someone please help here.

**Comment by psaini2018** [comment]
Hi,

Please try following and let me know if you still see issue:

Edit /etc/sysconfig/docker and OPTIONS to following:
OPTIONS='--selinux-enabled --cpu-rt-runtime=950000'

save the file.

systemctl daemon-reload
systemctl restart docker
Check the cgroup driver:
docker info | grep cgroupfs
Cgroup Driver: cgroupfs

Also, if you want to use systemd driver , please check the thread:
#837
#838

Also, I would request, please do not use device mapper for docker storage. Please look at Oracle Container runtime for docker storage. I would recommend to use xfs file system for docker storage.
https://docs.oracle.com/cd/E52668_01/E87205/html/index.html

**Comment by psaini79** [comment]
@mkumar01,

No Response. Closing this thread.
