### ISSUE TITLE
How to add custom tnsnames.ora to Oracle 12.1.0.2 se

### ISSUE THREAD

**Issue by MaxCCC** [oracle/docker-images#1181]
How can I add my custom tnsnames.ora to Oracle 12.1.0.2?
I can successfully build the base image. I've build it twice (one with the VOLUME for oracle data and once without (prebuilt image)).

My Dockerfile looks like this (I don't want to work with mounts)
FROM oracle/database:12.1.0.2-se2-prebuilt
COPY tnsnames2.ora /opt/oracle/product/12.1.0.2/dbhome_1/network/admin/tnsnames2.ora
USER root
RUN chown oracle:oinstall /opt/oracle/product/12.1.0.2/dbhome_1/network/admin/tnsnames2.ora
USER oracle

But it always seems to check sqlnet.ora (even not the default tnsnames.ora or am I wrong?)

In the container :
```
total 224K
-rw-r--r-- 1 oracle dba       373 Oct 31  2013 shrept.lst
drwxr-xr-x 2 oracle dba      4.0K Mar  7 08:58 samples
drwxr-xr-x 1 oracle dba      4.0K Mar  7 09:00 ..
-rwxr-xr-x 1 oracle oinstall 203K Mar  7 09:44 tnsnames2.ora
lrwxrwxrwx 1 oracle oinstall   47 Mar  7 14:49 sqlnet.ora -> /opt/oracle/oradata/dbconfig/ORCLCDB/sqlnet.ora
lrwxrwxrwx 1 oracle oinstall   49 Mar  7 14:49 listener.ora -> /opt/oracle/oradata/dbconfig/ORCLCDB/listener.ora
lrwxrwxrwx 1 oracle oinstall   49 Mar  7 14:49 tnsnames.ora -> /opt/oracle/oradata/dbconfig/ORCLCDB/tnsnames.ora
drwxr-xr-x 1 oracle dba      4.0K Mar  7 14:49 .
```

```
tns ping log:
TNS Ping Utility for Linux: Version 12.1.0.2.0 - Production on 07-MAR-2019 14:52:32

Copyright (c) 1997, 2014, Oracle.  All rights reserved.

Used parameter files:
/opt/oracle/product/12.1.0.2/dbhome_1/network/admin/sqlnet.ora
```

**Comment by mawasak** [comment]
Hi,
tnsping is checking sqlnet.ora to use places to resolve name. There is option NAMES.DIRECTORY_PATH which describe order for resolving eg.: NAMES.DIRECTORY_PATH = (LDAP, TNSNAMES, HOST).
tnsnames.ora name is always checking so try to overwrite it.

Regards,
Mariusz

**Comment by MaxCCC** [comment]
@mawasak Thanks, overwriting made it work
