### ISSUE TITLE
Siebel CRM on Docker

### ISSUE THREAD

**Issue by iserikov-x** [oracle/docker-images#1189]
Hello, 
is there any plan to create docker image for latest Siebel CRM?

Looking forward for your reply.

**Comment by pocelka** [comment]
Did you check this repository?
https://github.com/OracleSiebel/ConfiguringSiebel

**Comment by Djelibeybi** [comment]
The Siebel team have not shared any intention to containerise their very extensive product stack. You should ask this question via your Oracle Siebel account manager.
