### ISSUE TITLE
Unable to run Weblogic12213 after building it.

### ISSUE THREAD

**Issue by bibincherianvarghese** [oracle/docker-images#1200]
### Unable to run Weblogic12213 after building it.
Hi,
We are building oracle weblogic 12.2.1.3 following the instructions on [https://github.com/oracle/docker-images/tree/master/OracleWebLogic/dockerfiles/12.2.1.3]. The build was successful but every time we try to start the container with $ docker run -d -v $PWD:/u01/oracle/properties <image_id> fails.

The container won't get start and while checking the logs we are getting the following error 

standard_init_linux.go:207: exec user process caused "no such file or directory"

Thanking you in advance.
BIbin

**Comment by mriccell** [comment]
Are you missing the properties file?

**Comment by willzhang** [comment]
you should run as follow
```
docker run -d -p 7001:7001 -p 9002:9002 \
	-v /data/weblogic:/u01/oracle/properties \
	-e ADMINISTRATION_PORT_ENABLED=true \
	-e DOMAIN_NAME=base_domain \
	oracle/weblogic:12.2.1.3-generic

cat /data/weblogic/domain.properties
username=admin
password=88888888
```

**Comment by mriccell** [comment]
@bibincherianvarghese Are you still experiencing problems?
