### ISSUE TITLE
Not able to run Managed Server container

### ISSUE THREAD

**Issue by aivl2018** [oracle/docker-images#1205]
Hi Team,

I have Admin and managed server container which is saved in images and trying to run same image in another server.
I am successfully able to run Admin server from image.
But while starting managed server container it gets stopped at particular location.

Note :[i have defined volume mount where my wars are present]
Managed server container logs ==>
 Domain Home is:  /u01/oracle/user_projects/domains/base_domain
 Managed Server Name:  csqManagedSvr1
 NodeManager Name:
       ----> 'weblogic' admin password: w3bl0g1c
 Waiting for WebLogic Admin Server on wlsadmin:7001 to become available...
 WebLogic Admin Server is now available. Proceeding...
 Setting NodeManager
       ----> No NodeManager Name set
 Node Manager Name:  Machine_csqManagedSvr1
 Node Manager Home for Container:  /u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1
 NODEMGR_HOME_STR:  NODEMGR_HOME="/u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1"
 NODEMGRHOME_STR:  NodeManagerHome=/u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1
 DOMAINSFILE_STR:  DomainsFile=/u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1/nodemanager.domains
 LOGFILE_STR:  LogFile=/u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1/nodemanager.log
 Starting NodeManager in background...
 NodeManager started.
 /u01/oracle/createServer.sh: line 68: [: -eq: unary operator expected
 ==> /u01/oracle/log_csqManagedSvr1.nm <==
 tail: cannot open '/u01/oracle/user_projects/domains/base_domain/servers/csqManagedSvr1/logs/*.out' for reading: No such file or directory

 ==> /u01/oracle/log_csqManagedSvr1.nm <==
 NODEMGR_HOME is already set to /u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1
 CLASSPATH=/usr/java/jdk1.8.0_191/lib/tools.jar:/u01/oracle/wlserver/server/lib/weblogic.jar:/u01/oracle/wlserver/../oracle_common/modules/thirdparty/ant-contrib-1.0b3.jar:/u01/oracle/wlserver/modules/features/oracle.wls.common.nodemanager.jar::/u01/oracle/wlserver/..:/u01/oracle/wlserver/modules/features/oracle.wls.common.grizzly.jar
 + /usr/java/jdk1.8.0_191/bin/java -server -Djava.security.egd=file:/dev/./urandom -Djdk.tls.ephemeralDHKeySize=2048 -Dcoherence.home=/u01/oracle/wlserver/../coherence -Dbea.home=/u01/oracle/wlserver/.. -Dweblogic.RootDirectory=/u01/oracle/user_projects/domains/base_domain -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Djava.security.policy=/u01/oracle/wlserver/server/lib/weblogic.policy -Dweblogic.nodemanager.JavaHome=/usr/java/jdk1.8.0_191 weblogic.NodeManager -v
 <Mar 28, 2019 12:38:48 PM GMT> <INFO> <Loading domains file: /u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1/nodemanager.domains>
 <Mar 28, 2019 12:38:48 PM GMT> <INFO> <Upgrade> <Setting NodeManager properties version to 12.2.1.3.0>
 <Mar 28, 2019 12:38:48 PM GMT> <INFO> <Upgrade> <Saving upgraded NodeManager properties to '/u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1/nodemanager.properties'>
 <Mar 28, 2019 12:38:48 PM GMT> <INFO> <Loading domains file: /u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1/nodemanager.domains>
 <Mar 28, 2019 12:38:48 PM GMT> <INFO> <Loaded NodeManager configuration properties from '/u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1/nodemanager.properties'>
 Node manager v12.2.1.3.0

 Configuration settings:

 DomainsFile=/u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1/nodemanager.domains
 LogLimit=0
 DomainsDirRemoteSharingEnabled=true
 AuthenticationEnabled=true
 LogLevel=FINEST
 DomainsFileEnabled=true
 ListenAddress=
 NativeVersionEnabled=true
 ProcessDestroyTimeout=20000
 ListenPort=5556
 LogToStderr=true
 weblogic.StartScriptName=startWebLogic.sh
 SecureListener=false
 LogCount=1
 LogAppend=true
 weblogic.StopScriptEnabled=false
 StateCheckInterval=500
 CrashRecoveryEnabled=true
 weblogic.StartScriptEnabled=false
 LogFile=/u01/oracle/user_projects/domains/base_domain/nodemanager/nodemanager.log
 LogFormatter=weblogic.nodemanager.server.LogFormatter
 coherence.StartScriptEnabled=false
 ListenBacklog=50
 NodeManagerHome=/u01/oracle/user_projects/domains/base_domain/Machine_csqManagedSvr1
 RestEnabled=false
 weblogic.startup.JavaHome=/usr/java/jdk1.8.0_191
 weblogic.startup.MW_Home=
 coherence.startup.JavaHome=/usr/java/jdk1.8.0_191
 coherence.startup.MW_Home=

 Domain name mappings:

 base_domain -> /u01/oracle/user_projects/domains/base_domain

 <Mar 28, 2019 12:38:48 PM GMT> <INFO> <12.2.1.3.0>
 <Mar 28, 2019 12:38:48 PM GMT> <INFO> <Skipping SM.create for non WLS dir: AdminServer>
 <Mar 28, 2019 12:38:48 PM GMT> <INFO> <Server Implementation Class: weblogic.nodemanager.server.NMServer$ClassicServer.>
 <Mar 28, 2019 12:38:48 PM GMT> <INFO> <Plain socket listener started on port 5556>

**Comment by aivl2018** [comment]
I am able to see container is running but Managed server is not created yet

**Comment by aivl2018** [comment]
Hi Team,
Could you pls let us know why it gets stuck there . I tried it in many ways but still getting above error.

Thanks in advance !!

**Comment by aivl2018** [comment]
I found the solution but because of **root** user i am not able to edit it.
Can you please let us know as i am completely blocked here.

In File : container-scripts/createserver.sh

Block 1 ==> here it checks NM first time , as i am using same image in another server so it will be failed
# If log.nm does not exists, container is starting for 1st time
# So it should start NM and also associate with AdminServer, as well Managed Server
# Otherwise, only start NM (container is being restarted)
if [ ! -f /u01/oracle/log_$MS_NAME.nm ]; then
    ADD_SERVER=1
fi


Block 2 ====> here it fails the condition. **

> I need to comment the if condition here to solve my issue

**
if [ $ADD_SERVER -eq 1 ]; then
  wlst /u01/oracle/add-machine.py
  wlst /u01/oracle/add-server.py
fi

**Comment by mriccell** [comment]
@aivl2018 What sample did you use to create the domain image?
