### ISSUE TITLE
Not able to start weblogic container using same image which is running on different server

### ISSUE THREAD

**Issue by aivl2018** [oracle/docker-images#1208]
I have run weblogic container on one server which is running fine but when i copied the same image to different server it giving me below error.

Anyone can please suggest here ? @mriccell  

[weblogic@****** ~]$ docker run -d --name wlsadmin --hostname wlsadmin -p 7001:7001 -e username=weblogic -e password=weblogic123 -v /app/Oracle/Middleware/domains/docker_domain:/u01/oracle/user_projects test10-all:latest
9c616c1f251757b0f52bed2bcdbd5ffc4de9b84fb4601e4b9dfd63b9792a3de4
[weblogic@******* ~]$ docker logs --details 9c616c1f251757b0f52bed2bcdbd5ffc4de9b84fb4601e4b9dfd63b9792a3de4
 Domain Home is:  /u01/oracle/user_projects/domains/base_domain
 Domain Name is:  base_domain
 .
 .
 JAVA Memory arguments: -Xms2048m -Xmx2048m -XX:MaxPermSize=512m
 .
 CLASSPATH=/usr/java/jdk1.8.0_191/lib/tools.jar:/u01/oracle/wlserver/server/lib/weblogic.jar:/u01/oracle/wlserver/../oracle_common/modules/thirdparty/ant-contrib-1.0b3.jar:/u01/oracle/wlserver/modules/features/oracle.wls.common.nodemanager.jar::/u01/oracle/wlserver/common/derby/lib/derbynet.jar:/u01/oracle/wlserver/common/derby/lib/derbyclient.jar:/u01/oracle/wlserver/common/derby/lib/derby.jar
 .
 PATH=/u01/oracle/user_projects/domains/base_domain/bin:/u01/oracle/wlserver/server/bin:/u01/oracle/wlserver/../oracle_common/modules/thirdparty/org.apache.ant/1.9.8.0.0/apache-ant-1.9.8/bin:/usr/java/jdk1.8.0_191/jre/bin:/usr/java/jdk1.8.0_191/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/user_projects/domains/base_domain:/u01/oracle/user_projects/domains/base_domain/bin:/u01/oracle
 .
 ***************************************************
 *  To start WebLogic Server, use a username and   *
 *  password assigned to an admin-level user.  For *
 *  server administration, use the WebLogic Server *
 *  console at http://hostname:port/console        *
 ***************************************************
 Starting WLS with line:
 /usr/java/jdk1.8.0_191/bin/java -server   -Xms2048m -Xmx2048m -XX:MaxPermSize=512m -cp /u01/oracle/wlserver/server/lib/weblogic-launcher.jar -Dlaunch.use.env.classpath=true -Dweblogic.Name=AdminServer -Djava.security.policy=/u01/oracle/wlserver/server/lib/weblogic.policy  -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader  -javaagent:/u01/oracle/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/u01/oracle/wlserver/server -Dweblogic.home=/u01/oracle/wlserver/server     -Djava.awt.headless=true -Dconfig.dir=/u01/oracle/user_projects/domains/base_domain/property-files -Dspring.profiles.active=test -Djava.security.egd=file:/dev/./urandom -DUseSunHttpHandler=true -Dhttps.protocols=TLSv1.1,TLSv1.2 -XX:+PrintGC -XX:+PrintGCDetails -XX:+HeapDumpOnOutOfMemoryError -Dweblogic.system.BootIdentityFile= -verbose:gc -Xloggc: -Dhttps.protocols=TLSv1.1,TLSv1.2 -DUseSunHttpHandler=true -Dhttps.protocols=TLSv1.1,TLSv1.2 -Dweblogic.security.SSL.protocolVersion=TLSv1.1,TLSv1.2  weblogic.Server
 Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
 Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file  due to No such file or directory

 <Apr 2, 2019 7:43:21 AM GMT> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.>
 <Apr 2, 2019 7:43:21 AM GMT> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.>
 <Apr 2, 2019 7:43:21 AM GMT> <Info> <WebLogicServer> <BEA-000377> <Starting WebLogic Server with Java HotSpot(TM) 64-Bit Server VM Version 25.191-b12 from Oracle Corporation.>
 <Apr 2, 2019 7:43:22 AM GMT> <Info> <RCM> <BEA-2165021> <"ResourceManagement" is not enabled in this JVM. Enable "ResourceManagement" to use the WebLogic Server "Resource Consumption Management" feature. To enable "ResourceManagement", you must specify the following JVM options in the WebLogic Server instance in which the JVM runs: -XX:+UnlockCommercialFeatures -XX:+ResourceManagement.>
 <Apr 2, 2019 7:43:22 AM GMT> <Info> <Management> <BEA-141107> <Version: WebLogic Server 12.2.1.3.0 Thu Aug 17 13:39:49 PDT 2017 1882952>
 <Apr 2, 2019 7:43:23 AM GMT> <Info> <Security> <BEA-090065> <Getting boot identity from user.>
 **Enter username to boot WebLogic server:<Apr 2, 2019 7:43:23 AM GMT> <Error> <Security> <BEA-090783> <Server is running in Development Mode and the System Console to read the password securely from the command line was not found. The System Console is not present if stdin, stdout, or stderr is redirected when starting WebLogic Server.>**
 <Apr 2, 2019 7:43:23 AM GMT> <Notice> <WebLogicServer> <BEA-000388> <JVM called the WebLogic Server shutdown hook. The server will force shutdown now.>
 <Apr 2, 2019 7:43:23 AM GMT> <Notice> <WebLogicServer> <BEA-000396> <Server shutdown has been requested by <WLS Kernel>.>
 <Apr 2, 2019 7:43:23 AM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to FORCE_SHUTTING_DOWN.>

**Comment by mriccell** [comment]
I will take a look, I will fix the image to take the username and password from a properties file instead than from the command line.

**Comment by aivl2018** [comment]
Thanks Monica!!
I have one managed server container where i have deployed war files into that container. When i commit it & run that image into another server its not taking my customized part. 
I can see after addserver.sh it will get stop just create a managed server. 
So how can i do here if i want my customized part means war files in other container?
Can you please comment on it ?

**Comment by mriccell** [comment]
You should not deploy an application to a running container and then save it into an image.  It is against Docker best practices to do so.  Instead what you do you write a Dockerfile and WLST script that extend the domain image and run WLST to deploy the application to the cluster.  Now you have a new image with the app deployed.  I am working on a sample based on the 12.2.1.3 domain, it should be available this week.

**Comment by mriccell** [comment]
If you have persisted the domain configuration to a HOST volume like in the 12213-domain sample you can run WLST online or even the admin console to deploy the application to the domain configuration in the Host volume.  
If you are following the 12213-domain-home-in-image after you create the image you can extend it and write WLST code to deploy an application inside the image.
Thanks
Monica

**Comment by mriccell** [comment]
I just added a sample of how to deploy an application when the domain home is in the image, OracleWebLogic/samples/12213-deploy-application.
