### ISSUE TITLE
Oracle Database : Failed to connect with sqlplus using sys user from the virtual machine , and from windows 

### ISSUE THREAD

**Issue by madiha95** [oracle/docker-images#1210]
Hi
I have edited my dockerfile so that I can install java8 and maven when building the dockerfile , and now I'm facing an issue which is when trying to connect to sqlplus using the password that I got after running the image from the console , they didnt accept it , for both SYS or SYSTEM users , and even after running this command
`docker exec oracle-ee ./setPassword.sh LetsDocker` I still facing the @same issue ,
Knowing that after running this command it works but only for `system` user `sqlplus system/LetsDocker@//localhost:1521/ORCLPDB1` for other users whenever I'm mentionning theirs name  `sqlplus sys/LetsDocker@//localhost:1521/ORCLPDB1` it still tell me to put the username ,
And then when trying to connect from sqldeveloper of my host machine which is Windows in my case I cant , it still fail , knowing that I'm mentionning system as user , and LetsDocker as password and my virtual machine address as the host name , and 5500 and the port used ,
I have Windows 10;
if needed , here is my new dockerfile :
```
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2017 Oracle and/or its affiliates. All rights reserved.
#
# ORACLE DOCKERFILES PROJECT
# --------------------------
# This is the Dockerfile for Oracle Database 12c Release 2
# 
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# (1) linuxx64_12201_database.zip
#     Download Oracle Database 12c Release 12 Enterprise Edition or Standard Edition 2 for Linux x64
#     from http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Put all downloaded files in the same directory as this Dockerfile
# Run: 
#      $ docker build -t oracle/database:12.2.0.1-${EDITION} . 
#
# Pull base image
# ---------------
FROM oraclelinux:7-slim as base

# Maintainer
# ----------
MAINTAINER Gerald Venzl <gerald.venzl@oracle.com>

# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
ENV ORACLE_BASE=/opt/oracle \
    ORACLE_HOME=/opt/oracle/product/12.2.0.1/dbhome_1 \
    INSTALL_DIR=/opt/install \
    INSTALL_FILE_1="linuxx64_12201_database.zip" \
    INSTALL_RSP="db_inst.rsp" \
    CONFIG_RSP="dbca.rsp.tmpl" \
    PWD_FILE="setPassword.sh" \
    RUN_FILE="runOracle.sh" \
    START_FILE="startDB.sh" \
    CREATE_DB_FILE="createDB.sh" \
    SETUP_LINUX_FILE="setupLinuxEnv.sh" \
    CHECK_SPACE_FILE="checkSpace.sh" \
    CHECK_DB_FILE="checkDBStatus.sh" \
    USER_SCRIPTS_FILE="runUserScripts.sh" \
    INSTALL_DB_BINARIES_FILE="installDBBinaries.sh"

# Use second ENV so that variable get substituted
ENV PATH=$ORACLE_HOME/bin:$ORACLE_HOME/OPatch/:/usr/sbin:$PATH \
    LD_LIBRARY_PATH=$ORACLE_HOME/lib:/usr/lib \
    CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib

# Copy files needed during both installation and runtime
# -------------
COPY $SETUP_LINUX_FILE $CHECK_SPACE_FILE $INSTALL_DIR/
COPY $RUN_FILE $START_FILE $CREATE_DB_FILE $CONFIG_RSP $PWD_FILE $CHECK_DB_FILE $USER_SCRIPTS_FILE $ORACLE_BASE/

RUN chmod ug+x $INSTALL_DIR/*.sh && \
    sync && \
    $INSTALL_DIR/$CHECK_SPACE_FILE && \
    $INSTALL_DIR/$SETUP_LINUX_FILE && \
    rm -rf $INSTALL_DIR



#############################################
# -------------------------------------------
# Start new stage for installing the database
# -------------------------------------------
#############################################

FROM base AS builder

ARG DB_EDITION

# Install unzip for unzip operation
RUN yum -y install unzip

# Copy DB install file
COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/

# Install DB software binaries
USER oracle
RUN chmod ug+x $INSTALL_DIR/*.sh && \
    sync && \
    $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE $DB_EDITION
################################
   

###############################


#############################################
# -------------------------------------------
# Start new layer for database runtime
# -------------------------------------------
#############################################

FROM base

USER oracle
COPY --chown=oracle:dba --from=builder $ORACLE_BASE $ORACLE_BASE

USER root
RUN $ORACLE_BASE/oraInventory/orainstRoot.sh && \
    $ORACLE_HOME/root.sh
#Install java8
RUN \ 
 yum -y update 
#Install Java
 RUN \ 
 yum -y install jre && \
 yum -y install java-1.8.0-openjdk-devel && \
 javac -version

ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64
##########################################
#Install wget
RUN  \
 yum -y install wget 
###########################################
#Install maven3.6 
RUN \ 
 yum -y update && \ 
 wget https://www-us.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz -P /tmp  && \
 tar xf /tmp/apache-maven-*.tar.gz -C /opt && \
 ln -s /opt/apache-maven-3.6.0 /opt/maven

ENV M2_HOME=/opt/maven
ENV PATH=${M2_HOME}/bin:${PATH}
RUN \ 
 mvn -version  && \
 rm -rf /var/cache/yum 
  
USER oracle
WORKDIR /home/oracle

VOLUME ["$ORACLE_BASE/oradata"]
EXPOSE 1521 5500
HEALTHCHECK --interval=1m --start-period=5m \
   CMD "$ORACLE_BASE/$CHECK_DB_FILE" >/dev/null || exit 1

# Define default command to start Oracle Database. 
CMD exec $ORACLE_BASE/$RUN_FILE

```
I beleive That I'm missing somthing but couldnt define what is it exactly !
Thanks in advance

**Comment by gvenzl** [comment]
Hi @madiha95 

>  and now I'm facing an issue which is when trying to connect to sqlplus using the password that I got after running the image from the console , they didnt accept it , for both SYS or SYSTEM users 

What password are you trying to use?

> and even after running this command
docker exec oracle-ee ./setPassword.sh LetsDocker I still facing the @same issue ,
Knowing that after running this command it works but only for system user sqlplus system/LetsDocker@//localhost:1521/ORCLPDB1 for other users whenever I'm mentionning theirs name sqlplus sys/LetsDocker@//localhost:1521/ORCLPDB1 it still tell me to put the username ,

There are no other users created. Whatever users you want to have you will have to create them first.

> And then when trying to connect from sqldeveloper of my host machine which is Windows in my case I cant , it still fail , knowing that I'm mentionning system as user , and LetsDocker as password and my virtual machine address as the host name , and 5500 and the port used ,

The port to use is 1521 to connect via SQLDeveloper, not 5500

**Comment by herz08** [comment]
Hi Gerald,
I think I have the same problem. I'm trying to run the database on Windows 10 as a docker image. When I try to run the image and map a local folder to a Docker folder, I can not connect to sys when using the SQLDeveloper. I made these steps:

1. `docker run --name oracle18xe -p 1521:1521 -p 5500:5500 -v E:\Docker\Datafiles\18.4.0-xe\oradata:/opt/oracle/oradata oracle/database:18.4.0-xe`
2. `docker exec oracle18xe ./setPassword.sh manager`
3. Using SqlDeveloper to connect using sys/manager as sysdba (Connection localhost:1521/XE)
**Result:** ORA-01017: invalid username/password; logon denied
It is possible to connect with the unser system and pdbadmin (Connection localhost:1521/XEPDB1)

Then check this without mapping the folder:

4. `docker run --name oracle18xe2 -p 1522:1521 -p 5501:5500 oracle/database:18.4.0-xe`
5. `docker exec oracle18xe2 ./setPassword.sh manager`
6. Using SqlDeveloper to connect using sys/manager as sysdba (Connection localhost:1522/XE)
**Result:** Success

Could this be a special case when using Docker on Windows? 
I asked Roel Hartman last Week on the Apex Connect and he advised me to map the folder, maybe he used this on a mac.
Do you have any idea how to solve the problem?

Regards 
Oliver
