### ISSUE TITLE
sqlplus / as sysdba doesn't work in Oracle 18 xe

### ISSUE THREAD

**Issue by ostreek** [oracle/docker-images#1213]
Hi,

I have an installation script that I run after the database has started, and it uses "sqlplus / as sysdba". This works fine in Oracle 11, 12, and 18 SE2 but not in 18 Express Edition:

```  
bash-4.2# echo $ORACLE_SID
XE
bash-4.2# sqlplus / as sysdba

SQL*Plus: Release 18.0.0.0.0 - Production on Fri Apr 5 10:34:42 2019
Version 18.4.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

ERROR:
ORA-01017: invalid username/password; logon denied
```

My script works in the same way as setPassword.sh, which is also broken because of this issue.

I can of course connect using `sqlplus sys/<password>@//localhost:1521/XE as sysdba`.

As my script runs immediately after database creation, I could capture the password and use it in my script, with the syntax above, but this would be a bit of pain. And that wouldn't solve the problem for any script that runs at a later date, as the password may have changed from the one specified at creation time - although not via the setPassword script :-)

Should Express Edition support connecting in this way, or am I missing something? Is there a different way I can connect without having to specify the password?

Thanks,
Oliver

**Comment by gvenzl** [comment]
Hi @ostreek, I think you spotted a bug in the 18.4.0 `setPassword.sh` script.

The XE container runs under the `root` user but Oracle XE runs under the `oracle` user.
Only the `oracle` user can connect to the database via `sqlplus / as sysdba`.

This should work (as from the 11.2 XE image): `su -p oracle -c "sqlplus / as sysdba"`, can you try?
This command executes `sqlplus` as the `oracle` user.

**Comment by gvenzl** [comment]
Fix was merged.
