### ISSUE TITLE
Oracle bad performance 12.2.0.1-ee

### ISSUE THREAD

**Issue by michalkonieczny91** [oracle/docker-images#1214]
Hello I have a problem with performance on Oracle 12ee running on docker
I run the container without any limits on memory and CPU. My procedures which invoke several selects (nothing special) and it took 15 minutes  when on the another machine with the same parameters it took 3minutes 
The command i run is
`docker run -d --restart=unless-stopped --name oracle-ee-12 -v /docker/data/oracle-ee:/ORCL  -p 1515:1521  store/oracle/database-enterprise:12.2.0.1` 

So I tried increase memory via env `DB_MEMORY` but set it to 4GB do not give any improvment 
`docker run -d --restart=unless-stopped --name oracle-ee-12 -v /docker/data/oracle-ee:/ORCL -e DB_MEMORY=4GB  -p 1515:1521  store/oracle/database-enterprise:12.2.0.1`

I'm using the latest docker version 
```
root@server:/# docker version 
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54
 Built:             Wed Mar 27 18:36:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by gvenzl** [comment]
Unfortunately we cannot help much with why Docker appears to be slow on one machine while it runs fast on another. However, hopefully the community is of help here.

Go get things started it probably would be best if you can share more information on steps to reproduce, `docker info`, OS config and more.

**Comment by Djelibeybi** [comment]
Please provide the output from `docker info` on both the fast and slow machines, as @gvenzl requested.

**Comment by michalkonieczny91** [comment]
Hi
Docker info:
```
root@xxx:# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 18.09.4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 5.733GiB
Name: xxx
ID: xxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: xxx
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 xxxx:5000
 xxx.xxx.x.xxx:5000
 127.0.0.0/8
Registry Mirrors:
 http://xxx.xxx.x.xxx:5000/
 http://xxx:5000/
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

on the second machine oracle is installed without docker 
this is classic install 

* Oracle on docker work slow
* Oracle with classic install  work normally

**Comment by yetipenguin** [comment]
I'm hitting the same problem on CentOS Linux release 7.6.1810 (Core).

`docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false`

`docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 18
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.12.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: gebit-sparpos-poslive-dev
ID: IYXR:6T2C:3EK5:3LDU:POE4:6KZ4:4IAJ:BTJN:IGTO:BGBR:FJLZ:TYDT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine`

**Comment by yetipenguin** [comment]
12.1.0.2 ist **not** affected.

**Comment by davidritter** [comment]
I've observed that specifically system table access seems remarkably slower in 12.2, 18c and 19c under docker vs 12.1. This command run from SQL*Plus runs almost instantaneously from a 12.1 db in a container, but takes multiple minutes on 12.2, 18c, and 19c
`SELECT COUNT(*) FROM ALL_OBJECTS;`

Is that what you are seeing?

**Comment by OneDonMateo** [comment]
I have same issue on Oracle 12.2 in docker container on Windows and on MacOs. Seems that recreate scripts on sqlplus in bash are slow, but it depends on machine performance. I think that main problem is that after db recreate inserts are very slow, deletion is fast. I run container with memory setup and without. I didn't face those issues on previous versions of Oracle.

**Comment by Ulvhedin** [comment]
Hi,
Same issue on 12.2 se2.
It looks that following queries are fixing performance issue:
```
ALTER SYSTEM SET disk_asynch_io = FALSE SCOPE = SPFILE;
ALTER SYSTEM SET FILESYSTEMIO_OPTIONS=DIRECTIO SCOPE=SPFILE;
```
And restart oracle.

**Comment by Djelibeybi** [comment]
I'm going to close this issue as performance tuning is nominally beyond the scope of this repository. 

However, if you are still experiencing Database container-related performance issues, please open a new issue to discuss those.

**Comment by Djelibeybi** [comment]
I decided to flag it with `more-info-required` just in case this is still an issue. The stalebot will reap it, if not.
