### ISSUE TITLE
Problems with GoldenGate Microservices on Docker

### ISSUE THREAD

**Issue by maifine** [oracle/docker-images#1215]
I am using Oracle GoldenGate Microservices on Docker,
The image was successfully created and all services started successfully.

In ServiceManager Web UI, i add one Environment Variable like this:
```
TNS_ADMIN = /u02/ogg/Local/etc/conf/network
```
And in `/u02/ogg/Local/etc/conf/network`,I add file tnsnames.ora like this:
```
Itpmdb = (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=10.10.10.56)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=itpmdb)))
```

after that，i restarted all service in web ui.

In Administration Server Web UI,
I `Add Credentials`:
```
Credential Alias: itpmdb
User ID: lucksoft
password:luckserver
```
I encountered the following error when testing the connection  I `Add Credentials`:

```
Code:
OGG-08110
Severity:
ERROR
Title:
Login failed. OCI Error ORA (status = 12545-ORA-12545: Connect failed because target host or object does not exist )
```

Trying for a long time, even I deleted the tnsnames.ora file in the /u02/ogg/Local/etc/conf/network folder, the same error remains.

But when I enter the ogg container like this:

```
docker exec -it ogg bash
```

In the container run command like this:

```
export TNS_ADMIN=/u02/ogg/Local/etc/conf/network
sqlplus lucksoft/luckserver@itpmdb
```

The connection has been successful!

However, the connection test error in the Administration Server Web UI remains the same.

What is the reason for this? How can I solve it?

Thank you

**Comment by sbalousek** [comment]
You need to add the TNS name to the user name:

```
Credential Alias: itpmdb
User ID: lucksoft@itpmdb
password:luckserver
```

**Comment by maifine** [comment]
> You need to add the TNS name to the user name:
> 
> ```
> Credential Alias: itpmdb
> User ID: lucksoft@itpmdb
> password:luckserver
> ```

The problem is solved, thank you very much.
