### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by pmihalcin** [oracle/docker-images#122]
Hi,
Is there a way how to manage how much memory container will take?
It is like that in Tomcat case where one can specify -e "JAVA_OPTS=-Xmx256m" when spinning up new container
I refer to Weblogic images

**Comment by brunoborges** [comment]
You'd have to check Docker documentation to specify how much memory you want for your Docker container. 

For the WebLogic samples we provide here, you can set environment parameter [USER_MEM_ARGS](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/1221-domain/container-scripts/add-server.py#L28). This will be picked for setting JVM memory settings for Managed Servers (when you start sample image with `[createServer.sh](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/1221-domain/container-scripts/createServer.sh)` script).
