### ISSUE TITLE
OBIEE scaling

### ISSUE THREAD

**Issue by howard-cho** [oracle/docker-images#1225]
Hi, any plans to support scale-out for the OBIEE image?

**Comment by sjvp** [comment]
No plans.

The sample scripts just follow the documented approach to install and configure BI, but within docker context.

Someone could implement scale-out in docker by following the scale-out documentation: https://docs.oracle.com/middleware/12213/biee/BIESG/GUID-698235D3-6E66-4367-92D3-BFDCAB87FE00.htm#BIESG1660
