### ISSUE TITLE
typo in OracleFMWInfrastructure/dockerfiles/12.2.1.3/container-scripts/setEnv.sh etc

### ISSUE THREAD

**Issue by xiancao** [oracle/docker-images#1234]
There are typos in the following file:
in OracleFMWInfrastructure/dockerfiles/12.2.1.3/container-scripts/createOrStartInfraDomain.sh,

`wlst.sh -skipWLSModuleScanning /u01/oracle/container-scripts/createInfraDomain.py -oh ${ORACLE_HOME} -jh ${JAVA_HOME} -parent ${DOMAIN_ROOT} -name ${DOMAIN_NAME} -user ${USER} -password ${PASS} -rcuDb ${CONNECTION_STRING} -rcuPrefix ${RCUPREFIX} -rcuSchemaPwd ${DB_SCHEMA_PASS} -adminListenPort ${ADMIN_LISTEN_PORT} -adminName ${ADMIN_NAME} -adminPortEnabled ${ADMINISTRATION_PORT_ENABLED} -administrationPort ${ADMINISTRATION_PRT} -managedName ${MANAGED_NAME} -managedServerPort ${MANAGEDSERVER_PORT} -prodMode ${PRODUCTION_MODE}`

`-administrationPort ${ADMINISTRATION_PRT` should be 
`-administrationPort ${ADMINISTRATION_PORT}`

in docker-images/OracleFMWInfrastructure/dockerfiles/12.2.1.3/container-scripts/setEnv.sh,
`# Set ADMINISTRATION_PRT
extract_env ADMINISTRATION_PRT`
should be:
`# Set ADMINISTRATION_PORT
extract_env ADMINISTRATION_PORT`

in OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockerfile, 
in section "# Final image stage"
`ADMINISTRATION_PRT="${ADMINISTRATION_PRT:-9002}" \`
should be 
`ADMINISTRATION_PORT="${ADMINISTRATION_PORT:-9002}" \`

**Comment by xiancao** [comment]
Otherwise, when we set ADMINISTRATION_PORT=true in domain.properties, run_managed_server.sh will always waiting for admin server to be ready since it can not get the correct ADMINISTRATION_PORT number.

**Comment by mriccell** [comment]
Fixed in PR #1232
