### ISSUE TITLE
18c image does not exist in container-registry.oracle.com

### ISSUE THREAD

**Issue by poebus10** [oracle/docker-images#1237]
I was following steps in Oracle RAC Database on Docker and found that container-registry.oracle.com/database/rac:18.3.0 is not available.
...
>   --name racnode2 \
>   container-registry.oracle.com/database/rac:18.3.0
Unable to find image 'container-registry.oracle.com/database/rac:18.3.0' locally
Trying to pull repository container-registry.oracle.com/database/rac ... 
Get https://container-registry-phx.oracle.com/v2/database/rac/manifests/18.3.0: unauthorized: authentication required

I tried to login and pull the image but failed

[root@krx4adb01 dockerfiles]# docker login container-registry.oracle.com
Username (edw....@oracle.com): 
Password: 
Login Succeeded
[root@krx4adb01 dockerfiles]# docker pull container-registry.oracle.com/database/rac:18.3.0
Trying to pull repository container-registry.oracle.com/database/rac ... 
manifest for container-registry.oracle.com/database/rac:18.3.0 not found

**Comment by psaini79** [comment]
It is in the process and will be published soon. We are in the process of updating README.MD also for 18.3 in OCR.

**Comment by Djelibeybi** [comment]
I've asked the Oracle Container Registry team to look into why the 18.3.0 tag is not visible.

**Comment by stickycode** [comment]
@Djelibeybi Seems like there is a disconnect you keep saying the images will turn up in https://container-registry.oracle.com  but there is nothing there months later.

**Comment by Djelibeybi** [comment]
This issue is closed, so it took me a while to find. The database image is outside the scope of my personal influence, but I would suggest opening a new issue (or an SR if you have Database support as it'll carry more weight) asking the DB team to publish the image.
