### ISSUE TITLE
Building GoldenGate image on Windows using Git Bash

### ISSUE THREAD

**Issue by alesana-san** [oracle/docker-images#1238]
Hi!

I tried to use `dockerBuild.sh` for creating a GoldenGate image. I use WIndows 10 x64 and Git Bash (MINGW64) as a shell. I pre-built an InstantClient image to use it as a base image for OGG image. What I faced calling `dockerBuild.sh`:

- As I have `docker` installed to `Program Files` so I have to change line 27 of `dockerBuild.sh` to `eval "${primary^^}=\"${command}\""` to make paths with spaces to work

- Then I found out that I'm lacking `strings` utility. It would be nice if `dockerBuild.sh` made a pre-check of what you have installed and what utilities you are missing.

- And finally I had to use `"${DOCKER}"` in line 144 of `dockerBuild.sh` because `docker` is located in `Program Files` folder.

After these hacks I succeeded at image building.

**Comment by sbalousek** [comment]
Unfortunately, the `dockerBuild.sh` script is only supported on Linux.  Adding support for the Docker Desktop product for Mac and Windows is a priority.

Thanks for the tips!
