### ISSUE TITLE
No space left on device when running buildDockerImage.sh for OracleDatabase

### ISSUE THREAD

**Issue by lukaseder** [oracle/docker-images#124]
I'm running this on Windows 10 with still plenty of disk space:

![image](https://cloud.githubusercontent.com/assets/734593/17023297/f7294c36-4f52-11e6-96f2-0e51fcbdf4c1.png)

I git cloned this repository into a local directory and then copied Oracle 12.1.0.2 Enterprise Edition for Linux into `/c/Users/lukas/docker/oracle/docker-images/OracleDatabase/dockerfiles/12.1.0.2` and then ran `buildDockerImage.sh` only to get a "no space left on device" error

![image](https://cloud.githubusercontent.com/assets/734593/17023287/ed0ba58c-4f52-11e6-9294-d0eaeeb6f449.png)

What might be the cause of this?

**Comment by brunoborges** [comment]
You will have to dig configuration of Docker Toolbox for Windows. It uses a VirtualBox VM behind the scenes. That is where I believe disk space is not sufficient, not your host (Windows).

**Comment by brunoborges** [comment]
@lukaseder, I don't think there is anything we can do in the Dockerfiles to fix this. It is up to the user to adjust its Docker installation and host environment

**Comment by lukaseder** [comment]
Thanks for your help. I was afraid I had to dig into how these things work in detail :)

**Comment by lukaseder** [comment]
OK, for the record (i.e. for other docker newbies like myself), this is the command to increase the default disk (and memory) size:

```
$ docker-machine create --driver virtualbox --virtualbox-disk-size "40000" --virtualbox-memory 2048 default
```

Will edit and adapt if the above is not sufficient.

**Comment by lukaseder** [comment]
Folks: Just wanted to say that this is *really excellent*. Thanks a lot for doing this. Will definitely advertise this to everyone, also on the jOOQ blog :)

**Comment by gvenzl** [comment]
We are glad to hear @lukaseder and appreciate the valuable feedback! Have fun dockering around :)
