### ISSUE TITLE
You need to be root to perform this command

### ISSUE THREAD

**Issue by willzhang** [oracle/docker-images#1244]
the imge is i build 
docker-images/OracleWebLogic/dockerfiles/12.2.1.3/
how can i use root 
```
sh-4.2$ /usr/bin/yum install -y vim
Loaded plugins: ovl
ovl: Error while doing RPMdb copy-up:
[Errno 13] Permission denied: '/var/lib/rpm/.dbenv.lock'
You need to be root to perform this command.
sh-4.2$ 
```

**Comment by gvenzl** [comment]
Either by extending the image with another image, the preferred method really, or by doing a `docker exec -u=0 ...`.
For more information see the [Docker documentation](https://docs.docker.com/engine/reference/commandline/exec/)

**Comment by willzhang** [comment]
thanks, it's a good way for me to run the follow command
docker run --user=root ....
