### ISSUE TITLE
Unable to connect to oracle container from another container using OS Authentication

### ISSUE THREAD

**Issue by swjain23** [oracle/docker-images#1251]
Hi,

We setup our oracle container on a host machine which also has another .NET container which does some tasks on the database. We want to connect to the db as sysdba using OS authentication (specifying no password).
I started the process in .NET container as user oracle and inside created a connection string as:

var connectionString = string.Format("User Id=/;DBA Privilege=SYSDBA;Data Source={0}", serviceName); where serviceName is ORCLCDB.

When I try to connect, I get this error:

ORA-12154: TNS:could not resolve the connect identifier specified

Am I missing something? I can connect from inside the oracle container like this sqlplus / as sysdba. I want to do something similar from the other container via .NET.

**Comment by Djelibeybi** [comment]
How are you connecting the two containers together? How is the DB connection configured in your .NET container? Keep in mind that containers can't see each other by default, so you'll need to add them to the same Docker network or use a similar mechanism to ensure connectivity and name resolution work between them.

**Comment by davidritter** [comment]
By default Oracle DB no longer enables OS authentication by default. Assuming you have SQL file you are running to initialize your DB you should add this command to enable OS authentication
`ALTER SYSTEM SET remote_os_authent=true scope=spfile;`

**Comment by gvenzl** [comment]
Thanks @davidritter for the additional information.
Closing this issue due to lack of further response from the creator.
