### ISSUE TITLE
DockerHub store/oracle/database-enterprise:12.1.0.2 Cannot Start

### ISSUE THREAD

**Issue by Bconteh** [oracle/docker-images#1256]
I have pulled the `store/oracle/database-enterprise:12.1.0.2` from Dockerhub and attempted to run with the command `docker run --name oracle  -d -p 1523:1521 -p 5555:5500 store/oracle/database-enterprise:12.1.0.2`. The container will attempt to start but the Database Setup will fail with the following error:

> **docker logs -f 363bc6381c02**
User check : root.
Setup Oracle Database
Oracle Database 12.1.0.2 Setup
Sun Apr 28 18:05:48 UTC 2019
Check parameters ......
log file is : /home/oracle/setup/log/paramChk.log
paramChk.sh is done at 0 sec
untar DB bits ......
log file is : /home/oracle/setup/log/untarDB.log
untarDB.sh is done at 120 sec
config DB ......
log file is : /home/oracle/setup/log/configDB.log
ERROR : config DB failed, please check log /home/oracle/setup/log/configDB.log for details!
Sun Apr 28 18:05:48 UTC 2019
User check : root.
Setup Oracle Database

> **docker exec -it 363bc6381c02 bash**
[root@363bc6381c02 /]# cd /home/oracle/setup/log/
[root@363bc6381c02 log]# **cat configDB.log**
Sun Apr 28 18:07:48 UTC 2019
Start Docker DB configuration
Call configDBora.sh to configure as oracle user
Argument(s) Error... Patch not present in the Oracle Home, Rollback cannot proceed
If the patch was applied using -no_inventory option, use -ph option
to specify the patch shiphome location. Use 'opatch rollback -help'
to get more information.

ERROR : ORA- errors detected, config DB ora failed, please check log /home/oracle/setup/log/configDBora.log for details!
Docker DB configuration failed ...

**[root@363bc6381c02 log]# cat configDBora.log**
Sun Apr 28 18:07:49 UTC 2019
Configure DB as oracle user
Check user

SQL*Plus: Release 12.1.0.2.0 Production on Sun Apr 28 18:07:49 2019

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> ORA-00845: MEMORY_TARGET not supported on this system
SQL>
File created.

SQL> Disconnected
NID check db name

SQL*Plus: Release 12.1.0.2.0 Production on Sun Apr 28 18:07:51 2019

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0

SQL> ORACLE instance shut down.
SQL> Disconnected

SQL*Plus: Release 12.1.0.2.0 Production on Sun Apr 28 18:07:56 2019

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> ORACLE instance started.

Total System Global Area 3019898880 bytes
Fixed Size                  3715400 bytes
Variable Size             587206328 bytes
Database Buffers         2415919104 bytes
Redo Buffers               13058048 bytes
Database mounted.
SQL>
File created.

SQL>
Database altered.

SQL> alter database open resetlogs
*
ERROR at line 1:
ORA-01139: RESETLOGS option only valid after an incomplete database recovery

SQL> alter database rename global_name to ORCL.localdomain
                                     *
ERROR at line 1:
ORA-01109: database not open

SQL>
NAME                                 TYPE        VALUE
------------------------------------ ----------- ------------------------------
spfile                               string
SQL> ORA-01109: database not open

Database dismounted.
ORACLE instance shut down.
SQL> ORACLE instance started.

Total System Global Area 3019898880 bytes
Fixed Size                  3715400 bytes
Variable Size             587206328 bytes
Database Buffers         2415919104 bytes
Redo Buffers               13058048 bytes
Database mounted.
ORA-03113: end-of-file on communication channel
Process ID: 184
Session ID: 192 Serial number: 57212

SQL> ERROR:
ORA-03114: not connected to ORACLE

SQL> ERROR:
ORA-03114: not connected to ORACLE

SQL> ERROR:
ORA-03114: not connected to ORACLE

SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options
update password

Enter password for SYS:
create pdb : PDB1
Enter PDBADMIN User Password:
The database "ORCL" could not be started. Check the existence of the database.

LSNRCTL for Linux: Version 12.1.0.2.0 - Production on 28-APR-2019 18:08:54

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /u01/app/oracle/product/12.1.0/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.1.0.2.0 - Production
System parameter file is /u01/app/oracle/product/12.1.0/dbhome_1/network/admin/listener.ora
Log messages written to /u01/app/oracle/diag/tnslsnr/363bc6381c02/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=0.0.0.0)(PORT=1521)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.1.0.2.0 - Production
Start Date                28-APR-2019 18:08:54
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /u01/app/oracle/product/12.1.0/dbhome_1/network/admin/listener.ora
Listener Log File         /u01/app/oracle/diag/tnslsnr/363bc6381c02/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))
The listener supports no services
The command completed successfully

SQL*Plus: Release 12.1.0.2.0 Production on Sun Apr 28 18:08:54 2019

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> BEGIN dbms_xdb_config.sethttpsport (5500); END;

*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0

SQL> alter system register
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0

SQL> Disconnected
Oracle Interim Patch Installer version 12.2.0.1.8
Copyright (c) 2019, Oracle Corporation.  All rights reserved.

Please check the arguments and try again.

OPatch failed with error code 135
writing relink log to: /u01/app/oracle/product/12.1.0/dbhome_1/install/relink.log

DONE!

**Comment by Bconteh** [comment]
@gvenzl  Am I starting this image correctly or I need to pass in some extra arguments to docker run command of the image?

**Comment by Djelibeybi** [comment]
The Docker Store image and the `Dockerfile` provided here on GitHub are different. You may want to try building the image manually using the instructions on GitHub instead of using the one on the Docker Store (which is quite old now).

**Comment by Bconteh** [comment]
@Djelibeybi  @gvenzl  wouldn't be nice if the store images get updated ? We have some constraints in our project to pull images from trusted registries only. Building locally and pushing to our private registry isn't an option for us due to security reasons.

**Comment by Djelibeybi** [comment]
Surely building your own is more secure than using any third-party registry? That way, you know exactly what's in the image and how its built.

**Comment by Bconteh** [comment]
@Djelibeybi  @gvenzl Manual building the image isn't a problem at all as far as I'm concern. But once built manually, the ownership of the image changes from Oracle to the builder. Secondly, the resultant image is available to you alone. My project and firm doesn't like this idea. They can accept images from your registries only but not building them manually by self. 

Security point of view, since we agreed to use Oracle products, we should as well trust Images stored in their registries to be safe for use.

No chances of updating the images from your side instead of outsourcing this building process to the users?

**Comment by Djelibeybi** [comment]
The Database images will be updated to 18c/19c soon, but I suspect the older 12c images are not planned to be updated. Though, @gvenzl is the right person to comment further on what the plans for the Docker Store and Oracle Container Registry images are.

**Comment by Bconteh** [comment]
@Djelibeybi @gvenzl we are hunting the partitioning feature which is enabled by default in **store/oracle/database-enterprise:12.1.0.2** unlike **12.2.0.1**. My understanding, some features are sidelined in the newer releases in favour of the lightweight of images. Partitioning was part of the features sacrificed. However, 12.2.0.1 starts without this particular error posted on this issue.

**Comment by Bconteh** [comment]
@Djelibeybi @gvenzl Avi any updates on this issue? would be awesome to update your images on the docker store particularly this guy **12.2.0.1**.

**Comment by lungben** [comment]
Still encountering the same issue with the official Oracle 12.1.0.1 image.
Oracle, could you please fix the image in the official Docker store?

**Comment by Bconteh** [comment]
@lungben we had to give up on using Oracle in our project simply because of this.

I wasn't able to convince the guys to update the registry images and rebuilding the image locally is not an option for us due to the sensitivity and restriction in our project. :(
