### ISSUE TITLE
Weblogic failed to start when container restarted

### ISSUE THREAD

**Issue by jagkoth** [oracle/docker-images#1259]
We are running WL 12.2.1.3 on Docker swarm cluster have 10 worker nodes. we have multiple weblogic domain with 4 replicas. the problem we are facing is during any one of the worker node maintenance, swarm is trying to reschedule a running container to  another node and eventually container is created but inside the container WL process is failed to start up.

In other scenario: 1 admin 4 managed servers ( when I tried to restart the one of the running managed server(container)), wl server is not coming up and eventually the state remain same.

I am wondering does anyone faced same issue? do we have any weblogic health monitor script available ? how do we fix this problem ?

**Comment by mriccell** [comment]
@jagkoth We need to see the WLS server logs to see why the servers died in the first place.  Could you look into the logs and try to determine the reason?

**Comment by jagkoth** [comment]
@mriccell  Thanks for the response. I will share the logs shortly after simulate various scenarios

**Comment by mriccell** [comment]
What is you domain configuration?  Are you using a specific sample?
