### ISSUE TITLE
"No such file or directorytabase_1of2.zip" when installing ee

### ISSUE THREAD

**Issue by tkleiber** [oracle/docker-images#126]
Hi!

I have tried to create the docker image for Database 12.1.0.2 EE in a vagrant oel 7.2 box and in an offficial oraclelinux docker container via

./buildDockerImage.sh -v 12.1.0.2 -e

I have cloned this repository and provided my windows directory via volumes into the vagrant box and the oraclelinux docker container and added the downloaded files from otn:

[vagrant@oraclelinux7 dockerfiles]$ pwd
/docker-images/OracleDatabase/dockerfiles
[vagrant@oraclelinux7 dockerfiles]$ ls -la 12.1.0.2/linuxamd64_12102_database_*
-rwxrwxrwx 1 vagrant vagrant 1673544724 Jul 23 05:13 12.1.0.2/linuxamd64_12102_database_1of2.zip
-rwxrwxrwx 1 vagrant vagrant 1014530602 Jul 23 05:07 12.1.0.2/linuxamd64_12102_database_2of2.zip

In both cases I get following error:

[vagrant@oraclelinux7 dockerfiles]$ ./buildDockerImage.sh -v 12.1.0.2 -e
Checking if required packages are present and valid...
: No such file or directorytabase_1of2.zip
: FAILED open or readbase_1of2.zip
linuxamd64_12102_database_2of2.zip: OK
md5sum: WARNING: 1 listed file could not be read
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 12.1.0.2.

Any idea whats wrong with this?

Kind regards
Torsten

**Comment by tkleiber** [comment]
Similar error with xe version:

[vagrant@oraclelinux7 dockerfiles]$ ls -la 12.1.0.2/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
-rwxrwxrwx 1 vagrant vagrant 315891481 Jul 23 05:51 12.1.0.2/oracle-xe-11.2.0-1.0.x86_64.rpm.zip

[vagrant@oraclelinux7 dockerfiles]$ ./buildDockerImage.sh -v 11.2.0.2 -x -p
./buildDockerImage.sh: option requires an argument -- p
Unknown error while processing options inside buildDockerImage.sh
Checking if required packages are present and valid...
: No such file or directory0.x86_64.rpm.zip
: FAILED open or readx86_64.rpm.zip
md5sum: WARNING: 1 listed file could not be read
MD5 for required packages to build this image did not match!

**Comment by brunoborges** [comment]
You have to download Oracle DB binaries. See README.

**Comment by tkleiber** [comment]
Please see above, that I have download this:

vagrant@oraclelinux7 dockerfiles]$ ls -la 12.1.0.2/linuxamd64_12102_database_*
-rwxrwxrwx 1 vagrant vagrant 1673544724 Jul 23 05:13 12.1.0.2/linuxamd64_12102_database_1of2.zip
-rwxrwxrwx 1 vagrant vagrant 1014530602 Jul 23 05:07 12.1.0.2/linuxamd64_12102_database_2of2.zip

This seems a problem of the mdsum, when I use the -i switch I have now start this, but it is not ready at the moment. Could it be, that checksum does not work when the folders / files are provided via a vagrant/docker volume mapping?

**Comment by gvenzl** [comment]
This is a weird problem. On your first try it did find the second zip file:

[vagrant@oraclelinux7 dockerfiles]$ ./buildDockerImage.sh -v 12.1.0.2 -e
Checking if required packages are present and valid...
: No such file or directorytabase_1of2.zip
: FAILED open or readbase_1of2.zip
**linuxamd64_12102_database_2of2.zip: OK**
md5sum: WARNING: 1 listed file could not be read
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 12.1.0.2.

We heard before that the comments in the Checksum file can give some issues on some platforms. Can you try and delete all "#" marked lines and just leave the checksums themselves in the files.

**Comment by tkleiber** [comment]
No this does not change the behaviour - only skipping via switch -i helps to prevent this error.

**Comment by tkleiber** [comment]
This works fine when running directly on the windows host.
This give the mentioned error when running on the vagrant oel 7.2 client on the shared folder from the host.
This gives the error too when running on the oel 7.2 docker container running in the oel 7.2 client mapping the volume from the vagrant oel 7.2 client.

**Comment by gvenzl** [comment]
Hm, can you do a `ls -al` on the first install zip file in the vagrant environment? It almost sounds like as if vagrant doesn't expose the file to the environment.

**Comment by tkleiber** [comment]
See several updates before - the file is there, again:
ls -al linuxamd64_12102_database_1of2.zip
-rwxrwxrwx 1 vagrant vagrant 1673544724 Jul 23 05:13 linuxamd64_12102_database_1of2.zip

**Comment by gvenzl** [comment]
Did you try to execute the checksum command? Does that work within the vagrant environment?

**Comment by tkleiber** [comment]
Again: See 2 uptates above!

**Comment by brunoborges** [comment]
@tkleiber skip the checksum. It is just an optional verification the `buildDockerImage.sh` shell script does. This script is only intended to help anyway, not required at all to be used.

You may just as well go into the 12..1.0.2 folder and call `docker build <options>`.

**Comment by gvenzl** [comment]
If the `md5sum` Unix command itself isn't working with the vagrant environment there is little we can do to fix that.

**Comment by tkleiber** [comment]
Have found a solution now.
It seem that the Checksum.*file is in dos/windows UTF 8 format, at least when cloning the github repository on windows 10.
If this is mapped into the vagrant box, md5sum does gives the error.

If I convert the Checksum.* files to unix ansi format then the md5sum call is successful.
