### ISSUE TITLE
Deployment failed "No application file exists

### ISSUE THREAD

**Issue by meenaal** [oracle/docker-images#1262]
Hi Team,

I need some help.

I used OracleFMWInfrastructure:12.2.1.3 Dockerfile and creates a domain container without MANAGED SERVER. Using FMW image as a base image I tried to deploy my application but it is failing by stating that the Application doesn't exist, The folder where the poms.jar is available has full permission and the user which is used to create the domain and the user which is trying deploy are the same user. I  did a exec to the container and tried the wlst command line tool to deploy the same, even that is giving the same issue. Am I doing anything wrong, Please help me.
Error:

weblogic.management.ManagementException: [Deployer:149003]Unable to access application source information in "/u01/oracle/application/PDC_HOME/PDC/commsplatform/poms/poms.jar" for application "poms". The specific error is: No application files exist.

Thanks,
Meena.

**Comment by meenaal** [comment]
Forgot to mention: 
Application Home/SourcePath is outside of the user_project folder.
But both user_project and ApplicationHome both are accessible by the user "oracle" 
User_project is a volume.

**Comment by mriccell** [comment]
@meenaal is this the latest FMW Infrastructure 12.2.1.3 image?  This image creates the minimal configuration of an Admin Server and a Managed Server.  Do you need the JRF binaries?  What kind of application are you running?

**Comment by meenaal** [comment]
Yes, It is an ORACLE-CGBU application, it required JRF.
I use your docker files (OracleFMW Infrastructure Dockerfile and Downloaded the FMW_Infxxx.zip from Oracle site) 

Out of these 
'extensionTemplates' : [
            '@@ORACLE_HOME@@/oracle_common/common/templates/wls/oracle.jrf_template.jar',
            '@@ORACLE_HOME@@/oracle_common/common/templates/wls/oracle.jrf.ws.async_template.jar',
            '@@ORACLE_HOME@@/oracle_common/common/templates/wls/oracle.wsmpm_template.jar',
            '@@ORACLE_HOME@@/oracle_common/common/templates/wls/oracle.ums_template.jar',
            '@@ORACLE_HOME@@/em/common/templates/wls/oracle.em_wls_template.jar'
        ],

I have used only these

'extensionTemplates' : [
            '@@ORACLE_HOME@@/oracle_common/common/templates/wls/oracle.jrf_template.jar',
            '@@ORACLE_HOME@@/oracle_common/common/templates/wls/oracle.jrf.ws.async_template.jar',
            '@@ORACLE_HOME@@/em/common/templates/wls/oracle.em_wls_template.jar'
        ],


StartWeblogic throws an execution related to "adrc", I hope that doesn't matter to application deployment, The create domain script created new RCU and configures domain properly using the above-mentioned templates and starts the domain with "adrc" issue, but successfully starts and I m able to connect to the weblogic console using the hostname as well.

Thanks,
Meena.

**Comment by mriccell** [comment]
Yes the adrc exception is harmless.  Did you try deploying through the admin console?

**Comment by meenaal** [comment]
Yes, if the .ear file is located in the user_projects folder which is a volume I m able to deploy the ear through WebLogic console, Only using the application docker container same deployment with the same user_projects location, it is failing.

**Comment by mriccell** [comment]
Sorry could you describe with more detail what you mean by "Only using the application docker container same deployment with the same user_projects location, it is failing"?

**Comment by meenaal** [comment]
I have developed a dockerfile for my application deployment. 
Same user oracle will use the volume user_projects as like FMW container.
1)FMW Infra -image
2) FMW Infra - container
3) APP - image
4) App - container 

All of them uses same user "oracle" and the user_projects folder is a volume

**Comment by mriccell** [comment]
So if I understand correctly your domain configuration has been mapped to a volume but the application binaries are inside of the image, is this correct?  
If the answer is yes this is not a configuration we have tested or certified.  The FMW image only contains the binaries at docker run time the domain configuration is persisted to a Host volume.  If both the domain configuration as well as you application are all in the volume then you can use REST or WLST to deploy, this has been tested and we are sure it works.  The other model is putting both the domain configuration and the app in the image as in the WebLogic sample 12213-domain-home-in-image or 12213-domain-home-in-image-wdt.  
I have created a sample for the FMW Infrastructure domain 12213-domain-in-volume, we have not created the domain configuration in image for the FMW Infrastructure yet.  
The problem you are facing is that probably WLS does not have access to the application to deploy the app and be able to change the domain configuratio .

**Comment by mriccell** [comment]
If the domain is on a host volume then you can deploy the application using WLST online/offline you can deploy with the console or you can use REST.  If the domain is inside of an image I just created a sample under OracleWebLogic/samples/12213-deploy-application.  Please let me know if you need help.

**Comment by meenaal** [comment]
Hi Mricell,
Thanks a lot. 
What told was correct. It was my mistake, the folders were not accessible from the application container.
I used the --volumes-from in my application container to make it work.
I m very much new to Docker, was confused and made a mistake.

Thanks a lot once again for your guidance.

Regards,
Meena.
