### ISSUE TITLE
Container exited with code 1. Builds were successful

### ISSUE THREAD

**Issue by WojciechWeg** [oracle/docker-images#1264]
Hi,

I am trying to build and run weblogic 12.2.1.3.0 from scratch using dockerfile.

Here is list of my files I got from weblogic repo.

   Dockerfile
   fmw_12.2.1.3.0_wls_quick_Disk1_1of1.zip
   install.file
   oraInst.loc
   properties.env
   server-jre-8u211-linux-x64.tar.gz
   
   /container-scripts
        create-wls-domain.py
        createAndStartEmptyDomain.sh
		
		
I have build image with success by 
$ docker build -t oracle/weblogic:12.2.1.3-developer .

So I run container by using that image. Container has been built with success but quickly exited with code (1).
It should exited with code (0). 

Did you encounter similar issues during build process?
How can I analyze what went wrong?

**Comment by mriccell** [comment]
You probably do not have the properties files, look at the README you need a domain_security.properties and a domain.properties.  
If you use the run_admin_server.sh and run_managed_server.sh scripts they  invoke a script to take the properties from the properties files and set them  correctly as  environment variables when running the containers.
This image was recently created and enhanced I would suggest you re-clone the project and follow the instructions in the README.  If you have further questions and problems please let me know.

**Comment by mriccell** [comment]
Are you still experiencing the same problems?

**Comment by WojciechWeg** [comment]
No, I don't experience the same problem any more.

I grabbed whole repo of  weblogic 12.2.1.3.0 and then build from dockerfile. Now builds with success. 

Thank you for your engagement.

**Comment by Djelibeybi** [comment]
Glad you sorted it out.
