### ISSUE TITLE
Running custom scripts on container-registry.oracle.com/database/enterprise:12.2.0.1

### ISSUE THREAD

**Issue by ghillairet** [oracle/docker-images#1266]
I am trying to run custom scripts as described here https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/customscripts on oracle 12.2.0.1 from oracle registry. 
So far the scripts don't seem to execute, are they supported on that image?

I have tried this command:

```
 docker run --name customscripts \
-p 1521:1521 -p 5500:5500 \
-v /Users/guillaume/oracle/oradata:/opt/oracle/oradata \              
-v /Users/guillaume/oracle/scripts:/opt/oracle/scripts/setup \        
container-registry.oracle.com/database/enterprise:12.2.0.1
```

**Comment by Djelibeybi** [comment]
The image on the registry does not support custom scripts. You will need to build the image manually using the content from this repo instead.
