### ISSUE TITLE
OracleFMWInfrastructure createRCU.sh script has wrong variable name

### ISSUE THREAD

**Issue by jwveldhuis** [oracle/docker-images#1268]
https://github.com/oracle/docker-images/blob/623be62492129d925f1b8eff1cf4867a3d422086/OracleFMWInfrastructure/samples/12213-domain-in-volume/container-scripts/createRCU.sh#L56

`CONNECTION_STRING_`
instead of
`CONNECTION_STRING`

Due to this error the `CONNECTION_STRING` is picked from the existing default ENV (InfraDB) rather than reading from the `rcu.properties`.

**Comment by mriccell** [comment]
Thanks for the input will correct and create a PR.

**Comment by mriccell** [comment]
Thanks for the input and correction!
