### ISSUE TITLE
Clues about how to extend database image 

### ISSUE THREAD

**Issue by jomoespe** [oracle/docker-images#127]
Hi, 
I'm trying to extend the database image to have a container with data fixture for testing purpose, as you mention in the database readme: 
> ...You may extend the image with your own Dockerfile and create the users and tablespaces that you may need. 

I've tried two approaches:
- Create an **image FROM** the **Oracle** image and **execute** the DDL and DML files with **sqlplus** in the build phase. This doesn't work because in *build* phase Oracle is not running and sqlplus cannot establish connection.
- **Change the Dockerfile** to create tables and insert data in oracle build phase. With this approach I can't have a Oracle database base image to extends and build my specific data containers.

I've thought (but not tried already) about to run an Oracle container, run scripts inside and tag it. But this approach looks a little dirty for me, and it's not so easy to version and replicate it in different environments, or used in my CI/CD pipelines.

Is there other way? Any clue or suggestion about the best way to extend database image?  

Kind regards 
Jose

**Comment by brunoborges** [comment]
Hey @gvenzl any insight on possible samples we could push out?

**Comment by gvenzl** [comment]
Yup, fresh from the forge: https://github.com/gvenzl/docker-images/tree/master/OracleDatabase/samples/starterset
