### ISSUE TITLE
Error building Oracle XE 18c docker image in Oracle Linux 7

### ISSUE THREAD

**Issue by jesusmorenodiaz** [oracle/docker-images#1272]
**executing
 ./buildDockerImage.sh -v 18.4.0 -x**
got error
![Captura de pantalla de 2019-05-07 20-04-05](https://user-images.githubusercontent.com/44608693/57322211-4cde7a00-7103-11e9-8261-87d4d9fa4b2e.png)

  **Installing : file-5.11-35.el7.x86_64                                      1/2 
su: cannot open session: Permission denied**

more details...
**[SEVERE] The su command is not configured properly or the oracle user does not have the required privileges to install the Oracle database**. If you are running in a Docker environment, ensure to set the environment variable ORACLE_DOCKER_INSTALL=true and try again.
error: %pre(oracle-database-xe-18c-1.0-1.x86_64) scriptlet failed, exit status 1
Error in PREIN scriptlet in rpm package oracle-database-xe-18c-1.0-1.x86_64
  Verifying  : file-5.11-35.el7.x86_64                                      1/2 
  Verifying  : oracle-database-xe-18c-1.0-1.x86_64                          2/2

**Comment by jesusmorenodiaz** [comment]
Using OEL 7.6 with kernel 3.10 also got same error
Kernel Version: 3.10.0-957.12.1.el7.x86_64
Operating System: Oracle Linux Server 7.6
OSType: linux
Architecture: x86_64
[docker-info.txt](https://github.com/oracle/docker-images/files/3160481/docker-info.txt)

**Comment by jesusmorenodiaz** [comment]
Now testing OEL 7.5 with kernel 3.10, got same error
[docker-info.txt](https://github.com/oracle/docker-images/files/3160495/docker-info.txt)

**Comment by jesusmorenodiaz** [comment]
Testing in... COMPLETED OK!
[root@tecnica24 dockerfiles]# uname -a
Linux tecnica24.local 4.1.12-124.25.1.el7uek.x86_64 #2 SMP Tue Feb 5 12:38:44 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Djelibeybi** [comment]
We only support Docker when running the UEK4 or higher: https://docs.oracle.com/cd/E52668_01/E87205/html/docker_install_upgrade.html

As your testing shows, using the RHCK leads to problems. Closing this issue now.

**Comment by jesusmorenodiaz** [comment]
The UEK5 generates error.
Went down to check if solved in previous versions.

**Comment by davidljuba15031979** [comment]
My problem was with docker installed via Ubuntu "snap" package manager, same described in https://github.com/fuzziebrain/docker-oracle-xe/issues/15

So after installing via apt described on digitalocean site (see below quote) it completes correctly.

Quote from https://github.com/fuzziebrain/docker-oracle-xe/issues/15
> @tensau thx a lot, it is really related to the docker installation.
> 
> this helped me 
> `sudo snap remove docker --purge` , but take care this removes all docker images and containers (--purge does not save snap snapshots, witch makes remove very fast)
> 
> * https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04
