### ISSUE TITLE
Error building image under Ubuntu 18.04

### ISSUE THREAD

**Issue by guiotth** [oracle/docker-images#1274]
When launching the script:
 ./buildDockerImage.sh -v 18.4.0 -e -i 
I get the following error:

WARNING: No swap limit support
==========================
Building image 'oracle/database:18.4.0-ee' ...
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/parallels/docker-images/OracleDatabase/SingleInstance/dockerfiles/18.4.0/Dockerfile.ee: no such file or directory
Doing the same under Mac OSX works fine.

**Comment by Djelibeybi** [comment]
You say it works on macOS but you don't provide any detail about the environment that's not working. Please provide the output of `docker info` on your host.

**Comment by guiotth** [comment]
The environment is Ubuntu 18.04 running in Parallels.
Here is the docker info:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/snap/docker/common/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: 949e6fa (expected: fec3683)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-48-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.785GiB
Name: parallels-Parallels-Virtual-Platform
ID: 2B6T:R5W6:6JOL:6EYG:SW4R:3JCL:DE2G:S7TM:U6P2:3S6K:AOUC:7SS7
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 43
 System Time: 2019-05-09T10:43:58.879926161+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by Djelibeybi** [comment]
We've seen issues like this with `aufs` before. Can you try switching to using the `overlay2` driver on an XFS filesystem to see if that resolves the issue? Or reproduce it on Oracle Linux 7 instead?

**Comment by guiotth** [comment]
I will try Oracle Linux 7 then.
Thanks!
