### ISSUE TITLE
GraalVM 19.0.0 Docker image does not contain `native-image`

### ISSUE THREAD

**Issue by aboullaite** [oracle/docker-images#1276]
Hello,

I've recently tried to update from `graalvm-ce:1.0.0-rc16` to `graalvm-ce:19.0.0`, but my Dockerfile fails with the error:

```
/bin/sh: native-image: command not found
```

I've looked into the generated image files and it does not contain the `native-image` command binary

**Comment by aboullaite** [comment]
The is the normal behavior! 

 https://www.graalvm.org/docs/release-notes/ `Native Image was extracted from the base GraalVM distribution. Currently it is available as an early adopter plugin.`

**Comment by mzachh** [comment]
native-image is currently not included, you can install it with `gu install native-image` .

**Comment by MeenakshiHakeem** [comment]
@mzachh when i do gu install native-image i am getting the error gu command not found.. 

sudo gu install native-image
sudo: gu: command not found .

**Comment by mzachh** [comment]
@MeenakshiHakeem with the offical docker image it should just work, `gu` should be already in the path.

I assume you are using graalvm in an other way. `gu` is shipped with graalvm in the "bin" directory.

**Comment by MeenakshiHakeem** [comment]
@mzachh got it thanks

**Comment by alvarosanchez** [comment]
I'm wondering whether you guys would consider providing an official Docker image that has `native-image` pre-installed.

At Micronaut we use `oracle/graalvm-ce:$tag` a lot, and have to always run `gu install native-image`. It'll save time for users if it would come pre-installed.

**Comment by davelet** [comment]
> @MeenakshiHakeem with the offical docker image it should just work, `gu` should be already in the path.
> 
> I assume you are using graalvm in an other way. `gu` is shipped with graalvm in the "bin" directory.

Nice, it's located in `~/.sdkman/candidates/java/21.3.0.r17-grl/lib/installer/bin`
