### ISSUE TITLE
fail to "docker login container-registry.oracle/kubernetes"

### ISSUE THREAD

**Issue by zhigang-sun** [oracle/docker-images#1283]
Hi,

I fail to execute "docker login container-registry.oracle/kubernetes" even I input the correct SSO account&password. Fail result: "Error response from daemon: Get https://container-registry.oracle/v2/: x509: certificate signed by unknown authority" Note: I have accept and register by browser at https://container-registry.oracle.com with my SSO.

**Comment by Djelibeybi** [comment]
The command is `docker login container-registry.oracle.com`. You don't need to provide any further path or repo information on the login command-line.

You may also need to make sure you're bypassing any/all proxies or that they're configured correctly to proxy SSL connections.

**Comment by Djelibeybi** [comment]
Can you provide the output of `docker info` on the host, as this will show any configured proxy information.

**Comment by zhigang-sun** [comment]
Hi, 
The below is the output from my OEL7.5 server. Is it related to registry certificate issue?
PS: I didn't configure any proxy on our OEL.
Thanks,
Zhigang

[zhigsun@bej03220 ~]$ sudo docker login container-registry.oracle
Username: xxxx.xxxx@oracle.com
Password: 
Error response from daemon: Get https://container-registry.oracle/v2/: x509: certificate signed by unknown authority
[zhigsun@bej03220 ~]$ docker --version
Docker version 18.09.1-ol, build c3ab8a8

**Comment by Djelibeybi** [comment]
You're missing the ".com" at the end of the URL. And you haven't provided the output of `docker info`.

**Comment by zhigang-sun** [comment]
Avi,
Thanks for your help. Now I can login successfully.

**Comment by Djelibeybi** [comment]
Glad to hear it. I'm closing this issue.
