### ISSUE TITLE
Multi-stage build not working? Instant Client Docker hub image requires logon

### ISSUE THREAD

**Issue by ORESoftware** [oracle/docker-images#1286]
I tried using this in a Dockerfile:

```
FROM oracle/instantclient:12.2.0.1
```

I got 

```
Step 3/26 : FROM oracle/instantclient:12.2.0.1
pull access denied for oracle/instantclient, repository does not exist or may require 'docker login'

```

is this a public image? I shouldn't have to auth with hub.docker.com then?

**Comment by cjbj** [comment]
The only image is on what was Docker Store (and mirrored on Oracle's container registry), i.e. it has a clickthrough for licensing reasons.

However, what you almost certainly really want to be using is Instant Client 19.  Although there is no image, the base Instant Client RPMs have an updated license and don't require a clickthrough, so installation can be added to your own Dockerfile, see our [Dockerfile](https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/19/Dockerfile).  The 19.3 client libraries will connect to the same DB versions as 12.2 client.

**Comment by ORESoftware** [comment]
yeah it wasnt clear that it was store/oracle, I thought it was just oracle,
but thats just my naivete i guess

**Comment by Djelibeybi** [comment]
I have been working behind the scenes for longer than I care to admit to get approval to start publishing images that contain binaries that don't require a click-thru publicly on Docker Hub, and I'm hopeful that this happens soonish. When it does, we will be able to publish things like this as you expect them.

**Comment by ORESoftware** [comment]
Yeah that is appreciated, maybe sign the EULA via  the CLI?

**Comment by Djelibeybi** [comment]
You wouldn't need to sign the EULA at all. The latest Instant Client RPMs are available with no click-through from http://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/index.html

**Comment by ORESoftware** [comment]
got it, real quick on another topic, are there instructions on how to copy
the source from the image and compile it? if I use:

COPY --from=oracle_build /usr/local/oracle /usr/local/oracle

those are the binaries right? how can I copy the source and compile?

**Comment by Djelibeybi** [comment]
Please open a new issue for a different topic as this one is already closed. :)

**Comment by ORESoftware** [comment]
no problem, will do
