### ISSUE TITLE
how to copy source, not binaries, and compile source

### ISSUE THREAD

**Issue by ORESoftware** [oracle/docker-images#1287]
are there instructions on how to copy the source from the image and compile it? if I use:

```Dockerfile

COPY --from=oracle_build /usr/local/oracle /usr/local/oracle
```

those are the binaries right? how can I copy the source and compile?

**Comment by ORESoftware** [comment]
update: this is more accurate on where the files are located in the image:

```Dockerfile
COPY --from=oracle_client_build /usr/lib/oracle /usr/lib/oracle
COPY --from=oracle_client_build /usr/share/oracle /usr/share/oracle
COPY --from=oracle_client_build /usr/include/oracle /usr/include/oracle
```

**Comment by Djelibeybi** [comment]
The source of what? There are no sources in our images, so if you added sources, you should know where they are.

**Comment by ORESoftware** [comment]
Right, so is there an image where we can get the sources for oracle, and compile them easily? We may want to compile different depending on the target platform, right? Or are these binaries guaranteed to run on any *nix flavor?

**Comment by Djelibeybi** [comment]
The Oracle Instant Client is not open source and as such, we don't release the source code for the client library, just the binaries. I'm going to assign this question across to @cjbj who can answer the second question about binary compatibility.

**Comment by cjbj** [comment]
Binaries are platform specific and match the Oracle DB releases.
Platforms are shown at https://www.oracle.com/technetwork/database/database-technologies/instant-client/downloads/index.html

You'll need to distribute Instant Client (per the license - IANAL) for the target platforms or get your end users to install them.
