### ISSUE TITLE
rpm files are missing

### ISSUE THREAD

**Issue by ORESoftware** [oracle/docker-images#1291]
I was following these instructions:

https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/installing-oracle-database-instant-client.html#GUID-33543D62-0EBD-49A5-97C9-94C4F0C4E90A

when I run this:

```
Step 51/57 : RUN alien -i oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
 ---> Running in f44de5106d09

```
Then I get:

```
File "oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm" not found.
The command '/bin/sh -c alien -i oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm' returned a non-zero code: 2
```

**Comment by ORESoftware** [comment]
the same missing files are listed here:
https://help.ubuntu.com/community/Oracle%20Instant%20Client

**Comment by Djelibeybi** [comment]
You need to copy the RPM into the image during the build process. It doesn't exist in the base Ubuntu image beforehand.

**Comment by cjbj** [comment]
@ORESoftware for steps like those @Djelibeybi explained, see https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/12.2.0.1/Dockerfile

The 12.x Instant Client requires a click through before downloading; you have to get the RPMs from [OTN](http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html).

**Comment by ORESoftware** [comment]
ahh thank you
