### ISSUE TITLE
libaio package missing with latest 12.2.1.3 OracleFMWInfrastructure dockerfiles

### ISSUE THREAD

**Issue by ashageetha** [oracle/docker-images#1292]
**Issue**:
When we built OracleBI 12.2.1.3 image with latest 12.2.1.3 OracleFMWInfrastructure dockerfiles, 
 system components did not start as libnqcsfwrapper.so could not load. This was because of dependent libaio.so.1 was not present.

**Analysis**:
After debug we found that initially libaio which was being shipped with OracleFMWInfrastructure  12.2.1.3 image is missing with latest dockerfiles. 

**Root Cause**:
When multistage build was implemented to  Shrink the image size, install of libaio was done in intermediate first build and was not installed with final build. Hence libaio is missing in final 12.2.1.3 OracleFMWInfrastructure image.

**Dockerfile details**:
libaio installed in intermediate step of build:  https://github.com/oracle/docker-images/blob/1714789336409f66b4027ee1c11a860ad13d196b/OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockerfile#L59
But not present with final build: https://github.com/oracle/docker-images/blob/1714789336409f66b4027ee1c11a860ad13d196b/OracleFMWInfrastructure/dockerfiles/12.2.1.3/Dockerfile#L88

**Comment by Djelibeybi** [comment]
I believe @mriccell is already aware of this.

**Comment by Djelibeybi** [comment]
Fixed by #1293.
