### ISSUE TITLE
WebCenter Sites Installed - Cannot Login

### ISSUE THREAD

**Issue by st11x** [oracle/docker-images#1295]
Hi,

I have successfully installed WebCenter Sites using the provided Docker scripts. I could login to the admin server as the user weblogic. I can also login as SatelliteServer to the cache inventory tool, etc.

However, when I try to login to Sites with fwadmin, nothing happens, it just goes back to the login page. I don't see any errors in the log files. 

If I login via CatalogManager (ftcmd=login), I see this error

COM.FutureTense.Common.ContentServerException: ContentServerException: (Request Authentication failed in Catalog Manager) Error code:REQUEST AUTHENTICATION FAILED
        at COM.FutureTense.Common.CatalogManager.execute(CatalogManager.java:350)
        at COM.FutureTense.Servlet.FTServlet.execute(FTServlet.java:120)
        at COM.FutureTense.Servlet.FTServlet.doGet(FTServlet.java:52)

**Comment by st11x** [comment]
In wcsitesadminserver.env.list, I did set DOCKER_HOST=localhost not knowing what to set to. Is that a problem?

**Comment by ashishchalak** [comment]
You have to give hostmachine ip to dockerhost parameter.

**Comment by st11x** [comment]
My docker runs inside a Linux VM under Virtualbox. The intent was to share this VM or make containers that is portable for all the developers.

Setting this to a each hostmachine IP makes it a bit more cumbersome. Anyway, is that why it is failing? How is this DOCKER_HOST property used?

Can I still change it and restart the admin server? Or do I have to do the install all over again?

Thanks.

**Comment by ashishchalak** [comment]
Try installing on Linux VM, and use IP of your linux VM. You need to install over again.

**Comment by st11x** [comment]
I did install it on a Linux VM, just that all Dev has a Windows laptop, so we need to VirtualBox into one.

I searched through the install scripts and where it gets used most is a search and replace in the config directory like this:

'grep -r --exclude="jbossTicketCacheReplicationConfig.xml" ...'

Maybe I don't need to reinstall again.

**Comment by ashishchalak** [comment]
you can try that once to replace ip of virtual box in all files with that script

**Comment by st11x** [comment]
I had done so, it still didn't work. I was finally able to login via CatalogManager though, it just needed to go through POST.

**Comment by st11x** [comment]
There were other property files I had to change the localhost setting. They were identified by the install script. Files like cas.properties, deployerConfigContext.xml, and customBeans.xml.

I could have left everything as localhost except in those files, but I got it working. I will feedback when I find the minimal list of files to update.

**Comment by ashishchalak** [comment]
Any updates on your testing on this?

**Comment by st11x** [comment]
I haven't had the chance to circle back on this, I just need to recall where to set that external cas URL versus the internal.
