### ISSUE TITLE
Failed to build oracle BI 12.2.1.4 image

### ISSUE THREAD

**Issue by Savreddy** [oracle/docker-images#1309]
Building image for BI 12.2.1.4 , failed with below error

auncher log file is /tmp/OraInstall2019-06-08_02-40-24AM/launcher2019-06-08_02-40-24AM.log.
Extracting the installer . . . . . . . . . . . . . . . . . Done
Checking if CPU speed is above 300 MHz.   Actual 2194.873 MHz    Passed
Checking swap space: must be greater than 512 MB.   Actual 15999 MB    Passed
Preparing to launch the Oracle Universal Installer from /tmp/OraInstall2019-06-08_02-40-24AM
Log: /tmp/OraInstall2019-06-08_02-40-24AM/install2019-06-08_02-40-24AM.log
Setting ORACLE_HOME to /u01/oracle
Setting INSTALL_TYPE to BI Platform Distribution with Samples
Copyright (c) 1999, 2017, Oracle and/or its affiliates. All rights reserved.
Reading response file..
Skipping Software Updates
Validations are disabled for this session.
Verifying data
Copying Files
Internal Error: File Copy failed. Aborting Install

The log(s) can be found here: /tmp/OraInstall2019-06-08_02-40-24AM.
ERROR: Installer execution failed (1).
Removing intermediate container e2f361e922c3
The command '/bin/sh -c cd /u01 && unzip $BI_DISTRO_ZIP1 && unzip $BI_DISTRO_ZIP2 && cd - &&     /u01/$BI_INSTALLER1 -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE="BI Platform Distribution with Samples" &&     rm /u01/$BI_DISTRO_ZIP1 /u01/$BI_DISTRO_ZIP2 /u01/$BI_INSTALLER1 /u01/$BI_INSTALLER2 /u01/oraInst.loc /u01/install.file' returned a non-zero code: 1
There was an error building the image

**Comment by sjvp** [comment]
As per the console output, you'll need to look at the logs under  /tmp/OraInstall2019-06-08_02-40-24AM

**Comment by Savreddy** [comment]
No able to find logs /tmp , let me set up and share instance details with you.

**Comment by Djelibeybi** [comment]
I'm flagging this with more info required to see if it's still an issue.
