### ISSUE TITLE
Error while building docker image for 18.4.0 XE

### ISSUE THREAD

**Issue by aishydevil12286** [oracle/docker-images#1315]
Getting the following issue while executing 

 ./buildDockerImage.sh -v 18.4.0 -x 

Ignored MD5 sum, 'md5sum' command not available.
==========================
DOCKER info:
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 13
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 6VQ5:YTKU:SVOM:IXR6:HONV:YM4H:LQZ6:7YTA:4BBK:TFIJ:LCAA:72FD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 50
 System Time: 2019-06-22T07:52:13.805544236Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

==========================
Building image 'oracle/database:18.4.0-xe' ...
Sending build context to Docker daemon  18.94kB
Step 1/10 : FROM oraclelinux:7-slim
 ---> f7512ac13c1b
Step 2/10 : MAINTAINER Gerald Venzl <gerald.venzl@oracle.com>
 ---> Running in 04d9bd43c8d2
Removing intermediate container 04d9bd43c8d2
 ---> 7c6e0286ec4a
Step 3/10 : ENV ORACLE_BASE=/opt/oracle     ORACLE_HOME=/opt/oracle/product/18c/dbhomeXE     ORACLE_SID=XE     INSTALL_FILE_1="oracle-database-xe-18c-1.0-1.x86_64.rpm"     RUN_FILE="runOracle.sh"     PWD_FILE="setPassword.sh"     CONF_FILE="oracle-xe-18c.conf"     CHECK_SPACE_FILE="checkSpace.sh"     CHECK_DB_FILE="checkDBStatus.sh"     INSTALL_DIR="$HOME/install"     ORACLE_DOCKER_INSTALL="true"
 ---> Running in 758685cfb23c
Removing intermediate container 758685cfb23c
 ---> 82a5d5b07f34
Step 4/10 : ENV PATH=$ORACLE_HOME/bin:$PATH
 ---> Running in f89ae7828fdb
Removing intermediate container f89ae7828fdb
 ---> 605f7a17aa98
Step 5/10 : COPY $CHECK_SPACE_FILE $INSTALL_FILE_1 $RUN_FILE $PWD_FILE $CHECK_DB_FILE $CONF_FILE $INSTALL_DIR/
COPY failed: stat /var/lib/docker/tmp/docker-builder597505656/oracle-database-xe-18c-1.0-1.x86_64.rpm: no such file or directory

ERROR: Oracle Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.

**Comment by takov** [comment]
Did you download the binaries manually. 
Check the README.MD
IMPORTANT: You will have to provide the installation binaries of Oracle Database and put them into the dockerfiles/<version> folder. You only need to provide the binaries for the edition you are going to install. The binaries can be downloaded from the Oracle Technology Network, make sure you use the linux link: Linux x86-64....

**Comment by aishydevil12286** [comment]
@takov Yes, I did do that. But, I don't know why it's looking for it at the following location instead of the dockerfiles/ sub-directory. 

```/var/lib/docker/tmp/docker-builder597505656/```

Step 5/10 : COPY $CHECK_SPACE_FILE $INSTALL_FILE_1 $RUN_FILE $PWD_FILE $CHECK_DB_FILE $CONF_FILE $INSTALL_DIR/
COPY failed: stat **/var/lib/docker/tmp/docker-builder597505656**/oracle-database-xe-18c-1.0-1.x86_64.rpm: no such file or directory

**Comment by aishydevil12286** [comment]
Ah.. I placed it in the root, instead of the specific version
.
├── 11.2.0.2
├── 12.1.0.2
├── 12.2.0.1
├── 18.3.0
├── 18.4.0
├── 19.3.0
├── buildDockerImage.sh
└── oracle-database-xe-18c-1.0-1.x86_64.rpm

Needed to place it in **dockerfiles/18.4.0** ( this was the fix )

Thanks @takov . Need to read documentation more carefully.
