### ISSUE TITLE
Extending Dockerfile to import dump file

### ISSUE THREAD

**Issue by pzheng64** [oracle/docker-images#1324]
I'd like to build an image where my dump file is imported. 
https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/Dockerfile.ee

How can I provide ORACLE_SID,  ORACLE_PDB and ORACLE_PWD as preset inside Dockerfile?
These are passed to `docker run` parameters for now as in the following example:

```
docker run --name <container name> \
-p <host port>:1521 -p <host port>:5500 \
-e ORACLE_SID=<your SID> \
-e ORACLE_PDB=<your PDB name> \
-e ORACLE_PWD=<your database passwords> \
-e ORACLE_CHARACTERSET=<your character set> \
-v [<host mount point>:]/opt/oracle/oradata \
oracle/database:12.1.0.2-ee
```

That means I can't import database until I run `docker run` at least once.
What I'm going to do is just build a pre-built image where all the needed objects like TABLESPACE, ROLE, USER are set up and also dump file has been imported so that I can distribute this image to the developers.

**Comment by chahn** [comment]
Maybe this is what you're looking for?

https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/prebuiltdb

**Comment by pzheng64** [comment]
Thanks.
