### ISSUE TITLE
12213-domain-home-in-image-wdt hard-coded WDT_SUPPORTED_RELEASE=0.17

### ISSUE THREAD

**Issue by sxnzhang** [oracle/docker-images#1327]
12213-domain-home-in-image-wdt docker image by default references WDT 0.17 release , and with this version, domain creation failed with below NPE exception when the model file contains JDBC resource:

. ./createDomain.sh -oracle_home $Oracle_Home -domain_type WLS -domain_parent user_projects  -model_file sqlatn_template.yaml -variable_file domain.properties -archive_file archive.zip

JDK version is 1.8.0_171-b11
JAVA_HOME = .../jdk180171b11/jdk1.8.0_171
WLST_EXT_CLASSPATH = .../weblogic-deploy/lib/weblogic-deploy-core.jar
... ...

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

####<Jul 11, 2019 11:40:25 AM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05002> <Performing validation in TOOL mode for WebLogic Server version 12.2.1.3.0 and WLST OFFLINE mode>
####<Jul 11, 2019 11:40:25 AM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05003> <Performing model validation on the .../weblogic-deploy/bin/sqlatn_template.yaml model file>
####<Jul 11, 2019 11:40:25 AM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05005> <Performing archive validation on the .../archive.zip archive file>
####<Jul 11, 2019 11:40:25 AM> <INFO> <Validator> <__validate_domain_info_section> <WLSDPLY-05008> <Validating the domainInfo section of the model file>
####<Jul 11, 2019 11:40:25 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the topology section of the model file>
####<Jul 11, 2019 11:40:26 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the resources section of the model file>
####<Jul 11, 2019 11:40:26 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the appDeployments section of the model file>
####<Jul 11, 2019 11:40:26 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05009> <Model file .../weblogic-deploy/bin/sqlatn_template.yaml does not contain a appDeployments section, validation of appDeployments was skipped.>
####<Jul 11, 2019 11:40:26 AM> <INFO> <ValidationResults> <log_results> <WLSDPLY-05204> <Validation found 0 error, 0 warning, and 0 informational messages.>
####<Jul 11, 2019 11:40:26 AM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20017> <No filter configuration file .../weblogic-deploy/lib/model_filters.json>
####<Jul 11, 2019 11:40:26 AM> <INFO> <DomainCreator> <__create_domain> <WLSDPLY-12203> <Creating domain of type WLS>
####<Jul 11, 2019 11:40:26 AM> <INFO> <DomainCreator> <__create_domain_with_select_template> <WLSDPLY-12210> <Selecting base template named Basic WebLogic Server Domain>
####<Jul 11, 2019 11:40:27 AM> <INFO> <DomainCreator> <__create_domain_with_select_template> <WLSDPLY-12212> <Loading selected templates>
####<Jul 11, 2019 11:40:30 AM> <INFO> <Creator> <_create_mbean> <WLSDPLY-20013> <Updating SecurityConfiguration>
####<Jul 11, 2019 11:40:31 AM> <INFO> <TopologyHelper> <create_placeholder_jdbc_resources> <WLSDPLY-19401> <Creating placeholder for JDBC resource ORADataSource>
####<Jul 11, 2019 11:40:31 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name AdminServer>
####<Jul 11, 2019 11:40:31 AM> <INFO> <Creator> <_create_mbean> <WLSDPLY-20013> <Updating NMProperties>
####<Jul 11, 2019 11:40:31 AM> <INFO> <DomainCreator> <__create_domain_with_select_template> <WLSDPLY-12206> <Closing templates for domain base_domain>
com.oracle.cie.domain.script.ScriptException: 64254: Error occurred in "DomainGenerator.post.processing.phase.text" phase execution
64254: Encountered error: java.lang.NullPointerException
64254: Check log for more detail.
null
        at com.oracle.cie.domain.script.ScriptExecutor.runProgressOperator(ScriptExecutor.java:5870)
        at com.oracle.cie.domain.script.ScriptExecutor.writeDomain(ScriptExecutor.java:2111)
        at com.oracle.cie.domain.script.jython.WLScriptContext.writeDomain(WLScriptContext.java:1828)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.oracle.cie.domain.script.jython.WLSTState.processCommand(WLSTState.java:226)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:730)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.python.core.PyReflectedFunction.__call__(Unknown Source)
        at org.python.core.PyMethod.__call__(Unknown Source)
        at org.python.core.PyObject.__call__(Unknown Source)
        at org.python.core.PyInstance.invoke(Unknown Source)
        at org.python.pycode._pyx37.command$1(/tmp/WLSTOfflineIni4804702949218866262.py:19)
        at org.python.pycode._pyx37.call_function(/tmp/WLSTOfflineIni4804702949218866262.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(Unknown Source)
        at org.python.pycode._pyx37.writeDomain$27(/tmp/WLSTOfflineIni4804702949218866262.py:109)
        at org.python.pycode._pyx37.call_function(/tmp/WLSTOfflineIni4804702949218866262.py)
        at org.python.core.PyTableCode.call(Unknown Source)

**Comment by sxnzhang** [comment]
The domain creation is successful when using WDT version 1.1.1.  Here is an sample model file:
domainInfo:
    AdminUserName: $user_name
    AdminPassword: $password
topology:
    ProductionModeEnabled: true
    NMProperties:
        JavaHome: /usr/java/jdk1.8.0_211
        LogFile: '@@DOMAIN_HOME@@/nodemanager/nodemanager.log'
        DomainsFile: '@@DOMAIN_HOME@@/nodemanager/nodemanager.domains'
        NodeManagerHome: '@@DOMAIN_HOME@@/nodemanager'
        weblogic.StartScriptName: startWebLogic.sh
    Server:
        AdminServer:
            NetworkAccessPoint:
                T3Channel:
                    PublicPort: 30001
                    ListenPort: 30001
                    PublicAddress: localhost
    SecurityConfiguration:
        Realm:
            myrealm:
                AutoRestartOnNonDynamicChanges: true
                Adjudicator:
                    DefaultAdjudicator:
                        DefaultAdjudicator:
                AuthenticationProvider:
                    SQLAuthenticator:
                        SQLAuthenticator:
                            DataSourceName: ORADataSource
                            PlaintextPasswordsEnabled: true
                            PasswordStyleRetained: false
                            ControlFlag: SUFFICIENT
                    DefaultAuthenticator:
                        DefaultAuthenticator:
                    DefaultIdentityAsserter:
                        DefaultIdentityAsserter:
                            ActiveType: [ AuthenticatedUser, 'weblogic-jwt-token' ]
                Authorizer:
                    XACMLAuthorizer:
                        XACMLAuthorizer:
                            PolicyDeploymentEnabled: true
                CertPathProvider:
                    WebLogicCertPathProvider:
                        WebLogicCertPathProvider:
                CredentialMapper:
                    DefaultCredentialMapper:
                        DefaultCredentialMapper:
                PasswordValidator:
                    SystemPasswordValidator:
                        SystemPasswordValidator:
                RoleMapper:
                    XACMLRoleMapper:
                        XACMLRoleMapper:
resources:
    JDBCSystemResource:
        ORADataSource:
            Target: AdminServer
            JdbcResource:
                JDBCDataSourceParams:
                    JNDIName: jdbc.ORADataSource
                JDBCDriverParams:
                    URL: '@oracle.db.url@'
                    PasswordEncrypted: @oracle.db.pswd@
                    DriverName: oracle.jdbc.OracleDriver
                    Properties:
                        user:
                            Value: @oracle.db.user@
                JDBCXAParams:
                    XaTransactionTimeout: 50

**Comment by mriccell** [comment]
@CarolynRountree

**Comment by mriccell** [comment]
You can change the version of WDT that is used by the WDT sample.  In build.sh change WDT_SUPPORTED_RELEASE=0.17 to be the latest version 1.1.1.
Thanks
Monica

**Comment by sxnzhang** [comment]
Thanks for the info.

**Comment by rjeberhard** [comment]
The latest WebLogic operator release references version 0.24.  I'll update it to 1.1.1.

**Comment by mriccell** [comment]
@sxnzhang please let me know if that resolved your issue

**Comment by sxnzhang** [comment]
I set WDT_SUPPORTED_RELEASE=1.1.1 as environment variable before running the tests, which downloaded WDT release 1.1.1, and that solved the problem.  
Thank you for your help!
