### ISSUE TITLE
The OracleJDK docker image will be bigger because mv operation

### ISSUE THREAD

**Issue by liaoya** [oracle/docker-images#133]
The two OracleJDK Dockerfile has the following directive
RUN mv $(ls -1 -d /usr/java/*) $JAVA_HOME
The mv operation will increase the docker image size. There is no such problem when using "ln -s" command.

**Comment by brunoborges** [comment]
There was a problem when using symlink, which I cannot remember exactly, but it would fail on inherited images. Which is why we went with `mv` instead of `ln`. See commit 8b8b4904

**Comment by brunoborges** [comment]
Found the actual commit, with much better explanation :-)

See e234ae65f.
