### ISSUE TITLE
Unable to pull image "store/oracle/database-enterprise:12.2.0.1" when docker user namespace is enabled

### ISSUE THREAD

**Issue by hofsa** [oracle/docker-images#1331]
docker provides an usernamespace-feature for additional isolation of containers: [https://docs.docker.com/engine/security/userns-remap/](https://docs.docker.com/engine/security/userns-remap/)

If this feature is enabled, the image "store/oracle/database-enterprise:12.2.0.1" can not be pulled:

```
docker pull store/oracle/database-enterprise:12.2.0.1
12.2.0.1: Pulling from store/oracle/database-enterprise
4ce27fe12c04: Pull complete 
9d3556e8e792: Extracting [==================================================>]    151MB/151MB
fc60a1a28025: Download complete 
0c32e4ed872e: Download complete 
b465d9b6e399: Download complete 
failed to register layer: Error processing tar file(exit status 1): Container ID 54321 cannot be mapped to a host ID
```

The usernamespacing is enabled in the file /etc/docker/daemon.json:
```
{
  "userns-remap": "docker-remap:docker-remap"
}
```
The remap-user has uid 100'000, a corresponding docker-oracle-user with uid 154321 (remap-offset + excpected ID 54321) exists on the host:
```
docker-remap\x:100000:100000::/home/docker-remap:/bin/sh
docker-appsrv:x:101501:101501::/home/docker-appsrv:/bin/sh
docker-db:x:101502:101502::/home/docker-db:/bin/sh
docker-oracle:x:154321:154321::/home/docker-oracle:/bin/sh
```
Other images (openJDK, postgreSQL, mariaDB, ElasticSearch, ...) work without any problems.

My environment:
OS:
>Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Docker:
>Docker version 18.09.8, build 0dd43dd87f

**Comment by gvenzl** [comment]
I'm not very familiar with the user namespace feature but it looks like that the user `54321` cannot be mapped to any ID on the machine: `failed to register layer: Error processing tar file(exit status 1): Container ID 54321 cannot be mapped to a host ID`

**Comment by hofsa** [comment]
Hi Gerald
Thank you for your reply. I do agree, that there is a problem with the mapping to a user on the host. The question is, why is there a problem? :-)

When enabling the user-namespacing with the remap-user '100000', the mapping to the host should lead to the user-id 154321 (internal id 54'321 + remap-offset 100'000)
Also, it does not work if add a user 54321 to my host. 

The problem is easy to reproduce:
- Remove the image
- Add the user 100000, 154321 and 54321 to the host
- Enable user-namespacing with the entry in the file "/etc/docker/daemon.json" as described above
- Restart the docker-deamon
- Try to pull the image

Thanks for your help!

**Comment by gvenzl** [comment]
Hi @hofsa,

Unfortunately I'm not an expert when it comes to user-namespacing as said above. All I can tell you is that the database inside the container doesn't have permissions to create files on the file system. That should not be specific to the database as it's an OS level permission error.

Perhaps somebody else here has more experience with user-namespace mapping of Docker.

**Comment by hofsa** [comment]
Hi @gvenzl 
Thank you for your patience with my issue, but I still do not agree with your answer! :-)

We do have some experience regarding the user-namespacing in our company and I can asure you, that it is not a problem of "the container creating files":
- We are running a lot of different containers from a wide range of images and the oracle-image is the only one causing troubles
- The error happens when pulling the image --> At this stage, there is no container involved
- User-namespacing and file-permissions are tricky when mounting a host-filesystem into the container as avolume. But we do not mount a filesystem and we can't even start a container because the image-pull fails.
- While pulling the image, the database does not create files --> While pulling, no database-process is started

Therefore, I'm pretty sure that there is a problem within your image. There must be something special in one of the layers or the way you build the image...  Pulling the image should be independent of the content.

Is the Dockerfile for the image "database-enterprise:12.2.0.1" on GitHub?

**Comment by hofsa** [comment]
Hi @gvenzl 
I tried to build the image locally and was able to localize the problem. 
Looks like there is an issue with multistage-builds and user-namespacing. Other projects had simmilar issues. For example: [https://github.com/buildkite/elastic-ci-stack-for-aws/issues/392](https://github.com/buildkite/elastic-ci-stack-for-aws/issues/392)
I will do some more investigation next week.

**Comment by hofsa** [comment]
The error when pulling the image was caused by a to restrictive SubUID-range for the Docker remap-user.
In the files "/etc/subuid" and "/etc/subgid", only a range of 4096 was defined:
`docker-remap:100000:4097`
The "container-internal" oracle-user 54321 was mapped to the host-user 154321, which was not in the allowed range of 104096. 
Increasing the range was solving the problem:
`docker-remap:100000:65537`
