### ISSUE TITLE
why 11.2.0.2 can not build

### ISSUE THREAD

**Issue by yangfukai** [oracle/docker-images#1332]
![image](https://user-images.githubusercontent.com/17331289/61514312-615bbe80-aa32-11e9-8546-9849da7c5b7f.png)
![image](https://user-images.githubusercontent.com/17331289/61514338-6de01700-aa32-11e9-9452-cbd371dfe554.png)

**Comment by mrhappytech** [comment]
I would say that you need oracle-xe-11.2.0-1.0.x86_64.rpm.zip and before you will run build command you must convert all files to Linux format.
Try to run command: 
$ dos2unix.exe *.*

**Comment by yangfukai** [comment]
![image](https://user-images.githubusercontent.com/17331289/61941293-c468ca80-afc9-11e9-8875-0ed9c7615433.png)
![image](https://user-images.githubusercontent.com/17331289/61941353-df3b3f00-afc9-11e9-8352-131f158d857a.png)
come on man ! It still doesn't work !!!

**Comment by mrhappytech** [comment]
Hello, so I just tried it again for you.

`$ sh buildDockerImage.sh -x -v 11.2.0.2 -o "--memory=2g --memory-swap=2g"
Checking if required packages are present and valid...
md5sum: 'oracle-xe-11.2.0-1.0.x86_64.rpm.zip'$'\r': No such file or directory
: FAILED open or readx86_64.rpm.zip
md5sum: WARNING: 1 listed file could not be read`

I converted just one file in the end:

`$ dos2unix.exe Checksum.xe
dos2unix: converting file Checksum.xe to Unix format...`

The result:

`$ sh buildDockerImage.sh -x -v 11.2.0.2 -o "--memory=2g --memory-swap=2g"
Checking if required packages are present and valid...
oracle-xe-11.2.0-1.0.x86_64.rpm.zip: OK`

**Comment by yangfukai** [comment]
wow!It is work! thanks @mrhappytech
