### ISSUE TITLE
How to login using root user into docker container ?

### ISSUE THREAD

**Issue by aivl2018** [oracle/docker-images#1336]
How to login into docker container by root user. I tried below but i am getting below error.

Can anyone suggest here

[user@hostname ~]$ docker exec -it --user root f296ce6cf879 /bin/bash
**OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "chdir to cwd ("/u01/oracle") set in config.json failed: permission denied": unknown**

**Comment by MeloDai** [comment]
same problem

**Comment by azman6r6m1** [comment]
any specific reason to login as root since the docker user is oracle? this works for me.
`docker exec -it <container> bash`

**Comment by mark-au** [comment]
I believe this has been answered, you can specify the `--workdir` if you must log in as root.

**Comment by muditdevops** [comment]
> any specific reason to login as root since the docker user is oracle? this works for me.
> `docker exec -it <container> bash`

yes, if you want to update or install any external package we have to be root. As sudo is not supported in container.

**Comment by Djelibeybi** [comment]
> yes, if you want to update or install any external package we have to be root. As sudo is not supported in container.

You shouldn't be doing this inside a container. Rather, create your own image by modifying the Dockerfile to install the packages you want to update or install.

**Comment by mehsam** [comment]
https://www.baeldung.com/ops/root-user-password-docker-container
docker exec -it -u 0 image_name /bin/bash
