### ISSUE TITLE
Run problems with 11.2.0.2

### ISSUE THREAD

**Issue by mrhappytech** [oracle/docker-images#1337]
Hello, I have question about 11.2.0.2.

I am trying to run it under Windows 7 with Docker Toolbox.

**Build is OK.**

`sh buildDockerImage.sh -x -v 11.2.0.2 -o "--memory=2g --memory-swap=2g"`

I am not able to run it. Maybe I have problem with -v [<host mount point>:]. I have no idea where is problem in the end. I tried almost everything without success.

**Run command:**

`docker run --name oracle-xe \
--shm-size=2g \
-p 1521:1521 -p 8080:8080 \
-e ORACLE_PWD=mypassword \
-v oracledata:/u01/app/oracle/oradata \
oracle/database:11.2.0.2-xe`

**It will do this error:**

`mv: cannot stat '/etc/sysconfig/oracle-xe': No such file or directory
cp: cannot stat '/etc/oratab': No such file or directory
cp: cannot stat '/u01/app/oracle/oradata/dbconfig/XE/oratab': No such file or directory
grep: /etc/oratab: No such file or directory`

**I tried also create my own docker-compose:**

`version: '3.5'
services:
  oracle-xe:
    image: 'oracle/database:11.2.0.2-xe'
    shm_size: '2gb'
    ports:
      - '1521:1521'
      - '8080:8080'
    environment:
      - ORACLE_PWD=mypassword
    volumes:
      - './oracledata:/u01/app/oracle/oradata'
volumes:
  oracledata:
    driver: local`

**It will do this error:**

`cp: cannot stat '/u01/app/oracle/oradata/dbconfig/XE/oratab': No such file or directory
.......
mv: '/u01/app/oracle/product/11.2.0/xe/dbs/orapwXE' and '/u01/app/oracle/oradata/dbconfig/XE/orapwXE' are the same file
mv: cannot create symbolic link '/u01/app/oracle/oradata/dbconfig/XE/oracle-xe': Protocol error
cp: cannot stat '/etc/oratab': No such file or directory
cp: cannot stat '/u01/app/oracle/oradata/dbconfig/XE/oratab': No such file or directory
grep: /etc/oratab: No such file or directory`

How should I solve those problems? 
What am I doing wrong?

Thanks for answers in advance.

**Comment by yangfukai** [comment]
Can you provide your building resources?
just need link.
my e-mail:yk_carer@outlook.com

**Comment by mrhappytech** [comment]
Hi, 
I fixed it.

I think the problem was with VirtualBox. I was not able to run any database version. It was saying that I don't have enough free space in Virtual Machine. In the end I didn't extend space on virtual disk. I reinstalled all Docker Toolbox and VirtualBox. After that all works OK.
Anyway it is strange ...

#########################
DATABASE IS READY TO USE!
#########################
