### ISSUE TITLE
docker 12.1.0.2  database instance fails to start 

### ISSUE THREAD

**Issue by jcbrasuell** [oracle/docker-images#134]
docker 12.1.0.2 based database instance fails to start after docker image overall build successful. 

See highlights below.  Please let me know if you need any other log data.

================================================= Docker Build 
...
*** End of Installation Page***
The installation of Oracle Database 12c was successful.
INFO: Updating the global context
INFO: Path To 'globalcontext.xml' = /opt/oracle/product/12.1.0.2/dbhome_1/install/chainedInstall/globalcontext
INFO: Since operation was successful, move the current OiicAPISessionDetails to installed list
INFO: Number of root scripts to be executed = 2
INFO: isSuccessfullInstallation: true
INFO: isSuccessfullRemoteInstallation: true
INFO: Adding ExitStatus SUCCESS to the exit status set
INFO: Completed setting up InstallDB
INFO: Executing [/opt/oracle/product/12.1.0.2/dbhome_1/bin/diagsetup, clustercheck=false, basedir=/opt/oracle, oraclehome=/opt/oracle/product/12.1.0.2/dbhome_1]
with environment variables {ORACLE_HOME=/opt/oracle/product/12.1.0.2/dbhome_1, JAVA_HOME=, SHLVL=2, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt, CLASSPATH=, ORACLE_BASE=/opt/oracle, PATH=/usr/bin:/usr/ccs/bin:/opt/oracle/product/12.1.0.2/dbhome_1/bin:/opt/oracle/product/12.1.0.2/dbhome_1/OPatch/:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/oracle/install/database/install, CONFIG_RSP=dbca.rsp, INSTALL_FILE_1=linuxamd64_12102_database_1of2.zip, INSTALL_RSP=db_inst.rsp, INSTALL_FILE_2=linuxamd64_12102_database_2of2.zip, PWD=/opt/oracle/install, ORACLE_PDB=ORCLPDB1, PERL_INSTALL_FILE=installPerl.sh, HOSTNAME=9f6757744a2a, HOME=/home/oracle, INSTALL_DIR=/opt/oracle/install, ORACLE_SID=ORCLCDB, RUN_FILE=runOracle.sh, _=/opt/oracle/install/database/install/.oui, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat, LD_LIBRARY_PATH=/tmp/OraInstall2016-07-29_02-36-05PM/jdk/jre/lib/amd64/server:/tmp/OraInstall2016-07-29_02-36-05PM/jdk/jre/lib/amd64:/tmp/OraInstall2016-07-29_02-36-05PM/jdk/jre/../lib/amd64:/tmp/OraInstall2016-07-29_02-36-05PM/ext/bin:/tmp/OraInstall2016-07-29_02-36-05PM/ext/lib}
INFO: Starting Output Reader Threads for process /opt/oracle/product/12.1.0.2/dbhome_1/bin/diagsetup
WARNING: /opt/oracle/product/12.1.0.2/dbhome_1/bin/diagsetup: line 89: file: command not found
INFO: The process /opt/oracle/product/12.1.0.2/dbhome_1/bin/diagsetup exited with code 0
INFO: Waiting for output processor threads to exit.
INFO: Output processor threads exited.
INFO: Number of scripts to be executed as root user = 2
INFO: Shutting down OUISetupDriver.JobExecutorThread
INFO: Cleaning up, please wait...
INFO: All forked task are completed at state setup
INFO: Completed background operations
INFO: Moved to state <setup>
INFO: Waiting for completion of background operations
INFO: Completed background operations
INFO: Validating state <setup>
INFO: Completed validating state <setup>
INFO: Verifying route success
INFO: Waiting for completion of background operations
================================================= Docker Build end

=================================================  docker run begin
[root@ea7e7f 12.1.0.2]# docker run -p 1521:1521 -p 5500:5500 oracle/database:12.1.0.2-ee

 
LSNRCTL for Linux: Version 12.1.0.2.0 - Production on 29-JUL-2016 14:50:31
 
Copyright (c) 1991, 2014, Oracle.  All rights reserved.
 
Starting /opt/oracle/product/12.1.0.2/dbhome_1/bin/tnslsnr: please wait...
 
TNSLSNR for Linux: Version 12.1.0.2.0 - Production
System parameter file is /opt/oracle/product/12.1.0.2/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/708892e41fc9/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
 
Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.1.0.2.0 - Production
Start Date                29-JUL-2016 14:50:33
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           ORCLCDB
Listener Parameter File   /opt/oracle/product/12.1.0.2/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/708892e41fc9/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
 
SQL*Plus: Release 12.1.0.2.0 Production on Fri Jul 29 14:50:33 2016
 
Copyright (c) 1982, 2014, Oracle.  All rights reserved.
 
Connected to an idle instance.
 
SQL> ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/initORCLCDB.ora'
SQL> Disconnected
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining

[root@ea7e7f 12.1.0.2]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

=================================================  run end
 
================================================= ./8be36dcd376f034690416cd3a42914c830c26cbbed02cfdf519deabf8ddde6e9/opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log  begin ==========================
Unique database identifier check passed.

/ has enough space. Required space is 7665 MB , available space is 46841 MB.
File Validations Successful.
Copying database files
Error in Process: /opt/oracle/product/12.1.0.2/dbhome_1/bin/orapwd

Enter password for SYS:
Usage: orapwd file=<fname> entries=<users> force=<y/n> asm=<y/n>
       dbuniquename=<dbname> format=<legacy/12> sysbackup=<y/n> sysdg=<y/n>
       syskm=<y/n> delete=<y/n> input_file=<input-fname>

Usage: orapwd describe file=<fname>

  where
    file - name of password file (required),
    password - password for SYS will be prompted
               if not specified at command line.
               Ignored, if input_file is specified,
    entries - maximum number of distinct DBA (optional),
    force - whether to overwrite existing file (optional),
    asm - indicates that the password to be stored in
          Automatic Storage Management (ASM) disk group
          is an ASM password. (optional).
    dbuniquename - unique database name used to identify database
                   password files residing in ASM diskgroup only.
                   Ignored when asm option is specified (optional),
    format - use format=12 for new 12c features like SYSBACKUP, SYSDG and
             SYSKM support, longer identifiers, etc.
             If not specified, format=12 is default (optional),
    delete - drops a password file. Must specify 'asm',
             'dbuniquename' or 'file'. If 'file' is specified,
             the file must be located on an ASM diskgroup (optional),
    sysbackup - create SYSBACKUP entry (optional and requires the
                12 format). Ignored, if input_file is specified,
    sysdg - create SYSDG entry (optional and requires the 12 format),
            Ignored, if input_file is specified,
    syskm - create SYSKM entry (optional and requires the 12 format),
            Ignored, if input_file is specified,
    input_file - name of input password file, from where old user
                 entries will be migrated (optional),
    describe - describes the properties of specified password file
               (required).

  There must be no spaces around the equal-to (=) character.
DBCA_PROGRESS : DBCA Operation failed.
 
=================================================  ./8be36dcd376f034690416cd3a42914c830c26cbbed02cfdf519deabf8ddde6e9/opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log  end  =====================
[installActions2016-07-29_02-36-05PM.zip](https://github.com/oracle/docker-images/files/394139/installActions2016-07-29_02-36-05PM.zip)

**Comment by brunoborges** [comment]
See issue #123.

**Comment by brunoborges** [comment]
@gvenzl, mind to take a look? perhaps this case is different than #123?

**Comment by gvenzl** [comment]
This seems to be an issue with the password for the DBA accounts. Can you please confirm the following:

Did you invoke buildDockerImage.sh with `-p` and specify a password?  

If yes, did you have a space in it?  

If no, what is the password for `SYSPASSWORD` in the `dbca.rsp` response file?

**Comment by jcbrasuell** [comment]
No.  Did not run buildDockerImage.sh

I ran this:
docker build -t oracle/database:12.1.0.2-ee -f Dockerfile.ee .

[root@ea7e7f docker]# cat ./btrfs/subvolumes/dce3fa1e1159904ad492d6ba86b6bd619e0ae322438333e0ee10c8bfd6a8be12/opt/oracle/install/dbca.rsp | grep SYSPASSWORD
# Name          : SYSPASSWORD
SYSPASSWORD = "###ORACLE_PWD###"

**Comment by gvenzl** [comment]
Ok, that is the problem. The Dockerfile expects a password passed on for the DBA accounts. 

I just saw that the Dockerfile itself doesn't cover that yet in the comment section. 

Please try to rebuild the image using buildDockerFile.sh or using `--build-arg ORACLE_PWD=<Your DB password>`

**Comment by jcbrasuell** [comment]
Done.  Thanks Gerald!
