### ISSUE TITLE
how to copy the log4j.xml to the domain folder while building the Weblogic 1221 image

### ISSUE THREAD

**Issue by ganesh5756** [oracle/docker-images#1342]

**Comment by lennyphan** [comment]
To copy an updated log4j.xml to the WebLogic Server directory while building a new WebLogic docker image, update your Dockerfile with a command to copy the log4j.xml to the appropriate directory location.  For example, the following commands copy both the log4j.xml and log4j.properties file to the appropriate locations for the console application in the WebLogic server distribution:

# Copy log4j.properties for console application
COPY properties/docker-build/log4j.properties  ${ORACLE_HOME}/wlserver/server/lib/consoleapp/consolehelp/WEB-INF/classes

# Copy log4j.properties for console application
COPY properties/docker-build/log4j.xml  ${ORACLE_HOME}/wlserver/server/lib/consoleapp/webapp/WEB-INF/classes


NOTE: the two properties files (log4j.xml and log4j.properties) are assumed to be in the subdirectory 'properties/docker-build' from which the docker 'build' command is executed.

Please let me know if this was what you were looking for or not.

**Comment by mriccell** [comment]
@ganesh5756 pl;ease let us know if you still have questions

**Comment by mriccell** [comment]
closing
