### ISSUE TITLE
the env is not defined in the Dockerfile of  RAC 12.2.0.1. 

### ISSUE THREAD

**Issue by onetwobin** [oracle/docker-images#1347]
The error that (bash: /opt/scripts/install is a direcoty) is output when installed Oracle RAC.

The Problem may be bellowing. can you check that.
Path: OracleDatabase\RAC\OracleRealApplicationClusters\dockerfiles\12.2.0.1
file: Dockerfile
question:  $GRID_HOME_CLEANUP and $ORACLE_HOME_CLEANUP are not defined in 117L & 118L.
       `su  grid -c "$INSTALL_SCRIPTS/$GRID_HOME_CLEANUP" && \`
       `su  oracle -c "$INSTALL_SCRIPTS/$ORACLE_HOME_CLEANUP" && \ `

No error to build complete when defined bellowing in Dockerfile.
     `GRID_HOME_CLEANUP="GridHomeCleanup.sh" \`
     `ORACLE_HOME_CLEANUP="OracleHomeCleanup.sh" \`

**Comment by psaini79** [comment]
It is fixed. Please verify.  Please close this if the issue is fixed.

**Comment by onetwobin** [comment]
Thanks very much.
