### ISSUE TITLE
Can't connect to Oracle 12c Release 1 in docker container from host

### ISSUE THREAD

**Issue by yarhamjohn** [oracle/docker-images#1350]
I pulled the Oracle 12.1.0.2 docker image from the Oracle Container Registry (`container-registry.oracle.com/database/standard:12.1.0.2`) and created a container as per the instructions, leaving the environment file blank so as to keep all the parameters as their defaults (I am aware that I should change the password etc but right now I just want to get it working).

`$ docker run -d --env-file ./db_env.dat -p 1527:1521 -p 5507:5500 -it --name dockerDB --shm-size="8g" container-registry.oracle.com/database/standard`

I was able to successfully start the container, and can access it via `docker exec`. I was also able to verify that the Oracle instance was running correctly by executing some `sqlplus `against it from the shell inside the container.

However, I am not able to connect to the Oracle instance from my host machine, either through SQL Developer:

![image](https://user-images.githubusercontent.com/7828988/62767027-ac924b80-ba8b-11e9-80ce-a8461c1a5309.png)

or through `sqlplus`:

![SQLPlus](https://user-images.githubusercontent.com/7828988/62767008-a43a1080-ba8b-11e9-9e6a-3632670c56b2.PNG)

I get no errors, but the connection process just hangs forever. Do I need to change some setup somewhere or have I got the details wrong?

**Comment by gvenzl** [comment]
It sounds like our firewall or something else on your host is blocking you from reaching port `1527`. Please verify that you can connect to port `1527` or whichever port you are going to forward (probably the same for `5507`)
