### ISSUE TITLE
Unable to build connection manager v19

### ISSUE THREAD

**Issue by malagoli** [oracle/docker-images#1360]
Building command: ./buildDockerImage.sh -v 19.3.0
The building process is finishing with the following error:

Loaded plugins: ovl
Cleaning repos: ol7_UEKR5 ol7_developer_EPEL ol7_latest
su: System error
Removing intermediate container 704d0e326042
The command '/bin/sh -c chmod 755 $INSTALL_DIR/install/*.sh &&     sync &&     $INSTALL_DIR/install/$CHECK_SPACE_FILE &&     $INSTALL_DIR/install/$SETUP_LINUX_FILE &&     $INSTALL_DIR/install/$DB_SETUP_FILE  &&     sed -e '/hard *memlock/s/^/#/g' -i /etc/security/limits.d/oracle-database-preinstall-19c.conf &&     su - oracle -c "$INSTALL_DIR/install/$INSTALL_DB_BINARIES_FILE EE" &&     $INVENTORY/orainstRoot.sh &&     $DB_HOME/root.sh &&     rm -rf $INSTALL_DIR/install &&     rm -f /etc/sysctl.d/99-oracle-database-preinstall-19c-sysctl.conf &&     rm -f /etc/sysctl.d/99-sysctl.conf &&     rm -f /etc/rc.d/init.d/oracle-database-preinstall-19c-firstboot &&     rm -f /etc/security/limits.d/oracle-database-preinstall-19c.conf &&     rm -f $INSTALL_DIR/install/*  &&     chown -R oracle:oinstall $SCRIPT_DIR &&     chmod 755 $SCRIPT_DIR/*.sh &&     chmod 666 $SCRIPT_DIR/*.ora &&     sync' returned a non-zero code: 1

**Comment by psaini79** [comment]
@malagoli 

Please paste following output:
docker ps -a
uname -r
docker info
rpm -qa | grep docker
cat /etc/oracle-release

Were you able to build RAC 19.3.0 image? or same error? Did you disable selinux and firewalld?

**Comment by malagoli** [comment]
docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                       PORTS               NAMES

uname -r
4.14.35-1902.2.0.el7uek.x86_64

docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 18.09.1-ol
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
init version: fec3683
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.14.35-1902.2.0.el7uek.x86_64
Operating System: Oracle Linux Server 7.6
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 58.71GiB
Name: database-v19
ID: 2KHR:4CL7:32C4:JMJM:OFNN:DN2Y:J3X7:M2WO:3CCH:PNTZ:LDAJ:VXLD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

Registries: docker.io (secure)

rpm -qa | grep docker
docker-cli-18.09.1.ol-1.0.8.el7.x86_64
docker-engine-18.09.1.ol-1.0.8.el7.x86_64

cat /etc/oracle-release
Oracle Linux Server release 7.6

**Comment by psaini79** [comment]
@malagoli 

Please paste output of following:
getenforce
systemctl status firewalld
systemctl status iptables

This is strange that su oracle is not working and throwing system error.  Also, paste your dockerfile here, let check if there is any change in the file.

**Comment by malagoli** [comment]
Hi, disabling selinux solve the problem, perhaps has to be added in documentation.

In any case let me share my infos:

dockerfile: the one in master branch

getenforce
Enforcing

systemctl status firewalld
� firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2019-07-04 12:56:50 GMT; 1 months 21 days ago
     Docs: man:firewalld(1)
 Main PID: 3216 (code=exited, status=0/SUCCESS)

Jul 04 10:15:25 localhost.localdomain systemd[1]: Starting firewalld - dynamic firewall daemon...
Jul 04 10:15:25 localhost.localdomain systemd[1]: Started firewalld - dynamic firewall daemon.
Jul 04 12:56:49 database-v19 systemd[1]: Stopping firewalld - dynamic firewall daemon...
Jul 04 12:56:50 database-v19 systemd[1]: Stopped firewalld - dynamic firewall daemon.

systemctl status iptables
Unit iptables.service could not be found
