### ISSUE TITLE
Unable to connect to RAC Database

### ISSUE THREAD

**Issue by babloo2642** [oracle/docker-images#1365]
@psaini79 

Internally I’m able to connect to the database from both racnode1 and racnode2

[oracle@racnode1 ~]$ sqlplus system@"racnode-scan:1521/ORCLCDB"

SQL*Plus: Release 12.2.0.1.0 Production on Tue Aug 27 01:26:50 2019

Copyright (c) 1982, 2016, Oracle. All rights reserved.

Enter password:
Last Successful login time: Mon Aug 26 2019 19:08:59 +00:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL> quit
Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

[oracle@racnode2 ~]$ sqlplus system@"racnode-scan:1521/ORCLCDB"

SQL*Plus: Release 12.2.0.1.0 Production on Mon Aug 26 19:08:51 2019

Copyright (c) 1982, 2016, Oracle. All rights reserved.

Enter password:
Last Successful login time: Mon Aug 26 2019 18:35:30 +00:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL> quit
Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

#########################################################################

I’m unable to connect to RAC Database externally. From the racnode-cman1 able to connect, but from the docker host unable to telnet 1521.

[oracle@racnode-cman1 ~]$ lsnrctl status

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 27-AUG-2019 02:08:47

Copyright (c) 1991, 2016, Oracle. All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=3aa1690ab82b)(PORT=1521)))
TNS-12545: Connect failed because target host or object does not exist
TNS-12560: TNS:protocol adapter error
TNS-00515: Connect failed because target host or object does not exist
Linux Error: 2: No such file or directory
Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1521)))
TNS-12541: TNS:no listener
TNS-12560: TNS:protocol adapter error
TNS-00511: No listener
Linux Error: 2: No such file or directory

[root@xxxxx ~]# ping racnode-cman1
PING racnode-cman1.example.com (172.16.1.15) 56(84) bytes of data.
64 bytes from racnode-cman1.example.com (172.16.1.15): icmp_seq=1 ttl=64 time=0.027 ms
64 bytes from racnode-cman1.example.com (172.16.1.15): icmp_seq=2 ttl=64 time=0.033 ms
64 bytes from racnode-cman1.example.com (172.16.1.15): icmp_seq=3 ttl=64 time=0.033 ms
64 bytes from racnode-cman1.example.com (172.16.1.15): icmp_seq=4 ttl=64 time=0.033 ms
64 bytes from racnode-cman1.example.com (172.16.1.15): icmp_seq=5 ttl=64 time=0.030 ms
64 bytes from racnode-cman1.example.com (172.16.1.15): icmp_seq=6 ttl=64 time=0.033 ms
64 bytes from racnode-cman1.example.com (172.16.1.15): icmp_seq=7 ttl=64 time=0.032 ms
64 bytes from racnode-cman1.example.com (172.16.1.15): icmp_seq=8 ttl=64 time=0.033 ms
^C
--- racnode-cman1.example.com ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 6999ms
rtt min/avg/max/mdev = 0.027/0.031/0.033/0.007 ms

[root@xxxxx ~]# telnet racnode-cman1 1521
Trying 172.16.1.15...
telnet: connect to address 172.16.1.15: Connection refused

[oracle@xxxxx ~]$ sqlplus system@"racnode-cman1:1521/ORCLCDB"

SQL*Plus: Release 12.2.0.1.0 Production on Mon Aug 26 19:23:16 2019

Copyright (c) 1982, 2016, Oracle. All rights reserved.

Enter password:
ERROR:
ORA-12541: TNS:no listener

Enter user-name: system
Enter password:
ERROR:
ORA-12162: TNS:net service name is incorrectly specified

**Comment by psaini79** [comment]
@babloo2642 

Please paste following from docker host:
docker ps -a
systemctl status firewalld
netstat -apen | grep 1521

telnet <docker_host> 1521

Do following inside the racnode1 container as an Oracle user:
srvctl add service -d ORCLCDB -s testsvc -r "ORCLCDB1,ORCLCDB2"
srvctl start service -d ORCLCDB -s testsvc
lsnrctl status

Try to connect from racnode-cman using testsvc and try the same from docker host.

**Comment by babloo2642** [comment]
@psaini79 

Please find the below details:


[root@xxxxxx ~]# docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS               NAMES
050097bb5d42        oracle/database-rac:12.2.0.1   "/usr/sbin/oracleinit"   2 days ago          Up 2 days                               racnode2
d4a6d8e3e427        oracle/database-rac:12.2.0.1   "/usr/sbin/oracleinit"   2 days ago          Up 2 days                               racnode1
3417d5d5c975        oracle/client-cman:12.2.0.1    "/bin/sh -c 'exec $S…"   4 weeks ago         Up 4 weeks                              racnode-cman
[root@xxxxxx ~]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
[root@xxxxxx ~]# netstat -apen | grep 1521
[root@xxxxxxxx ~]# telnet xxxxxxxx 1521
Trying 171.65.64.137...
telnet: connect to address 171.65.64.137: Connection refused

####################################################

[oracle@racnode1 ~]$ srvctl add service -d ORCLCDB -s testsvc -r "ORCLCDB1,ORCLCDB2"
[oracle@racnode1 ~]$ srvctl start service -d ORCLCDB -s testsvc
[oracle@racnode1 ~]$ lsnrctl status

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 28-AUG-2019 23:50:59

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Connecting to (ADDRESS=(PROTOCOL=tcp)(HOST=)(PORT=1521))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                26-AUG-2019 17:24:52
Uptime                    2 days 6 hr. 26 min. 6 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /export/app/12.2.0/grid/network/admin/listener.ora
Listener Log File         /export/app/grid/diag/tnslsnr/racnode1/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=LISTENER)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=172.16.1.150)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=172.16.1.160)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=racnode1.example.com)(PORT=5500))(Security=(my_wallet_directory=/export/app/oracle/product/12.2.0/dbhome_1/admin/ORCLCDB/xdb_wallet))(Presentation=HTTP)(Session=RAW))
Services Summary...
Service "+ASM" has 1 instance(s).
  Instance "+ASM1", status READY, has 1 handler(s) for this service...
Service "+ASM_DATA" has 1 instance(s).
  Instance "+ASM1", status READY, has 1 handler(s) for this service...
Service "9109c53c3bca460de053960110ac09f3" has 1 instance(s).
  Instance "ORCLCDB1", status READY, has 1 handler(s) for this service...
Service "ORCLCDB" has 1 instance(s).
  Instance "ORCLCDB1", status READY, has 1 handler(s) for this service...
Service "ORCLCDBXDB" has 1 instance(s).
  Instance "ORCLCDB1", status READY, has 1 handler(s) for this service...
Service "orclpdb" has 1 instance(s).
  Instance "ORCLCDB1", status READY, has 1 handler(s) for this service...
Service "testsvc" has 1 instance(s).
  Instance "ORCLCDB1", status READY, has 1 handler(s) for this service...
The command completed successfully

##############################################


[oracle@racnode-cman1 ~]$ sqlplus system@xxxxxx:1521/ORCLCDB -s testsvc

SQL*Plus: Release 12.2.0.1.0 Production

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Use SQL*Plus to execute SQL, PL/SQL and SQL*Plus statements.

Usage 1: sqlplus -H | -V

    -H		   Displays the SQL*Plus version and the
		   usage help.
    -V		   Displays the SQL*Plus version.

Usage 2: sqlplus [ [<option>] [{logon | /nolog}] [<start>] ]

  <option> is: [-AC] [-C <version>] [-L] [-M "<options>"] [-NOLOGINTIME] [-R <level>]
	       [-S]

    -AC 	   Enable Application Continuity.
    -C <version>   Sets the compatibility of affected commands to the
		   version specified by <version>.  The version has
		   the form "x.y[.z]".	For example, -C 10.2.0
    -L		   Attempts to log on just once, instead of
		   reprompting on error.
    -M "<options>" Sets automatic HTML or CSV markup of output.  The options
		   have the form:
		   {HTML html_options|CSV csv_options}
		   See SQL*Plus User's Guide for detailed HTML and CSV options.
    -NOLOGINTIME   Don't display Last Successful Login Time.
    -R <level>	   Sets restricted mode to disable SQL*Plus commands
		   that interact with the file system.	The level can
		   be 1, 2 or 3.  The most restrictive is -R 3 which
		   disables all user commands interacting with the
		   file system.
    -S		   Sets silent mode which suppresses the display of
		   the SQL*Plus banner, prompts, and echoing of
		   commands.

  <logon> is: {<username>[/<password>][@<connect_identifier>] | / }
	      [AS {SYSDBA | SYSOPER | SYSASM | SYSBACKUP | SYSDG | SYSKM | SYSRAC}] [EDITION=value]

    Specifies the database account username, password and connect
    identifier for the database connection.  Without a connect
    identifier, SQL*Plus connects to the default database.

    The AS SYSDBA, AS SYSOPER, AS SYSASM, AS SYSBACKUP, AS SYSDG,
    AS SYSKM and AS SYSRAC options are database administration privileges.

    <connect_identifier> can be in the form of Net Service Name
    or Easy Connect.

      @[<net_service_name> | [//]Host[:Port]/<service_name>]

	<net_service_name> is a simple name for a service that resolves
	to a connect descriptor.

	Example: Connect to database using Net Service Name and the
		 database net service name is ORCL.

	   sqlplus myusername/mypassword@ORCL

	Host specifies the host name or IP address of the database
	server computer.

	Port specifies the listening port on the database server.

	<service_name> specifies the service name of the database you
	want to access.

	Example: Connect to database using Easy Connect and the
		 Service name is ORCL.

	   sqlplus myusername/mypassword@Host/ORCL

    The /NOLOG option starts SQL*Plus without connecting to a
    database.

    The EDITION specifies the value for Session Edition.


  <start> is: @<URL>|<filename>[.<ext>] [<parameter> ...]

    Runs the specified SQL*Plus script from a web server (URL) or the
    local file system (filename.ext) with specified parameters that
    will be assigned to substitution variables in the script.

When SQL*Plus starts, and after CONNECT commands, the site profile
(e.g. $ORACLE_HOME/sqlplus/admin/glogin.sql) and the user profile
(e.g. login.sql in the working directory) are run.  The files may
contain SQL*Plus commands.

Refer to the SQL*Plus User's Guide and Reference for more information.

########################################

[oracle@xxxxxx ~]$ sqlplus system@xxxxxxx:1521/ORCLCDB -s testsvc
-bash: sqlplus: command not found

###########################################

I think after running the srvctl command, I’m unable to connect to db from the racnode1 and racnode2

[oracle@racnode1 ~]$ sqlplus system@"racnode-scan:1521/ORCLCDB"

SQL*Plus: Release 12.2.0.1.0 Production on Thu Aug 29 05:47:01 2019

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

ERROR:
ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA


Enter user-name: system
Enter password: 
ERROR:
ORA-12162: TNS:net service name is incorrectly specified


[oracle@racnode2 ~]$ sqlplus system@"racnode-scan:1521/ORCLCDB"

SQL*Plus: Release 12.2.0.1.0 Production on Thu Aug 29 05:48:21 2019

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

ERROR:
ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA


Enter user-name: system
Enter password: 
ERROR:
ORA-12162: TNS:net service name is incorrectly specified

**Comment by psaini79** [comment]
@babloo2642 

It seems you have binded the CMAN container to docker host on port 1521. Can you paste the command of cman container creation?

Also, paste the output of following:
docker inspect racnode-cman1

**Comment by babloo2642** [comment]
@psaini79 

Please find the output below:
Container creation command:
/usr/bin/docker run -d --hostname racnode-cman1 --dns-search=example.com \
--network=rac_pub1_nw --ip=172.16.1.15 \
-e DOMAIN=example.com -e PUBLIC_IP=172.16.1.15 \
-e PUBLIC_HOSTNAME=racnode-cman1 -e SCAN_NAME=racnode-scan \
-e SCAN_IP=172.16.1.70 --privileged=false \
-p 1521:1521 --name racnode-cman oracle/client-cman:12.2.0.1


[root@xxxxxxx ~]# docker inspect racnode-cman
[
    {
        "Id": "3417d5d5c9756a95884c680191945c6e489ce9ac197af0fd56537e4c34c1401b",
        "Created": "2019-07-29T11:26:29.198470975Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "exec $SCRIPT_DIR/$RUN_FILE"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 5334,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-07-29T11:26:29.658200778Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:0cf079c49ea9e5e352a61268c712b95084a782e6a8ecde22962a2ccd087db225",
        "ResolvConfPath": "/var/lib/docker/containers/3417d5d5c9756a95884c680191945c6e489ce9ac197af0fd56537e4c34c1401b/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/3417d5d5c9756a95884c680191945c6e489ce9ac197af0fd56537e4c34c1401b/hostname",
        "HostsPath": "/var/lib/docker/containers/3417d5d5c9756a95884c680191945c6e489ce9ac197af0fd56537e4c34c1401b/hosts",
        "LogPath": "/var/lib/docker/containers/3417d5d5c9756a95884c680191945c6e489ce9ac197af0fd56537e4c34c1401b/3417d5d5c9756a95884c680191945c6e489ce9ac197af0fd56537e4c34c1401b-json.log",
        "Name": "/racnode-cman",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "rac_pub1_nw",
            "PortBindings": {
                "1521/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "1521"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [
                "example.com"
            ],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/e0169789f18ced253f193ece7a5431a4085b24086b108abe7be0b74adafab44e-init/diff:/var/lib/docker/overlay2/f582404840daf4576790f1f7de8ebf8940c978a14224567bb8f6497c0537c56f/diff:/var/lib/docker/overlay2/a2dab70d1c59f8bab2cf4960edd2a027a51565612162ccd59dfd55572a362119/diff:/var/lib/docker/overlay2/8cdb48f15db807c121379d9b96a086d5e6d6fb4d2dcf992e9eaffbc6aabfdbef/diff:/var/lib/docker/overlay2/fd97274c9f923739e95db4eae008bc23f807290f8acb6a657fde95f3fa725f03/diff:/var/lib/docker/overlay2/5e94ee3c26f2b47711f4648dfc14697959b0f4129e80562a3e46712ec28731f5/diff:/var/lib/docker/overlay2/d844843e5ea5487c412801ea2a89cce8738819fa47c498b49acc6c16d0b072d3/diff",
                "MergedDir": "/var/lib/docker/overlay2/e0169789f18ced253f193ece7a5431a4085b24086b108abe7be0b74adafab44e/merged",
                "UpperDir": "/var/lib/docker/overlay2/e0169789f18ced253f193ece7a5431a4085b24086b108abe7be0b74adafab44e/diff",
                "WorkDir": "/var/lib/docker/overlay2/e0169789f18ced253f193ece7a5431a4085b24086b108abe7be0b74adafab44e/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "racnode-cman1",
            "Domainname": "",
            "User": "oracle",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1521/tcp": {},
                "5500/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DOMAIN=example.com",
                "PUBLIC_IP=172.16.1.15",
                "PUBLIC_HOSTNAME=racnode-cman1",
                "SCAN_NAME=racnode-scan",
                "SCAN_IP=172.16.1.70",
                "PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "SETUP_LINUX_FILE=setupLinuxEnv.sh",
                "INSTALL_DIR=/opt/scripts",
                "INVENTORY=/export/app/oraInventory",
                "DB_BASE=/export/app/oracle",
                "DB_HOME=/export/app/oracle/product/12.2.0/client_1",
                "INSTALL_FILE_1=linuxx64_12201_client.zip",
                "DB_INSTALL_RSP=client.rsp",
                "DB_SETUP_FILE=setupDB.sh",
                "RUN_FILE=runOracle.sh",
                "CONFIG_CMAN_FILE=configCMAN.sh",
                "CHECK_SPACE_FILE=checkSpace.sh",
                "CMANORA=cman.ora",
                "FUNCTIONS=functions.sh",
                "INSTALL_DB_BINARIES_FILE=installDBBinaries.sh",
                "container=true",
                "INSTALL_SCRIPTS=/opt/scripts/install",
                "SCRIPT_DIR=/opt/scripts/startup",
                "DB_PATH=/export/app/oracle/product/12.2.0/client_1/bin:/export/app/oracle/product/12.2.0/client_1/OPatch/:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DB_LD_LIBRARY_PATH=/export/app/oracle/product/12.2.0/client_1/lib:/usr/lib:/lib"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "exec $SCRIPT_DIR/$RUN_FILE"
            ],
            "ArgsEscaped": true,
            "Image": "oracle/client-cman:12.2.0.1",
            "Volumes": null,
            "WorkingDir": "/home/oracle",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "0dcd18f9a2ec2bdd3146b4e5d3dcce8e6bf45a27e004c77d11a4fa15ea75f144",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/0dcd18f9a2ec",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "rac_pub1_nw": {
                    "IPAMConfig": {
                        "IPv4Address": "172.16.1.15"
                    },
                    "Links": null,
                    "Aliases": [
                        "3417d5d5c975"
                    ],
                    "NetworkID": "dce10788a9f696fddbfd922199fb6df60fe9a101e1d444716cd3ae1592b3b55b",
                    "EndpointID": "fdf6fe17a615af87f68e924b8754d79bcac088193980c162ef4549fd770b4801",
                    "Gateway": "172.16.1.1",
                    "IPAddress": "172.16.1.15",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:10:01:0f",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by psaini79** [comment]
@babloo2642 

The command seems to be fine. I am wondering why netstat -apen | grep 1521 output nothing. Can you heck again  if there is any process listening on port 1521 on docker host?

**Comment by babloo2642** [comment]
@psaini79 

Still the output is nothing:

[root@xxxxx ~]# netstat -apen | grep 1521
[root@xxxxx ~]#

**Comment by psaini79** [comment]
@babloo2642 ,

I am not sure why the port is not mapped to docker host, can you please stop racnode-cman1 container, delete the container and recreate it.

Paste the following output:
netstat -tpln | grep 1521

**Comment by psaini79** [comment]
I have following output on  my machine and I am able to  telnet:

netstat -tpln | grep 1521
tcp6       0      0 :::1521                 :::*                    LISTEN      15167/docker-proxy

CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                    NAMES
719c764a19d9        oracle/database-rac:12.2.0.1   "/usr/sbin/oracleinit"   29 hours ago        Up 29 hours         0.0.0.0:6043->22/tcp                                     racnode2
f31fa63a9e5a        oracle/database-rac:12.2.0.1   "/usr/sbin/oracleinit"   29 hours ago        Up 29 hours         0.0.0.0:6042->22/tcp                                     racnode1
6831ad678460        oracle/client-cman:12.2.0.1    "/bin/sh -c 'exec $S…"   29 hours ago        Up 29 hours         0.0.0.0:1521->1521/tcp, 5500/tcp, 0.0.0.0:6044->22/tcp   racnode-cman1

**Comment by babloo2642** [comment]
@psaini79 

I have recreated it. Please find the details below:

[root@xxxxxx ~]# docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS               NAMES
2fa25f66b822        oracle/client-cman:12.2.0.1    "/bin/sh -c 'exec $S…"   7 minutes ago       Up 7 minutes                            racnode-cman
050097bb5d42        oracle/database-rac:12.2.0.1   "/usr/sbin/oracleinit"   3 days ago          Up 3 days                               racnode2
d4a6d8e3e427        oracle/database-rac:12.2.0.1   "/usr/sbin/oracleinit"   3 days ago          Up 3 days                               racnode1
[root@xxxxx ~]# netstat -tpln | grep 1521
[root@xxxxx ~]#

**Comment by psaini79** [comment]
@babloo2642 

I tried to reproduced this issue on my server and did not face this issue. Can you please SR with Oracle Linux team as this issue more docker specific.

**Comment by mark-au** [comment]
Did you raise an SR? Was your problem resolved?
