### ISSUE TITLE
Unable to get oracle instant client

### ISSUE THREAD

**Issue by RizziWilliam** [oracle/docker-images#1366]
Have been trying to use oracle instant client on a docker file, but i can't manage to get it to work. Have been looking into issues to find out what was doing wrong without sucess. 
The error that i'm getting: `pull access denied for oracle/instantclient, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

I have seen people saying about doing a login into oracle, but doesn't understand where should i do it.

Edit: The database is in a different computer from the backend.

**Comment by shnplr** [comment]
I built the image myself:

```
git clone https://github.com/oracle/docker-images.git
cd docker-images/OracleInstantClient/dockerfiles/12.2.0.1/
cp <DOWNLOAD_LOC>/oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm .
cp <DOWNLOAD_LOC>/oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm .
cp <DOWNLOAD_LOC>/oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm .
docker build --pull -t oracle/instantclient:12.2.0.1 .
```

**Comment by cjbj** [comment]
@RizziWilliam what's your Dockerfile?

The 19.3 client will connect to the same DB versions as 12.2, so make life easy and use the [19.3 Dockerfile](https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/19/Dockerfile) which will automatically pull in Instant Client RPMs without needing any login or copying.

**Comment by RizziWilliam** [comment]
This is my dockerfile in the moment

```
FROM node:10.16.0-stretch-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM node:10.16.0-stretch-slim
WORKDIR /app
COPY --from=builder /app .
EXPOSE 3000
ENV API_PORT=3000
ENV NODE_ENV=production
CMD ["npm", "start"]
```

**Comment by cjbj** [comment]
Ah you're using Node.js.  Look at:

- https://blogs.oracle.com/opal/dockerfiles-for-node-oracledb-are-easy-and-simple

- https://learncodeshare.net/2019/08/27/howto-connect-your-nodejs-app-in-docker-to-your-oracle-database/

If you want to continue with node:10.16.0-stretch-slim, then you may prefer to add Instant Client ZIPs, which you will have to manually download as @shnplr did, see https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/12.2.0.1/Dockerfile  For Node.js the related installation instructions for using Instant Client ZIPs are https://oracle.github.io/node-oracledb/INSTALL.html#instzip

**Comment by RizziWilliam** [comment]
I managed to make it work.

```
FROM node:10.16.0-stretch-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM node:10.16.0-stretch-slim
WORKDIR /app
RUN apt-get update && apt-get install -y alien libaio1 
ADD oracle-instantclient*.rpm /tmp/
RUN alien -i /tmp/oracle-instantclient*.rpm && \
    rm -rf /var/cache/yum && \
    rm -f /tmp/oracle-instantclient*.rpm && \
    echo /usr/lib/oracle/12.2/client64/lib > /etc/ld.so.conf.d/oracle-instantclient12.2.conf && \
    ldconfig
COPY --from=builder /app .
EXPOSE 3000
ENV API_PORT=3000
ENV NODE_ENV=production
ENV PATH=$PATH:/usr/lib/oracle/12.2/client64/bin
CMD ["npm", "start"]
```

You guys are actually helping me out in other issue on oracledb. Going to close this issue and let the link to there case someone want to se the result from this. https://github.com/oracle/node-oracledb/issues/1147

**Comment by cjbj** [comment]
Thank's for the update.

It's probably easier to use the Instant Client zips instead of bothering with Alien.

And I would still suggest using 19.3
