### ISSUE TITLE
SQLDeveloper remote debugger to oracle db container

### ISSUE THREAD

**Issue by ksawerykarwacki** [oracle/docker-images#1372]
I am using Docker for Windows and run my Oracle container like this: 

```
docker run -d --expose 4000 -p 14000:4000 -p 11521:1521 -p 15500:5500 --name Oracle oracle12c_empty:latest
```

This image has an instance predefined and some initial configs but it is based on Oracle 12c EE image.

My schema is named test and my machine is named MY_COMPUTER so i run:

```
grant debug connect session to test;
grant execute on dbms_debug_jdwp to test;
 
begin
dbms_network_acl_admin.append_host_ace(
HOST=>'MY_COMPUTER',
ace=> SYS.xs$ace_type(
privilege_list=>SYS.xs$name_list('JDWP'),
principal_name=>'test',
principal_type=>SYS.xs_acl.ptype_db)
);
end;
```

My assumption is that I need additional port to 1521 and 5500 for debugger so I exposed 4000, but if I try attach remote debugger at localhost:14000 I receive:

The debugger is not able to listen for JPDA using the specified parameters.

How should I configure this?

**Comment by gvenzl** [comment]
Hi @ksawerykarwacki,

As this is related to debugging via SQL Developer and an Oracle Database inside a container, which has nothing to do with the build files provided in this repository, you are better off posting your question on the [SQL Developer forum](https://community.oracle.com/community/groundbreakers/database/developer-tools/sql_developer).

The issues for this repository are to handle general questions and issues for the build files provided.

Thanks,

**Comment by phartenfeller** [comment]
Had the same issue, and @PhilippSalvisberg helped me fix it and explained the issue in more detail [here](https://gist.github.com/PhilippSalvisberg/2f2853bc7a95fa86d9de9c0deab10602).

Using `127.0.0.1` won't work from within the container; instead, I ran `ipconfig getifaddr en0` and used that address to connect with the debugger. Make sure the ACL is set up for that. Philipp uses a wildcard in the linked Gist.
