### ISSUE TITLE
LINUX.X64_193000_db_home.zip: no such file or directory

### ISSUE THREAD

**Issue by Costonied** [oracle/docker-images#1381]
**OS:** macOS Mojave version 10.14.6

I have run `sudo ./buildDockerImage.sh 12.2.0.2 -e`
But received the error:

> Step 10/23 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
> COPY failed: stat /var/lib/docker/tmp/docker-builder613747487/LINUX.X64_193000_db_home.zip: no such file or directory

Could anybody help with it?

**Comment by Costonied** [comment]
I was so blind.

> IMPORTANT: You will have to provide the installation binaries of Oracle Database and put them into the dockerfiles/<version> folder. You only need to provide the binaries for the edition you are going to install. The binaries can be downloaded from the Oracle Technology Network, make sure you use the linux link: Linux x86-64

**Comment by huxaiphaer** [comment]
Hi @Costonied , I downloaded the binaries in this path `docker-images/oracle database/singleinstance/dockerfiles` but I still get the same error, what could be wrong

**Comment by anibal21** [comment]
It worked for me for version 19.3.0, downloading version 19.3 from here https://www.oracle.com/cl/database/technologies/oracle-database-software-downloads.html called Linux x86-64. And I put the zip inside the folder dockerfiles/19.3.0/.

**Comment by mustybatz** [comment]
I had the same issue, it worked by running the build script and setting the `SLIMMING` flag to false:
`./buildContainerImage.sh -v 19.3.0 -e -o '--build-arg SLIMMING=false'`

**Comment by dtesch** [comment]
It would have been better if you had put the installation binaries in the same folder as the Dockerfile. For the 19.3 version, you need to put the file in `OracleDatabase/SingleInstance/dockerfiles/19.3.0`
