### ISSUE TITLE
Add volume mount for Instant Client to use wallet

### ISSUE THREAD

**Issue by martindsouza** [oracle/docker-images#1385]
For the [Oracle Instant Client](https://github.com/oracle/docker-images/tree/master/OracleInstantClient) can we add a volume mount so that we can reference a wallet. Reason: ATP connections.

Not sure if `TNS_ADMIN` env variable should be set by default or only defined during the `run` statement if a wallet is being used. Perhaps could also include a script to detect if files are present in the volume mount location and then automatically set the `TNS_ADMIN` env.

Ex: `export TNS_ADMIN=/home/jdoe/.wallets/atp01`

cc: @gvenzl

**Comment by cjbj** [comment]
You can indeed easily add a wallet mount (as I suspect you know).  

You don't need to set TNS_ADMIN.  With `docker run`, you can add something like:

```
-v /my/host/walletdir:/usr/lib/oracle/19.3/client64/lib/network/admin:ro
```

Also see https://static.rainfocus.com/oracle/oow19/sess/1553560683840001mfXq/PF/DEV4626-Developing-and-Deploying-Python-and-Node.js-Applications-in-Docker_1568845042122001Vsfl.pdf   (For Oracle Linux you probably don't need/want to use `:Z`.)

I plan to mention this in the repo and Dockerfile header documentation but PRs are welcome.

**Comment by cjbj** [comment]
@martindsouza my PR was merged: https://github.com/oracle/docker-images/pull/1394
