### ISSUE TITLE
Oracle Database 19.3.0 /bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory

### ISSUE THREAD

**Issue by AjeshM** [oracle/docker-images#1387]
Oracle databse 19.3.0. Image building failed.
I'm attaching two log files one is terminal window log and the other is Installaction of Oracle.
I've gone through previous issues of same heading. But i dont find any issue with memory or hardisk space.
[InstallationActionLog.txt](https://github.com/oracle/docker-images/files/3665497/InstallationActionLog.txt)
[TerminalWindowLog.txt](https://github.com/oracle/docker-images/files/3665499/TerminalWindowLog.txt)
Hope it'll help to find the issue. Thanks

**Comment by gvenzl** [comment]
I cannot reproduce this nor should it have happened on a clean install. The `orainstRoot.sh` script is only not created if an oraInventory is already present.

Was there any cached/dangling image beforehand?
Is this issue reproducible?
