### ISSUE TITLE
OracleDatabase: Error when trying to compile procedure in native mode in Docker Swarm

### ISSUE THREAD

**Issue by jlafourc** [oracle/docker-images#1396]
Hi,

I'd like to open an issue related to #1302

We used the information provided to run OracleDB on our computers with a standard docker run. 

But we would like to do it in docker swarm. I couldn't fin a way to specify the correct options for tmpfs /dev/shm volume. 

Anyone did it successfully ? 

Thank you

Julien

**Comment by gvenzl** [comment]
Unfortunately, I'm not a Docker Swarm expert.
Perhaps others in this repo are, but I highly recommend the Docker forum for your question.

**Comment by gvenzl** [comment]
@Djelibeybi do you have any ideas?

**Comment by Djelibeybi** [comment]
No idea on Swarm either, I'm afraid. Oracle seems to have standardised on Kubernetes for container orchestration.

**Comment by jlafourc** [comment]
I think we can close this one. 

Definitely not possible in Swarm
