### ISSUE TITLE
Unable to set Delivery Failure Options for the JMS Queue's

### ISSUE THREAD

**Issue by bgundubi** [oracle/docker-images#1401]
Hi Team,

we want to set  Delivery Failure Options for JMS Queues while creating a docker image for Weblogic.

**Comment by mriccell** [comment]
I will create a PR to demonstrate how to set Delivery Failure Options for JMS Queues.

**Comment by mriccell** [comment]
You need to configure these options  https://docs.oracle.com/middleware/12213/wls/WLACH/pagehelp/JMSjmsdestinationsjmsqueueredeliverytitle.html#attributes n the WLST script https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/12213-domain-with-resources/container-scripts/jms-deploy.py
