### ISSUE TITLE
Reduce default size of container

### ISSUE THREAD

**Issue by mlechler** [oracle/docker-images#1402]
Hi,

is it possible to reduce the default container size of 25GB? Is there a flag or something else?

Best regards
Marcel

**Comment by Djelibeybi** [comment]
Which container? There are lots.

**Comment by mlechler** [comment]
Sorry, I forgot to specify... The OracleDatabase -> SingleInstance container comes with a default of 25GB storage requirement. Is this really needed or could it be decreased? Is it only required for the image build?

**Comment by Djelibeybi** [comment]
That's only if you're using the dm-loop driver. Switch to the recommend btrfs or overlay2 storage drivers instead as they don't require allocated storage.

**Comment by mlechler** [comment]
I'm on the overlay2 storage driver since the beginning. If I try to build the image my storage (currently 20GB, at the moment not more possible) runs full and the process gets stuck.

**Comment by Djelibeybi** [comment]
I'll let @gvenzl take it from here then.

**Comment by gvenzl** [comment]
I'm not sure how multi-stage builds affect the default image size. It could easily be that they all count together during the build and hence why you need that much space.

The resulting image is only around 6GB for 19c, which is thankfully much smaller than the default settings.

Can you share your output where it hangs and also `docker images` to see how big they are, please?

**Comment by mlechler** [comment]
Hi, the build looks like this...
1. **df -h**, before build:
![image](https://user-images.githubusercontent.com/22612468/66982052-a933c580-f0b5-11e9-8931-909480992341.png)
2. **docker system df**:
![image](https://user-images.githubusercontent.com/22612468/66982494-82c25a00-f0b6-11e9-812e-2dc101c844bf.png)
3. **docker build packages/oracle** pulls the 4,8GB image and tries to build it:
![image](https://user-images.githubusercontent.com/22612468/66983387-bc946000-f0b8-11e9-8419-69ad06aa8fed.png)
![image](https://user-images.githubusercontent.com/22612468/66983409-cf0e9980-f0b8-11e9-88db-664893cc0911.png)
Dockerfile looks simple, currently we are using a prebuilt image:
> FROM container-registry.oracle.com/database/standard:12.1.0.2
> COPY nginx.conf /etc/nginx/conf.d/default.conf
4. **docker run**, after untar the DB:
![image](https://user-images.githubusercontent.com/22612468/66984190-8a83fd80-f0ba-11e9-81c6-52ddd3ce4df4.png)
5. It keeps stuck in the task "config DB" and exits with an error:
![image](https://user-images.githubusercontent.com/22612468/66985566-5c53ed00-f0bd-11e9-8878-25ba83e41786.png)
**configDB.log**:
![image](https://user-images.githubusercontent.com/22612468/66985622-7beb1580-f0bd-11e9-831d-29f85b02b3c5.png)
**configDBora.log**:
![image](https://user-images.githubusercontent.com/22612468/66985774-c9678280-f0bd-11e9-9a00-552243dc5411.png)
**df -h**:
![image](https://user-images.githubusercontent.com/22612468/66985807-df754300-f0bd-11e9-80a2-d292d31409ca.png)
**docker system df**:
![image](https://user-images.githubusercontent.com/22612468/66985840-f156e600-f0bd-11e9-8858-f9eea430fd3a.png)

Honestly....this is the first time I tried to run it without docker-compose, so I'm a little bit surprised...
I think the fast exceedance then depends on the composition of all images. I guess it can also happen that we exceed the storage size when the config is successful.

Our build chain is designed to build and run the containers via docker-compose, andI think the size during the build and config can't be reduced?

Would the size be smaller if I build an 19c image with the scripts?

**Comment by gvenzl** [comment]
I see from the last post that the image in question is one from container-registry.oracle.com, which is not the same images as the scripts here on GitHub will create.

Can you try with an image from this repository, building it yourself? All of them should be well below 10GB.
