### ISSUE TITLE
How to make database instance persistent?

### ISSUE THREAD

**Issue by tkleiber** [oracle/docker-images#141]
Hi!

Is there any documentation, how I can separate the database installation in docker container from the database instance data in a persistent volume?
Is this possible with this images?

Kind regards
Torsten

**Comment by gvenzl** [comment]
Hi @tkleiber,

At this point in time this isn't possible with those images but this is something that we are investigating.

I'll leave this issue open to act as a tracker for this.

Thanks,

**Comment by sigaELwebeo** [comment]
This guy builds a oracleDB image and uses persistence storage.
https://fritshoogland.wordpress.com/2015/08/11/installing-the-oracle-database-in-docker/

He volumes the folder "/u01/app/oracle/data" inside the container. No clue wich one will be in this installation.

**Comment by ramonPires** [comment]
@sigaELwebeo you tryed the solution using volumes? I tryed creating a volume for the folder "/u01/app/oracle/oradata/XE" and "/u01/app/oracle/",but don't work, the oracle instance could not be mounted.  I tryed with this: `docker create --name oracle  -v /Users/ramon/Development/docker/database/oracle:/u01/app/oracle --shm-size=1g -p 1521:1521 -p 8080:8080 -p 1234:22 oracle/database:11.2.0.2-xe` .

**Comment by ratroncoso** [comment]
Y did persistent data but in an awful way!!!

1.- Create a container1 with volume:
          /docker/volumes/oradb:/opt/oracle/oradata
     and it was empty.

2.- Create a container2 with volume /docker/volumes/oradb:/data
     Docker exec on it and copy the entire ORCLCDB folder to /data
     
3.- Docker exec into container 1, chown and chmod on ORCLCDB
     Copy and replace file /opt/oracle/oradata/ORCLCDB/control01.ctl to /opt/oracle/fast_recovery_area/ORCLCDB/control02.

4.- Delete container2.

I'm waiting to have more availability to modify Dockerfile to build oradata folder and expose as volume.

**Comment by ramonPires** [comment]
With this image, https://github.com/MaksymBilenko/docker-oracle-xe-11g , I can mount a volume with the way I want, but I really want is use the official image.  @ratroncoso I will try your solution,thank you.

**Comment by ramonPires** [comment]
@ratroncoso Your solution is for oracle 12c, right? I'm asking because the folders hierarchy are different on Oracle 11 XE.

**Comment by ratroncoso** [comment]
Oracle Database Enterprise Edition 12C

**Comment by ramonPires** [comment]
@ratroncoso did you try with  Oracle 11g XE or just Oracle 12c?

**Comment by ratroncoso** [comment]
@ramonPires only on Oracle12c

**Comment by ramonPires** [comment]
@gvenzl any update about this issue? I found other solution, http://marceloochoa.blogspot.com.br/2016/06/is-time-for-oracle-xe-on-docker.html ,but I don't  test yet.

**Comment by gvenzl** [comment]
With the latest commit we now have containers that provide persistence for all database editions.

**Comment by tkleiber** [comment]
When starting the xe docker container in vagrant box via

docker run  ... --restart unless-stopped

and calling

vagrant halt
vagrant up

the docker container comes up after this, as I can see via docker ps, but database is not available.

Have to do to make the database available again via

docker stop container
docker start container

**Comment by brunoborges** [comment]
@tkleiber can you provide logs of what's happening? really hard to figure out what's going on.

We'd also appreciate if you could post a new issue with these logs.

**Comment by tkleiber** [comment]
How can I find this logs?

**Comment by brunoborges** [comment]
`$ docker logs` should be a good start

**Comment by KamilJedrzejuk** [comment]
@brunoborges I have some problems with oracle https://github.com/oracle/docker-images/issues/1480
