### ISSUE TITLE
permissison denied error while running domain for 1213-domain

### ISSUE THREAD

**Issue by sandeep-git-code** [oracle/docker-images#1412]
https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/1213-domain
when i run the domain creation for the above i receive permission denied error 
could you pls help
![Screenshot from 2019-10-21 19-17-03](https://user-images.githubusercontent.com/56678922/67210916-7da73700-f437-11e9-9cb6-7f6f742543fd.png)

**Comment by mriccell** [comment]
Please use the https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain to create the domain. Support for WLS 12.1.3 will end very soon.
