### ISSUE TITLE
recent images still not published to container-registry.oracle.com?

### ISSUE THREAD

**Issue by stickycode** [oracle/docker-images#1414]
Will there be new images or is everyone expected to build their own? I don't mind but if that is the case you should just remove all the images rather than have stale ones.

**Comment by Djelibeybi** [comment]
It's easier to build your own (and you get to tweak it to your own needs). The levels of approvals required to publish Oracle binaries on a (relatively) free-to-download site like the Container Registry are immense, as I'm sure you can imagine.

**Comment by stickycode** [comment]
Is there a more protected site for license holders that has published images? I'd like to validate with a known standard well used image before I create my own.

**Comment by Djelibeybi** [comment]
Not that I know of, which is why we built our own.

**Comment by stickycode** [comment]
Just saw other response, I'll get an SR raised and see where that goes. Thanks
