### ISSUE TITLE
Extended Oracle Database Image not running in Docker on colleagues laptop

### ISSUE THREAD

**Issue by wazbekker** [oracle/docker-images#1417]
Hi 

I created an image using this command ```.\buildDockerImage.sh -v 12.2.0.1 -s``` and the linuxx64_12201_database.zip for the installation files.

I then extended that image by setting the parameter MAX_STRING_SIZE to extended following these [steps](https://www.markusdba.net/?p=197).  I then committed my changes to an image called wazbekker/oracledatabase and pushed it to docker hub with a tag of 12.2.0.1-se2-extended.  

I am running this image as a container successfully using the following command:

```
docker run
 --name oracle-12.2.0.1-se2-extended 
-p 1521:1521
 -p 5500:5500 
-e ORACLE_SID=ORCLCDB 
-e ORACLE_PWD=oracle 
-v oradata:/opt/oracle/oradata wazbekker/oracledatabase:12.2.0.1-se2-extended.
```
 I am able to connect and create users/schemas and create tables etc without any issues.

The problem comes in when a work colleague pulls the image from Docker Hub and tries to run it with the exact same run command as above.

This is the output of trying to run the image:
```
Global Database Name:ORCLCDB

System Identifier(SID):ORCLCDB

2019-10-25T11:11:05.410085437Z 

SQL*Plus: Release 12.2.0.1.0 Production on Fri Oct 25 11:11:05 2019

2019-10-25T11:11:05.410119290Z 

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

2019-10-25T11:11:05.410129239Z 

Connected to an idle instance.

2019-10-25T11:11:06.428916968Z 

SQL>    ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORCLCDB/control01.ctl' scope=spfile

*

ERROR at line 1:

ORA-01034: ORACLE not available

Process ID: 0

Session ID: 0 Serial number: 0

2019-10-25T11:11:06.428974643Z 

2019-10-25T11:11:06.428978087Z 

SQL>    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE

*

ERROR at line 1:

ORA-01034: ORACLE not available

P2019-10-25T11:11:06.431320012Z 

2019-10-25T11:11:06.431323423Z 

SQL> BEGIN DBMS_XDB_CONFIG.SETGLOBALPORTENABLED (TRUE); END;

2019-10-25T11:11:06.432850490Z 

*

ERROR at line 1:

ORA-01034: ORACLE not available

Process ID: 0

Session ID: 0 Serial number: 0

2019-10-25T11:11:06.432886010Z 

2019-10-25T11:11:06.432889290Z 

SQL> Disconnected

mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileORCLCDB.ora': No such file or directory

mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwORCLCDB': No such file or directory

The Oracle base remains unchanged with value /opt/oracle

#####################################

########### E R R O R ###############

DATABASE SETUP WAS NOT SUCCESSFUL!

Please check output for further info!

########### E R R O R ###############

#####################################

The following output is now a tail of the alert.log:

ORCLPDB1(3):Autotune of undo retention is turned on. 

2019-10-08T13:36:37.318521+00:00

ORCLPDB1(3):Endian type of dictionary set to little

ORCLPDB1(3):[3320] Successfully onlined Undo Tablespace 2.

ORCLPDB1(3):Undo initialization finished serial:0 start:9585533 end:9585611 diff:78 ms (0.1 seconds)

ORCLPDB1(3):Database Characterset for ORCLPDB1 is AL32UTF8

ORCLPDB1(3):Opatch validation is skipped for PDB ORCLPDB1 (con_id=0)

ORCLPDB1(3):Opening pdb with Resource Manager plan: DEFAULT_PLAN

Pluggable database ORCLPDB1 opened read write

ORCLPDB1(3):Completed: alter pluggable database orclpdb1 open
```

I then ran this command to connect to the container ```docker exec -it oracle-12.2.0.1-se2-extended /bin/bash``` and did some digging with regards to the errors in the output and found the following:
```
[oracle@ab98fad78405 ~]$ cd /opt/oracle/product/12.2.0.1/dbhome_1/dbs
[oracle@ab98fad78405 dbs]$ ls -al
total 24
drwxr-xr-x 1 oracle dba      4096 Oct 18 11:16 .
drwxr-xr-x 1 oracle dba      4096 Oct  8 13:33 ..
-rw-rw---- 1 oracle oinstall 1544 Oct  8 13:33 hc_ORCLCDB.dat
-rw-r--r-- 1 oracle dba      3079 May 15  2015 init.ora
-rw-r----- 1 oracle oinstall   24 Oct  8 13:04 lkORCLCDB
lrwxrwxrwx 1 oracle oinstall   49 Oct 18 11:16 orapwORCLCDB -> /opt/oracle/oradata/dbconfig/ORCLCDB/orapwORCLCDB
lrwxrwxrwx 1 oracle oinstall   54 Oct 18 11:16 spfileORCLCDB.ora -> /opt/oracle/oradata/dbconfig/ORCLCDB/spfileORCLCDB.ora
```

```
[oracle@ab98fad78405 ORCLCDB]$ cd /opt/oracle/oradata/dbconfig/ORCLCDB
[oracle@ab98fad78405 ORCLCDB]$ ls -al
total 24
drwxr-xr-x 2 oracle oinstall 4096 Oct 18 11:16 .
drwxr-xr-x 3 oracle oinstall 4096 Oct 18 10:45 ..
-rw-r--r-- 1 oracle oinstall  234 Oct 18 11:16 listener.ora
-rw-r--r-- 1 oracle oinstall  789 Oct 18 11:16 oratab
-rw-r--r-- 1 oracle oinstall   53 Oct 18 11:16 sqlnet.ora
-rw-r--r-- 1 oracle oinstall  197 Oct 18 11:16 tnsnames.ora
```

The symlinks are pointing to files that do not exist and I am not sure why?  These files exist in the container that I am running, using the exact same image.

I have a feeling this might be a problem with the volume but not sure what to do to fix it.

Hopefully someone can point me in the right direction to solve this issue?

**Comment by gvenzl** [comment]
Hi @wazbekker, 

In short, `docker commit` doesn't persist anything that's sitting in a volume. So, all the data files and therefore your database is gone once you have committed the new image.

[`docker commit` documentation](https://docs.docker.com/engine/reference/commandline/commit/):

> Extended description
>
>It can be useful to commit a container’s file changes or settings into a new image. This allows you to debug a container by running an interactive shell, or to export a working dataset to another server. Generally, it is better to use Dockerfiles to manage your images in a documented and maintainable way. Read more about valid image names and tags.
>
> The commit operation will not include any data contained in volumes mounted inside the container.

See the last paragraph.

The only way around it is to keep the data files inside the image itself and make the database transient (i.e. your database is gone once you drop the container). For that, you will have to remove the `VOLUME` instruction as described here: https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/samples/prebuiltdb/README.md

Of course, there are other ways to get there, but it depends all on what you need.
You could, for example, embed a `setup` script that does the same and then there is no need for `docker commit` at all. Or you could just create the DB once and then just use that volume as a "gold image", etc.

**Comment by wazbekker** [comment]
Hi @gvenzl 

Thank you for the reply and thank you for pointing me in the right direction.  

I will take a look at the other options.

**Comment by wazbekker** [comment]
Hi @gvenzl 

I followed the instructions in the prebuiltdb readme and I was able to create an image that can be reused by others at work.

Thank you for the help.
