### ISSUE TITLE
Execution of `buildDockerImage.sh` fails with md5sum

### ISSUE THREAD

**Issue by satishdash** [oracle/docker-images#142]
Hi,
As per the main line instructions for building WLS docker images it asked to check the content of *.download files under OracleWeblogic/dockerfiles/12.2.1.1/

```
$ cat fmw_12.2.1.1.0_wls_Disk1_1of1.zip.download
# Download WebLogic Server Generic Installer 12.2.1.1
#
# - http://www.oracle.com/technetwork/middleware/weblogic/downloads/wls-for-dev-1703574.html
#
01c15af9011b349a41c9ddc60e88f7cc  fmw_12.2.1.1.0_wls_Disk1_1of1.zip
```

But when I download the recommended file the md5sums do not match.
```
$ md5sum fmw_12.2.1.1.0_wls_Disk1_1of1.zip
fe0826ca8ca01c88caaf5db3ad9f84a5  fmw_12.2.1.1.0_wls_Disk1_1of1.zip
```

I have downloaded the Generic installer "http://download.oracle.com/otn/nt/middleware/12c/122110/fmw_12.2.1.1.0_wls_Disk1_1of1.zip") from "http://www.oracle.com/technetwork/middleware/weblogic/downloads/wls-for-dev-1703574.html"

Could anyone let me know the solution for this ? Am I missing anything here?

**Comment by brunoborges** [comment]
Skip the checksum. See instructions:

`sh buildDockerImage.sh -h`

**Comment by brunoborges** [comment]
I just downloaded the package from OTN and the MD5 is `01c15af9011b349a41c9ddc60e88f7cc`, as indicated in the `.download` file used to do the checksum inside `buildDockerImage.sh`.

Either download again, or skip md5sum if that works.

**Comment by clockfort** [comment]
For future reference to people googling into this issue, like me, the file hash described here is actually an html file with 
```
<p class="loginFailed">System error. Please re-try your action. If you continue to get this error, please contact the Administrator.</p>
```

... I believe which is a result of Oracle opting to hide hyper-old versions of the JDK behind an additional login layer now.
