### ISSUE TITLE
19c unable to run EM Database Express - Internal Server Error - SYS.PRVT_EMX no data found

### ISSUE THREAD

**Issue by pgalley22** [oracle/docker-images#1421]
I built a 19c docker image
When running it, I'm successfully able  connect to the database.
However when connecting to the EM Database Express I've got: Internal Server Error
and in the log:

XDB initialized.
qmhGetHTTPError: Got unknown oracle error. Error stack is:
2019-11-05T09:22:37.791458+00:00
Errors in file /opt/oracle/diag/rdbms/llx2193/LLX2193/trace/LLX2193_s001_461.trc:
ORA-01403: no data found
ORA-06512: at "SYS.PRVT_EMX", line 2720
ORA-06512: at "SYS.PRVT_EMX", line 2704
ORA-06512: at line 1

-------------------

aaa@laulxlab2:/oams/oracle_docker> sudo docker info
Containers: 7
 Running: 4
 Paused: 0
 Stopped: 3
Images: 249
Server Version: 18.09.1
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 251.7GiB
Name: laulxlab2.temenosgroup.com
ID: 3JXJ:RUJA:S6M4:L6YV:IRXK:YGZG:KGVS:5GNZ:4A4A:C3SE:72PX:JVJ6
Docker Root Dir: /data/docker_data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: the overlay storage-driver is deprecated, and will be removed in a future release.

Running the same docker image on Oracle Linux 7.7 is fine

I'm asking myself if it may be due to the fact I'm running RHEL 7.3

**Comment by gvenzl** [comment]
This is a database issue and has nothing to do with the Docker scripts provided here. Please check support.oracle.com on the database error you are receiving.
