### ISSUE TITLE
SSH check failed for the grid@racnode1 beuase of permission denied error!

### ISSUE THREAD

**Issue by XiaoYu-HN** [oracle/docker-images#1423]
i follow the guide: https://container-registry.oracle.com/pls/apex/f?p=113:4:185098448853 to directly pull RAC 18.3.0 image from Oracle Container Registry, not follow the buildDockerImage.sh here.

racnode1 container build succeed, i can log into and verify the cluster and database is OK.
racnode1 container build failed with below error:
11-11-2019 03:06:58 UTC :  : ORACLE_SID is set to ORCLCDB
11-11-2019 03:06:58 UTC :  : Setting random password for root/grid/oracle user
11-11-2019 03:06:58 UTC :  : Setting random password for grid user
11-11-2019 03:06:58 UTC :  : Setting random password for oracle user
11-11-2019 03:06:58 UTC :  : Setting random password for root user
11-11-2019 03:06:58 UTC :  : Cluster Nodes are racnode1 racnode2
11-11-2019 03:06:58 UTC :  : Running SSH setup for grid user between nodes racnode1 racnode2
11-11-2019 03:08:12 UTC :  : Running SSH setup for oracle user between nodes racnode1 racnode2
11-11-2019 03:09:22 UTC : : SSH check failed for the grid@racnode1 beuase of permission denied error! SSH setup did not complete sucessfully
11-11-2019 03:09:22 UTC : : Error has occurred in Grid Setup, Please verify!

thanks in advance!

**Comment by psaini79** [comment]
@XiaoYu-HN 

Issue occurred during Node addition? It seems SSH is not setup properly. I will look into it. Can you also test with building docker image?

**Comment by XiaoYu-HN** [comment]
Yes, the error occured when I add racnode2 to cluster. racnode1 is OK. below is the procedure:
1. create a Linux instance in OCI, i will run 2 container in this host, no CMAN
2. install docker
3. pull RAC 18.3.0 docker image from Oracle Container Registry
4. follow the help, set kernel parameter etc to meet the prerequisite
5. create a 50G block volumn  and attach to Linux instance
6. create and start racnode1
7. verified the cluster and database is OK
8. create and start racnode2 (node addition)
9. error occured (test many times, error is the same)

command to create racnode1:
$ docker create -t -i \
  --hostname racnode1 \
  --volume /boot:/boot:ro \
  --volume /dev/shm \
  --tmpfs /dev/shm:rw,exec,size=4G \
  --volume /opt/containers/rac_host_file:/etc/hosts  \
  --dns-search=example.com \
  --device=/dev/sdb:/dev/asm_disk1  \
  --privileged=false  \
  --cap-add=SYS_NICE \
  --cap-add=SYS_RESOURCE \
  --cap-add=NET_ADMIN \
  -e NODE_VIP=172.16.1.160 \
  -e VIP_HOSTNAME=racnode1-vip  \
  -e PRIV_IP=192.168.17.150 \
  -e PRIV_HOSTNAME=racnode1-priv \
  -e PUBLIC_IP=172.16.1.150 \
  -e PUBLIC_HOSTNAME=racnode1  \
  -e SCAN_NAME=racnode-scan \
  -e SCAN_IP=172.16.1.70  \
  -e OP_TYPE=INSTALL \
  -e DOMAIN=example.com \
  -e ASM_DEVICE_LIST=/dev/asm_disk1 \
  -e ORACLE_PWD="Oracle_18c" \
  -e ASM_DISCOVERY_DIR=/dev \
  -e OS_PASSWORD=Oracle_18c \
  --restart=always --tmpfs=/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  --cpu-rt-runtime=95000 --ulimit rtprio=99  \
  --name racnode1 \
  container-registry.oracle.com/database/rac:18.3.0

command to create racnode2:
$ docker create -t -i \
  --hostname racnode2 \
  --volume /boot:/boot:ro \
  --volume /dev/shm \
  --tmpfs /dev/shm:rw,exec,size=4G \
  --volume /opt/containers/rac_host_file:/etc/hosts  \
  --dns-search=example.com \
  --device=/dev/sdb:/dev/asm_disk1  \
  --privileged=false  \
  --cap-add=SYS_NICE \
  --cap-add=SYS_RESOURCE \
  --cap-add=NET_ADMIN \
  -e NODE_VIP=172.16.1.161 \
  -e VIP_HOSTNAME=racnode2-vip  \
  -e PRIV_IP=192.168.17.151 \
  -e PRIV_HOSTNAME=racnode2-priv \
  -e PUBLIC_IP=172.16.1.151 \
  -e PUBLIC_HOSTNAME=racnode2  \
  -e SCAN_NAME=racnode-scan \
  -e SCAN_IP=172.16.1.70  \
  -e DOMAIN=example.com \
  -e ASM_DEVICE_LIST=/dev/asm_disk1 \
  -e ASM_DISCOVERY_DIR=/dev \
  -e OS_PASSWORD=Oracle_18c \
  -e EXISTING_CLS_NODES=racnode1 \
  -e ORACLE_SID=ORCLCDB \
  -e OP_TYPE=ADDNODE \
  --restart=always --tmpfs=/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  --cpu-rt-runtime=95000 --ulimit rtprio=99  \
  --name racnode2 \
  container-registry.oracle.com/database/rac:18.3.0


I will test building docker image also, will feedback you when completed.
thanks a lot!

**Comment by XiaoYu-HN** [comment]
@psaini79 test of building docker image on OCI compute instance is OK!

**Comment by XiaoYu-HN** [comment]
@psaini79 I have test the pull image method and failed again(18c image, not 12c), the same error. compare to the build image method, i find the difference, although i have set the OS_PASSWORD and ORACLE_PWD in the command line, but password is not set as expected. is this a bug?

**Comment by psaini79** [comment]
@XiaoYu-HN 

I will look into it. It can be a doc bug. Let me verify and will come back to you.

**Comment by XiaoYu-HN** [comment]
@psaini79 I test my  pull image again, this time succeed by using README.md in github (described in password manegement section ) rather than online help from https://container-registry.oracle.com/  (use OS_PASSWORD and ORACLE_PWD as CLI parameter). this should be a doc bug

**Comment by psaini79** [comment]
@XiaoYu-HN 

I will fix the doc bug and will test the same.

**Comment by psaini79** [comment]
@XiaoYu-HN , please check as I updated the doc long back but forgot to update the thread. Let me know if you are see the issue still.  If everything is fine then close the thread.
