### ISSUE TITLE
Can't connect to RAC through CMAN

### ISSUE THREAD

**Issue by XiaoYu-HN** [oracle/docker-images#1425]
I have a host with docker installed. then:
1. build and run CMAN
2. build ann run racnode1 & racnode2, version 19.3
3. pull instant clinet 19.3 image
4. test connection through CMAN

I can connect to RAC when i inside container racnode1 & racnode2,  can't but from the docker host, the error is as below:

$ docker run -ti --rm oracle/instantclient:19 sqlplus system/Oracle.123@172.16.1.70/ORCLCDB

SQL*Plus: Release 19.0.0.0.0 - Production on Thu Nov 14 03:33:31 2019
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

ERROR:
ORA-12170: TNS:Connect timeout occurred

should I manually add target RAC node in CMAN? or it's auto registered during rac node creation?
where can i find target rac host info in CMAN container? I don't find anything relevant to target host in cman.ora
thanks in advance！

**Comment by XiaoYu-HN** [comment]
below is my cman.ora, is this correct? why there's no target host e.g. racnode-scan specified in this file? 
[oracle@racnode-cman1 admin]$ cat cman.ora
...
# CMAN Alias
CMAN_racnode-cman1.example.com =
(configuration=
  # Listening address of the cman
  (address=(protocol=tcp)(host=racnode-cman1.example.com)(port=1521))
  # Configuration parameters of this CMAN
  (parameter_list =
    # Need authentication for connection?
    # Valid values: boolean values for on/off
    (connection_statistics=yes)
    (log_directory=/u01/app/oracle/product/19.3.0/client_1/network/log)
    (log_level=USER)
    (trace_directory=/u01/app/oracle/product/19.3.0/client_1/network/trace)
    (trace_level=USER)
    (valid_node_checking_registration=on)
    (registration_invited_nodes=*)
  )

  # Rule list

  # Rule Specification:
  # src = Source of connection; '*' for 'ANY'
  # dst = Destination of connection; '*' for 'ANY'
  # srv = Service of connection; '*' for 'ANY'
  # act = Action: 'accept', 'reject' or 'drop'

  # Action List Specification:
  # aut         = aso_authentication_filter
  # moct        = outbound_connect_timeout
  # mct         = session_timeout
  # mit         = idle_timeout
  # conn_stats  = connect_statistics
  (rule_list=
    (rule=
       (src=*)(dst=*)(srv=*)(act=accept)
       (action_list=(aut=off)(moct=0)(mct=0)(mit=0)(conn_stats=on))
    )
  )
)

**Comment by psaini79** [comment]
@XiaoYu-HN 

Please do following and share the output:
Login to racnode1 and execute following from ORCL1CDB database
show parameter remote_listener

Login to cman container and execute following:
cmctl
show services
show  connections

**Comment by XiaoYu-HN** [comment]
@psaini79 
from racnode1 container:
```
[oracle@racnode1 ~]$ sqlplus sys@ORCLCDB as sysdba                  
SQL*Plus: Release 19.0.0.0.0 - Production on Fri Nov 15 00:43:12 2019
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.


Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0

SQL> show parameter remote_listener

NAME                                 TYPE        VALUE
------------------------------------ ----------- ------------------------------
remote_listener                      string       racnode-scan:1521

```
from CMAN container:
```
[oracle@racnode-cman1 ~]$ cmctl show services

CMCTL for Linux: Version 19.0.0.0.0 - Production on 15-NOV-2019 00:45:33

Copyright (c) 1996, 2019, Oracle.  All rights reserved.

Current instance CMAN_racnode-cman1.example.com is already started
Connecting to (DESCRIPTION=(address=(protocol=tcp)(host=racnode-cman1.example.co                                                       m)(port=1521)))
Services Summary...
Proxy service "cmgw" has 1 instance(s).
  Instance "cman", status READY, has 2 handler(s) for this service...
    Handler(s):
      "cmgw001" established:0 refused:0 current:0 max:256 state:ready
         <machine: localhost, pid: 186>
         (ADDRESS=(PROTOCOL=ipc)(KEY=#186.1)(KEYPATH=/var/tmp/.oracle_5432100))
      "cmgw000" established:0 refused:0 current:0 max:256 state:ready
         <machine: localhost, pid: 184>
         (ADDRESS=(PROTOCOL=ipc)(KEY=#184.1)(KEYPATH=/var/tmp/.oracle_5432100))
Service "cmon" has 1 instance(s).
  Instance "cman", status READY, has 1 handler(s) for this service...
    Handler(s):
      "cmon" established:2 refused:0 current:1 max:4 state:ready
         <machine: localhost, pid: 178>
         (ADDRESS=(PROTOCOL=ipc)(KEY=#178.1)(KEYPATH=/var/tmp/.oracle_5432100))
The command completed successfully.

[oracle@racnode-cman1 ~]$ cmctl show connections

CMCTL for Linux: Version 19.0.0.0.0 - Production on 15-NOV-2019 00:46:15

Copyright (c) 1996, 2019, Oracle.  All rights reserved.

Current instance CMAN_racnode-cman1.example.com is already started
Connecting to (DESCRIPTION=(address=(protocol=tcp)(host=racnode-cman1.example.com)(port=1521)))
TNS-04049: Specified connections do not exist
The command completed successfully.

```

BTW, follow the README, I only specify CMAN related arguments when I create the first RAC node, but not when I build the RAC base image and create the second RAC node, is this OK?

**Comment by psaini79** [comment]
@XiaoYu-HN 

It need to look at the scripts not sure why this occurred.  However, I tested on my machine and please do  following to fix it:

Login to racnode1 container and execute following steps as oracle user in ORCLCDB1 DB:
```
alter system set remote_listener='ranode-scan:1521,racnode-cman1:1521' scope=both;
alter system register;

```
Exit from racnode1 and login to racnode-cman1 and execute following:

```
cmctl
dminister CMAN_racnode-cman1.example.com
Current instance CMAN_racnode-cman1.example.com is already started
Connections refer to (DESCRIPTION=(address=(protocol=tcp)(host=racnode-cman1.example.com)(port=1521))).
The command completed successfully.
CMCTL:CMAN_racnode-cman1.example.com> 
CMCTL:CMAN_racnode-cman1.example.com> 
CMCTL:CMAN_racnode-cman1.example.com> show services
```

You should see database services registered with CMAN and you must be able to connect to DB.

**Comment by XiaoYu-HN** [comment]
@psaini79 thanks a lot! it works!
anothrer finding, i can successfully login only after I disable the OS firewall
```
sudo systemctl stop firewalld
```

**Comment by psaini79** [comment]
@XiaoYu-HN 

Please close this if it worked for you.
