### ISSUE TITLE
/bin/sh: /u01/oracle/wlst: Permission denied

### ISSUE THREAD

**Issue by kris0107** [oracle/docker-images#1426]
While creating the docker image of Oracle Weblogic 12.1.3, I got the error for the weblogic server domain image.

Step 5/13 : ENV DOMAIN_NAME="base_domain"     PRE_DOMAIN_HOME=/u01/oracle/user_projects     ADMIN_PORT="7001"     ADMIN_HOST="wlsadmin"     NM_PORT="5556"     MS_PORT="7002"     CONFIG_JVM_ARGS="-Dweblogic.security.SSL.ignoreHostnameVerification=true"     PATH=$PATH:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:$PRE_DOMAIN_HOME/domains/base_domain:$PRE_DOMAIN_HOME/domains/base_domain/bin:/u01/oracle
 ---> Running in 82c8de60b8e1
Removing intermediate container 82c8de60b8e1
 ---> f51bb728196f
Step 6/13 : COPY container-scripts/* /u01/oracle/
 ---> 9722a5bbd827
Step 7/13 : USER root
 ---> Running in 7ecaa0cc63c0
Removing intermediate container 7ecaa0cc63c0
 ---> 7cdb12072890
Step 8/13 : WORKDIR /u01/oracle
 ---> Running in 1d47921fb3ae
Removing intermediate container 1d47921fb3ae
 ---> 22d397fae118
Step 9/13 : RUN /u01/oracle/wlst /u01/oracle/create-wls-domain.py &&     mkdir -p $PRE_DOMAIN_HOME &&     chmod a+xr $PRE_DOMAIN_HOME &&     chown -R oracle:oracle $PRE_DOMAIN_HOME &&     mkdir -p $PRE_DOMAIN_HOME/domains/base_domain/servers/AdminServer/security &&     echo "username=weblogic" > $PRE_DOMAIN_HOME/domains/base_domain/servers/AdminServer/security/boot.properties &&     echo "password=$ADMIN_PASSWORD" >> $PRE_DOMAIN_HOME/domains/base_domain/servers/AdminServer/security/boot.properties &&     echo ". $PRE_DOMAIN_HOME/domains/base_domain/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc &&     echo "export PATH=$PATH:/u01/oracle/wlserver/common/bin:$PRE_DOMAIN_HOME/domains/base_domain/bin" >> /u01/oracle/.bashrc &&     cp /u01/oracle/commEnv.sh /u01/oracle/wlserver/common/bin/commEnv.sh &&     rm /u01/oracle/create-wls-domain.py /u01/oracle/jaxrs2-template.jar
 ---> Running in b007629b0961
**/bin/sh: /u01/oracle/wlst: Permission denied**
The command **'/bin/sh -c /u01/oracle/wlst /u01/oracle/create-wls-domain.py &&     mkdir -p $PRE_DOMAIN_HOME &&     chmod a+xr $PRE_DOMAIN_HOME &&     chown -R oracle:oracle $PRE_DOMAIN_HOME &&     mkdir -p $PRE_DOMAIN_HOME/domains/base_domain/servers/AdminServer/security &&     echo "username=weblogic" > $PRE_DOMAIN_HOME/domains/base_domain/servers/AdminServer/security/boot.properties &&     echo "password=$ADMIN_PASSWORD" >> $PRE_DOMAIN_HOME/domains/base_domain/servers/AdminServer/security/boot.properties &&     echo ". $PRE_DOMAIN_HOME/domains/base_domain/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc &&     echo "export PATH=$PATH:/u01/oracle/wlserver/common/bin:$PRE_DOMAIN_HOME/domains/base_domain/bin" >> /u01/oracle/.bashrc &&     cp /u01/oracle/commEnv.sh /u01/oracle/wlserver/common/bin/commEnv.sh &&     rm /u01/oracle/create-wls-domain.py /u01/oracle/jaxrs2-template.jar'** returned a non-zero code:126

**Comment by mriccell** [comment]
Please use the https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain to create the domain. Support for WLS 12.1.3 will end very soon.
