### ISSUE TITLE
Startup script location is incorrect.

### ISSUE THREAD

**Issue by pbecotte** [oracle/docker-images#1427]
Hi! As mentioned in #878 the container presents extension points to run startup scripts. This is great! The problem is that it doesn't actually work.

This is because the mount location /u01/app/oracle/scripts/setup/ (etc..) don't exist in the image. This is no problem- `docker run -v ...` will create the path. The problem is that the container doesn't run as `root` and docker will create the folders UP TO that path as owned by root. Even THAT wouldn't be a problem if the script didn't then try to create other folders in that tree and use them for other stuff. So if you do
`docker run -v ./mysql.sql:/u01/app/oracle/scripts/setup/mysql.sql oracle/database` the startup will fail.

I worked around this for now by adding an entrypoint script
```
#! /bin/bash
mkdir -p /u01/app/oracle/scripts/setup
cp /setup.sql /u01/app/oracle/scripts/setup/setup.sql
exec "$@"
```

In the other thread it was closed because "not everyone wants to use a volume" That's fine- but there's _no reason_ not to create the folder structure at build time, or, alternatively, move the mount location to a different tree that isn't used by the entrypoint script. Compatability with the postgres/mysql images was mentioned... this is the reason their mountpoints are at `docker-entrypoint-initdb.d/`

(I would happily write a Pull Request- but am a bit confused. This repo doesn't actually seem to be used for the image I see at `store/oracle/database-enterprise:12.2.0.1`? It is set up mostly the same, but file names and the like don't really line up. That image doesn't have any description on dockerhub lol- so an addition to the FAQ of what images the Dockerfiles are actually used to publish, and if you're going to provide store images, provide the Dockerfiles for those as well? I see a bunch of example commands for images like oracle/database:12.2.0.1-ee ... but that doesn't seem to exist?)

**Comment by Djelibeybi** [comment]
The Database image is the only one for which the `Dockerfile` here doesn't match what is on the Oracle Container Registry and Docker Store. This is for very complicated legacy reasons and should not be the case moving forward. 

The upshot of which is, please do submit a pull request that resolves this issue.

**Comment by pbecotte** [comment]
Actually, I am not sure if it is an issue now- looking closer the image I pulled has basically nothing in common with this one, including the ability to run scripts on startup (so it didn't matter where I mounted them haha).

Is this image located somewhere so that I can use it? Or is the only option to build it myself?

**Comment by Djelibeybi** [comment]
The only option is to build it yourself. The 12c image on OCR is not going to be updated. @gvenzl can confirm, but I believe that upcoming 19c and 20c images will be based on the Dockerfiles in this repo.

**Comment by pbecotte** [comment]
This ticket is completely innacurate. Building the image and using that does work as described. Only recommendation I would have is to add a note to the FAQ pointing out that store/oracle/database is NOT this repo.

**Comment by Djelibeybi** [comment]
I agree, so I've opened this PR: https://github.com/oracle/docker-images/pull/1432
