### ISSUE TITLE
COPY failed: stat /var/lib/docker/tmp/docker-builder381294764/linuxamd64_12102_database_1of2.zip: no such file or directory

### ISSUE THREAD

**Issue by ranmc** [oracle/docker-images#1428]
./buildDockerImage.sh -v 12.1.0.2 -s -i 
![1](https://user-images.githubusercontent.com/32739812/69300150-63869180-0c4d-11ea-82f2-b45d19fbbbfb.png)
![2](https://user-images.githubusercontent.com/32739812/69300151-641f2800-0c4d-11ea-9ca2-c5d6c4b92792.png)

**Comment by Djelibeybi** [comment]
That's the wrong zip file. You have the 12.2.0.1 zip file, so you should be in the 12.2.0.1 directory.

**Comment by ranmc** [comment]
I'm trying.very thankful!

**Comment by ranmc** [comment]
> 那是错误的zip文件。您拥有12.2.0.1 zip文件，因此您应该位于12.2.0.1目录中。

I'm trying.very thankful!

**Comment by Djelibeybi** [comment]
You're welcome. Let me know if it works.

**Comment by ranmc** [comment]
> You're welcome. Let me know if it works.

The problem has been solved. Thanks again!
