### ISSUE TITLE
./buildDockerImage.sh -v 11.2.0.2 -x -i

### ISSUE THREAD

**Issue by ranmc** [oracle/docker-images#1429]
I run this command: ./buildDockerImage.sh -v 11.2.0.2 -x -i
However, there is no such Dockerfile.xe in the 11.2.0.2.
![1](https://user-images.githubusercontent.com/32739812/69317443-ed4a5500-0c75-11ea-8e1f-738bf7ab5b11.png)
![2](https://user-images.githubusercontent.com/32739812/69317589-39959500-0c76-11ea-990e-dc73e1f5036d.png)

**Comment by Djelibeybi** [comment]
There is no 12.2.0.1 XE version. You need to use either `-e` or `-s` which will install either Enterprise or Standard Edition.

**Comment by ranmc** [comment]
> There is no 12.2.0.1 XE version. You need to use either `-e` or `-s` which will install either Enterprise or Standard Edition.
Sorry, I didn't get it. Did you say 11.2.0.1?

**Comment by Djelibeybi** [comment]
Sorry, I misread. It's still the same resolution though. You need to use `-e` or `-s` instead of `-x`

**Comment by ranmc** [comment]
> Sorry, I misread. It's still the same resolution though. You need to use `-e` or `-s` instead of `-x`

I originally used "-v 11.2.0.2 -is ", but I couldn't find 11.2.0.2/ dockerfile.se2.

**Comment by gvenzl** [comment]
Hi @ranmc, can you please clone the repository again?
There definitely is a `Dockerfile.xe` in that directory here on GitHub:

![image](https://user-images.githubusercontent.com/4610293/70481587-ec982800-1a97-11ea-8fa8-b10eae52f285.png)

**Comment by gvenzl** [comment]
I can also see that you have the wrong zip files downloaded as well. Please make sure that you download the 11g R2 Express Edition zip file.

**Comment by ranmc** [comment]
> I can also see that you have the wrong zip files downloaded as well. Please make sure that you download the 11g R2 Express Edition zip file.

Thanks! The problem has already been settled.
