### ISSUE TITLE
Starting 1231-domain image fails wih Failed to deploy library Extension-Name: jax-rs, Specification-Version: 2, Implementation-Version: 2.22.4.0, because of conflicting library Manifest values, and library information registered with the server: [Implementation-Version: 2.22.4.0 vs. 2.5.1].

### ISSUE THREAD

**Issue by gasgithub** [oracle/docker-images#1431]
Hi,

I'm trying to build simple single server image using https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/1213-domain , I've change the dockerfile to use the following image FROM store/oracle/weblogic:12.2.1.3
Build completes, but during runtime I get following exception and cannot access admin console.

Any hints how to resolve it?

Regards
Greg

<Nov 21, 2019 9:46:44,796 AM GMT> <Error> <Deployer> <BEA-149205> <Failed to initialize the application "jax-rs [LibSpecVersion=2.0,LibImplVersion=2.5.1]" due to error weblogic.app
lication.library.LibraryDeploymentException: [J2EE:160145]Failed to deploy library Extension-Name: jax-rs, Specification-Version: 2, Implementation-Version: 2.22.4.0, because of conflicting library Manifest values, and library information registered with the server: [Implementation-Version: 2.22.4.0 vs. 2.5.1]. Check the library MANIFEST.MF file and correct
version information there to match server settings, or undeploy the misconfigured library.
weblogic.application.library.LibraryDeploymentException: [J2EE:160145]Failed to deploy library Extension-Name: jax-rs, Specification-Version: 2, Implementation-Version: 2.22.4.0, b
ecause of conflicting library Manifest values, and library information registered with the server: [Implementation-Version: 2.22.4.0 vs. 2.5.1]. Check the library MANIFEST.MF file
and correct version information there to match server settings, or undeploy the misconfigured library.
        at weblogic.application.internal.library.LibraryDeploymentFactory.getLibData(LibraryDeploymentFactory.java:129)
        at weblogic.application.internal.library.LibraryDeploymentFactory.createDeployment(LibraryDeploymentFactory.java:50)
        at weblogic.application.internal.DeploymentManagerImpl.createDeployment(DeploymentManagerImpl.java:195)
        at weblogic.application.internal.DeploymentManagerImpl.access$800(DeploymentManagerImpl.java:61)
        at weblogic.application.internal.DeploymentManagerImpl$DeploymentCreatorImpl.createDeployment(DeploymentManagerImpl.java:628)
        Truncated. see log file for complete stacktrace
>

**Comment by mriccell** [comment]
Please use the https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain to create the domain, 12.1.3 is not a supported version of WebLogic.
