### ISSUE TITLE
Outdated documentation in Dockerfiles?

### ISSUE THREAD

**Issue by fdevibe** [oracle/docker-images#1435]
The Dockerfiles in `OracleWebLogic/dockerfiles/12.2.1.3` instruct you to download a jre and place it in the current directory. However, AFAICT, there is no reference to this in the Dockerfiles, and they seem to build upon an image that has a separate Dockerfile in `OracleJava/java-8`, which needs to be built separately. `OracleWebLogic/README.md` gives correct instructions, so said Dockerfiles should be updated with those.

**Comment by mriccell** [comment]
Fixed
