### ISSUE TITLE
How to configure LDAP auth provider for single server domain?

### ISSUE THREAD

**Issue by gasgithub** [oracle/docker-images#1436]
Hi,

Trying to configure LDAP authentication provider, preferably in offline mode.
I'm using base store/oracle/weblogic:12.2.1.3-dev and created own create-wls-domain.py script, but in no way I can create LDAP config.

Tried this way:
cd('/SecurityConfiguration/base_domain/Realms/myrealm')
cmo.createAuthenticationProvider('LDAP-AD', 'weblogic.security.providers.authentication.ActiveDirectoryAuthenticator')

 but then I get:
com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Could not create generic operation:weblogic.security.providers.authentication.
ActiveDirectoryAuthenticator@com.oracle.cie.domain.operation.OperationBuilder.createConfigOperation(OperationBuilder.java:342)

also tried:
create('LDAP-AD', 'weblogic.security.providers.authentication.ActiveDirectoryAuthenticator')

but that fails also.

So what is suggested/recommended way to configure LDAP for WLS in docker? 
Couldnt find any security related samples...

Regard
Greg

**Comment by mriccell** [comment]
It should be the same exact LDAP for WLS in docker. @TheFrogPad do you know why this would be failing?

**Comment by TheFrogPad** [comment]
@gasgithub as @mriccell indicates the functions are the same with Docker, you are making configuration updates to the WebLogic domain.

From what you have here it looks like you are not using the proper syntax for offline WLST to create an authentication provider. After `cd` to the realm, then for offline use `create` command and specify the argument for the `baseProviderType`.

The use of `createAuthenticationProvider` is for online WLST, for offline you should be able to do:
```
create('LDAP-AD', 'weblogic.security.providers.authentication.ActiveDirectoryAuthenticator', 'AuthenticationProvider')
```
The related documentation links are at:
* https://docs.oracle.com/middleware/12213/wls/WLSTC/reference.htm#GUID-4DE797B0-7CC8-40C5-A456-78B61CD839FF
* https://docs.oracle.com/en/middleware/fusion-middleware/12.2.1.3/wlstg/config_wls.html#GUID-B9A1978E-DCDF-4925-9D3D-BB603F3FE7F7

**Comment by mriccell** [comment]
@gasgithub are you still experiencing difficulty?

**Comment by TheFrogPad** [comment]
@gasgithub if you feel you still have an issue then feel free to re-open

**Comment by TheFrogPad** [comment]
@mriccell I have no permission to close issues in the `docker-images` repository. You can leave open if you prefer but I would close and the issue can be re-opened if a problem remains
