### ISSUE TITLE
Readiness probe failed: Get http://x.x.x.x:8001/weblogic/ready: dial tcp x.x.x.x:8001: connect: connection refused

### ISSUE THREAD

**Issue by kris0107** [oracle/docker-images#1437]
While creating the kubernetes image for the weblogic 12.1.3, the wls-admin server is showing this error.

**Comment by rjeberhard** [comment]
WebLogic is supported in Kubernetes for version 12.2.1.3 and above.  Also, extended support for WebLogic 12.1.3 expires at the end of 2019 is just over one month.

**Comment by kris0107** [comment]
It is for the Weblogic 12.2.1.3 only. Sorry for the typo.

**Comment by mriccell** [comment]
This issue is more of a WebLogic Kubernetes Operator issue and so that you get the correct attention do you mind opening an issue in https://github.com/oracle/weblogic-kubernetes-operator project?
