### ISSUE TITLE
Error in OracleFMWInfrastructure container run: com.oracle.cie.domain.ValidateException: 40318: Invalid or missing JDBC datasource connection parameters.

### ISSUE THREAD

**Issue by acarlson1994** [oracle/docker-images#1438]
I am recieving a JDBC URL validation error when running a container with the "oracle/fmw-infrastructure:12.2.1.4" image:
docker-images/OracleFMWInfrastructure/dockerfiles/12.2.1.4/Dockerfile

DB Image:
oracle/database-enterprise:12.2.0.1

The container log:
[https://pastebin.com/WmXKTUP9](https://pastebin.com/WmXKTUP9)

The RCU log:
[https://pastebin.com/ZxQy0rtY](https://pastebin.com/ZxQy0rtY)

The WLST offline log (ERROR @ LN 445):
[https://pastebin.com/h1twW3rR](https://pastebin.com/h1twW3rR)

It seems the RCU schemas properly get loaded into the DB. But during domain creation the createInfraDomain.py script fails validation of JDBC url. However, from what I see in the logs nothing is obviously incorrect.

Any help is appreciated! I can also provide more detail if needed.

Docker info:
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 107
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.768GiB
Name: linuxkit-00155d630101
ID: TAWZ:HTPZ:GBRW:NONR:QCFN:34KX:KINW:IXJ7:Q45J:4AWS:MAM2:FX7P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 58
 System Time: 2019-11-25T19:28:44.5834882Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by mriccell** [comment]
@anpanigr could you please take a look and see why this is not working?

**Comment by acarlson1994** [comment]
@mriccell, @anpanigr as an FYI: I ended up switching to a linux host and was having an easier time getting this image working. Now that I understand how to get it working on a linux host I will most likely attempt to get this working in windows again in the next few days.

I will let you know if I can more accurately re-create this issue, and hopefully tell you how.

**Comment by mriccell** [comment]
I will close this issue but please reopen or enter a new one if you still run into problems.
