### ISSUE TITLE
Error response from daemon: Error processing tar file(exit status 1): Error setting up pivot dir: mkdir /<>/<>/devicemapper/mnt/db0d0a0863f920f34a02d14d957880580e0bd94cd14f88400ef18b4a1b987cd4/rootfs/u01/.pivot_root734935069: no such file or directory

### ISSUE THREAD

**Issue by debabgho30** [oracle/docker-images#1439]
Hi,
I am running docker container created from 

docker load -i db.tar

It works fine most of time but it fails intermittently with below

Error response from daemon: Error processing tar file(exit status 1): Error setting up pivot dir: mkdir /<>/<>/devicemapper/mnt/db0d0a0863f920f34a02d14d957880580e0bd94cd14f88400ef18b4a1b987cd4/rootfs/u01/.pivot_root734935069: no such file or directory

**Comment by Djelibeybi** [comment]
We don't recommend using the `devicemapper` storage driver several reasons. Can you please switch to using either `btrfs` or `overlay2` (on XFS with `-ftype=1`) as documented here: https://docs.oracle.com/en/operating-systems/oracle-linux/docker/docker-install-storage.html

If you're not using Oracle Linux 7, please consult your OS documentation for how to change the file system used by Docker on that OS.

**Comment by Djelibeybi** [comment]
Note that this issue is not specific to the database image (nor I suspect the import process), so I'm closing it. You should contact either your OS support vendor (if they include Docker support, like we do) or Docker (if you're using Docker EE) for further assistance.
