### ISSUE TITLE
Fix README for '1221-domain-with-resources' example

### ISSUE THREAD

**Issue by abhirockzz** [oracle/docker-images#144]
The README file for '1221-domain-with-resources' example is incorrect (it is the one which one used for '1221-appdeploy' sample). Please add appropriate instructions in the README (related to the Data Source and JMS infra setup)

**Comment by brunoborges** [comment]
@abhirockzz mind to provide a Pull Request with what you have in mind?

**Comment by brunoborges** [comment]
@abhirockzz any chance you can provide a PR to fix this issue?

**Comment by brunoborges** [comment]
@abhirockzz can you submit a pull request?

**Comment by abhirockzz** [comment]
done... PR #168
