### ISSUE TITLE
docker tag not working for db image

### ISSUE THREAD

**Issue by ddevadat** [oracle/docker-images#1440]
performing the setup of SOA on Docker
After installing oracle db 12.2.0.1 ee the below step is failing
[vagrant@docker1 dockerfiles]$ docker tag container-registry.oracle.com/oracle/database:12.2.0.1-e oracle/database:12.2.0.1-ee
Error response from daemon: No such image: container-registry.oracle.com/oracle/database:12.2.0.1-e

**Comment by Djelibeybi** [comment]
If you're cutting and pasting, you're missing an 'e'. It should be:
```
docker tag container-registry.oracle.com/oracle/database:12.2.0.1-ee oracle/database:12.2.0.1-ee
```
The output of `# docker images` will tell you the exact image name and tag to use.

**Comment by ddevadat** [comment]
still the same error
[vagrant@docker1 dockerfiles]$ docker tag container-registry.oracle.com/oracle/database:12.2.0.1-ee oracle/database:12.2.0.1-ee
Error response from daemon: No such image: container-registry.oracle.com/oracle/database:12.2.0.1-ee

**Comment by ddevadat** [comment]
The instruction given in the readme is

The DB image created through above step need to be retagged from container-registry.oracle.com/oracle/database:12.2.0.1-ee to oracle/database:12.2.0.1-ee before continuing with next steps.

$ docker tag container-registry.oracle.com/oracle/database:12.2.0.1-e oracle/database:12.2.0.1-ee

But docker images command gives the below
[vagrant@docker1 dockerfiles]$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
oracle/database     12.2.0.1-ee         4795ae6ed2ba        3 hours ago         5.98GB

Is this step really needed?

**Comment by Djelibeybi** [comment]
No, you've already got the image with the right tag.,
