### ISSUE TITLE
Error response from daemon: pull access denied for oracle/database, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by security-prince** [oracle/docker-images#1444]
OS Info:
- NAME="CentOS Linux"
- VERSION="8 (Core)"
- ID="centos"
- ID_LIKE="rhel fedora"
- VERSION_ID="8"
- PLATFORM_ID="platform:el8"
- PRETTY_NAME="CentOS Linux 8 (Core)"

Docker Version: 18.06.3-ce, build d7080c1

I am trying to build and run the oracle image from [here](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1) using this command: `docker build --build-arg DB_EDITION=ee -t oracle/database:12.2.0.1-ee -f Dockerfile .`the build is successful and i can see the image being created via the docker images command, but when i am trying to run this image using the command : `docker run --name oracle-ee -p 1521:1521 -p 5500:5500 -v /home/oracle/oradata:/opt/oracle/oradata oracle/database:12.2.0.1-ee` i am getting an error saying `docker: Error response from daemon: pull access denied for oracle/database, repository does not exist or may require 'docker login'.`. I tried logging into container-registry.oracle.com using the docker login command but no luck.

**Comment by Djelibeybi** [comment]
Can you provide the output of `docker images` on that host? The `run` command is not finding the image you created.

**Comment by Djelibeybi** [comment]
Also, have you tried using the provided `buildDockerImage.sh` script which does a lot of pre-and-post build checks to ensure a successful image is created?

**Comment by security-prince** [comment]
@Djelibeybi 

docker images
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              870c4f38490b        5 minutes ago       118MB
oraclelinux         7-slim              c2b5cb5bcd9d        3 weeks ago         118MB
hello-world         latest              fce289e99eb9        11 months ago       1.84kB
```

**Comment by security-prince** [comment]
> Also, have you tried using the provided `buildDockerImage.sh` script which does a lot of pre-and-post build checks to ensure a successful image is created?

i can't find the `buildDockerImage.sh` in this [directory](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1)

**Comment by Djelibeybi** [comment]
It's one level up becuase it supports all available DB versions: https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles

**Comment by Djelibeybi** [comment]
Your image is not being built successfully, because you're getting a `<none>:<none>` image which is the last succesfully layer in the build. You need to review the output of the `docker build` command and work out what's failing.
