### ISSUE TITLE
This FROM image Dockerfile was removed in a previous commit.

### ISSUE THREAD

**Issue by brona90** [oracle/docker-images#1450]
https://github.com/oracle/docker-images/blob/9e5ca769aaa59e3f4aacb99420e50572fd4417ba/OracleWebLogic/samples/1221-domain-with-resources/Dockerfile#L20 

The Dockerfile that created the image referenced in this FROM was removed in commit: https://github.com/oracle/docker-images/commit/e49bb4d070de9ba8dcd5f5c718c93a1f77b498f6

The commit was made by @mriccell and accepted by @Djelibeybi.

Can either of you address plans for a replacement, or if the folder could be restored?

**Comment by mriccell** [comment]
WebLogic 1221 is no longer supported, I will change the sample to extend 12.2.1.3 which is a supported version of WLS.  I will create a PR.
