### ISSUE TITLE
OracleWebLogic Generic images created thru the Dockerfile.generic does not include example teamplates

### ISSUE THREAD

**Issue by anpanigr** [oracle/docker-images#1458]
As I see the all the Dockerfile.generic in docker-images/OracleWebLogic/dockerfiles has the installation type as " WebLogic Server" instead of "Complete with Examples"

$ find . -name "*.generic" | xargs grep "INSTALL_TYPE" 
./12.2.1.4/Dockerfile.generic:    ${JAVA_HOME}/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE="**WebLogic Server**" && \
./12.1.3/Dockerfile.generic:RUN $JAVA_HOME/bin/java -jar /u01/$FMW_PKG -ignoreSysPrereqs -novalidation -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE="**WebLogic Server**" && \
./12.2.1.3/Dockerfile.generic:    ${JAVA_HOME}/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE="**WebLogic Server**" && \

**Comment by mark-au** [comment]
I expect the images were designed to be minimal. 
Did we want to create another image tag for "Complete with Examples"? I note the INSTALL_TYPE is also set in the `install.file` but believe it's overridden by the installer argument

**Comment by mriccell** [comment]
That is correct @mark-au , I will not create another image Complete with Examples.  I will document that if the user wants to run the medrec sample then they need to build the image with the correct INSTALL_TYPE.

**Comment by rjeberhard** [comment]
@mriccell, we should close this issue.  I'm willing to help, but I don't have permission ;)
