### ISSUE TITLE
Image database-enterprise:12.2.0.1-slim: setup scripts do not execute

### ISSUE THREAD

**Issue by Muzietto** [oracle/docker-images#1459]
I am building a container straight from image store/oracle/database-enterprise:12.2.0.1-slim.

I have a few SQL scripts to populate the db on the container.

I mount the scripts directory on my PC into /opt/oracle/scripts/setup

The container starts but the scripts are not executed.

I log into the container and I see that the scripts have been mounted correctly. They are executable by all users. The db has started well: from within the container I can run sqlplus and manipulate the db myself.

What am I doing wrong with the setup scripts? What can i check further?

On a more general note, I'd like to know a page that documents the basic usage of image store/oracle/database-enterprise:12.2.0.1-slim.

**Comment by Djelibeybi** [comment]
Answered in the FAQ: https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/FAQ.md#can-i-use-setup-or-startup-scripts-with-the-oracle-database-image-pulled-from-the-oracle-container-registry-or-docker-hub

**Comment by Muzietto** [comment]
Perfect. Thank you for the fast answer. Closing.
