### ISSUE TITLE
Add SIGTERM support to runOracle.sh

### ISSUE THREAD

**Issue by Djelibeybi** [oracle/docker-images#146]
Currently, when `docker stop` is called, it just issues `SIGTERM` then `SIGKILL` to the `runOracle.sh` script, which is a very inelegant way of shutting down the database.

The `runOracle.sh` script should include signal handlers to trap `SIGTERM` and issue a `SHUTDOWN IMMEDIATE` to the Database before the container exits.

**Comment by brunoborges** [comment]
Hey @gvenzl, was this fixed in your latest PR ?

**Comment by gvenzl** [comment]
No, this is still work in progress.
