### ISSUE TITLE
OracleJava/java-11 run build.sh times out while building the image

### ISSUE THREAD

**Issue by anpanigr** [oracle/docker-images#1460]
Sending build context to Docker daemon  4.096kB
Step 1/9 : FROM oraclelinux:7-slim
 ---> c2b5cb5bcd9d
Step 2/9 : MAINTAINER Aurelio Garcia-Ribeyro <aurelio.garciaribeyro@oracle.com>
 ---> Using cache
 ---> 540bf658937f
Step 3/9 : RUN set -eux; 	yum install -y 		gzip 		tar 	freetype fontconfig 	; 	rm -rf /var/cache/yum
 ---> Running in f230d763d7e2
+ yum install -y gzip tar freetype fontconfig
Loaded plugins: ovl
https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Trying other mirror.
---
My NO_PROXY contains the string ".oracle.com"

**Comment by Djelibeybi** [comment]
Don't include that string in NO_PROXY as yum.oracle.com is hosted outside Oracle's firewall.

**Comment by anpanigr** [comment]
I removed the string ".oracle.com" from NO_PROXY, still I get the same error 
<src123100(EE8)>env | grep PROXY
NO_PROXY=localhost,127.0.0.1,.us.oracle.com,.oraclecorp.com,.oraclevcn.com,slc13lgz,/var/run/docker.sock,10.96.0.0/12,192.168.0.0/16,10.196.12.49,10.247.91.45
HTTPS_PROXY=http://www-proxy-hqdc.us.oracle.com:80
HTTP_PROXY=http://www-proxy-hqdc.us.oracle.com:80
<src123100(EE8)>sh build.sh
Sending build context to Docker daemon  4.096kB
Step 1/9 : FROM oraclelinux:7-slim
 ---> c2b5cb5bcd9d
Step 2/9 : MAINTAINER Aurelio Garcia-Ribeyro <aurelio.garciaribeyro@oracle.com>
 ---> Using cache
 ---> 540bf658937f
Step 3/9 : RUN set -eux; 	yum install -y 		gzip 		tar 	freetype fontconfig 	; 	rm -rf /var/cache/yum
 ---> Running in be0697adb772
+ yum install -y gzip tar freetype fontconfig
Loaded plugins: ovl
https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Trying other mirror.
https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Trying other mirror.

**Comment by Djelibeybi** [comment]
Try using `https_proxy` as the environment variable. I believe `yum` is case sensitive.

**Comment by anpanigr** [comment]
I have setup https_proxy too
<src123100(EE8)>env | grep proxy
http_proxy=http://www-proxy-hqdc.us.oracle.com:80
https_proxy=http://www-proxy-hqdc.us.oracle.com:80
HTTPS_PROXY=http://www-proxy-hqdc.us.oracle.com:80
no_proxy=localhost,127.0.0.1,.us.oracle.com,.oraclecorp.com,.oraclevcn.com,slc13lgz,/var/run/docker.sock,10.96.0.0/12,192.168.0.0/16,10.196.12.49,10.247.91.45
HTTP_PROXY=http://www-proxy-hqdc.us.oracle.com:80

**Comment by Djelibeybi** [comment]
That should work. Can you test whether a container can get to the proxy at all. What's the output from this:
```
$ docker run -e http_proxy=www-proxy-hqdc.us.oracle.com:80 --rm -it oraclelinux:7-slim curl -I www.google.com
```

**Comment by anpanigr** [comment]
$ docker run -e http_proxy=www-proxy-hqdc.us.oracle.com:80 --rm -it oraclelinux:7-slim curl -I www.google.com  
HTTP/1.1 200 OK
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Via: 1.1 10.68.69.9 (McAfee Web Gateway 7.8.2.13.0.30003)
Date: Thu, 12 Dec 2019 22:15:32 GMT
Vary: Accept-Encoding
Server: gws
Expires: -1
Set-Cookie: 1P_JAR=2019-12-12-22; expires=Sat, 11-Jan-2020 22:15:32 GMT; path=/; domain=.google.com
Set-Cookie: NID=193=gi3OkXKorXRqwJ2cHqxKwWPwwQ4kLSnMpArQiOyg2FTnsLAnJAYFY_tyeL7bl6ED596xxMnbBs2zuXSyfT-Mbn-m5XNuM6HXDhYSn7eMXdgdMqzMY85Xx6GpoY1q-q00Pk_AjrO8tk9XM6dDmd_lfInMZDpSoNkD7dlM3YNm02A; expires=Fri, 12-Jun-2020 22:15:32 GMT; path=/; domain=.google.com; HttpOnly
Content-Type: text/html; charset=ISO-8859-1
Accept-Ranges: none
Cache-Control: private, max-age=0
X-Frame-Options: SAMEORIGIN
Proxy-Connection: Keep-Alive
X-XSS-Protection: 0

**Comment by Djelibeybi** [comment]
Ok, drop the `http://` from your configuration for each of the environment variables, i.e it should be `HTTP=www-proxy-hqdc.us.oracle.com:80` and see if that worksl

**Comment by anpanigr** [comment]
<bash>env | grep proxy
http_proxy=www-proxy-hqdc.us.oracle.com:80
https_proxy=www-proxy-hqdc.us.oracle.com:80
HTTPS_PROXY=www-proxy-hqdc.us.oracle.com:80
no_proxy=localhost,127.0.0.1,.us.oracle.com,.oraclecorp.com,/var/run/docker.sock,10.96.0.0/12,10.244.0.0/16,10.241.118.45,10.241.118.45,oracledx.com
HTTP_PROXY=www-proxy-hqdc.us.oracle.com:80

Still see the same issue

**Comment by Djelibeybi** [comment]
There may be an issue with the Akamai node you're hitting from that machine. Can you try from a different location? It works just fine for me, so my local (in Australia) node is fine.

**Comment by mriccell** [comment]
@anpanigr are you still hitting this issue otherwise we should close it.
