### ISSUE TITLE
Oracle readonly ORACLE_HOME

### ISSUE THREAD

**Issue by oehrlis** [oracle/docker-images#1466]
Has it ever been considered to support Oracle read-only home in combination with Docker read only root fs?

- Build the docker image and set ${ORACLE_HOME}/bin/roohctl -enable
- Define tmpfs, bind mounts or volumes for the usual suspects e.g. /var, /tmp, $ORACLE_BASE/homes, $ORACLE_BASE/dbs, $ORACLE_BASE/audit, $ORACLE_BASE/cfgtoollogs
- alternatively adjust the move script to include the dbs, audit and homes folder

Regards
Stefan

**Comment by oehrlis** [comment]
Hi 

Hi

As of Oracle 20c the Oracle Home by default is a "read-only" home.  It's not that the Oracle home is effectively read only, but DB specific files like spfile, init.ora orapwd are no longer in $ORACLE_HOME/dbs. Therefore the function `moveFiles` will not work for 20c.

why not add a check if an Oracle Home is read only. Depending on the check either the files in $ORACLE_HOME/dbs or $ORACLE_BASE/dbs will be moved.

Have you worked on this or should I add a PR to update runOracle.sh

Regards
Stefan

**Comment by yunus-qureshi** [comment]
This is addressed in 21.3 dockerfiles
