### ISSUE TITLE
run racnode1 error

### ISSUE THREAD

**Issue by withqingshao** [oracle/docker-images#1475]
Verifying OS Kernel Parameter: semopm ...FAILED
racnode1: PRVG-1205 : OS kernel parameter "semopm" does not have expected
          current value on node "racnode1" [Expected = "100" ; Current = "32";
          Configured = "100"].

Verifying OS Kernel Parameter: aio-max-nr ...FAILED
racnode1: PRVG-1205 : OS kernel parameter "aio-max-nr" does not have expected
          current value on node "racnode1" [Expected = "1048576" ; Current =
          "65536"; Configured = "1048576"].

Verifying Device Checks for ASM ...FAILED
  Verifying ASM device sharedness check ...FAILED
    Verifying Shared Storage Accessibility:/dev/asm_disk2,/dev/asm_disk1
    ...FAILED
    racnode1: 
racnode1: PRVF-7009 : Could not get the type of storage
    racnode1: 
racnode1: PRVF-7009 : Could not get the type of storage

Verifying resolv.conf Integrity ...FAILED
racnode1: PRVG-10048 : Name "racnode1" was not resolved to an address of the
          specified type by name servers o"127.0.0.11".
racnode1: Check for integrity of file "/etc/resolv.conf" failed

  Verifying (Linux) resolv.conf Integrity ...FAILED
  racnode1: PRVG-10048 : Name "racnode1" was not resolved to an address of the
            specified type by name servers o"127.0.0.11".

Verifying DNS/NIS name service ...FAILED
PRVG-1101 : SCAN name "racnode-scan" failed to resolve

**Comment by mark-au** [comment]
I'm guessing you are trying to build one of the OracleRealApplicationClusters images but which version are you having trouble with?

**Comment by withqingshao** [comment]
12.2.0

**Comment by mark-au** [comment]
Please review the [README.md](https://github.com/oracle/docker-images/tree/master/OracleDatabase/RAC/OracleRealApplicationClusters#section-1--prerequsites-for-rac-on-docker) which lists the prerequisites for building an image. 
It appears you have not performed the sysctl or DNS configuration before building. Can you confirm?

**Comment by withqingshao** [comment]
how to config dns ,can you provide a demo?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mark Cram"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 上午7:33
收件人: "oracle/docker-images"<docker-images@noreply.github.com&gt;; 
抄送: "张绍青"<1311204171@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [oracle/docker-images] run racnode1 error (#1475)




Please review the README.md which lists the prerequisites for building an image.
 It appears you have not performed the sysctl or DNS configuration before building. Can you confirm?

**Comment by mark-au** [comment]
I believe the image checks your nameservers to validate the hostnames you gave correctly resolve back to the container in DNS. These would be configured by your network administrator.

I'll assign to @gvenzl to verify this is correct.

**Comment by gvenzl** [comment]
Actually, @psaini79 is the right person for RAC, reassigning to him.

**Comment by psaini79** [comment]
@withqingshao 

Please paste the  output of  /etc/host. Also, please share the details of docker version.

**Comment by withqingshao** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Param Saini"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 下午2:53
收件人:&nbsp;"oracle/docker-images"<docker-images@noreply.github.com&gt;;
抄送:&nbsp;"张绍青"<1311204171@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [oracle/docker-images] run racnode1 error (#1475)




@withqingshao
 
Please paste the  output of  /etc/host. Also, please share the details of docker version.

**Comment by withqingshao** [comment]
docker version 19.03.5
/etc/hosts

127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
10.200.132.5 example.com

**Comment by psaini79** [comment]
@withqingshao 

Can you please paste your container creation command? It seems you are using IPs from your env as they are different from the IPs I explained in README.md.

Are you using macvlan bridge?

**Comment by psaini79** [comment]
@withqingshao 

No response. Closing this thread. If you still see issue, please reopen it and  provide the details.
