### ISSUE TITLE
Oracle NoSQL 19.5 docker container

### ISSUE THREAD

**Issue by odbaeu** [oracle/docker-images#1483]
Could you please provide new Oracle NoSQL docker files?

Thank you!

**Comment by mark-au** [comment]
We'll chase this up for you but if you wanted an immediate workaround for testing you can modify the existing file:

```
diff --git a/NoSQL/4.5.12/Dockerfile b/NoSQL/4.5.12/Dockerfile
index 3bb3d0d..9b2fdda 100644
--- a/NoSQL/4.5.12/Dockerfile
+++ b/NoSQL/4.5.12/Dockerfile
@@ -24,8 +24,8 @@ FROM oracle/serverjre:8
 
 MAINTAINER Mayuresh A Nirhali <mayuresh.nirhali@oracle.com>
 
-ENV VERSION="4.5.12" \
-    KVHOME=/kv-4.5.12 \
+ENV VERSION="19.5.16" \
+    KVHOME=/kv-19.5.16 \
     PACKAGE="kv-ee" \
     EXTENSION="tar.gz" \
     _JAVA_OPTIONS="-Djava.security.egd=file:/dev/./urandom"
```
And then build it
`docker build -t oracle/nosqlee:19.5.16 .`

**Comment by odbaeu** [comment]
Thank you @mark-au!

I'd like to comment 2 things:
- I was a little confused when I noticed that there is no http/https API (ORDS) anymore to access data. I'd like to access Oracle NoSQL (Basic Edition) with APEX.
- Oracle SQLDeveloper 19.4 (Mac) was unable to connect to Oracle NoSQL 19.5.16 (Lite). I had to go back to SQLDeveloper 19.1.

**Comment by Djelibeybi** [comment]
Those are outside the scope of this repo. I would recommend opening an SR for both if you have Oracle support.

**Comment by NoSQLGuy** [comment]
Daniel Nelle, is it possible you write to me at anand.chandak@oracle.com with your requirements. Like Avi said, this is really outside of the scope of this repo.

**Comment by odbaeu** [comment]
Thank you @NoSQLGuy! I really dislike SRs... but I don't want to talk about that in public.
