### ISSUE TITLE
Oracle Database XE Express not supported in Dockerfile for 19c

### ISSUE THREAD

**Issue by meastp** [oracle/docker-images#1488]
When will you extend the example Dockerfile for Oracle Database 19c to support Express Edition (Standard and Enterprise editions are already supported)?

**Comment by gvenzl** [comment]
Hi @meastp, there is no 19c XE release of the Oracle Database as of yet, so also no Dockerfiles to support it. As soon as it is available, we will provide a Dockerfile for it as well.
