### ISSUE TITLE
can not pull de image , even with login sucess

### ISSUE THREAD

**Issue by josepinto19741994** [oracle/docker-images#1497]
Login Succeeded
root@jose-HP-ProBook-440-G5:~/Documentos/EDP/jpinto/testes# docker pull container-registry.oracle.com/middleware/weblogic:12.2.1.3
Error response from daemon: pull access denied for container-registry.oracle.com/middleware/weblogic, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by rjeberhard** [comment]
The Oracle container registry requires that you go to the website, login, and accept the license before you will be able to pull the Docker image.

**Comment by josepinto19741994** [comment]
ok, I have done it
You last accepted the Oracle Standard Terms and Restrictions on 01/17/2020 at 11:59 AM Coordinated Universal Time (UTC).

docker pull container-registry.oracle.com/middleware/soasuite:12.2.1.3
works FINE

BUT to 
docker pull container-registry.oracle.com/oracle/database:12.2.0.1-ee

 docker pull container-registry.oracle.com/oracle/database:12.2.0.1-ee
Error response from daemon: pull access denied for container-registry.oracle.com/oracle/database, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Does not work sucesefull

**Comment by Djelibeybi** [comment]
You have to accept the license for each image.

**Comment by josepinto19741994** [comment]
yes, see my picture, please
![sow_OK](https://user-images.githubusercontent.com/59601289/72714264-58c17d80-3b66-11ea-9f7a-62821af92e98.png)

**Comment by Djelibeybi** [comment]
The Docker pull command you're using is incorrect. The right pull command is `docker pull container-registry.oracle.com/database/enterprise:12.2.0.1` as is shown in the table of available labels on the Oracle Container Registry  itself.

Note that the image on the Oracle Container Registry does NOT match the one built via the Dockerfiles here on GitHub, as documented in the [Oracle Database FAQ](https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/FAQ.md).

**Comment by mark-au** [comment]
Did this resolve your issue?
