### ISSUE TITLE
SOA admin server startup error

### ISSUE THREAD

**Issue by muthudba** [oracle/docker-images#1500]
[root@localhost OracleSOASuite]# docker logs -f soaas
INFO: CONNECTION_STRING = localhost:1521/soapdb
INFO: RCUPREFIX         = SOA01
INFO: Copying RCU backup file
INFO: Setting RCU for ORCL
INFO: Dropping Schema SOA01...

        RCU Logfile: /tmp/RCU2020-01-28_07-32_149004539/logs/rcu.log

Processing command line ....
Unable to connect to the database using the provided details.
Enter a valid hostname and port or check if the listener is up and running.

ERROR - RCU-6090 Connection step validation failed.
CAUSE - RCU-6090 Skipping main operation: failed to connect to database because database details were missing or invalid.
ACTION - RCU-6090 Provide correct database details and try again.
INFO: Creating Schema SOA01...

        RCU Logfile: /tmp/RCU2020-01-28_07-32_786648714/logs/rcu.log

Processing command line ....
Unable to connect to the database using the provided details.
Enter a valid hostname and port or check if the listener is up and running.

ERROR - RCU-6090 Connection step validation failed.
CAUSE - RCU-6090 Skipping main operation: failed to connect to database because database details were missing or invalid.
ACTION - RCU-6090 Provide correct database details and try again.
ERROR: RCU Loading Failed. Check the RCU logs

**Comment by mark-au** [comment]
You appear to be using the default configuration, do you have a database running with those default settings (localhost:1521/soapdb) or do you need to update `setenv.sh` as described in the README.md?
