### ISSUE TITLE
Recommended process for single instance database container upgrade

### ISSUE THREAD

**Issue by nneul** [oracle/docker-images#1502]
I've seen various articles about upgrade process and techniques using containers, such as:

https://oracle-base.com/articles/12c/multitenant-upgrade-pdb-using-unplug-plugin-12cr1

but have not seen anything clearly defined for use with containers built using these docker images.

Do you have a suggested recipe to follow for upgrades, such as if you did a container deployment with 18.3.0 and wanted to bump to 18.4.0 or 19.3.0?

**Comment by gvenzl** [comment]
Hi @nneul, there is no such recipe for Docker specifically. Oracle Database has many ways to be upgraded, originating from many different use cases. Whether the database runs inside a container, VM or not is orthogonal to these use cases.

In short, I recommend to pick one that works best for you and stick with it.

**Comment by nneul** [comment]
Yeah, but that's not exactly a reasonable answer for docker based deployment if the normal upgrade process is "run the oracle installation scripts on your server". I disagree that this is orthogonal to the 'container' based case since the whole intent is to NOT manually add additional code/scripts/etc. inside the container. For a VM based deployment, I'd agree with your assessment.

At the very least, documenting at least one process that is known to work with one of your vanilla container images would be highly beneficial for users of the image/dockerfiles/etc.

**Comment by gvenzl** [comment]
It's not necessarily a "run the oracle installation scripts on your server". You can, for example, perform an out of place upgrade or you can use the unplug/plug functionality.

That's a great idea, I will forward your request to our upgrade team! :)

**Comment by gvenzl** [comment]
The request to produce guidelines on how to upgrade Oracle DB within containers has been forwarded to the upgrade team.

Closing this issue.
