### ISSUE TITLE
Need an quick advise regarding the patch list

### ISSUE THREAD

**Issue by kavicse87** [oracle/docker-images#1505]
Please advise whether the 12.2.1.4.0 has the below patches updated & inbuilt. As I'm upgrading the environment to 12.2.1.4.0

29135930;One-off
27117282;One-off
26355633;One-off
26287183;One-off
26261906;One-off
26051289;One-off

**Comment by Djelibeybi** [comment]
Which product are you referring to? Database? WebLogic? SOA? Coherence?

**Comment by kavicse87** [comment]
Weblogic

**Comment by kavicse87** [comment]
Right now we're using 12.2.1.3.0 and we've the above patches updated in that environment. we wanted to upgrade the environment to the latest i.e)12.1.4.0 along with the weblogic Kubernetes operator 2.4.0.. But we wanted to make sure whether these patches are inbuilt with the latest one or not..

**Comment by kavicse87** [comment]
from the support.oracle.com we could see only the below patch.

29135930;One-off

Below list of patches aren't available for the product weblogic 12.2.1.3.0. Please provide the downloadable link.

27117282;One-off

But we see the below patches in the image and are applied already..
26355633;One-off
26287183;One-off
26261906;One-off
26051289;One-off

**Comment by mriccell** [comment]
Patches
But we see the below patches in the image and are applied already..
26355633;One-off
26287183;One-off
26261906;One-off
26051289;One-off
Have been applied to the WebLogic binaries pre WebLogic 12.2.1.3 release to address some JDBC driver issues.
