### ISSUE TITLE
Question: How to create tablespaces / users in ORACLE_SID / ORACLE_PDB?

### ISSUE THREAD

**Issue by gutschet** [oracle/docker-images#1511]
Hello,
I have created a 19.3.0-ee image using the provided scripts. I have started a container from the image with ORACLE_SID=MYSID and ORACLE_PDB=MYPDB as environment variables. I have added some startup scripts via a volume mounted to /opt/oracle/scripts/startup. One script creates some tablespaces (01_create_ts.sql) and a second one creates some users, using that tablespaces (02_create_users.sql). My tablespaces are successfully created, but the creation of my users fails, because it says that the tablespaces  do not exist. 
Log of tablespace creation:

> /opt/oracle/runUserScripts.sh: running /opt/oracle/scripts/startup/01_create_ts.sql
> old   1: CREATE TABLESPACE &&TS_USERS_NAME
> new   1: CREATE TABLESPACE USER_MYUSER
> old   3:     DATAFILE '&&TS_USERS_DATAFILE'
> new   3:     DATAFILE '/opt/oracle/oradata/MYSID/MYUSER.DBF'
> 
> Tablespace created.
> 
> old   1: CREATE TABLESPACE &&TS_INDEXES_NAME
> new   1: CREATE TABLESPACE INDEX_MYUSER
> old   3:     DATAFILE '&&TS_INDEXES_DATAFILE'
> new   3:     DATAFILE '/opt/oracle/oradata/MYSID/MYINDEX.DBF'
> 
> Tablespace created.
> 
> old   1: CREATE TEMPORARY TABLESPACE &&TS_TEMP_NAME
> new   1: CREATE TEMPORARY TABLESPACE TEMP_MYUSER
> old   2:     TEMPFILE '&&TS_TEMP_DATAFILE'
> new   2:     TEMPFILE '/opt/oracle/oradata/MYSID/MYTEMP.DBF'
> 
> Tablespace created.

Log of user creation:

> /opt/oracle/runUserScripts.sh: running /opt/oracle/scripts/startup/02_create_users.sql
> old   1: create user &&USER_NAME
> new   1: create user MYUSER
> old   2:   identified by &&USER_PASS
> new   2:   identified by *****
> old   3:   default tablespace &&TS_USERS_NAME
> new   3:   default tablespace USER_MYUSER
> old   4:   temporary tablespace &&TS_TEMP_NAME
> new   4:   temporary tablespace TEMP_MYUSER
> old   5:   quota unlimited on &&TS_USERS_NAME
> new   5:   quota unlimited on USER_MYUSER
> old   6:   quota unlimited on &&TS_INDEXES_NAME
> new   6:   quota unlimited on INDEX_MYUSER
> create user MYUSER
> *
> ERROR at line 1:
> ORA-65048: error encountered when processing the current DDL statement in
> pluggable database MYPDB
> ORA-00959: tablespace 'USER_MYUSER' does not exist

It seems to me, that the tablespaces are created in ORACLE_SID (MYSID), but the user is created in ORACLE_PDB (MYPDB), you can see that in the log of user creation.

How can I create the user in ORACLE_SID instead of ORACLE_PDB?
Why are tablespaces and users created in different localtions (ORACLE_SID / ORACLE_PDB)?
How to do it right?

Kind regards

**Comment by gvenzl** [comment]
Hi @gutschet, you can't create a user in the CDB unless it's a [common user](https://docs.oracle.com/en/database/oracle/oracle-database/19/multi/overview-of-the-multitenant-architecture.html#GUID-3BB161DA-9CC0-4D61-A2C1-5D3662E0DECF).

I think what you want to do is to create the tablespace and the user in the PDB instead of the CDB altogether.
For this, you will have to add an `ALTER SESSION SET CONTAINER=MYPDB;` at the top of your SQL scripts.

**Comment by gutschet** [comment]
HI @gvenzl  thank you. With your advice i got it running now.
