### ISSUE TITLE
ODI tutorial: RCU 6090 hostname errors

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [oracle/docker-images#1515]
Stepping through the instructions for ODI, I 
1) Create ODIDatabase container from [here](https://hub.docker.com/_/oracle-database-enterprise-edition)
2) Create docker image using dockerfile and buildDockerImage.sh (I'm on windows, so I just found the `docker build` command in the shells script and manuallly typed it in
3) Run the image 
(volumes are giving me errors, so I've left them off the `docker run` commands, but that's a topic for another day)

On the third step, I get the error:
```
(base) C:\Users\600301\Documents\docker>docker run -t -i --name ODIContainer --env-file ./odi.env.list -p 20910:20910 oracle/odi:12.2.1.2.6
CONNECTION_STRING=ODIDatabase:1521/odipdb
RCUPREFIX=ODI1
DB_PASSWORD=password
HOST_NAME=oditest

Processing command line ....
Unable to connect to the database using the provided details.
Enter a valid hostname and port or check if the listener is up and running.

ERROR - RCU-6090 Connection step validation failed.
CAUSE - RCU-6090 Skipping main operation: failed to connect to database because database details were missing or invalid.
ACTION - RCU-6090 Provide correct database details and try again.
RCU Loading Failed.. Check the RCU logs
```

How can I get this container to connect to the database container?  I've tried as the `<Database Host Name>` in `CONNECTION_STRING` the name of the container `ODIDatabase`, the hostname environment variable of container ODIDatabase `fa94a1ada3b2`, and `localhost`.  Here is the result of 
```
(base) C:\Users\600301\Documents\docker>docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                       PORTS                                            NAMES
fa94a1ada3b2        store/oracle/database-enterprise:12.2.0.1   "/bin/sh -c '/bin/ba…"   About an hour ago   Up About an hour (healthy)   0.0.0.0:1521->1521/tcp, 0.0.0.0:5500->5500/tcp   ODIDatabase
```

**Comment by Djelibeybi** [comment]
These images are not tested with Docker for Windows. I would recommend installing VirtualBox and running Docker in a an Oracle Linux 7 VM instead. That will eliminate any indiosyncrasies from Windows that may be causing a problem.

Having said that, you appear to be missing a `--link` parameter in your `docker run` command for ODI that would create the connection to the Database container.

**Comment by Djelibeybi** [comment]
The ODI stuff also hasn't been updated for almost three years now, so it's more than slightly out-of-date, unfortunately.

**Comment by Jacob-Stevens-Haas** [comment]
Thanks.  I'll try out the --link option and see if I can get it to work.  Since the machine says 'Unable to connect to the database using the provided details', that hopefully sounds like `--link` is the issue and not Docker for Windows idiosyncracies. 🤞

**Comment by Djelibeybi** [comment]
Did that work? Without the `--link` parameters, providing `localhost` as the DB host _should_ work as the DB maps the ports to the local machine.
