### ISSUE TITLE
Can my open source project use an OracleDB docker image for free?

### ISSUE THREAD

**Issue by jzabroski** [oracle/docker-images#1520]
Hi,

My open source project is used by Fortune 500 companies, and sometimes they file bugs against my project's Oracle provider, but I have no way to test it since none of the clients I do business with for a living use Oracle.

I'm wondering if anyone from Oracle reading this knows if there is a process for open source developers to be able to get a "Student License" or equivalent of Oracle for purposes of integration testing the Oracle ODBC provider.

**Comment by Djelibeybi** [comment]
The OTN Developer license would probably cover this use case: https://www.oracle.com/downloads/licenses/standard-license.html but we are not lawyers here, so you'd need to review it yourself and make your own decisions accordingly.

**Comment by Djelibeybi** [comment]
Alternatively, the Oracle Database Express Edition is free to use and can be used as a test platform for all of the larger Oracle Database variants: https://www.oracle.com/database/technologies/xe-downloads.html

**Comment by Djelibeybi** [comment]
Finally, there are existing`Dockerfiles` for the XE product in this repo, so the combination would be free to use.

**Comment by Djelibeybi** [comment]
See the XE FAQ for more info: https://www.oracle.com/database/technologies/appdev/xe/faq.html

**Comment by jzabroski** [comment]
Which docker images in this repository use XE?  I don't see an "OracleXE" folder or "OracleExpress" folder.  Thank you for your kind help.  I am sure there are Oracle customers who will benefit.

**Comment by Djelibeybi** [comment]
This [`README.md`](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance) is out of date, but the `18.4.0` version supports XE.

**Comment by jzabroski** [comment]
AWESOME! Thank you, Avi!!

**Comment by cjbj** [comment]
Oracle ODBC drivers are also available for free as part of Instant Client, see https://www.oracle.com/database/technologies/releasenote-odbc-ic.html

Also checkout the 'always free' cloud database offering https://docs.cloud.oracle.com/en-us/iaas/Content/FreeTier/freetier.htm  It's the same DB as you might install locally.
