### ISSUE TITLE
Use  oracle linux 8 ad  GraalVM base images

### ISSUE THREAD

**Issue by aboullaite** [oracle/docker-images#1528]
The current graalVM images are based on oracle linux 7, with a very old gcc version (gcc-4.8.5). I am wondering if it possible to use oracle-linux 8-slim image as base image as well ?! Would you consider this option ?

**Comment by Djelibeybi** [comment]
That's an excellent idea. @mzachh what do you think?

**Comment by mzachh** [comment]
Hi Mohammed,

Oracle Linux 8 GraalVM images will come in the future, but we have no specific date yet.

If you need newer dev tools and gcc on OL7 you can already install software collection to the oracle/graalvm-ce OL7 images, like:

```
# yum-config-manager --enable ol7_software_collections
# yum install devtoolset-8
# source /opt/rh/devtoolset-8/enable
# gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
```

Software collections details: https://docs.oracle.com/en/operating-systems/oracle-linux/scl-user/index.html#

Hope this helps until OL8 images are available

**Comment by aboullaite** [comment]
@mzachh fair enough! This exact hack was what I trying to get ride off. 
I still think that having both oracle linux 7 & 8 is an option, but understand your priorities guys! Are you open for a PR on that sense ?

**Comment by Djelibeybi** [comment]
@aboullaite you would need to sign the Oracle Contributor Agreement first: https://www.oracle.com/technetwork/community/oca-486395.html. Once you've done that, feel free to submit a pull request for review.
