### ISSUE TITLE
Unable connect to container using sqldeveloper from Linux-ubuntu

### ISSUE THREAD

**Issue by docker0319dbaghub** [oracle/docker-images#1538]
Hello,

My container is up and working well.
I started the container using : 
docker run --name db2 -p 48000:1521 oracle/database:12.2.0.1-ee

I am able to connect to Oracle database using sqlplus : docker exec -ti db2 sqlplus system@ORCLPDB1

But I am unable to connect using to the container from sqldeveloper from same machine(Linux-ubuntu).

Please suggest.

Thanks and regards,
Srinivas

**Comment by Djelibeybi** [comment]
How are you trying to connect via SQL Developer? What settings are you using?

**Comment by docker0319dbaghub** [comment]
Hi Djelibeybi,

I have already created an Oracle 12c database in the Docker container and trying to connect to the database using SQL developer on Linux-ubuntu(host OS)

Case1:
======
I have used the below solution to setup and connect to SQL developer on Linux.
https://github.com/thraco/sqldev-docker/blob/master/README.md

My Dockerfile:
FROM fedora:23

#Enter the major version number for your SQL Developer RPM
ENV sqldev_ver 19

#Enter the name of the auto-generated version directory under ~/.sqldeveloper
ENV sqldev_subdir 19.2.1

RUN dnf install -y wget file libXtst libXrender

RUN wget --no-cookies --no-check-certificate "https://download.oracle.com/otn/java/jdk/8u241-b07/1f5b5a70bf22433b84d0e960903adac8/jdk-8u241-linux-x64.rpm" -O jdk-linux-x64.rpm
RUN dnf install -y jdk-linux-x64.rpm

COPY import/* /root/

RUN dnf install -y /root/sqldeveloper-${sqldev_ver}*
RUN mkdir -p /root/.sqldeveloper/${sqldev_subdir}/ && echo "SetJavaHome /usr/java/latest/" > /root/.sqldeveloper/${sqldev_subdir}/product.conf

ENV JAVA_HOME=/usr/java/latest
ENTRYPOINT sqldeveloper

The sqldev build works fine:
Syntax: docker build --no-cache -t sqldev -f Dockerfile .

but when I try to start the container using sqldev (sqldeveloper image), it saying JDK path not set
syntax: docker run -ti -v /tmp/.X11-unix/:/tmp/.X11-unix/ --rm -e DISPLAY -e TZ=GMT sqldev

**error:**
 Oracle SQL Developer
 Copyright (c) 2005, 2018, Oracle and/or its affiliates. All rights reserved.

/opt/sqldeveloper/sqldeveloper/bin/../../ide/bin/launcher.sh: line 954: [: : integer expression expected
The JDK (/usr/java/latest/) is not a valid JDK.
The JDK was specified by a SetJavaHome directive in a .conf file or by a --setjavahome option.
Type the full pathname of a JDK installation (or Ctrl-C to quit), the path will be stored in /root/.sqldeveloper/19.2.1/product.conf
^C


Could you help me how JDK should be set.



Case2:
======
Then I have used another solution as below, but still i see no SQL developer screen on my Linux machine.
https://github.com/passing/docker-sqldeveloper

My Dockerfile:
FROM centos:7

COPY src /tmp/src
RUN yum localinstall -y /tmp/src/*.rpm
RUN yum install -y libXext libXrender libXtst file

RUN echo SetJavaHome /usr/java/default >> /opt/sqldeveloper/sqldeveloper/bin/sqldeveloper.conf

CMD sqldeveloper

syntax for building sqldev image: docker build -t sqldeveloper .

The build was successful.

but when I run the run.sh script to start the docker container and connect using SQL developer, I am getting xauth error.

run.sh script
#!/bin/bash

CONFIG=~/.sqldeveloper
TNSNAMES=/etc/tnsnames.ora
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.${USER}.xauth

if [ ! -d "$CONFIG" ]
then
                mkdir "$CONFIG"
        fi

        if [ -f $TNSNAMES ]
        then
                        TNS="-v $TNSNAMES:$TNSNAMES"
                fi

                xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH  nmerge -
docker run -ti $TNS -v $CONFIG:/root -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e DISPLAY=$DISPLAY -e XAUTHORITY=$XAUTH  --net=host sqldeveloper

$./run.sh

**error:**
oracle@oraclelinux:~/docker-sqldeveloper$ ./run.sh
xauth: (argv):1:  unable to read any entries from file "(stdin)"

 Oracle SQL Developer
 Copyright (c) 2005, 2018, Oracle and/or its affiliates. All rights reserved.


In place of run.sh script if I used the below syntax, the don't seen any SQL developer nor it throws any error as below:

oracle@oraclelinux:~/docker-sqldeveloper$ docker run -ti --rm -e DISPLAY -v $HOME/.Xauthority:/home/oracle/.Xauthority --net=host sqldeveloper

 Oracle SQL Developer
 Copyright (c) 2005, 2018, Oracle and/or its affiliates. All rights reserved.


Please share your valuable suggestions.


Thanks and regards,
Srinivas

**Comment by Djelibeybi** [comment]
Why are you trying to run SQL Developer in a Docker container? Why not just run it on Ubuntu and connect as normal?

**Comment by docker0319dbaghub** [comment]
We require SQL Developer to run on Docker container since if a user wanted to connect directly to docker container from VNC as a second option, he/she wanted to run multiple SQL developer sessions for testing purpose.

**Comment by gvenzl** [comment]
Hi @docker0319dbaghub,

As this issue is related to installing and running SQL Developer inside a Docker container, I suggest you post your question and the output above directly in the SQL Developer forum: https://community.oracle.com/community/groundbreakers/database/developer-tools/sql_developer
I'm sure our SQL Developer community will be glad to help you and hopefully find an answer for you quickly.

This repository and the issues associated with it are for the provided Docker build files of this GitHub repo itself.
