### ISSUE TITLE
unable to docker run the OBI docker container for 12.2.1.4 on Oracle linux 7.7

### ISSUE THREAD

**Issue by TonyVertenten** [oracle/docker-images#1539]
Hi,
I am trying to run the docker container as defined in 12.2.1.4. I am able to succesfully create the docker image but when I try to docker run it, I get an error in the createAndStartDomain script. After some digging it seems that the config.sh is not executed properly.
The command I am using to start the container is:
docker run -it -p 9500:9500 -p 9502:9502 -p 9514:9514 -e ADMIN_USERNAME=weblogic -e ADMIN_PASSWORD=welcome1 -e DB_HOST=192.168.15.2 -e DB_PORT=1521 -e DB_SERVICE=orclpdb.mshome.net -e DB_USERNAME=sys -e DB_PASSWORD=xxxx -e SCHEMA_PREFIX=DOBI1 -e SCHEMA_PASSWORD=xxxx oracle/biplatform:12.2.1.4

I have obfuscated the passwords.
Thanks 
Tony Vertenten

**Comment by Djelibeybi** [comment]
Can you provide details on how you built the `oracle/biplatform:12.2.1.4` image? Did you build the underlying images, or did you use the OCR version?

**Comment by TonyVertenten** [comment]
Thank you for your reply.
Yes I did use the FMW image from OCR. Monica Riccelli already pointed out
to me that I should build the FMW image myself as described in the
documentation.
I will give it another go later today.

Thanks
Tony Vertenten

Op wo 4 mrt. 2020 om 21:32 schreef Avi Miller <notifications@github.com>:
