### ISSUE TITLE
Stuck at <JMX Connector Server started at service:jmx:iiop://<IPAdd>:8001/jndi/weblogic.management.mbeanservers.runtime.>

### ISSUE THREAD

**Issue by zunurain222** [oracle/docker-images#1540]
Hi,

I have successfully run the container from the image Weblogic version 12.2.1.4.

Using the same docker host, connection between containers works fine with Managed server (using pack and unpack utility) and Node Manager. Yet, when I attempted with multi host configuration, it started to stuck at the mentioned title above (It was able to connect to admin server, though). At first, connecting Node Manager stucked as well but was solved by using the -Dweblogic.rjvm.enableprotocolswitch=true option, as referred to issue 575[https://github.com/oracle/docker-images/issues/575](url) 

Is using multi host supported or do I have to use Kubernetes?

**Comment by zunurain222** [comment]
here is the output, it seems to be able to connect to the admin server

`[oracle@6bf681b39d34 ~]$ ./domain/bin/startManagedWebLogic.sh ms3 publichostname.com:8000
.
.
JAVA Memory arguments: -Djava.security.egd=file:/dev/./urandom
.
CLASSPATH=/usr/java/jdk-8/lib/tools.jar:/u01/oracle/wlserver/server/lib/weblogic.jar:/u01/oracle/wlserver/../oracle_common/modules/thirdparty/ant-contrib-1.0b3.jar:/u01/oracle/wlserver/modules/features/oracle.wls.common.nodemanager.jar:/u01/oracle/wlserver/common/derby/lib/derbyclient.jar:/u01/oracle/wlserver/common/derby/lib/derby.jar
.
PATH=/u01/oracle/domain/bin:/u01/oracle/wlserver/server/bin:/u01/oracle/wlserver/../oracle_common/modules/thirdparty/org.apache.ant/1.10.5.0.0/apache-ant-1.10.5/bin:/usr/java/jdk-8/jre/bin:/usr/java/jdk-8/bin:/usr/java/jdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/jdk-8/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin
.
***************************************************
*  To start WebLogic Server, use a username and   *
*  password assigned to an admin-level user.  For *
*  server administration, use the WebLogic Server *
*  console at http://hostname:port/console        *
***************************************************
Starting WLS with line:
/usr/java/jdk-8/bin/java -server   -Djava.security.egd=file:/dev/./urandom -cp /u01/oracle/wlserver/server/lib/weblogic-launcher.jar -Dlaunch.use.env.classpath=true -Dweblogic.Name=ms3 -Djava.security.policy=/u01/oracle/wlserver/server/lib/weblogic.policy  -Dweblogic.ProductionModeEnabled=true -Dweblogic.rjvm.enableprotocolswitch=true -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader  -javaagent:/u01/oracle/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/u01/oracle/wlserver/server -Dweblogic.home=/u01/oracle/wlserver/server -Dweblogic.management.server=webtraining1c.mylabserver.com:8000   weblogic.Server
<Mar 5, 2020 7:54:11 AM GMT> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.>
<Mar 5, 2020 7:54:11 AM GMT> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.>
<Mar 5, 2020 7:54:12 AM GMT> <Info> <WebLogicServer> <BEA-000377> <Starting WebLogic Server with Java HotSpot(TM) 64-Bit Server VM Version 25.241-b07 from Oracle Corporation.>
<Mar 5, 2020 7:54:12 AM GMT> <Info> <RCM> <BEA-2165021> <"ResourceManagement" is not enabled in this JVM. Enable "ResourceManagement" to use the WebLogic Server "Resource Consumption Management" feature. To enable "ResourceManagement", you must specify the following JVM options in the WebLogic Server instance in which the JVM runs: -XX:+UnlockCommercialFeatures -XX:+ResourceManagement.>
<Mar 5, 2020 7:54:13 AM GMT> <Info> <Security> <BEA-090065> <Getting boot identity from user.>
Enter username to boot WebLogic server:weblogic
Enter password to boot WebLogic server:
<Mar 5, 2020 7:54:17 AM GMT> <Info> <Management> <BEA-141107> <Version: WebLogic Server 12.2.1.4.0 Thu Sep 12 04:04:29 GMT 2019 1974621>
<Mar 5, 2020 7:54:19 AM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to STARTING.>
<Mar 5, 2020 7:54:19 AM GMT> <Info> <WorkManager> <BEA-002900> <Initializing self-tuning thread pool.>
<Mar 5, 2020 7:54:19 AM GMT> <Info> <WorkManager> <BEA-002942> <CMM memory level becomes 0. Setting standby thread pool size to 256.>
<Mar 5, 2020 7:54:20,738 AM GMT> <Notice> <Log Management> <BEA-170019> <The server log file weblogic.logging.FileStreamHandler instance=960863689
Current log file=/u01/oracle/domain/servers/ms3/logs/ms3.log
Rotation dir=/u01/oracle/domain/servers/ms3/logs
 is opened. All server side log events will be written to this file.>
<Mar 5, 2020 7:54:21,590 AM GMT> <Notice> <Security> <BEA-090946> <Security pre-initializing using security realm: myrealm>
<Mar 5, 2020 7:54:22,157 AM GMT> <Notice> <Security> <BEA-090947> <Security post-initializing using security realm: myrealm>
<Mar 5, 2020 7:54:24,632 AM GMT> <Notice> <Security> <BEA-090082> <Security initialized using administrative security realm: myrealm>
<Mar 5, 2020 7:54:25,142 AM GMT> <Notice> <JMX> <BEA-149512> <JMX Connector Server started at service:jmx:iiop://172.17.0.2:8001/jndi/weblogic.management.mbeanservers.runtime.>`

**Comment by mriccell** [comment]
You are free to use Docker containers in multi-host environments.  No ne of our samples use unpack or pack to create the domain configuration we use WLST or the WebLogic Deploy Tooling.  Please take a look at https://github.com/mriccell/docker-images/tree/master/OracleWebLogic/samples/12213-domain-home-in-image, https://github.com/mriccell/docker-images/tree/master/OracleWebLogic/samples/12213-domain-home-in-image-wdt, or https://github.com/mriccell/docker-images/tree/master/OracleWebLogic/samples/12213-domain.

We have developed open source tools to manage WebLogic domain deployments in K8s which we support and spend engineering resource in developing, enhancing, and developing.  I would advice you to look at deploying your WebLogic workloads in Kubernetes.

**Comment by kanumurisunil** [comment]
we have occured the same issue we ahve changed the timeout parameter in config.xml

from <timeout-seconds>600</timeout-seconds>
to 
>     <timeout-seconds>18000</timeout-seconds>

restarted the Admin server
