### ISSUE TITLE
Openshift - Deploying container image of Oracle SOA suite

### ISSUE THREAD

**Issue by yjhabak** [oracle/docker-images#1541]
Hi,

Am trying to deploying container image of Oracle SOA Suite, in OpenShift platform [openshift-online.com], with following steps. 

1. Accepted the license at https://container-registry.oracle.com
2. Tried to deploy an image at Openshift side, but seeing an error - 
**Could not load image metadata.
you may not have access to the container image "docker.io/library/12.2.1.3:latest"**

Am i missing any steps ?

**Comment by Djelibeybi** [comment]
Probably several, but very few of these images are tested with OpenShift. The URL you're getting in the error seems to indicate that you're not specifying the source of the image correctly, but I've never played with OpenShift, so I don't know how that's configured.

**Comment by yjhabak** [comment]
Initial issue is resolved,m post giving the correct URL. Now status of POD is "InvalidImageName" and not able to see any other error details.

**Comment by mark-au** [comment]
Did you end up entering the correct image path?
