### ISSUE TITLE
oracle domain image does not run for generic installation

### ISSUE THREAD

**Issue by suresh0512** [oracle/docker-images#1552]
Hi - I had installed the generic version of the weblogic as shown below , but when I try to run the image for domain creation, gives me an error because the Docker file under samples directory has the developer image by default..

Do we need to Change it and run, is that expected behavior?

FROM oracle/weblogic:12.2.1.3-developer

Image I built:
oracle/weblogic                   12.2.1.3-generic    081c17d15e33        2 hours ago         1.15GB

**Comment by mriccell** [comment]
Just edit the FROM clause to match your generic image name.

**Comment by suresh0512** [comment]
Hi , could you please help on the below error ?

[oracle@roothost 12213-domain]$ ./run_managed_server.sh MS1 98001
Export environment variables from the property file
Context for docker build is /home/oracle/docker-images/OracleWebLogic/samples/12213-domain
Export environment variables from the /home/oracle/docker-images/OracleWebLogic/samples/12213-domain/properties/domain.properties properties file
 env_arg: CUSTOM_DOMAIN_NAME=myDomain
 env_arg: CUSTOM_ADMIN_NAME=myadmin
 env_arg: CUSTOM_ADMIN_PORT=7001
 env_arg: CUSTOM_ADMIN_HOST=AdminContainer
 env_arg: CUSTOM_MANAGED_SERVER_PORT=8001
 env_arg: CUSTOM_MANAGED_SERVER_NAME_BASE=MS
 env_arg: CUSTOM_CONFIGURED_MANAGED_SERVER_COUNT=2
 env_arg: CUSTOM_CLUSTER_NAME=cluster1
 env_arg: CUSTOM_CLUSTER_TYPE=DYNAMIC
 env_arg: CUSTOM_PRODUCTION_MODE_ENABLED=true
 env_arg: CUSTOM_DOMAIN_HOST_VOLUME=/home/tmp_dm_home
Admin Host is:
Name of managed server to be started is MS1
docker port 98001 will be mapped to managed server port 8001
Admin Host is: AdminContainer
docker run -d -p 98001:8001 -v /home/oracle/docker-images/OracleWebLogic/samples/12213-domain/properties:/u01/oracle/properties  -e CUSTOM_DOMAIN_NAME=myDomain -e CUSTOM_ADMIN_NAME=myadmin -e CUSTOM_ADMIN_PORT=7001 -e CUSTOM_ADMIN_HOST=AdminContainer -e CUSTOM_ADMIN_HOST=AdminContainer -e CUSTOM_MANAGED_SERVER_PORT=8001 -e CUSTOM_MANAGED_SERVER_NAME_BASE=MS -e CUSTOM_CONFIGURED_MANAGED_SERVER_COUNT=2 -e CUSTOM_CLUSTER_NAME=cluster1 -e CUSTOM_CLUSTER_TYPE=DYNAMIC -e CUSTOM_PRODUCTION_MODE_ENABLED=true -e CUSTOM_MANAGED_NAME=MS1 --volumes-from AdminContainer --link AdminContainer:AdminContainer --name MS1 12213-weblogic-domain-in-volume /u01/oracle/container-scripts/startManagedServer.sh
docker: invalid publish opts format (should be name=value but got '98001:8001').
See 'docker run --help'.
[oracle@roothost 12213-domain]$
