### ISSUE TITLE
Oracle DB 12.1.0.2 Enterprise fail on build dockerfail

### ISSUE THREAD

**Issue by Dmytrius** [oracle/docker-images#1555]
When I build docker container with command:

> ./buildDockerImage.sh -v 12.1.0.2 -e -i

I catch fail with next line:

> Removing intermediate container 639eb2e66c09
>  ---> b0f20f80974d
> Step 11/24 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_FILE_2 $INSTALL_RSP $PERL_INSTALL_FILE $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
> COPY failed: stat /var/lib/docker/tmp/docker-builder287030375/linuxamd64_12102_database_1of2.zip: no such file or directory
> 
> ERROR: Oracle Database Docker Image was NOT successfully created.
> ERROR: Check the output and correct any reported problems with the docker build operation.

Please help me,  deal with this error.

**Comment by gvenzl** [comment]
Hi @Dmytrius,

You do not have the installer zip file in the `12.1.0.2` directory: `linuxamd64_12102_database_1of2.zip: no such file or directory`

Please remove the `-i` option that will prevent verification on whether the binaries are in place or not.

**Comment by Dmytrius** [comment]
thanks for the answer @gvenzl , but all versions that are here do not pass validation md5sum...

**Comment by Djelibeybi** [comment]
> thanks for the answer @gvenzl , but all versions that are here do not pass validation md5sum...

Well, you'll need to fix this before continuining. If they don't pass md5 validation, then they're not the right installer zip files (or have been corrupted during download).

**Comment by gvenzl** [comment]
@Dmytrius, you have to download the installer zip files first and put them into the directory.
As per the [README.md](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance#building-oracle-database-docker-install-images):

> Building Oracle Database Docker Install Images
IMPORTANT: You will have to provide the installation binaries of Oracle Database (except for Oracle Database 18c XE) and put them into the dockerfiles/<version> folder. You only need to provide the binaries for the edition you are going to install. The binaries can be downloaded from the Oracle Technology Network, make sure you use the linux link: Linux x86-64. The needed file is named linuxx64__database.zip. You also have to make sure to have internet connectivity for yum. Note that you must not uncompress the binaries. The script will handle that for you and fail if you uncompress them manually!
