### ISSUE TITLE
"illegal option -- p" when creating EE database image

### ISSUE THREAD

**Issue by tkleiber** [oracle/docker-images#156]
Hi!

WIth the actual commit i get the error when running following command:

sudo ./buildDockerImage.sh -v 12.1.0.2 -e -i -p XXXXXXX
./buildDockerImage.sh: illegal option -- p

This option seems to be remove when the database instance part moved from the image to the container but
https://github.com/oracle/docker-images/blob/master/OracleDatabase/README.md
has to be updated to reflect this change.

Kind regards
Torsten Kleiber

**Comment by gvenzl** [comment]
Thank you, the update was missed in the README.
