### ISSUE TITLE
Oracle 18.4.0 does not start in kubernetes cluster if NFS is used as volume

### ISSUE THREAD

**Issue by petermicuch** [oracle/docker-images#1561]
I have configured oracle image build by [docker file](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles/18.4.0) to run within kubernetes statefulset. If I run this image with volume configured as hostpath, there is no issue and DB starts up normally and I am able to connect to it. However when I configure NFS as a file system for volume, there is an issue "[FATAL] ORA-01503: CREATE CONTROLFILE failed". When I observe volume during start of container, I can see that folders and files are created inside (even big ones such as sysaux01.dbf, system01.dbf) without issues. It is only when I see that there are two files control01.ctl and control02.ctl that appear in folder /opt/oracle/oradata/ when the installation of DB fails. Afterwards all files are removed and only empty folder structure remains in volume.

I read this [article ](https://community.oracle.com/thread/2475652) that suggest to set "filesystemio_options" to asynch. However I am not sure how to set this in the image and if that is possible and I also am not sure if this really helps. Is there any suggestion how to make this work correctly using NFS as backing system for my volumes?

```
Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case charact                                     er and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
Confirm the password:
Configuring Oracle Listener.
Listener configuration succeeded.
Configuring Oracle Database XE.
Enter SYS user password:                                                                                                                                                                               *                                     ***********
Enter SYSTEM user password:
**********
Enter PDBADMIN User Password:
*********
Prepare for db operation
7% complete
Copying database files
29% complete
Creating and starting Oracle instance
[FATAL] ORA-01503: CREATE CONTROLFILE failed
ORA-00204: error in reading (block 15, # blocks 1) of control file
ORA-00202: control file: '/opt/oracle/oradata/XE/control01.ctl'
ORA-27072: File I/O error

43% complete
100% complete
[FATAL] ORA-01503: CREATE CONTROLFILE failed
ORA-00204: error in reading (block 15, # blocks 1) of control file
ORA-00202: control file: '/opt/oracle/oradata/XE/control01.ctl'
ORA-27072: File I/O error

29% complete
7% complete
0% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.

Database configuration failed. Check logs under '/opt/oracle/cfgtoollogs/dbca'.
mv: failed to preserve ownership for /opt/oracle/oradata/dbconfig/XE/spfileXE.ora: Permission denied
mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/orapwXE': No such file or directory
mv: '/opt/oracle/product/18c/dbhomeXE/network/admin/listener.ora' and '/opt/oracle/oradata/dbconfig/XE/listener.ora' are the same file
mv: '/opt/oracle/product/18c/dbhomeXE/network/admin/tnsnames.ora' and '/opt/oracle/oradata/dbconfig/XE/tnsnames.ora' are the same file
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
Linux-x86_64 Error: 5: Input/output error
Additional information: 1
2020-03-28T09:25:03.220077+00:00
Shutting down instance (abort) (OS id: 800)
License high water mark = 1
USER (ospid: 800): terminating the instance
2020-03-28T09:25:04.224370+00:00
Instance terminated by USER, pid = 800
2020-03-28T09:25:04.346499+00:00
Instance shutdown complete (OS id: 800)
```

**Comment by petermicuch** [comment]
I also tried to run Oracle 18.4.0 in azure managed cluster using azuredisk for volumes. Installation gets further, but it crashes at 47% without any error message being put on the screen.

```
Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
Confirm the password:
Configuring Oracle Listener.
Listener configuration succeeded.
Configuring Oracle Database XE.
Enter SYS user password:
***********
Enter SYSTEM user password:
*************
Enter PDBADMIN User Password:
********
Prepare for db operation
7% complete
Copying database files
29% complete
Creating and starting Oracle instance
30% complete
31% complete
34% complete
38% complete
41% complete
43% complete
Completing Database Creation
47% complete
```

After that container is restarted and crashes in a loop with this output:
```
Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
Confirm the password:
Configuring Oracle Listener.
Listener configuration succeeded.
Configuring Oracle Database XE.
[FATAL] [DBT-06607] The data file (/opt/oracle/oradata/XE/system01.dbf) already exists on the file system.
   CAUSE: This configuration    is going to create the data file location (/opt/oracle/oradata/XE/system01.dbf). But it is detected that there is an existing database using this data file location or the data files from a previous configuration may be left behind.
   ACTION: Clean up the existing data files, or provide a different db_unique_name.

Database configuration failed. Check logs under '/opt/oracle/cfgtoollogs/dbca'.
/opt/oracle/runOracle.sh: line 119: /opt/oracle/product/18c/dbhomeXE/network/admin/listener.ora: Too many levels of symbolic links
/opt/oracle/runOracle.sh: line 155: /opt/oracle/product/18c/dbhomeXE/network/admin/tnsnames.ora: Too many levels of symbolic links
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining
```

I even tried to use azurefile instead of azuredisk, but also without luck. Although the output looks like DB connection was made, there are no files in the volume under XE folder at all, which shall be there when DB actually works:

```
Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
Confirm the password:
Configuring Oracle Listener.
Listener configuration succeeded.
Configuring Oracle Database XE.
Enter SYS user password:
***********
Enter SYSTEM user password:
************
Enter PDBADMIN User Password:
*************
Prepare for db operation
7% complete
Copying database files
29% complete
100% complete
[FATAL] Recovery Manager failed to restore datafiles. Refer logs for details.
7% complete
0% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.

Database configuration failed. Check logs under '/opt/oracle/cfgtoollogs/dbca'.
mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/spfileXE.ora': No such file or directory
mv: preserving times for '/opt/oracle/oradata/dbconfig/XE/orapwXE': Operation not permitted
mv: preserving permissions for '/opt/oracle/oradata/dbconfig/XE/orapwXE': Operation not permitted
mv: preserving times for '/opt/oracle/oradata/dbconfig/XE/listener.ora': Operation not permitted
mv: preserving permissions for '/opt/oracle/oradata/dbconfig/XE/listener.ora': Operation not permitted
mv: preserving times for '/opt/oracle/oradata/dbconfig/XE/tnsnames.ora': Operation not permitted
mv: preserving permissions for '/opt/oracle/oradata/dbconfig/XE/tnsnames.ora': Operation not permitted
The Oracle base remains unchanged with value /opt/oracle
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
Changing di2dbun from xe to XE
.... (PID:632): Redo network throttle feature is disabled at mount time
2020-03-29T14:57:13.658978+00:00
Successful mount of redo thread 1, with mount id 2917465605
2020-03-29T14:57:13.659258+00:00
Database mounted in Exclusive Mode
Lost write protection disabled
.... (PID:632): Using STANDBY_ARCHIVE_DEST parameter default value as /opt/oracle/product/18c/dbhomeXE/dbs/arch [krsd.c:17717]
Create Relation IPS_PACKAGE_UNPACK_HISTORY
Completed: ALTER DATABASE   MOUNT
```

**Comment by gvenzl** [comment]
Hi @petermicuch,

Are you cleaning up the volumes after the failed runs?
On the Azure cluster you get a:
```
[FATAL] [DBT-06607] The data file (/opt/oracle/oradata/XE/system01.dbf) already exists on the file system.
   CAUSE: This configuration    is going to create the data file location (/opt/oracle/oradata/XE/system01.dbf). But it is detected that there is an existing database using this data file location or the data files from a previous configuration may be left behind.
   ACTION: Clean up the existing data files, or provide a different db_unique_name.
```

On the first run, I spot a `permission denied` error after the control file creation, which I'm wondering whether permissions could be responsible for the control file error as well:

```
mv: failed to preserve ownership for /opt/oracle/oradata/dbconfig/XE/spfileXE.ora: Permission denied
```

**Comment by petermicuch** [comment]
Hi @gvenzl,

I always started with clean volume. I wrote: "After that container is restarted and crashes in a loop with this output". This is where the file already exists of course, because container crashed. The question is, why it fails the first time at "Completing Database Creation 47% complete" without giving the reason. But that is regarding the use case in azure container services, using azure managed disk.

The issue was mainly opened due to fact, that this installation does not work with NFS as volume, which at least for me higher priority. And in there I am certain that this is not permission issue. I even added this into docker file before executing RUN_FILE:
CMD ls $ORACLE_BASE/oradata && chmod -R o+rw $ORACLE_BASE/oradata && chown oracle:dba $ORACLE_BASE/oradata  && exec $ORACLE_BASE/$RUN_FILE

When I observe volume during start of container, I can see that folders and files are created inside (even big ones such as sysaux01.dbf, system01.dbf) without issues. It only fails ones it tries to copy those control files, which I can also see in the volume for brief moment before the error message.

Here is the output of the `ls -all` command from the container after the failure. You can see that oracle/dba is owner. I even tried `chmod -R 777 oradata` after this failure and rerun installation, but without luck:
```
bash-4.2# cd /opt/oracle/
bash-4.2# ls -all
total 17
drwxr-xr-x 1 oracle oinstall   78 Mar 28 09:23 .
drwxr-xr-x 1 root   root       20 Mar 27 16:04 ..
drwxr-xr-x 3 oracle oinstall   16 Mar 28 09:23 admin
drwxr-x--- 2 oracle oinstall    6 Mar 28 09:23 audit
drwxr-xr-x 4 oracle oinstall   31 Mar 28 09:23 cfgtoollogs
-rwxr-xr-- 1 root   root     1136 Mar 27 15:45 checkDBStatus.sh
drwxrwx--- 2 oracle oinstall    6 Mar 27 16:04 checkpoints
drwxrwxr-x 1 oracle oinstall   34 Mar 27 16:04 diag
drwxrwx--- 4 oracle oinstall   78 Mar 27 16:04 oraInventory
drwxrwxrwx 2 oracle dba        64 Mar 28 09:21 oradata
drwxr-xr-x 1 oracle oinstall   17 Mar 27 16:00 product
-rwxr-xr-- 1 root   root     6131 Mar 27 15:45 runOracle.sh
drwxr-xr-x 4 oracle oinstall   34 Mar 27 16:04 scripts
-rwxr-xr-- 1 root   root      774 Mar 27 15:45 setPassword.sh
bash-4.2# cd oradata/
bash-4.2# ls -all
total 5
drwxrwxrwx 2 oracle dba        64 Mar 28 09:21 .
drwxr-xr-x 1 oracle oinstall   78 Mar 28 09:23 ..
drwxrwxrwx 2 oracle dba      4096 Mar 28 09:25 XE
drwxrwxrwx 2 oracle dba        64 Mar 28 09:21 dbconfig
bash-4.2#
```
I am happy to provide more details or even yaml file in case you would like to try to reproduce this on your own. And I also tried different NFS providers (in RedHat, on WinSrv2016).

**Comment by gvenzl** [comment]
Thanks @petermicuch , that would explain it.

The very first error that occurs is an issue with creating the control file:

```
[FATAL] ORA-01503: CREATE CONTROLFILE failed
ORA-00204: error in reading (block 15, # blocks 1) of control file
ORA-00202: control file: '/opt/oracle/oradata/XE/control01.ctl'
ORA-27072: File I/O error

43% complete
100% complete
[FATAL] ORA-01503: CREATE CONTROLFILE failed
ORA-00204: error in reading (block 15, # blocks 1) of control file
ORA-00202: control file: '/opt/oracle/oradata/XE/control01.ctl'
ORA-27072: File I/O error

29% complete
7% complete
0% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.
```

Unfortunately, that output doesn't provide enough details.

Could you retrieve the install log file `/opt/oracle/cfgtoollogs/dbca/XE/XE.log` and, because it's likely that there too won't be enough information, can you also have a look of whether there is a trace file `*.trc` in that folder somewhere and post it as well, please?

**Comment by petermicuch** [comment]
Thanks for you fast responses @gvenzl.

I totally missed that log pointing to /opt/oracle/cfgtoollogs/dbca/XE/XE.log. As expected, there is not much in XE.log, but you may find useful information in the trace.log (original name trace.log_2020-03-30_07-37-41PM).

[XE.log](https://github.com/oracle/docker-images/files/4407245/XE.log)
[trace.log](https://github.com/oracle/docker-images/files/4407246/trace.log)

**Comment by gvenzl** [comment]
Hi @petermicuch,

Thanks for the additional information. The trace file does also not include much more than we already know, the fact that the control file creation fails. I have extracted a few more details but not much new information:

```
[progressPage.flowWorker] [ 2020-03-30 19:39:37.705 UTC ] [CloneDBCreationStep.executeImpl:494]  createCTLSql=Create controlfile reuse set database "XE"
MAXINSTANCES 8
MAXLOGHISTORY 1
MAXLOGFILES 16
MAXLOGMEMBERS 3
MAXDATAFILES 1024
Datafile 
'/opt/oracle/oradata/XE/sysaux01.dbf',
'/opt/oracle/oradata/XE/system01.dbf',
'/opt/oracle/oradata/XE/undotbs01.dbf',
'/opt/oracle/oradata/XE/users01.dbf'
LOGFILE GROUP 1 ('/opt/oracle/oradata/XE/redo01.log') SIZE 200M,
GROUP 2 ('/opt/oracle/oradata/XE/redo02.log') SIZE 200M,
GROUP 3 ('/opt/oracle/oradata/XE/redo03.log') SIZE 200M RESETLOGS;
INFO: Mar 30, 2020 7:39:38 PM oracle.assistants.dbca.driver.StepDBCAJob$1 update
INFO: Percentage Progress got for job:Creating and starting Oracle instance progress:1.0


INFO: Mar 30, 2020 7:39:38 PM oracle.install.commons.util.exception.SynchronizedErrMsgHandler adviceMessages
INFO: Following messages are begin reported:


SEVERE: Mar 30, 2020 7:39:38 PM oracle.install.commons.util.exception.SynchronizedErrMsgHandler adviceMessages
SEVERE: ORA-01503: CREATE CONTROLFILE failed
ORA-00204: error in reading (block 15, # blocks 1) of control file
ORA-00202: control file: '/opt/oracle/oradata/XE/control01.ctl'
ORA-27072: File I/O error
```

The `ORA-27072: File I/O error` means that some underlying I/O failed when reading a block of the control file (as per `ORA-00204: error in reading (block 15, # blocks 1) of control file`), however, there is no more information what the underlying I/O error was.
I found one reference to XFS and 4k sector sizes but that gives a clear Linux error underneath:

```
ORA-00204: error in reading (block 1, # blocks 1) of control file 
ORA-00202: control file: '/opt/oracle/oradata/oradb/control02.ctl' 
ORA-27072: File I/O error 
Linux-x86_64 Error: 22: Invalid argument 
```

Can you share some more information on the NFS that's attached?
And could you also confirm whether the database creation works fine without an NFS volume?

**Comment by petermicuch** [comment]
Hi @gvenzl,

thanks for your support so far.

When I used hostpath as volume (i.e. local disk of the node), everything works fine. But using hostpath is not really ideal solution, especially in multi node clusters, which is actually the case for me.

Now to you question on NFS. I have multiple test clusters where I tried this, and thus I tried multiple versions of NFS.

1. K8s cluster (1master+2nodes) connected to NFS which is hosted on WinSrv2016 (nodes are CentOS VMs).
2. K8s cluster (1master+1worker) connected to NFS hosted on the master node itself (nodes are RedHat VMs).

In the first case I am using [nfs-client-provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client) to provision volumes for me. NFS versions supported by WinSrv2016 are listed [here](https://docs.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview). So up to NFSv4.1.

In the second case, I am NOT using [nfs-client-provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client), but referencing NFS directly in my PVC.
```
  accessModes:
  - ReadWriteMany
  nfs:
    path: /nfsshare_oracle
    server: localhost
```
In the second case even never version of NFS is supported as you can see in the output of this command:
```
[root@xxxxxxxxxxxx]# sudo cat /proc/fs/nfsd/versions
-2 +3 +4 +4.1 +4.2
```

Error in both case is the same as I attached to my last comment. I know that for example Microsoft for MsSQL 2017 and 2019 requires at least NFSv4.2. Could you maybe post what kind of volumes have you used so far in combination with Oracel 18.4.0? Here is my list that I already tried:
|Volume type|Did it work?|
|---|---|
|Hostpath|yes|
|NFS WinSrv2016 hosted (up to v4.1)|no|
|NFS linux hosted (up to v4.2)|no|
|AzureDisk|no|
|AzureFile|no|

**Comment by petermicuch** [comment]
Hi @gvenzl,

have you been able to get it running on NFS or other than Hostpath volume?

**Comment by mikperic** [comment]
I have the same problem and need a solution.

**Comment by mnemonic01** [comment]
Hi
Is the NFS volume mounted on all K8S worker nodes?

**Comment by petermicuch** [comment]
@mnemonic01 I am not sure what are you targeting with the question. I personally tried this with NFS provisioner, having NFS hosted on WinServer2016, but I also tried this on small cluster with 1 master and 1 worker node where I have created NFS volume manually, which in that case was mounted on both, master and that single worker node. So the answer to you question would be: yes it was mounted an all (in this case single) worker nodes.

I hope that helps.

**Comment by mnemonic01** [comment]
Because I saw this I/O error I wanted to know if the pod and container with DB could reach you NFS volume, thats why

**Comment by petermicuch** [comment]
Hmm... I see. It definitely could reach it, because as describe in original post: "When I observe volume during start of container, I can see that folders and files are created inside (even big ones such as sysaux01.dbf, system01.dbf) without issues. It is only when I see that there are two files control01.ctl and control02.ctl that appear in folder /opt/oracle/oradata/ when the installation of DB fails."

So it definitely was writing successfully into that volume until some point in time.

**Comment by petermicuch** [comment]
After some time I tried to install NFS server (10.81.75.75) on Ubuntu and have setup it in the following way:
```
root@nfs:/# cat /etc/exports
/share 10.81.75.8(rw,insecure,fsid=0,sync,no_root_squash,no_subtree_check)
root@nfs:/# cat /var/lib/nfs/etab
/share 10.81.75.8(rw,sync,wdelay,hide,nocrossmnt,insecure,no_root_squash,no_all_squash,no_subtree_check,secure_locks,acl,no_pnfs,fsid=0,anonuid=65534,anongid=65534,sec=sys,rw,insecure,no_root_squash,no_all_squash)
root@ds-aipc-nfs:/# ufw status
Status: active

To                         Action      From
--                         ------      ----
2049                       ALLOW       10.81.75.8
```
So there are not very secure parameters applied to exported directory for my client (10.81.75.8 is k8s node where oracle is running).

And this is output from k8s node:
```
[root@ds-k8s-n02 peter]# nfsstat -m
/var/lib/kubelet/pods/f426f352-bc5a-476a-9075-d5b0515ebd43/volumes/kubernetes.io~nfs/pvc-b84e8b56-218c-442f-8a26-6c7ec5a0b141 from nfs:/k8s-provisioner/vtc-oracle-data-oracle-0-pvc-b84e8b56-218c-442f-8a26-6c7ec5a0b141
 Flags: rw,relatime,vers=4.1,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.81.75.8,local_lock=none,addr=10.81.75.75
```

And since I had it setup, I thought I will give it one more try with Oracle. And believe me or not, Oracle is finally working in this setup with NFS from k8s cluster. I have used very same docker image that I preserved in my personal repo. I am not sure if this is because of different attributes assigned in `/etc/exports`, but it seems like it. Other than that, I used Ubuntu instead of RedHat last time. On Windows Server, I am not able to set exactly the same attributes, or I have not yet found out how. Hope it helps to someone.
@gvenzl  - does this help in anyway to explain failures I had before? If not, I will close this issue as it is anyway opened for too long without any activity.
