### ISSUE TITLE
Oracle 12c in docker doesn't run scripts on container startup

### ISSUE THREAD

**Issue by teju188** [oracle/docker-images#1563]
Hi,

I have created Oracle12c docker container in Linux environment. I am trying to run docker container which will do volume mounting to run the SQL scripts on every startup of docker container using below command. Though after startup of container, files are getting copied to mounted directory location but it is not getting executed. I have tried same example provided on below github article but no luck.

https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/customscripts

**Docker Command:**
docker run --name customscripts -p 1528:1521 -p 5500:5500 -e ORACLE_SID=ORCLSCRIPT -e ORACLE_PDB=CUSTOMSCRIPTS -v /home/oracle/oradata:/opt/oracle/oradata -v /home/oracle/myScripts:/opt/oracle/scripts/startup container-registry.oracle.com/database/enterprise:12.2.0.1

**Comment by Djelibeybi** [comment]
Please see the FAQ: https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/FAQ.md

You can't run startup scripts with the image on Oracle Container Registry. You need to build your own image using the Dockerfiles from GitHub.

**Comment by teju188** [comment]
Hi Team,
 I can not access link provided in the link which will guide on creating the image from docker file. Could you please help me on this on priority.

**Comment by Djelibeybi** [comment]
Start here: https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance

**Comment by teju188** [comment]
Hi Team,
As per documentation on shared link, I have downloaded 'linuxx64_12201_database.z                                                                                        ip' and kept in dockerFiles folder. As a next step, I have copied the  buildDockerImage.sh file from docker-images/OracleDatabase/SingleInstance/dockerfiles/ folder and kept under my dockerFiles folder on server. I have tried executing it with below command but getting below mentioned error. Is there any step that I am missing or Is buildDockerImage.sh file has any errors. Please suggest. I couldn't find much on this issue.

**Command:**
. ./buildDockerImage.sh -v 12.1.0.2 -e 

**Error:**
' is not a typo you can use command-not-found to lookup the package that contain                                                                                        s it, like this:
    cnf
bash: ./buildDockerImage.sh: line 12: syntax error near unexpected token `$'{\r'                                                                                        '
'ash: ./buildDockerImage.sh: line 12: `usage() {

**Comment by Djelibeybi** [comment]
You can't just copy individual files. You need to use `git` to clone the entire repo and then download the binary zip file to the same directory as the `Dockerfile`

**Comment by teju188** [comment]
Hi, I am struggling with cloning the repository and following the further steps. Could you please refer me to the step wise guide to get it done. Also which Oracle version supports to run the scripts on startup. I am struggling from long for getting it done.

**Comment by Djelibeybi** [comment]
The page I provided above is all the steps you need to follow: https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance

The scripts provided in this repo build Docker images for multiple Database versions: `11.2.0.2  12.1.0.2  12.2.0.1  18.3.0  18.4.0  19.3.0`. All of the images you build support running scripts on startup of the container. You just need to build the image itself.

**Comment by teju188** [comment]
Hi,

I am getting below error while creating the container with below command. Image got created successfully as suggested by you. Could you please help. I have referred #123 and #246 but couldn't resolve my issue. Please suggest.

**Command:**
docker run --name my_oracle_container1 -p 1548:1521 -v /home/oracle/myScripts:/opt/oracle/scripts/startup -v /home/oracle/oradata:/opt/oracle/oradata oracle/database:12.1.0.2-ee

**Error:**
SQL> ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/initORCLCDB.ora'
SQL> Disconnected
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/checkDBStatus.sh: line 26: sqlplus: command not found
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:

**Comment by teju188** [comment]
Also I couldn't run following commands as it was giving error for unexpected argument

Please try to rebuild the image using buildDockerFile.sh -p <password> or using --build-arg ORACLE_PWD=<password> if you are building manual with docker build

**Comment by Djelibeybi** [comment]
This issue is already closed. Please open a new issue.
