### ISSUE TITLE
copy failed: stat /var/lib/docker/tmp/docker-builder533822263/cargo.lock: no such file or directory

### ISSUE THREAD

**Issue by bertvb1** [oracle/docker-images#1567]
Hi

I installed docker on my linux mint, but when I try to docker-compose build, it fails on step 8 and i get this error:
copy failed: stat /var/lib/docker/tmp/docker-builder533822263/cargo.lock: no such file or directory
I'm new to linux and docker, so I don't know much of what to do, can anyone help?

Kind regards,
Van Bovn Bert

**Comment by Djelibeybi** [comment]
Fails on step 8 of what?

**Comment by bertvb1** [comment]
Step 8 of the building storage

**Comment by Djelibeybi** [comment]
I have no idea what you're talking about. Please provide more specific information.

**Comment by bertvb1** [comment]
I cloned a repository from github, I installed docker and docker-compose, then they said the next step was to open my console in the cloned directory and execute the following commands: docker-compose build and then docker-compose up
But when I start docker-compose build, it says it has to 12 steps for building storage, but it goes into error on the 8th step

**Comment by Djelibeybi** [comment]
You should ask in the same repository from which you cloned then.
