### ISSUE TITLE
/setPassword.sh does not work for Oracle XE: no such file or directory

### ISSUE THREAD

**Issue by tkleiber** [oracle/docker-images#157]
Hi!

The database is up as I can see in the log and the login dialog for APEX is reachable too.

I try to change the password for an Oracle XE container similar as described in 
https://blogs.oracle.com/developer/entry/creating_and_oracle_database_docker

I have opened another shell and changed to the directory, where setPassword is located in the host:
ls -la setPassword.sh
-rwxrwxrwx 1 vagrant vagrant 180 Sep  3 04:34 setPassword.sh

But docker exec does not find it:

sudo docker exec db11.2.0.2-xe ./setPassword.sh LetsDocker
rpc error: code = 2 desc = oci runtime error: exec failed: exec: "./setPassword.sh": stat ./setPassword.sh: no such file or directory

Kind regards
Torsten Kleiber

**Comment by gvenzl** [comment]
This still missed a symbolic link being created in the current directory.

**Comment by brunoborges** [comment]
@tkleiber could you please see if latest commit from @gvenzl fixed this issue?

**Comment by brunoborges** [comment]
I'll assume this is fixed by commoit 375c028

**Comment by tkleiber** [comment]
Confirmed that the problem is solved, sorry for the delay, but I was on vacation.

**Comment by tkleiber** [comment]
But the error happens furthermore in Oracle EE.

**Comment by gvenzl** [comment]
Can you check whether that file exists and whether you typed the command correctly (with a . at the beginning). It's hard to guess without seeing the actual command/error:

    gvenzl-mac:~ gvenzl$ docker exec oracle-ee ./setPassword.sh LetsDocker
    The Oracle base remains unchanged with value /opt/oracle
    
    SQL*Plus: Release 12.1.0.2.0 Production on Thu Oct 13 22:22:11 2016
    
    Copyright (c) 1982, 2014, Oracle.  All rights reserved.
    
    
    Connected to:
    Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
    With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options
    
    SQL>
    User altered.
    
    SQL>
    User altered.
    
    SQL>
    Session altered.
    
    SQL>
    User altered.
    
    SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
    With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

**Comment by tkleiber** [comment]
The file is not in the ee container as following commands should be shown:

[vagrant@oraclelinux7 ~]$ docker exec db12.1.0.2-ee ls setPassword.sh
ls: cannot access setPassword.sh: No such file or directory
[vagrant@oraclelinux7 ~]$ docker exec db12.1.0.2-ee ls
[vagrant@oraclelinux7 ~]$ docker exec db12.1.0.2-ee pwd
/home/oracle
[vagrant@oraclelinux7 ~]$ docker exec db12.1.0.2-ee find / -name setPassword.sh
find: '/etc/dhcp': Permission denied
find: '/etc/pki/rsyslog': Permission denied
find: '/proc/tty/driver': Permission denied
find: '/root': Permission denied
find: '/var/cache/ldconfig': Permission denied
find: '/var/empty/sshd': Permission denied
find: '/var/lib/machines': Permission denied
find: '/var/lib/rsyslog': Permission denied
find: '/var/lib/yum/history/2016-07-19/1': Permission denied
find: '/var/lib/yum/history/2016-07-19/2': Permission denied
find: '/var/lib/gssproxy/clients': Permission denied
find: '/var/lib/gssproxy/rcache': Permission denied
find: '/var/lib/nfs/statd': Permission denied
find: '/var/lib/rpcbind': Permission denied
find: '/var/log/oracle-rdbms-server-12cR1-preinstall/backup/Jul-28-2016-19-04-10': Permission denied
find: '/var/log/oracle-rdbms-server-12cR1-preinstall/results': Permission denied
find: '/var/spool/up2date': Permission denied
find: '/var/spool/cron': Permission denied

**Comment by brunoborges** [comment]
@tkleiber we don't use Vagrant, so we can't test it. Clearly it is a problem with your environment. Sorry.

**Comment by gvenzl** [comment]
@tkleiber, looks like that something went wrong during the build, if the file is not there. It is copied as part of the run and config file into $ORACLE_BASE and then linked later on to the $HOME folder: ` ln -s $ORACLE_BASE/$PWD_FILE $HOME/ && \`

Can you post the build log?

**Comment by tkleiber** [comment]
After pulling the latest changes from github the problem is not reproducible anymore. Thank you nevertheless.
