### ISSUE TITLE
ODI Docker V 12.2.1.2.6: getting error while running sh /odi/studio/odi.sh

### ISSUE THREAD

**Issue by alisheykhi** [oracle/docker-images#1573]
Hello,

I have created ODIContainer and ODIDatbase based on the readme file in this [link](https://github.com/oracle/docker-images/tree/master/OracleDataIntegrator).
Everything works well and containers are up and running. but when I run the command `sh odi.sh` inside ODIContainer in directory `$HOME/odi/studio`, I face an error for launching the ODI Studio:
```
Oracle Data Integrator 12c (12.2.1.2.6)
Copyright (c) 1997, 2016, Oracle and/or its affiliates. All rights reserved.
/u01/oracle/odi/studio/bin/../../../jdeveloper/ide/bin/launcher.sh: line 1332: file: command not found
```

**Comment by Djelibeybi** [comment]
Are you trying to start a GUI application? That won't work from inside a container anyway (at least, not without a bunch of changes).

**Comment by alisheykhi** [comment]
Dear @Djelibeybi,

thanks for your quick response.
If I can't run odi studio, how can i use this container?
already I trying run with x11 but it doesn't work.

**Comment by Djelibeybi** [comment]
You need to use Studio on a different machine to access ODI inside the container, AFAIK.
