### ISSUE TITLE
A few issues - Common User, and then Stored Procedure in invalid state

### ISSUE THREAD

**Issue by bkbonner** [oracle/docker-images#1577]
I created an Oracle 19c SE image using:

./buildDockerImage.sh -v 19.3.0 -s

Then I ran:

docker run --name oracle19c -p 32769:1521 -p 5500:5500 -e ORACLE_SID=XE -e ORACLE_PWD=<<password>> oracle/database:19.3.0.se

Everything for both of these command seems to exceed.

So I connect in as SYSTEM using the password: <<password>> above.  I try to issue the following commands that I used to use against Oracle 11g:

create user unituser identified by password;
create user devuser identified by password;

grant all privileges to unituser;
grant all privileges to devuser;

When I try to create the user, it gives me an error:

ORA-65096 - invalid common user or role name.

I read that common users have access to all PDBs, so I use;  c##devuser:

created user c##unituser identified by password;
create user c##devuser identified by password;

and then:

grant all privileges to c##unituser;
grant all privileges to c##devuser;

These seem to work OK, but when I created a stored procedure that needed access to the view dba_constraints.

I tried running the procedure and it fails with:  

ORA-06550. PLS-00905: object C##DEVUSER.SP_MDF_TBL_META is invalid

And when I look at the line that's invalid, it's trying to access the view dba_constraints.

Is there some other way I should be using this docker image??

Thank you for your assistance.

**Comment by bkbonner** [comment]
btw, I realize that the sp_mdf_tbl_meta is a stored proc we wrote that worked on ORACLE XE and 11g.  but for some reason the same privileges do not allow a procedure that references this procedure to see the dba_constraints view.

I'm just wondering if there's a setting or switch that I've missed.

**Comment by bkbonner** [comment]
Bueller?  Bueller?

**Comment by Djelibeybi** [comment]
This _sounds_ like it's more of a general database question, not Docker specific. Have you tried this on plain Database 19, i.e. perhaps by leveraging our Vagrant build: https://github.com/oracle/vagrant-boxes/tree/master/OracleDatabase

**Comment by bkbonner** [comment]
it might be.   we've been running against Oracle XE (docker) and also against Oracle 11g on AWS which has been upgraded to 19c (but not with pluggable DB).

Is there a way to make Oracle locally not have a pluggable DB config?   This might be one solution to the issue, but I'm not sure how to do it.

I'll investigate further....it seems to be a privileges issue with the pluggable DB setup.

**Comment by Djelibeybi** [comment]
You can also get Database-specific community support over on our Groundbreakers Community too: https://community.oracle.com/community/groundbreakers/database

The issues here on GitHub are  for issues with the container images themselves, not the products they contain.

**Comment by bkbonner** [comment]
thx.

**Comment by bkbonner** [comment]
thanks for the help.  I did some more research around the dba_constraints and the 'select any dictionary' privilege has to be granted to the user to get it to work according to this:   
https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/cdb_-views.html#GUID-2B8A1B8B-4F5B-4FBB-AE0B-68B6F8BA7D5E

**Comment by Djelibeybi** [comment]
Glad you discovered the solution.
