### ISSUE TITLE
[RAC] `--volume racstorage:/oradata` hangs up container process on creation.

### ISSUE THREAD

**Issue by ishammahajan** [oracle/docker-images#1581]
CMAN and RACStorage server has been created and launched successfully. The volume for NFS storage has also been created using the following command -
```
docker volume create --driver local \
--opt type=nfs \
--opt   o=addr=192.168.17.25,rw,bg,hard,tcp,vers=3,timeo=600,rsize=32768,wsize=32768,actimeo=0 \
--opt device=:/oradata \
racstorage
```
as specified in the README.

However, launching `racnode1` using
```
docker create -t -i \
  --hostname racnode1 \
  --volume /boot:/boot:ro \
  --volume /dev/shm \
  --tmpfs /dev/shm:rw,exec,size=4G \
  --volume /opt/containers/rac_host_file:/etc/hosts  \
  --volume /opt/.secrets:/run/secrets \
  --dns-search=example.com \
  --privileged=false \
  --volume racstorage:/oradata \
  --cap-add=SYS_NICE \
  --cap-add=SYS_RESOURCE \
  --cap-add=NET_ADMIN \
  -e NODE_VIP=172.16.1.160  \
  -e VIP_HOSTNAME=racnode1-vip  \
  -e PRIV_IP=192.168.17.150  \
  -e PRIV_HOSTNAME=racnode1-priv \
  -e PUBLIC_IP=172.16.1.150 \
  -e PUBLIC_HOSTNAME=racnode1  \
  -e SCAN_NAME=racnode-scan \
  -e SCAN_IP=172.16.1.70  \
  -e OP_TYPE=INSTALL \
  -e DOMAIN=example.com \
  -e ASM_DISCOVERY_DIR=/oradata \
  -e ASM_DEVICE_LIST=/oradata/asm_disk01.img,/oradata/asm_disk02.img,/oradata/asm_disk03.img,/oradata/asm_disk04.img,/oradata/asm_disk05.img  \
  -e CMAN_HOSTNAME=racnode-cman1 \
  -e CMAN_IP=172.16.1.15 \
  -e COMMON_OS_PWD_FILE=common_os_pwdfile.enc \
  -e PWD_KEY=pwd.key \
  --restart=always \
  --tmpfs=/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  --cpu-rt-runtime=95000 \
  --ulimit rtprio=99  \
  --name racnode1 \
  oracle/database-rac:12.2.0.1
```
and then `docker start racnode1`, simply doesn't run. The container is created correctly, but starting it up does nothing
```
[root@e2e ~]# docker start racnode1

```
I can't even seem to remove the container with `docker rm racnode1` after I `ctrl+c` back into the shell -- the command does nothing there too. Running any command related to racnode1 does nothing. All other docker commands seem to work fine though.

However, removing the line `--volume racstorage:/oradata` from the container creation and then starting it up does properly startup the container properly -- obviously not successfully, since there is no volume for ASM storage then.

What could be the issue?

**Comment by psaini79** [comment]
@ishammahajan 

Please send me the output of of following:
`
docker logs -f racnode1
rpm -qa |  grep docker
cat /etc/oracle-release
uname -r
docker info
`

**Comment by psaini79** [comment]
@ishammahajan 

I have one more question.  What was the sequence to delete the container? Did you delete first racstorage container or volume and then racnode container?

Also, login inside the container `docker exec -i -t racnode1 /bin/bas` and see if /tmp/orod.log is there? if yes, paste the contents.

**Comment by ishammahajan** [comment]
@psaini79 
`docker logs -f racnode1`: blank response -- no logs, I'm assuming
`rpm -qa | grep docker`:
```
docker-ce-19.03.8-3.el7.x86_64
docker-ce-cli-19.03.8-3.el7.x86_64
```
`cat /etc/oracle-release`: file doesn't exist on my file system. If you meant log into the container, I don't think the container has actually started with `docker start`. That's because `docker ps` doesn't return with the container's details.
`uname -r`: 3.10.0-957.12.1.el7.x86_64
`docker info`:
```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 37
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.12.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 28.6GiB
 Name: e2e-66-149
 ID: 7JBE:XLCN:UWUK:3JNM:TLGJ:4KZQ:ON7H:W7LF:J34G:BJGJ:7ZIR:Q6SJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
_____
`docker exec -i -t racnode1 /bin/bash` doesn't return anything because as mentioned above I don't think the container actually started up.

**Comment by ishammahajan** [comment]
Sequence of deleting the container would be just `docker rm racnode1` because again it doesn't seem like the container is running. (although `docker stop racnode1` doesn't do anything as well -- just hangs up the terminal)

**Comment by psaini79** [comment]
@ishammahajan 

You are on UEK 3 but you must be on UEK 4 or UEK 5. I would prefer UEK 5 and OL 7. Also, use Oracle docker engine on OL and it should work without any issue.

For Oracle container runtime, please use following link:
https://docs.oracle.com/en/operating-systems/oracle-linux/docker/docker-install.html

**Comment by ishammahajan** [comment]
Thanks! Would you please also let me know why this would affect the container not starting up?

**Comment by Djelibeybi** [comment]
> You are on UEK 3 but you must be on UEK 4 or UEK 5. I would prefer UEK 5 and OL 7. Also, use Oracle docker engine on OL and it should work without any issue.

Just to clarify: this is the CentOS kernel or RHCK equivalent. Not the UEK.

**Comment by ishammahajan** [comment]
@Djelibeybi thanks for clarifying! Unfortunately I don't know what step I should take. Since I don't have the UEK, what should I upgrade my CentOS kernel to -- which version?

**Comment by Djelibeybi** [comment]
CentOS (and RHEL)'s kernels tend to be too old for some of the requirements for RAC. I would encourage you to install Oracle Linux 7 Update 8 instead of CentOS, using the ISOs from here: https://yum.oracle.com/oracle-linux-isos.html

Like CentOS, Oracle Linux is free to download, distribute and use and all our errata are freely available too via yum.oracle.com.

**Comment by psaini79** [comment]
Thanks @Djelibeybi  for the clarification.

@ishammahajan , We tested RAC with kernel version 4.1.x and 4.14 and actually RAC on Docker doesn't work with kernel version 3.x.  Please use the link @Djelibeybi  provided  to download and install OL and keep me posted if you see any issue for RAC on Docker setup.

**Comment by ishammahajan** [comment]
@Djelibeybi unfortunately the server provider I use doesn't allow for OL as an OS. Is it possible that I run an OL container and within it run RAC?

Thanks for the info @psaini79 ! Make's my understanding much clearer.

**Comment by Djelibeybi** [comment]
@ishammahajan you can't nest containers. Perhaps you should consider running RAC via Vagrant/VirtualBox instead of Docker, so you can do it on your desktop: https://github.com/oracle/vagrant-boxes/tree/master/OracleRAC

**Comment by ishammahajan** [comment]
So I installed the latest kernel. `5.6.4-1.el7.elrepo.x86_64` is the output of `uname -r` now. Remade all images and containers and ran them. Same issue. Can there be any other reason for the issue?

**Comment by psaini79** [comment]
@ishammahajan 

Seems there is some confusion as I clearly mentioned to try RAC on Docker  on UEKR5 which is based on 4.14 kernelline or UEKR which is based on 4.1 kernel main line on **Oracle Linux** with **Oracle Container runtime** not on kernel 5.6.

To understand UEKR5, you can see following blog:
https://blogs.oracle.com/wim/unbreakable-enterprise-kernel-release-5-for-oracle-linux-7

Also, you have not configured the docker host system as per the suggestion https://docs.oracle.com/en/operating-systems/oracle-linux/docker/docker-install.html i.e. overlay2 (storage driver) with xfs file system (backing file system).

I can see following in the output you have pasted me previously:

 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>

Once you configure it correctly, I am sure it should work without any issue. Though RAC on docker will not work on this machine as it is not configured correctly, let me understand the container startup issue correctly.

1) you started racstorage container
 Note: Dd you check it started successfully?
 Please paste output of `docker logs -f racstorage`
2) You mentioned if you remove /oradata then racnode1 comes up.
 Paste me the logs of racnode1
3) nfs package detail
      rpm -qa |  grep nfs-utils

**Comment by psaini79** [comment]
@ishammahajan 

Any update on this?

**Comment by ishammahajan** [comment]
Ah, I forgot to respond. I haven't tried this yet, due to a lack of appropriate resources. I'll close this for now. Thanks for all the help! :)
