### ISSUE TITLE
Can’t run oracle container with image from docker file

### ISSUE THREAD

**Issue by teju188** [oracle/docker-images#1583]
Hi,

I am getting below error while creating the container with below command. Image got created successfully as suggested by you. Could you please help. I have referred #123 and #246 but couldn't resolve my issue. Please suggest.

Command:
docker run --name my_oracle_container1 -p 1548:1521 -v /home/oracle/myScripts:/opt/oracle/scripts/startup -v /home/oracle/oradata:/opt/oracle/oradata oracle/database:12.1.0.2-ee

Error:
SQL> ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/initORCLCDB.ora'
SQL> Disconnected
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/checkDBStatus.sh: line 26: sqlplus: command not found
tail: cannot open '/opt/oracle/diag/rdbms///trace/alert*.log' for reading: No such file or directory
tail: no files remaining
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
#####################################
The following output is now a tail of the alert.log:

**Comment by gerbil** [comment]
Please try to add --cpuset-cpus="0-7" to a docker run command.

**Comment by teju188** [comment]
I have tried with adding as suggested but got below error then I have change it to 0-3 then it is giving same error as earlier. Please suggest.

**Error:**
docker: Error response from daemon: Requested CPUs are not available - requested 0-7, available: 0-3.

**Comment by teju188** [comment]
Is there any update on this issue. Please suggest.

**Comment by gvenzl** [comment]
Hi @teju188, in case this is still an issue, the database cannot find the parameter file:

```
LRM-00109: could not open parameter file '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/initORCLCDB.ora'
```

which would suggest that your volume doesn't contain the files required to run the database:

`-v /home/oracle/oradata:/opt/oracle/oradata`
