### ISSUE TITLE
Can't start initialized image

### ISSUE THREAD

**Issue by gerbil** [oracle/docker-images#1584]
After doing prepareOracle.sh and commiting this image i can't run it using docker.. i got fatal oracle error on startup..

[ 2020-04-16 14:21:20.523 UTC ] [FATAL] ORA-01034: ORACLE not available

I will add some context here:
1. Base image build done using 18.0.4 dockerfile
2. Custom scripts deployed to a running container after database setup finished
3. Docker commit to a separate image
4. Docker run this image 
5. Fatal error on startup

**Comment by gvenzl** [comment]
Hi @gerbil, the error suggests that the Oracle Database hasn't been started up yet at that point.
