### ISSUE TITLE
Missing OracleWebLogic/samples/1411-domain-home-in-image

### ISSUE THREAD

**Issue by tuxerrante** [oracle/docker-images#1587]
Hi,
I'm trying to create a Kubernetes pod with a docker image containing 14.1.1.0-slim WLS.

I am following this guide https://oracle.github.io/weblogic-kubernetes-operator/quickstart/create-domain/

and while creating the domain, k8s can not find the image of WLS, despite having set

domainHomeImageBase: eu-frankfurt-1.ocir.io/frhyz1ndv9sd/ccp/weblogic:14.1.1.0-slim
inside [create-domains-input.yaml](http://github.com/oracle/weblogic-kubernetes-operator/blob/master/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain-inputs.yaml) .

Then I do as follows:
`domain-home-in-image $ ./create-domain.sh -i ../../../../../create-domain-inputs.yaml -o ../../../ ../../../domain1_out/ -u weblogic -p Weblogic1 -e`

I think the problem is that the image is searched by default on https://github.com/oracle/docker-images.git where _domainHomeImageBuildPath_ point to
https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/12213-domain-home-in-image/Dockerfile

How can I redirect it to another repo like the internal OCIR one inside our OCI tenant?
Are you planning to publish an equivalent dockerfile with the new 14 soon?

-----
Trying from the OCI cloud shell I can download the wls 14 slim image but then it stucks on another image.
I've tried to set the variable 'image' create-domain-inputs.yaml but here's the results:
- image: weblogic:14.1.1.0-slim --> Failed to pull image "weblogic:14.1.1.0-slim": rpc error: code = Unknown desc = pull access denied for weblogic, repository does not exist or may require 'docker login'
- #image: --> Failed to pull image "domain-home-in-image:14.1.1.0-slim":
- image: 12213-domain-home-in-image --> Failed to pull image "12213-domain-home-in-image"

-----
Thanks

**Comment by mriccell** [comment]
This issue belongs to the Kubernetes  GitHub project.
