### ISSUE TITLE
Facing issue in running racnode1

### ISSUE THREAD

**Issue by onkarnigam14** [oracle/docker-images#1591]
HI I am facing issue in building the racnode1 , because of which i am not able to get the ASM disks inside the /oradata
Starting Update UTMP about System Boot/Shutdown...
[FAILED] Failed to mount RPC Pipe File System.
See 'systemctl status var-lib-nfs-rpc_pipefs.mount' for details.
[DEPEND] Dependency failed for rpc_pipefs.target.
[DEPEND] Dependency failed for RPC security service for NFS client and server.
[ OK ] Started Update UTMP about System Boot/Shutdown.

**Comment by psaini79** [comment]
@onkarnigam14 

It seems you are storage container for shared storage. Can you please paste the output of following:
docker logs -f racnode1
docker logs -f racnode-storage

docker info
cat /etc/oracle-release
uname -r
systemctl status docker

**Comment by psaini79** [comment]
@onkarnigam14 

Any update on this?

**Comment by onkarnigam14** [comment]
It is resolved , thanks

**Comment by psaini79** [comment]
@onkarnigam14 

Closing this.
