### ISSUE TITLE
Change init parameter not possible (compatible) in 18c XE

### ISSUE THREAD

**Issue by zoony87** [oracle/docker-images#1592]
Hey, I want to change the compatible parameter of the DB and downgrade it dynamically on first start 

First I tried to alter the system in sqlplus, but shutdown imediate and startup does not function.

Altering the system and restart docker container ends in a conflict with control files. 

Next, I tried to manipulate the init files bevore configure the database in the container
and changed the init.ora compatible params to something else.  But then I got again problems with the controlfile version. 

I tried to change it via script on startup in $ORACLE_HOME/dbs/init.ora file and in opt/oracle/product/18c/dbhomeXE/assistants/dbca/templates/XE_Database.dbc.

But still, the database has problems to start.

How can I change the compatible using the init files or altering the system?

**Comment by gvenzl** [comment]
Please ask this question on the [Oracle XE Forum](https://community.oracle.com/community/groundbreakers/database/developer-tools/oracle_database_express_edition_xe/overview) as this question is related to Oracle XE directly and not the scripts provided in this repository.
