### ISSUE TITLE
How to reach noSQL outside the container

### ISSUE THREAD

**Issue by olelbis** [oracle/docker-images#1594]
I'm able to use CLI, Ping and also sql for noSQL inside a docker.
But whe i try for example:
docker run -h store -d -p 5000:5000 --name=kvlite oracle/nosql

on my windows machine:
netstat -an|find "5000"
  TCP    0.0.0.0:5000           0.0.0.0:0              LISTENING
  TCP    [::]:5000              [::]:0                 LISTENING

from cmd or powershell i try:
D:\Java\jdk8\bin\java.exe -jar .\kvstore.jar ping -host localhost -port 5000
Can't find store topology: Could not contact any RepNode at: [localhost:5000]

Same results if i try with my hostname or ip address.

Cheers

**Comment by adeywong** [comment]
Bumping this - anyone ?

**Comment by Djelibeybi** [comment]
Have you opened the firewall on your Docker host to allow port 5000?

**Comment by adeywong** [comment]
I have disabled my firewall just in case, but that does not seem to be the issue.
Has anyone been able to successfully connect from their host to the OracleNoSql inside a container? There was recommendation was to run the container with host networking mode, but this doesn't work if the host is a MacOS. I have also modified the dockerfile to start kvlite with -host 0.0.0.0 and it didnt work either.

**Comment by adeywong** [comment]
Also want to note that container to container connection as per the example on the docker page works fine
```
 docker run --rm -ti --link kvlite:store oracle/nosql \
  java -jar lib/kvstore.jar ping -host store -port 5000
```

**Comment by olelbis** [comment]
> Also want to note that container to container connection as per the example on the docker page works fine
> 
> ```
>  docker run --rm -ti --link kvlite:store oracle/nosql \
>   java -jar lib/kvstore.jar ping -host store -port 5000
> ```

Exactly, i’also able to use cotainer to container connection succesfully.

But if i try from my linux or win machine, i got topology error.

If i install nosql locally instead using docker everithing work fine.

**Comment by NoSQLGuy** [comment]
The IP address for the docker container running the store is different. To get the container ip address, do the following:
Get the docker container ip address. Issue this command immediately after creating the container : docker inspect nosql-container | grep -i ipadd
 
You can then ping the store using the container IP address:
 
docker run --name nosql-container -d kvlite:latest
docker exec -it nosql-container bash
 
On the docker bash prompt, issue the following command:
java -jar lib/kvstore.jar ping -port 5000 -host <container_ip_address>

**Comment by NoSQLGuy** [comment]
Are you trying to accessing the NoSQL DB running in the container from a client java program?
If so, you can try the following :

add a param --net=host when running nosql-container
$ docker run --name nosql-container --net=host -p 5000:5000 -d kvlite:latest

Now instead of IPAddress, you can use the hostname in Java Client code to access kvlite DB that is running in the container in your java program as below :

KVStore store = KVStoreFactory.getStore(new KVStoreConfig("kvstore", "Hostname:5000"));

Give it a try and let me know?

**Comment by Djelibeybi** [comment]
> add a param --net=host when running nosql-container

This doesn't work with Docker for Mac or Windows, because the container actually runs in a nested VM. Can you provide all the ports necessary so that we can map them directly? I tried with 5001, 5000 and 5010-5020, but that didn't work either.

**Comment by mshelest4** [comment]
Hi,
I run into same problem. It would be great to know if found some solution.
Thanks.

**Comment by NoSQLGuy** [comment]
@mshelest4 let me check and get back

**Comment by falkenbt** [comment]
Would be great to have a way, otherwise NoSQL is not really practicably usable in our development process which starts the necessary containers automatically. Can this be escalated or can commercial support help out?

**Comment by NoSQLGuy** [comment]
@falkenbt  - can you please write me at anand dot chandak @oracle dot com (replace dot and spaces.

**Comment by NoSQLGuy** [comment]
Can you please start the container with -network=host

for e.g docker run --rm -d --network host --name kvlite oracle/nosql:19.5-ce

And when you are connecting to the KVHost from your java program give the hostname (make sure the entry is present in the /etc/hosts file)

For e.g
KVStoreConfig config = new KVStoreConfig("kvstore", "instance-20191024-0922-nosql-lab:5000");
        store = KVStoreFactory.getStore(config);

**Comment by mstepan** [comment]
On MacOS `-network=host` won't help you. So, for MacOS there is not workaround for now.

**Comment by dario-vega** [comment]
An explanation is provided in the last version
