### ISSUE TITLE
Push oracle container to docker hub

### ISSUE THREAD

**Issue by csuriano23** [oracle/docker-images#1595]
Hi, I' d like to know if pushing to docker hub of an oracle XE DB image generated with a customized revision of the 19.3.0 Dockerfile provided in this repository is compliant with the terms of use.

Thank you
Carlo

**Comment by Djelibeybi** [comment]
We are not lawyers, so we can't answer license compliance questions on GitHub. I can however point you at the Oracle XE license terms for the Linux RPM release: https://docs.oracle.com/en/database/oracle/oracle-database/18/xelic/licensing-information.html

You will need to do your own assessment of the license terms to determine if what you're proposing meets those terms.
