### ISSUE TITLE
Oracle Weblogic MultiHost setup scripts

### ISSUE THREAD

**Issue by koshyvarghese** [oracle/docker-images#1597]
Oracle Weblogic Multi host link which as per the document is available in (https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/1221-docker-compose/docker-compose.yml) 
is not available currently. Can you share the current link to setup multihost Weblogic Cluster setup.
@mriccell  can you share the link to the multihost Weblogic Cluster setup

**Comment by mriccell** [comment]
This is an old obsolete sample that I need to remove.  I would look at our Kubernetes support if you are interested in multi host deployments of containers/pods https://oracle.github.io/weblogic-kubernetes-operator/
