### ISSUE TITLE
Docker wls container 12213-weblogic-domain

### ISSUE THREAD

**Issue by kerberos5** [oracle/docker-images#1598]
Hi,
I followed the instructions from [here ](https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain) but the contain not work corretly.
my docker images create:
`docker@ubuntu:~$ docker images
REPOSITORY                           TAG                  IMAGE ID            CREATED             SIZE
12213-weblogic-domain-in-volume      latest               dca4584abe41        About an hour ago   961MB
oracle/weblogic                      12.2.1.3-developer   5967bd051ce6        24 hours ago        961MB
<none>                               <none>               3495a2b2c780        24 hours ago        1.45GB`

i run . ./run_admin_server.sh this create a container but into log i have:

`docker@ubuntu:~/kubernates/OracleWebLogic/samples/12213-domain$ docker logs AdminContainer 
Domain Home is:  /u01/oracle/user_projects/domains/myDomain
/u01/oracle/properties/domain_security.properties
/u01/oracle/properties/domain.properties
Java Options: -Doracle.jdbc.fanEnabled=false -Dweblogic.StdoutDebugEnabled=false
/u01/oracle/container-scripts/createWLSDomain.sh: line 85: /u01/oracle/user_projects/domains/myDomain/bin/setDomainEnv.sh: Permission denied
Starting the Admin Server
/u01/oracle/container-scripts/createWLSDomain.sh: line 91: /u01/oracle/user_projects/domains/myDomain/startWebLogic.sh: Permission denied`

my volume mapped is /data/wls and it create only  security folder:
`docker@ubuntu:/data/wls/myDomain/servers/myadmin$ ll
total 12
drwxr-x--- 3 docker docker 4096 Apr 30 14:50 ./
drwxr-x--- 3 docker docker 4096 Apr 30 14:50 ../
drwxr-x--- 2 docker docker 4096 Apr 30 14:50 security`

where should i correct the permissions?

thanks

**Comment by kerberos5** [comment]
if i edit my container: docker exec -it AdminContainer bash and try to run startWeblogic.sh i have:
`[oracle@AdminContainer myDomain]$ . ./bin/setDomainEnv.sh
[oracle@AdminContainer myDomain]$ . ./startWebLogic.sh 
bash: /u01/oracle/user_projects/domains/myDomain/bin/startWebLogic.sh: Permission denied`

help please.....

**Comment by mriccell** [comment]
Your host volume must have rwx permissions for owner and group so that the servers running in the containers can execute the scripts and write the logs and stores in the host volume.

**Comment by kerberos5** [comment]
> Your host volume must have rwx permissions for owner and group so that the servers running in the containers can execute the scripts and write the logs and stores in the host volume.

thanks for the reply ... 
my properties file:
`DOMAIN_NAME=base_domain
ADMIN_PORT=7001
ADMIN_NAME=myadmin
ADMIN_HOST=AdminContainer
MANAGED_SERVER_PORT=8001
MANAGED_SERVER_NAME_BASE=MS
CONFIGURED_MANAGED_SERVER_COUNT=2
PRODUCTION_MODE_ENABLED=true
CLUSTER_NAME=cluster1
CLUSTER_TYPE=DYNAMIC
DOMAIN_HOST_VOLUME=/data/wls`
the volume /data/wls i have set:
`UUID=2131ddcf-988e-4f26-a5d4-38b3006019bf /data           ext4    errors=remount-ro,auto,exec,rw,user 0       0`

when I start the container some directories and files are created automatically but I get that exception on the 2 scripts above
for example the logs folder is not created, I have to create it by hand ...

**Comment by kerberos5** [comment]
it works! the problem is in the external FS there is some error in the definition of the permissions.
if i use the docker user fs it works fine. i have change from /data/wls to /home/docker/data/wls
maybe I have to change how the volume is mounted

thanks!

**Comment by kerberos5** [comment]
Hi, 
I have found the solution to my problem!
i change my definition in fstab from:
`#UUID=2131ddcf-988e-4f26-a5d4-38b3006019bf /data           ext4    errors=remount-ro,auto,exec,rw,user 0       0`
To:
`UUID=2131ddcf-988e-4f26-a5d4-38b3006019bf  /data           ext4    defaults 0       2`
and run 
chown -R docker:docker /data/wls
chmod -R 775 /data/wls
now the container work fine... and create all folders:
`docker@ubuntu:/data/wls/base_domain/servers/myadmin$ ll
total 44
drwxr-x--- 7 docker docker  4096 May  5 10:28 ./
drwxr-x--- 3 docker docker  4096 May  5 10:28 ../
-rw-r----- 1 docker docker 12806 May  5 10:29 base_domain.log
drwxr-x--- 3 docker docker  4096 May  5 10:28 cache/
drwxr-x--- 5 docker docker  4096 May  5 10:28 data/
drwxr-x--- 3 docker docker  4096 May  5 10:28 logs/
drwxr-x--- 2 docker docker  4096 May  5 10:28 security/
drwxr-x--- 4 docker docker  4096 May  5 10:28 tmp/`

`docker@ubuntu:/data/wls/base_domain/servers/myadmin$ docker inspect --format '{{.NetworkSettings.IPAddress}}' AdminContainer
172.17.0.2`
