### ISSUE TITLE
Build of Oracle 19c docker image failing

### ISSUE THREAD

**Issue by HKnackstedt** [oracle/docker-images#1601]
When trying to build a Docker image with the Dockerfile for Oracle 19c on Windows I receive the following error:

![2020-05-04 15_10_33-Administrator_ Eingabeaufforderung - docker  build --force-rm=true --no-cache=tr](https://user-images.githubusercontent.com/62141060/80970135-fb062800-8e1a-11ea-925a-b15e6b609479.png)

I was unable to retrieve the logs because the build continued nevertheless. However, the resulting container image is broken.

I am using the following command to build:
`docker build --force-rm=true --no-cache=true --build-arg DB_EDITION=SE2 -t oracle/database:19.3.0-SE2 -f Dockerfile .`

**Comment by gvenzl** [comment]
Hi @HKnackstedt, the error you see in your build indicates another issue earlier on. Could you by chance log the output into a log file and post it?

It would also be great if you could get the log referred in the error: `/tmp/InstallAction2020-05-04...`
