### ISSUE TITLE
Access to  Console Not Working from Docker HUB Image download

### ISSUE THREAD

**Issue by chayzgithub** [oracle/docker-images#1602]
Hi,

I researched existing tickets but could it could not clarify my issue.

When I run the container out of the Docker Store Weblogic Image (store/oracle/weblogic:12.2.1.3-dev-200127), using the below command

**Command**:

docker run -d -p 7001:7001 -p 9002:9002  -v $PWD:/u01/oracle/properties -e ADMINISTRATION_PORT_ENABLED=true -e DOMAIN_NAME=docker_domain store/oracle/weblogic:12.2.1.3-dev-200127

**Note**:
1.  I have domain.proerties in the PWD and also given it 777. 
2. I have issued the docker run command as non-root.

I have tried accessing the console in the many ways (https and http)

1. 127.0.0.1:9002/console and using port 7001/2
2. 0.0.0.0:9002/console and 7001/2
3. 172.17.0.2:9002/console and 7001/2.  (IP address from docker inspect command)

**Docker Logs:**

<May 4, 2020 4:03:18,748 PM GMT> <Notice> <Server> <BEA-002613> <Channel "DefaultSecure[1]" is now listening on 127.0.0.1:7002 for protocols iiops, t3s, ldaps, https.>
<May 4, 2020 4:03:18,748 PM GMT> <Notice> <Server> <BEA-002613> <Channel "DefaultSecure" is now listening on 172.17.0.2:7002 for protocols iiops, t3s, ldaps, https.>
<May 4, 2020 4:03:18,748 PM GMT> <Notice> <Server> <BEA-002613> <Channel "Default" is now listening on 172.17.0.2:7001 for protocols iiop, t3, ldap, snmp, http.>
<May 4, 2020 4:03:18,749 PM GMT> <Notice> <Server> <BEA-002613> <Channel "Default[1]" is now listening on 127.0.0.1:7001 for protocols iiop, t3, ldap, snmp, http.>
<May 4, 2020 4:03:18,749 PM GMT> <Notice> <Server> <BEA-002613> <Channel "DefaultSecure[1]" is now listening on 127.0.0.1:7002 for protocols iiops, t3s, ldaps, https.>
<May 4, 2020 4:03:18,749 PM GMT> <Notice> <Server> <BEA-002613> <Channel "DefaultSecure" is now listening on 172.17.0.2:7002 for protocols iiops, t3s, ldaps, https.>
<May 4, 2020 4:03:18,749 PM GMT> <Notice> <Server> <BEA-002613> <Channel "Default" is now listening on 172.17.0.2:7001 for protocols iiop, t3, ldap, snmp, http.>
<May 4, 2020 4:03:18,749 PM GMT> <Notice> <Server> <BEA-002613> <Channel "Default[1]" is now listening on 127.0.0.1:7001 for protocols iiop, t3, ldap, snmp, http.>
<May 4, 2020 4:03:18,758 PM GMT> <Notice> <WebLogicServer> <BEA-000360> <The server started in RUNNING mode.>
<May 4, 2020 4:03:18,766 PM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to RUNNING.>

Finally,
Please correct me if my procedure above is incorrect OR if my expectation of the docker image is not accurate.

Thank you.

**Comment by mriccell** [comment]
The ADMINISTRATION_PORT_ENABLED=true  means you must use https and accept certificate.  The ip address corresponds to the Docker network where the container is running.  Do a docker inspect <container-id> and look at the host ip  where the 9002port. E.g.  "Ports": {
                "7001/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7001"
                    }
                ],
                "9002/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "9002"
                    }
                ]
In this case to access the console in my browser I would enter https://localhost:9002/console.

Monica

**Comment by chayzgithub** [comment]
Hi Monica,

It works now. I could not figure out an easy way to export and accept a certificate in **Chrome**.  If you had similar experience, please share.

I downloaded **Firefox** where it gives me a way to "Accept the risk and Continue" to let me proceed to load the page.

Thank you for the quick response. 

Bye
Chad

**Comment by mriccell** [comment]
Yes  for security reasons the administration port is enabled by default.
Thanks
Monica

**Comment by tharasavio** [comment]
i still face the same issue
