### ISSUE TITLE
Error building Oracle XE 18c docker image in Oracle Linux 7.8

### ISSUE THREAD

**Issue by jesusmorenodiaz** [oracle/docker-images#1604]
Please help, I have to resolve this...

Reported last year, abandoned using docker with 18c XE and now starting again...
https://github.com/oracle/docker-images/issues/1279#issue-443106483

Other guys having same error...
https://github.com/oracle/docker-images/issues/1279#issuecomment-525034353
https://github.com/fuzziebrain/docker-oracle-xe/issues/15

[SEVERE] The su command is not configured properly or the oracle user does not have the required privileges to install the Oracle database. If you are running in a Docker environment, ensure to set the environment variable ORACLE_DOCKER_INSTALL=true and try again.
**error: %pre(oracle-database-xe-18c-1.0-1.x86_64) scriptlet failed, exit status 1**
Error in PREIN scriptlet in rpm package oracle-database-xe-18c-1.0-1.x86_64
  Verifying  : file-5.11-36.el7.x86_64                                      1/2 
  Verifying  : oracle-database-xe-18c-1.0-1.x86_64                          2/2

[root@tecnica24 dockerfiles]# uname -a
Linux tecnica24.local 4.14.35-1902.5.2.2.el7uek.x86_64 #2 SMP Fri Sep 20 00:39:39 GMT 2019 x86_64 x86_64 x86_64 GNU/Linux

Running UEK5

Also applied...
"Before installing oracle, you need to comment session include system-auth line in /etc/pam.d/su file of your linux image"

**Comment by jesusmorenodiaz** [comment]
If you search in Google: "oracle linux su cannot open session permission denied"
you go to this book "Oracle GoldenGate With Microservices: Real-Time Scenarios with Oracle GoldenGate"...

https://books.google.es/books?id=OhbRDwAAQBAJ&pg=PT391&lpg=PT391&dq=oracle+linux+su+cannot+open+session+permission+denied&source=bl&ots=cismO8Fzu-&sig=ACfU3U3gLBf37mElWWunjrH8FxRctD6FUw&hl=es&sa=X&ved=2ahUKEwj0i_2SpabpAhWR5OAKHfzGB0E4ChDoATAEegQIChAB#v=onepage&q=oracle%20linux%20su%20cannot%20open%20session%20permission%20denied&f=false

Here you can read...
Comment in /etc/pam.d/su line "session include system-auth"

So in Dockerfile.xe I applied this RUN prior to all the rest and used FROM oraclelinux:7.8

RUN sed -E -i 	\
's/session[[:space:]]+include[[:space:]]+system-auth/#session\t\tinclude\t\tsyst
em-auth/g' /etc/pam.d/su

I would like if this is a "good" solution or just a patch that could affect system security.

**Comment by craighurley** [comment]
Based on the example provided by @jesusmorenodiaz, here's a shorter `sed` command that works: 

`sed -E 's/(session\s+include\s+system-auth)/#\1/g' -i /etc/pam.d/su`
