### ISSUE TITLE
Weblogic 12.2.1.3 running from Docker container but not able to open from browser

### ISSUE THREAD

**Issue by ranajoy-paul** [oracle/docker-images#1605]
My weblogic admin server is running from docker container as given below
I was following this : https://github.com/oracle/docker-images/tree/master/OracleWebLogic/dockerfiles/12.2.1.3.

I have also tried with patched image(by downloading p27117282_122130_Generic.zipand using this image :oracle/weblogic:12213-p27117282) but having same rsult and not able to open admin console

So moved back to use the image : oracle/weblogic:12.2.1.3-developer and used below

Command used(with ADMINISTRATION_PORT_ENABLED=false):
docker run -d --name wlsadmin --hostname wlsadmin -p 7001:7001 -p 9002:9002 -v C:\Users\RANAJOYPAUL\Ranajoy\APMM\GIT-Oracle-Weblogic\docker-images\OracleWebLogic\samples\12213-domain\properties:/u01/oracle/properties -e ADMINISTRATION_PORT_ENABLED=false -e ADMIN_PASSWORD=welcome1 -v C:\Users\RANAJOYPAUL\Ranajoy\APMM\GIT-Oracle-Weblogic\docker-images\OracleWebLogic\samples\12213-domain:/u01/oracle/user_projects oracle/weblogic:12.2.1.3-developer

docker inspect --format '{{.NetworkSettings.IPAddress}}' wlsadmin  
Output : 172.17.0.2

But not able to open ping or open the admin console using any of these URLs'(both http & https)
http://172.17.0.2/7001/console
http://172.17.0.2/9001/console
http://172.17.0.2/9002/console

`
PS C:\Users\RANAJOYPAUL\Ranajoy\APMM\GIT-Oracle-Weblogic\docker-images\OracleWebLogic\samples\12213-patch> docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                                            NAMES
952cdcc15652        oracle/weblogic:12.2.1.3-developer   "/u01/oracle/createA…"   25 minutes ago      Up 21 minutes       0.0.0.0:7001->7001/tcp, 0.0.0.0:9002->9002/tcp   wlsadmin
`

Please find docker log after admin server is started(as I couldnt open admin server so didnt try to start managed server yet)
===============================================

`Domain Home is: /u01/oracle/user_projects/domains/base_domain

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

domain_name : [base_domain]

admin_listen_port : [7001]

domain_path : [/u01/oracle/user_projects/domains/base_domain]

production_mode : [dev]

admin name : [AdminServer]

administration_port_enabled : [false]

administration_port : [9002]

Exiting WebLogic Scripting Tool.

.

JAVA Memory arguments: -Djava.security.egd=file:/dev/./urandom

CLASSPATH=/usr/java/jdk-8/lib/tools.jar:/u01/oracle/wlserver/server/lib/weblogic.jar:/u01/oracle/wlserver/../oracle_common/modules/thirdparty/ant-contrib-1.0b3.jar:/u01/oracle/wlserver/modules/features/oracle.wls.common.nodemanager.jar::/u01/oracle/wlserver/common/derby/lib/derbynet.jar:/u01/oracle/wlserver/common/derby/lib/derbyclient.jar:/u01/oracle/wlserver/common/derby/lib/derby.jar

PATH=/u01/oracle/user_projects/domains/base_domain/bin:/u01/oracle/wlserver/server/bin:/u01/oracle/wlserver/../oracle_common/modules/thirdparty/org.apache.ant/1.9.8.0.0/apache-ant-1.9.8/bin:/usr/java/jdk-8/jre/bin:/usr/java/jdk-8/bin:/usr/java/jdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/jdk-8/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin

***************************************************

* To start WebLogic Server, use a username and *

* password assigned to an admin-level user. For *

* server administration, use the WebLogic Server *

* console at http://hostname:port/console *

Starting WLS with line:

/usr/java/jdk-8/bin/java -server -Djava.security.egd=file:/dev/./urandom -cp /u01/oracle/wlserver/server/lib/weblogic-launcher.jar -Dlaunch.use.env.classpath=true -Dweblogic.Name=AdminServer -Djava.security.policy=/u01/oracle/wlserver/server/lib/weblogic.policy -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -javaagent:/u01/oracle/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/u01/oracle/wlserver/server -Dweblogic.home=/u01/oracle/wlserver/server weblogic.Server

<May 9, 2020 7:37:51 AM GMT> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.>

<May 9, 2020 7:37:51 AM GMT> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.>

<May 9, 2020 7:37:52 AM GMT> <Info> <WebLogicServer> <BEA-000377> <Starting WebLogic Server with Java HotSpot(TM) 64-Bit Server VM Version 25.251-b08 from Oracle Corporation.>

<May 9, 2020 7:37:52 AM GMT> <Info> <RCM> <BEA-2165021> <"ResourceManagement" is not enabled in this JVM. Enable "ResourceManagement" to use the WebLogic Server "Resource Consumption Management" feature. To enable "ResourceManagement", you must specify the following JVM options in the WebLogic Server instance in which the JVM runs: -XX:+UnlockCommercialFeatures -XX:+ResourceManagement.>

<May 9, 2020 7:37:52 AM GMT> <Info> <Management> <BEA-141107> <Version: WebLogic Server 12.2.1.3.0 Thu Aug 17 13:39:49 PDT 2017 1882952>

<May 9, 2020 7:37:54 AM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to STARTING.>

<May 9, 2020 7:37:54 AM GMT> <Info> <WorkManager> <BEA-002900> <Initializing self-tuning thread pool.>

<May 9, 2020 7:37:54 AM GMT> <Info> <WorkManager> <BEA-002942> <CMM memory level becomes 0. Setting standby thread pool size to 256.>

<May 9, 2020 7:37:55,791 AM GMT> <Notice> <Log Management> <BEA-170019> <The server log file weblogic.logging.FileStreamHandler instance=269631520

Current log file=/u01/oracle/user_projects/domains/base_domain/servers/AdminServer/logs/AdminServer.log

Rotation dir=/u01/oracle/user_projects/domains/base_domain/servers/AdminServer/logs

is opened. All server side log events will be written to this file.>

<May 9, 2020 7:37:56,288 AM GMT> <Notice> <Security> <BEA-090946> <Security pre-initializing using security realm: myrealm>

<May 9, 2020 7:37:57,449 AM GMT> <Notice> <Security> <BEA-090947> <Security post-initializing using security realm: myrealm>

<May 9, 2020 7:37:59,667 AM GMT> <Notice> <Security> <BEA-090082> <Security initialized using administrative security realm: myrealm>

<May 9, 2020 7:37:59,768 AM GMT> <Notice> <Security> <BEA-090083> <Storing boot identity in the file: /u01/oracle/user_projects/domains/base_domain/servers/AdminServer/security/boot.properties.>

<May 9, 2020 7:38:00,473 AM GMT> <Notice> <JMX> <BEA-149512> <JMX Connector Server started at service:jmx:iiop://172.17.0.2:7001/jndi/weblogic.management.mbeanservers.runtime.>

<May 9, 2020 7:38:01,101 AM GMT> <Notice> <JMX> <BEA-149512> <JMX Connector Server started at service:jmx:iiop://172.17.0.2:7001/jndi/weblogic.management.mbeanservers.domainruntime.>

<May 9, 2020 7:38:01,355 AM GMT> <Notice> <JMX> <BEA-149512> <JMX Connector Server started at service:jmx:iiop://172.17.0.2:7001/jndi/weblogic.management.mbeanservers.edit.>

<May 9, 2020 7:38:06,654 AM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to STANDBY.>

<May 9, 2020 7:38:06,679 AM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to STARTING.>

<May 9, 2020 7:38:06,781 AM GMT> <Notice> <Log Management> <BEA-170036> <The Logging monitoring service timer has started to check for logged message counts every 30 seconds.>

<May 9, 2020 7:38:07,361 AM GMT> <Notice> <Log Management> <BEA-170027> <The server has successfully established a connection with the Domain level Diagnostic Service.>

<May 9, 2020 7:38:07,963 AM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to ADMIN.>

<May 9, 2020 7:38:08,076 AM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to RESUMING.>

<May 9, 2020 7:38:08,211 AM GMT> <Notice> <Server> <BEA-002613> <Channel "Default" is now listening on 172.17.0.2:7001 for protocols iiop, t3, ldap, snmp, http.>

<May 9, 2020 7:38:08,214 AM GMT> <Notice> <Server> <BEA-002613> <Channel "Default[1]" is now listening on 127.0.0.1:7001 for protocols iiop, t3, ldap, snmp, http.>

<May 9, 2020 7:38:08,225 AM GMT> <Notice> <WebLogicServer> <BEA-000331> <Started the WebLogic Server Administration Server "AdminServer" for domain "base_domain" running in development mode.>

<May 9, 2020 7:38:08,227 AM GMT> <Notice> <Server> <BEA-002613> <Channel "Default" is now listening on 172.17.0.2:7001 for protocols iiop, t3, ldap, snmp, http.>

<May 9, 2020 7:38:08,238 AM GMT> <Notice> <Server> <BEA-002613> <Channel "Default[1]" is now listening on 127.0.0.1:7001 for protocols iiop, t3, ldap, snmp, http.>

<May 9, 2020 7:38:08,249 AM GMT> <Notice> <WebLogicServer> <BEA-000360> <The server started in RUNNING mode.>

<May 9, 2020 7:38:08,303 AM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to RUNNING.>`
=============================
Please find docker inspect screen as below
[DockerInspectScreen.docx](https://github.com/oracle/docker-images/files/4602991/DockerInspectScreen.docx)

=============================

 docker inspect wlsadmin
[
    {
        "Id": "952cdcc156529853e08186dafa4d62c8ee08c5a4247207df9b796f653a0c37a4",
        "Created": "2020-05-09T07:33:22.276120293Z",
        "Path": "/u01/oracle/createAndStartEmptyDomain.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 9783,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-05-09T07:37:22.730631164Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:77db98d950d17e35e884c4d5b5f947533b2c3c869e63a5a4c26354f9b09469a9",
        "ResolvConfPath": "/var/lib/docker/containers/952cdcc156529853e08186dafa4d62c8ee08c5a4247207df9b796f653a0c37a4/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/952cdcc156529853e08186dafa4d62c8ee08c5a4247207df9b796f653a0c37a4/hostname",
        "HostsPath": "/var/lib/docker/containers/952cdcc156529853e08186dafa4d62c8ee08c5a4247207df9b796f653a0c37a4/hosts",
        "LogPath": "/var/lib/docker/containers/952cdcc156529853e08186dafa4d62c8ee08c5a4247207df9b796f653a0c37a4/952cdcc156529853e08186dafa4d62c8ee08c5a4247207df9b796f653a0c37a4-json.log",
        "Name": "/wlsadmin",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/host_mnt/c/Users/RANAJOYPAUL/Ranajoy/APMM/GIT-Oracle-Weblogic/docker-images/OracleWebLogic/samples/12213-domain/properties:/u01/oracle/properties",
                "/host_mnt/c/Users/RANAJOYPAUL/Ranajoy/APMM/GIT-Oracle-Weblogic/docker-images/OracleWebLogic/samples/12213-domain:/u01/oracle/user_projects"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "7001/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7001"
                    }
                ],
                "9002/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "9002"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                19,
                139
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/99d0ca13e6e07d7fb4625307beb9d043a9fb7f863f0781ee1c7df2ea845b16cb-init/diff:/var/lib/docker/overlay2/1a6d1e98950c194c8990ae17ef0172e7d58778bb2406e9502dd422568ed45d7a/diff:/var/lib/docker/overlay2/46afc05558f42fd16638e9c706b1dd7c223ed3a7f24712d21dcbb5ec2f16f5da/diff:/var/lib/docker/overlay2/d1059dc3ef56bd780d44e6255241b46f40c89296327239491c803e6d8e2da825/diff:/var/lib/docker/overlay2/a5ccf0fb03ba7ef6b520f7807486f0f1359fd0b27db96205df64164079464990/diff:/var/lib/docker/overlay2/25ec8b5c96e2841b327ced77582cac03ab66e2181711e216a5f663cf33a86f58/diff:/var/lib/docker/overlay2/1f371e54b76ce1b0f28f51aeb6092a00848dce32a14c53c5ed0d70cf445e4921/diff:/var/lib/docker/overlay2/6f8829cf732e62aa0aee64c50c0544a6ded484700df980bdabf62d08195c240b/diff",
                "MergedDir": "/var/lib/docker/overlay2/99d0ca13e6e07d7fb4625307beb9d043a9fb7f863f0781ee1c7df2ea845b16cb/merged",
                "UpperDir": "/var/lib/docker/overlay2/99d0ca13e6e07d7fb4625307beb9d043a9fb7f863f0781ee1c7df2ea845b16cb/diff",
                "WorkDir": "/var/lib/docker/overlay2/99d0ca13e6e07d7fb4625307beb9d043a9fb7f863f0781ee1c7df2ea845b16cb/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/RANAJOYPAUL/Ranajoy/APMM/GIT-Oracle-Weblogic/docker-images/OracleWebLogic/samples/12213-domain",
                "Destination": "/u01/oracle/user_projects",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/RANAJOYPAUL/Ranajoy/APMM/GIT-Oracle-Weblogic/docker-images/OracleWebLogic/samples/12213-domain/properties",
                "Destination": "/u01/oracle/properties",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "wlsadmin",
            "Domainname": "",
            "User": "oracle",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "7001/tcp": {},
                "9002/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ADMINISTRATION_PORT_ENABLED=false",
                "ADMIN_PASSWORD=welcome1",
                "PATH=/usr/java/jdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/jdk-8/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin",
                "LANG=en_US.UTF-8",
                "JAVA_VERSION=1.8.0_251",
                "JAVA_HOME=/usr/java/jdk-8",
                "ORACLE_HOME=/u01/oracle",
                "USER_MEM_ARGS=-Djava.security.egd=file:/dev/./urandom",
                "SCRIPT_FILE=/u01/oracle/createAndStartEmptyDomain.sh",
                "DOMAIN_NAME=base_domain",
                "ADMIN_LISTEN_PORT=7001",
                "ADMIN_NAME=AdminServer",
                "DEBUG_FLAG=true",
                "PRODUCTION_MODE=dev",
                "ADMINISTRATION_PORT=9002"
            ],
            "Cmd": [
                "/u01/oracle/createAndStartEmptyDomain.sh"
            ],
            "Image": "oracle/weblogic:12.2.1.3-developer",
            "Volumes": null,
            "WorkingDir": "/u01/oracle",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "fd56a7a2d4476c3cbcec506e47b1c91491c615350b1d63dc867a606e27cae829",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "7001/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7001"
                    }
                ],
                "9002/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "9002"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/fd56a7a2d447",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "16b019000f1f86638d8ac4b142fb56bc920b6719fd1ae362a6f85dd3fc20ab19",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "2a538b1c91149c498ed043aed83551b83fc0397ab4397b438d8f1599fbaf599d",
                    "EndpointID": "16b019000f1f86638d8ac4b142fb56bc920b6719fd1ae362a6f85dd3fc20ab19",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

===========================

Please help @mriccell & Team. Thanks in advance

**Comment by mriccell** [comment]
You should be able to reach the console using port 7001 since ADMINISTRATION_PORT_ENABLED=false
from inspect "Ports": {
"7001/tcp": [
{
"HostIp": "0.0.0.0",
"HostPort": "7001"
}
],
"9002/tcp": [
{
"HostIp": "0.0.0.0",
"HostPort": "9002"
}
]
you should be able to reach the admin console http://localhost:7001.

**Comment by ranajoy-paul** [comment]
Thanks Monica!! I managed to up my weblogic admin console and access it. Actually I also had HyperV installed in my machine and fixed the network and then able to access the weblogic admin. Appreciated your quick response even at weekend and will contact you in future. 
Hope you and family doing well in lock down and  in this world crisis time and in good health.
Thanks again :-)
