### ISSUE TITLE
Cannot connect to the Oracle Database 12.2.0.1 after restarting the server

### ISSUE THREAD

**Issue by alisheykhi** [oracle/docker-images#1607]
Hi,

After an unexpected restart in my server, I can't connect to the database. 
As I checked, the docker was disabled, so I used this command:
`systemctl start docker`
and then 
`docker start ODIDatabase`
following is `docker ps -a` output:

> 089fe21650d5        oracle/database:12.2.0.1-ee   "/bin/sh -c 'exec $O…"   4 weeks ago         Up 2 hours (healthy)       0.0.0.0:1521->1521/tcp, 0.0.0.0:5500->5500/tcp   ODIDatabase

and `docker logs ODIDatabase | tail -50` is:

> Listener Log File         /opt/oracle/diag/tnslsnr/089fe21650d5/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
SQL*Plus: Release 12.2.0.1.0 Production on Sat May 9 17:17:03 2020
Copyright (c) 1982, 2016, Oracle.  All rights reserved.
Connected to an idle instance.
SQL> ORACLE instance started.
Total System Global Area 1610612736 bytes
Fixed Size                  8793304 bytes
Variable Size             520094504 bytes
Database Buffers         1073741824 bytes
Redo Buffers                7983104 bytes
Database mounted.
Database opened.
SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
The Oracle base remains unchanged with value /opt/oracle
#########################
DATABASE IS READY TO USE!
#########################
The following output is now a tail of the alert.log:
ODIPDB(3):Database Characterset for ODIPDB is AL32UTF8
2020-05-09T17:17:13.122406+00:00
ODIPDB(3):Opatch validation is skipped for PDB ODIPDB (con_id=0)
2020-05-09T17:17:13.502077+00:00
ODIPDB(3):Opening pdb with no Resource Manager plan active
Pluggable database ODIPDB opened read write
Starting background process CJQ0
2020-05-09T17:17:13.688170+00:00
CJQ0 started with pid=40, OS id=285 
Completed: ALTER DATABASE OPEN
2020-05-09T17:17:14.561609+00:00
Shared IO Pool defaulting to 64MB. Trying to get it from Buffer Cache for process 84.
===========================================================
Dumping current patch information
===========================================================
No patches have been applied
===========================================================
2020-05-09T17:17:16.887695+00:00
Setting Resource Manager plan SCHEDULER[0x4AC8]:DEFAULT_MAINTENANCE_PLAN via scheduler window
Setting Resource Manager CDB plan DEFAULT_MAINTENANCE_PLAN via parameter
ODIPDB(3):Setting Resource Manager plan SCHEDULER[0x4AC2]:DEFAULT_MAINTENANCE_PLAN via scheduler window
ODIPDB(3):Setting Resource Manager plan DEFAULT_MAINTENANCE_PLAN via parameter

**Comment by alisheykhi** [comment]
`lsnrctl status` output is:

> LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 10-MAY-2020 22:10:02
Copyright (c) 1991, 2016, Oracle.  All rights reserved.
Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                10-MAY-2020 22:03:56
Uptime                    0 days 0 hr. 6 min. 6 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/089fe21650d5/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=089fe21650d5)(PORT=5500))(Security=(my_wallet_directory=/opt/oracle/admin/ODIDB/xdb_wallet))(Presentation=HTTP)(Session=RAW))
Services Summary...
Service "ODIDB" has 1 instance(s).
  Instance "ODIDB", status READY, has 1 handler(s) for this service...
Service "ODIDBXDB" has 1 instance(s).
  Instance "ODIDB", status READY, has 1 handler(s) for this service...
Service "a2a58949ae4a0961e053020011acc13c" has 1 instance(s).
  Instance "ODIDB", status READY, has 1 handler(s) for this service...
Service "odipdb" has 1 instance(s).
  Instance "ODIDB", status READY, has 1 handler(s) for this service...
The command completed successfully 

tnsnames.ora

> ODIDB=localhost:1521/ODIPDB
ODIPDB= 
  (DESCRIPTION = 
    (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = ODIPDB)
    )
  )

`echo $ORACLE_SID`:
>odidb

`echo $ORACLE_PDB`:
>odipdb

**Comment by gvenzl** [comment]
Could you tell us how you are trying to connect, what symptoms you encounter, what OS you are running this on, etc?

**Comment by alisheykhi** [comment]
before this accident, I could connect to the database using SQL Developer on my local machine.
docker host is CentOS 7. 
when I run `nc docker.host 1521`  on another machine in this network I face this error:

> Ncat: No route to host.

**Comment by alisheykhi** [comment]
I used the following db.env.list for first time running DB container:
>ORACLE_SID=odidb
ORACLE_PDB=odipdb
ORACLE_PWD=Welcome1

but after restarting container, values of SID and PDB are:
>ORACLE_SID=ODIDB
ORACLE_PDB=ODIPDB

I think you changed this in runOracle.sh file for issue 984?

**Comment by gvenzl** [comment]
Yeah, the SID has to be uppercase.
Are you connecting via the service or the ORACLE_SID in SQL Developer?

None of this would explain a `No route to host` error though.
