### ISSUE TITLE
Error occured during installation of Oracle Database 

### ISSUE THREAD

**Issue by vafaronaghi** [oracle/docker-images#161]
Hi ,

this error  occured as i tried to install oracle DB 12.1.0.2 (enterprise)
--
Checking Temp space: must be greater than 500 MB.   Actual 6654 MB    Passed
Checking swap space: must be greater than 150 MB.   Actual 7720 MB    Passed
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2016-09-09_09-46-55PM. Please wait ...[FATAL] [INS-32021] Insufficient disk space on this volume for the selected Oracle home.
   CAUSE: **The selected Oracle home was on a volume without enough disk space.**
   ACTION: Choose a location for Oracle home that has enough space (minimum of 6,553MB) or free up space on the existing volume.

A log of this session is currently saved as: /tmp/OraInstall2016-09-09_09-46-55PM/installActions2016-09-09_09-46-55PM.log. Oracle recommends that if you want to keep this log, you should move it from the temporary location.
Removing intermediate container aa791192b625

The command '/bin/sh -c unzip $INSTALL_FILE_1 &&     rm $INSTALL_FILE_1 &&        unzip $INSTALL_FILE_2 &&     rm $INSTALL_FILE_2 &&        $INSTALL_DIR/database/runInstaller -silent -force -waitforcompletion -responsefile $INSTALL_DIR/$INSTALL_RSP -ignoresysprereqs -ignoreprereq &&     rm -rf $INSTALL_DIR/database' returned a non-zero code: 254

**There was an error building the image.**
--

I have enough space on hard disk.

Any Idea how to fix ?

Thanks

**Comment by ramonPires** [comment]
I had the same problem trying to build this image for oracle xe,in my case with Docker for mac, and I found a solution to change the swap space https://forums.docker.com/t/docker-for-mac-configure-swap-space/20656/2?u=ramonpires .

**Comment by brunoborges** [comment]
@gvenzl, mind to wrap up the Swap space issue and document it in the [README.md](https://github.com/gvenzl/docker-images/blob/master/OracleDatabase/README.md), please?

**Comment by vafaronaghi** [comment]
ok, i will verify it and document in README.md definitely

**Comment by jlafourc** [comment]
Hi,

I am on Debian with Docker 1.12.1 . I am running in the same issue. I increased my swap space (now 14G). I also changed the Base Device Size (now 32GB). I tried Oracle 12c SE && EE. 

I am running out of ideas. 

Thanks

Julien

**Comment by jlafourc** [comment]
In fact I reply to myself. I cleaned all my containers and images (and restarted my computer just in case ... ) as mentined here : 
https://github.com/wscherphof/oracle-12c/issues/5#issuecomment-105737307

and it worked !
