### ISSUE TITLE
Unable to login in https://container-registry.oracle.com/

### ISSUE THREAD

**Issue by marcoros77** [oracle/docker-images#1610]
Hi,

I'm trying to login to https://container-registry.oracle.com/ to install the weblogic docker image on my windows 10 PC, but when I execute the docker login command and after providing the correct username and password I'm prompted with the error:

`Error response from daemon: Get https://container-registry-phx.oracle.com/v2/: unauthorized: authentication required`

I've verified my user is in the local windows docker-users group.

I've then verified that I can login via browser on the webpage https://container-registry.oracle.com/  and that I accepted the Oracle Standard Terms and Restrictions on the weblogic related web page so there should be no issue there.

I've also tried to login from a different PC, a linux machine with OMV5, but after providing the right username and password I'm prompted with a different error: 

`Error reponse from daemon: Get https://container-registry-phx.oracle.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) `

Do you have any advice?

Thank you

**Comment by Djelibeybi** [comment]
Remove the `-phx` from the URL.

**Comment by marcoros77** [comment]
Hi Djelibeybi , thank you, but the docker login command I run is without the -phx:

`docker login container-registry.oracle.com`

I think I'm redirected to it, but don't know why.

Thank you.

**Comment by Djelibeybi** [comment]
I can't reproduce this locally unfortunately. It's logging me just fine. Strictly speaking we don't really support the Oracle Container Registry here on GitHub, but if you have an Oracle Linux support subscription, you can open an SR with Oracle Support.

However, you could just build your own WebLogic image using the files provided on this very repo. :)

**Comment by marcoros77** [comment]
Thank you, will do!

**Comment by marcoros77** [comment]
Hi ,

I'm sorry but also to build my weblogic image with the code in this repo requires the docker login in order to download the JRE... I will try to modify it and see if I can provide my own JRE to build it.

Any hints on where to look for it?

Thank you.

**Comment by marcoros77** [comment]
Hi Djelibeybi,

I've tried to build my own using the code on this repo, but it still requires the docker login to work in order to download the oracle server/serverjre:8 image:

`pull access denied for oracle/serverjre, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

And I don't think I can get around that... or can I? Can you think about a workaround?

Thank you again for your help.

**Comment by Djelibeybi** [comment]
You can build the JRE as well using Dockerfiles in this repo too. :) The only thing you need to be able to pull is the official Oracle Linux image from Docker Hub (which doesn't require a login).

**Comment by mriccell** [comment]
If you go to https://github.com/oracle/docker-images/tree/master/OracleJava/java-8 you can build a serverjre:8 image yourself.  There is also a

**Comment by marcoros77** [comment]
Thank you very much guys, I've tried to build the serverjre image from the link provided by mriccell, but it seems that when it tries to install tar and gzip it can't get to the yum oracle repository:

`https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: yum.oracle.com; Name or service not known"`

I can access though yum.oracle.com and the link specified with no problem with my browser, and I've checked that docker has the correct proxy configured, I can pull images from the docker offical repo.

Do you have any other suggestions?

Thank you again for your help.

**Comment by Djelibeybi** [comment]
You're having networking issues with Docker that are unrelated to this repo. I suggest trying to get help from a Docker specific repo or forum and once you get that working, try these builds again.

**Comment by marcoros77** [comment]
Thank you, will do, thanks again for the help
