### ISSUE TITLE
An error occured while starting 12.1.0.2-ee image

### ISSUE THREAD

**Issue by hichem-belhocine** [oracle/docker-images#1612]
Hello.
I was able to create an image for 12.1.0.2-ee.

I was also able to deploy it on Google Kuberentes engine. (all things as expected)

Now, i'm trying to deploy it on Opnshift Container Platform on-prem, I got this error:

```
The listener supports no services
The command completed successfully
cat: /opt/oracle/cfgtoollogs/dbca/ORCLDB/ORCLDB.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ORCLDB.log: No such file or directory
mv: cannot stat '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/spfileORCLDB.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/orapwORCLDB': No such file or directory
mv: cannot stat '/opt/oracle/product/12.1.0.2/dbhome_1/network/admin/tnsnames.ora': No such file or directory
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/checkDBStatus.sh: line 26: sqlplus: command not found
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining
```

I have already assign a Security Context Constraints **anyuid** to the service account default to be able to run as any user (oc adm policy add-scc-to-user anyuid -z default)

**Comment by gvenzl** [comment]
Can you please share the entire output as well as the `docker run` command and parameters you have used?

**Comment by hichem-belhocine** [comment]
Hallo Grald,

thank you a lot for the answer.

I'm deploying the oracle container using a deployment file. I have already run it using **docker run ....** and it works fine.

I deployed the same yaml file in Google Kubernetes Engine and it works fine.

The logs and the deployment yaml files are below.

As i said before, i have already assign a Security Context Constraints anyuid to the service account **default** to be able to **run as any user** (oc adm policy add-scc-to-user anyuid -z default)

[logs.txt](https://github.com/oracle/docker-images/files/4626913/logs.txt)
[deployment.txt](https://github.com/oracle/docker-images/files/4626920/deployment.txt)

**Comment by gvenzl** [comment]
Thanks for the additional info, @hichem-belhocine.

This looks very much like a configuration issue within Open Shift. I suppose we already knew that much, given that it works fine on GKE and via `docker run`. :)

It looks like the container isn't allowed/able to start up`dbca`. The failure below:
```
LSNRCTL for Linux: Version 12.1.0.2.0 - Production on 14-MAY-2020 08:15:43

Copyright (c) 1991, 2014, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.1.0.2/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.1.0.2.0 - Production
System parameter file is /opt/oracle/product/12.1.0.2/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/product/12.1.0.2/dbhome_1/network/log/listener.log
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.1.0.2.0 - Production
Start Date                14-MAY-2020 08:15:43
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.1.0.2/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/product/12.1.0.2/dbhome_1/network/log/listener.log
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
cat: /opt/oracle/cfgtoollogs/dbca/ORCLDB/ORCLDB.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ORCLDB.log: No such file or directory
```
is from this piece of code:
```
lsnrctl start &&
dbca -silent -responseFile $ORACLE_BASE/dbca.rsp ||
 cat /opt/oracle/cfgtoollogs/dbca/$ORACLE_SID/$ORACLE_SID.log ||
 cat /opt/oracle/cfgtoollogs/dbca/$ORACLE_SID.log
```

`lsnrctl start` works successfully, but `dbca -silient ...` fails which causes the two outputs from `cat` above.

Now the question is, why is `dbca` not begin run on Open Shift? :)

**Comment by hichem-belhocine** [comment]
I have tested this example: https://medium.com/@pittar/running-oracle-12c-on-openshift-container-platform-ca471a9f7057

It works fine, but i need to run the 12.1.0.2-ee version.

**Comment by grischdian** [comment]
I'm trying to debug this problem for @hichem-belhocine on his test-cluster. How can I get more informations regarding dbca? I have no clue about oracle but am familiar with containers ;)

I just found out, that dbca is exiting with exitcode 1 instead of 0 but the command throws no error message.

**Comment by hichem-belhocine** [comment]
Hi @gvenzl,

I would tell you that i have created the 12.2.01 image and it works fine.

Thank you.

Best regards.
