### ISSUE TITLE
An error occurred while starting 19.3.0-ee 

### ISSUE THREAD

**Issue by ecost4** [oracle/docker-images#1614]
Hi,

I've got this error when trying execute docker run command.

**% docker run --name oracle19c -p 1521:1521 oracle/database:19.3.0-ee**

```
ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: gQtWabHql7w=1

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 14-MAY-2020 13:25:08

Copyright (c) 1991, 2019, Oracle.  All rights reserved.

Starting /opt/oracle/product/19c/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 19.0.0.0.0 - Production
System parameter file is /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/393f0f63e7b4/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Start Date                14-MAY-2020 13:25:08
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/393f0f63e7b4/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
/opt/oracle/product/19c/dbhome_1/bin/dbca: line 135: /u01/app/oracle/product/19.0.0/dbhome_1/bin/platform_common: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB.log: No such file or directory
mv: cannot stat '/opt/oracle/product/19c/dbhome_1/dbs/spfileORCLCDB.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/19c/dbhome_1/dbs/orapwORCLCDB': No such file or directory
mv: cannot stat '/opt/oracle/product/19c/dbhome_1/network/admin/tnsnames.ora': No such file or directory
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/checkDBStatus.sh: line 26: sqlplus: command not found
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining
```

**Comment by gvenzl** [comment]
Hi @ecost4,

Could you please share the docker image build log?
It looks like some steps have failed during that so that the `$ORACLE_HOME` hasn't been adjusted inside `dbca`

**Comment by gvenzl** [comment]
We will most likely also need the install logs from the `runInstaller` command as well, as the `OH` variable in `dbca` is adjusted during the `runInstaller` invocation.

**Comment by ecost4** [comment]
LOG: [buid.log](https://github.com/oracle/docker-images/files/4633783/buid.log)

**Comment by gvenzl** [comment]
Thanks @ecost4, you did receive an error during the binaries installation:

```
You can find the log of this install session at:
 /tmp/InstallActions2020-05-14_10-47-30AM/installActions2020-05-14_10-47-30AM.log
[FATAL] Error in invoking target 'irman ioracle idrdactl idrdalsnr idrdaproc' of makefile '/opt/oracle/product/19c/dbhome_1/rdbms/lib/ins_rdbms.mk'. See '/tmp/InstallActions2020-05-14_10-47-30AM/installActions2020-05-14_10-47-30AM.log' for details.
Moved the install session logs to:
 /opt/oracle/oraInventory/logs/InstallActions2020-05-14_10-47-30AM
```

Can you please retrieve the install session log file and upload it as well?

**Comment by ecost4** [comment]
Sorry @gvenzl, I removed the container and image. I'm using a oracle docker images from docker hub with oracle database 12c version. 

I think you can reproduce this issue easily. 

I hope that you find the issue and fix, otherwise will be impossible use this.

Thanks

**Comment by datocrats-org** [comment]
I am having related problems, something to do with how the files within `/opt/oracle/product/19c/dbhome_1/dbs/` are being moved around during the **symLinkFiles** function. 
 That function is being called in too many contexts in my opinion.  It would be better to refactor how the installation checks for pre-existing dbf files given that we may both be symlinking within linux and reusing volumes between docker builds.

**Comment by rhuffman** [comment]
I'm having the exact same problem with the 18c image. I'm very willing to provide more information if you can help me with this.

**Comment by beyst77** [comment]
I have the same problem with the 19c se image. During the installation the following error is thrown:

`make: *** [/opt/oracle/product/19c/dbhome_1/rdbms/lib/oracle] Error 137`

[installerPatchActions_2020-06-05_05-57-24AM.log](https://github.com/oracle/docker-images/files/4734274/installerPatchActions_2020-06-05_05-57-24AM.log)

**Comment by gvenzl** [comment]
@rhuffman, @beyst77, do you still face this issue and can you still reproduce it?
If so, can you provide the log files?

@beyst77, the log file you have attached, doesn't contain anything regarding the error. It's the `installerPatchActions*` while I believe the errors will be logged in the `installerActions*` file.
