### ISSUE TITLE
Oracle weblogic Kubernetes Operator failed to deploy in Pod and returns with openapi.ApiException: javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by ranajoy-paul** [oracle/docker-images#1617]
Was trying Oracle weblogic Kubernetes Operator for setting up Weblogic admin & managed server to run from Cloud following : https://oracle.github.io/weblogic-kubernetes-operator/quickstart/  in IBM cloud using Docker Desktop  win windows 10 with kubernetes 

The "traefik"application started and running in Remote IBM cloud using below command:
`helm install traefik-operator stable/traefik --namespace traefik --values kubernetes/samples/charts/traefik/values.yaml --set "kubernetes.namespaces={traefik}" --wait`

Followed the comands from ---https://oracle.github.io/weblogic-kubernetes-operator/quickstart/install/
But the weblogic-operator after deployment failed on IBM Cloud(CrashBack) and Pods are in error.

`helm install sample-weblogic-operator kubernetes/charts/weblogic-operator --namespace sample-weblogic-operator-ns --set image=oracle/weblogic-kubernetes-operator:2.5.0 --set serviceAccount=sample-weblogic-operator-sa --set "domainNamespaces={}" --wait`

The Major error is : 
**{0}","exception":"\nio.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request\n\tat** 

Is it related to my local laptop's Java version or I am missing any configuration? But I have tried with both JDK 9 & 11 with same result.
Please help. Thanks in Advance.

Start LOG------
`Launching Oracle WebLogic Server Kubernetes Operator...
Importing keystore /operator/internal-identity/temp/weblogic-operator.jks to /operator/internal-identity/temp/weblogic-operator.p12...
Entry for alias weblogic-operator-alias successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled
Warning:
The -srcstorepass option is specified multiple times. All except the last one will be ignored.
MAC verified OK
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4720    0  2777  100  1943  12955   9064 --:--:-- --:--:-- --:--:-- 13037
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5811    0  3281  100  2530  13838  10671 --:--:-- --:--:-- --:--:-- 13902
OpenJDK 64-Bit Server VM warning: Option MaxRAMFraction was deprecated in version 10.0 and will likely be removed in a future release.
VM settings:
    Max. Heap Size (Estimated): 3.73G
    Using VM: OpenJDK 64-Bit Server VM
{"timestamp":"05-15-2020T14:05:23.463+0000","thread":1,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.TuningParametersImpl","method":"update","timeInMillis":1589551523463,"message":"Reloading tuning parameters from Operator's config map","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:23.779+0000","thread":1,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.Main","method":"main","timeInMillis":1589551523779,"message":"Oracle WebLogic Server Kubernetes Operator, version: 2.5.0, implementation: master.b9d4b93, build time: 2020-02-26T11:17:50-0500","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:23.847+0000","thread":11,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.Main","method":"begin","timeInMillis":1589551523847,"message":"Operator namespace is: sample-weblogic-operator-ns","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:23.873+0000","thread":11,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.Main","method":"begin","timeInMillis":1589551523873,"message":"Operator target namespaces are: sample-weblogic-operator-ns","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:23.878+0000","thread":11,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.Main","method":"begin","timeInMillis":1589551523878,"message":"Operator service account is: sample-weblogic-operator-sa","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:23.885+0000","thread":11,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.helpers.HealthCheckHelper","method":"performK8sVersionCheck","timeInMillis":1589551523885,"message":"Verifying Kubernetes minimum version","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:24.407+0000","thread":11,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.helpers.ClientPool","method":"getApiClient","timeInMillis":1589551524407,"message":"The Kuberenetes Master URL is set to https://172.21.0.1:443","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:24.646+0000","thread":11,"fiber":"","domainUID":"","level":"WARNING","class":"oracle.kubernetes.operator.helpers.HealthCheckHelper","method":"performK8sVersionCheck","timeInMillis":1589551524646,"message":"Failure reading Kubernetes version.  Exception thrown: {0}","exception":"\nio.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request\n\tat io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:898)\n\tat io.kubernetes.client.openapi.apis.VersionApi.getCodeWithHttpInfo(VersionApi.java:139)\n\tat io.kubernetes.client.openapi.apis.VersionApi.getCode(VersionApi.java:120)\n\tat oracle.kubernetes.operator.helpers.CallBuilder.lambda$readVersionCode$47(CallBuilder.java:4`
--------End LOG

Is it related to my local laptop's Java version or I am missing any configuration? But I have tried with both JDK 9 & 11 with same result.
Please help. Thanks in Advance.

**Comment by mriccell** [comment]
This is the wrong repository to open this issue please open this issue in https://oracle.github.io/weblogic-kubernetes-operator.
Thanks
Monica

**Comment by ranajoy-paul** [comment]
Sure Monica @mriccell , Thanks!!
