### ISSUE TITLE
Weblogic 12.2.1.4 -- how do i run WLST commands?

### ISSUE THREAD

**Issue by vrmerlin** [oracle/docker-images#1619]
I'd like to create a container and automatically configure it with a WAR file and JDBC connections. I'm unclear on how to do that though, and haven't been able to find any examples. It seems to me I need to run some WLST commands after the container is up. Is that the right approach?

I'm bringing up the container-registry.oracle.com/middleware/weblogic:12.2.1.4 image, and given a domain.properties file with the admin username/password, I'm able to bring up a WebLogic container. With a browser I can get to the container's admin console by entering:

> https://myhostname:9002/console

So, I know that port works for the admin console.

I'm also able to go into WSDL by exec'ing a bash into the container, and running the command:

> oracle_common/common/bin/wlst.sh

In that shell, i tried to connect to the host with:

> connect('admin', foobar, 't3://localhost:9002')

But I get an error, "Error getting the initial context. There is no server running at t3://localhost:9002 : Failed to initialize JNDI context"

I then tried:

> connect('admin', 'foobar', 't3://localhost:7001')

But then I get the error, "User 'principals=[admin, Administrators]' has administration role. All tasks by administrators must go through an Administration Port"

Any ideas on how I connect with WLST to the WebLogic server? Is that even the right approach?

**Comment by mriccell** [comment]
@vrmerlin we have a sample which shows how to create a data source with wlst by extending the image https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain-with-resources.
9002 is the Admin channel and you need to connect using SSL.
Monica

**Comment by vrmerlin** [comment]
Fantastic!! What about deploying a WAR file? Is there an example of that?

Thanks!
John

________________________________

**Comment by mriccell** [comment]
@vrmerlin I want to stir towards using 2 open source tools that make it very easy to migrate your on premise domain configuration and deployment and build an image with the domain.  The WebLogic Deploy Tooling (WDT) https://github.com/oracle/weblogic-deploy-tooling and the WebLogic Image Tool (WIT) https://github.com/oracle/weblogic-image-tool.  Please look at the 3 part demo videos of a CI/CD pipeline using these tools, part1 introspects the on premise domain https://www.youtube.com/watch?v=zI-Y5enyVvQ and part2 shows how to build the image https://www.youtube.com/watch?v=Nx0mS2t8JS8.  The WebLogic team has also developed a WebLogic Kubernetes Operator to manage the lifecycle of these container in Kubernetes.  
Please email me if you have questions.
Monica

**Comment by vrmerlin** [comment]
Hi Monica -- those tools look interesting, and i'll definitely look into them further but they aren't really what I'm trying to accomplish. We aren't deploying to kubernetes in this phase, but we will as some point in the (distant) future. Now, I'd like to have a docker image process that could be applied to multiple environments, including local development systems. 

I feel like i was SO close. I edited my first response, so maybe you didn't see my edited response in github which was a much more specific problem. I was imitating as closely as I could your sample to deploy an application, but it's not working. Is there some element I'm missing?

John

**Comment by vrmerlin** [comment]
i should add that my goal is not to imitate the production system *exactly*. It's a very simple setup... three jdbc connections and a WAR file. i just want to generate a weblogic instance that runs it. There won't be any complex clustering configuration needed.  I half a dozen other applications that are of similar design, so I'm trying to come up with a pattern I can duplicate multiple times. Once I have the pattern, I can then enhance it, like having build variations that connect to development or QA databases.

**Comment by vrmerlin** [comment]
I was able to work through the problems by deviating less from your sample (go figure...). Now i have a cluster, a RUNNING server, and an "Active" deployment. Unfortunately, the site doesn't come up though, just gives me a blank page. Progress, though.

**Comment by vrmerlin** [comment]
I do notice that the war file is still coming up as type "unknown", whereas on the production system it is coming up as type "Web Application".  Is that a problem or not?

**Comment by vrmerlin** [comment]
Manually reinstalling and starting the WAR file caused it to have a type of "Web Application," but still no page content. I noticed on start and on the war restart, i got this error in the container stdout:

> org.igfay.jfig.JFigException: Resource not found in classpath: ecd073a792c5.config.xml

**Comment by vrmerlin** [comment]
Good news, i got it all working. :-)

**Comment by hshimalaya** [comment]
@vrmerlin 

I am facing same issue. I used WLST scripts to deploy my WARs. The WARs got deployed but with type "unknown"

Would you be kind enough to let me know how you resolved this ?
