### ISSUE TITLE
lstat linuxamd64_12102_database_1of2.zip: no such file or directory

### ISSUE THREAD

**Issue by eliuha** [oracle/docker-images#162]
failing to install the linuxamd64_12102_database_1of2.zip

Step 5 : COPY $INSTALL_FILE_1 $INSTALL_FILE_2 $INSTALL_RSP $PERL_INSTALL_FILE $INSTALL_DIR/
lstat linuxamd64_12102_database_1of2.zip: no such file or directory
There was an error building the image.
master@docker:~/OracleDatabase/dockerfiles$

**Comment by brunoborges** [comment]
Have you downloaded the binary from oracle.com ?

**Comment by gvenzl** [comment]
You need to download the install zip files and put them into the right directory. See the README.me for more information.

**Comment by eliuha** [comment]
can you add the link please ?

**Comment by gvenzl** [comment]
You can download the binaries from the [Oracle Technology Network Download page](http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html).
