### ISSUE TITLE
oracle/database:18.4.0-xe doesn't allow connections for the `system` user

### ISSUE THREAD

**Issue by findinpath** [oracle/docker-images#1620]
When setting up oracle 18.4.0-xe as

https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance 

when trying to connect from outside the instance I get the exception:

```
ORA-12528, TNS:listener: all appropriate instances are blocking new connections
```
or 

```
ORA-12526, TNS:listener: all appropriate instances are in restricted mode.
```

As a workaround, I connect on the docker container

```bash
docker exec -it --user=oracle ${oracle_image_name} bash
``` 

and disable the restricted sessions setting
```
sqlplus /nolog
conn sys as sysdba
password: oracle
alter system disable restricted session;
```

and after this works.

Could you please enable by default or environment variable the restricted sessions?

**Comment by gvenzl** [comment]
I cannot reproduce this issue. After a successful setup, I can connect from within the container as well as outside the container on the same instance with `SYSTEM` and any other user.

The two error messages above could indicate that the database wasn't fully set up yet when the connections where tried to be established.

Can you confirm that you saw this message in the container log before you tried to connect:

```
#########################
DATABASE IS READY TO USE!
#########################
```

**Comment by findinpath** [comment]
I haven't used the docker image since issuing this ticket.

If the connection to the database works on your machine then probably I must have done something wrong while setting up the Oracle docker instance.

Please disregard then this ticket.
