### ISSUE TITLE
Question: Weblogic UCP DS

### ISSUE THREAD

**Issue by Sckmo** [oracle/docker-images#1627]
I'm using the image 12212-oradb-wlsstore
is there a way to set the datasource type to UCP in oradatasource.properties file?
thank you

**Comment by mriccell** [comment]
You need to write WLST as described in the WebLogic documentation https://docs.oracle.com/middleware/1221/wls/JDBCA/ucp_datasources.htm#JDBCA764 which will replace ds-deploy.py used in the sample https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12212-oradb-wlsstore/container-scripts.
