### ISSUE TITLE
No edition has been passed on error

### ISSUE THREAD

**Issue by uadhikari1989** [oracle/docker-images#1631]
When I run docker build -t oracle/database:19.3.0-${EDITION} .
ERROR: No edition has been passed on!
Please specify the correct edition!
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE $DB_EDITION' returned a non-zero code: 1

Where do we have to define the edition and by what name?
![image](https://user-images.githubusercontent.com/42251216/83690392-46485d80-a5b6-11ea-994e-3cc3b813ecdc.png)

**Comment by Djelibeybi** [comment]
You need to replace `${EDITION}` with the actual edition you want to use, i.e. either XE, SE or EE.

**Comment by gvenzl** [comment]
Please use the `./buildDockerImage.sh` build script instead.

**Comment by uadhikari1989** [comment]
[image: image.png]

**Comment by uadhikari1989** [comment]
I used

docker build -t oracle/database:19.3.0-$EE . but it threw the same error.

**Comment by uadhikari1989** [comment]
I tried this way too but no luck.

[image: image.png]

**Comment by Djelibeybi** [comment]
The images are not working. Please paste the text instead, but as @gvenzl says, you should be using the `./buildDockerImage.sh` script, which is documented.

**Comment by uadhikari1989** [comment]
Thank you all for the comments.. 

I run ./buildDockerImage.sh -v 19.3.0 -e 19.3 and it worked perfectly.

**Comment by bennyzx** [comment]
@uadhikari1989 Verified. It works. Thanks for your good advice.

**Comment by gvkuzmen** [comment]
it helped me too! thanks a LOT!

**Comment by omurad** [comment]
Looking at the Dockerfile, it specifies a `DB_EDITION` argument. Meaning you're supposed to add an argument to the Docker build command such as `--build-arg DB_EDITION=EE`.

The following command works

`docker build -t oracle/database:19.3.0-EE --build-arg DB_EDITION=EE .`

**Comment by sykang0223** [comment]
@omurad thx!!
