### ISSUE TITLE
OracleFMWInfrastructure 12213-domain-in-volume -  getDatabaseDefaults() failed - Failed to build JDBC Connection object

### ISSUE THREAD

**Issue by VBAICEAN** [oracle/docker-images#1633]
Hi,

I am trying to build FMW Infrastructure Domain Image per instructions at https://github.com/oracle/docker-images/tree/master/OracleFMWInfrastructure/samples/12213-domain-in-volume.

Step $ ./build.sh InfraNET fails with error:

```
Step 22/24 : RUN /u01/oracle/container-scripts/createFMWDomain.sh &&     echo ". $DOMAIN_HOME/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc &&     chmod -R a+x $DOMAIN_HOME/bin/*.sh
 ---> Running in e5afb5d9e99d
Configuring Domain for first time
=====================================
Domain Home is:  /u01/oracle/user_projects/domains/myinfraDomain
CUSTOM_CONNECTION_STRING=InfraDB:1521/InfraPDB1.us.oracle.com
CUSTOM_RCUPREFIX=INFRA08
CUSTOM_DOMAIN_NAME=myinfraDomain
DOMAIN_HOME=/u01/oracle/user_projects/domains/myinfraDomain
CONNECTION_STRING=InfraDB:1521/InfraPDB1.us.oracle.com
RCUPREFIX=INFRA08
jdbc_url=jdbc:oracle:thin:@InfraDB:1521/InfraPDB1.us.oracle.com
Creating Domain Home
ls -l /u01/oracle/properties
Domain Configuration Phase
==========================

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Creating Admin Server...
Creating cluster...
managed server name is infraMS1
Creating Node Managers...
Will create Base domain at /u01/oracle/user_projects/domains/myinfraDomain
Writing base domain...
Base domain created at /u01/oracle/user_projects/domains/myinfraDomain
Extending domain at /u01/oracle/user_projects/domains/myinfraDomain
Database  InfraDB:1521/InfraPDB1.us.oracle.com
Applying JRF templates...
Extension Templates added
Configuring the Service Table DataSource...
fmwDatabase  jdbc:oracle:thin:@InfraDB:1521/InfraPDB1.us.oracle.com
Getting Database Defaults...
Error: getDatabaseDefaults() failed. Do dumpStack() to see details.
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/container-scripts/createFMWDomain.py", line 297, in ?
  File "/u01/oracle/container-scripts/createFMWDomain.py", line 42, in createInfraDomain
  File "/u01/oracle/container-scripts/createFMWDomain.py", line 141, in extendDomain
  File "/tmp/WLSTOfflineIni9123244009121955878.py", line 263, in getDatabaseDefaults
  File "/tmp/WLSTOfflineIni9123244009121955878.py", line 19, in command
Failed to build JDBC Connection object:
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2983)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:735)
        at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Got exception when auto configuring the schema component(s) with data obtained from shadow table:
Failed to build JDBC Connection object:

Removing intermediate container e5afb5d9e99d
The command '/bin/sh -c /u01/oracle/container-scripts/createFMWDomain.sh &&     echo ". $DOMAIN_HOME/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc &&     chmod -R a+x $DOMAIN_HOME/bin/*.sh' returned a non-zero code: 1

I have completed the previous steps.

$ docker ps -a 
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                      PORTS                                            NAMES
3cb360a8d1a3        12213-fmw-rcu                               "/u01/oracle/contain…"   29 minutes ago      Exited (0) 29 minutes ago                                                    RCU
3985ba844e28        store/oracle/database-enterprise:12.2.0.1   "/bin/sh -c '/bin/ba…"   46 minutes ago      Up 46 minutes (healthy)     0.0.0.0:1521->1521/tcp, 0.0.0.0:5500->5500/tcp   InfraDB
```

Any advice would be appreciated.

Thanks,
Veronica

(Edited for formatting)

**Comment by mriccell** [comment]
Where is your database running?  Did you give the right permissions to the DB user/password so that it can create the schema in the database?

**Comment by VBAICEAN** [comment]
Hi Monica,

I am running everything on my laptop using Docker Desktop. The goal is to containerize an ADF application. For now, I am trying to deploy it locally in the container. I am new to both Docker and python.

docker ps -a shows:

`$ docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                   PORTS                                            NAMES
3cb360a8d1a3        12213-fmw-rcu                               "/u01/oracle/contain…"   3 days ago          Exited (0) 3 days ago                                                     RCU
3985ba844e28        store/oracle/database-enterprise:12.2.0.1   "/bin/sh -c '/bin/ba…"   3 days ago          Up 19 hours (healthy)    0.0.0.0:1521->1521/tcp, 0.0.0.0:5500->5500/tcp   InfraDB
`
Per further debugging, it appears the issue is an ORA-01017: invalid username/password. I am investigating why this happens - your help will be much appreciated.

I am attaching the current output from $ ./build.sh InfraNET command.

Thanks and regards,
Veronica

[ORA-01017 invalid username-password.docx](https://github.com/oracle/docker-images/files/4786560/ORA-01017.invalid.username-password.docx)

**Comment by mriccell** [comment]
Please follow the exact steps in the README https://github.com/oracle/docker-images/blob/master/OracleFMWInfrastructure/samples/12213-domain-in-volume/README.md
The section Running the Oracle FMW Infrastructure domain Docker image

**Comment by VBAICEAN** [comment]
Hi Monica,

Please specify if I need to build myself the Oracle Fusion Middleware Infrastructure 12.2.1.3 binary image. 

My understanding per the README was that this would be an optional step, since the base image is referenced in Dockerfile [https://github.com/oracle/docker-images/blob/master/OracleFMWInfrastructure/samples/12213-domain-in-volume/Dockerfile](url)

Thanks again,
Veronica

**Comment by mriccell** [comment]
@VBAICEAN you can either build the FMW Infra binary image or pull it from container-registry.oracle.com/middleware/fmw-infrastructure:12.2.1.4

**Comment by mriccell** [comment]
This is not an issue,  you need a FMW Infra binary image to be the basis of your domain.. You can obtain the binary image in several ways: 1) Build the FMW Infastructure 12.2.1.4 binary image by following instructions in https://github.com/oracle/docker-images/tree/main/OracleWebLogic/dockerfiles/12.2.1.4  2) Pull a already pre-built image from Oracle Container Registry container-registry.oracle.com/middleware/fmw-infrastructure:12.2.1.4 3) Use the WebLogic Image Tool to build a FMW Infra image https://oracle.github.io/weblogic-image-tool/.  After you have the binary image replace the FROM clause to make reference of the binary image tag.

**Comment by mriccell** [comment]
Then follow the exact steps in the README https://github.com/oracle/docker-images/blob/master/OracleFMWInfrastructure/samples/12213-domain-in-volume/README.md
The section Running the Oracle FMW Infrastructure domain Docker image
