### ISSUE TITLE
Exception type: SIGBUS, Non-existent physical address ksm_mga_heap_alloc_seg()

### ISSUE THREAD

**Issue by josehcrtrt** [oracle/docker-images#1636]
After creating an image for version 19.3.0 wiith commands below:

<pre>
./buildDockerImage.sh -v 19.3.0 -e
</pre>

I started the database and it is OK to use for create user/schema, tables, make dump and restore with impdb. 

Using a dump generated at Oracle 11g, im facing errors like this at alert.log:

<pre>
Exception [type: SIGBUS, Non-existent physical address] [ADDR:0x4002DD000000] [PC:0x10986FC, ksm_mga_heap_alloc_seg()+140] [flags: 0x0, count: 1]
Errors in file /opt/oracle/diag/rdbms/orcl/ORCL/trace/ORCL_m004_25061.trc  (incident=15584) (PDBNAME=CDB$ROOT):
ORA-07445: exception encountered: core dump [ksm_mga_heap_alloc_seg()+140] [SIGBUS] [ADDR:0x4002DD000000] [PC:0x10986FC] [Non-existent physical address] []
Use ADRCI or Support Workbench to package the incident.
See Note 411.1 at My Oracle Support for error and packaging details.
</pre>

Here is the content of the trace /opt/oracle/diag/rdbms/orcl/ORCL/trace/ORCL_m004_25061.trc

<pre>
Trace file /opt/oracle/diag/rdbms/orcl/ORCL/trace/ORCL_m004_25061.trc
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0
Build label:    RDBMS_19.3.0.0.0DBRU_LINUX.X64_190417
ORACLE_HOME:    /opt/oracle/product/19c/dbhome_1
System name:	Linux
Node name:	9c6fcea3e360
Release:	5.3.0-59-generic
Version:	#53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020
Machine:	x86_64
Instance name: ORCL
Redo thread mounted by this instance: 1
Oracle process number: 59
Unix process pid: 25061, image: oracle@9c6fcea3e360 (M004)

*** 2020-06-19T14:44:30.347578+00:00 (CDB$ROOT(1))
*** SESSION ID:(389.62862) 2020-06-19T14:44:30.347619+00:00
*** CLIENT ID:() 2020-06-19T14:44:30.347625+00:00
*** SERVICE NAME:(SYS$BACKGROUND) 2020-06-19T14:44:30.347629+00:00
*** MODULE NAME:(MMON_SLAVE) 2020-06-19T14:44:30.347634+00:00
*** ACTION NAME:(Incident Meter Smry Maint) 2020-06-19T14:44:30.347638+00:00
*** CLIENT DRIVER:() 2020-06-19T14:44:30.347643+00:00
*** CONTAINER ID:(1) 2020-06-19T14:44:30.347647+00:00
 
*********** START A RUN OF [Incident Meter Smry Maint] *************

*** 2020-06-19T14:45:31.759664+00:00 (CDB$ROOT(1))
*** MODULE NAME:(MMON_SLAVE) 2020-06-19T14:45:31.759717+00:00
*** ACTION NAME:(Sweep incidents slave action) 2020-06-19T14:45:31.759724+00:00
*** CONTAINER ID:(1) 2020-06-19T14:45:31.759729+00:00
 
*********** START A RUN OF [Sweep incidents slave action] *************

*** 2020-06-19T14:46:27.068998+00:00 (CDB$ROOT(1))
*** MODULE NAME:(MMON_SLAVE) 2020-06-19T14:46:27.069039+00:00
*** ACTION NAME:(KDILM background EXEcution) 2020-06-19T14:46:27.069045+00:00
*** CONTAINER ID:(1) 2020-06-19T14:46:27.069050+00:00
 
*********** START A RUN OF [KDILM background EXEcution] *************
*** MODULE NAME:(MMON_SLAVE) 2020-06-19T14:46:27.069772+00:00
*** ACTION NAME:(Auto-Flush Slave Action) 2020-06-19T14:46:27.069789+00:00
*** CONTAINER ID:(1) 2020-06-19T14:46:27.069794+00:00
 
*********** START A RUN OF [Auto-Flush Slave Action] *************

*** 2020-06-19T14:46:33.198807+00:00 (CDB$ROOT(1))
*** MODULE NAME:(MMON_SLAVE) 2020-06-19T14:46:33.198859+00:00
*** ACTION NAME:(Sweep incidents slave action) 2020-06-19T14:46:33.198866+00:00
*** CONTAINER ID:(1) 2020-06-19T14:46:33.198871+00:00
 
*********** START A RUN OF [Sweep incidents slave action] *************

*** 2020-06-19T14:47:06.992596+00:00 (CDB$ROOT(1))
*** MODULE NAME:(MMON_SLAVE) 2020-06-19T14:47:06.992661+00:00
*** ACTION NAME:(Monitor Tablespace Thresholds) 2020-06-19T14:47:06.992668+00:00
*** CONTAINER ID:(1) 2020-06-19T14:47:06.992674+00:00
 
*********** START A RUN OF [Monitor Tablespace Thresholds] *************

*** 2020-06-19T14:47:28.511541+00:00 (CDB$ROOT(1))
*** MODULE NAME:(MMON_SLAVE) 2020-06-19T14:47:28.511592+00:00
*** ACTION NAME:(KDILM background EXEcution) 2020-06-19T14:47:28.511600+00:00
*** CONTAINER ID:(1) 2020-06-19T14:47:28.511605+00:00
 
*********** START A RUN OF [KDILM background EXEcution] *************
*** MODULE NAME:(MMON_SLAVE) 2020-06-19T14:47:28.511844+00:00
*** ACTION NAME:(KDILM background CLeaNup) 2020-06-19T14:47:28.511857+00:00
*** CONTAINER ID:(1) 2020-06-19T14:47:28.511864+00:00
 
*********** START A RUN OF [KDILM background CLeaNup] *************
*** MODULE NAME:(MMON_SLAVE) 2020-06-19T14:47:28.512062+00:00
*** ACTION NAME:(Intensive AutoTask Dispatcher) 2020-06-19T14:47:28.512074+00:00
*** CONTAINER ID:(1) 2020-06-19T14:47:28.512080+00:00
 
*********** START A RUN OF [Intensive AutoTask Dispatcher] *************
*** MODULE NAME:(MMON_SLAVE) 2020-06-19T14:47:28.526748+00:00
*** ACTION NAME:(Automatic Report Flush) 2020-06-19T14:47:28.526778+00:00
*** CONTAINER ID:(1) 2020-06-19T14:47:28.526785+00:00
 
*********** START A RUN OF [Automatic Report Flush] *************

*** 2020-06-19T14:47:29.146841+00:00 (CDB$ROOT(1))
Exception [type: SIGBUS, Non-existent physical address] [ADDR:0x4002DD000000] [PC:0x10986FC, ksm_mga_heap_alloc_seg()+140] [flags: 0x0, count: 1]
DDE: Problem Key 'ORA 7445 [ksm_mga_heap_alloc_seg]' was flood controlled (0x6) (incident: 15584)
ORA-07445: exception encountered: core dump [ksm_mga_heap_alloc_seg()+140] [SIGBUS] [ADDR:0x4002DD000000] [PC:0x10986FC] [Non-existent physical address] []
Dumping swap information
Memory (Avail / Total) = 155.63M / 9965.79M
Swap (Avail / Total) = 1656.75M /  2048.00M
ssexhd: crashing the process...
Shadow_Core_Dump = partial
ksdbgcra: writing core file to directory '/opt/oracle/diag/rdbms/orcl/ORCL/cdump'
</pre>

**Comment by gvenzl** [comment]
Hi @josehcrtrt,

This is a database internal error that you encounter.
Please consult with [My Oracle Support](https://support.oracle.com/portal/).

**Comment by sunsunsong** [comment]
I have same issue with all same error , anybody help?

**Comment by Djelibeybi** [comment]
The same thing applies: please open an SR with Oracle Support.

**Comment by josehcrtrt** [comment]
I opened SR 3-23363809671 : Error on Docker Oracle 19.3.0: Exception type: SIGBUS, Non-existent physical address

But until now, no satisfactory resolution

The Support want code dump files, but directories has no files:

<pre>
[oracle@6bb89c83b74e cdump]$ ls -laR
.:
total 116
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 .
drwxr-x--- 1 oracle oinstall 4096 Jun 26 18:32 ..
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:20 core_122
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:21 core_124
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:23 core_1482
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:26 core_1485
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:25 core_1515
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:27 core_1546
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:33 core_1578
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:28 core_1609
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:30 core_1640
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:29 core_1643
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:31 core_1705
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:32 core_1736
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:35 core_1800
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:34 core_1803
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:41 core_1833
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:36 core_1864
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:37 core_1924
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:38 core_1927
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:39 core_1958
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:40 core_2039
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:42 core_2041
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:43 core_2052
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:44 core_2112
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:24 core_436
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:19 core_498
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:22 core_786

./core_122:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:20 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_124:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:21 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1482:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:23 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1485:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:26 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1515:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:25 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1546:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:27 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1578:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:33 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1609:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:28 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1640:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:30 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1643:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:29 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1705:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:31 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1736:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:32 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1800:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:35 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1803:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:34 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1833:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:41 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1864:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:36 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1924:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:37 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1927:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:38 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_1958:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:39 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_2039:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:40 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_2041:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:42 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_2052:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:43 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_2112:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:44 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_436:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:24 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_498:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:19 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

./core_786:
total 8
drwxr-x--- 2 oracle oinstall 4096 Jun 29 17:22 .
drwxr-x--- 1 oracle oinstall 4096 Jun 29 17:44 ..

</pre>

**Comment by sunsunsong** [comment]
I have researched these errors for several days,  and have read a lot of related error topic articles in the internal, one of the related topic: [https://blog.csdn.net/mrluoe/article/details/9138765?utm_medium=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.nonecase&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.nonecase](url),  seems to give me tips, so followed this article, I do the change in /etc/hosts in docker like this : 

[root @07d72f31ae39]$ more /etc/hosts
127.0.0.1       localhost   07d72f31ae39
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.18.0.2      07d72f31ae39

also, add hostname in the first line in /etc/hosts, and restart Oracle DB, so everything seems to be ok for two days, no that errors and core dump show again, and everything in the alert log is pretty good.
another should be noticed if you restart docker again, this change in /etc/hosts can be a rollback, need change again, and restart Oracle DB.
I hope it helps and works.

**Comment by josehcrtrt** [comment]
Oracle suport suggested this workaround:
<pre>
ALTER SYSTEM SET "_in_memory_cdt"=OFF SCOPE=BOTH;
</pre>
"Disabling that particular hidden parameter appears to be a fairly minor change and should have no ill-effects.

After that the error has stopped occurring.

As it is a workaround (using a hidden parameter "_"), the oracle-docker team could create a definitive solution.

Please let us know when this definitive solution is available.

**Comment by sunsunsong** [comment]
That change that I set in /etc/hosts does not work after a few days,  and you provided that alert command is work until now.
Thank you very much Josehcrtrt !

**Comment by josehcrtrt** [comment]
Ok @sunsunsong . I´m glad to help!
