### ISSUE TITLE
Customized RAC deployment on docker

### ISSUE THREAD

**Issue by nmukheja** [oracle/docker-images#1638]
Hi Team, 

We are planning to implement this solution for our non-prod functional testing environment.
But we need to change the hard coded settings of disk and ram etc in the deployment.
Also we are planning to implement NFS not as a container.
Do you have any similar documentation or steps for same.

**Comment by psaini79** [comment]
@nmukheja ,

I do not recall that there is any hard coded setting. Are you referring to NFS based dummy disks names? Also, please let me know your exact requirement and we can assist you.

**Comment by nmukheja** [comment]
If i want to use different asm disk sizes or different RAM for my deployment how can i do so or will it be handled automatically.
With respect to NFS , can we use NFS without creating storage container.

**Comment by psaini79** [comment]
Yes, you do not need NFS container and you can have biger ASM disk size on real NFS device. Also, what RAM you want to assign to containers?
Please paste your requirement and let me give you a container creation command.

**Comment by psaini79** [comment]
@nmukheja 

Please let me know if you have any requirements details. Otherwise, you can use NFS in an existing solution and assign memory to containers by using --memory flag in container creation command.

**Comment by nmukheja** [comment]
@psaini79 

Thanks for the reply , we are looking to create containers with 16GB memory each.
Also once the ASM disk is created using NFS container, is there an option to extend the disk or we need to create NFS container again.

**Comment by psaini79** [comment]
@nmukheja 

1) Create NFS volume using your NFS server and make sure the docker bridge is able to reach that.  In the 2nd point, I am using racstorage docker NFS volume and you need to change it to based on your env.

2) Please create a container using the following command:

```
docker create -t -i \
   --hostname racnode1 \
   --volume /boot:/boot:ro \
   --volume /dev/shm \
   --tmpfs /dev/shm:rw,exec,size=4G \
   --volume /opt/containers/rac_host_file:/etc/hosts  \
   --volume /opt/.secrets:/run/secrets \
   --dns-search=example.com \
   --privileged=false \
   --volume racstorage:/oradata \
   --cap-add=SYS_NICE \
   --cap-add=SYS_RESOURCE \
   --cap-add=NET_ADMIN \
   -e NODE_VIP=172.16.1.160  \
   -e VIP_HOSTNAME=racnode1-vip  \
   -e PRIV_IP=192.168.17.150  \
   -e PRIV_HOSTNAME=racnode1-priv \
   -e PUBLIC_IP=172.16.1.150 \
   -e PUBLIC_HOSTNAME=racnode1  \
   -e SCAN_NAME=racnode-scan \
   -e SCAN_IP=172.16.1.70  \
   -e OP_TYPE=INSTALL \
   -e DOMAIN=example.com \
   -e ASM_DISCOVERY_DIR=/oradata \
   -e ASM_DEVICE_LIST=/oradata/asm_disk01.img,/oradata/asm_disk02.img,/oradata/asm_disk03.img,/oradata/asm_disk04.img,/oradata/asm_disk05.img  \
   -e CMAN_HOSTNAME=racnode-cman1 \
   -e CMAN_IP=172.16.1.15 \
   -e COMMON_OS_PWD_FILE=common_os_pwdfile.enc \
   -e PWD_KEY=pwd.key \
   --restart=always \
   --tmpfs=/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
   --volume /etc/localtime:/etc/localtime:ro \
    --cpuset-cpus 0-1 \
    --memory 16G \
    --memory-swap 32G \
    --sysctl kernel.shmall=2097152  \
    --sysctl "kernel.sem=250 32000 100 128" \
    --sysctl kernel.shmmax=8589934592  \
    --sysctl kernel.shmmni=4096 \
   --cpu-rt-runtime=95000 \
   --ulimit rtprio=99  \
   --name racnode1 \
   oracle/database-rac:19.3.0
```
3) If  you want to create 2 node RAC using responsefile, please refer the following  link:
https://github.com/oracle/docker-images/tree/master/OracleDatabase/RAC/OracleRealApplicationClusters/samples/customracdb

Let me know if you see any issue.

**Comment by nmukheja** [comment]
Thanks @psaini79 

One last thing i want to know is suppose we start the NFS with lets say 150GB(all disks included) and after some time requirement is for 200GB. Can we dynamically increase the same or we need to take backup, drop everything and create with new config.

**Comment by psaini79** [comment]
@nmukheja 

You don't need to delete the RAC cluster to add or delete the disks. Following will be the steps:
 *  Mount the NFS volume with the correct permissions
 * Create disks using dd command and add them based on your requirement.

Keep me posted if you see any issue or you have a question to understand the steps.

**Comment by nmukheja** [comment]
Thanks @psaini79 :

It would be really helpful if you can point me to some documentation for adding disk dynamically or provide steps for same.

**Comment by psaini79** [comment]
@nmukheja 

Please refer the following link :

https://docs.oracle.com/en/database/oracle/oracle-database/18/cwaix/creating-files-on-a-nas-device-for-use-with-oracle-automatic-storage-management.html#GUID-D1F279EF-2D7D-4F70-9AC3-3078FF6E5649

You create the zero-padded disks to be used Oracle ASM.

Once the disks are ready with proper permissions, you can add them to existing ASM disk group using the following link:
https://docs.oracle.com/en/database/oracle/oracle-database/19/ostmg/alter-diskgroups.html#GUID-6BB31112-8687-4C1E-AF14-D94FFCDA736F

**Comment by nmukheja** [comment]
Thanks @psaini79  for your help ..!!

**Comment by psaini79** [comment]
@nmukheja 

Close the ticket and open a new ticket if you have any questions.
