### ISSUE TITLE
oracledb-19c does not contain apex

### ISSUE THREAD

**Issue by uadhikari1989** [oracle/docker-images#1648]
I looked at the Dockerfile regarding OracleDB but couldn't see anything related to apex. I saw apex at oracleDB 12 version. So If I also need to have apex alongside OracleDb then what should I do? Or am I not able to understand the code properly.

**Comment by mrchulho** [comment]
apex seems to get removed after installation per this code:
https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/19.3.0/installDBBinaries.sh#L62

Can you try to comment out that line, and run buildDockerImage.sh?

**Comment by uadhikari1989** [comment]
@mrchulho Thanks for the respond. The image was built but how can I check if the apex is installed or not? Also I put the apex zip file prior building my docker image..

**Comment by mrchulho** [comment]
@uadhikari1989 `docker exec` can be used.
https://docs.docker.com/engine/reference/commandline/exec/

**Comment by uadhikari1989** [comment]
@mrchulho I am familiar with the docker exec things. But when I go inside the terminal what should I do? I went inside the container and do ps -ef | grep apex but it didn't show anything. 

![db_docker-apex](https://user-images.githubusercontent.com/42251216/86796865-a0fd2b00-c034-11ea-8a84-e43c8a56114b.PNG)

**Comment by uadhikari1989** [comment]
> apex seems to get removed after installation per this code:
> https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/19.3.0/installDBBinaries.sh#L62
> 
> Can you try to comment out that line, and run buildDockerImage.sh?

I don't think it worked that way.. I still saw apex is not installed.

**Comment by mrchulho** [comment]
@uadhikari1989  What do you get by this command in the container?
`ls -l $ORACLE_HOME/apex`

**Comment by uadhikari1989** [comment]
> @uadhikari1989 What do you get by this command in the container?
> `ls -l $ORACLE_HOME/apex`

![image](https://user-images.githubusercontent.com/42251216/87057656-c1f88400-c1cc-11ea-8c62-aedda4ddb4c4.png)

**Comment by mrchulho** [comment]
apex requires web listener.
https://docs.oracle.com/en/database/oracle/application-express/20.1/htmig/Oracle-AE-installation-requirements.html#GUID-848EF7A3-07D0-427E-A080-694144570136

Oracle REST Data Services (ORDS) gets also deleted while slimming process
https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/19.3.0/installDBBinaries.sh#L64

You may want to build a new image disabling slimming altogether.
`buildDockerImage.sh -v 19.3.0 -e -o "--build-arg SLIMMING=false"`
https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile#L38

**Comment by uadhikari1989** [comment]
> apex requires web listener.
> https://docs.oracle.com/en/database/oracle/application-express/20.1/htmig/Oracle-AE-installation-requirements.html#GUID-848EF7A3-07D0-427E-A080-694144570136
> 
> Oracle REST Data Services (ORDS) gets also deleted while slimming process
> https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/19.3.0/installDBBinaries.sh#L64
> 
> You may want to build a new image disabling slimming altogether.
> `buildDockerImage.sh -v 19.3.0 -e -o "--build-arg SLIMMING=false"`
> https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile#L38

I tried this way too. I was able to bring up the oracleDb up but not the apex. 

I run this command
[umesh@docker-server ~]$ docker run --name 19.3.0-ee  --shm-size=1g -p 1521:1521 -p 8080:8080 -e ORACLE_PWD=PWD -v /u01/app/oracle/oradata oracle/database:19.3.0-ee

All my ports are open. Then I went to browser and run http://localhost:8080/ords/ but nothing comes up. I also tried my IP address instead of localhost but no luck on that too..

**Comment by mrchulho** [comment]
From apex [documentation](https://docs.oracle.com/en/database/oracle/application-express/20.1/htmig/choosing-web-listener.html#GUID-2FF90AE3-87AE-42EB-90C7-A79A0A6AA997)

> 3.4.3 About Oracle REST Data Services
> Oracle REST Data Services (formerly Oracle Application Express Listener) is Java-based, can be installed into any supported J2EE compliant Web Server. Oracle recommends using Oracle REST Data Services with Oracle Application Express.
> 
> It is a free tool that is fully supported against Oracle WebLogic Server and Apache Tomcat.

You will need to download and install Tomcat.
See [this project](https://github.com/Dani3lSun/docker-db-apex-dev) where oracle and tomcat seem covered.

**Comment by uadhikari1989** [comment]
> From apex [documentation](https://docs.oracle.com/en/database/oracle/application-express/20.1/htmig/choosing-web-listener.html#GUID-2FF90AE3-87AE-42EB-90C7-A79A0A6AA997)
> 
> > 3.4.3 About Oracle REST Data Services
> > Oracle REST Data Services (formerly Oracle Application Express Listener) is Java-based, can be installed into any supported J2EE compliant Web Server. Oracle recommends using Oracle REST Data Services with Oracle Application Express.
> > It is a free tool that is fully supported against Oracle WebLogic Server and Apache Tomcat.
> 
> You will need to download and install Tomcat.
> See [this project](https://github.com/Dani3lSun/docker-db-apex-dev) where oracle and tomcat seem covered.

I was able to follow https://github.com/Dani3lSun/docker-db-apex-dev document which you mentioned. But that document is more of  Enterprise Edition with non-CDB architecture. Is that architecture and this architecture which is in this repo the same? If that's the case then I am good but our organization does not need the architecture with non-CDB. So I am confused now.

Our architecture is pretty much similar with what the code with oracledb with 12.2.0.1 version have and same with apex stuffs. But 19c feature doesn't contain apex like it contained in 12 version.

**Comment by KamilJedrzejuk** [comment]
Don't use Apex IT is 2020 You have Angular. VueJS.  react
