### ISSUE TITLE
Can I run the Oracle WebLogic Docker Image in production?

### ISSUE THREAD

**Issue by Starefossen** [oracle/docker-images#165]
Can someone from Oracle tell me if I can run the Oracle WebLogic Docker Image in production mode (not development mode) with external traffic and what license I will need for it?

**Comment by brunoborges** [comment]
Eeerrr... What is Oracle WildFly? Are you talking about WildFly from Red Hat, or you wanted to say Oracle WebLogic?

**Comment by Starefossen** [comment]
Sorry. My bad for mixing up the names. I meant Oracle WebLogic. Currently in the process of migrating a bunch of Java applications to Docker.

**Comment by Starefossen** [comment]
I have read the [Running Oracle WebLogic Server on Docker (E70166-01)](https://docs.oracle.com/middleware/12211/wls/DOCKR/DOCKR.pdf) as well as [Supported Virtualization and Partitioning Technologies for Oracle Fusion Middleware](http://www.oracle.com/technetwork/middleware/ias/oracleas-supported-virtualization-089265.html) and I can not find an explanation on how licensing for production usage works.

**Comment by brunoborges** [comment]
There are no specifics for licensing WebLogic on Docker. You license as
usual (regardless if you will use inside a container or directly on the
host environment)

*Bruno Borges*
+1 (650) 454-9628
*www.brunoborges.com <http://www.brunoborges.com>*

**Comment by haribabuscb** [comment]
How WebLogic licensing works in case of shipping the pre-built service’s images to customer?

**Comment by mriccell** [comment]
Docker is not considered a hard partitioned technology.  For development purposes only the customer can pull the image and the license is the same as in  OTN Free Developer License Agreement http://www.oracle.com/technetwork/licenses/wls-dev-license-1703567.html.  When the customer deploys Docker container running WebLogic Servers in production they must license all the CPUs in the host where the Docker containers are running.

**Comment by mriccell** [comment]
Does this help?

**Comment by haribabuscb** [comment]
Thanks for the response. Yes, your answer was clear and I got an initial understanding on WebLogic Server Docker licensing.

**Comment by brunoborges** [comment]
I would go beyond and say that Docker *does not support* hard partitioning because processes run on the host. So, it *can't* be understood as hard partitioned technology at all.

**Comment by kamatchigiri** [comment]
> http://www.oracle.com/technetwork/licenses/wls-dev-license-1703567.html
How licensing is done when the Weblogic containerized image runs on public cloud where cpus can't be calculated?  Does it differ to every cloud service provider?
