### ISSUE TITLE
ORA-65169: error encountered while attempting to copy file

### ISSUE THREAD

**Issue by flrsilva** [oracle/docker-images#1650]
Hello,

I'm trying to deploy DB version 19.3.0 on a Kubernetes cluster with docker containers. The image creation process completes apparently without any errors. If I load the image directly using the docker container tool, the image runs flawlessly. When I try to run the DB container image on the Kubernetes cluster, I get the following error output in the container db log: 

```
2020-07-06 22:43:27.938 UTC ] Prepare for db operation
DBCA_PROGRESS : 8%
[ 2020-07-06 22:43:28.038 UTC ] Copying database files
DBCA_PROGRESS : 31%
[ 2020-07-06 22:44:42.925 UTC ] Creating and starting Oracle instance
DBCA_PROGRESS : 32%
DBCA_PROGRESS : 36%
DBCA_PROGRESS : 40%
DBCA_PROGRESS : 43%
DBCA_PROGRESS : 46%
[ 2020-07-06 22:53:50.643 UTC ] Completing Database Creation
DBCA_PROGRESS : 51%
DBCA_PROGRESS : 54%
[ 2020-07-06 23:01:29.438 UTC ] Creating Pluggable Databases
[ 2020-07-06 23:01:30.712 UTC ] [WARNING] ORA-65169: error encountered while attempting to copy file
ORA-12801: error signaled in parallel query server

[ 2020-07-06 23:01:30.714 UTC ] [FATAL] ORA-65011: Pluggable database PDB does not exist.

[ 2020-07-06 23:01:30.715 UTC ] ORA-65011: Pluggable database PDB does not exist.
...
```

On the pluggable DB log, the error reported is: 
```
CREATE PLUGGABLE DATABASE PDB ADMIN USER PDBADMIN IDENTIFIED BY ****** ROLES=(CONNECT) file_name_convert=('/opt/oracle/oradata/CDB/pdbseed/sysaux01.dbf','/opt/oracle/oradata/CDB/PDB/sysaux01.dbf',
*
ERROR at line 1:
ORA-65169: error encountered while attempting to copy file
ORA-12801: error signaled in parallel query server
```

I've checked for possible solutions here [#1527] and here [#1121], but didn't worked out. I'm attaching some relevant logs and install file to try to get pointers on what could be causing this issue. 
[CDB.log](https://github.com/oracle/docker-images/files/4882136/CDB.log)
[plugDatabase1R.log](https://github.com/oracle/docker-images/files/4882139/plugDatabase1R.log)
[postDBCreation.log](https://github.com/oracle/docker-images/files/4882140/postDBCreation.log)
[dbca.rsp.txt](https://github.com/oracle/docker-images/files/4882161/dbca.rsp.txt)

Any help/hints will be gladly taken in consideration. 

Thanks in advance, best regards,

**Comment by abhisbyk** [comment]
Hi,
Can you make use of the helm charts available in the [OracleDatabase/SingleInstance/helm-charts/](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/helm-charts/oracle-db) directory for deploying the image on your Kubernetes cluster ?
