### ISSUE TITLE
OracleDatabase/SingleInstance: Excessive amount of *.aud files are being generated by healthcheck

### ISSUE THREAD

**Issue by ChaosEngine** [oracle/docker-images#1651]
When health check is being performed in form of `checkDBStatus.sh` script, execution of:

`
sqlplus -s / as sysdba << EOF
   set heading off;
   set pagesize 0;
   SELECT DISTINCT open_mode FROM v\\$pdbs WHERE open_mode = "$OPEN_MODE";
`

this script is executed every minute (`Dockerfile`):

`
HEALTHCHECK --interval=1m --start-period=5m \
   CMD "$ORACLE_BASE/$CHECK_DB_FILE" >/dev/null || exit 1
`

...which is very very often to say the least. And combined with default sysdba user priv setting which can not be turned of (?):

https://docs.oracle.com/cd/B19306_01/network.102/b14266/cfgaudit.htm#i1007559
***.aud** files are generated at an astounding rate.

Solution? consider other health check method not producing adump *aud file to appear every minute

**Comment by faisal6621** [comment]
Hi @ChaosEngine,
I had recently observed that when creating a docker container it is extensively consuming the memory available which goes to 100% (100Gb currently). This issue occurs on a specific machine only.
Can you share the path where these *.aud files being generated?

**Comment by ChaosEngine** [comment]
> Hi @ChaosEngine,
> I had recently observed that when creating a docker container it is extensively consuming the memory available which goes to 100% (100Gb currently). This issue occurs on a specific machine only.
> Can you share the path where these *.aud files being generated?

Sure. It resides at `/opt/oracle/admin/ORCLCDB/adump/` inside container.

**Comment by ChaosEngine** [comment]
Great, thanks for merging the PR :-)

Should I consider creating similar PRs for other versions? I see opportunity to fix it also [here](https://github.com/oracle/docker-images/blob/c1c4e793d09160e908bdb75c1df26f09a3631054/OracleDatabase/SingleInstance/dockerfiles/11.2.0.2/checkDBStatus.sh), [here](https://github.com/oracle/docker-images/blob/c1c4e793d09160e908bdb75c1df26f09a3631054/OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/checkDBStatus.sh),  [here](https://github.com/oracle/docker-images/blob/c1c4e793d09160e908bdb75c1df26f09a3631054/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/checkDBStatus.sh) and [here](https://github.com/oracle/docker-images/blob/c1c4e793d09160e908bdb75c1df26f09a3631054/OracleDatabase/SingleInstance/dockerfiles/18.3.0/checkDBStatus.sh).
Again, this is still due to every `/ as sysdba` login being audited and creating unnecessary *.aud file.
I assume that RAC images could be also affected by this.
