### ISSUE TITLE
Oracle Database sessions not terminating, even after docker container is stopped

### ISSUE THREAD

**Issue by putta2811** [oracle/docker-images#1652]
Hi Team,

I have a docker container in which I run a bash script to which I pass a sqlfile and other arguments. The bash executes the sqlfile by connecting to Oracle using sqlplus. The database is remote database. Basically I am just trying to connect to sqlplus from inside my container and executing a package. 

What i have observed is when i stop the docker container or when i connect to the docker container and try to kill the OS process of sqlplus, I see that in both case the container exits but in database the session is still active and finishes.

When we stop a docker container, will it not do a clean exit. Please could you help with this issue. I have tried handling signals etc. But i see the container stops and sqlplus also exits but the database sessions don't get terminated.

Oracle Database - 12c Rac - Exadata system

DockerFile - 

From <OS image>[centos image]
Entrypoint ["/bin/bash","startup_script.sh"]

startup_script.sh
sqlplus <credentials> <sqlfile> <arguments>

Executed as:
docker run <image> <sqlfile> <arguments>

**Comment by Djelibeybi** [comment]
Please note that we absolutelyu do not support Docker on an Exadata at all. This shouldn't even be attempted. We also do not support CentOS based images on any platform. Finally, we don't support customer Dockerfiles.

If you can reproduce this issue on a normal Oracle Linux host running Oracle Container Runtime for Docker with one of the Dockerfiles hosted on this repo, then we'd be happy to provide further support.

**Comment by cjbj** [comment]
The other problem I see is running a SQL\*Plus script.  While SQL\*Plus is great for ad hoc stuff and query testing, your scenario should use a scripting language such as Python with the cx_Oracle driver so you have more control over error handling.  See https://github.com/oracle/docker-images/blob/master/OracleLinuxDevelopers/oraclelinux7/python/3.6-oracledb/Dockerfile or https://blogs.oracle.com/opal/docker-for-oracle-database-applications-in-nodejs-and-python-part-1
