### ISSUE TITLE
How create managed server with Docker in host remote (Weblogic 12.2.1.4)

### ISSUE THREAD

**Issue by stevenoliva01** [oracle/docker-images#1653]
How create managed server with Docker in host remote (Weblogic 12.2.1.4) ?

Is there a step-by-step manual?

**Comment by Djelibeybi** [comment]
Is this still an issue?

**Comment by mriccell** [comment]
Please follow the example https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain

**Comment by mriccell** [comment]
I am not sure what you mean by host remote.  The above sample is 12.2.1.3 but all you need is to change the FROM clause to extend a 12.2.1.4 binary image.
