### ISSUE TITLE
Unable to create the database on first run

### ISSUE THREAD

**Issue by neosource** [oracle/docker-images#166]
DBCA_PROGRESS : 42%
ORA-04031: unable to allocate 1015832 bytes of shared memory ("shared pool","unknown object","PDB Dynamic He","Alloc/Free SWRF Metric CHBs")

This on MacOS X 10.11.6 running Docker Version 1.12.1-beta26.1 (build: 12100)

**Comment by gvenzl** [comment]
How much memory is available for the container? You will need at least 2GB to run the DB inside it.

**Comment by brunoborges** [comment]
@neosource, can you provide more information?

**Comment by neosource** [comment]
There is 16 GB on the machine and I am sure there is more than 2 GB for the container. Things are even worse now that I have upgraded to MacOS Seirra. The build script is not going ahead after the "Successfully Setup Software." message.

Regards,
Ravi Reddy

**Comment by gvenzl** [comment]
@neosource Actually, after that message not much is happening anymore. But Docker takes a while to commit the layer afterwards though. Just tested it and it seems to hang for about 2 minutes before it progresses:

> Starting Oracle Universal Installer...
> 
> Checking Temp space: must be greater than 500 MB.   Actual 25113 MB    Passed
> Checking swap space: must be greater than 150 MB.   Actual 8063 MB    Passed
> Preparing to launch Oracle Universal Installer from /tmp/OraInstall2016-09-29_08-46-22PM. Please wait ...[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
>    ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
> You can find the log of this install session at:
>  /opt/oracle/oraInventory/logs/installActions2016-09-29_08-46-22PM.log
> The installation of Oracle Database 12c was successful.
> Please check '/opt/oracle/oraInventory/logs/silentInstall2016-09-29_08-46-22PM.log' for more details.
> 
> As a root user, execute the following script(s):
> 	1. /opt/oracle/oraInventory/orainstRoot.sh
> 	2. /opt/oracle/product/12.1.0.2/dbhome_1/root.sh
> 
> 
> 
> Successfully Setup Software.
> 
>  ---> 93c6b161d382
> Removing intermediate container 176538900fe0
> Step 11 : RUN chmod u+x $INSTALL_DIR/installPerl.sh &&     $ORACLE_HOME/perl/bin/perl -v ||     $INSTALL_DIR/installPerl.sh
>  ---> Running in 3bbff9f922d9
> 
> This is perl 5, version 14, subversion 1 (v5.14.1) built for x86_64-linux-thread-multi
> 
> Copyright 1987-2011, Larry Wall
> 
> Perl may be copied only under the terms of either the Artistic License or the
> GNU General Public License, which may be found in the Perl 5 source kit.
> 
> Complete documentation for Perl, including FAQ lists, should be found on
> this system using "man perl" or "perldoc perl".  If you have access to the
> Internet, point your browser at http://www.perl.org/, the Perl Home Page.
> 
>  ---> e8c4ef9129a0
> Removing intermediate container 3bbff9f922d9
> Step 12 : USER root
>  ---> Running in 7ea6ca603a5c
>  ---> 75a2051ae29b
> Removing intermediate container 7ea6ca603a5c
> Step 13 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
>  ---> Running in 020ca76e5a64
> Changing permissions of /opt/oracle/oraInventory.
> Adding read,write permissions for group.
> Removing read,write,execute permissions for world.
> 
> Changing groupname of /opt/oracle/oraInventory to dba.
> The execution of the script is complete.
> Check /opt/oracle/product/12.1.0.2/dbhome_1/install/root_9f6757744a2a_2016-09-29_20-51-19.log for the output of root script
>  ---> a7936965105b
> Removing intermediate container 020ca76e5a64
> Step 14 : USER oracle
>  ---> Running in 0b1cfde6bc7b
>  ---> 9ad0e941cd36
> Removing intermediate container 0b1cfde6bc7b
> Step 15 : WORKDIR /home/oracle
>  ---> Running in 5ecad5456a68
>  ---> 2f55d5d135a9
> Removing intermediate container 5ecad5456a68
> Step 16 : EXPOSE 1521 5500
>  ---> Running in 2474b1451bae
>  ---> 3d4164cf449d
> Removing intermediate container 2474b1451bae
> Step 17 : CMD $ORACLE_BASE/$RUN_FILE
>  ---> Running in 7e7f4436c796
>  ---> 58ad3e502a25
> Removing intermediate container 7e7f4436c796
> Successfully built 58ad3e502a25
> 
>   Oracle Database Docker Image for 'ee' version 12.1.0.2 is ready to be extended:
> 
>     --> oracle/database:12.1.0.2-ee
> 
>   Build completed in 751 seconds.

This was the latest ee build file that I've just tested.

Are you

**Comment by brunoborges** [comment]
Built here too and it is working fine. For now, I'll leave this closed.

@neosource, let us know of any other issue.
