### ISSUE TITLE
Wrong script location for OracleDatabase SingleInstance Express Edition

### ISSUE THREAD

**Issue by jahson** [oracle/docker-images#1662]
According to [doc](https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md#running-scripts-after-setup-and-on-startup)

```
Note: Use /u01/app/oracle/scripts/ instead of /opt/oracle/scripts/ for Express Edition.
```

This statement is true for [11.2.0.2](https://github.com/oracle/docker-images/blob/4f54ca3ba86fef21822f70c4901cf6e474364dda/OracleDatabase/SingleInstance/dockerfiles/11.2.0.2/Dockerfile.xe#L36-L38), but not for [18.4.0](https://github.com/oracle/docker-images/blob/4f54ca3ba86fef21822f70c4901cf6e474364dda/OracleDatabase/SingleInstance/dockerfiles/18.4.0/Dockerfile.xe#L29-L31).

Either documentation or Dockerfile is wrong. I'm ready to create a pull request when you'll provide me with the details.

**Comment by gvenzl** [comment]
The documentation is wrong:

```
[oracle@ol7 ~]$ docker run --name test1 -ti oracle/database:18.4.0-xe bash
bash-4.2# ls -al /opt/oracle/scripts
total 0
drwxr-xr-x 1 oracle oinstall  24 May  1 18:42 .
drwxr-xr-x 1 oracle oinstall 180 May  1 18:42 ..
drwxr-xr-x 1 oracle oinstall   0 May  1 18:42 setup
drwxr-xr-x 1 oracle oinstall   0 May  1 18:42 startup
bash-4.2# ls -al /u01/app/oracle/scripts
ls: cannot access /u01/app/oracle/scripts: No such file or directory
bash-4.2# exit
exit

[oracle@ol7 ~]$ docker run --name test2 -ti oracle/database:11.2.0.2-xe bash
bash-4.2# ls -al /opt/oracle/scripts
ls: cannot access /opt/oracle/scripts: No such file or directory
bash-4.2# ls -al /u01/app/oracle/scripts
total 0
drwxr-xr-x 1 oracle dba  24 Apr  2 04:01 .
drwxr-xr-x 1 oracle dba 138 Apr  2 04:01 ..
drwxr-xr-x 1 oracle dba   0 Apr  2 04:01 setup
drwxr-xr-x 1 oracle dba   0 Apr  2 04:01 startup
bash-4.2# exit
exit
[oracle@ol7 ~]$
Connection to localhost closed.
```

**Comment by jahson** [comment]
But both versions are Express Edition, am I right?

**Comment by jahson** [comment]
Ah, I see your PR now.
