### ISSUE TITLE
Oracle 19c container times out with versions 19.3.0.0 and onwards of the OJDBC

### ISSUE THREAD

**Issue by danielthegray** [oracle/docker-images#1663]
The Oracle 19c Docker image does not work with Version 19.3.0.0 and above of the Oracle JDBC driver, giving a strange "Got minus one from read call" for any ojdbc driver versioned at 19.3 or above.

I have prepared a small demo project which show cases the bug. I have ruled out network problems by sniffing traffic both inside and outside the Docker container, from SQL*Plus, and the traffic is the same. It might be a bug in the driver itself, but I post it here because I cannot rule out that the database container itself is not part of the problem (since Oracle 11g and 12c work fine).

The repository can be found here: https://github.com/danielthegray/ojdbc-bugsample/tree/master along with an explanatory README file.

The full error stack trace is pasted below:
```
java.sql.SQLRecoverableException: IO Error: Got minus one from a read call
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:858)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at ojdbc.bugsample.App.main(App.java:14)
Caused by: oracle.net.ns.NetException: Got minus one from a read call
        at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:557)
        at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:258)
        at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:190)
        at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:132)
        at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:105)
        at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:91)
        at oracle.net.ano.AnoCommNIO.p(Unknown Source)
        at oracle.net.ano.AnoCommNIO.e(Unknown Source)
        at oracle.net.ano.AnoComm.readUB4(Unknown Source)
        at oracle.net.ano.Ano.c(Unknown Source)
        at oracle.net.ano.Ano.negotiation(Unknown Source)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:368)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1600)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:591)
        ... 7 more
```

If you have any other questions, please let me know!

**Comment by ewie** [comment]
I experienced the same issue and solved it by providing connection property `oracle.net.disableOob=true`.

**Comment by danielthegray** [comment]
This made my showcase application pass the test with all versions of the driver! Thanks for this. I added the proposed solution to a branch on the bugsample repo: https://github.com/danielthegray/ojdbc-bugsample/tree/connection_prop_fix
where all the versions succesfully connect.

However, I believe that there must be some underlying problem that causes the need for this connection parameter. If I use a modern version of SQL*Plus (or if I use SQLCL, the new CLI tool from Oracle), they also fail to connect to the Oracle 19c Docker container. I don't think I can easily (or legally?) tweak the connection parameter of these applications.

What causes this problem and how can good behavior for this combination of Docker container + modern JDBC drivers be obtained?

**Comment by Djelibeybi** [comment]
See the last entry of the Database FAQ: https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/FAQ.md

**Comment by zappee** [comment]
How to configure this `DISABLE_OOB=ON` if I use the official `container-registry.oracle.com/database/enterprise:19.3.0.0` image?

**Comment by Djelibeybi** [comment]
> How to configure this `DISABLE_OOB=ON` if I use the official `container-registry.oracle.com/database/enterprise:19.3.0.0` image?

I have opened a new issue for your question: #1727

**Comment by santisagar** [comment]
> The Oracle 19c Docker image does not work with Version 19.3.0.0 and above of the Oracle JDBC driver, giving a strange "Got minus one from read call" for any ojdbc driver versioned at 19.3 or above.
> 
> I have prepared a small demo project which show cases the bug. I have ruled out network problems by sniffing traffic both inside and outside the Docker container, from SQL*Plus, and the traffic is the same. It might be a bug in the driver itself, but I post it here because I cannot rule out that the database container itself is not part of the problem (since Oracle 11g and 12c work fine).
> 
> The repository can be found here: https://github.com/danielthegray/ojdbc-bugsample/tree/master along with an explanatory README file.
> 
> The full error stack trace is pasted below:
> 
> ```
> java.sql.SQLRecoverableException: IO Error: Got minus one from a read call
>         at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:858)
>         at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
>         at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
>         at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
>         at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
>         at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
>         at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
>         at ojdbc.bugsample.App.main(App.java:14)
> Caused by: oracle.net.ns.NetException: Got minus one from a read call
>         at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:557)
>         at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:258)
>         at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:190)
>         at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:132)
>         at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:105)
>         at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:91)
>         at oracle.net.ano.AnoCommNIO.p(Unknown Source)
>         at oracle.net.ano.AnoCommNIO.e(Unknown Source)
>         at oracle.net.ano.AnoComm.readUB4(Unknown Source)
>         at oracle.net.ano.Ano.c(Unknown Source)
>         at oracle.net.ano.Ano.negotiation(Unknown Source)
>         at oracle.net.ns.NSProtocol.connect(NSProtocol.java:368)
>         at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1600)
>         at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:591)
>         ... 7 more
> ```
> 
> If you have any other questions, please let me know!

What is workaround for this issues?

**Comment by santisagar** [comment]
> I experienced the same issue and solved it by providing connection property `oracle.net.disableOob=true`. This property name is defined by `oracle.jdbc.OracleConnection#CONNECTION_PROPERTY_THIN_NET_DISABLE_OUT_OF_BAND_BREAK`.

Where is that property file located?

**Comment by Djelibeybi** [comment]
> Where is that property file located?

See the FAQ entry: https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/FAQ.md#ora-12637-packet-receive-failed

**Comment by ewie** [comment]
> > I experienced the same issue and solved it by providing connection property `oracle.net.disableOob=true`. This property name is defined by `oracle.jdbc.OracleConnection#CONNECTION_PROPERTY_THIN_NET_DISABLE_OUT_OF_BAND_BREAK`.
> 
> Where is that property file located?

It's a connection property which is part of the JDBC URL, e.g. `jdbc:oracle:thin:@localhost:1521/service?oracle.net.disableOob=true` according to https://docs.oracle.com/en/database/oracle/oracle-database/21/jajdb/.

I don't know if it also works via a system property in general, i.e. `-Doracle.net.disableOob=true`. But that's how SQL Developer can be configured according to https://stackoverflow.com/a/10100981.

**Comment by IshaanDesai45** [comment]
#2607  This PR includes the `DISABLE_OOB=ON` workaround which would solve this problem
