### ISSUE TITLE
docker RAC deployment on Veritas Storage

### ISSUE THREAD

**Issue by saketrp** [oracle/docker-images#1664]
Hi,

I am trying to deploy the RAC docker containers on veritas storage (database residing on a vxfs mountpoint). However, the documentation suggests the storage options as ASM or NFS. Is non-ASM storage supported for RAC? If yes, is there any documentation available for this?

**Comment by psaini79** [comment]
@saketrp 

While using VxFS is permissible, especially as RAC on Docker is currently only supported for Test and Dev environments, Oracle cannot provide best practices or guidance on how to make RAC on Docker work on VxFS. Also, support for ASM / NFS has been chosen as the default for simplicity, while ASM will likely be the initially supported configuration for production environments once offered.
