### ISSUE TITLE
oracle/database:18.4.0-xe does not exist

### ISSUE THREAD

**Issue by hantsy** [oracle/docker-images#1679]
Defined a *docker-compoes.yaml*.

```yaml
# see https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.5" # specify docker-compose version, v3.5 is compatible with docker 17.12.0+

# Define the services/containers to be run
services:
  oracledb:
    image: oracle/database:18.4.0-xe
    environment:
      - "ORACLE_PWD:test@123"
    volumes:
      - ./oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500

```

And I tried to run `docker-compose up oracledb`.

```bash
Pulling oracledb (oracle/database:18.4.0-xe)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling oracledb (oracle/database:18.4.0-xe)...

ERROR: pull access denied for oracle/database, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by hantsy** [comment]
In the docker hub, only found the enterprise database there, for writing a demo app, I do not want to download such a huge db.

**Comment by hantsy** [comment]
When building image myself, I got the error like this.

```bash
Cannot open: https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm. Skipping.
Nothing to do
```

**Comment by larmic** [comment]
@hantsy I did not found an image for oracle-xe. I build it by myself: https://hub.docker.com/r/larmic/oracle-xe.

I'm using this image for integration testing. Maybe this will help you.

I would appreciate an official image.

**Comment by gvenzl** [comment]
@hantsy, building the image works fine on my end. Do you still have this issue? Can you see whether you can reach that file in your browser?

**Comment by hantsy** [comment]
@gvenzl I have built it myself successfully.

Wrote down a note about this progress: https://github.com/hantsy/devops-sandbox/blob/master/oracle-database-18.4.0-xe.md

But personally, I hope Oracle can push the XE version to the **public** Docker hub for developers.  Adding an `ACCEPT_LICENSE` env param to the Dockerfile to accept the oracle license like what is done in MS SQLServer.

**Comment by gvenzl** [comment]
Thank you @hantsy!

Your feedback is very welcome, I will forward it to the appropriate people!

Thanks,
