### ISSUE TITLE
OracleDatabase/SingleInstance/README.md - wrong port for docker run of Express Edition

### ISSUE THREAD

**Issue by pauljereb** [oracle/docker-images#1681]
In the description of the **docker run** parameters for XE 18c it says

"Two ports are exposed: 1521 (Oracle Listener), 8080 (APEX)"

but in the example it's port **5500**

`docker run --name <container name> \
-p <host port>:1521 -p <host port>:5500 \
-e ORACLE_PWD=<your database passwords> \
-e ORACLE_CHARACTERSET=<your character set> \
-v [<host mount point>:]/opt/oracle/oradata \
oracle/database:18.4.0-xe`

**Comment by gvenzl** [comment]
Actually, that's an oversight the other way around.
18c XE no longers ships with APEX (unlike 11g XE), so it's a mistake in the ReadMe parameter as well as in the label in the Dockerfile.
