### ISSUE TITLE
Licensing of built images

### ISSUE THREAD

**Issue by ChrisJBurns** [oracle/docker-images#1687]
Currently, we have an Oracle Enterprise Edition that will be in prod with the full license. However for development we aim to try and build our own images using this repo. We have a question regarding the licensing. Could we implement the build process into our CI tool that could publish the Docker images to an internal docker registry? This saves each developer having to run the builds and downloading the binaries themselves. We won't be publishing or distributing these images publicly, just privately within our development environments.

We want to make sure that there are no licensing complications before we do this as we know Oracle are strict with regards to who can use their software and how it is distributed.

**Comment by Djelibeybi** [comment]
We are not authorised to discuss any licensing related topics via GitHub issues. In this case, please engage your Oracle account manager and request an official response.
