### ISSUE TITLE
OracleUnifiedDirectory: Instance Setup LDIF execution not using SSL

### ISSUE THREAD

**Issue by MatthiasScholzTW** [oracle/docker-images#1688]
### Brief
Using the ldif file format extension does not use an encrypted connection to run the ldapmodify command.

### Background
During the bootstrapping process of the OUD instance I would like to run some custom configuration. One step should add the `Global Administrator`. In the documentation there is a section about [Readme: Running Scripts after Setup](https://github.com/oracle/docker-images/blob/master/OracleUnifiedDirectory/README.md#running-scripts-after-setup) which describes support for shell scripts, dsconfig and ldif. Since the `Global Administrator` can be added using `ldapmodify` I assumed providing an ldif file will do the trick. Since the `Global Administrator` has to be added to the `cn=config` suffix a secured connection has to be used.

The current implementation of the execution of ldif files does not establish a secure connection. This can be achieved with adding the `--useSSL` parameter to the `ldapmodify` command.

### Possible Solutions

1. Adding support for secure connection to the ldapmodify command inside: [config_oud_instance.sh](https://github.com/oracle/docker-images/blob/117aa7987c4d8084788f979a543310bcd59ac7c0/OracleUnifiedDirectory/dockerfiles/12.2.1.3/scripts/config_oud_instance.sh#L81)
2. Introduction of additional extension `ldifs`
3. Using a complete different way

I would be open to provide an implementation which fits the intended use.

### Question

1. How should the `Global Administrator` be added?
2. Is it intended not to support encrypted connections?

### References
- [Readme: Running Scripts after Setup](https://github.com/oracle/docker-images/blob/master/OracleUnifiedDirectory/README.md#running-scripts-after-setup)
- [useSSL required for cn=config](https://stackoverflow.com/questions/17847891/how-can-i-add-an-admin-user-in-oracle-unified-directory-oud-11g-r2)

**Comment by Djelibeybi** [comment]
@oehrlis can you review this? The OUD content was provided by you. :)

**Comment by oehrlis** [comment]
Hi 

Yes I'll have look as soon as I'm back to work.

Regards Stefan

**Comment by oehrlis** [comment]
@MatthiasScholzTW the OUD configuration script [63_config_oud_instance.sh](https://github.com/oracle/docker-images/blob/117aa7987c4d8084788f979a543310bcd59ac7c0/OracleUnifiedDirectory/dockerfiles/12.2.1.4.0/scripts/63_config_oud_instance.sh) respectively [config_oud_instance.sh](https://github.com/oracle/docker-images/blob/117aa7987c4d8084788f979a543310bcd59ac7c0/OracleUnifiedDirectory/dockerfiles/12.2.1.3/scripts/config_oud_instance.sh) is based on a similar approach used for the Database Docker container. Originally I assumed that one would like to use CONF batch files, LDIF files and shell scripts. Whereby the files are used as follows:

- _.conf_ files are batch files for _dsconfig_ and will be executed using SSL and the admin port (usually 4444)
- _.ldif_ files to be loaded via _ldapmodify_ using the LDAP port (usually 1389)
- _.sh_ shell script to run any kind of shell / bash scripts.

If files with similar name but different extensions exists e.g. _04_create_root_user.conf_, _04_create_root_user.ldif_ and _04_create_root_user.sh_ only the shell script will be executed. I do use this to setup enhanced used cases. See the [setup](https://github.com/oehrlis/doe/tree/master/eus/oud/setup) scripts to configure an OUD instance for EUS in my repo for Docker based Oracle engineering ([oehrlis/doe](https://github.com/oehrlis/doe)). This way, you could also add / configure a global admin. The script [04_create_root_user.sh](https://github.com/oehrlis/doe/blob/master/eus/oud/setup/04_create_root_user.sh) for example creates root users via ldapmodify, ssl and the admin port.

In regard to your questions:
1. You may use the same approach as mentioned above to create global users or any other configuration which requires LDAPS and/or the admin connection
2. No, it was just not required initially.

I came across another use case where I set up OUD without an LDAP port, just LDAPS. Of course this does not work with the LDIF file either. I any way planned to update the OUD Docker build scripts. Therefor I can add support for LDIFS aka LDIF with SSL support. 

On the other hand, I would be grateful if you could check if the above described method with the shell script is a possible solution for you.

**Comment by MatthiasScholzTW** [comment]
Thanks a lot for your feedback and very valuable input!
Let me come back to this issue once I tried the approach you suggest.
