### ISSUE TITLE
buildDockerImage.sh not passing build-arg correctly for proxy

### ISSUE THREAD

**Issue by willievu** [oracle/docker-images#169]
The syntax for --build-arg is

`--build-arg name=value`

buildDockerImage.sh generates something like this for proxy settings:

`--build-arg="http_proxy=<url>"`

The code fragment for proxy settings needs to be changed to the following:

```
# Proxy settings
PROXY_SETTINGS=""
if [ "${http_proxy}" != "" ]; then
  PROXY_SETTINGS="$PROXY_SETTINGS --build-arg http_proxy=${http_proxy}"
fi

if [ "${https_proxy}" != "" ]; then
  PROXY_SETTINGS="$PROXY_SETTINGS --build-arg https_proxy=${https_proxy}"
fi

if [ "${ftp_proxy}" != "" ]; then
  PROXY_SETTINGS="$PROXY_SETTINGS --build-arg ftp_proxy=${ftp_proxy}"
fi

if [ "${no_proxy}" != "" ]; then
  PROXY_SETTINGS="$PROXY_SETTINGS --build-arg no_proxy=${no_proxy}"
fi

if [ "$PROXY_SETTINGS" != "" ]; then
  echo "Proxy settings were found and will be used during build."
fi
```

I'm using Docker Version: 1.12.1

**Comment by brunoborges** [comment]
Which  `buildDockerImage.sh` are you refering to?

**Comment by gvenzl** [comment]
They are all wrong for:

- OracleDatabase
- OracleHTTPServer
- OracleWeblogic

The rest of them don't pass on proxy settings.
