### ISSUE TITLE
Running /opt/oracle/scripts/setup as different user

### ISSUE THREAD

**Issue by tremkonzah** [oracle/docker-images#1690]
Hello,

How can i run /opt/oracle/scripts/setup as different users? 

e.g i have two .sql, first create user and schema and i want to use user from first script to create table in second .sql 

If i check run script function, it run as sysdba

```function runUserScripts {

  SCRIPTS_ROOT="$1";

  # Check whether parameter has been passed on
  if [ -z "$SCRIPTS_ROOT" ]; then
    echo "$0: No SCRIPTS_ROOT passed on, no scripts will be run";
    exit 1;
  fi;
  
  # Execute custom provided files (only if directory exists and has files in it)
  if [ -d "$SCRIPTS_ROOT" ] && [ -n "$(ls -A $SCRIPTS_ROOT)" ]; then
      
    echo "";
    echo "Executing user defined scripts"
  
    for f in $SCRIPTS_ROOT/*; do
        case "$f" in
            *.sh)     echo "$0: running $f"; . "$f" ;;
            *.sql)    echo "$0: running $f"; echo "exit" | su -p oracle -c "$ORACLE_HOME/bin/sqlplus / as sysdba @$f"; echo ;;
            *)        echo "$0: ignoring $f" ;;
        esac
        echo "";
    done
    
    echo "DONE: Executing user defined scripts"
    echo "";
  
  fi;
  
}
```

How to use sysdba for first .sql and use different user for second .sql?

thanks

**Comment by zunurain222** [comment]
Hi everyone,

I have encountered the same issue as well. One thing I noticed is due to lack of memory. I am running docker on Windows 10 with WSL2. After setting the RAM to be 4GB (previously 2GB), the issue was resolved. I hope that helps

**Comment by gvenzl** [comment]
You could either 

a) just pack your SQL*Plus invocation into a shell script instead:

```bash
su -p oracle -c "$ORACLE_HOME/bin/sqlplus <your user>/<your password>@//localhost:1521/<your PDB> @<your file>"
```

b) put a [`connect`](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqpug/CONNECT.html#GUID-47249D66-7ED9-48BE-9C79-CE250ABB88B8) instruction into the sql script:

```sql
connect <your user>/<your password>@//localhost:1521/<your PDB>
...
...
...
```
