### ISSUE TITLE
Need for multiple diskgroups

### ISSUE THREAD

**Issue by susaine** [oracle/docker-images#1691]
Hey guys,

I have a requirement for using multiple diskgroups which i am able to do via create diskgroup command after the initial setup. But wanted to check if thats possible via initial setup, i mean while i create the racnodes.
Thanks

**Comment by psaini79** [comment]
@susaine 

Yes, this is possible. We need to run a custom script which basically can use asmca and complete the new disk group creation.

**Comment by psaini79** [comment]
Create all the required shell script with the extension *.sh which you want to run after Grid deployment but before DB creation. Stage them in a dir "/custom_scripts/grid" change the script permissions to 755 and  mount it to the container using volume and pass the following parameters:

```
--volume /custom_scripts/grid:/custom_scripts/grid \
-e GRID_SCRIPT_ROOT = /custom_scripts/grid \
<...Rest of the container creation command>
```
