### ISSUE TITLE
kernel-headers-3.10.0-1127.19.1.el7 - Package does not match intended download

### ISSUE THREAD

**Issue by catam1976** [oracle/docker-images#1693]
Building Docker image for 12.1.0.2-se2, I've encountered this error:

https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/kernel-headers-3.10.0-1127.19.1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ol7_latest clean metadata
Trying other mirror.

Error downloading packages:
  kernel-headers-3.10.0-1127.19.1.el7.x86_64: [Errno 256] No more mirrors to try.

This was working fine before August 2020.

**Comment by europemaster** [comment]
I can confirm that I have the same error.

Running the suggested command did not help.

**Comment by barrynorman** [comment]
Same here.
There was a package update on the 20th. Might be the problem?!

**Comment by InfectoOne** [comment]
Same here. I have tried adding the following command to the `Dockerfile` (as suggested):
`RUN run yum --enablerepo=ol7_latest clean metadata`

Unfortunately, that made no difference.

**Comment by catam1976** [comment]
I've changed the setupLinuxEnv.sh from 12.1.0.2 by adding 

yum -y install kernel-headers && \

before 

yum -y install oracle-rdbms-server-12cR1-preinstall tar openssl && \

And the build fails with that 'yum -y install kernel-headers'. I am not a Linux expert but it looks like that package is wrong.

**Comment by ltamaster** [comment]
This worked for me 
<img width="565" alt="Screen Shot 2020-08-24 at 10 44 16" src="https://user-images.githubusercontent.com/6034968/91058708-c9e27b00-e5f6-11ea-9b33-f87218d5d719.png">

**Comment by barrynorman** [comment]
> This worked for me
> <img alt="Screen Shot 2020-08-24 at 10 44 16" width="565" src="https://user-images.githubusercontent.com/6034968/91058708-c9e27b00-e5f6-11ea-9b33-f87218d5d719.png">

Thanks. Just this line? 
`yum --enablerepo=ol7_latest clean metadata`

Unfortunately I still get the same error.

**Comment by sappysaplala** [comment]
> > This worked for me
> > <img alt="Screen Shot 2020-08-24 at 10 44 16" width="565" src="https://user-images.githubusercontent.com/6034968/91058708-c9e27b00-e5f6-11ea-9b33-f87218d5d719.png">
> 
> Thanks. Just this line?
> `yum --enablerepo=ol7_latest clean metadata`
> 
> Unfortunately I still get the same error.
> I can see the output from the command...
> 
> ```
> Cleaning repos: ol7_latest
> 0 metadata files removed
> 0 sqlite files removed
> 0 metadata files removed
> ```

I purged all the images created then reran the operation with the changes to the setupLinuxEnv.sh.  Worked already.

**Comment by barrynorman** [comment]
@sappysaplala I forgot to delete all the images. Now it works.
Thanks!

**Comment by Djelibeybi** [comment]
Hey folks, we had to republish the `kernel-3.10.0-1127.19.1` and all of its associated packages and it took a while for the metadata to sync accordingly. This is not a Docker issue, but something the yum.oracle.com team are taking care of. It should all be back up and running again ASAP.
