### ISSUE TITLE
enterprise:12.1.0.2 and enterprise:12.2.0.1 images are not compatible

### ISSUE THREAD

**Issue by zappee** [oracle/docker-images#1694]
I must use the partitioning feature because my production SQL scripts contain partitioning related lines. Unfortunately, your `enterprise:12.2.0.1` image does not contain this feature which is so bad because its name suggests that this is an enterprise image.

Anyway, I have read on the internet that the `enterprise:12.1.0.2` image has the partitioning feature enabled. So I pulled this image from dockerhub and I changed my `docker-compose.yml`:

Original configuration: `image: store/oracle/database-enterprise:12.2.0.1`
New setting: `image: store/oracle/database-enterprise:12.1.0.2`

Unfortunately, the `v12.1.0.2` image is not compatible with the `v12.2.0.1` image. I do not know what is the difference between these two but my docker environment just stopped working with the 12.1.0.2 image. I do not have time to play with this issue, I want to use oracle docker image as a black box product, I do not care how it was installed, I just want to use it. But the mentioned two images are not compatible with each other.

Because my docker scripts only work with v12.2.0.1 BUT this version does not support partitioning, I need to modify the original, production SQL files. This is so bad...

Are you planning to release a v12.2.0.1 image with partitioning feature as it was asked [here](https://github.com/oracle/docker-images/issues/685)?

Many people are waiting for this image.

_ps. I understand that the image size will be bigger with this feature and the docker startup time will take longer with this feature but this is still better than modifying the original company's SQLs._

**Comment by gvenzl** [comment]
Hi @zappee,

Please use the latest [`container-registry.oracle.com/database/enterprise:19.3.0.0`](https://container-registry.oracle.com/pls/apex/f?p=113:4:12558865788584:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:9,9,Oracle%20Database%20Enterprise%20Edition,Oracle%20Database%20Enterprise%20Edition,1,0&cs=3f6pKaXflipSqI21sj72bZEWUwGjMFkFXR6Yj45zoN_tBn0Pzkx7y9kyTpF8CvgFExvD29Wb1A4XuMI84EDNnPw) image that does support partitioning and provides you with the latest and long-term support version of Oracle Database.

As of now, we are not planning on refreshing the 12.2.0.1 or 12.1.0.2 images.

**Comment by zappee** [comment]
Thx!
