### ISSUE TITLE
Weblogic exception : javax.naming.NameNotFoundException: Unable to resolve 'jdbc.payment'. Resolved 'jdbc'; remaining name 'payment'

### ISSUE THREAD

**Issue by shady-ragab1** [oracle/docker-images#1703]
I have this exception when I lookup jndi datasource from weblogic from spring boot application...only after one successful deployment...I mean from the second deployment on.If I restart the container, it will work fine for the first deployment only.

Caused by: javax.naming.NameNotFoundException: Unable to resolve 'jdbc.payment'. Resolved 'jdbc'; remaining name 'payment'

the datasource with the same name and attached to the admin server.

I use docker image : store/oracle/weblogic:12.2.1.4-dev with environment variable PRODUCTION_MODE=dev

update : if I deattach the data source from the server then reattche it again then start the war, It runs successfully for one time again

**Comment by Djelibeybi** [comment]
Is this still an issue?

**Comment by mriccell** [comment]
The store image is old, please either build the image from this project or pull from container-registry.oracle.com/middleware/weblogic:12.2.1.4.  Where is the domain configuration in a volume or inside the image?
