### ISSUE TITLE
Oracle Instant client 19.3  image upgradation to support oraclelinux:8.2

### ISSUE THREAD

**Issue by arpana-g** [oracle/docker-images#1704]
Currently the Oracle instant client 19.3 image supports oraclelinux:7-slim and in the README section also details of the el7 package is mentioned .As oraclelinux:8.2 is released and current image do not support this latest version..So do you plan to release oracle instant client image based on oraclelinux:8.2? if so when do you plan to release the image.

**Comment by Djelibeybi** [comment]
Currently, there is no Instant Client available for Oracle Linux 8. I'm assigning this to @cjbj on the Instant Client team because they will need to release the client first before the image can be rebased to a newer Oracle Linux version.

**Comment by cjbj** [comment]
You can use the OL7 19c Instant Client on OL8, you just need to install the `libnsl` package manually.  Getting the simple RPM spec file change for this into the DB 19 release update cycle has been 'interesting'.  

Luckily, when the next major DB version is released, you won't need `libnsl` at all.

**Comment by arpana-g** [comment]
I intend to install oracle-instant-client-19.3 on rhel 8.2 by using the official Dockerfile of oracle instant client .I have analysed that below line should be removed when we consider oraclelinux:8.2 as base image 
`yum -y install oracle-release-el7 && yum-config-manager --enable ol7_oracle_instantclient`

Below Error reported even though we install libns: 
No match for argument: oracle-release-el7 Error: Unable to find a match: oracle-release-el7

The Dockerfile which works with oraclelinux:8.2 looks like this :
FROM oraclelinux:8.2
 
 
ARG release=19 
ARG update=3 
ARG FILES_REPOSITORY_URL=http://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/getPackage/
ARG rpmversion=19.3.0.0.0-1.x86_64.rpm

 # Uncomment if the tools package is added 
#ENV PATH=$PATH:/usr/lib/oracle/${release}.${update}/client64/bin


RUN   yum -y install tar libnsl ${FILES_REPOSITORY_URL}/oracle-instantclient${release}.${update}-basic-${rpmversion} ${FILES_REPOSITORY_URL}/oracle-instantclient${release}.${update}-devel-${rpmversion} ${FILES_REPOSITORY_URL}/oracle-instantclient${release}.${update}-sqlplus-${rpmversion} 


CMD ["sqlplus", "-v"]

As per the above  implementation the official Dockerfile of oracle-instant-client needs to be updated to support oraclelinux:8.2.

**Comment by Djelibeybi** [comment]
As I mentioned earlier, we will not be updating the official Dockerfiles until the Instant Client packages are released for OL8 along with the release RPM to enable the repo. Once those are available, then the image can be updated.
