### ISSUE TITLE
Rename "charts" to "helm-charts"

### ISSUE THREAD

**Issue by gvenzl** [oracle/docker-images#1708]
For visibility reasons, we should rename  
`https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/charts`  
to  
`https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/helm-charts`

Furthermore, it makes sense to have a very short section in the `https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md` to refer to that folder and what it's purpose is.

**Comment by mark-au** [comment]
Related: https://github.com/oracle/docker-images/issues/1042
