### ISSUE TITLE
Replacing the current OracleUnifiedDirectory content with the Oracle authored version

### ISSUE THREAD

**Issue by Djelibeybi** [oracle/docker-images#1720]
First, many thanks to @oehrlis who submitted the current `OracleUnifiedDirectory` content and samples to this repo.

There are going to be two pull requests for OUD:

- [x] I am going to move the existing content into a `contrib` folder, so that it remains available to existing users.

- [x]  The Oracle Middleware team will submit Oracle authored content that will become the officially supported version.

I will assign this issue to myself and keep it open until both PRs are submitted and merged.

**Comment by oehrlis** [comment]
Hi

I was just wondering if it is still desired that I update the OUD content under `contrib` or should it stay as it is. I currently planned to continue my OUD config and support the official Oracle supported version. The main source of my OUD configuration is in my repository anyway [oehrlis/docker](https://github.com/oehrlis/docker/tree/master/OracleOUD).

Regards Stefan

**Comment by Djelibeybi** [comment]
If you have updates, please do continue to submit them.

**Comment by Djelibeybi** [comment]
Oracle official content submitted as #1734 .

**Comment by rishiagarwal-oracle** [comment]
@Djelibeybi we can close this issue? both the steps are now complete

**Comment by Djelibeybi** [comment]
Yep, we can.
