### ISSUE TITLE
Cannot locate libclntsh.so

### ISSUE THREAD

**Issue by dry4ng** [oracle/docker-images#1725]
Trying to run python in `oraclelinux8-python:3.8` container. Getting an error:

`DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help`

Using cx_Oracle==8.0.1

**Comment by dry4ng** [comment]
Solved by using appropriate image: `oraclelinux7-python:3.6-oracledb`

**Comment by Djelibeybi** [comment]
Re-opening to verify that the `oraclelinux8-python:3.8` container image works as expected. If not, this issue serves as a trigger to resolve it.

**Comment by Djelibeybi** [comment]
And it helps to read the issue first. :) The `oraclelinux8` variants don't include the Oracle Instant Client, so `cx_Oracle` doesn't work, as you've discovered. Closing the bug again.

**Comment by cjbj** [comment]
Workaround for OL8: manually install the Instant Client Basic package from [here](https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html) and manually install the libnsl package.
