### ISSUE TITLE
How to configure DISABLE_OOB=ON with the official database/enterprise:19.3.0.0 image?

### ISSUE THREAD

**Issue by Djelibeybi** [oracle/docker-images#1727]
How to configure this `DISABLE_OOB=ON` if I use the official `container-registry.oracle.com/database/enterprise:19.3.0.0` image?

_Originally posted by @zappee in https://github.com/oracle/docker-images/issues/1663#issuecomment-702265270_

**Comment by cjbj** [comment]
It's a client side setting.

**Comment by zappee** [comment]
I see. That was my mistake. Thanks.

**Comment by Djelibeybi** [comment]
This appears to be resolved now too.

**Comment by IshaanDesai45** [comment]
#2607  This PR includes the `DISABLE_OOB=ON` workaround which would solve this problem
