### ISSUE TITLE
 Provide an official GraalVM image that has `native-image` pre-installed.

### ISSUE THREAD

**Issue by Djelibeybi** [oracle/docker-images#1729]
> I'm wondering whether you guys would consider providing an official Docker image that has `native-image` pre-installed.

> At Micronaut we use `oracle/graalvm-ce:$tag` a lot, and have to always run `gu install native-image`. It'll save time for users if it would come pre-installed.

_Originally posted by @alvarosanchez in https://github.com/oracle/docker-images/issues/1276#issuecomment-705386688_

**Comment by aboullaite** [comment]
I can help on this one! should the PR be sent here or to the [new GraalVM images](https://github.com/graalvm/container/tree/master/community) repo ?

**Comment by Djelibeybi** [comment]
It would go into the new GraalVM repo as we no longer house the `Dockerfile`s for GraalVM here.

**Comment by mzachh** [comment]
Hi Mohammed,

thanks for your contribution, we will follow up on the new repo. Closing this issue ...
