### ISSUE TITLE
Oracle 19c does not start because of memory configuration

### ISSUE THREAD

**Issue by piotrekfus91** [oracle/docker-images#1730]
Hi,

I try to use Oracle 19c Docker image built using provided in this repository steps. The image is built correctly - works on my machine very well. But when I tried to run it on our Jenkins machine, I could not start it. I can find the following errors in Docker logs:
```
db_1        | SQL*Plus: Release 19.0.0.0.0 - Production on Pt Paź 9 07:28:47 2020
db_1        | Version 19.3.0.0.0
db_1        |
db_1        | Copyright (c) 1982, 2019, Oracle.  All rights reserved.
db_1        |
db_1        | Połączono z nieaktywną instancją.
db_1        |
db_1        | SQL> ORA-27104: system-defined limits for shared memory was misconfigured
db_1        | SQL> Rozłączono
db_1        | The Oracle base remains unchanged with value /opt/oracle
db_1        | #####################################
db_1        | ########### E R R O R ###############
db_1        | DATABASE SETUP WAS NOT SUCCESSFUL!
db_1        | Please check output for further info!
db_1        | ########### E R R O R ###############
db_1        | #####################################
db_1        | The following output is now a tail of the alert.log:
db_1        | 2020-08-11T13:49:43.364359+00:00
db_1        | Instance shutdown complete (OS id: 3796)
db_1        | 2020-10-09T07:28:49.300197+02:00
db_1        | Starting ORACLE instance (normal) (OS id: 32)
db_1        | 2020-10-09T07:28:49.353273+02:00
db_1        | System cannot support SGA size of 9536 MB.
db_1        | 2020-10-09T07:28:49.353373+02:00
db_1        | Total system memory configured is 10 GB.
db_1        | 2020-10-09T07:28:49.353463+02:00
db_1        | Instance maximum shared memory size should be less than 9023 MB.
```
I couldn't find any information how to configure this memory. Any hints?

**Comment by yunus-qureshi** [comment]
@piotrekfus91 
do you have any container memory limits set? What's the physical memory on the node?

**Comment by piotrekfus91** [comment]
@yunus-qureshi thanks for your reply! I do not have container memory limits. On this node I have 8GB of RAM.

**Comment by yunus-qureshi** [comment]
@piotrekfus91 are you sure? The logs seems to say otherwise

db_1        | System cannot support SGA size of 9536 MB.
db_1        | 2020-10-09T07:28:49.353373+02:00
db_1        | Total system memory configured is 10 GB.

**Comment by piotrekfus91** [comment]
Right. We have 5 Jenkins machines, I check on one only. To be honest, htop on each machine says:
* 8GB
* 8,8GB
* 12GB
* 9,7GB
Given log is from a machine having 9,7GB.

**Comment by yunus-qureshi** [comment]
@piotrekfus91 

Plz paste the output of "docker info"  on the failing node

**Comment by piotrekfus91** [comment]
@yunus-qureshi here we go:
```Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 111
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 438
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 9.79 GiB
Name: p4esb-jenkins-slave4
ID: BSFP:ZKR4:TWYM:6I3R:XAKZ:6H62:WTY5:NSD4:DDDM:TG5C:B2L3:7J6H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: toukjenkins
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://docker-registry-cache.touk.pl/
Live Restore Enabled: false
```

**Comment by yunus-qureshi** [comment]
@piotrekfus91 
Thanks there is something wrong with DBCA memory calculation. Will you able get inside the container and get all the logs under /opt/oracle/cfgtoollogs and attach as tar ball

**Comment by piotrekfus91** [comment]
@yunus-qureshi thanks for a quick reply! Please, find logs attached.
[cfgtoollogs.tar.gz](https://github.com/oracle/docker-images/files/5369293/cfgtoollogs.tar.gz)

**Comment by yunus-qureshi** [comment]
@piotrekfus91 

The attached logs indicate DB creation is successful

[ 2020-08-11 13:25:50.729 UTC ] Prepare for db operation
DBCA_PROGRESS : 8%
[ 2020-08-11 13:25:50.793 UTC ] Copying database files
DBCA_PROGRESS : 31%
[ 2020-08-11 13:27:20.624 UTC ] Creating and starting Oracle instance
DBCA_PROGRESS : 32%
DBCA_PROGRESS : 36%
DBCA_PROGRESS : 40%
DBCA_PROGRESS : 43%
DBCA_PROGRESS : 46%
[ 2020-08-11 13:35:47.655 UTC ] Completing Database Creation
DBCA_PROGRESS : 51%
DBCA_PROGRESS : 54%
[ 2020-08-11 13:43:17.050 UTC ] Creating Pluggable Databases
DBCA_PROGRESS : 58%
DBCA_PROGRESS : 77%
[ 2020-08-11 13:43:27.519 UTC ] Executing Post Configuration Actions
DBCA_PROGRESS : 100%
[ 2020-08-11 13:43:27.520 UTC ] Database creation complete. For details check the logfiles at:
 /opt/oracle/cfgtoollogs/dbca/ORCL.
Database Information:
Global Database Name:ORCL
System Identifier(SID):ORCL

**Comment by piotrekfus91** [comment]
@yunus-qureshi It is from failed instance. I checked again:
```docker run -it -e NLS_LANG=POLISH_POLAND.UTF8 -e TZ=Europe/Warsaw docker.touk.pl/integracja/oracle-database:19.3.0-ee
[.....]
SQL> ORA-27104: system-defined limits for shared memory was misconfigured
SQL> Rozłączono
The Oracle base remains unchanged with value /opt/oracle
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
2020-08-11T13:49:43.364359+00:00
Instance shutdown complete (OS id: 3796)
2020-10-13T12:31:26.173526+02:00
Starting ORACLE instance (normal) (OS id: 32)
2020-10-13T12:31:26.177366+02:00
System cannot support SGA size of 9536 MB.
2020-10-13T12:31:26.177426+02:00
Total system memory configured is 10 GB.
2020-10-13T12:31:26.177483+02:00
Instance maximum shared memory size should be less than 9023 MB.
```
I left this terminal window as-is. Using the other one I did:
```jenkins@p4esb-jenkins-slave4:~$ docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                             PORTS               NAMES
beca65a17a74        docker.touk.pl/integracja/oracle-database:19.3.0-ee   "/bin/sh -c 'exec ..."   48 seconds ago      Up 47 seconds (health: starting)   1521/tcp            zen_galileo
jenkins@p4esb-jenkins-slave4:~$ docker exec -it beca bash
[oracle@beca65a17a74 ~]$ cat /opt/oracle/cfgtoollogs/dbca/ORCL/ORCL.log
[ 2020-08-11 13:25:49.469 UTC ] [WARNING] [DBT-06208] The 'SYS' password entered does not conform to the Oracle recommended standards.
[ 2020-08-11 13:25:49.469 UTC ] [WARNING] [DBT-06208] The 'SYSTEM' password entered does not conform to the Oracle recommended standards.
[ 2020-08-11 13:25:49.469 UTC ] [WARNING] [DBT-06208] The 'PDBADMIN' password entered does not conform to the Oracle recommended standards.
[ 2020-08-11 13:25:50.729 UTC ] Prepare for db operation
DBCA_PROGRESS : 8%
[ 2020-08-11 13:25:50.793 UTC ] Copying database files
DBCA_PROGRESS : 31%
[ 2020-08-11 13:27:20.624 UTC ] Creating and starting Oracle instance
DBCA_PROGRESS : 32%
DBCA_PROGRESS : 36%
DBCA_PROGRESS : 40%
DBCA_PROGRESS : 43%
DBCA_PROGRESS : 46%
[ 2020-08-11 13:35:47.655 UTC ] Completing Database Creation
DBCA_PROGRESS : 51%
DBCA_PROGRESS : 54%
[ 2020-08-11 13:43:17.050 UTC ] Creating Pluggable Databases
DBCA_PROGRESS : 58%
DBCA_PROGRESS : 77%
[ 2020-08-11 13:43:27.519 UTC ] Executing Post Configuration Actions
DBCA_PROGRESS : 100%
[ 2020-08-11 13:43:27.520 UTC ] Database creation complete. For details check the logfiles at:
 /opt/oracle/cfgtoollogs/dbca/ORCL.
Database Information:
Global Database Name:ORCL
System Identifier(SID):ORCL
```

**Comment by yunus-qureshi** [comment]
@piotrekfus91 

Please  paste the output of the following commands from the failing node

1.  /sbin/sysctl -a | grep kernel.shm
2. docker logs beca65a17a74

**Comment by piotrekfus91** [comment]
@yunus-qureshi here we go:
docker logs
```ORACLE EDITION: ENTERPRISE

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 14-PAŹ-2020 07:39:37

Copyright (c) 1991, 2019, Oracle.  All rights reserved.

Uruchamianie /opt/oracle/product/19c/dbhome_1/bin/tnslsnr: proszę czekać...

TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Plik parametrów systemowych jest /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Komunikaty dziennika zapisano do /opt/oracle/diag/tnslsnr/752540e60bed/listener/alert/log.xml
Nasłuch na: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Nasłuch na: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Łączenie z (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STAN NASŁUCHU
------------------------
Alias                    LISTENER
Wersja                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Data rozpoczęcia        14-PAŹ-2020 07:39:38
Czas działania                    0 dni 0 h 0 min. 0 s
Poziom śladu            off
Zabezpieczenie          ON: Local OS Authentication
SNMP                      OFF
Plik parametrów nasłuchu   /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Plik dziennika nasłuchu /opt/oracle/diag/tnslsnr/752540e60bed/listener/alert/log.xml
Nasłuch punktów końcowych - podsumowanie...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
Nasłuch nie zapewnia usług
Polecenie zakończone powodzeniem

SQL*Plus: Release 19.0.0.0.0 - Production on Śr Paź 14 07:39:38 2020
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Połączono z nieaktywną instancją.

SQL> ORA-27104: system-defined limits for shared memory was misconfigured
SQL> Rozłączono
The Oracle base remains unchanged with value /opt/oracle
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
2020-08-11T13:49:43.364359+00:00
Instance shutdown complete (OS id: 3796)
2020-10-14T07:39:39.435064+02:00
Starting ORACLE instance (normal) (OS id: 32)
2020-10-14T07:39:39.438335+02:00
System cannot support SGA size of 9536 MB.
2020-10-14T07:39:39.438392+02:00
Total system memory configured is 10 GB.
2020-10-14T07:39:39.438445+02:00
Instance maximum shared memory size should be less than 9023 MB.
```
```jenkins@p4esb-jenkins-slave4:~$ sudo /sbin/sysctl -a | grep kernel.shm
kernel.shm_next_id = -1
kernel.shm_rmid_forced = 0
kernel.shmall = 18446744073692774399
kernel.shmmax = 18446744073692774399
kernel.shmmni = 4096
```

**Comment by yunus-qureshi** [comment]
@piotrekfus91 looks like your shm settings are incorrect. shmall and shmmax can't be same

Set shmmax to approx 50% of physical memory (From DBCA logs seems like your node has approx 32 GB)
so
shmmax=17179869184  (16 G * 1024 * 1024 * 1024)
shmall=41944304      (shmmax/4096)

Can you plz fix shm settings and retry

**Comment by piotrekfus91** [comment]
@yunus-qureshi How did you get 32GB? Every method I did show it like 10GB (I checked using htop, free, /proc/meminfo).
I changed this parameters (on the docker host machine) to values:
```jenkins@p4esb-jenkins-slave4:~$ sudo sysctl kernel.shmmax=4294967296
kernel.shmmax = 4294967296
jenkins@p4esb-jenkins-slave4:~$ sudo sysctl kernel.shmall=1048576
kernel.shmall = 1048576
```
And still the result is the same. I counted it as 4GB of shmmax, and 4GB/4096 for shmall. Just to be on the safe side - I also checked your values, but to na avail - same error.

**Comment by piotrekfus91** [comment]
Moreover, the same values of memory I have on my local machine on which this image works correctly. Two of my colleagues also have the same values. It is default value in linux kernel: https://github.com/torvalds/linux/blob/master/include/uapi/linux/shm.h#L23

**Comment by yunus-qureshi** [comment]
@piotrekfus91 @noeldcosta 

Ok I think I understand the problem here. The DB is initially created on a node  (with 32 Gig memory from DBCA logs) SGA/PGA are calculated based on this and stored in spfile in the data volumes. If you are copying/moving around this data volume to other  nodes, please make sure the newer nodes are of higher memory config if not the same.  You can't create the DB on high config node and move it lower config nodes.

**Comment by piotrekfus91** [comment]
Yes, this makes sense. I created this image on a machine having 32GB of RAM. Is there any option to limit this memory while creating image or should I find the worst machine we have? :)

**Comment by yunus-qureshi** [comment]
@piotrekfus91 

We are working on exactly the same enhancement. For now to get past this issue, please do the following

1. Clone this repo
2. Comment out lines 40 through 42 
docker-images/OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh
3. Rebuild the image 

Use this image for your deployments across nodes.

**Comment by piotrekfus91** [comment]
@yunus-qureshi it works :) It is good as a workaround, but, to be honest, original version is a bit on the contrary to Docker nature - where once built image should work everywhere in the same manner. Especially if building process of this image is so complecated and can be run every time we want to start a container.
@noeldcosta Thanks for sharing your experience!
Should we close this issure?

**Comment by noeldcosta** [comment]
@yunus-qureshi could you link the enhancement request to this issue? It would be good to provide an option via an environment variable to allow the user to choose whether they want automatic calculation for SGA/PGA or want a fixed size for portability (default, since expectation with Docker is to be portable).

**Comment by yunus-qureshi** [comment]
@piotrekfus91 @noeldcosta 

This is the PR that will allow you to pass memory config without having to rebuild the image with the above workaround.

https://github.com/oracle/docker-images/pull/1742

The PR is merged
