### ISSUE TITLE
SSH check failed while executing docker logs -f racnode1

### ISSUE THREAD

**Issue by Shreyashirwadkar** [oracle/docker-images#1731]
10-09-2020 07:36:04 UTC :  : SCAN_IP name is 172.16.1.70
10-09-2020 07:36:04 UTC :  : RAC Node PRIV IP is set to 10.209.117.83 
10-09-2020 07:36:04 UTC :  : RAC Node private hostname is set to racnode1
10-09-2020 07:36:04 UTC :  : CMAN_HOSTNAME name is racnode-cman1
10-09-2020 07:36:04 UTC :  : CMAN_IP name is 172.16.1.15
10-09-2020 07:36:04 UTC :  : Cluster Name is not defined
10-09-2020 07:36:04 UTC :  : Cluster name is set to 'racnode-c'
10-09-2020 07:36:04 UTC :  : Password is empty string
10-09-2020 07:36:04 UTC :  : Common OS Password string is set for Grid user
10-09-2020 07:36:04 UTC :  : Common OS Password string is set for  Oracle user
10-09-2020 07:36:04 UTC :  : Common OS Password string is set for Oracle Database
10-09-2020 07:36:04 UTC :  : Setting CONFIGURE_GNS to false
10-09-2020 07:36:04 UTC :  : GRID_RESPONSE_FILE env variable set to empty. configGrid.sh will use standard cluster responsefile
10-09-2020 07:36:04 UTC :  : Location for User script SCRIPT_ROOT set to /common_scripts
10-09-2020 07:36:04 UTC :  : IGNORE_CVU_CHECKS is set to true
10-09-2020 07:36:04 UTC :  : Oracle SID is set to ORCLCDB
10-09-2020 07:36:04 UTC :  : Oracle PDB name is set to ORCLPDB
10-09-2020 07:36:04 UTC :  : Check passed for network card eth0 for public IP 10.209.117.83
10-09-2020 07:36:04 UTC :  : Public Netmask : 255.255.255.0
10-09-2020 07:36:05 UTC :  : Check passed for network card eth0 for private IP 10.209.117.83
10-09-2020 07:36:05 UTC :  : Building NETWORK_STRING to set  networkInterfaceList in Grid Response File
10-09-2020 07:36:05 UTC :  : Network InterfaceList  set to eth0:10.209.117.0:1
10-09-2020 07:36:05 UTC :  : Setting random password for grid user
10-09-2020 07:36:05 UTC :  : Setting random password for oracle user
10-09-2020 07:36:05 UTC :  : Calling setupSSH function
10-09-2020 07:36:05 UTC :  : SSh will be setup among racnode1 nodes
10-09-2020 07:36:05 UTC :  : Running SSH setup for grid user between nodes racnode1
10-09-2020 07:36:38 UTC :  : Running SSH setup for oracle user between nodes racnode1
10-09-2020 07:36:44 UTC : : SSH check failed for the grid@racnode1! Error occurred during SSH setup
10-09-2020 07:36:44 UTC : : Error has occurred in Grid Setup, Please verify!

**Comment by psaini79** [comment]
@Shreyashirwadkar 

Please share the following from docker host:
* docker info
* rpm -qa | grep docker
* uname -r 
* systemctl status firewalld
* getenforce

**Comment by mark-au** [comment]
Being worked in duplicate #1732
