### ISSUE TITLE
SSH check failed while executing racnode1 logs

### ISSUE THREAD

**Issue by Shreyashirwadkar** [oracle/docker-images#1732]
10-09-2020 07:36:04 UTC :  : SCAN_IP name is 172.16.1.70
10-09-2020 07:36:04 UTC :  : RAC Node PRIV IP is set to 10.209.117.83 
10-09-2020 07:36:04 UTC :  : RAC Node private hostname is set to racnode1
10-09-2020 07:36:04 UTC :  : CMAN_HOSTNAME name is racnode-cman1
10-09-2020 07:36:04 UTC :  : CMAN_IP name is 172.16.1.15
10-09-2020 07:36:04 UTC :  : Cluster Name is not defined
10-09-2020 07:36:04 UTC :  : Cluster name is set to 'racnode-c'
10-09-2020 07:36:04 UTC :  : Password is empty string
10-09-2020 07:36:04 UTC :  : Common OS Password string is set for Grid user
10-09-2020 07:36:04 UTC :  : Common OS Password string is set for  Oracle user
10-09-2020 07:36:04 UTC :  : Common OS Password string is set for Oracle Database
10-09-2020 07:36:04 UTC :  : Setting CONFIGURE_GNS to false
10-09-2020 07:36:04 UTC :  : GRID_RESPONSE_FILE env variable set to empty. configGrid.sh will use standard cluster responsefile
10-09-2020 07:36:04 UTC :  : Location for User script SCRIPT_ROOT set to /common_scripts
10-09-2020 07:36:04 UTC :  : IGNORE_CVU_CHECKS is set to true
10-09-2020 07:36:04 UTC :  : Oracle SID is set to ORCLCDB
10-09-2020 07:36:04 UTC :  : Oracle PDB name is set to ORCLPDB
10-09-2020 07:36:04 UTC :  : Check passed for network card eth0 for public IP 10.209.117.83
10-09-2020 07:36:04 UTC :  : Public Netmask : 255.255.255.0
10-09-2020 07:36:05 UTC :  : Check passed for network card eth0 for private IP 10.209.117.83
10-09-2020 07:36:05 UTC :  : Building NETWORK_STRING to set  networkInterfaceList in Grid Response File
10-09-2020 07:36:05 UTC :  : Network InterfaceList  set to eth0:10.209.117.0:1
10-09-2020 07:36:05 UTC :  : Setting random password for grid user
10-09-2020 07:36:05 UTC :  : Setting random password for oracle user
10-09-2020 07:36:05 UTC :  : Calling setupSSH function
10-09-2020 07:36:05 UTC :  : SSh will be setup among racnode1 nodes
10-09-2020 07:36:05 UTC :  : Running SSH setup for grid user between nodes racnode1
10-09-2020 07:36:38 UTC :  : Running SSH setup for oracle user between nodes racnode1
10-09-2020 07:36:44 UTC : : SSH check failed for the grid@racnode1! Error occurred during SSH setup
10-09-2020 07:36:44 UTC : : Error has occurred in Grid Setup, Please verify!

**Comment by psaini79** [comment]
@Shreyashirwadkar 

Please sharee the output of the following:
* docker info
* rpm -qa | grep docker
* systemctl status docker -l
* uname -r
* systemctl status firewalld
* getenforce

**Comment by Shreyashirwadkar** [comment]
@psaini79 Please see the below output :

**docker info -**


Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 42
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-80.11.1.el8_0.x86_64
 Operating System: Red Hat Enterprise Linux 8.1 (Ootpa)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.63GiB
 Name: dl360g9-1-v09.localdomain
 ID: NHIK:FPUP:Q27V:2XK3:QCSJ:ZXF3:ZTKM:U6UB:WGX4:F2L2:VC4I:GP75
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false



 **rpm -qa | grep docker**

docker-ce-19.03.12-3.el7.x86_64
docker-ce-cli-19.03.12-3.el7.x86_64



**systemctl status docker -l**



● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-10-05 15:43:35 IST; 6 days ago
     Docs: https://docs.docker.com
 Main PID: 1367 (dockerd)
    Tasks: 29
   Memory: 91.7M
   CGroup: /system.slice/docker.service
           ├─ 1367 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --cpu-rt-runtime=950000 --cpu-rt-period=1000000 --exec-opt=native.cgroupdriver=cgroupfs
           └─25822 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 1521 -container-ip 10.209.117.85 -container-port 1521

Oct 07 11:13:52 dl360g9-1-v09.localdomain dockerd[1367]: time="2020-10-07T11:13:52.662541512+05:30" level=info msg="Container 6e9ae25fb3f85212e9afa11928b069615878b563eebda230067f2c>
Oct 07 11:13:53 dl360g9-1-v09.localdomain dockerd[1367]: time="2020-10-07T11:13:53.001032084+05:30" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks>
Oct 09 12:05:51 dl360g9-1-v09.localdomain dockerd[1367]: time="2020-10-09T12:05:51.554044546+05:30" level=info msg="Container 96fba96d4fbde671f28bec0482b6e1f52bdaccc4e3d68902f5338d>
Oct 09 12:05:51 dl360g9-1-v09.localdomain dockerd[1367]: time="2020-10-09T12:05:51.901844688+05:30" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks>
Oct 09 12:10:19 dl360g9-1-v09.localdomain dockerd[1367]: time="2020-10-09T12:10:19.641458924+05:30" level=info msg="Container 94c01aac0a5f0f47d081a9d0d527481c4e2cebf8a23a485358b2db>
Oct 09 12:10:20 dl360g9-1-v09.localdomain dockerd[1367]: time="2020-10-09T12:10:20.357557734+05:30" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks>
Oct 09 12:49:38 dl360g9-1-v09.localdomain dockerd[1367]: time="2020-10-09T12:49:38.106905255+05:30" level=info msg="Container 374a0a7e390a4aad239971c610eebb8a6f65ba52f0bded7dd76873>
Oct 09 12:49:38 dl360g9-1-v09.localdomain dockerd[1367]: time="2020-10-09T12:49:38.819059125+05:30" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks>
Oct 09 13:02:44 dl360g9-1-v09.localdomain dockerd[1367]: time="2020-10-09T13:02:44.536431751+05:30" level=info msg="Container c10f8c4ecb5a95cbe1dd03cbca832aa6588f454bad45e676c716f6>
Oct 09 13:02:45 dl360g9-1-v09.localdomain dockerd[1367]: time="2020-10-09T13:02:45.222075656+05:30" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks>



**uname -r**
4.18.0-80.11.1.el8_0.x86_64


**systemctl status firewalld**
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)

**getenforce**
Enforcing

**Comment by psaini79** [comment]
@Shreyashirwadkar 

It seems you are using the docker community edition. I have not used community edition during my testing. However, at this time error is doesn't seem to be related to the Docker community edition.

Please disable selinux using following command:
```
setenforce 0
getenforce
```
The `getenforce` command must show permissive. After this change, retry again and it should work.

**Comment by Shreyashirwadkar** [comment]
@psaini79 
Still the same SSH check failed for the grid@racnode1! Error occurred during SSH setup is shown after disabling SELinux

Below is the docker create command:

docker create -t -i \
  --hostname racnode1 \
  --volume /boot:/boot:ro \
  --volume /dev/shm \
  --tmpfs /dev/shm:rw,exec,size=4G \
  --volume /opt/containers/rac_host_file:/etc/hosts  \
  --volume /opt/.secrets:/run/secrets \
  --dns-search=example.com \
  --privileged=false \
  --volume /mnt:/oradata \
  --cap-add=SYS_NICE \
  --cap-add=SYS_RESOURCE \
  --cap-add=NET_ADMIN \
  -e NODE_VIP=172.16.1.160  \
  -e VIP_HOSTNAME=racnode1-vip  \
  -e PUBLIC_IP=10.209.117.83 \
  -e PUBLIC_HOSTNAME=racnode1 -e SINGLENIC=true \
  -e SCAN_NAME=racnode-scan \
  -e SCAN_IP=172.16.1.70  \
  -e OP_TYPE=INSTALL \
  -e DOMAIN=example.com \
  -e ASM_DISCOVERY_DIR=/oradata \
  -e ASM_DEVICE_LIST=/oradata/asm_disk01.img,/oradata/asm_disk02.img,/oradata/asm_disk03.img,/oradata/asm_disk04.img,/oradata/asm_disk05.img  \
  -e CMAN_HOSTNAME=racnode-cman1 \
  -e CMAN_IP=172.16.1.15 \
  -e COMMON_OS_PWD_FILE=/opt/.secrets/common_os_pwdfile.enc \
  -e PWD_KEY=/opt/.secrets/pwd.key \
  --restart=always \
  --tmpfs=/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  --cpu-rt-runtime=95000 \
  --ulimit rtprio=99  \
  --name racnode1 \
  oracle/database-rac:19.3.0

**Comment by psaini79** [comment]
@Shreyashirwadkar 

ssh is blocked because of some security checks from the docker host. Please share the following:
1) Get the output of the following from docker host
```
systemctl status iptables
```
If the above is enabled please execute the following and disable the same.
```
systemctl stop iptables
systemctl disable iptables
```
**Note**: Make sure you also disable firewalld.

Once you fix the above, try the ssh again

2) Login to racnode1 and racnode2 container and get me following file output:
```
cat /etc/pam.d/sshd
```
Check if `session required pam_loginuid.so` entry exist then change it to `session optional pam_loginuid.so` and try again. Please try both the steps one by one and let me know the observations.

**Comment by Shreyashirwadkar** [comment]
I am trying to provide VxFS mount point (--volume /mnt:/oradata) instead of NFS mount point

**Comment by psaini79** [comment]
@Shreyashirwadkar 

I have never tested with VxFS so I cannot comment on this. However, please let me know if you have any questions related to NFS and block device.

Keep me posted about your testing on VxFS.

**Comment by Djelibeybi** [comment]
Closing due to lack of response.
