### ISSUE TITLE
Ability to use the unpack command in a docker file

### ISSUE THREAD

**Issue by tonymwinters** [oracle/docker-images#174]
It would be nice to 'unpack' a domain template in the docker file from a template .jar as opposed to creating a new one. Replacing the create-wls-domain.py line from the dockerfile with something like:

`/u01/oracle/oracle_common/common/bin/unpack.sh -domain=/u01/oracle/user_projects/domains/$DOMAIN_NAME -template=/u01/oracle/security.jar`

returns an error:

`Required component home not found for component 'oracle.wls.core.app.server' version '12.1.3.0.0' in the MW_HOME: /u01/oracle
`

**Comment by brunoborges** [comment]
Can you please provide more details, and if possible a test case?

**Comment by brunoborges** [comment]
@tonymwinters, any input here? See my previous comment.

**Comment by tonymwinters** [comment]
@brunoborges sorry for the delay. A really common use-case would be to use the Oracle pack and unpack commands to install a domain template from an existing domain:

[https://docs.oracle.com/cd/E13179_01/common/docs92/pack/commands.html]

You can create a template from an existing weblogic domain that has all jndi settings already setup. The pack command does that for you and creates a .jar file. The unpack command takes that .jar and creates the domain for you on the weblogic server you're unpacking in. 

I modified the Dockerfile and replaced the wslt command to create a template with the following:

`/u01/oracle/oracle_common/common/bin/unpack.sh -domain=/u01/oracle/user_projects/domains/$DOMAIN_NAME -template=/u01/oracle/security.jar` and got the error above.

If this worked, we could take all existing non-containerized instances of weblogic, export (pack) all domains and import them into containerized versions.

**Comment by brunoborges** [comment]
Make sure you have `setDomainEnv.sh`

**Comment by brunoborges** [comment]
@tonymwinters, please provide all commands you performed, starting from building the images.

It is not clear whether you used an install image, or a domain image.
It is also not clear where exactly you called `unpack.sh` nor which other commands you may or may not called before `unpack.sh`.

**Comment by brunoborges** [comment]
@tonymwinters, any chance to get the detailed step-by-step you took when trying to use unpack ?

**Comment by mriccell** [comment]
@tonymwinters could you answer @brunoborges reqyest for step-by-step  you took when trying to use unpack ?

**Comment by tonymwinters** [comment]
Yea hey sorry for the delay guys. I actually scrapped the idea a while ago but maybe you guys can still look at this. The modified dockerfile looked something like this:

`# Pull base image
# ---------------
FROM oracle/weblogic:12.1.3-developer

# Maintainer
# ----------
MAINTAINER Bruno Borges <bruno.borges@oracle.com>

# WLS Configuration
# -------------------------------
ARG ADMIN_PASSWORD
ENV DOMAIN_NAME="security" \
    DOMAIN_HOME="/u01/oracle/user_projects/domains/security" \
    ADMIN_PORT="8001" \
    ADMIN_HOST="wlsadmin" \
    NM_PORT="5556" \
    MS_PORT="7001" \
    CONFIG_JVM_ARGS="-Dweblogic.security.SSL.ignoreHostnameVerification=true" \
    PATH=$PATH:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/user_projects/domains/security/bin:/u01/oracle

# Add files required to build this image
USER oracle
COPY container-scripts/* /u01/oracle/

# Configuration of WLS Domain
WORKDIR /u01/oracle
RUN ls -la /u01/oracle && /u01/oracle/oracle_common/common/bin/unpack.sh -domain=/u01/oracle/user_projects/domains/$DOMAIN_NAME -template=/u01/oracle/security.jar && \
    mkdir -p /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security && \
    echo "username=weblogic" > /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security/boot.properties && \ 
    echo "password=$ADMIN_PASSWORD" >> /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security/boot.properties && \
    echo ". /u01/oracle/user_projects/domains/$DOMAIN_NAME/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc && \ 
    echo "export PATH=$PATH:/u01/oracle/wlserver/common/bin:/u01/oracle/user_projects/domains/security/bin" >> /u01/oracle/.bashrc && \
    cp /u01/oracle/commEnv.sh /u01/oracle/wlserver/common/bin/commEnv.sh

# Expose Node Manager default port, and also default http/https ports for admin console
EXPOSE $NM_PORT $ADMIN_PORT $MS_PORT

WORKDIR $DOMAIN_HOME 

# Define default command to start bash. 
CMD ["startWebLogic.sh"]`

**Comment by Djelibeybi** [comment]
Closing due to lack of updates. Feel free to create a new issue if you experience any further issues.
