### ISSUE TITLE
De-register managed server in a autoscaled environment

### ISSUE THREAD

**Issue by a5rar** [oracle/docker-images#1740]
The weblogic [scripts](https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/1213-domain/container-scripts) do a great job of explaining how to register a server dynamically. However i get stuck when it comes to de-registering when the environment scales down. 

At the moment i am having to go in and manually delete the servers from the admin console.  I have tried to latch a deregister script to one of the sig kill sig term  function but tit looks like the script never gets called.  

Im not entirely sure this is a docker weblogic issue or a docker issue in general.  But it would be nice to have some kind of mechanism that does a cleanup after the docker container is shutdown.
i.e run a script to deregsiter it self from the cluster and  remove it self from the admin server etc

**Comment by Djelibeybi** [comment]
I suggest that this is something better managed by the [WebLogic Kubernetes Operator](https://oracle.github.io/weblogic-kubernetes-operator/).
