### ISSUE TITLE
Oracle DB XE image should ignore ORACLE_SID

### ISSUE THREAD

**Issue by gvenzl** [oracle/docker-images#1750]
Issue #1747 highlights a scenario where a user can set ORACLE_SID to a different SID which is then used to identify the password and spfile.
For Oracle XE, the ORACLE_SID should be hard set to `XE` via `ENV ORACLE_SID=XE`.

**Comment by abhisbyk** [comment]
@gvenzl `ORACLE_SID` is already hard set using `ENV ORACLE_SID=XE` in the Dockerfile for 21c XE. But, a user can still change this using `-e ORACLE_SID=<something else>`, while running the image using `docker run` command.

As we have common scripts for EE and XE edition from 21c onwards, the only differentiating point to know whether to setup EE database or XE one is `ORACLE_SID`. In this case, if a user uses XE image and gives `ORACLE_SID` some other value than XE, the setup is bound to fail. 

It is also mentioned clearly in the [README](https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md#running-oracle-database-21c18c-express-edition-in-a-container) that we can not change `ORACLE_SID` for Oracle XE images.
