### ISSUE TITLE
what does  create-domain.sh and  kubectl apply -f domain.yaml do ?

### ISSUE THREAD

**Issue by sy1968** [oracle/docker-images#1759]
During deployment of WebLogic/soa etc on Kubernetes, we are asked to run first create-domain.sh and then domain.yaml.
Can we get clarity, a little bit in detail on what these scripts do?
Thanks

**Comment by rjeberhard** [comment]
The create-domain.sh script is a sample that creates a WebLogic domain configuration (domain home filesystem) on a persistent volume and then also creates a YAML file specifying a resource of type, Domain, which describes how WebLogic instances should be run in the cluster. This Domain resource type is defined by a CRD and is related to the WebLogic Server Kubernetes Operator (https://github.com/oracle/weblogic-kubernetes-operator). The second step to `kubectl apply` creates the resource and triggers the operator to start WebLogic instances.

**Comment by sy1968** [comment]
thx
