### ISSUE TITLE
Not able to run 11g docker container

### ISSUE THREAD

**Issue by JaydiptaBiswas** [oracle/docker-images#176]
Hi,
I am trying to run Oracle 11g docker container, which is throwing me below error. Please let me know what I am missing.

Run command: 
docker run --name ora11g \
--shm-size=1g \
-p 1522:1521 -p 8082:8080 \
-v /docker-container/volumes/ora11g:/u01/app/oracle/oradata \
oracle/database:11.2.0.2-xe

LOG:
Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> BEGIN DBMS_XDB.SETLISTENERLOCALACCESS(FALSE); END;

      *
ERROR at line 1:
ORA-06550: line 1, column 7:
PLS-00201: identifier 'DBMS_XDB.SETLISTENERLOCALACCESS' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored

SQL> Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
#########################
DATABASE IS READY TO USE!
#########################
starting up 4 shared server(s) ...
ORACLE_BASE from environment = /u01/app/oracle
Mon Oct 10 11:15:42 2016
ALTER DATABASE   MOUNT
ORA-00210: cannot open the specified control file
ORA-00202: control file: '/u01/app/oracle/oradata/XE/control.dbf'
ORA-27037: unable to obtain file status
Linux-x86_64 Error: 13: Permission denied
Additional information: 3
ORA-205 signalled during: ALTER DATABASE   MOUNT...

**Comment by ramonPires** [comment]
@JaydiptaBiswas  did you give write permission in the folder `ora11g`?

**Comment by gvenzl** [comment]
@JaydiptaBiswas you have to make sure that you give write permissions for your folder /docker-container/volumes/ora11g:

    ORA-00210: cannot open the specified control file
    ORA-00202: control file: '/u01/app/oracle/oradata/XE/control.dbf'
    ORA-27037: unable to obtain file status
    Linux-x86_64 Error: 13: Permission denied
    Additional information: 3

**Comment by gvenzl** [comment]
Given the silence I assume that this was just a permission issue and hence close this ticket. Please reopen if the issue remains.

**Comment by gagarp** [comment]
I am seeing same issue. pls suggest how it got resolved?

**Comment by gvenzl** [comment]
See comment: https://github.com/oracle/docker-images/issues/227#issuecomment-362012907

**Comment by lvthillo** [comment]
I had to perform `sudo chown 1000:1000 data-oracle-11/` (where data-oracle-11 is my local directory which will be used as mount point for the container -v)
