### ISSUE TITLE
Oracle DB 19 image as Non-CDB 

### ISSUE THREAD

**Issue by Liarick** [oracle/docker-images#1760]
Hello,

Is-it possible to create a non-CDB Oracle 19 image ?
I do not find a way of doing that with the associated documentation.

The CDB Oracle 19 image created block my "create or replace" process, and seems that is coming from the CDB option.

Thanks

**Comment by gvenzl** [comment]
Hi @Liarick,

No, the non-CDB architecture was deprecated with 12.1 (before these images were available) and should no longer be used.

Can you elaborate on your "create or replace" process?

Thx,

**Comment by Liarick** [comment]
Hello @gvenzl,

First of all, thanks for your quick answer.

Some context : 
I create a schema "BODEV" on the DB created with the Oracle image. I do import a dump of my company in it.
With the user "BODEV" I try to run this simple CREATE OR REPLACE :
`CREATE OR REPLACE FUNCTION ACTUAL_VERSION
    RETURN VARCHAR
AS
BEGIN
    RETURN 'NEW-VERSION';
END ACTUAL_VERSION;
/`

That give me this error :

> ORA-38824:` Une commande CREATE OR REPLACE ne peut pas modifier la propriété EDITIONABLE d'un objet existant.
> 38824. 00000 -  "A CREATE OR REPLACE command may not change the EDITIONABLE property of an existing object."
> *Cause:    An attempt was made to replace an existing object with a different
>            value for the EDITIONABLE property.
> *Action:   Switch the EDITIONABLE property in the REPLACE statement, or alter
>            the existing object to have an EDITIONABLE property matching the
>            EDITIONABLE property in the REPLACE statement.

**Comment by jgebal** [comment]
@Liarick 
We use non-cdb docker images for @utplsql https://github.com/utPLSQL/docker-scripts

Note that those are slimmed-down images we use for self-testing of utPLSQL - they are not meant to be used by any means in production.
