### ISSUE TITLE
Provide images on Docker Store , Docker Hub or a private Docker Registry

### ISSUE THREAD

**Issue by ramonPires** [oracle/docker-images#177]
@brunoborges  oracle will provide some day support for official images on Docker Store , Docker Hub or in a private Docker Registry? Building images on every update in the project is an annoying task. I don't know if there is a license issue,but it will be good for the community if we could do this in an easy way.

**Comment by brunoborges** [comment]
Yes, we will soon make available our own Docker Hub with pre-built images based on the Dockerfiles here.

**Comment by cleankod** [comment]
How soon is "soon"? :smile:

**Comment by brunoborges** [comment]
Oh... soon as in now: container-registry.oracle.com

**Comment by lionelve** [comment]
And the xe image??

**Comment by veqryn** [comment]
You guys should put that link somewhere on here, as I was only able to find it through this ticket: https://github.com/oracle/docker-images/tree/master/OracleDatabase
