### ISSUE TITLE
Update README of OracleCoherence/docs/00.imageusage/ ?

### ISSUE THREAD

**Issue by lurodrig** [oracle/docker-images#1776]
Hello there,

Trying `docker run -d oracle/coherence:12.2.1.3.0-standalone` I get 
```
$ docker run -d oracle/coherence:12.2.1.3.0-standalone
Unable to find image 'oracle/coherence:12.2.1.3.0-standalone' locally
docker: Error response from daemon: pull access denied for oracle/coherence, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
In the other hand if I try `docker run -d store/oracle/coherence:12.2.1.3` it works :) I took this latter one from your https://hub.docker.com/ after `Check out`

Thanks in advance,

Luis

**Comment by Djelibeybi** [comment]
If you follow the instructions to build Coherence first, it will create the `oracle/coherence:12.2.1.3.0-standalone` image for you.
