### ISSUE TITLE
Increase CPUs in RAC Docker container nodes 

### ISSUE THREAD

**Issue by vishesh423** [oracle/docker-images#1786]
Hi,

I want to setup three node RAC on docker container and increase cpus from 2 to 8 on each rac container nodes. 

Could you please help in providing the commands to create RAC nodes by increasing CPUs during container creation level. 

Below command currently using to create container node which is configuring only 2 CPUs in RAC container nodes. 

docker create -t -i \
--hostname racnode1 \
--volume /boot:/boot:ro \
--volume /dev/shm \
--tmpfs /dev/shm:rw,exec,size=4G \
--volume /data/containers/rac_host_file:/etc/hosts  \
--volume /data/.secrets:/run/secrets \
--dns-search=example.com \
--privileged=false \
--volume racstorage:/oradata \
--cap-add=SYS_NICE \
--cap-add=SYS_RESOURCE \
--cap-add=NET_ADMIN \
-e NODE_VIP=172.16.1.160  \
-e VIP_HOSTNAME=racnode1-vip  \
-e PRIV_IP=192.168.17.150  \
-e PRIV_HOSTNAME=racnode1-priv \
-e PUBLIC_IP=172.16.1.150 \
-e PUBLIC_HOSTNAME=racnode1  \
-e SCAN_NAME=racnode-scan \
-e SCAN_IP=172.16.1.70  \
-e OP_TYPE=INSTALL \
-e ORACLE_SID=ORCLCDB  \
-e DOMAIN=example.com \
-e ASM_DISCOVERY_DIR=/oradata \
-e ASM_DEVICE_LIST=/oradata/asm_disk01.img,/oradata/asm_disk02.img,/oradata/asm_disk03.img,/oradata/asm_disk04.img,/oradata/asm_disk05.img  \
-e CMAN_HOSTNAME=racnode-cman1 \
-e CMAN_IP=172.16.1.15 \
-e COMMON_OS_PWD_FILE=common_os_pwdfile.enc \
-e PWD_KEY=pwd.key \
--restart=always \
--tmpfs=/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro  \
--cpu-rt-runtime=95000  \
--cpuset-cpus 0-1 \
--ulimit rtprio=99  \
--memory 64G \
--memory-swap 64G \
--ulimit rtprio=99   \
--name racnode1  \
oracle/database-rac:19.3.0

Thanks 
Vishesh

**Comment by vishesh423** [comment]
Hello Team,

Could please update on my query as i need to increase the cpu from 2 to 8 on each container RAC node. 

Thanks 
Vishesh

**Comment by psaini79** [comment]
@vishesh423 

Please use the following command:
```
docker update --cpuset-cpus 0-4 <container_name>
```

Let me know if you see any issue.

**Comment by vishesh423** [comment]
Hi ,

Will this update cpu during runtime of container or permanently add cpus in existing container nodes. 

Are below commands correct to update on existing nodes to increase cpus from 2 to 8 on each nodes. We are using 48 cores on our Docker host 

docker update --cpuset-cpus 0-8 racnode1 
docker update --cpuset-cpus 9-16 racnode2 
docker update --cpuset-cpus 17-24 racnode3

Thanks 
Vishesh

**Comment by psaini79** [comment]
@vishesh423 

This will be a persistent conf and this will reflect at the container level. If you need 8 cpus per RAC node container, please use the following:

docker update --cpuset-cpus 0-7 racnode1
docker update --cpuset-cpus 8-15 racnode2
docker update --cpuset-cpus 16-23 racnode3

**Comment by Djelibeybi** [comment]
This issue appears to be resolved. If you have further questions, please open a new issue.
