### ISSUE TITLE
.dmp file execution on oracle container startup. 

### ISSUE THREAD

**Issue by PrajktaBhosale** [oracle/docker-images#1788]
Hello Team,

I am trying to execute the .dmp file on oracle database startup but runUserScripts startup scripts has only support the .sh and .sql files. So the mounted .dmp file is getting ignored while creating the container.

I am using the below image form git hub
https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance#running-scripts-after-setup-and-on-startup

Do you have any approach to execute .dmp file on container startup. Please suggest.

**Comment by Djelibeybi** [comment]
Write a script that imports the `.dmp` file.
