### ISSUE TITLE
Change NLS configuration on Oracle XE

### ISSUE THREAD

**Issue by ramonPires** [oracle/docker-images#179]
I have a problem when I use the impdp tool for import a dump:
`ORA-02374: conversion error loading table "SCHEMA"."ADDRESS"
ORA-12899: value too large for column STREET (actual: 103, maximum: 100)
ORA-02372: data for row: STREET : 0X'4EE36F20706F73737569206EBA206E61206672656E74652064'`.  
I found a solution, change the charset of the database from `AL32UTF8 ` to `WE8ISO8859P1` :
`sqlplus /nolog`

`conn sys as sysdba;`
`SHUT;
STARTUP RESTRICT;
Alter database character set INTERNAL_USE WE8ISO8859P1;
SHUT;
STARTUP;`
But when I do it, my database  got corrupted by this change. I want to know if it is possible to change the `NLS_CHARACTERSET` on database creation,instead of change it  when the container is ready to use. I tried to put the `alter database ....` after this line https://github.com/oracle/docker-images/blob/master/OracleDatabase/dockerfiles/11.2.0.2/runOracle.sh#L79 , but I still got the same problem.

**Comment by brunoborges** [comment]
For issues with the Database, please go to community.oracle.com

**Comment by ramonPires** [comment]
@brunoborges I don't think it's a database issue,I just want to know if I can configure the image a predefined parameter like  NLS. I already found the database solution,I got a help from a DBA,and he said the only way is in the moment when I create the database.

**Comment by brunoborges** [comment]
Then the best thing to do is for you to tweak your own Dockerfile or inherited Docker image, and adjust the DB settings to your taste.

**Comment by ramonPires** [comment]
Ok,I'll try it.

**Comment by ramonPires** [comment]
Sorry @anthony-o, I don't remenber how I solved it.

**Comment by anthony-o** [comment]
OK thank you anyway @ramonPires .

@brunoborges I think it's a bug with the Oracle Docker image because even if I set `NLS_LANG` as a Docker environment variable to my container (`docker run -e NLS_LANG=FRENCH_FRANCE.WE8ISO8859P15 ...`), the `runOracle.sh` script doesn't seem to take it into consideration... according to the [official documentation](https://docs.oracle.com/cd/E17781_01/install.112/e18802/toc.htm#XEINL138), we should just define such environment variable to define the NLS settings of the Oracle XE database...

**Comment by mriccell** [comment]
@gvenzl  would you know why the language setting is not taking effect?

**Comment by anthony-o** [comment]
I tried [another approach by trying to change the global system locale](https://stackoverflow.com/q/52401710/535203) without any success for the moment because I just couldn't find a way to change the system locale...

**Comment by anthony-o** [comment]
I managed to [set the system locale](https://stackoverflow.com/a/52402320/535203) but even with this + defining the global `NLS_LANG` environment to `FRENCH_FRANCE.WE8ISO8859P15` (or without defining such `NLS_LANG` just switching global locale to `fr_FR.ISO-8859-15` (also tested with `en_US.ISO-8859-15` without any better luck)) it does not work: `SELECT * FROM nls_database_parameters;` continues to return the following values (among others):

    NLS_LANGUAGE	AMERICAN
    NLS_TERRITORY	AMERICA
    NLS_CHARACTERSET	AL32UTF8
