### ISSUE TITLE
DATABASE SETUP WAS NOT SUCCESSFUL! Please check output for further info!

### ISSUE THREAD

**Issue by ac185300** [oracle/docker-images#1795]
Hi,
The moment I restart the docker desktop. The oracle19c container fails to start.

**Steps are as follows:**
- Running the container using the below command.
```
docker run -d --name CONT_20201105 \
-p 1521:1521 -p 5500:5500 \
-e ORACLE_SID=ORCLCDB \
-e ORACLE_PDB=ORCLPDB1 \
-e ORACLE_PWD=Password@123 \
-e ORACLE_EDITION=enterprise \
-e ORACLE_CHARACTERSET=AL32UTF8 \
-v "C:\Users\abcd\Docker\Volumes\Oracle19.3.0":/opt/oracle/oradata \
oracle/database:19.3.0-ee
```

- Once the container is created, I am able to access it.
- The moment I restart my laptop, start the container, I see [this](https://github.com/chakrabortyanshu/Issues/blob/main/Docker/Oracle/19.3.0/docker_logs) in the docker logs.
- The docker info is [here.](https://github.com/chakrabortyanshu/Issues/blob/main/Docker/Oracle/19.3.0/docker_info)
- The logs from the container are [here.](https://github.com/chakrabortyanshu/Issues/blob/main/Docker/Oracle/19.3.0/trace.zip)
- The Volume folder has complete permission. So I hope that should not be the problem.

Please let me know if you need more information.

Not sure how to resolve this issue.
Any help would be appreciated.

Thanks
Anshuman

**Comment by ac185300** [comment]
Attaching Docker info for your reference.

> C:\Users\abcd>docker info
> Client:
>  Debug Mode: false
>  Plugins:
>   scan: Docker Scan (Docker Inc., v0.3.4)
> 
> Server:
>  Containers: 3
>   Running: 1
>   Paused: 0
>   Stopped: 2
>  Images: 24
>  Server Version: 19.03.13
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
>  runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  init version: fec3683
>  Security Options:
>   seccomp
>    Profile: default
>  Kernel Version: 5.4.39-linuxkit
>  Operating System: Docker Desktop
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 2
>  Total Memory: 1.915GiB
>  Name: docker-desktop
>  ID: ANHN:XXPF:A3JQ:M45P:6EEP:SAOJ:ANS4:QWPU:MK37:WNF3:7NZL:ZBLH
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: true
>   File Descriptors: 52
>   Goroutines: 62
>   System Time: 2020-11-26T14:11:55.2454629Z
>   EventsListeners: 4
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
>  Product License: Community Engine

**Comment by ac185300** [comment]
I have pulled out the logs from the container. It is [here](https://github.com/chakrabortyanshu/Issues/blob/main/Docker/Oracle/19.3.0/trace.zip)

Please let me know if you need more information.

The Volume folder has a complete permission. So I hope that should not be the problem.

Thanks

**Comment by Djelibeybi** [comment]
You might want to try increasing the amount of memory assigned to the Docker VM by Docker Desktop.
