### ISSUE TITLE
GraalVM 20.3.0  Images tags for OL8 are not available

### ISSUE THREAD

**Issue by nelvadas** [oracle/docker-images#1796]
GraalVM 20.3.0 LTS following  tags  are not released on Docker Hub
* oracle/graalvm-ce:20.3.0-java8-ol8
* oracle/graalvm-ce:20.3.0-java11-ol8

**Comment by Djelibeybi** [comment]
The GraalVM container source has moved to https://github.com/graalvm/container. Those images are available via GitHub Packages: https://github.com/graalvm/container/packages/237037
