### ISSUE TITLE
Error installing oracleXE 18c on docker 

### ISSUE THREAD

**Issue by upretip** [oracle/docker-images#1803]
Details of error while running Oracle Database 18.4c XE on docker container

Host MacOs Catalina v10.15.6(19G2021)
`Docker version 19.03.13, build 4484c46d9`

## Building Image

Method 1
```
git clone https://github.com/oracle/docker-images.git
cd docker-images/OracleDatabase/SingleInstance/dockerfiles/buildDockerImage.sh
./buildDockerImage.sh -v 18.4.0 -x -i
```

Method 2

```
git clone https://github.com/oracle/docker-images.git # don't clone it twice
cd docker-images/OracleDatabase/SingleInstance/dockerfiles/18.4.0
docker build -t oracle/database:18.4.0-xe -f Dockerfile.xe .
```

Both creates the same image but takes time to run

## Run the container

```
docker run -d --name foo -v oracle_vol:/opt/oracle/oradata -p 1521:1521 -p 5500:5500 -e ORACLE_PWD=secret oracle/database:18.4.0-xe 
docker logs -f foo
```
## Output of the log file

```
ORACLE PASSWORD FOR SYS AND SYSTEM: secret
Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
Confirm the password:
Configuring Oracle Listener.
Listener configuration succeeded.
Configuring Oracle Database XE.
Enter SYS user password: 
*****
Enter SYSTEM user password: 
**********
Enter PDBADMIN User Password: 
******
Prepare for db operation
7% complete
Copying database files
8% complete
[WARNING] ORA-00821: Specified value of sga_target 596M is too small, needs to be at least 632M
ORA-01078: failure in processing system parameters

9% complete
[FATAL] ORA-01034: ORACLE not available

29% complete
100% complete
[FATAL] ORA-01034: ORACLE not available

7% complete
0% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.

Database configuration failed. Check logs under '/opt/oracle/cfgtoollogs/dbca'.
mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/spfileXE.ora': No such file or directory
The Oracle base remains unchanged with value /opt/oracle
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining
```

**Comment by upretip** [comment]
I might have found the problem. The default resource that docker client was assigned was 2GB RAM and 2 cpu on both my MacOS: powerful workstation (catalina) and my personal (mojave) . For some reason, on Mojave, the container was able to run and install database without any issue whereas on catalina, i was seeing the above error. 

I upped the resosurce on the catalina and now the database setup is successful! Apologize if I wasted anybody's time.
🙇‍♂️

**Comment by jfarcode** [comment]
> I might have found the problem. The default resource that docker client was assigned was 2GB RAM and 2 cpu on both my MacOS: powerful workstation (catalina) and my personal (mojave) . For some reason, on Mojave, the container was able to run and install database without any issue whereas on catalina, i was seeing the above error.
> 
> I upped the resosurce on the catalina and now the database setup is successful! Apologize if I wasted anybody's time.
> 🙇‍♂️

Hello!
I had the same problem and I solved it with your recommendation. I set my resources to 2.25GB of RAM and this was enough for me. If I set 2.0GB, the installation fails and the container terminates
