### ISSUE TITLE
Creating JMS Connection Factory via offline wlst

### ISSUE THREAD

**Issue by aradecki** [oracle/docker-images#1804]
Hi,

I'm using Weblogic based on store/oracle/weblogic:12.2.1.4-dev-191221 docker image. I tried to add new connection factory using offline wlst. But there is a problem with setting DefaultTargetingEnabled (i need 'false' value) attribute due to :
"The commands in the following table are used to read an existing domain, update the domain as needed, and close the domain in offline mode. During this process, if a connection factory is targeted to a subdeployment, after running the updateDomain command and restarting the domain, default-targeting-enabled is set to true for the connection factory." (https://docs.oracle.com/middleware/1213/wls/WLSTG/config_wls.htm#WLSTG200)
So i think offline mode is not the right way. 
Maybe the online mode is better but i can't connect to WLS using connect method. Admin port is 9002 and works fine via browser, but how to use it from wlst ? Is the 9002 the right port for t3s protocol ? Which server adres should I use (localhost, hostname, IP ) ? Maybe you have other way to add new CF and permanently set DefaultTargetingEnabled  to false ?

**Comment by rjeberhard** [comment]
When the admin port is enabled, then that port is the correct port for all administrative traffic, including console and WLST traffic using t3s.

@jshum2479, do you know the answer to the question regarding DefaultTargetingEnabled?

**Comment by aradecki** [comment]
Thanks for anwer. So maybe it is SSL (certificate) problem ? I have dafault image-provided SSL configuration
Setting this two parametrs didn't solved the issue:

weblogic.security.SSL.ignoreHostnameVerification = true
weblogic.security.TrustKeyStore = DemoTrust

When trying to connect i get:

wls:/offline> connect('weblogic','pass','t3s://localhost:9002')
Connecting to t3s://localhost:9002 with userid weblogic ...
This Exception occurred at Tue Dec 08 15:12:16 CET 2020.
javax.naming.CommunicationException: Failed to initialize JNDI context, tried 2 time or times totally, the interval of each time is 0ms.
t3s://localhost:9002: Destination 127.0.0.1, 9002 unreachable.; nested exception is:
        javax.net.ssl.SSLHandshakeException: General SSLEngine problem; No available router to destination.; nested exception is:
        java.rmi.ConnectException: No available router to destination. [Root exception is java.net.ConnectException: t3s://localhost:9002: Destination 127.0.0.1, 9002 unreachable.; nested exception is:
        javax.net.ssl.SSLHandshakeException: General SSLEngine problem; No available router to destination.; nested exception is:
        java.rmi.ConnectException: No available router to destination.]
Traceback (innermost last):
  File "<console>", line 1, in ?
  File "<iostream>", line 19, in connect
  File "<iostream>", line 553, in raiseWLSTException
WLSTException: Error occurred while performing connect : Cannot connect via t3s or https. If using demo certs, verify that the -Dweblogic.security.TrustKeyStore=DemoTrust system property is set. : Failed to initialize JNDI context, tried 2 time or times totally, the interval of each time is 0ms.
t3s://localhost:9002: Destination 127.0.0.1, 9002 unreachable.; nested exception is:
        javax.net.ssl.SSLHandshakeException: General SSLEngine problem; No available router to destination.; nested exception is:
        java.rmi.ConnectException: No available router to destination.
Use dumpStack() to view the full stacktrace :

**Comment by jshum2479** [comment]
Offline changes are best done when the server is down, the DefaultTargetEnabled is available both offline and online.  It maybe overriden during shutdown.

For wlst connection problem if you are using demo ssl keys,  you can set the environment variables before launching wlst, otherwise set to whatever your trust store.

WLST_PROPERTIES="-Dweblogic.security.SSL.ignoreHostnameVerification=true -Dweblogic.security.TrustKeyStore=DemoTrust"

**Comment by mriccell** [comment]
You can also disable Admin mode 
NOTE: For security, the Administration port 9002 is enabled by default, before running the container in WebLogic 12.2.1.4. If you prefer to not enable the Administration port when you issue the docker run command, set ADMINISTRTATION_PORT_ENABLED to false. If you intend to run these images in production, then you must change the Production Mode to production. When you set the DOMAIN_NAME, the DOMAIN_HOME=/u01/oracle/user_projects/domains/$DOMAIN_NAME.

**Comment by aradecki** [comment]
Setting:
WLST_PROPERTIES="-Dweblogic.security.SSL.ignoreHostnameVerification=true -Dweblogic.security.TrustKeyStore=DemoTrust"
instead of:
JAVA_OPTS="-Dweblogic.security.SSL.ignoreHostnameVerification=true -Dweblogic.security.TrustKeyStore=DemoTrust"
solved the issue. Now i can connect using: connect('weblogic','pass','t3s://localhost:9002'). Adding new connection factory was only matter of time then.
Thank You
