### ISSUE TITLE
Unable to find prerequisite files for Oracle RAC setup

### ISSUE THREAD

**Issue by nav-nandan** [oracle/docker-images#1805]
`./buildDockerImage.sh -v 12.2.0.1`

results in

```
Checking if required packages are present and valid...
md5sum: linuxx64_12201_database.zip: No such file or directory
linuxx64_12201_database.zip: FAILED open or read
md5sum: linuxx64_12201_grid_home.zip: No such file or directory
linuxx64_12201_grid_home.zip: FAILED open or read
md5sum: WARNING: 2 listed files could not be read
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 12.2.0.1.
```

Following instructions as per https://github.com/oracle/docker-images/tree/master/OracleDatabase/RAC/OracleRealApplicationClusters and unable to find linuxx64_12201_database.zip and linuxx64_12201_grid_home.zip from https://www.oracle.com/database/technologies/oracle-database-software-downloads.html

Logged a service request via support portal for the same as well - [SR #3-24706766011](https://support.oracle.com/epmos/faces/SrDetail?srNumber=3-24706766011)

Any pointers on this would be helpful.

**Comment by Djelibeybi** [comment]
The older releases have been removed from OTN because they're no longer supported. You'll need to find the right product on [Oracle Software Delivery Cloud](https://edelivery.oracle.com) and rename them appropriately.

@psaini79 perhaps a README update is required for this?

**Comment by psaini79** [comment]
@nav-nandan 

You can login to https://edelivery.oracle.com/ and download 12.2.0.1 Grid and database. You need to Oracle Database Grid Infrastructure and Oracle database 12.2.0.1.

Let me know if you see any issue.

**Comment by psaini79** [comment]
I am closing this issue. Please re-open if you have any question on software bits availability.
