### ISSUE TITLE
Hi, exists any dockerfile or image docker to Oracle ESSO?

### ISSUE THREAD

**Issue by ylarosag** [oracle/docker-images#1808]

**Comment by Djelibeybi** [comment]
If it's not in this repo, it doesn't exist.

**Comment by ylarosag** [comment]
Too bad, at this point I wanted to test it for our systems. In my opinion it would be an important docker.

**Comment by Djelibeybi** [comment]
I'll let the ESSO team know that there is interest here. Thanks for your suggestion.
