### ISSUE TITLE
[FATAL] [DBT-10317] Specified SID Name (XXX) already exists on running prebuilt image

### ISSUE THREAD

**Issue by njiang-Quest** [oracle/docker-images#1812]
Hi, I want to reuse a batabase with pre settings, so I use docker commit to save it, but it ran ERROR, 

step1 - follow #269 to removing all VOLUME from Dockerfile

setp2 -  create base image using LINUX.X64_193000_db_home.zip:
./buildDockerImage.sh -v 19.3.0 -s

step3 - run the base image to init database:
docker run --name fipsoracle \
 -p 1521:1521 -p 5500:5500 -p 2484:2484 \
 -e ORACLE_SID=ORCL19C  \
 -e ORACLE_PDB=ORCLPDB  \
 -e ORACLE_PWD=XXX   \
 -e ORACLE_EDITION=standard \
 -v /home/test/customscripts:/opt/oracle/scripts/setup \
  oracle/database:19.3.0-se2   

The database container works as expected.

step4 - followed this instructions to commit the prebuilt container, https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/prebuiltdb

setp5 - use prebuild db image:
root@ubuntu1604:/home/test# docker run --name fips19c -p 1521:1521 -p 5500:5500 -p 2484:2484 oracle/db-prebuilt:fips19c-se2
ORACLE EDITION: STANDARD
ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: Rdis2fun

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 16-DEC-2020 02:06:36

Copyright (c) 1991, 2019, Oracle.  All rights reserved.

Starting /opt/oracle/product/19c/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 19.0.0.0.0 - Production
System parameter file is /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/dfc8bb5a8773/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Start Date                16-DEC-2020 02:06:37
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/dfc8bb5a8773/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[WARNING] [DBT-10328] Specified GDB Name (ORCL19C) may have a potential conflict with an already existing database on the system.
   ACTION: Specify a different GDB Name that does not conflict with existing databases on the system.
[FATAL] [DBT-10317] Specified SID Name (ORCL19C) already exists.
   ACTION: Specify a different SID Name that does not already exist.
[ 2020-12-11 06:46:10.648 UTC ] Prepare for db operation
DBCA_PROGRESS : 8%
[ 2020-12-11 06:46:10.897 UTC ] Copying database files
DBCA_PROGRESS : 31%
[ 2020-12-11 06:48:20.401 UTC ] Creating and starting Oracle instance
DBCA_PROGRESS : 32%
DBCA_PROGRESS : 36%
DBCA_PROGRESS : 40%
DBCA_PROGRESS : 43%
DBCA_PROGRESS : 46%
[ 2020-12-11 07:01:47.890 UTC ] Completing Database Creation
DBCA_PROGRESS : 51%
DBCA_PROGRESS : 54%
[ 2020-12-11 07:13:46.724 UTC ] Creating Pluggable Databases
DBCA_PROGRESS : 58%
DBCA_PROGRESS : 77%
[ 2020-12-11 07:14:01.793 UTC ] Executing Post Configuration Actions
DBCA_PROGRESS : 100%
[ 2020-12-11 07:14:01.800 UTC ] Database creation complete. For details check the logfiles at:
 /opt/oracle/cfgtoollogs/dbca/ORCL19C.
Database Information:
Global Database Name:ORCL19C
System Identifier(SID):ORCL19C

SQL*Plus: Release 19.0.0.0.0 - Production on Wed Dec 16 02:06:46 2020
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to an idle instance.

SQL>    ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORCL19C/control01.ctl' scope=spfile
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0

SQL>    ALTER SYSTEM SET local_listener=''
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0

SQL>    ALTER PLUGGABLE DATABASE ORCLPDB SAVE STATE
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0

SQL> BEGIN DBMS_XDB_CONFIG.SETGLOBALPORTENABLED (TRUE); END;

*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0

SQL> Disconnected
mv: cannot stat '/opt/oracle/product/19c/dbhome_1/dbs/spfileORCL19C.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/19c/dbhome_1/dbs/orapwORCL19C': No such file or directory
The Oracle base remains unchanged with value /opt/oracle
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
#####################################
The following output is now a tail of the alert.log:
2020-12-16T02:03:00.262712+00:00
JIT: pid 494 requesting stop
.... (PID:494): Archival disabled due to shutdown: 1089
Shutting down archive processes
Archiving is disabled
JIT: pid 494 requesting stop
2020-12-16T02:03:00.349373+00:00
Stopping background process VKTM
2020-12-16T02:03:14.141432+00:00
Instance shutdown complete (OS id: 494)

docker info:
root@ubuntu1604:/home/test# docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 33
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-197-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: ubuntu1604
ID: 4B6W:BHDI:TVIO:KAYA:L6ZS:3FDW:5YKS:WD5B:P3VM:2AMJ:JK3F:NHFR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

**Comment by abhisbyk** [comment]
@njiang-Quest Can you please use the [prebuiltdb extension](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/extensions/prebuiltdb) for your use case. 

Closing this issue for now. Please reopen and let me know if you encounter any problem.
