### ISSUE TITLE
Oracle 11.2.0.2-xe / No HOST or PORT found / Running Oracle XE as a part of GitLab CI pipeline

### ISSUE THREAD

**Issue by JouniV** [oracle/docker-images#1813]
Hello,

I can run Oracle 11.2.0.2-xe docker container locally without any problems on Centos operating system. I can connect to this database and it works very well.

However, when I try to run it as a part of GitLab CI pipeline, I can see the following error message in GitLab CI pipeline console.

health check: exit code 1
Health check container logs:
2020-12-16T20:15:54.538119045Z FATAL: No HOST or PORT found

Do you know how to define the needed settings for the Oracle XE 11.2.0.2 docker container as a part of GitLab CI pipeline?

Kind Regards,
Jouni

**Comment by rbermudez728** [comment]
I have the same issue, some idea?

**Comment by mark-au** [comment]
I'm not familiar with GitLab CI but I'm going to make some guesses to try and help:
* The CI system is using the HEALTHCHECK value from https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/11.2.0.2/Dockerfile.xe#L89
* This calls https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/11.2.0.2/checkDBStatus.sh and we're not getting a return code of zero on line 33.

Is it possible the container isn't starting up within the 5min window defined in the HEALTHCHECK and GitLab only tests once? Is the container getting enough resources etc? I expect GitLab has tighter default memory/cpu limits than `docker` on CentOS

**Comment by JouniV** [comment]
Thank you for your help. I will check if there are such kind of issues and will get back on this.

**Comment by JouniV** [comment]
Docker in docker technique solved my problem. So, I start the container by using Docker commands. For some reason, it did not work as a service. This case can be closed.

**Comment by abhisbyk** [comment]
Closing this issue as it is resolved.
