### ISSUE TITLE
./buildDockerImage.sh -v 11.2.0.2 -x -i failed to solve with frontend dockerfile.v0

### ISSUE THREAD

**Issue by wheredia** [oracle/docker-images#1823]
Hi, everyone. I run this command `./buildDockerImage.sh -v 11.2.0.2 -x -i`, after I have executed  _git clone_ using this command `git clone https://github.com/oracle/docker-images.git` and that returns me this error
![image](https://user-images.githubusercontent.com/15109469/103590966-cfad6e80-4ebc-11eb-9014-ee6791943eba.png)

**Comment by gvenzl** [comment]
Hi @wheredia,

As per the [Readme.md](https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md):

> Building Oracle Database Docker Install Images
**IMPORTANT**: You will have to provide the installation binaries of Oracle Database (except for Oracle Database 18c XE) and put them into the dockerfiles/<version> folder.

Thx,

**Comment by wheredia** [comment]
OMG, you're right!!!!! I should have downloaded the oracle-xe-*.zip file into version folder before exec build bash. Thanks a lots
