### ISSUE TITLE
Borked nodejs/12-oracledb image

### ISSUE THREAD

**Issue by cjbj** [oracle/docker-images#1837]
https://github.com/oracle/docker-images/blob/master/OracleLinuxDevelopers/oraclelinux7/nodejs/12-oracledb/Dockerfile doesn't actually run `yum -y install nodejs node-oracledb-node12`.  It also (now) needs to use the Instant Client 21 repo instead of the older repo.

**Comment by cjbj** [comment]
The fix will be like:
```
RUN yum -y install oracle-nodejs-release-el7 oracle-instantclient-release-el7 && \
    yum-config-manager --disable ol7_developer_nodejs14 && \
    yum-config-manager --enable ol7_developer_nodejs12 && \
    yum -y install nodejs node-oracledb-node12 && \
    rm -rf /var/cache/yum/*
```

**Comment by cjbj** [comment]
@AmedeeBulle is this in your domain now?

**Comment by Djelibeybi** [comment]
@cjbj I'll submit a fix now. Thanks for catching this.
