### ISSUE TITLE
ORA-00205 when mounting virtualbox shared folders as docker volume for EE database instance persistence

### ISSUE THREAD

**Issue by tkleiber** [oracle/docker-images#184]
Are there any filesystem type restrictions when creating volumes for persistence? There is no file created in the shared folder! Similar call works fine for XE version.

[vagrant@oraclelinux7 ~]$ sudo docker run -p 1521:1521 -p 8080:8080 -p 5500:5500 --name="db12.1.0.2-ee" --restart unless-stopped -v /virtual_storage/oracle/database/12.1.0.2/ee:/opt/oracle/oradata localhost:5000/oracle/database:12.1.0.2-ee

LSNRCTL for Linux: Version 12.1.0.2.0 - Production on 13-OCT-2016 20:38:16

Copyright (c) 1991, 2014, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.1.0.2/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.1.0.2.0 - Production
System parameter file is /opt/oracle/product/12.1.0.2/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/2f6e880e3eea/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.1.0.2.0 - Production
Start Date                13-OCT-2016 20:38:19
Uptime                    0 days 0 hr. 0 min. 1 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           ORCLCDB
Listener Parameter File   /opt/oracle/product/12.1.0.2/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/2f6e880e3eea/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully

SQL*Plus: Release 12.1.0.2.0 Production on Thu Oct 13 20:38:19 2016

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> ORACLE instance started.

Total System Global Area 1610612736 bytes
Fixed Size                  2924928 bytes
Variable Size             520097408 bytes
Database Buffers         1073741824 bytes
Redo Buffers               13848576 bytes
**ORA-00205: error in identifying control file, check alert log for more info**

SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options
ORACLE_BASE from environment = /opt/oracle
Thu Oct 13 20:38:26 2016
ALTER DATABASE   MOUNT
Thu Oct 13 20:38:26 2016
**ORA-00210: cannot open the specified control file
ORA-00202: control file: '/opt/oracle/oradata/ORCLCDB/control01.ctl'
ORA-27037: unable to obtain file status**
Linux-x86_64 Error: 2: No such file or directory
Additional information: 3
ORA-205 signalled during: ALTER DATABASE   MOUNT...
Thu Oct 13 20:38:26 2016
Checker run found 1 new persistent data failures
Thu Oct 13 20:38:28 2016
Using default pga_aggregate_limit of 2048 MB

**Comment by gvenzl** [comment]
There is no restriction of file systems from Oracle Database side and it doesn't seem that [Docker](https://docs.docker.com/engine/tutorials/dockervolumes/) has on either.
The output indicates a restart scenario. Was the previous setup successful where the database gets created?

**Comment by tkleiber** [comment]
After pulling the latest changes from github the problem is not reproducible anymore. Thank you nevertheless.
