### ISSUE TITLE
No Ruby installed in OL Docker images

### ISSUE THREAD

**Issue by crush-157** [oracle/docker-images#1842]
There are no official OL Docker images with Ruby installed.

It would be good to have both a "full fat" image (for development / builds) and a "slim" image (for runtime).

Note, (as of 19/01/2021) current stable Ruby releases are...
- 3.0.0
- 2.7.2
- 2.6.6

See https://www.ruby-lang.org/en/downloads/branches/

**Comment by Djelibeybi** [comment]
We can only build images using the Ruby packages we're already shipping (though, I'll see if we can build newer versions). From a Ruby perspective, what's the difference between a development or runtime image? Or is it just the parent image chosen?

OL7 has 2.0 in its base repos and 2.2 to 2.7 via Software Collections. We'll start there and see how we go.  
OL8 has 2.5, 2.6 and 2.7.

**Comment by crush-157** [comment]
Typically peeps use `FROM ruby:latest as builder` or `FROM ruby:2.7 as builder`.

Then the production stage is typically `FROM ruby:alpine` or `FROM ruby:2.7-alpine` for production, to reduce container weight and attack surface.

If only we still had [Smith](https://github.com/oracle/smith) eh? ;-)

**Comment by Djelibeybi** [comment]
Right, though the `-alpine` based images are unsupportable. This is about the best we get while remaining within the supportability state of the images.
