### ISSUE TITLE
Startup after patching takes extremely long

### ISSUE THREAD

**Issue by tranquilitybase69** [oracle/docker-images#1850]
Hi,

I followed the README instructions to build a base Oracle 19.3. image and used the "extensions" setup to patch this base image to 19.8. The startup of the base image is acceptable at appr. < 1 min. 
However the startup of the patched image takes very long. It shows that the database is ready to be used

#########################
DATABASE IS READY TO USE!
#########################

after appr. the same time as the base image and then starts datapatch which takes appr. 8 min. (see datapatch log below)

Maybe I missed something, but would be best practice to speed up the startup time. 

`
Running datapatch...
SQL Patching tool version 19.8.0.0.0 Production on Tue Jan 26 16:41:45 2021
Copyright (c) 2012, 2020, Oracle.  All rights reserved.

Log file for this invocation: /opt/oracle/cfgtoollogs/sqlpatch/sqlpatch_852_2021_01_26_16_41_45/sqlpatch_invocation.log

Connecting to database...OK
Gathering database info...done

Note:  Datapatch will only apply or rollback SQL fixes for PDBs
       that are in an open state, no patches will be applied to closed PDBs.
       Please refer to Note: Datapatch: Database 12c Post Patch SQL Automation
       (Doc ID 1585822.1)

Bootstrapping registry and package to current versions...done
Determining current state...done

Current state of interim SQL patches:
  No interim patches found

Current state of release update SQL patches:
  Binary registry:
    19.8.0.0.0 Release_Update 200703031501: Installed
  PDB CDB$ROOT:
    Applied 19.3.0.0.0 Release_Update 190410122720 successfully on 26-JAN-21 01.28.29.036525 PM
  PDB ORCLPDB1:
    Applied 19.3.0.0.0 Release_Update 190410122720 successfully on 26-JAN-21 01.34.15.315387 PM
  PDB PDB$SEED:
    Applied 19.3.0.0.0 Release_Update 190410122720 successfully on 26-JAN-21 01.34.15.315387 PM

Adding patches to installation queue and performing prereq checks...done
Installation queue:
  For the following PDBs: CDB$ROOT ORCLPDB1
    No interim patches need to be rolled back
    Patch 31281355 (Database Release Update : 19.8.0.0.200714 (31281355)):
      Apply from 19.3.0.0.0 Release_Update 190410122720 to 19.8.0.0.0 Release_Update 200703031501
    No interim patches need to be applied
  For the following PDBs: PDB$SEED
    No interim patches need to be rolled back
    Patch 31281355 (Database Release Update : 19.8.0.0.200714 (31281355)):
      Apply from 19.3.0.0.0 Release_Update 190410122720 to 19.8.0.0.0 Release_Update 200703031501
    No interim patches need to be applied

Installing patches...
Patch installation complete.  Total patches installed: 3

Validating logfiles...done
Patch 31281355 apply (pdb CDB$ROOT): SUCCESS
  logfile: /opt/oracle/cfgtoollogs/sqlpatch/31281355/23688465/31281355_apply_ORCLCDB_CDBROOT_2021Jan26_16_42_22.log (no errors)
Patch 31281355 apply (pdb ORCLPDB1): SUCCESS
  logfile: /opt/oracle/cfgtoollogs/sqlpatch/31281355/23688465/31281355_apply_ORCLCDB_ORCLPDB1_2021Jan26_16_45_13.log (no errors)
Patch 31281355 apply (pdb PDB$SEED): SUCCESS
  logfile: /opt/oracle/cfgtoollogs/sqlpatch/31281355/23688465/31281355_apply_ORCLCDB_PDBSEED_2021Jan26_16_47_46.log (no errors)
SQL Patching tool complete on Tue Jan 26 16:49:58 2021
DONE: Datapatch execution.

DONE: Executing user defined scripts

#### The following output is now a tail of the alert.log:
Completed: alter pluggable database "PDB$SEED" close immediate force instances=('ORCLCDB')
2021-01-26T16:49:57.942708+00:00
alter pluggable database "PDB$SEED" open READ ONLY instances=('ORCLCDB')
PDB$SEED(2):Autotune of undo retention is turned on.
PDB$SEED(2):Endian type of dictionary set to little
PDB$SEED(2):Undo initialization finished serial:0 start:76412545 end:76412545 diff:0 ms (0.0 seconds)
PDB$SEED(2):Database Characterset for PDB$SEED is WE8MSWIN1252
PDB$SEED(2):Opening pdb with no Resource Manager plan active
Pluggable database PDB$SEED opened read only
Completed: alter pluggable database "PDB$SEED" open READ ONLY instances=('ORCLCDB')
`

**Comment by pazyp** [comment]
The patching process you create a new docker image from scratch, so the first run after patching is creating the Databases (CDB & PDB) again so it is likely to take some time.  After the first startup if you stop it and start it again does it start in a reasonable time frame?

**Comment by tranquilitybase69** [comment]
Yes that is what I thought too and I have since created an image with a database created inside which serves my purpose.
I guess I was just wondering how an empty database could take so long to patch as the 19.3. image starts in a reasonable time.

Of course starting and stopping once and then restarting will speed things up.

Thanks for your clarification.

**Comment by tranquilitybase69** [comment]
Closing as I found a solution.
