### ISSUE TITLE
Incorrect version for the oraclelinux8 golang images

### ISSUE THREAD

**Issue by AmedeeBulle** [oracle/docker-images#1856]
The OL8 golang image is based on the `go-toolset:ol8` stream which is not bound to a golang version, so you always get the latest release:

```bash
$ docker run --rm ghcr.io/oracle/oraclelinux8-golang:1.13                                                      
go version go1.14.12 linux/amd64
```

Not sure how to address this, in particular the way we currently do the build -- also depending in the release schedule we might end up with a different version in the multi-arch builds...

**Comment by Djelibeybi** [comment]
There is no approved way to fix this except to remove the version because we're only allowed to use the packages distributed by Oracle, so that's what I've done.
