### ISSUE TITLE
XE Database Docker container created with --restart unless-stopped does not start the database after boot

### ISSUE THREAD

**Issue by tkleiber** [oracle/docker-images#186]
This is a follow up of https://github.com/oracle/docker-images/issues/141:

When starting the xe docker container in vagrant box via

docker run ... --restart unless-stopped

and rebooting via

vagrant halt
vagrant up

the docker container comes up after this, as I can see via docker ps, but database is not available.

Have to do to make the database available again via

docker stop container
docker start container

**Comment by tkleiber** [comment]
[docker_log.txt](https://github.com/oracle/docker-images/files/531398/docker_log.txt)

**Comment by gvenzl** [comment]
This is interesting. From the log the following happens:

On Sat Oct 15 `20:17:43 2016` the DB installation was successful.
Then a regular shutdown happens at `20:19:05 2016`

    Stopping container.
    SIGTERM received, shutting down database!
    Shutting down Oracle Database 11g Express Edition instance.
    Sat Oct 15 20:19:05 2016

Then a successful startup happens again at `20:19:39 2016`:

    Completed: ALTER DATABASE OPEN
    Starting background process CJQ0
    Sat Oct 15 20:19:41 2016
    CJQ0 started with pid=25, OS id=245 
    Sat Oct 15 20:21:40 2016
    XDB installed.
    XDB initialized.

Followed by a shutdown again at `20:22:20 2016`:

    Stopping container.
    SIGTERM received, shutting down database!
    Shutting down Oracle Database 11g Express Edition instance.
    Sat Oct 15 20:22:20 2016

Now here is where it gets interesting. After that shutdown of the database a new database installation is kicked off at about `20:24:28 2016`, which fails:

    Starting Oracle Net Listener...Done
    Configuring database...
    Database Configuration failed.  Look into /u01/app/oracle/product/11.2.0/xe/config/log for details

    SQL*Plus: Release 11.2.0.2.0 Production on Sat Oct 15 20:24:28 2016

    Copyright (c) 1982, 2011, Oracle.  All rights reserved.

    Connected to an idle instance.

Although the previous shutdowns and startup aren't necessarily related to the issue I just wanted to point them out for completeness.

To analyze this further we will have to have a look into `/u01/app/oracle/product/11.2.0/xe/config/log` and figure out what the issue was with the configuration. Please gather the log files in there and attach them to this thread.

**Comment by tkleiber** [comment]
I try to map these steps to that what I do:

- fresh start of the virtualbox via vagrant
- creation of the docker container, which create the database too
- as this first shell shows the alert.log, the first database shutdown comes from a container stop in a second shell
- then the container is started from this shell again
- then I shutdown the virtualbox via vagrant, which stops the container and so the database too
- then I start up the virtualbox via vagrant, which starts the container via the container option  "--restart unless-stopped" and should start the database too

The persistant layer for the database is mounted from my windows system via virtualbox shared folders and than to the container. Is it possible, that the startup/creation script of the database happens before this persistant layer is fully mounted?
[log.zip](https://github.com/oracle/docker-images/files/534308/log.zip)

**Comment by gvenzl** [comment]
That could be the case. Is the mounting of the shared folder done automatically?

Can you try to leave the persistence layer inside the virtualbox environment rather than in a shared folder on windows? That should show whether it is a problem with the shared folder or something else.

**Comment by tkleiber** [comment]
Have tried without persistence - then all works fine. The container and the database is restarting after booting the virtualbox.

Have then tried using persistence with mounting a local created directory in the virtualbox as docker volume, but then I get the errors directly from creating the docker container, which starts the database. I think this has something to do with groups and ownership, as the database files are created with a user and group terry, but cannot be opened by all other users.

**Comment by gvenzl** [comment]
Whichever directory is used for persistence has to be writable to by the user `oracle` or the group `dba` inside the Docker container.

**Comment by gvenzl** [comment]
I guess the issue was related to permissions outside the docker container. --> Close.
