### ISSUE TITLE
chart not find  checkDBLockStatus.sh

### ISSUE THREAD

**Issue by pandihao** [oracle/docker-images#1866]
location: docker-images/blob/master/OracleDatabase/SingleInstance/helm-charts/oracle-db/templates/deployment.yaml
checkDBLockStatus.sh not find

**Comment by pandihao** [comment]
deployment.yaml:  

     readinessProbe:
            exec:
              command: [ "/bin/sh", "-c", "$ORACLE_BASE/checkDBLockStatus.sh" ]
            initialDelaySeconds: 20
            periodSeconds: 40
            timeoutSeconds: 20

**Comment by yunus-qureshi** [comment]
@pandihao The oracle DB image from container-registry.oracle.com should have this script included

**Comment by Djelibeybi** [comment]
@yunus-qureshi I thought the Oracle DB image on Container Registry now used the Dockerfiles in this repo. Is that not the case? If not, we need that to be called out far more explicitly.

**Comment by yunus-qureshi** [comment]
@Djelibeybi the Container Registry image is indeed built from the Dockerfiles in this repo but it includes one extension that is not yet merged to this repo. I'll raise a PR for that

@pandihao if you are using a locally built image, update helm-charts/oracle-db/templates/deployment replacing checkDBLockStatus.sh in the readiness probe with checkDBStatus.sh
