### ISSUE TITLE
 Oracle Database Kubernetes example， kubernetes-example.yaml  config has problem

### ISSUE THREAD

**Issue by pandihao** [oracle/docker-images#1868]
file location: docker-images/OracleDatabase/SingleInstance/samples/kubernetes/kubernetes-example.yaml
kubectl apply -f kubernetes-example.yaml

Issue:

SQL> Disconnected from Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0
mkdir: cannot create directory '/opt/oracle/oradata/dbconfig': Permission denied
mv: cannot stat '/opt/oracle/product/19c/dbhome_1/dbs/spfileORCLCDB.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/19c/dbhome_1/dbs/orapwORCLCDB': No such file or directory
mv: cannot move '/opt/oracle/product/19c/dbhome_1/network/admin/sqlnet.ora' to '/opt/oracle/oradata/dbconfig/ORCLCDB/': No such file or directory
mv: cannot move '/opt/oracle/product/19c/dbhome_1/network/admin/listener.ora' to '/opt/oracle/oradata/dbconfig/ORCLCDB/': No such file or directory
mv: cannot move '/opt/oracle/product/19c/dbhome_1/network/admin/tnsnames.ora' to '/opt/oracle/oradata/dbconfig/ORCLCDB/': No such file or directory
mv: cannot move '/opt/oracle/product/19c/dbhome_1/install/.docker_enterprise' to '/opt/oracle/oradata/dbconfig/ORCLCDB/': No such file or directory
cp: cannot create regular file '/opt/oracle/oradata/dbconfig/ORCLCDB/': No such file or directory
ln: failed to create symbolic link '/opt/oracle/product/19c/dbhome_1/network/admin/sqlnet.ora': File exists
ln: failed to create symbolic link '/opt/oracle/product/19c/dbhome_1/network/admin/listener.ora': File exists
ln: failed to create symbolic link '/opt/oracle/product/19c/dbhome_1/network/admin/tnsnames.ora': File exists
cp: cannot stat '/opt/oracle/oradata/dbconfig/ORCLCDB/oratab': No such file or directory
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/checkDBStatus.sh: line 26: sqlplus: command not found

---------------------------------------------------------------------------------------------------
Solve：

###
add config:
     spec:
        securityContext:
        runAsUser: 54321
        fsGroup: 54321

###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-rdbms
  labels:
    app: oracle-rdbms
  namespace: example-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-rdbms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle-rdbms
    spec:
      containers:
        - name: rdbms
          image: local-repo/oracle/database:19.3.0-ee
          envFrom:
            - configMapRef:
                name: oracle-rdbms-config
            - secretRef:
                name: oracle-rdbms-credentials
          ports:
            - containerPort: 1521
              name: oracle-listener
            - containerPort: 5500
              name: oem-express
          volumeMounts:
          - name: oradata
            mountPath: /opt/oracle/oradata
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            exec:
              command:
                - /bin/sh
                - "-c"
                - $ORACLE_BASE/$CHECK_DB_FILE
          livenessProbe:
            initialDelaySeconds: 300
            periodSeconds: 60
            exec:
              command:
                - /bin/sh
                - "-c"
                - $ORACLE_BASE/$CHECK_DB_FILE
      volumes:
        - name: oradata
          persistentVolumeClaim:
            claimName: oracle-rdbms-oradata

**Comment by yunus-qureshi** [comment]
@abhisbyk please take a look

**Comment by abhisbyk** [comment]
@pandihao Thanks for pointing out the issue. We need the security context mentioning uid as 54321 to deploy successfully on k8s cluster. We will fix this.
