### ISSUE TITLE
Dockerfile for FMW Infrastructure Installer

### ISSUE THREAD

**Issue by nikhilkhedlekar** [oracle/docker-images#187]
Hello. 
The dockerfiles you have provided are very insightful. I was wondering if you would also commit a dockerfile for the FMW Infrastructure Installer. 
Thank you!

**Comment by brunoborges** [comment]
There are Dockerfiles for the FMW Infrastructure Installer. For example: [Dockerfile.infrastructure](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/dockerfiles/12.2.1/Dockerfile.infrastructure)
