### ISSUE TITLE
Pre-built Oracle 18.4.0-xe failed on start-up

### ISSUE THREAD

**Issue by mrsladek** [oracle/docker-images#1880]
Hi,

I've just crated a 18.4.0 xe Oracle container following the instructions provided [here](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance).

When I start ut the database with `docker run --name oracle18xe -p 51521:1521 -p 55500:5500 oracle/database:18.4.0-xe` I get an error as follows:

> sed: can't read /etc/oratab: No such file or directory
> /opt/oracle/runOracle.sh: line 194: /etc/init.d/oracle-xe-18c: No such file or directory
> grep: /etc/oratab: No such file or directory
> /opt/oracle/checkDBStatus.sh: line 18: oraenv: No such file or directory
> #####################################
> ########### E R R O R ###############
> DATABASE SETUP WAS NOT SUCCESSFUL!
> Please check output for further info!
> ########### E R R O R ###############
> #####################################
> The following output is now a tail of the alert.log:
> tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
> tail: no files remaining

Any ideas how to fix this issue?

Running macOS 11.2.3 with docker engine 20.10.5

Thank you :)

**Comment by mrsladek** [comment]
Hi again, I build the image once again and it seems to work well now. The previous image was ~340MB in size. I assume the download of the binary went wrong. The new image is 3.5GB and works well.

I wished the database was 350MB in size and was working :P

**Comment by Djelibeybi** [comment]
Glad you got it working. :)
