### ISSUE TITLE
[Oracle 18c] Fail to restart

### ISSUE THREAD

**Issue by ortizman** [oracle/docker-images#1882]
I started the container, created the database and worked on it without problems. 
I even restarted to check that the docker volume was well mapped and that the data was not lost.

The next day, oracle no longer started and gave me the following message

Can you help me with this error?

```
The Oracle base remains unchanged with value /opt/oracle
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
ORA-01157: cannot identify/lock data file 13 - see DBWR trace file
ORA-01110: data file 13: '/opt/oracle/product/18c/dbhomeXE/dbs/TBS_ABC_RELEASE.DBF'
ORA-1157 signalled during: ALTER DATABASE OPEN...
2021-03-24T12:36:47.866000+00:00
Errors in file /opt/oracle/diag/rdbms/xe/XE/trace/XE_mz00_110.trc:
ORA-01110: data file 13: '/opt/oracle/product/18c/dbhomeXE/dbs/TBS_ABC_RELEASE.DBF'
ORA-01565: error in identifying file '/opt/oracle/product/18c/dbhomeXE/dbs/TBS_ABC_RELEASE.DBF'
ORA-27037: unable to obtain file status
Linux-x86_64 Error: 2: No such file or directory
Additional information: 7
```

***startup docker command***
`docker run --rm --name oracle-18xe -p 1521:1521 -p 5500:5500 -e ORACLE_PWD=Prueba123 -e ORACLE_CHARACTERSET=UTF8 -v /home/manuel/.oracle_xe_oradata/:/opt/oracle/oradata oracle/database:18.4.0-xe`

**folder permissions**

_ls -lart_
`drwxrwxrwx   4  54321  54321    4096 mar 10 17:22  .oracle_xe_oradata
`

**Docker Info**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 36
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-45-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.34GiB
 Name: book1
 ID: LDGP:JSFS:LKQJ:O7H6:W2RF:XRCO:CL3I:D5CZ:PXAC:BE36:7J3R:M3QG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ortizman
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by ortizman** [comment]
Ok, I found how to reproduce the error easily. 

1. Perform a clean install
`docker run -d --rm --name oracle-18xe -p 1521:1521 -p 5500:5500 -e ORACLE_PWD=Prueba123 -e ORACLE_CHARACTERSET=UTF8 -v /home/manuel/.new_oradata/:/opt/oracle/oradata oracle/database:18.4.0-xe
`
2. Create a new tablespace
alter session set "_ORACLE_SCRIPT"=true;

CREATE TABLESPACE TBS_ABC_RELEASE DATAFILE 'TBS_ABC_RELEASE.DBF' SIZE 2048m AUTOEXTEND ON NEXT 32m MAXSIZE 3072m;

CREATE USER ABC_RELEASE IDENTIFIED BY Pass123 DEFAULT TABLESPACE TBS_ABC_RELEASE;

GRANT ALL PRIVILEGES TO ABC_RELEASE;


3. reboot... and the error occurs.

**Comment by gvenzl** [comment]
Hi @ortizman,

Yup, the error is right there in the log:

```
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
ORA-01157: cannot identify/lock data file 13 - see DBWR trace file
ORA-01110: data file 13: '/opt/oracle/product/18c/dbhomeXE/dbs/TBS_ABC_RELEASE.DBF'
ORA-1157 signalled during: ALTER DATABASE OPEN...
```

Specifically

```
ORA-01157: cannot identify/lock data file 13 - see DBWR trace file
ORA-01110: data file 13: '/opt/oracle/product/18c/dbhomeXE/dbs/TBS_ABC_RELEASE.DBF'
```

You are creating a new tablespace inside the container, not the volume.
`/opt/oracle/product/18c/dbhomeXE/dbs/` is not part of your volume`-v /home/manuel/.oracle_xe_oradata/:/opt/oracle/oradata` (namely `/opt/oracle/oradata`) and nor should it be.
Given the immutable nature of Docker containers, anything that's not in the volume won't be persisted.
Luckily the remedy is simple, just put your tablespace data file where also the other data files reside:

Change
```sql
CREATE TABLESPACE TBS_ABC_RELEASE DATAFILE 'TBS_ABC_RELEASE.DBF' ...
```

to

```sql
CREATE TABLESPACE TBS_ABC_RELEASE DATAFILE '/opt/oracle/oradata/XE/TBS_ABC_RELEASE.DBF' ...
```

**Comment by ortizman** [comment]
@gvenzl thank you very much for your reply.

I noticed the same thing a moment ago and solved it in a similar way.

I lost some time with this. 

How common is it to create the DATAFILE with the specified path?

If you don't remember this before creating the TS, everything will still work fine and you will be able to operate even for days before you realize that you will lose all the data when you restart the container.

Even a warning in the README would help.

**Comment by gvenzl** [comment]
> How common is it to create the DATAFILE with the specified path?

Pretty common usually, because folks have to decide which location, disks, SAN, etc. to use that has enough storage for the data to come. There are many options of how and where one can create tablespaces in Oracle Database, always worthwhile checking the [documentation](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-TABLESPACE.html#GUID-51F07BF5-EFAF-4910-9040-C473B86A8BF9) as well.

> If you don't remember this before creating the TS, everything will still work fine and you will be able to operate even for days before you realize that you will lose all the data when you restart the container. 

Yes true, it will work as long as the container is there and you didn't start a new one. But that's the thing with Docker's nonpersistent nature and running software inside it that requires persistence. The same is true also if, e.g., you forget to mount a volume to the container to begin with. It will work, until...

Btw, you might also want to rethink your strategy here:

```sql
alter session set "_ORACLE_SCRIPT"=true;

CREATE TABLESPACE TBS_ABC_RELEASE DATAFILE 'TBS_ABC_RELEASE.DBF' SIZE 2048m AUTOEXTEND ON NEXT 32m MAXSIZE 3072m;

CREATE USER ABC_RELEASE IDENTIFIED BY Pass123 DEFAULT TABLESPACE TBS_ABC_RELEASE;

GRANT ALL PRIVILEGES TO ABC_RELEASE;
```

* `alter session set "_ORACLE_SCRIPT"=true;`
  You should never use an underscore parameter unless explicitly told by Oracle Support.
* `CREATE TABLESPACE TBS_ABC_RELEASE`
  You probably want to create that tablespace in the PDB (XEPDB1) itself, not the CDB
* `CREATE USER ABC_RELEASE IDENTIFIED BY`
  You probably want to create that user in the PDB (XEPDB1) itself, not the CDB
* GRANT ALL PRIVILEGES TO ABC_RELEASE;
  You should probably not grant all privileges to the user but only the ones you need. It might come back and bite you in production where somebody doesn't allow you to use a given privilege that your app silently relied on.

Happy to continue the conversation here or over on [Twitter](https://twitter.com/GeraldVenzl) if you want/need more info. Fair warning, Twitter is usually quicker for me.

**Comment by ortizman** [comment]
I have no control over these statements

Back to the point. I understand the "nature" of containers (not just docker), but this is not a case where one forgets to map a volume, but it is related to the tablespace creation statement

**Comment by gvenzl** [comment]
That is a shame, well, if you know who does, I'm happy to explain to that person as well.

Yes, correct, the create tablespace statement allows one to create a tablespace anywhere on the file system, and if the path is omitted, the database picks a default location that doesn't happen to reside in the volume. What is it that you are after?

**Comment by ortizman** [comment]
So, the statement is perfectly valid, and sufficient in a variety of contexts, but it will have different consequences in a docker installation than in a non-docker installation. 

That oracle assigns by default a place in the container filesystem outside the mapped volume (for my tablespace) might be less obvious in pre-existing applications where this was not an issue.

On the other hand, by destroying the docker container, not only will I lose my data but it will no longer be possible to create a new one normally because it will fail Oracle on startup!

Because of the above, I suggest to add a Note / Warning

Translated with www.DeepL.com/Translator (free version)

**Comment by gvenzl** [comment]
Yes, the statement is perfectly valid.

Yeah, in the end, Oracle Database does nothing special but just calls the regular file system calls to create a file. If the path is omitted, the path is the current working directory, just like a `touch myfile.txt` or `vim myfile.txt` would do as well.

Yeah, sort of. If a data file isn't accessible the Oracle RDBMS will not allow you to open that database. One could always open the database in mount state and remove the tablespace, recreate it, or do a lot of other things including recovering the tablespace. All of that has little to do with running inside Docker and just with how the software works, but I understand your point. If you miss adding the tablespace into a location where the volume is, you can shoot yourself in the foot potentially quite a bit later on.

We will add the error to the FAQs, thank you for the suggestion!
