### ISSUE TITLE
Error has occurred in Grid Setup Issue Oracle Linux 7 with Docker

### ISSUE THREAD

**Issue by rashm1n** [oracle/docker-images#1887]
ERROR: 
PRVG-10467 : The default Oracle Inventory group could not be determined.

Verifying Physical Memory ...PASSED
Verifying Available Physical Memory ...PASSED
Verifying Swap Size ...PASSED
Verifying Free Space: racnode1:/usr,racnode1:/var,racnode1:/etc,racnode1:/sbin,racnode1:/tmp ...PASSED
Verifying User Existence: grid ...
  Verifying Users With Same UID: 54332 ...PASSED
Verifying User Existence: grid ...PASSED
Verifying Group Existence: asmadmin ...PASSED
Verifying Group Existence: asmdba ...PASSED
Verifying Group Membership: asmdba ...PASSED
Verifying Group Membership: asmadmin ...PASSED
Verifying Run Level ...PASSED
Verifying Hard Limit: maximum open file descriptors ...PASSED
Verifying Soft Limit: maximum open file descriptors ...PASSED
Verifying Hard Limit: maximum user processes ...PASSED
Verifying Soft Limit: maximum user processes ...PASSED
Verifying Soft Limit: maximum stack size ...PASSED
Verifying Architecture ...PASSED
Verifying OS Kernel Version ...PASSED
Verifying OS Kernel Parameter: semmsl ...PASSED
Verifying OS Kernel Parameter: semmns ...PASSED
Verifying OS Kernel Parameter: semopm ...PASSED
Verifying OS Kernel Parameter: semmni ...PASSED
Verifying OS Kernel Parameter: shmmax ...PASSED
Verifying OS Kernel Parameter: shmmni ...PASSED
Verifying OS Kernel Parameter: shmall ...PASSED
Verifying OS Kernel Parameter: file-max ...PASSED
Verifying OS Kernel Parameter: ip_local_port_range ...PASSED
Verifying OS Kernel Parameter: rmem_default ...PASSED
Verifying OS Kernel Parameter: rmem_max ...PASSED
Verifying OS Kernel Parameter: wmem_default ...PASSED
Verifying OS Kernel Parameter: wmem_max ...PASSED
Verifying OS Kernel Parameter: aio-max-nr ...PASSED
Verifying OS Kernel Parameter: panic_on_oops ...PASSED
Verifying Package: kmod-20-21 (x86_64) ...PASSED
Verifying Package: kmod-libs-20-21 (x86_64) ...PASSED
Verifying Package: binutils-2.23.52.0.1 ...PASSED
Verifying Package: compat-libcap1-1.10 ...PASSED
Verifying Package: libgcc-4.8.2 (x86_64) ...PASSED
Verifying Package: libstdc++-4.8.2 (x86_64) ...PASSED
Verifying Package: libstdc++-devel-4.8.2 (x86_64) ...PASSED
Verifying Package: sysstat-10.1.5 ...PASSED
Verifying Package: ksh ...PASSED
Verifying Package: make-3.82 ...PASSED
Verifying Package: glibc-2.17 (x86_64) ...PASSED
Verifying Package: glibc-devel-2.17 (x86_64) ...PASSED
Verifying Package: libaio-0.3.109 (x86_64) ...PASSED
Verifying Package: libaio-devel-0.3.109 (x86_64) ...PASSED
Verifying Package: nfs-utils-1.2.3-15 ...PASSED
Verifying Package: smartmontools-6.2-4 ...PASSED
Verifying Package: net-tools-2.0-0.17 ...PASSED
Verifying Port Availability for component "Oracle Remote Method Invocation (ORMI)" ...PASSED
Verifying Port Availability for component "Oracle Notification Service (ONS)" ...PASSED
Verifying Port Availability for component "Oracle Cluster Synchronization Services (CSSD)" ...PASSED
Verifying Port Availability for component "Oracle Notification Service (ONS) Enterprise Manager support" ...PASSED
Verifying Port Availability for component "Oracle Database Listener" ...PASSED
Verifying Users With Same UID: 0 ...PASSED
Verifying Current Group ID ...PASSED
Verifying Root user consistency ...PASSED
Verifying Package: cvuqdisk-1.0.10-1 ...PASSED
Verifying Host name ...PASSED
Verifying Node Connectivity ...
  Verifying Hosts File ...PASSED
  Verifying Check that maximum (MTU) size packet goes through subnet ...PASSED
Verifying Node Connectivity ...PASSED
Verifying Multicast or broadcast check ...PASSED
Verifying ASM Integrity ...PASSED
Verifying Device Checks for ASM ...
  Verifying Package: cvuqdisk-1.0.10-1 ...PASSED
  Verifying ASM device sharedness check ...
    Verifying Shared Storage Accessibility:/oradata/asm_disk01.img,/oradata/asm_disk02.img,/oradata/asm_disk03.img,/oradata/asm_disk05.img,/oradata/asm_disk04.img ...PASSED
  Verifying ASM device sharedness check ...PASSED
  Verifying Access Control List check ...PASSED
  Verifying I/O scheduler ...PASSED
Verifying Device Checks for ASM ...PASSED
Verifying Network Time Protocol (NTP) ...
  Verifying '/etc/ntp.conf' ...PASSED
Verifying Network Time Protocol (NTP) ...FAILED (PRVG-1017)
Verifying Same core file name pattern ...PASSED
Verifying User Mask ...PASSED
Verifying User Not In Group "root": grid ...PASSED
Verifying Time zone consistency ...PASSED
Verifying VIP Subnet configuration check ...PASSED
Verifying resolv.conf Integrity ...FAILED (PRVG-10048)
Verifying DNS/NIS name service ...
  Verifying Name Service Switch Configuration File Integrity ...PASSED
Verifying DNS/NIS name service ...FAILED (PRVG-1101)
Verifying Single Client Access Name (SCAN) ...WARNING (PRVG-11368)
Verifying Domain Sockets ...PASSED
Verifying /boot mount ...PASSED
Verifying Daemon "avahi-daemon" not configured and running ...PASSED
Verifying Daemon "proxyt" not configured and running ...PASSED
Verifying loopback network interface address ...PASSED
Verifying Oracle base: /u01/app/grid ...
  Verifying '/u01/app/grid' ...PASSED
Verifying Oracle base: /u01/app/grid ...PASSED
Verifying User Equivalence ...PASSED
Verifying RPM Package Manager database ...INFORMATION (PRVG-11250)
Verifying Network interface bonding status of private interconnect network interfaces ...PASSED
Verifying /dev/shm mounted as temporary file system ...PASSED
Verifying File system mount options for path /var ...PASSED
Verifying DefaultTasksMax parameter ...PASSED
Verifying zeroconf check ...PASSED
Verifying ASM Filter Driver configuration ...PASSED
Verifying Systemd login manager IPC parameter ...PASSED
Verifying Access control attributes for cluster manifest file ...PASSED

Pre-check for cluster services setup was unsuccessful on all the nodes. 

Failures were encountered during execution of CVU verification request "stage -pre crsinst".

Verifying Network Time Protocol (NTP) ...FAILED
racnode1: PRVG-1017 : NTP configuration file "/etc/ntp.conf" is present on
          nodes "racnode1" on which NTP daemon or service was not running

Verifying resolv.conf Integrity ...FAILED
racnode1: PRVG-10048 : Name "racnode1" was not resolved to an address of the
          specified type by name servers "127.0.0.11".

Verifying DNS/NIS name service ...FAILED
PRVG-1101 : SCAN name "racnode-scan" failed to resolve

Verifying Single Client Access Name (SCAN) ...WARNING
racnode1: PRVG-11368 : A SCAN is recommended to resolve to "3" or more IP
          addresses, but SCAN "racnode-scan" resolves to only "172.16.1.70"

Verifying RPM Package Manager database ...INFORMATION
PRVG-11250 : The check "RPM Package Manager database" was not performed because
it needs 'root' user privileges.

CVU operation performed:      stage -pre crsinst
Date:                         Mar 30, 2021 10:08:04 AM
CVU home:                     /u01/app/19.3.0/grid/
User:                         grid
03-30-2021 15:38:29 IST :  : CVU Checks are ignored as IGNORE_CVU_CHECKS set to true. It is recommended to set IGNORE_CVU_CHECKS to false and meet all the cvu checks requirement. RAC installation might fail, if there are failed cvu checks.
03-30-2021 15:38:29 IST :  : Running Grid Installation
03-30-2021 15:38:45 IST :  : Running root.sh
03-30-2021 15:38:45 IST :  : Nodes in the cluster racnode1
03-30-2021 15:38:45 IST :  : Running root.sh on racnode1
03-30-2021 15:38:45 IST :  : Running post root.sh steps
03-30-2021 15:38:45 IST :  : Running post root.sh steps to setup Grid env
03-30-2021 15:38:52 IST :  : Checking Cluster Status
03-30-2021 15:38:52 IST :  : Nodes in the cluster 
03-30-2021 15:38:52 IST :  : Removing /tmp/cluvfy_check.txt as cluster check has passed
03-30-2021 15:38:52 IST :  : Running User Script for grid user
03-30-2021 15:38:52 IST :  : Generating DB Responsefile Running DB creation
03-30-2021 15:38:52 IST :  : Running DB creation
03-30-2021 15:38:58 IST :  : Checking DB status
03-30-2021 15:38:58 IST : : ORCLCDB is not up and running on racnode1
03-30-2021 15:38:58 IST : : Error has occurred in Grid Setup, Please verify!

**Comment by rashm1n** [comment]
docker info

Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 33
 Server Version: 19.03.11-ol
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.1.12-61.1.18.el7uek.x86_64
 Operating System: Oracle Linux Server 7.3
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.42GiB
 Name: oracle.novalocal
 ID: MVIN:LVAE:ZHVS:SGLR:O7JQ:L7FY:3J6N:CCZV:WRJK:66GY:M4B5:ZCMT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

rpm -qa | grep docker

docker-cli-19.03.11.ol-8.el7.x86_64
docker-engine-19.03.11.ol-8.el7.x86_64

uname -r

4.1.12-61.1.18.el7uek.x86_64

cat /etc/oracle-release

Oracle Linux Server release 7.3

systemctl status docker

docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2021-03-30 14:26:38 IST; 19h ago
     Docs: https://docs.docker.com
 Main PID: 11213 (dockerd)
   Memory: 6.3G
   CGroup: /system.slice/docker.service
           ├─11213 /usr/bin/dockerd --cpu-rt-runtime=950000 --cpu-rt-period=1000000 --exec-opt=native.cgroupdriver=systemd
           └─18853 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 1521 -container-ip 172.16.1.15 -container-po...

Mar 30 14:44:49 oracle.novalocal dockerd[11213]: time="2021-03-30T14:44:49.856043307+05:30" level=info msg="Layer sha25...d up"
Mar 30 14:53:38 oracle.novalocal dockerd[11213]: time="2021-03-30T14:53:38.492798420+05:30" level=info msg="ignoring ev...lete"
Mar 30 15:01:06 oracle.novalocal dockerd[11213]: time="2021-03-30T15:01:06.525985026+05:30" level=info msg="Layer sha25...d up"
Mar 30 15:01:11 oracle.novalocal dockerd[11213]: time="2021-03-30T15:01:11.577561726+05:30" level=info msg="Layer sha25...d up"
Mar 30 15:01:16 oracle.novalocal dockerd[11213]: time="2021-03-30T15:01:16.626289662+05:30" level=info msg="Layer sha25...d up"
Mar 30 15:01:21 oracle.novalocal dockerd[11213]: time="2021-03-30T15:01:21.689252509+05:30" level=info msg="Layer sha25...d up"
Mar 30 15:33:45 oracle.novalocal dockerd[11213]: time="2021-03-30T15:33:45.531650547+05:30" level=info msg="Container 6...orce"
Mar 30 15:33:45 oracle.novalocal dockerd[11213]: time="2021-03-30T15:33:45.875837921+05:30" level=info msg="ignoring ev...lete"
Mar 30 16:13:23 oracle.novalocal dockerd[11213]: time="2021-03-30T16:13:23.900370470+05:30" level=info msg="Container 9...orce"
Mar 30 16:13:24 oracle.novalocal dockerd[11213]: time="2021-03-30T16:13:24.038865170+05:30" level=info msg="ignoring ev...lete"
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by rashm1n** [comment]
![image](https://user-images.githubusercontent.com/33457890/113095655-7467ef80-9211-11eb-9d28-4403aa5af867.png)

/u01/app/oracle/diag

[diag.zip](https://github.com/oracle/docker-images/files/6234072/diag.zip)

**Comment by psaini79** [comment]
@rashm1n 

Please test Oracle RAC on Docker with UEK 5. It seems your OL machine is imaged with UEK 4 i.e. `Kernel Version: 4.1.12-61.1.18.el7uek.x86_64`.  I did not find the zip file of diag directory of Grid which must be in your case is /u01/app/grid/diag inside the racnode1 and racnode2.

Also, login execute following commands from inside the container and paste the output. To login tot the container, you can execute `docker exec -i -t racnode1 /bin/bash` from your docker host.

```
/u01/app/19.3.0grid/bin/crsctl check crs
/u01/app/19.3.0grid/bin/olsnodes
```

**Comment by rashm1n** [comment]
Creating a new instance with the updated Kernal fixed the issue. Thanks for the help @psaini79. Much appreciated.
