### ISSUE TITLE
Updated ORDS docker image?

### ISSUE THREAD

**Issue by paolobellardone** [oracle/docker-images#1888]
The highest version of ORDS that can be used to build the ORDS docker image is 18.3.0, while the latest available is 20.4.3. Will it be available an update of this image?

**Comment by jfarcode** [comment]
I have been trying for a few days to implement `oracle/restdataservices:20.4.3` container with my database container `oracle/database:18.4.0-xe`.
These connect but what I get is:
URL | ERROR CODE | ERROR MESSAGE
--- | -----------|--------------
http://localhost:8888/ords/    or   http://localhost:8888/ords/sql-developer/  | 404 | The request could not be assigned to any database. Check if the request URL is correct and if the URLs to the database mappings have been configured correctly.

**Comment by jprates** [comment]
Same as @jfarcode is happening here, and ORDS 18.4 is no longer available for download, the oldest version available is 19.4.6, so unless I'm missing something there is no way we can make use of this container.

FYI I tried do use v20.4.3 by creating the Checksum.20.4.3 file with the checksum line, and as said it does return error 404 all the time:
`b3855a4e68120d7eb49a2f7c8334a540  ords-20.4.3.050.1904.zip`

**Comment by stif** [comment]
I am facing the same problem with ORDS 21.1.1
```
a6afba1b823ee77a10c365f240a67812  ords-21.1.1.116.2032.zip
```
=> 404 Not Found


Please fix this or provide a download link for the last supported ORDS version (18.4.0)

**Comment by stif** [comment]
any news when we can expect a update to a recent ORDS version?

**Comment by gvenzl** [comment]
I'll check with the team. We modified the build script that it would build any ORDS version when skipping the checksum check (via the `-i` option) but it sounds like other things have changed in ORDS that make the container no longer work.
