### ISSUE TITLE
Can not run OracleDB container Macbook M1

### ISSUE THREAD

**Issue by tanyaKl** [oracle/docker-images#1896]

**Comment by gvenzl** [comment]
Hi @tanyaKl, the image `sbtatlas.sigma.sbrf.ru:5000/oracle_base:41.000.00.etalon` is not the one that is built using these build scripts. Ideally, you get in contact with the image provider and ask for clarification.

That being said, I see several Unix `Permission denied` errors in the output:

```
SP2-0157: unable to CONNECT to ORACLE after 3 attempts, exiting SQL*Plus

/opt/oracle/app/product/19c/dbhome_1/bin/oraenv: line 57: /dev/null: Permission denied

/opt/oracle/app/product/19c/dbhome_1/bin/dbhome: line 66: /dev/null: Permission denied

ORACLE_HOME = [/home/oracle] ? \c

/opt/oracle/app/product/19c/dbhome_1/bin/oraenv: line 135: /dev/null: Permission denied
```

Can it perhaps be that you have to enable additional permissions on your Mac for that image?

**Comment by gvenzl** [comment]
Just for reference, what was the issue @tanyaKl?
