### ISSUE TITLE
Patching with official oracle patches

### ISSUE THREAD

**Issue by montge** [oracle/docker-images#190]
Request that a sample be provided of best practices in applying  PSU patches to the weblogic install (and oracle database) install so that the security scanners (nessus) are nolonger detecting vulnerabilities.

**Comment by mriccell** [comment]
I have added to samples a 12211-patch sample which demonstrates how to apply a PSU to a WLS 12.2.1 install image.  After creating a new image extend and create domain image, start new WLS Server containers with the patched binaries.
