### ISSUE TITLE
Dockerfile for Oracle SSO

### ISSUE THREAD

**Issue by afulay** [oracle/docker-images#191]
Any suggestions on how to deploy Oracle Single Sign-On via docker? Any plans to provide dockerfile or image for it?

**Comment by brunoborges** [comment]
No plans. What would be the use case? Why would you put SSO inside a container?

**Comment by afulay** [comment]
Same reason as other apps, reduce the use of VMs, better consolidation, etc.

**Comment by brunoborges** [comment]
But for production use or dev/test only?

**Comment by afulay** [comment]
Dev/test for sure.

**Comment by afulay** [comment]
Test/dev.

cheers, Adeesh

**Comment by abhirockzz** [comment]
@afulay Does SSO refer to Oracle eSSO (Enterprise Single Sign On) or Oracle Access Manager ? Or something else ?

**Comment by afulay** [comment]
eSSO.

**Comment by Djelibeybi** [comment]
Closing this issue as a whole bunch of new Oracle Dockerfiles are in development. Hopefully it'll be part of that.
