### ISSUE TITLE
Oracle Database Single Instance for Windows containers

### ISSUE THREAD

**Issue by djechelon** [oracle/docker-images#1912]
I know most people use Linux containers. Wouldn't it be a nasty idea to provide build scripts for a Windows-based container?

I know I have permission to make the script on my own and make a pull request, but I just don't have enough experience and competence to install Oracle from the CLI in Windows, not to mention creating a pwsh/cmd to automate it.

Just an idea

**Comment by gvenzl** [comment]
Unfortunately, the same is true for me with regards to Windows.
I'm a Linux guy running a Mac, but nowhere close to Windows and shell scripting in it.

If anybody would be up for creating and maintaining build scripts for Windows, I'm sure we would be happy to accept that Pull Request.

**Comment by SetTrend** [comment]
I ran the Windows installer in a Windows Docker container, but the installer failed.

One of the reasons was that it set a fix IP address into various configuration files while building the Docker image, whereas the Linux container uses 0.0.0.0.

If someone could list the alterations performed by the Linux script, I may go and convert them into PowerShell/Windows.

**Comment by gvenzl** [comment]
Windows containers are currently not on our roadmap and a PR from the community has not been provided.
Also, this ER does not show much interest from the community in Windows containers (anymore), hence closing this ER.
