### ISSUE TITLE
buildContainerImage.sh is creating an incomplete installation of Oracle Database 18.4.0 XE image

### ISSUE THREAD

**Issue by eakeur** [oracle/docker-images#1913]
I'm trying to create an image of the Oracle Database 18c XE but the script is creating something and leaving it undone. 
The image down here are logs from the execution of the buildContainerImage.sh file 

![image](https://user-images.githubusercontent.com/63017440/115729444-cc4ecd80-a35b-11eb-9e9e-ae4d0287ff0b.png)

As you can see in the image, the installation happens very fast but throws no error. But when I try to start a container based on it, here's what happens: 

```
sed: can't read /etc/oratab: No such file or directory
/opt/oracle/runOracle.sh: line 194: /etc/init.d/oracle-xe-18c: No such file or directory
grep: /etc/oratab: No such file or directory
/opt/oracle/checkDBStatus.sh: line 18: oraenv: No such file or directory
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining
```
I had no idea of what was happening until I saw the image size of a colleague in my team: 5.87GB. Mine 322.69MB. How's that possible? Is there any workarounds for this image installation?

Here's my Docker info, running on Windows integrated with WSL2 Debian

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 12.42GiB
 Name: docker-desktop
 ID: I7YI:EAJL:YE5R:4RPW:BIDF:VIAL:TRR5:5HEX:RQ4I:2U6J:IACA:FLMF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by eakeur** [comment]
> Hey @eakeur, do you have the output from the build itself, please?

Hi! It's the one in the picture. It shows nothing but that.

**Comment by Djelibeybi** [comment]
As you're using Docker Desktop for Windows, please change the Docker Engine JSON configuration to disable BuildKit, i.e.

```json
  "features": {
    "buildkit": false
  }
```

That should configure Docker to revert back to the previous build output style and let us see the full output.

**Comment by inteligeninfosys** [comment]
Same issue here with me, any suggestions? I have docker desktop on Mac

**Comment by Djelibeybi** [comment]
Please provide the exact `docker build` command you're using. If you're running macOS, please add `-o --progress=plain` to the `./buildContainerImage.sh` parameters so that BuildX outputs the entire log. I recommend piping it all out to `tee`, i.e. adding ` | tee - xe-build.log` at the end, so it captures the output.

**Comment by Djelibeybi** [comment]
Turns out, BuildKit is really difficult to log. Instead, try this please:

```shell
$ cd /path/to/oracle/docker-images/OracleDatabase/SingeInstance/dockerfiles/18.4.0
$ DOCKER_BUILDKIT=0 docker build --force-rm=true --no-cache=true --progress=plain --build-arg DB_EDITION=xe -t oracle/database:18.4.0-xe -f Dockerfile.xe . | tee -a ./build-xe.log
```

That will actually capture the full, unabridged build process.
