### ISSUE TITLE
Error when trying to run the docker container from 12.1.0.2 image: "Cannot create a container database from non Container Database template."

### ISSUE THREAD

**Issue by StefanSperliDerNeicheWaldvogel** [oracle/docker-images#1917]
Hello, 

Despite using the general purpose database template, I get following error when trying to run the container: 

ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: T8S4Ao9qlF4=1

LSNRCTL for Linux: Version 12.1.0.2.0 - Production on 22-APR-2021 13:26:57

Copyright (c) 1991, 2014, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.1.0.2/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.1.0.2.0 - Production
System parameter file is /opt/oracle/product/12.1.0.2/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/1a4ed98b02be/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.1.0.2.0 - Production
Start Date                22-APR-2021 13:26:57
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.1.0.2/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/1a4ed98b02be/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
Cannot create a container database from non Container Database template.
cat: /opt/oracle/cfgtoollogs/dbca/CDB/CDB.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/CDB.log: No such file or directory
mv: cannot stat '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/spfileCDB.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/orapwCDB': No such file or directory
mv: cannot stat '/opt/oracle/product/12.1.0.2/dbhome_1/network/admin/tnsnames.ora': No such file or directory
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/checkDBStatus.sh: line 26: sqlplus: command not found
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
#####################################
The following output is now a tail of the alert.log:
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining

Has anyone encountered a similar problem before and found a solution?

**Comment by gvenzl** [comment]
Hi @StefanSperliDerNeicheWaldvogel, I think the clue to the issue is this line:

> Cannot create a container database from non Container Database template.

**Comment by StefanSperliDerNeicheWaldvogel** [comment]
Hi @gvenzl , thanks for your reply and I assumed as much but couldn't find an answer for it online after googling the error message. I found a question about it in the Oracle forum which wasn't answered. Do you know what I would have to change to make the container run properly? 

Here is the template I am using, filename is cust.dbc:

<?xml version = '1.0'?>
<DatabaseTemplate name="General_Purpose" description=" " version="12.1.0.2.0">
   <CommonAttributes>
      <option name="OMS" value="true"/>
      <option name="JSERVER" value="true"/>
      <option name="SPATIAL" value="true"/>
      <option name="IMEDIA" value="true"/>
      <option name="XDB_PROTOCOLS" value="true">
         <tablespace id="SYSAUX"/>
      </option>
      <option name="ORACLE_TEXT" value="true">
         <tablespace id="SYSAUX"/>
      </option>
      <option name="SAMPLE_SCHEMA" value="false"/>
      <option name="CWMLITE" value="true">
         <tablespace id="SYSAUX"/>
      </option>
      <option name="APEX" value="true"/>
      <option name="DV" value="true"/>
      <option name="NET_EXTENSIONS" value="true"/>
   </CommonAttributes>
   <Variables/>
   <CustomScripts Execute="false"/>
   <InitParamAttributes>
      <InitParams>
         <initParam name="db_name" value=""/>
         <initParam name="dispatchers" value="(PROTOCOL=TCP) (SERVICE={SID}XDB)"/>
         <initParam name="audit_file_dest" value="{ORACLE_BASE}/admin/{DB_UNIQUE_NAME}/adump"/>
         <initParam name="compatible" value="12.1.0.2.0"/>
         <initParam name="remote_login_passwordfile" value="EXCLUSIVE"/>
         <initParam name="processes" value="1000"/>
         <initParam name="undo_tablespace" value="UNDOTBS1"/>
         <initParam name="control_files" value="(&quot;/oracle/tables/{DB_UNIQUE_NAME}/control01.ctl&quot;, &quot;{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/control02.ctl&quot;, &quot;{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/control03.ctl&quot;)"/>
         <initParam name="diagnostic_dest" value="{ORACLE_BASE}"/>
         <initParam name="db_recovery_file_dest" value="{ORACLE_BASE}/fast_recovery_area"/>
         <initParam name="audit_trail" value="db"/>
         <initParam name="db_recovery_file_dest_size" value="" unit="MB"/>
		 <initParam name="nls_territory" value="GERMANY"/>
         <initParam name="nls_language" value="GERMAN"/>
         <initParam name="log_archive_dest_1" value="'LOCATION=/log/{DB_NAME}'"/>
         <initParam name="session_max_open_files" value="1000"/>
         <initParam name="global_names" value="FALSE"/>
         <initParam name="session_cached_cursors" value="200"/>
         <initParam name="open_cursors" value="1000"/>
         <initParam name="job_queue_processes" value="10"/>
         <initParam name="utl_file_dir" value="*"/>
         <initParam name="log_archive_format" value="ARC%S_%R.%T"/>
         <initParam name="parallel_max_servers" value="0"/>
         <initParam name="undo_management" value="AUTO"/>
         <initParam name="db_files" value="1024"/>
         <initParam name="plsql_code_type" value="NATIVE"/>
         <initParam name="archive_lag_target" value="900"/>
         <initParam name="optimizer_index_caching" value="90"/>
         <initParam name="optimizer_index_cost_adj" value="30"/>
		 <initParam name="sort_area_size" value="1024000"/>
		 <initParam name="sort_area_retained_size" value="1024000"/>
         <initParam name="db_block_size" value="8" unit="KB"/>
		 <initParam name="recyclebin" value="OFF"/>
         <initParam name="pga_aggregate_limit" value="4" unit="GB"/>
         <initParam name="pga_aggregate_target" value="2" unit="GB"/>
         <initParam name="lock_sga" value="FALSE"/>
         <initParam name="pre_page_sga" value="FALSE"/>
         <initParam name="sga_max_size" value="5504" unit="MB"/>
         <initParam name="sga_target" value="1856" unit="MB"/>
      </InitParams>
      <MiscParams>
         <databaseType>MULTIPURPOSE</databaseType>
         <maxUserConn>20</maxUserConn>
         <percentageMemTOSGA>40</percentageMemTOSGA>
         <customSGA>false</customSGA>
         <archiveLogMode>false</archiveLogMode>
         <initParamFileName>{ORACLE_BASE}/admin/{DB_UNIQUE_NAME}/pfile/init.ora</initParamFileName>
      </MiscParams>
      <SPfile useSPFile="true">{ORACLE_HOME}/database/spfile{SID}.ora</SPfile>
   </InitParamAttributes>
   <StorageAttributes>
      <DataFiles>
         <Location>{ORACLE_HOME}/assistants/dbca/templates/Seed_Database.dfb</Location>
         <SourceDBName cdb="true">seeddata</SourceDBName>
         <Name id="3" Tablespace="SYSAUX" Contents="PERMANENT" Size="560" autoextend="true" blocksize="8192" con_id="1">{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/SYSAUX01.DBF</Name>
         <Name id="1" Tablespace="SYSTEM" Contents="PERMANENT" Size="780" autoextend="true" blocksize="8192" con_id="1">{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/SYSTEM01.DBF</Name>
         <Name id="5" Tablespace="UNDOTBS1" Contents="UNDO" Size="645" autoextend="true" blocksize="8192" con_id="1">{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/UNDOTBS01.DBF</Name>
         <Name id="6" Tablespace="USERS" Contents="PERMANENT" Size="5" autoextend="true" blocksize="8192" con_id="1">{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/USERS01.DBF</Name>
      </DataFiles>
      <TempFiles>
         <Name id="1" Tablespace="TEMP" Contents="TEMPORARY" Size="60" con_id="1">{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/TEMP01.DBF</Name>
      </TempFiles>
      <ControlfileAttributes id="Controlfile">
         <maxDatafiles>100</maxDatafiles>
         <maxLogfiles>16</maxLogfiles>
         <maxLogMembers>3</maxLogMembers>
         <maxLogHistory>1</maxLogHistory>
         <maxInstances>8</maxInstances>
         <image name="control01.ctl" filepath="{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/"/>
         <image name="control02.ctl" filepath="{ORACLE_BASE}/fast_recovery_area/{DB_UNIQUE_NAME}/"/>
      </ControlfileAttributes>
      <RedoLogGroupAttributes id="1">
         <reuse>false</reuse>
         <fileSize unit="KB">51200</fileSize>
         <Thread>1</Thread>
         <member ordinal="0" memberName="redo01.log" filepath="{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/"/>
      </RedoLogGroupAttributes>
      <RedoLogGroupAttributes id="2">
         <reuse>false</reuse>
         <fileSize unit="KB">51200</fileSize>
         <Thread>1</Thread>
         <member ordinal="0" memberName="redo02.log" filepath="{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/"/>
      </RedoLogGroupAttributes>
      <RedoLogGroupAttributes id="3">
         <reuse>false</reuse>
         <fileSize unit="KB">51200</fileSize>
         <Thread>1</Thread>
         <member ordinal="0" memberName="redo03.log" filepath="{ORACLE_BASE}/oradata/{DB_UNIQUE_NAME}/"/>
      </RedoLogGroupAttributes>
   </StorageAttributes>
</DatabaseTemplate>
