### ISSUE TITLE
Docker pull access denied

### ISSUE THREAD

**Issue by niteshn24** [oracle/docker-images#1920]
Hi,
I am trying to run docker image for oracle db v 19.3.0-ee , which seem to have completed.

I still get the below error. pls advise. 

```
Unable to find image 'oracle/database:latest' locally
docker: Error response from daemon: pull access denied for oracle/database, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```
```
$ docker images
REPOSITORY        TAG         IMAGE ID       CREATED             SIZE
oracle/database   19.3.0-ee   423eff6c93a9   About an hour ago   6.54GB
```

**Comment by AmedeeBulle** [comment]
You need to provide the name with the tag -- e.g.: `oracle/database:19.3.0-ee`

**Comment by niteshn24** [comment]
> You need to provide the name with the tag -- e.g.: `oracle/database:19.3.0-ee`

Yes already did that as below
`docker run -d --name oracle-ee -p 1521:1521 -e ORACLE_SID=orcl -e ORACLE_PWD=password123 -v oradata:/opt/oracle/oradata oracle/database 19.3.0-ee`

**Comment by gvenzl** [comment]
You need a colon `:`, not a space between database and 19.3.0-ee: `oracle/database:19.3.0-ee`

**Comment by niteshn24** [comment]
got it. My bad! thank you Amedee & gvenzl.
