### ISSUE TITLE
docker image on windows -- insufficient space 

### ISSUE THREAD

**Issue by niteshn24** [oracle/docker-images#1921]
Hi guys,

I am trying to create another docker container but it fails with the below. Any advice on how to create a local volume and remap. Of course i did 

`$ docker volume create test`

`$ docker run -d --name oracle1931 -p 1522:1521 -e ORACLE_SID=test -e ORACLE_PWD=password121 -v test:/opt/oracle/oradata oracle/database:19.3.0-ee`

```
[FATAL] [DBT-06604] The location specified for 'Data Files Location' has insufficient free space.
   CAUSE: Only (2,541MB) free space is available on the location (/opt/oracle/oradata/TEST).
   ACTION: Choose a 'Data Files Location' that has enough space (minimum of (3,603MB)) or free up space on the specified location.
cat: /opt/oracle/cfgtoollogs/dbca/TEST/TEST.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/TEST.log: No such file or directory
```

**Comment by gvenzl** [comment]
Sounds like you don't have enough space in the volume:

```
 CAUSE: Only (2,541MB) free space is available on the location (/opt/oracle/oradata/TEST).
```

Can it be that you have some space limit set for Docker volumes?

**Comment by Djelibeybi** [comment]
Keep in mind that on Windows, there is a hidden VM that has a fixed disk size and that's used for all storage. Check the Docker Preferences and make sure the VM disk is large enough for your needs.
