### ISSUE TITLE
docker oracle port issue

### ISSUE THREAD

**Issue by niteshn24** [oracle/docker-images#1924]
Hi, Need your assistance here..

created two containers here but there is conflict when i open both the same time...

`docker run -d --name oracle1931 -p 1521:1521 -e ORACLE_PWD=password123 -v oradata:/opt/oracle/oradata test/oracledb:latest`
`docker run -d --name oracle19 -p 1522:1521 -e ORACLE_PWD=password123 -v oradata:/opt/oracle/oradata test/oracledb:latest`

My second container fails to work with the below even though it is redirected to host port as 1522. Thoughts?

Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
Services Summary...
Service "ORCLCDB" has 1 instance(s).
  Instance "ORCLCDB", status BLOCKED, has 1 handler(s) for this service...

**Comment by AmedeeBulle** [comment]
I believe you copied 2 times the same line in you issue report as both lines are looking identical to me.

If your intent is to run 2 databases you will need to pass
- a different name
- a different local port
- a different volume for the database files

**Comment by AmedeeBulle** [comment]
You edited your issue with different name/port, but you still use the same volume (`oradata`)...
You cannot run two database engines on the same set of database files.

**Comment by niteshn24** [comment]
`docker run -d --name oracle193 -p 1521:1521 -e ORACLE_PWD=password123 -v tempdir:/opt/oracle/oradata geoplace/oracledb:latest`



SQL*Plus: Release 19.0.0.0.0 - Production on Fri Apr 30 15:10:33 2021
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to an idle instance.

```
SQL> ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/opt/oracle/product/19c/dbhome_1/dbs/initORCLCDB.ora'
SQL> Disconnected
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
```

**Comment by niteshn24** [comment]
this is odd as i was expecting it to work now that i created another volume too

**Comment by gvenzl** [comment]
The tag `geoplace/oracledb:latest` suggests that you are using a different image than provided from the build scripts in this repo. There seems to be multiple issues in the output above:

1) The database cannot find the server parameter file (which is symlinked from the volume back to `$ORACLE_HOME/dbs`
1) It appears that the image does not contain a fully functioning database setup:
```
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
```
followed by:
```
/opt/oracle/checkDBStatus.sh: line 26: sqlplus: command not found
```

You will have to check with the provider of that image to find out what's going on inside there or, in case that it is your own image, see what went wrong during the image build or the entrypoint script on container startup.
