### ISSUE TITLE
After Mac update the Docker Stopped working due to running Oracle XE image in it

### ISSUE THREAD

**Issue by pbhatthybris** [oracle/docker-images#1925]
Hello There,

I had Oracle XE Image built and loaded with data in Docker Container. I believe, the Docker Oracle XE container was running overnight. Also, the Mac updated, now the Docker container complains about the Oracle XE image not able to load. See the attached screen shot.

![image](https://user-images.githubusercontent.com/17163139/116758227-9c4b9e00-a9dd-11eb-9445-8cacbe8aeacc.png)

Docker Vesrion:
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Oracle XE (Free) Version:
18.4.0 installed from the docker-images in this repo. 

MacOs version: BigSur Version: 11.3

Only change that I noticed in the MaC update was following, that I reversed(included), but with no effect on outcome.
the following line was removed by update (in file /etc/group)
_trustd:*:282:_trustd

 

Thank you.
Prashantkumar Bhatt

**Comment by Djelibeybi** [comment]
You might want to try clicking Troubleshoot in the Docker menu bar and seeing if anything there might help. Or try a more general Docker Desktop support location, as we only support the images, not the conatiner runtime.
