### ISSUE TITLE
Error building container image with ./buildContainerImage - [MacOS][Oracle-database-xe-18c] 

### ISSUE THREAD

**Issue by agustinllado** [oracle/docker-images#1926]
Hello, i'm trying to build a docker container image for Oracle-database-xe-18c with ./buildContainerImage command but the following error interrupts the installation.

**`sed: can't read /etc/security/limits.d/oracle-database-preinstall-18c.conf: No such file or directory`**

```
#8 13.09 sed: can't read /etc/security/limits.d/oracle-database-preinstall-18c.conf: No such file or directory
------
executor failed running [/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     cd $INSTALL_DIR &&     yum -y install openssl oracle-database-preinstall-18c &&     sed -i -e 's/\(oracle\s\+hard\s\+nofile\)/# \1/' /etc/security/limits.d/oracle-database-preinstall-18c.conf &&     yum -y localinstall $INSTALL_FILE_1 &&     rm -rf /var/cache/yum &&     rm -rf /var/tmp/yum-* &&     mkdir -p $ORACLE_BASE/scripts/setup &&     mkdir $ORACLE_BASE/scripts/startup &&     ln -s $ORACLE_BASE/scripts /docker-entrypoint-initdb.d &&     mkdir -p $ORACLE_BASE/oradata /home/oracle &&     chown -R oracle:oinstall $ORACLE_BASE /home/oracle &&     mv $INSTALL_DIR/$RUN_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$PWD_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$CHECK_DB_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$CONF_FILE /etc/sysconfig/ &&     ln -s $ORACLE_BASE/$PWD_FILE / &&     cd $HOME &&     rm -rf $INSTALL_DIR &&     chmod ug+x $ORACLE_BASE/*.sh]: exit code: 2
```

Anyone knows any workaround to manage this?

I'm running it on MacOS Big Sur with Apple chip.

Thanks in advance!

**Comment by Djelibeybi** [comment]
That soulds like your container can't install the preinstall RPM, or didn't install it properly. You'll need to provide the entire output though, because this isn't enough to identify the actual problem. Try running the build manually using the command I provided in #1913

**Comment by AmedeeBulle** [comment]
> I'm running it on MacOS Big Sur with Apple chip.

I'm afraid the database won't run on Apple silicon...

@Djelibeybi can we have this confirmed / documented?

**Comment by agustinllado** [comment]
> That soulds like your container can't install the preinstall RPM, or didn't install it properly. You'll need to provide the entire output though, because this isn't enough to identify the actual problem. Try running the build manually using the command I provided in #1913

I already tried, but getting the same issue 
`sed: can't read /etc/security/limits.d/oracle-database-preinstall-18c.conf: No such file or directory
`

<img width="715" alt="Screen Shot 2021-05-03 at 12 20 46" src="https://user-images.githubusercontent.com/59889107/116895861-fe88e680-ac09-11eb-873b-937451a87eeb.png">

Is what @AmedeeBulle wrote confirmed?

Thanks both for your answers

**Comment by Djelibeybi** [comment]
@AmedeeBulle is correct. The Database only runs on `x86_64` hardware. The release of Docker Desktop for macOS M1 is not supported. I will add this to the FAQ.

**Comment by Djelibeybi** [comment]
Sorry I didn't notice that myself either.

**Comment by samuelgomesgit** [comment]
Not sure if this still relevant, but I've managed to run the buildContainer script on the M1 by adding --platform=linux/amd64 to the build command (ln 243). It took about 15 minutes to build the image.

**Comment by erfanbashar** [comment]
> Not sure if this still relevant, but I've managed to run the buildContainer script on the M1 by adding --platform=linux/amd64 to the build command (ln 243). It took about 15 minutes to build the image.

@samuelgomesgit I'm facing a similar issue. Would you please share any screenshot of what you changed in the buildContainer.sh file. I have done the similar change but it's showing the same error message, perhaps I've not done the changes accurately

**Comment by Vunovati** [comment]
Running `./buildContainerImage.sh -x -v 18.4.0 -o '--platform=linux/amd64'` did it for me (~17 min).

Explanation:
When building Intel docker images on M1, you need to provide `--platform=linux/amd64` docker build option.

in `buildContainerImage.sh`
`-o: passes on container build option`

**Comment by Andrew-Pynch** [comment]
> 

you rock i love you thank you 1 billion
