### ISSUE TITLE
Docker RAC - Failing because Grid Set-up

### ISSUE THREAD

**Issue by Anand0583** [oracle/docker-images#1929]
Hello Team,

I have tried following the docker installation of Oracle RAC. Can you please help us here with what is the issue.

Below is the logs of racnode1.

`docker logs -f racnode1
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=weeus01devorcl03
TERM=xterm
PRIV_HOSTNAME=weeus01devorcl03-priv
DOMAIN=example.com
CRS_NODES=racnode1
GRID_RESPONSE_FILE=grid_sample.rsp
OP_TYPE=INSTALL
NODE_VIP=172.17.0.8
VIP_HOSTNAME=weeus01devorcl03-vip
PUBLIC_HOSTNAME=weeus01devorcl03
SCAN_IP=172.17.0.7
ASM_DEVICE_LIST=/dev/asm_disk1
DBCA_RESPONSE_FILE=dbca_sample.rsp
PRIV_IP=192.168.17.150
SCAN_NAME=scantest.localdomain
ASM_DISCOVERY_DIR=/dev
PUBLIC_IP=172.17.0.6
COMMON_OS_PWD_FILE=common_os_pwdfile.enc
SETUP_LINUX_FILE=setupLinuxEnv.sh
INSTALL_DIR=/opt/scripts
GRID_BASE=/u01/app/grid
GRID_HOME=/u01/app/19.3.0/grid
INSTALL_FILE_1=LINUX.X64_193000_grid_home.zip
GRID_INSTALL_RSP=gridsetup_19c.rsp
GRID_SW_INSTALL_RSP=grid_sw_install_19c.rsp
GRID_SETUP_FILE=setupGrid.sh
FIXUP_PREQ_FILE=fixupPreq.sh
INSTALL_GRID_BINARIES_FILE=installGridBinaries.sh
INSTALL_GRID_PATCH=applyGridPatch.sh
INVENTORY=/u01/app/oraInventory
CONFIGGRID=configGrid.sh
ADDNODE=AddNode.sh
DELNODE=DelNode.sh
ADDNODE_RSP=grid_addnode.rsp
SETUPSSH=setupSSH.expect
DOCKERORACLEINIT=dockeroracleinit
GRID_USER_HOME=/home/grid
SETUPGRIDENV=setupGridEnv.sh
RESET_OS_PASSWORD=resetOSPassword.sh
MULTI_NODE_INSTALL=MultiNodeInstall.py
DB_BASE=/u01/app/oracle
DB_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
INSTALL_FILE_2=LINUX.X64_193000_db_home.zip
DB_INSTALL_RSP=db_sw_install_19c.rsp
DBCA_RSP=dbca_19c.rsp
DB_SETUP_FILE=setupDB.sh
PWD_FILE=setPassword.sh
RUN_FILE=runOracle.sh
STOP_FILE=stopOracle.sh
ENABLE_RAC_FILE=enableRAC.sh
CHECK_DB_FILE=checkDBStatus.sh
USER_SCRIPTS_FILE=runUserScripts.sh
REMOTE_LISTENER_FILE=remoteListener.sh
INSTALL_DB_BINARIES_FILE=installDBBinaries.sh
GRID_HOME_CLEANUP=GridHomeCleanup.sh
ORACLE_HOME_CLEANUP=OracleHomeCleanup.sh
DB_USER=oracle
GRID_USER=grid
FUNCTIONS=functions.sh
COMMON_SCRIPTS=/common_scripts
CHECK_SPACE_FILE=checkSpace.sh
RESET_FAILED_UNITS=resetFailedUnits.sh
SET_CRONTAB=setCrontab.sh
CRONTAB_ENTRY=crontabEntry
EXPECT=/usr/bin/expect
BIN=/usr/sbin
container=true
INSTALL_SCRIPTS=/opt/scripts/install
SCRIPT_DIR=/opt/scripts/startup
GRID_PATH=/u01/app/19.3.0/grid/bin:/u01/app/19.3.0/grid/OPatch/:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DB_PATH=/u01/app/oracle/product/19.3.0/dbhome_1/bin:/u01/app/oracle/product/19.3.0/dbhome_1/OPatch/:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GRID_LD_LIBRARY_PATH=/u01/app/19.3.0/grid/lib:/usr/lib:/lib
DB_LD_LIBRARY_PATH=/u01/app/oracle/product/19.3.0/dbhome_1/lib:/usr/lib:/lib
HOME=/home/grid
Failed to parse kernel command line, ignoring: No such file or directory
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization other.
Detected architecture x86-64.

Welcome to Oracle Linux Server 7.9!

Set hostname to <weeus01devorcl03>.
Failed to parse kernel command line, ignoring: No such file or directory
Failed to parse kernel command line, ignoring: No such file or directory
Failed to parse kernel command line, ignoring: No such file or directory
/usr/lib/systemd/system-generators/systemd-fstab-generator failed with error code 1.
[/usr/lib/systemd/system/systemd-pstore.service:22] Unknown lvalue 'StateDirectory' in section 'Service'
Cannot add dependency job for unit display-manager.service, ignoring: Unit not found.
[  OK  ] Reached target Local Encrypted Volumes.
[  OK  ] Reached target Swap.
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Reached target RPC Port Mapper.
[  OK  ] Created slice Root Slice.
[  OK  ] Listening on Journal Socket.
[  OK  ] Created slice System Slice.
         Starting Read and set NIS domainname from /etc/sysconfig/network...
         Starting Journal Service...
         Starting Rebuild Hardware Database...
         Starting Configure read-only root support...
Couldn't determine result for ConditionKernelCommandLine=|rd.modules-load for systemd-modules-load.service, assuming failed: No such file or directory
Couldn't determine result for ConditionKernelCommandLine=|modules-load for systemd-modules-load.service, assuming failed: No such file or directory
         Mounting FUSE Control File System...
[  OK  ] Created slice system-getty.slice.
[  OK  ] Reached target Local File Systems (Pre).
[  OK  ] Listening on /dev/initctl Compatibility Named Pipe.
[  OK  ] Listening on Delayed Shutdown Socket.
[  OK  ] Created slice User and Session Slice.
[  OK  ] Reached target Slices.
[  OK  ] Started Journal Service.
[  OK  ] Started Read and set NIS domainname from /etc/sysconfig/network.
         Starting Flush Journal to Persistent Storage...
[FAILED] Failed to mount FUSE Control File System.
See 'systemctl status sys-fs-fuse-connections.mount' for details.
[  OK  ] Started Flush Journal to Persistent Storage.
[  OK  ] Started Configure read-only root support.
         Starting Load/Save Random Seed...
[  OK  ] Reached target Local File Systems.
         Starting Mark the need to relabel after reboot...
         Starting Rebuild Journal Catalog...
         Starting Preprocess NFS configuration...
         Starting Create Volatile Files and Directories...
[  OK  ] Started Mark the need to relabel after reboot.
[  OK  ] Started Rebuild Journal Catalog.
[  OK  ] Started Create Volatile Files and Directories.
         Starting Update UTMP about System Boot/Shutdown...
         Mounting RPC Pipe File System...
[  OK  ] Started Load/Save Random Seed.
[  OK  ] Started Update UTMP about System Boot/Shutdown.
[FAILED] Failed to mount RPC Pipe File System.
See 'systemctl status var-lib-nfs-rpc_pipefs.mount' for details.
[DEPEND] Dependency failed for rpc_pipefs.target.
[DEPEND] Dependency failed for RPC security service for NFS client and server.
[  OK  ] Started Preprocess NFS configuration.
[  OK  ] Started Rebuild Hardware Database.
         Starting Update is Completed...
[  OK  ] Started Update is Completed.
[  OK  ] Reached target System Initialization.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Reached target Timers.
[  OK  ] Listening on RPCbind Server Activation Socket.
[  OK  ] Reached target Sockets.
         Starting RPC bind service...
[  OK  ] Started Flexible branding.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Basic System.
         Starting GSSAPI Proxy Daemon...
         Starting Login Service...
         Starting Resets System Activity Logs...
         Starting OpenSSH Server Key Generation...
         Starting LSB: Bring up/down networking...
         Starting Self Monitoring and Reporting Technology (SMART) Daemon...
[  OK  ] Started D-Bus System Message Bus.
[  OK  ] Started RPC bind service.
[  OK  ] Started GSSAPI Proxy Daemon.
[  OK  ] Started Resets System Activity Logs.
         Starting Cleanup of Temporary Directories...
[  OK  ] Reached target NFS client services.
[  OK  ] Reached target Remote File Systems (Pre).
[  OK  ] Reached target Remote File Systems.
         Starting Permit User Sessions...
[  OK  ] Started Login Service.
[  OK  ] Started Cleanup of Temporary Directories.
[  OK  ] Started Permit User Sessions.
[  OK  ] Started Command Scheduler.
[  OK  ] Started OpenSSH Server Key Generation.
[  OK  ] Started LSB: Bring up/down networking.
[  OK  ] Reached target Network.
         Starting OpenSSH server daemon...
         Starting /etc/rc.d/rc.local Compatibility...
[  OK  ] Reached target Network is Online.
         Starting Notify NFS peers of a restart...
[  OK  ] Started /etc/rc.d/rc.local Compatibility.
[  OK  ] Started Console Getty.
[  OK  ] Reached target Login Prompts.
[  OK  ] Started Notify NFS peers of a restart.
[  OK  ] Started OpenSSH server daemon.
05-04-2021 10:50:27 UTC :  : Process id of the program :
05-04-2021 10:50:27 UTC :  : #################################################
05-04-2021 10:50:27 UTC :  :  Starting Grid Installation
05-04-2021 10:50:27 UTC :  : #################################################
05-04-2021 10:50:27 UTC :  : Pre-Grid Setup steps are in process
05-04-2021 10:50:27 UTC :  : Process id of the program :
05-04-2021 10:50:27 UTC :  : Disable failed service sys-fs-fuse-connections.mount
Failed to parse kernel command line, ignoring: No such file or directory
Failed to parse kernel command line, ignoring: No such file or directory
Failed to parse kernel command line, ignoring: No such file or directory
05-04-2021 10:50:27 UTC :  : Resetting Failed Services
05-04-2021 10:50:27 UTC :  : Disable failed service var-lib-nfs-rpc_pipefs.mount
Failed to parse kernel command line, ignoring: No such file or directory
Failed to parse kernel command line, ignoring: No such file or directory
Failed to parse kernel command line, ignoring: No such file or directory
05-04-2021 10:50:27 UTC :  : Resetting Failed Services
05-04-2021 10:50:27 UTC :  : Sleeping for 60 seconds
[  OK  ] Started Self Monitoring and Reporting Technology (SMART) Daemon.
[  OK  ] Reached target Multi-User System.
[  OK  ] Reached target Graphical Interface.
         Starting Update UTMP about System Runlevel Changes...
[  OK  ] Started Update UTMP about System Runlevel Changes.

Oracle Linux Server 7.9
Kernel 5.4.17-2102.200.13.el8uek.x86_64 on an x86_64

weeus01devorcl03 login: 05-04-2021 10:51:27 UTC :  : Systemctl state is running!
05-04-2021 10:51:27 UTC :  : Setting correct permissions for /bin/ping
05-04-2021 10:51:27 UTC :  : Public IP is set to 172.17.0.6
05-04-2021 10:51:27 UTC :  : RAC Node PUBLIC Hostname is set to weeus01devorcl03
05-04-2021 10:51:27 UTC :  : weeus01devorcl03 already exists : 172.17.0.6       weeus01devorcl03.example.com    weeus01devorcl03
172.17.0.8      weeus01devorcl03-vip.example.com        weeus01devorcl03-vip
172.17.0.5      weeus01devorcl03-cman1.example.com      weeus01devorcl03-cman1, no  update required
05-04-2021 10:51:27 UTC :  : Preparing host line for weeus01devorcl03-priv
05-04-2021 10:51:27 UTC :  : Adding \n192.168.17.150\tweeus01devorcl03-priv.example.com\tweeus01devorcl03-priv to /etc/hosts
05-04-2021 10:51:27 UTC :  : weeus01devorcl03-vip already exists : 172.17.0.8   weeus01devorcl03-vip.example.com        weeus01devorcl03-vip, no  update required
05-04-2021 10:51:27 UTC :  : scantest.localdomain already exists : 172.17.0.7   scantest.localdomain.example.com        scantest.localdomain, no  update required
05-04-2021 10:51:27 UTC :  : Preapring Device list
05-04-2021 10:51:27 UTC :  : Changing Disk permission and ownership /dev/asm_disk1
05-04-2021 10:51:27 UTC :  : DNS_SERVERS is set to empty. /etc/resolv.conf will use default dns docker embedded server.
05-04-2021 10:51:27 UTC :  : #####################################################################
05-04-2021 10:51:27 UTC :  :  RAC setup will begin in 2 minutes
05-04-2021 10:51:27 UTC :  : ####################################################################
05-04-2021 10:51:29 UTC :  : ###################################################
05-04-2021 10:51:29 UTC :  : Pre-Grid Setup steps completed
05-04-2021 10:51:29 UTC :  : ###################################################
05-04-2021 10:51:29 UTC :  : Checking if grid is already configured
05-04-2021 10:51:29 UTC :  : Process id of the program :
05-04-2021 10:51:29 UTC :  : Public IP is set to 172.17.0.6
05-04-2021 10:51:29 UTC :  : RAC Node PUBLIC Hostname is set to weeus01devorcl03
05-04-2021 10:51:29 UTC :  : Domain is defined to example.com
05-04-2021 10:51:29 UTC :  : Default setting of AUTO GNS VIP set to false. If you want to use AUTO GNS VIP, please pass DHCP_CONF as an env parameter set to true
05-04-2021 10:51:29 UTC :  : RAC VIP set to 172.17.0.8
05-04-2021 10:51:29 UTC :  : RAC Node VIP hostname is set to weeus01devorcl03-vip
05-04-2021 10:51:29 UTC :  : SCAN_NAME name is scantest.localdomain
05-04-2021 10:51:29 UTC :  : SCAN PORT is set to empty string. Setting it to 1521 port.
05-04-2021 10:51:29 UTC :  : 172.17.0.7
05-04-2021 10:51:29 UTC :  : SCAN Name resolving to IP. Check Passed!
05-04-2021 10:51:29 UTC :  : SCAN_IP name is 172.17.0.7
05-04-2021 10:51:29 UTC :  : RAC Node PRIV IP is set to 192.168.17.150
05-04-2021 10:51:29 UTC :  : RAC Node private hostname is set to weeus01devorcl03-priv
05-04-2021 10:51:29 UTC :  : CMAN_NAME set to the empty string
05-04-2021 10:51:29 UTC :  : CMAN_IP set to the empty string
05-04-2021 10:51:29 UTC :  : Cluster Name is not defined
05-04-2021 10:51:29 UTC :  : Cluster name is set to 'racnode-c'
05-04-2021 10:51:29 UTC :  : Password is empty string
05-04-2021 10:51:29 UTC :  : Common OS Password string is set for Grid user
05-04-2021 10:51:29 UTC :  : Common OS Password string is set for  Oracle user
05-04-2021 10:51:29 UTC :  : Common OS Password string is set for Oracle Database
05-04-2021 10:51:29 UTC :  : Setting CONFIGURE_GNS to false
05-04-2021 10:51:29 UTC :  : Location for User script SCRIPT_ROOT set to /common_scripts
05-04-2021 10:51:29 UTC :  : IGNORE_CVU_CHECKS is set to true
05-04-2021 10:51:29 UTC :  : Oracle SID is set to ORCLCDB
05-04-2021 10:51:29 UTC :  : Oracle PDB name is set to ORCLPDB
05-04-2021 10:51:29 UTC :  : GRID_RESPONSE_FILE is set to grid_sample.rsp, so ASM_DEVICE_LIST env variable will be ignored
05-04-2021 10:51:29 UTC :  : Setting random password for grid user
05-04-2021 10:51:29 UTC :  : Setting random password for oracle user
05-04-2021 10:51:29 UTC :  : Calling setupSSH function
05-04-2021 10:51:29 UTC :  : SSh will be setup among racnode1 nodes
05-04-2021 10:51:29 UTC :  : Running SSH setup for grid user between nodes racnode1
05-04-2021 10:51:59 UTC :  : Running SSH setup for oracle user between nodes racnode1
05-04-2021 10:52:00 UTC : : SSH check failed for the grid@racnode1! Error occurred during SSH setup
05-04-2021 10:52:00 UTC : : Error has occurred in Grid Setup, Please verify!`

Thanks,
Anand.

**Comment by psaini79** [comment]
Please share the following details:

## Docker Host

- Get the output of `docker info`
- Systemctl output `systemctl status docker -l`
- OS Details `cat /etc/oracle-release`
- Firewalld Status `systemctl status firewalld`
- Selinux Status `getenforce`
- Output of /etc/sysctl.conf `cat /etc/sysctl.conf`
- Kernel Version `uname -r`

## Container

- Login to container `docker exec -i -t racnode1 /bin/bash`
- go to  `/u01/app/grid`
- Zip the diag directory and upload it.

**Comment by Anand0583** [comment]
We are able to start-up a Single RAC Node. But for multiple RAC nodes to be started is it only supported via Docker MACVLAN or it will be supported via overlay or IPVlan. As we cant have promiscuous mode being enabled.

**Comment by Anand0583** [comment]
@psaini79 please let us know your comments.

**Comment by psaini79** [comment]
@Anand0583 

You can use IPVLAN  or Macvlan. CHeck we have also 21.3 release available. Let me know if you are still seeing any issues.

**Comment by Anand0583** [comment]
@psaini79 but we are trying to deploy the Docker images on Azure Virtual Machine or AKS and on both I dont think IPVLAN or MACVLAN is supported. Is it a hard requirement to have IPVLAN or MACVLAN supported for enabling RAC setup.

**Comment by psaini79** [comment]
@Anand0583 

Please refer following GitHUb Thread:

https://github.com/oracle/docker-images/issues/2255

Note: We do not support Oracle RAC on Docker Azure.

**Comment by saurabhaahujaa** [comment]
Have you tried in Oracle Cloud with IPVLAN or MACVLAN over VLAN network? There is option to enable video acceleration in compute instances. I have tested to be working with it, please validate and let us know if we can close this issue?

"Hardware-assisted (SR-IOV) networking
For low-latency workloads such as video streaming, real-time applications, and large or clustered databases. Does not support live migration."

**Comment by psaini79** [comment]
We do not support Oracle RAC on Docker/Podman on Cloud. Please try RAC on Docker/Podman on  on-premise machine deployed on Ol7 for RAC on  Docker and Ol8 for RAC on Podman.
