### ISSUE TITLE
oracle/database:18.4.0-xe does not exist 

### ISSUE THREAD

**Issue by ortizman** [oracle/docker-images#1946]
The image is no longer accessible

`docker pull oracle/database:18.4.0-xe
`

response

> Error response from daemon: pull access denied for oracle/database, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

`docker -v`

> Docker version 20.10.6, build 370c289

Do you have any idea why it is no longer available?

Thanks

**Comment by gvenzl** [comment]
Unfortunately, there has never been an Oracle official 18c XE image on Docker Hub.
However, there are many community-provided images for XE on Docker Hub, e.g. (shameless plug here :upside_down_face: ) [`docker pull gvenzl/oracle-xe:18.4.0`](https://hub.docker.com/r/gvenzl/oracle-xe)
