### ISSUE TITLE
java -jar lib/kvstore.jar ping - ConnectException when using IPAddress

### ISSUE THREAD

**Issue by aambasta** [oracle/docker-images#196]
I created a Oracle Linux VM (ipAddr 192.168.10.2) on my windows machine.
On this VM I further created a kvlite docker container.

In **Dockerfile** following is CMD issued:
`CMD ["java", "-jar", "lib/kvstore.jar", "kvlite"]`

Once kvlite docker container was created I ran following commands on my VM:
**$ docker run --name nosql-container -d kvlite:latest**
**$ docker exec -it nosql-container bash**

On the container bash prompt I try to ping my client using following command (but using VM IpAddress and not **localhost**):
`# java -jar lib/kvstore.jar ping -port 5000 -host 192.168.10.2`

This however throws an exception 
**_Picked up _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
Could not connect to registry at 192.168.10.2:5000 Unable to connect to the storage node agent at host 192.168.10.2, port 5000, which may not be running; nested exception is:
        java.rmi.ConnectException: Connection refused to host: 192.168.10.2; nested exception is:
        java.net.ConnectException: Connection refused
Can't find store topology: Could not contact any RepNode at: [192.168.10.2:5000]_**

But, things works fine when I use -host as localhost instead i.e., 
`# java -jar lib/kvstore.jar ping -port 5000 -host localhost`

To resolve this issue I tried following:
- I stopped my kvlite docker container
- Changed config.xml ($KVROOT/config.xml) for value hostname to IpAddress
- Re-Started my kvlite docker container, but this didn't helped, container couldn't start

Next I tried to re-create a new docker image for kvlite issuing below CMD:
`CMD ["java", "-jar", "lib/kvstore.jar", "kvlite", "-host", "192.168.10.2", "-port", "5000"]`

But here also when I tried starting kvlite docker container, it didn't start.

I even verified my **/etc/hosts** file for entry of IpAddress-192.168.10.2.

Any help appreciated in advance.

**Comment by brunoborges** [comment]
Hey @gvenzl, could you find someone on the NoSQL team to help on this one?

**Comment by anandchandak** [comment]
The IP address for the docker container running the store is different. To get the container ip address, do the following:
Get the docker container ip address. Issue this command immediately after creating the container : docker inspect nosql-container | grep -i ipadd
 
You can then ping the store using the container IP address:
 
docker run --name nosql-container -d kvlite:latest
docker exec -it nosql-container bash
 
On the docker bash prompt, issue the following command:
java -jar lib/kvstore.jar ping -port 5000 -host <container_ip_address>

**Comment by aambasta** [comment]
@anandchandak Thanks for this info. Container IP Address is **172.17.0.2**
But further I need to access this NoSQL db remotely from a Java Client (on my windows desktop).


The Java code-snippet below:

`KVStore store = KVStoreFactory.getStore(new KVStoreConfig("kvstore", "192.168.10.2:5000"));`


This throws an exception:
**_oracle.kv.FaultException: Could not contact any RepNode at: 192.168.10.2:5000_**
....
**_Caused by: java.rmi.UnknownHostException: Unknown host: ecfe59938ea4; nested exception is:_**


When I use container ip **172.17.0.2** instead, I still get **UnknownHostException**

Any help appreciated.

**Comment by brunoborges** [comment]
@aambasta did you bind port 5000 of the container, to the host?

**Comment by aambasta** [comment]
@brunoborges Yes actually I tried that as well but getting same exception :(

`$ docker run --name nosql-container -p 5000:5000 -d kvlite:latest`

**Comment by aambasta** [comment]
I resolved the issue by adding a param --net=host when running nosql-container
`$ docker run --name nosql-container --net=host -p 5000:5000 -d kvlite:latest`

Now instead of IPAddress you can use VM hostname in Java Client code to access kvlite DB.
`KVStore store = KVStoreFactory.getStore(new KVStoreConfig("kvstore", "VMHostname:5000"));`
