### ISSUE TITLE
Using docker-compose can't expose 1521 as 3122, 1521:1521 works

### ISSUE THREAD

**Issue by LucaGabi** [oracle/docker-images#1961]
Hi,

Using docker-compose can't expose port 1521 as 3122, 1521:1521 works, why ?

**Comment by AmedeeBulle** [comment]
This is really a `docker-compose` question...

There is no reason it should not work; it would help if you share your compose file -- my best guess it that you might have the ports in the wrong order...

**Comment by LucaGabi** [comment]
Thanks I used nmap and it was not showing but it was there .. I used nc for testing .. 

Can we use ssl/tls certificates with Oracle XE ?

**Comment by gvenzl** [comment]
>Can we use ssl/tls certificates with Oracle XE ?

There is nothing in XE that I'm aware of that should prevent you from using SSL certificates. You can find the doc section for SSL [here](https://docs.oracle.com/en/database/oracle/oracle-database/18/dbseg/configuring-secure-sockets-layer-authentication.html#GUID-6AD89576-526F-4D6B-A539-ADF4B840819F).
