### ISSUE TITLE
Cannot find sqlldr

### ISSUE THREAD

**Issue by SoulHeretic** [oracle/docker-images#1965]
Hello everyone,

I am trying to import a tbl file with dummy data into my database, however I cannot figure out how to get around the "the sqlldr: not found" problem. I cd into a sql_loader which is a file I made in my home directory that has my tbl file filled with dummy data along with the control file.
Then I use the following line:
 sqlldr userid=system/oracle control=control.lst log=track.log
and then I get "the sqlldr: not found" message. Does my sql_loader file need to be in a different location? I tried doing it inside the database but that doesn't work either.

**Comment by cjbj** [comment]
@SoulHeretic is this a question about the dockerfiles in the repo?

**Comment by SoulHeretic** [comment]
Sort of. I would like to use SQL Loader so I can import data from an external file since that is the only way to do it in Oracle. But since I cannot reach/find the SQL Loader I am wondering if I need to add something to the repo in my ssh server, or am I tackling this wrong. I tried to follow this: https://github.com/oracle/docker-images/issues/643#issuecomment-434928819 
but a lot of the advice is outdated and/or not sure it would fix my issue in particular.

**Comment by SoulHeretic** [comment]
Nevermind, I see what was going wrong.
