### ISSUE TITLE
/home/oracle not found during build of container

### ISSUE THREAD

**Issue by robingoetzuscold** [oracle/docker-images#1973]
Hello all,

I am trying to build a Docker image locally on a M1 Mac.

I downloaded and added the zip file in the 19.3.0 as described.
![image](https://user-images.githubusercontent.com/47578600/121726917-cf8b4d80-cab0-11eb-8498-7fc82aa0ec2a.png)

Then I am trying to build the container image running from within the dockerfiles folder:

`./buildContainerImage.sh -v 19.3.0 -e -i`

However, the build fails with the following error:
![image](https://user-images.githubusercontent.com/47578600/121726674-7d4a2c80-cab0-11eb-8013-ab14a77dac52.png)

I am reaching out to see if I am missing something or if there is an issue with the build.

Thank you already for all help!

**Comment by Djelibeybi** [comment]
Please see https://github.com/oracle/docker-images/discussions/1951 for details on the lack of support for M1 based Macs.
