### ISSUE TITLE
Oracle Linux 8 Node.js 14-oracledb Invalid Dockerfile CMD Argument

### ISSUE THREAD

**Issue by WGMurray** [oracle/docker-images#1987]
This issue should be pretty short and sweet. The issue itself is also pretty benign.

In the[ oraclelinux8-nodejs:14-oracledb module](https://github.com/oracle/docker-images/tree/main/OracleLinuxDevelopers/oraclelinux8/nodejs/14-oracledb) Dockerfile the CMD instruction passes a parameter "v" to the "/bin/node" call. As a result an error occurs if built as is. 

```
FROM oraclelinux:8-slim

COPY nodejs.module /etc/dnf/modules.d/nodejs.module

RUN microdnf install oracle-instantclient-release-el8 oraclelinux-developer-release-el8 && \
    microdnf install libaio \
                     oracle-instantclient-basic \
                     node-oracledb-node14 \
                     && \
    microdnf clean all

ENV NODE_PATH=/usr/local/lib/node_modules/

CMD ["/bin/node", "v"]
```

Instead it should just have a preceding hyphen to mark it as a parameter for the node call to print out the version of node. 

`CMD ["/bin/node", "-v"]`

I realize this is really not much of an issue as these are more templates than anything, but I thought it was worth at least mentioning that the current Dockerfile for this module will not by itself build an image that can be run. 

I apologize if I'm not meeting some standard format or placing this issue correctly. I honestly have very little interaction with authors/projects/communities on GitHub. 

Regards,
Grant

**Comment by totalamateurhour** [comment]
Thanks for reporting, Grant. We will get this fixed.
