### ISSUE TITLE
Oracle database should consider cgroups

### ISSUE THREAD

**Issue by beegee1** [oracle/docker-images#1989]
Hello everyone,

would it be possible that the Oracle database single instance reads the configured cgroups on DB creation and on DB startup to setup the sga_target, pga_target, totalMemory, cpu_limit accordingly? 20 percent of sga could be used for pga (https://www.morganslibrary.org/reference/memory_management.html) as a default for example and additionally make it configurable.
This is especially interesting when the DB is operated in a Kubernetes cluster. Currently the Oracle DB assumes that the whole memory and CPU of the node can be used, which is not a good idea.

**Comment by abhisbyk** [comment]
@beegee1  PR #2238 addresses this issue.
