### ISSUE TITLE
Oracle Database PSU patches

### ISSUE THREAD

**Issue by montge** [oracle/docker-images#199]
Please provide recommended docker files for PSU installation for Docker based database.

**Comment by yahonda** [comment]
Hi,

I'm maintaining a Ruby on Rails ActiveRecord database connection adapter for Oracle database called Oracle enhanced adapter.

As of right now, I have manually installed Oracle 12c database instance to test it.
I'm thinking about to migrate it to Oracle 12c database running on Docker,  then I got the original error below. It is reported as https://github.com/rsim/oracle-enhanced/issues/1130 .

```sql
ORA-12801: error signaled in parallel query server P000
ORA-01006: bind variable does not exist: SELECT view_name FROM all_views where owner = SYS_CONTEXT('userenv', 'session_user')
```

By installing Oracle 12c multitenant on Oracle Linux 7 without docker and applied  "DB PSU 12.1.0.2.161018 (Oct2016)",
the original error has been addressed. Unfortunately, I am not able to apply this PSU to my Oracle database 12c running on Docker.

I'm very interested in this request will be available and/or I'd like to know if there is a way to apply this "DB PSU 12.1.0.2.161018 (Oct2016)" manually on top of Oracle database 12.1.0.2 running on docker.

Thanks.

**Comment by gvenzl** [comment]
Indeed, we can see the need for that. The newer patches also require a new version of the `OPatch` utility which will also have to be downloaded at least once and provided one.
Given that patches do change the binaries in the ORACLE_HOME and the proliferation of different needs for different patches, users will have to create their own patched image off the base image. I'll look into providing a sample that takes the base image and applies user provided patches to a new image.

**Comment by gvenzl** [comment]
This is fixed, see [OracleDatabase/samples/applypatch](https://github.com/oracle/docker-images/tree/master/OracleDatabase/samples/applypatch)
