### ISSUE TITLE
Are this available internally for oracle developers? 

### ISSUE THREAD

**Issue by haansanghavi** [oracle/docker-images#2021]
Hi, 

I am trying to find this docker images internally inside oracle on any platform but did not find any proper place. 

If any other developer know where this might be available internally, please let me know. 

From,
A fellow oracle developer

**Comment by tbarnes-us** [comment]
Is your question answered? I see you asked similar questions on internal slack.

**Comment by Djelibeybi** [comment]
Will respond internally.
