### ISSUE TITLE
Create Oracle Database Single Instance Dockerfile for 19.8

### ISSUE THREAD

**Issue by alan-czajkowski** [oracle/docker-images#2034]
https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/dockerfiles

19.3 is the highest available version, need 19.8

**Comment by gvenzl** [comment]
Please use the [patching extension](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/extensions/patching) to build a 19.8 image.
