### ISSUE TITLE
Is there any plans to support Oracle Instant Client for macOS M1? 

### ISSUE THREAD

**Issue by tjlee** [oracle/docker-images#2035]
Is there any plans to support Oracle Instant Client for macOS M1?

**Comment by cjbj** [comment]
Planned but no ETA.

Users have reported the Intel Instant Client works.  (Also we now have Instant Client Linux ARM)

**Comment by tjlee** [comment]
@cjbj one of our users got the following:
`/Users/xxx/Oracle/instantclient_19_8/libocijdbc19.dylib: mach-o, but wrong architecture.`
when he tries to use Instant client on M1. 

Do you need any extended logs?

**Comment by cjbj** [comment]
@tjlee since this is a not a supported platform, and I have no access to M1, I am unable to comment.  Sorry!
