### ISSUE TITLE
denied: requested access to the resource is denied.

### ISSUE THREAD

**Issue by ristagg** [oracle/docker-images#2036]
When trying to do

 docker run --name oracle-build -p 1521:1521 -p 5500:5500 oracle/database:19.3.0-ee

as per the instructions in:  https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/samples/prebuiltdb

Unable to find image 'oracle/database:19.3.0-ee' locally
docker: Error response from daemon: pull access denied for oracle/database, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by gvenzl** [comment]
Hi @ristagg,

As per the instructions in point 1:

> First, you need to start up a container to get a database created. **For this you will have to have the image already built.**

Please build your `oracle/database:19.3.0-ee` image first and try again.
