### ISSUE TITLE
Oracle database 12.1.0.2 is not working

### ISSUE THREAD

**Issue by ukreddy-erwin** [oracle/docker-images#2040]
I have registered with the docker image of oracle database and got below link to pull the image.

docker pull store/oracle/database-enterprise:12.2.0.1

No other tags available to see on the page. But some how I got information about 12.1.0.2

With 12.2.0.1, I am able to run a database and connect to it.
But with 12.1.0.2, the database is not connecting.

docker service create --with-registry-auth --network=oracle_net --name Oracledb_39 -p target=1521 store/oracle/database-enterprise:12.2.0.1

docker service create --with-registry-auth --network=oracle_net --name Oracledb_39 -p target=1521 store/oracle/database-enterprise:12.1.0.2

The 12.1.0.2 with dbeaver client to connect:

![image](https://user-images.githubusercontent.com/21240709/128014689-e0883852-3e84-4ff6-a9dd-88fde5d78888.png)

But able to connect with 12.2.0.1
![image](https://user-images.githubusercontent.com/21240709/128014761-83571aef-cf6b-4f9e-a99c-3432cc483908.png)

Please suggest how to connect to 12.1.0.2 or any of 12.1.x

And also please share how to see all the tags available for oracle database docker image.

**Comment by gvenzl** [comment]
The Docker Store images are no longer available, please use 19c onwards from container-registry.oracle.com
