### ISSUE TITLE
21C - 21.3.0 docker run - when SGA/PGA memory parameters of any size are specified the command fails

### ISSUE THREAD

**Issue by tedonmain** [oracle/docker-images#2069]
Docker Desktop 4GB Memory, 1GB swap

-e INIT_SGA_SIZE=<your database SGA memory in MB> \
-e INIT_PGA_SIZE=<your database PGA memory in MB> \

When these parameters are specified using _**docker run ...**_ the container build fails with a comment that the shared_pool_size is not set. 

Note: Removing the SGA/PGA parameters, _**docker run ...**_   container builds successfully.

**Comment by yunus-qureshi** [comment]
Please attach the logs
