### ISSUE TITLE
Creation of PDB fails in Oracle 21 c  [FATAL] Error while executing "/opt/oracle/product/21c/dbhome_1/rdbms/admin/execemx.sql"

### ISSUE THREAD

**Issue by cvranjith** [oracle/docker-images#2071]
Below is the docker arguments command used.

docker run -dit --name oradb21c \
-p 1531:1521 -p 5510:5500 \
-e ORACLE_SID=CDB1 \
-e ORACLE_PDB=PDB1 \
-e ORACLE_PWD=XXXX \
-e ORACLE_CHARACTERSET=AL32UTF8 \
-e ENABLE_ARCHIVELOG=false \

Tried with and without INIT_SGA_SIZE & INIT_PGA_SIZE.

Db creation fails after 46%

[FATAL] Error while executing "/opt/oracle/product/21c/dbhome_1/rdbms/admin/execemx.sql". Refer to "/opt/oracle/cfgtoollogs/dbca/CDB1/execemx0.log" for more details. Error in Process: /opt/oracle/product/21c/dbhome_1/perl/bin/perl
[ 2021-08-23 07:24:49.205 UTC ] [WARNING] ORA-65017: seed pluggable database may not be dropped or altered

Attached logs
[docker-logs.txt](https://github.com/oracle/docker-images/files/7029988/docker-logs.txt)
[execemx0.log](https://github.com/oracle/docker-images/files/7029991/execemx0.log)

**Comment by yunus-qureshi** [comment]
got in touch with @cvranjith for env.

**Comment by cvranjith** [comment]
Problem was because I was using "overlay" driver. I changed to "[overlay2](https://docs.docker.com/storage/storagedriver/overlayfs-driver/)" and it worked. 
Thank you @yunus-qureshi  for helping out
