### ISSUE TITLE
Windows Docker images?

### ISSUE THREAD

**Issue by StefanScherer** [oracle/docker-images#208]
I just saw this GitHub repo with lots of Dockerfiles for Oracle products. 
Are there plans to expand this for Windows Docker images as well?

So instead having multiple solutions from the community to build a Windows Java Docker image it would be better to have a standard way to use.

What about eg. Oracle Database as Windows Docker image? Is that possible?

Thanks!

Stefan Scherer
Docker Captain
Microsoft MVP - Cloud and Datacenter Management

**Comment by brunoborges** [comment]
All maintainers are Mac and Linux users, so we can't really commit to provide Windows Docker Images. But it shouldn't be hard for the community to fork these recipes and make them work on Windows environments.

But I'll leave this issue open for a while to see if there is greater interest.

Thanks for the suggestion.

**Comment by StefanScherer** [comment]
See eg. #209 running from a Mac as well.

**Comment by StefanScherer** [comment]
Just out of curiosity. Are there plans to provide such images on Docker Hub? I know of some licensing / redistribution problems around Oracle Java and so on. That's why most people use OpenJDK, but there is no such version for Windows.

I'm just wondering, because Microsoft also provides their Windows base images with windowsservercore and nanoserver on Docker Hub using foreign addresses to keep the download artifacts at Microsoft CDN servers. Using such docker images you accept a specific license and that's it.
See https://hub.docker.com/r/microsoft/windowsservercore/ for details.

**Comment by Djelibeybi** [comment]
We have no way to validate/test the pull request (no Windows available) and we cannot ship our images on the Docker Hub.

We announced the Oracle Container Registry at Oracle OpenWorld 2016 which will host Oracle proprietary software images, but we cannot host Windows-based images on this registry as we do not have legal permission to distribute Windows binaries.

**Comment by StefanScherer** [comment]
OK, good to know. Thanks for the details. Maybe AppVeyor can help you in near future so you don't need own Windows machines.

**Comment by Djelibeybi** [comment]
FYI, the Container Registry has launched at https://container-registry.oracle.com. I'm going to close this issue as we currently have no plans to distribute Windows-based Docker images.
