### ISSUE TITLE
While building docker images for os database 28c  in my mac m1 ... It is giving me such kind of error

### ISSUE THREAD

**Issue by radhika2802** [oracle/docker-images#2084]
=> ERROR [3/3] RUN chmod ug+x /install/*.sh &&     sync &&     /insta  83.6s ------                                                                        
 > [3/3] RUN chmod ug+x /install/*.sh &&     sync &&     /install/checkSpace.sh &&     cd /install &&     yum -y install openssl oracle-database-preinstall-18c &&     sed -i -e 's/\(oracle\s\+hard\s\+nofile\)/# \1/' /etc/security/limits.d/oracle-database-preinstall-18c.conf &&     yum -y localinstall https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm &&     rm -rf /var/cache/yum &&     rm -rf /var/tmp/yum-* &&     mkdir -p /opt/oracle/scripts/setup &&     mkdir /opt/oracle/scripts/startup &&     ln -s /opt/oracle/scripts /docker-entrypoint-initdb.d &&     mkdir -p /opt/oracle/oradata /home/oracle &&     chown -R oracle:oinstall /opt/oracle /home/oracle &&     mv /install/runOracle.sh /opt/oracle/ &&     mv /install/setPassword.sh /opt/oracle/ &&     mv /install/checkDBStatus.sh /opt/oracle/ &&     mv /install/oracle-xe-18c.conf /etc/sysconfig/ &&     ln -s /opt/oracle/setPassword.sh / &&     cd $HOME &&     rm -rf /install &&     chmod ug+x /opt/oracle/*.sh:

**Comment by gvenzl** [comment]
Oracle Database is not available for ARM / M1 chips.
See https://github.com/oracle/docker-images/discussions/1951 for further information.
