### ISSUE TITLE
Kubernetes Deployment for Oracle database with helm

### ISSUE THREAD

**Issue by zjcnew** [oracle/docker-images#2095]
The database file has been persisted, But when the pod is evicted, access to the database fails.

[oracle@ora12201-1-oracle-db-c965786df-fbgd7 /]$ sqlplus sys/passwd@127.0.0.1:1521/db0 as sysdba

SQL*Plus: Release 12.2.0.1.0 Production on Wed Sep 8 10:39:21 2021

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

ERROR:
ORA-12514: TNS:listener does not currently know of service requested in connect
descriptor

Enter user-name:

**Comment by abhisbyk** [comment]
@zjcnew If the pod is evicted, then the listener service running in that pod will also be down causing ORA-12514.
Can you share more details about you cluster configuration, deployment info etc (using kubectl describe) to find out why this pod eviction is happening ?
