### ISSUE TITLE
buildDockerImage.sh errors out becase "-bash: /usr/java/default/bin/java: Permission denied"

### ISSUE THREAD

**Issue by kharels** [oracle/docker-images#210]
I build the OracleJava and then tried to build the weblogic container but I keep running into this error below. Please let me know if you have any questions.

# ./buildDockerImage.sh -d -v 12.2.1
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip: OK
=====================
Building image 'oracle/weblogic:12.2.1-developer' ...
Sending build context to Docker daemon 389.1 MB
Sending build context to Docker daemon
Step 0 : FROM oracle/serverjre:8
 ---> dd1f7577b61a
Step 1 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in ffa0d42c1534
 ---> d362cbe05183
Removing intermediate container ffa0d42c1534
Step 2 : ENV FMW_PKG fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip FMW_JAR fmw_12.2.1.0.0_wls_quick.jar ORACLE_HOME /u01/oracle USER_MEM_ARGS "-Djava.security.egd=file:/dev/./urandom" DEBUG_FLAG true PRODUCTION_MODE dev PATH $PATH:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin
 ---> Running in 2e8cba2c60ed
 ---> 39d25aa0efb0
Removing intermediate container 2e8cba2c60ed
Step 3 : COPY $FMW_PKG install.file oraInst.loc /u01/
 ---> 0be0addb746b
Removing intermediate container be80bf3582da
Step 4 : RUN chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file
 ---> Running in 9a1e7e665cd1
/
**-bash: /usr/java/default/bin/java: Permission denied**
Removing intermediate container 9a1e7e665cd1
The command '/bin/sh -c chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 126
There was an error building the image.

**Comment by gvenzl** [comment]
This looks like a permission issue inherited from the serverjre:8 image. @brunoborges, can you check whether you can reproduce the problem?

**Comment by brunoborges** [comment]
I cannot. Works just fine here... for months...

**Comment by gvenzl** [comment]
@kharels, can you share the build log of your OracleJava image build.

**Comment by kharels** [comment]
Since I didnt have previous build log, I deleted all the old container images and tried rebuilding everything again. I ran into same issue. Please see the logs below.

# ./build.sh
Sending build context to Docker daemon 59.91 MB
Sending build context to Docker daemon
Step 0 : FROM oraclelinux:latest
latest: Pulling from oraclelinux
8f262c55eef2: Pull complete
1a8a6d51728e: Pull complete
3690474eb5b4: Already exists
Digest: sha256:8419f0f8be4b28d686547e292be836ff0174e43f4292e62c26ecab0fb0034cf5
Status: Downloaded newer image for oraclelinux:latest
 ---> 1a8a6d51728e
Step 1 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in 9411ce52cc62
 ---> 21d91019da6c
Removing intermediate container 9411ce52cc62
Step 2 : ENV JAVA_PKG server-jre-8u*-linux-x64.tar.gz JAVA_HOME /usr/java/default
 ---> Running in c76204ca6add
 ---> cbd4dfb7e3ec
Removing intermediate container c76204ca6add
Step 3 : ADD $JAVA_PKG /usr/java/
 ---> 32989f2bf8b3
Removing intermediate container 871e9eeba873
Step 4 : RUN export JAVA_DIR=$(ls -1 -d /usr/java/*) &&     ln -s $JAVA_DIR /usr/java/latest &&     ln -s $JAVA_DIR /usr/java/default &&     alternatives --install /usr/bin/java java $JAVA_DIR/bin/java 20000 &&     alternatives --install /usr/bin/javac javac $JAVA_DIR/bin/javac 20000 &&     alternatives --install /usr/bin/jar jar $JAVA_DIR/bin/jar 20000
 ---> Running in cf6867081814
 ---> a22b26ba6df8
Removing intermediate container cf6867081814
Successfully built a22b26ba6df8

# ./buildDockerImage.sh -d -v 12.2.1
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip: OK
=====================
Building image 'oracle/weblogic:12.2.1-developer' ...
Sending build context to Docker daemon 389.1 MB
Sending build context to Docker daemon
Step 0 : FROM oracle/serverjre:8
 ---> a22b26ba6df8
Step 1 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in e791a368d26a
 ---> 782153e25a06
Removing intermediate container e791a368d26a
Step 2 : ENV FMW_PKG fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip FMW_JAR fmw_12.2.1.0.0_wls_quick.jar ORACLE_HOME /u01/oracle USER_MEM_ARGS "-Djava.security.egd=file:/dev/./urandom" DEBUG_FLAG true PRODUCTION_MODE dev PATH $PATH:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin
 ---> Running in 9127a244d499
 ---> 553d40c78710
Removing intermediate container 9127a244d499
Step 3 : COPY $FMW_PKG install.file oraInst.loc /u01/
 ---> 7cecbde0d5f7
Removing intermediate container 3fb20b5c4937
Step 4 : RUN chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file
 ---> Running in 90005d540ddc
/
-bash: /usr/java/default/bin/java: Permission denied
Removing intermediate container 90005d540ddc
The command '/bin/sh -c chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 126
There was an error building the image.

**Comment by gvenzl** [comment]
That looks all good so far. I wonder what the permissions of your java binary is. Can you please jump into your Java Docker image and do a `ls -al` on your Java bin folder:

To jump into the container`docker run -ti oracle/serverjre:8 /bin/bash`
And then execute `ls -al /usr/java/default/bin/`:

Here is what I get, all permissions are correct:

    [root@a5a79a5fec7d /]# ls -al /usr/java/default/bin/
    total 444
    drwxr-xr-x 1 10 143    398 Sep 22 23:23 .
    drwxr-xr-x 1 10 143    164 Sep 22 23:24 ..
    -rwxr-xr-x 1 10 143   7965 Sep 22 23:23 appletviewer
    -rwxr-xr-x 1 10 143   7941 Sep 22 23:23 extcheck
    -rwxr-xr-x 1 10 143   7973 Sep 22 23:23 idlj
    -rwxr-xr-x 1 10 143   7925 Sep 22 23:23 jar
    -rwxr-xr-x 1 10 143   7957 Sep 22 23:23 jarsigner
    -rwxr-xr-x 1 10 143   7734 Sep 22 23:23 java
    -rwxr-xr-x 1 10 143   1809 Sep 22 23:23 java-rmi.cgi
    -rwxr-xr-x 1 10 143   7941 Sep 22 23:23 javac
    -rwxr-xr-x 1 10 143   7941 Sep 22 23:23 javah
    -rwxr-xr-x 1 10 143   7925 Sep 22 23:23 jcmd
    -rwxr-xr-x 1 10 143   7941 Sep 22 23:23 jdeps
    -rwxr-xr-x 1 10 143   7941 Sep 22 23:23 jjs
    -rwxr-xr-x 1 10 143   7925 Sep 22 23:23 jps
    -rwxr-xr-x 1 10 143   7949 Sep 22 23:23 jrunscript
    -rwxr-xr-x 1 10 143   7941 Sep 22 23:23 keytool
    -rwxr-xr-x 1 10 143   7949 Sep 22 23:23 native2ascii
    -rwxr-xr-x 1 10 143   8149 Sep 22 23:23 orbd
    -rwxr-xr-x 1 10 143   7957 Sep 22 23:23 pack200
    -rwxr-xr-x 1 10 143   7997 Sep 22 23:23 policytool
    -rwxr-xr-x 1 10 143   7925 Sep 22 23:23 rmic
    -rwxr-xr-x 1 10 143   7941 Sep 22 23:23 rmid
    -rwxr-xr-x 1 10 143   7949 Sep 22 23:23 rmiregistry
    -rwxr-xr-x 1 10 143   7957 Sep 22 23:23 schemagen
    -rwxr-xr-x 1 10 143   7965 Sep 22 23:23 servertool
    -rwxr-xr-x 1 10 143   8181 Sep 22 23:23 tnameserv
    -rwxr-xr-x 1 10 143 228933 Sep 22 23:23 unpack200
    -rwxr-xr-x 1 10 143   7941 Sep 22 23:23 wsgen
    -rwxr-xr-x 1 10 143   7957 Sep 22 23:23 wsimport
    -rwxr-xr-x 1 10 143   7957 Sep 22 23:23 xjc

**Comment by kharels** [comment]
All of the perms looks good. Please see below

# ls -al /usr/java/default/bin/
total 452
drwxr-xr-x 2 10 143   4096 Sep 23 04:20 .
drwxr-xr-x 8 10 143   4096 Sep 23 04:20 ..
-rwxr-xr-x 1 10 143   7965 Sep 23 04:20 appletviewer
-rwxr-xr-x 1 10 143   7941 Sep 23 04:20 extcheck
-rwxr-xr-x 1 10 143   7973 Sep 23 04:20 idlj
-rwxr-xr-x 1 10 143   7925 Sep 23 04:20 jar
-rwxr-xr-x 1 10 143   7957 Sep 23 04:20 jarsigner
-rwxr-xr-x 1 10 143   7734 Sep 23 04:20 java
-rwxr-xr-x 1 10 143   1809 Sep 23 04:20 java-rmi.cgi
-rwxr-xr-x 1 10 143   7941 Sep 23 04:20 javac
-rwxr-xr-x 1 10 143   7941 Sep 23 04:20 javah
-rwxr-xr-x 1 10 143   7925 Sep 23 04:20 jcmd
-rwxr-xr-x 1 10 143   7941 Sep 23 04:20 jdeps
-rwxr-xr-x 1 10 143   7941 Sep 23 04:20 jjs
-rwxr-xr-x 1 10 143   7925 Sep 23 04:20 jps
-rwxr-xr-x 1 10 143   7949 Sep 23 04:20 jrunscript
-rwxr-xr-x 1 10 143   7941 Sep 23 04:20 keytool
-rwxr-xr-x 1 10 143   7949 Sep 23 04:20 native2ascii
-rwxr-xr-x 1 10 143   8149 Sep 23 04:20 orbd
-rwxr-xr-x 1 10 143   7957 Sep 23 04:20 pack200
-rwxr-xr-x 1 10 143   7997 Sep 23 04:20 policytool
-rwxr-xr-x 1 10 143   7925 Sep 23 04:20 rmic
-rwxr-xr-x 1 10 143   7941 Sep 23 04:20 rmid
-rwxr-xr-x 1 10 143   7949 Sep 23 04:20 rmiregistry
-rwxr-xr-x 1 10 143   7957 Sep 23 04:20 schemagen
-rwxr-xr-x 1 10 143   7965 Sep 23 04:20 servertool
-rwxr-xr-x 1 10 143   8181 Sep 23 04:20 tnameserv
-rwxr-xr-x 1 10 143 228933 Sep 23 04:20 unpack200
-rwxr-xr-x 1 10 143   7941 Sep 23 04:20 wsgen
-rwxr-xr-x 1 10 143   7957 Sep 23 04:20 wsimport
-rwxr-xr-x 1 10 143   7957 Sep 23 04:20 xjc

**Comment by brunoborges** [comment]
I couldn't reproduce the bug. See my test in this recorded [asciinema](https://asciinema.org/a/65kyti2xiqfu38mvvbnb5m5r9).

**Comment by kharels** [comment]
Thanks for trying to reproduce. I cleaned up on my side and tried building again and I see different error now. May be this will help you steer in right direction.

`# ./buildDockerImage.sh -d -v 12.2.1
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip: OK
=====================
Building image 'oracle/weblogic:12.2.1-developer' ...
Sending build context to Docker daemon 389.1 MB
Sending build context to Docker daemon
Step 0 : FROM oracle/serverjre:8
 ---> 59e9c994b18a
Step 1 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in ff82fe088d04
 ---> 2d13f2ac475e
Removing intermediate container ff82fe088d04
Step 2 : ENV FMW_PKG fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip FMW_JAR fmw_12.2.1.0.0_wls_quick.jar ORACLE_HOME /u01/oracle USER_MEM_ARGS "-Djava.security.egd=file:/dev/./urandom" DEBUG_FLAG true PRODUCTION_MODE dev PATH $PATH:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin
 ---> Running in dc44d211a72f
 ---> de5bad4b9fdb
Removing intermediate container dc44d211a72f
Step 3 : COPY $FMW_PKG install.file oraInst.loc /u01/
 ---> e29d8c5e4d3f
Removing intermediate container 650f3c833f8b
Step 4 : RUN chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file
 ---> Running in 2e3428697dda
/
su: warning: cannot change directory to /u01/oracle: Permission denied
su: failed to execute /bin/bash: Permission denied
Removing intermediate container 2e3428697dda
The command '/bin/sh -c chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 126
There was an error building the image.
`

**Comment by kharels** [comment]
Another thing I noticed is that my build context is 398 mb vs your is north of 2.5 GB

**Comment by brunoborges** [comment]
Remove all of your images and containers, and double check the binaries you've downloaded.

```bash
#!/bin/bash
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```

**Comment by kharels** [comment]
# Removed everything

`# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE`
`# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES`

# Checked md5sum
`# cat Checksum.developer`
`# Download WebLogic Server Quick Installer 12.2.1`
`#`
`# - http://www.oracle.com/technetwork/middleware/weblogic/downloads/wls-for-dev-1703574.html`
`#`
`e9a0606d3f074c24ef72246efc5bdd85  fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip`
`# md5sum fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip`
`e9a0606d3f074c24ef72246efc5bdd85  fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip`

Here is my build, please check it out. [https://asciinema.org/a/6pwec564ez1qhvan4l8f9hnjq](asciinema)

**Comment by brunoborges** [comment]
This seems to be some issue in your host environment. 

What is your Docker version and what OS are you using?

**Comment by kharels** [comment]
Here you are. I am using centos distro

`# uname -a`
`Linux CIS-sandbox 2.6.32-642.6.2.el6.x86_64 #1 SMP Mon Oct 24 10:22:33 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux`
`# rpm -qa| grep docker`
`docker-engine-1.7.1-1.el6.x86_64`

**Comment by Djelibeybi** [comment]
CentOS 6 and that Docker version are very old and no longer supported by upstream or by us.

You should switch to CentOS 7 (which supports modern Docker versions) or use Oracle Linux 7 with UEK4.

**Comment by kharels** [comment]
Thank you guys for the support. I will do that.
