### ISSUE TITLE
Install additional linux packages in a Oracle Database container

### ISSUE THREAD

**Issue by doberkofler** [oracle/docker-images#2108]
I would need some additional linux packages in my Oracle Database container and was looking for a simple way to run any custom scripts during the creation of the docker image using `buildContainerImage.sh` similar to the custom scripts that can be specified when running the image?

**Comment by syaifulnizam** [comment]
I’m give update software

**Comment by syaifulnizam** [comment]
> I would need some additional linux packages in my Oracle Database container and was looking for a simple way to run any custom scripts during the creation of the docker image using `buildContainerImage.sh` similar to the custom scripts that can be specified when running the image?

**Comment by syaifulnizam** [comment]
[Access]() p

**Comment by abhisbyk** [comment]
@doberkofler You can use the following command to enter inside the container as root user:
```bash
docker exec -it -u root <container-name> bash
```
After this, you can install additional packages using `yum`.

For running custom scripts at database setup and/or startup, please refer the following link:
[https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance#running-scripts-after-setup-and-on-startup](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance#running-scripts-after-setup-and-on-startup). Currently, custom sql/shell scripts are supported.

Closing this issue for now. Please reopen if some additional info is required.
