### ISSUE TITLE
No support for Oracle 21c XE (Expression Edition)

### ISSUE THREAD

**Issue by rockyhopper** [oracle/docker-images#2110]
Hello, 

Oracle 21c XE is now available for download.

Despite the mention on that page that is suggesting we can build a Linux Docker image for 21c XE: 
    https://www.oracle.com/database/technologies/appdev/xe/quickstart.html

It fails with following message:

./buildContainerImage.sh -v 21.3.0 -x
WARNING: No swap limit support
Checking Docker version.
Version 21.3.0 does not have Express Edition available.

Did I miss something? 
(If not yet supported, any plan to support that version?)

Thanks

**Comment by sosoba** [comment]
> While in the meantime, one may use https://hub.docker.com/r/gvenzl/oracle-xe.

This is slippery. Who accepted the Oracle License? The author of the image for everyone?

**Comment by abhisbyk** [comment]
PR #2194 raised for 21c XE support.

**Comment by abhisbyk** [comment]
PR #2194 merged.
