### ISSUE TITLE
how to deploy application in weblogic using docker-compose.yaml file

### ISSUE THREAD

**Issue by wfqrwhregre** [oracle/docker-images#2113]

**Comment by rjeberhard** [comment]
We have not attempted to design a solution for WebLogic application deployment using Docker Compose. 

Instead, we do have tools to generate a container image with a fully configured domain (including application deployment) using two open-source tools: 1) the [WebLogic Deploy Tool](https://github.com/oracle/weblogic-deploy-tooling) and 2) the [WebLogic Image Tool](https://github.com/oracle/weblogic-image-tool).

Separately, we've done a lot of work on running WebLogic within a Kubernetes cluster, including application deployment.

**Comment by wfqrwhregre** [comment]
Yes..using the samples ..you have given in github...Iam able to deploy single application with domain but is there any solution to deploy muktiple applications same time

**Comment by rjeberhard** [comment]
We don't have any sample here that does that already, but the intention was that the samples could be edited to meet your needs.

**Comment by wfqrwhregre** [comment]
okay
