### ISSUE TITLE
Missed oracle-xe-11.2.0-1.0.x86_64.rpm.zip in the docker build script

### ISSUE THREAD

**Issue by sberdachuk-epam** [oracle/docker-images#2114]
I got an error when trying to build Oracle XE v 11.2.0.2 from:  https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/dockerfiles

$ ./buildContainerImage.sh -x -v 11.2.0.2
Checking Docker version.
Checking if required packages are present and valid...
md5sum: oracle-xe-11.2.0-1.0.x86_64.rpm.zip: No such file or directory
oracle-xe-11.2.0-1.0.x86_64.rpm.zip: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 11.2.0.2.

There is an instruction in the Docker file:
```
# (1) oracle-xe-11.2.0-1.0.x86_64.rpm.zip
#     Download Oracle Database 11g Release 2 Express Edition for Linux x64
#     from http://www.oracle.com/technetwork/database/database-technologies/express-edition/downloads/index.html
```
But this file is not available for download :(

At the same time I'm successed when tried to build Oracle XE v 18.4.0
$ ./buildContainerImage.sh -x -v 18.4.0

**Comment by gvenzl** [comment]
11g XE is no longer available for download.
Please use Oracle DB 18c XE instead.
