### ISSUE TITLE
Dockerfile for Oracle Forms 12c

### ISSUE THREAD

**Issue by alexsantos** [oracle/docker-images#212]
I've been using the docker images for Oracle Database on our development environment and now I need to test also Oracle Forms 12c.
Are there any plans on providing oficial dockerfiles for Forms also?
TYA

**Comment by brunoborges** [comment]
There are no plans to provide Dockerfiles for Forms, but thanks for showing interest.

**Comment by alexsantos** [comment]
I'll try to extend a WebLogic container for Oracle Forms and Reports then.
BTW, there are no Dockerfiles for 12.2.1.2 infrastruture. I'm doing it myself.

**Comment by hamps79** [comment]
@alexsantos did you have much success with creating a container for Oracle Form and Reports 12c?
Just started looking at this as an option and came across your discussion.

**Comment by pacoalcaide** [comment]
Here in Córdoba, we are walking in the same path. ;-)
It would be nice to share the job.

**Comment by brunoborges** [comment]
If you get this working, let us know and we can link to your project from the README.

**Comment by axl79com** [comment]
In Seville we are also triying to get working a Reports and Applications deployiment clusters. Thanks to these great posts with some changes to adapt out requirements:

https://dirknachbar.blogspot.com.es/2017/05/how-to-install-and-configure-oracle.html
http://robertcrames.blogspot.com.es/2017/05/how-to-install-and-configure-oracle.html

The problem right now is on the reports server that it´s not fully working, it can be started, but only shows help pages, when triying to showenv or showjobs, without set server name it gets stuck, and when  server name is passed as parameter, it says that server named XXXX cannot be bind.

Any idea of what are we missing on config?

PD: @pacoalcaide would be great if we can contact by Hangout to share achivements and problems faced, maybe we can have success together.

Thanks for this great work.

**Comment by pacoalcaide** [comment]
@axl79com thanks for the URLs and when you want we can try Hangout. I tried to find you with your login "axl79com", but I could'nt.

**Comment by axl79com** [comment]
@pacoalcaide I send you and invitation with Hangouts, please accept it  so we can talk.

Sorry for off topic.

**Comment by japareja** [comment]
Hi all, I´m @axl79com with another account. Finally I get a working Reports Server 12.2.1.0.0 container. The work isn´t finished, and some improvements can be done, so I made a project on Github so everybody can use it and share their achievements.

@pacoalcaide fell free to collaborate, I´ll review pull requests and commit them to master branch.

@brunoborges please link this project to main README, I hope the next person searching for this Reports & Forms images can easily find it.

https://github.com/japareja/DockerFMWReports12c

Thanks all people working and collaborating on Oracle Docker images, they are great, and change the way we can use Oracle products on development and production enviropment.

**Comment by DirkNachbar** [comment]
Hi all,
as Robert Crames and I had developed the already mentioned script solution for Oracle Forms & Reports 12c within this thread, I took some time to convert them to a Docker solution.

Here you can find Oracle Forms & Reports 12.2.1.2.0 and Oracle Forms & Reports 12.2.1.3.0 (with Option FADS) on Docker:
[https://github.com/DirkNachbar/Docker](https://github.com/DirkNachbar/Docker)

Cheers
Dirk

**Comment by Manishrana007** [comment]
Hi Mriccell, 

I am using "https://github.com/oracle/docker-images/tree/master/OracleFMWInfrastructure" container to build the "12.2.1.3" version of the fusion Middleware infrastructure. However when I trying to do "docker run" I am getting following error.

 Configuring Domain for first time
 If Domain has already been Configured
 Start the Admin and Managed Servers
 =====================================
 CONNECTION_STRING=fc54f8444045:1521/ORCLPDB1
 RCUPREFIX=INFRA
 DOMAIN_NAME=InfraDomain
 Loading RCU Phase
 =================
 CONNECTION_STRING=fc54f8444045:1521/ORCLPDB1
 RCUPREFIX=INFRA
 DB_PASSWORD=xxxxxxxxxx
 jdbc_url=jdbc:oracle:thin:@fc54f8444045:1521/ORCLPDB1
 ADMIN_PASSWORD=xxxxxxxxx
 DB_SCHEMA_PASSWORD=xxxxxxxxx
 DB_USERNAME=sys
 DOMAIN_HOME: /u01/oracle/user_projects/domains/InfraDomain
 MW_HOME: /u01/oracle
 WL_HOME: /u01/oracle/wlserver
 ADMIN_USER: weblogic
 DOMAIN_ROOT: /u01/oracle/user_projects/domains
 DOMAIN HOME: /u01/oracle/user_projects/domains/InfraDomain
 Loading SOA RCU into database
 Domain Configuration Phase
 ==========================

 Initializing WebLogic Scripting Tool (WLST) ...

 Welcome to WebLogic Server Administration Scripting Shell

 Type help() for help on available commands

 /u01/oracle/container-scripts/createInfraDomain.py called with the following sys.argv array:
 sys.argv[0] = /u01/oracle/container-scripts/createInfraDomain.py
 sys.argv[1] = -oh
 sys.argv[2] = /u01/oracle
 sys.argv[3] = -jh
 sys.argv[4] = /usr/java/default
 sys.argv[5] = -parent
 sys.argv[6] = /u01/oracle/user_projects/domains
 sys.argv[7] = -name
 sys.argv[8] = InfraDomain
 sys.argv[9] = -user
 sys.argv[10] = weblogic
 sys.argv[11] = -password
 sys.argv[12] = xxxxxxxxxx
 sys.argv[13] = -rcuDb
 sys.argv[14] = fc54f8444045:1521/ORCLPDB1
 sys.argv[15] = -rcuPrefix
 sys.argv[16] = INFRA
 sys.argv[17] = -rcuSchemaPwd
 sys.argv[18] = xxxxxxxxxx
 Error: set() failed. Do dumpStack() to see details.
 Error: runCmd() failed. Do dumpStack() to see details.
 Problem invoking WLST - Traceback (innermost last):
   File "/u01/oracle/container-scripts/createInfraDomain.py", line 271, in ?
   File "/u01/oracle/container-scripts/createInfraDomain.py", line 59, in createInfraDomain
   File "/u01/oracle/container-scripts/createInfraDomain.py", line 72, in createBaseDomain
   File "/tmp/WLSTOfflineIni8277535826787643075.py", line 79, in set
   File "/tmp/WLSTOfflineIni8277535826787643075.py", line 19, in command
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2983)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:735)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

 com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException

 RetVal from Domain creation 1
 Domain Creation Failed.. Please check the Domain Logs

Please could you help me here.

Thanks,
Manish

**Comment by Manishrana007** [comment]
Hi Mriccell/others,

Any update on my issues please?

Cheers,
Manish

**Comment by brunoborges** [comment]
This issue is closed. You should open a new issue specific to your problem.
