### ISSUE TITLE
Oracle Database XE 18.4.0 on M1

### ISSUE THREAD

**Issue by Peipi98** [oracle/docker-images#2184]
I run this command:
`docker run --name myxedb -d -p 1521:1521 -e ORACLE_PWD=system -e ORACLE_CHARACTERSET=AL32UTF8 oracle/database:18.4.0-xe`

Then I check on Docker that gives me this result:
```ORACLE PASSWORD FOR SYS AND SYSTEM: system

Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:

Confirm the password:

Configuring Oracle Listener.

Listener configuration succeeded.

Configuring Oracle Database XE.

#

# A fatal error has been detected by the Java Runtime Environment:

#

#  Internal Error (safepoint.cpp:310), pid=195, tid=0x000000403d91a700

#  guarantee(PageArmed == 0) failed: invariant

#

# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)

# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)

# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

#

# An error report file with more information is saved as:

# /tmp/hs_err_pid195.log

#

# If you would like to submit a bug report, please visit:

#   http://bugreport.java.com/bugreport/crash.jsp

#

qemu: uncaught target signal 6 (Aborted) - core dumped

/bin/bash: line 1:   193 Done                    ( echo 'system'; echo 'system'; echo 'system' )

       195 Aborted                 | /opt/oracle/product/18c/dbhomeXE/bin/dbca -silent -createDatabase -gdbName XE -templateName XE_Database.dbc -characterSet AL32UTF8 -createAsContainerDatabase true -numberOfPDBs 1 -pdbName XEPDB1 -sid XE -emConfiguration DBEXPRESS -emExpressPort 5500 -J-Doracle.assistants.dbca.validate.DBCredentials=false -sampleSchema true -customScripts /opt/oracle/product/18c/dbhomeXE/assistants/dbca/postdb_creation.sql -initParams sga_target=596M,pga_aggregate_target=198M


Database configuration failed. Check logs under '/opt/oracle/cfgtoollogs/dbca'.

/usr/bin/mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/spfileXE.ora': No such file or directory

/usr/bin/mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/orapwXE': No such file or directory

ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this

information is not available for the current user ID .

You can set ORACLE_BASE manually if it is required.

Resetting ORACLE_BASE to its previous value or ORACLE_HOME

The Oracle base remains unchanged with value /opt/oracle

#####################################

########### E R R O R ###############

DATABASE SETUP WAS NOT SUCCESSFUL!

Please check output for further info!

########### E R R O R ###############

#####################################

The following output is now a tail of the alert.log:

/usr/bin/tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory

/usr/bin/tail: no files remaining```

**Comment by horavamartin** [comment]
I've got the same problem on my MacBook Pro M1. I need this database for work so it would be amazing and it would really make my life easier.

**Comment by yunus-qureshi** [comment]
Please paste the output of docker info

**Comment by amari-at4** [comment]
The same problem occurs but with version 11.2.0.2 

Running the command:

`docker run --name oratest -d -p 1521:1521 -e ORACLE_PWD=system -e ORACLE_CHARACTERSET=AL32UTF8 --shm-size=1G oracle/database:11.2.0.2-xe` fails, here you can see error log for this execution [docker_oracle_error.log](https://github.com/oracle/docker-images/files/7692307/docker_oracle_error.log)

And my docker info is [docker_info.txt](https://github.com/oracle/docker-images/files/7692313/docker_info.txt)

The image was compiled using this command `./buildContainerImage.sh -v 11.2.0.2 -x -o “--platform=linux/amd64”` becasue if you use `./buildContainerImage.sh -v 11.2.0.2 -x` the image compilation fails [build_image_fails.log](https://github.com/oracle/docker-images/files/7692318/build_image_fails.log)

**Comment by jaiodoo** [comment]
i solve that executing in terminal 
ulimit -c unlimited

**Comment by doberkofler** [comment]
@jaiodoo Have you really been able to run an Oracle Database in a Docker container on Apple Silicon by just using the `“--platform=linux/amd64”` flag? That would be great! If so, could you elaborate on the exact environment and setup and how is the performance?

**Comment by pavestru** [comment]
I happened to resolve this (or very similar issue) **by accident** - the docker container got restarted after a failed DB setup until the setup was eventually successful.

To be precise:
- I installed docker inside [Lima](https://github.com/lima-vm/lima) with `arch: "x86_64"` ([the slow mode](https://github.com/lima-vm/lima/blob/master/docs/multi-arch.md#slow-mode) - better for compatibility)
- Enter Lima VM: (`lima`)
- Inside Lima run: `./buildContainerImage.sh  -v 18.4.0 -x`
  - no `--platform` flag necessary as I am on x86_64 already
  - this took a really long time (about 6 hours !!!) - now you know why it's called slow mode
- `docker run --name myxedb -d -p 1521:1521 -e ORACLE_PWD=system -e ORACLE_CHARACTERSET=AL32UTF8 oracle/database:18.4.0-xe` 
-  Oracle Database configuration failed and docker got restarted ... until, finally, it succeeded!

Oracle DB doesn't feel slow in my normal day-to-day use (no heavy use).

**Comment by abhisbyk** [comment]
@Peipi98 Oracle database docker images are not compatible on ARM platform (Apple M1) currently. Many guys are successful in running the docker images on Lima. Please use the method mentioned [above](https://github.com/oracle/docker-images/issues/2184#issuecomment-1046884609) to run the image.

Additionally, we are working on the compatibility of Oracle Database with ARM platform and the release expectation is later this year. So, closing this issue for now. Please feel free to reopen in case you have any further queries.

**Comment by Furqan-Iqbal** [comment]
@abhisbyk can you give me an idea how I can run Oracle Db 19c Docker image on Mac M1 using Lima.

**Comment by OliHarris** [comment]
Hey everyone, I am going to try running Oracle Database XE 18.4.0 on a new M1 PowerBook Pro, as mentioned in this thread using one of these [SO answers](https://stackoverflow.com/a/70719148)

There is also another thread discussing this topic here:
https://github.com/oracle/docker-images/discussions/1951

Fingers crossed at some point will see support for M1-based Macs in the future!!

**Comment by artemzi** [comment]
@OliHarris Do you have any updates about the issue? I have tried the solution with Colima described in [this](https://blog.jdriven.com/2022/07/running-oracle-xe-with-testcontainers-on-apple-silicon/) article on my M1 Max and got nothing in result.
