### ISSUE TITLE
runOracle.sh cat /sys/fs/cgroup/memory/memory.limit_in_bytes return a big value

### ISSUE THREAD

**Issue by marcelo-ochoa** [oracle/docker-images#219]
OracleDatabase/dockerfiles/12.1.0.2/runOracle.sh have a checking:
```
if [ `cat /sys/fs/cgroup/memory/memory.limit_in_bytes` -lt 2147483648 ]; then
   echo "Error: The container doesn't have enough memory allocated."
   echo "A database container needs at least 2 GB of memory."
   echo "You currently only have $((`cat /sys/fs/cgroup/memory/memory.limit_in_bytes`/1024/1024/1024)) GB allocated to the container."
   exit 1;
fi;
```
This checking always returns 18446744073709551615 which is maximum [addressable memory in 64 bits systems](https://github.com/docker/docker/issues/18087), so the if fails with  **[: 18446744073709551615: integer expression** expected and is not doing the expected checking.
Marcelo.

**Comment by gvenzl** [comment]
Fixed
