### ISSUE TITLE
Documentation links for Oracle Database 12c R2 Standard Edition 2 and Oracle Database 12c R2 Enterprise Edition lead to 404

### ISSUE THREAD

**Issue by yzhan289** [oracle/docker-images#2199]
I am currently reviewing the Single instance [FAQ](https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/FAQ.md#can-i-use-setup-or-startup-scripts-with-the-oracle-database-image-pulled-from-the-oracle-container-registry-or-docker-hub), and it looks like the links for Oracle Database 12c R2 Standard Edition 2 and Oracle Database 12c R2 Enterprise Edition both lead to 404. Can you fix this to link to the correct sites? I could only [Oracle Database 21c](https://container-registry.oracle.com/ords/f?p=113:4:707523985000:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:9,9,Oracle%20Database%20Enterprise%20Edition,Oracle%20Database%20Enterprise%20Edition,1,0&cs=3HQzPquFMIZSmR5LZ3wTUnsz2qjr2DRDc1TFTiAm8CDOYw6MerYmZrVto7gqVPG6TZKXud-vCgy5XEoJJd0jGdg) but I wasn't sure if these docs would be correct for 12c.

**Comment by yunus-qureshi** [comment]
@gvenzl  We might need to update this FAQ as starting 19c the container-registry images do support startup scripts

**Comment by yzhan289** [comment]
@yunus-qureshi Nice, are there any docs about how to add startup scripts for 19c?

**Comment by yunus-qureshi** [comment]
@yzhan289 it is already documented in the 21c link you have pasted above as part of the docker run command

**Comment by gvenzl** [comment]
@yunus-qureshi, yes, the FAQ needs an overhaul indeed.
Can you please have someone take a look at it?
