### ISSUE TITLE
Changing Node Manager password does not work.

### ISSUE THREAD

**Issue by MattAtTTU** [oracle/docker-images#220]
When changing the Node Manager password during build, per the documentation, the build completes without issue.  However, when running a container from the image, either by executing the default startNMandOHS.sh script or by calling configureWLSProxyPlugin.sh, the startup will fail with the following error. 

```
weblogic.nodemanager.NMException: Received error message from Node Manager Server: [Access to domain 'ohsDomain' for user 'weblogic' denied]. Please check Node Manager log for details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/container-scripts/start-ohs.py", line 26, in ?
  File "<iostream>", line 111, in nmConnect
  File "<iostream>", line 240, in raiseWLSTException
WLSTException: Error occurred while performing nmConnect : Cannot connect to Node Manager. : Received error message from Node Manager Server: [Access to domain 'ohsDomain' for user 'weblogic' denied]. Please check Node Manager log for details. 
```

The issue is due to the start-ohs.py script containing the nm_pass variable, which is set to the value of the NM_PASSWORD variable in the operating system.  The NM_PASSWORD variable doesn't exist since it is only a build argument. 

This issue can be resolved by adding the following line to the Dockerfile in the ENV section so the NM_PASSWORD variable will remain set after build. 

`NM_PASSWORD=$NM_PASSWORD \`

Full ENV section for our environment:

```
ENV NM_PORT=5556 \
    NM_PASSWORD=$NM_PASSWORD \
    OHS_LISTEN_PORT=8080 \
    OHS_SSL_PORT=8443 \
    JAVA_HOME=/usr/java/default \
    MW_HOME=/u01/oracle/ohssa \
    ORACLE_HOME=/u01/oracle/ohssa \
    DOMAIN_NAME=ohsDomain \
    OHS_COMPONENT_NAME=ohs_sa1 \
    PATH=$PATH:$ORACLE_HOME/oracle_common/common/bin:$ORACLE_HOME/user_projects/domains/ohsDomain/bin:/u01/oracle/container-scripts
```
Is there any security issue with persisting the Node Manager password in the OS as an environmental variable?  If there is, I think another viable workaround would be to insert the Node Manager password as a hard coded variable in start-ohs.py.

**Comment by MattAtTTU** [comment]
I should have noted this is in reference to the Oracle HTTP Server source.

**Comment by mriccell** [comment]
@MattAtTTU  Yes we can not persist the NodeManager password  in the OS environment or hard code it in the WLST script.  If you look at the 12.2.1.1 or 12.2.1.2 WebLogic scripts we dynamically generate the WLS Admin password when we run the container and use this password to set it in the nodemanager properties file, look at create-wls-domain.py.

**Comment by MattAtTTU** [comment]
Ok.  Should the build argument for node manager password be removed from the Oracle HTTP Server Docker image documentation?

**Comment by Djelibeybi** [comment]
@mriccell can you address @MattAtTTU's question about the documentation? Perhaps a PR to adjust if necessary?

**Comment by mriccell** [comment]
@MattAtTTU take a look at how we do it in WebLogic with the admin password, in the scripts when we build the image createAndStartEmptyDomain.sh we will generate the admin password and pass it into the WLST script to set it.
# Create Domain only if 1st execution
if [ $ADD_DOMAIN -eq 0 ]; then
# Auto generate Oracle WebLogic Server admin password
ADMIN_PASSWORD=$(cat date| md5sum | fold -w 8 | head -n 1) 

echo ""
echo "    Oracle WebLogic Server Auto Generated Empty Domain:"
echo ""
echo "      ----> 'weblogic' admin password: $ADMIN_PASSWORD"
echo ""

sed -i -e "s|ADMIN_PASSWORD|$ADMIN_PASSWORD|g" /u01/oracle/create-wls-domain.py

You could do something similar with OHS to generate the Node Manager password and pass it into the WLST script.
I see what you are saying about the documentation, I will create a pull request to change that. Thanks
