### ISSUE TITLE
Image size oracledb-express v21

### ISSUE THREAD

**Issue by VegarRingdalAibel** [oracle/docker-images#2225]
When I make make XE v 21 image, its 6.53 gig
Is it possible to make smaller, have I done something wrong?

Ref
https://github.com/oracle/docker-images/pull/145
https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance

**Comment by abhisbyk** [comment]
@VegarRingdalAibel I reduced two extra layers in 21.3 XE image in the PR #2419 
Stil the image size is almost same. It is mostly because of the database software binary size and can not be reduced further.
