### ISSUE TITLE
Oracle 12c EE - ORA-04035: unable to allocate 4096 bytes of shared memory in shared object cache "JOXSHM" of size "1073741824"

### ISSUE THREAD

**Issue by marcelo-ochoa** [oracle/docker-images#223]
Using Oracle 12c EE version throws **ORA-04035: unable to allocate 4096 bytes of shared memory in shared object cache "JOXSHM" of size "1073741824"** due noexec flag in mount option for /dev/shm. This is caused when using the Oracle internal JVM.
According to Oracle dev team the issue is fixed re-mounting /dev/shm with exec flag so at docker run time running as root is fixed by calling:
```
# fix ORA-04035: unable to allocate 4096 bytes of shared memory in shared object cache "JOXSHM" of size "1073741824"
mount -o remount,exec /dev/shm
```
At Dockerfile.ee script the effective user is **oracle**, so I propose fix that using another script running as root user which call finally runOracle.sh script, for example:
[Dockerfile](https://github.com/marcelo-ochoa/docker/blob/master/ols-official/Dockerfile)
```
USER	root

VOLUME ["/opt/oracle/oradata"]
EXPOSE	1521 5500

CMD	[ "sh" , "-c" ,  "/home/oracle/manage-oracle.sh" ]
```
where [manage-oracle.sh](https://github.com/marcelo-ochoa/docker/blob/master/ols-official/manage-oracle.sh) call sysctl command and then runOracle.sh as user oracle.

```
mount -o remount,exec /dev/shm

echo "export ORACLE_SID=$ORACLE_SID" >>/home/oracle/.bashrc
echo "export ORACLE_PDB=$ORACLE_PDB" >>/home/oracle/.bashrc
su - oracle -c "$ORACLE_BASE/runOracle.sh"
```
Also docker run command must include **--shm-size=8g --privileged=true** flags, for example:
```
#!/bin/bash
docker run -ti --rm --shm-size=8g --privileged=true --name test --hostname test \
-p 1521:1521 -p 5500:5500 -p 9099:9099 \
-e ORACLE_SID=TEST \
-e ORACLE_PDB=PDB1 \
-v /home/data/db/12cR1:/u01/app/oracle/oradata \
oracle/database:12.1.0.2-ee
```

**Comment by gvenzl** [comment]
Can you please share more details on your test case and what you are trying to do. A simple test case with a one liner Java stored procedure works well without raising this error.

**Comment by marcelo-ochoa** [comment]
Here my test case:
as root:
```
mkdir /home/data/db/t1
chown 1000:500 /home/data/db/t1
```
as a regular user:
```
[mochoa@localhost OracleDatabase]$ docker run --rm --name test1 -p 1521:1521 -p 5500:5500 -e ORACLE_SID=TEST -e ORACLE_PDB=PDB1 -v /home/data/db/t1:/opt/oracle/oradata oracle/database:12.1.0.2-ee
ORACLE AUTO GENERATED PASSWORD FOR SYS, SYSTEM AND PDBAMIN: 8AqjjSF5qSk=

LSNRCTL for Linux: Version 12.1.0.2.0 - Production on 12-DEC-2016 21:35:24

Copyright (c) 1991, 2014, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.1.0.2/dbhome_1/bin/tnslsnr: please wait...
   continuing output
SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options
#########################
DATABASE IS READY TO USE!
#########################

```
in another session attach with bash to execute sqlplus on PDB1:
```
[mochoa@localhost OracleDatabase]$ docker exec -ti test1 bash
[oracle@f1e7bb6faa16 ~]$ sqlplus "sys/8AqjjSF5qSk=@pdb1 as sysdba"

SQL*Plus: Release 12.1.0.2.0 Production on Mon Dec 12 22:00:46 2016

Copyright (c) 1982, 2014, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

SQL> declare
  res NUMBER;
begin
  for c in (SELECT dbms_java.longname(object_name) cName
            FROM user_objects
            WHERE object_type = 'JAVA CLASS' AND status = 'VALID'
            AND dbms_java.longname(object_name) like 'oracle/ODCI/%') loop
    res := dbms_java.compile_class(c.cName);
  end loop;
end;
/
  2    3    4    5    6    7    8    9   10   11  
PL/SQL procedure successfully completed.

SQL> declare
  res NUMBER;
begin
  for c in (SELECT dbms_java.longname(object_name) cName
            FROM user_objects
            WHERE object_type = 'JAVA CLASS' AND status = 'VALID'
            AND dbms_java.longname(object_name) like 'oracle/xdb/%') loop
    res := dbms_java.compile_class(c.cName);
  end loop;
end;
/
  2    3    4    5    6    7    8    9   10   11  

PL/SQL procedure successfully completed.
```
attaching in another bash you can see at .trc files something like this:
```
[oracle@f1e7bb6faa16 trace]$ pwd
/opt/oracle/diag/rdbms/test/TEST/trace
[oracle@f1e7bb6faa16 trace]$ tail -f TEST_m000_1424.trc
peshmmap_Create_Memory_Map:
Map_Length = 4096
Map_Protection = 7
Flags = 1
File_Offset = 0
mmap failed with error 1
error message:Operation not permitted
ORA-04035: unable to allocate 4096 bytes of shared memory in shared object cache "JOXSHM" of size "1073741824"
joez: Failed loading machine code: Unable to allocate code space
joez_compile_method: done compiling method oracle/xdb/servlet/ArrayEnumeration.nextElement(0x67793085).

```
Best regards, Marcelo.

**Comment by gvenzl** [comment]
Thanks, seems like others had similar issues with /dev/shm: https://github.com/docker/docker/issues/6758

However, this issue got closed with not much explanation why nor a feasible workaround.

**Comment by gvenzl** [comment]
There was a fix proposed on the original docker issue which does the trick: `docker run -it -v /dev/shm --tmpfs /dev/shm:rw,nosuid,nodev,exec,size=4g`

I tried via `docker run --name test -v /dev/shm --tmpfs /dev/shm:rw,nosuid,nodev,exec,size=1g -p 1521:1521 -v /home/oracle/oradata:/opt/oracle/oradata oracle/database:12.2.0.1-ee` and the errors highlighted above do no longer occur, hence closing this issue.

**Comment by marcelo-ochoa** [comment]
Revisiting this problem against 18c XE image I found a workaround using Docker Swarm (18.03.1-ce) finding first where shm is mounted at the server, for example on Ubuntu:
```
# mount |grep shm
none on /run/shm type tmpfs (rw,nosuid,nodev)
```
and mounting using legacy mount at docker-compose.yml (stack definition), for example:
```
version: '3.6'
services:
  ols:
    image: oracle/database:18.4.0-xe
    hostname: ols
    volumes:
      - db_data:/opt/oracle/oradata # persistent oracle database data.
      - /run/shm:/dev/shm
```
by doing that, 18cXE Docker image reports:
```
bash-4.2# mount|grep shm
none on /dev/shm type tmpfs (rw,nosuid,nodev,relatime,size=8036328k,nr_inodes=2009082)
```
fixing  ORA-04035: unable to allocate 4096 bytes of shared memory in shared object cache "JOXSHM".
HTH, Marcelo.
