### ISSUE TITLE
Oracle 19.3.0 prompt command not found when buildContainerImage.

### ISSUE THREAD

**Issue by essapp** [oracle/docker-images#2234]
./buildContainerImage.sh -e -v 19.3.0 -t essapp/ora:19.3.0 -i -o '--build-arg SLIMMING=ture'
Error:
Launching Oracle Database Setup Wizard...

[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
[WARNING] [INS-13014] Target environment does not meet some optional requirements.
   CAUSE: Some of the optional prerequisites are not met. See logs for details. installActions2022-01-21_04-33-11AM.log
   ACTION: Identify the list of failed prerequisite checks from the log: installActions2022-01-21_04-33-11AM.log. Then either from the log file or from installation manual find the appropriate configuration to meet the prerequisites and fix it manually.
The response file for this session can be found at:
 /opt/oracle/product/19c/dbhome_1/install/response/db_2022-01-21_04-33-11AM.rsp

You can find the log of this install session at:
 /tmp/InstallActions2022-01-21_04-33-11AM/installActions2022-01-21_04-33-11AM.log

As a root user, execute the following script(s):
        1. /opt/oracle/oraInventory/orainstRoot.sh
        2. /opt/oracle/product/19c/dbhome_1/root.sh

Execute /opt/oracle/oraInventory/orainstRoot.sh on the following nodes: 
[6e7db19a3b70]
Execute /opt/oracle/product/19c/dbhome_1/root.sh on the following nodes: 
[6e7db19a3b70]

Successfully Setup Software with warning(s).
Moved the install session logs to:
 /opt/oracle/oraInventory/logs/InstallActions2022-01-21_04-33-11AM
/opt/install/installDBBinaries.sh: line 59: ture: command not found
Removing intermediate container 6e7db19a3b70

**Comment by abhisbyk** [comment]
@essapp There is a typo in your command. You have written '**ture**' instead of '**true**'. Additionally, `SLIMMING` is by default **true**. One should specify build-arg, if the intention is to make `SLIMMING` **false**, otherwise this can be skipped. 
The build process halted because of this typo. OraInventory thing is a warning and can be ignored. Can you pls try again, and send me full build logs in case of any error ?
