### ISSUE TITLE
Docker DB 19c coming up unhealthy

### ISSUE THREAD

**Issue by bhushanarora2006** [oracle/docker-images#2245]
I tried 12c image, it's working fine. But issue is with 19c and 21c. DB connection is successful DB and listener is running fine.

bash-3.2$ docker ps -a
CONTAINER ID   IMAGE                                                        COMMAND                  CREATED          STATUS                      PORTS                         
3a8b5a33841b   container-registry.oracle.com/database/enterprise:19.3.0.0   "/bin/sh -c 'exec $O…"   3 hours ago      Up 3 hours (unhealthy)                                    19cdb2

The Oracle base remains unchanged with value /opt/oracle
#########################
DATABASE IS READY TO USE!
#########################

Executing user defined scripts
/opt/oracle/runUserScripts.sh: running /opt/oracle/scripts/extensions/startup/runDatapatch.sh
Datafiles are already patched. Skipping datapatch run.

DONE: Executing user defined scripts

The following output is now a tail of the alert.log:
ORCLPDB1(3):Completed: ALTER DATABASE DEFAULT TABLESPACE "USERS"
2022-02-03T15:06:00.920970+00:00
ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORCLCDB/control01.ctl' SCOPE=SPFILE;
2022-02-03T15:06:00.931086+00:00
ALTER SYSTEM SET local_listener='' SCOPE=BOTH;
   ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
Completed:    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
2022-02-03T15:06:02.854768+00:00

XDB initialized.
2022-02-03T15:06:36.839607+00:00
TABLE SYS.WRP$_REPORTS: ADDED INTERVAL PARTITION SYS_P201 (4417) VALUES LESS THAN (TO_DATE(' 2022-02-04 01:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
TABLE SYS.WRP$_REPORTS_DETAILS: ADDED INTERVAL PARTITION SYS_P202 (4417) VALUES LESS THAN (TO_DATE(' 2022-02-04 01:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
TABLE SYS.WRP$_REPORTS_TIME_BANDS: ADDED INTERVAL PARTITION SYS_P205 (4416) VALUES LESS THAN (TO_DATE(' 2022-02-03 01:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
2022-02-03T16:05:35.500177+00:00
Resize operation completed for file# 3, old size 532480K, new size 542720K
2022-02-03T16:11:13.987947+00:00
Warning: VKTM detected a time stall. 
Time drifts can result in unexpected behavior such as time-outs. 
Please see the VKTM trace file for more details:
/opt/oracle/diag/rdbms/orclcdb/ORCLCDB/trace/ORCLCDB_vktm_2743.trc
2022-02-03T16:55:54.424396+00:00
Heavy swapping observed on system
2022-02-03T16:55:54.433104+00:00
WARNING: Heavy swapping observed on system in last 5 mins.
Heavy swapping can lead to timeouts, poor performance, and instance eviction.
2022-02-03T17:15:11.006163+00:00
Warning: VKTM detected a time stall. 
Time drifts can result in unexpected behavior such as time-outs. 
Please see the VKTM trace file for more details:
/opt/oracle/diag/rdbms/orclcdb/ORCLCDB/trace/ORCLCDB_vktm_2743.trc
bash-3.2$

**Comment by muhammad-asn** [comment]
Is there any update on this issue?

**Comment by yunus-qureshi** [comment]
Exec into the container and paste the output of sh -x checkDBStatus.sh and sh -x checkDBLockStatus.sh

**Comment by dkellenb** [comment]
I have the same issue with 19.3.0.0 and 21.3.0.0

I've started the container with:
```
docker run --name ora-demo-21 -p 41521:1521 -p 45500:5500 -e ORACLE_PW=Oracle21 container-registry.oracle.com/database/enterprise:21.3.0.0
```

After few minutes, the message `DATABASE IS READY TO USE!` is visible, but according to `docker ps` the container is still _starting_.

Logs:
```
$ docker run --name ora-demo-21 -p 41521:1521 -p 45500:5500 -e ORACLE_PW=Oracle21 container-registry.oracle.com/database/enterprise:21.3.0.0
[2022:05:03 10:10:03]: Acquiring lock ..create_lck with heartbeat 30 secs
[2022:05:03 10:10:03]: Lock acquired
[2022:05:03 10:10:03]: Starting heartbeat
[2022:05:03 10:10:03]: Lock held ..create_lck
ORACLE EDITION: ENTERPRISE

LSNRCTL for Linux: Version 21.0.0.0.0 - Production on 03-MAY-2022 10:10:04

Copyright (c) 1991, 2021, Oracle.  All rights reserved.

Starting /opt/oracle/product/21c/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 21.0.0.0.0 - Production
System parameter file is /opt/oracle/homes/OraDB21Home1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/532d53bedaa5/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 21.0.0.0.0 - Production
Start Date                03-MAY-2022 10:10:04
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/homes/OraDB21Home1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/532d53bedaa5/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
Prepare for db operation
8% complete
Copying database files
31% complete
Creating and starting Oracle instance
32% complete
36% complete
40% complete
43% complete
46% complete
Completing Database Creation
51% complete
54% complete
Creating Pluggable Databases
58% complete
77% complete
Executing Post Configuration Actions
100% complete
Database creation complete. For details check the logfiles at:
 /opt/oracle/cfgtoollogs/dbca/ORCLCDB.
Database Information:
Global Database Name:ORCLCDB
System Identifier(SID):ORCLCDB
Look at the log file "/opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log" for further details.

SQL*Plus: Release 21.0.0.0.0 - Production on Tue May 3 10:15:26 2022
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.


Connected to:
Oracle Database 21c Enterprise Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0

SQL> 
System altered.

SQL> 
System altered.

SQL> 
Pluggable database altered.

SQL> 
PL/SQL procedure successfully completed.

SQL> SQL> 
Session altered.

SQL> 
User created.

SQL> 
Grant succeeded.

SQL> 
Grant succeeded.

SQL> 
Grant succeeded.

SQL> 
User altered.

SQL> SQL> Disconnected from Oracle Database 21c Enterprise Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0
The Oracle base remains unchanged with value /opt/oracle

Executing user defined scripts
/opt/oracle/runUserScripts.sh: running /opt/oracle/scripts/extensions/setup/savePatchSummary.sh

/opt/oracle/runUserScripts.sh: running /opt/oracle/scripts/extensions/setup/swapLocks.sh
[2022:05:03 10:15:27]: Acquiring lock .ORCLCDB.exist_lck with heartbeat 30 secs
[2022:05:03 10:15:27]: Lock acquired
[2022:05:03 10:15:27]: Starting heartbeat
[2022:05:03 10:15:27]: Lock held .ORCLCDB.exist_lck

DONE: Executing user defined scripts

The Oracle base remains unchanged with value /opt/oracle
#########################
DATABASE IS READY TO USE!
#########################

Executing user defined scripts
/opt/oracle/runUserScripts.sh: running /opt/oracle/scripts/extensions/startup/runDatapatch.sh
Datafiles are already patched. Skipping datapatch run.

DONE: Executing user defined scripts

The following output is now a tail of the alert.log:
ORCLPDB1(3):CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
ORCLPDB1(3):Completed: CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
ORCLPDB1(3):ALTER DATABASE DEFAULT TABLESPACE "USERS"
ORCLPDB1(3):Completed: ALTER DATABASE DEFAULT TABLESPACE "USERS"
2022-05-03T10:15:26.885973+00:00
ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORCLCDB/control01.ctl' SCOPE=SPFILE;
2022-05-03T10:15:26.892592+00:00
ALTER SYSTEM SET local_listener='' SCOPE=BOTH;
ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
Completed: ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
```

docker ps:
```
$ docker ps 
CONTAINER ID   IMAGE                                                        COMMAND                  CREATED          STATUS                             PORTS                                                                                      NAMES
532d53bedaa5   container-registry.oracle.com/database/enterprise:21.3.0.0   "/bin/sh -c 'exec $O…"   9 minutes ago    Up 9 minutes (health: starting)    0.0.0.0:41521->1521/tcp, :::41521->1521/tcp, 0.0.0.0:45500->5500/tcp, :::45500->5500/tcp   ora-demo-21
```

Output of `checkDBStatus.sh` and `checkDBLockStatus.sh`:
```
$ docker exec -it ora-demo-21 sh
sh-4.2$ /opt/oracle/checkDBStatus.sh
The Oracle base remains unchanged with value /opt/oracle
sh-4.2$ /opt/oracle/checkDBLockStatus.sh
[2022:05:03 10:20:52]: Connecting to the lock process /tmp/..create_lck
[2022:05:03 10:20:52]: Lock held ..create_lck
```

**Comment by yunus-qureshi** [comment]
The container-registry image has a minor issue that is causing this. Also it is not the latest build from GitHub.  It will be refreshed soon. Until then to work around this always pass ORACLE_SID in your docker run command

-e ORACLE_SID=ORCLCDB

**Comment by dkellenb** [comment]
Hi @yunus-qureshi : Thank you. It's now working as expected!

**Comment by yunus-qureshi** [comment]
The container-registry image has been updated to fix this issue

**Comment by srini1010** [comment]
I am having the same issue for Oracle GG for MySQL DB - Linux version (213000_ggs_Linux_x64_MySQL_services_shiphome.zip) . Is there a fix or a work around for this?

`[root@ucchub-2-swarm-dev-east-b-2 log]# docker container ls | grep oracle
097f73d91909   oracle/gg21cmicrov4                                                                                                                                           "/usr/local/bin/depl…"   31 seconds ago   Up 29 seconds (health: starting)   80/tcp, 0.0.0.0:9993->443/tcp, :::9993->443/tcp   sleepy_tereshkova
[root@ucchub-2-swarm-dev-east-b-2 log]# docker container ls | grep oracle
097f73d91909   oracle/gg21cmicrov4                                                                                                                                           "/usr/local/bin/depl…"   2 minutes ago   Up 2 minutes (unhealthy)   80/tcp, 0.0.0.0:9993->443/tcp, :::9993->443/tcp   sleepy_tereshkova
[`
