### ISSUE TITLE
Sometime openssl rand -base64 8 generated password does not conform to the Oracle recommended standards

### ISSUE THREAD

**Issue by marcelo-ochoa** [oracle/docker-images#226]
runOracle.sh script uses **_openssl rand -base64 8_** command to generate a random password, but some time it doesn't included a number inside, for example **_LhCsOGTOaTM=_** warning generated is:

> [WARNING] [DBT-06208] The 'SYS' password entered does not conform to the Oracle recommended standards.
>    CAUSE: 
> a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
> b.The password entered is a keyword that Oracle does not recommend to be used as password
>    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.

is not a big problem but can confuse non experimented users :)

**Comment by brunoborges** [comment]
@gvenzl perhaps appending a 0 at the end just to make sure it has a number would be sufficient...

**Comment by gvenzl** [comment]
Yes, that is probably a good approach. Note, the auto generated password can always be reset with `docker exec <container name> ./setPassword.sh <your password>`.

**Comment by gvenzl** [comment]
This issue is now fixed, a "1" will be appended to the password automatically.
