### ISSUE TITLE
GoldenGate 21.3 Microservices for PostgreSQL

### ISSUE THREAD

**Issue by wanghy8166** [oracle/docker-images#2270]
I use the method in "https://github.com/oracle/docker-images/tree/main/OracleGoldenGate/12c-19c#extracting-oracle-goldengate-installation-media-for-non-oracle-databases",
Compile the Docker image for "Oracle GoldenGate 21.3.0.0.0 Microservices for PostgreSQL",
Compilation is fine, logging is fine when the container is started,
But the status of the management service is: abnormal abort,
Has this happened to anyone? How can I fix it?

**Comment by sbalousek** [comment]
Creation of containerized images for Oracle GoldenGate 21c is done from the `OracleGoldenGate/21c` directory. For PostgreSQL, an example command to build an image is:

```sh
docker build --tag=oracle/goldengate-postgresql:21.3.0.0.0 --build-arg INSTALLER=213000_ggs_Linux_x64_PostgreSQL_services_shiphome.zip .
```

Containerized images for Oracle Goldengate 21c for PostgreSQL have not been fully tested.

**Comment by sbalousek** [comment]
Oracle Goldengate 21c for PostgreSQL is now a tested and supported version.
