### ISSUE TITLE
chpasswd: line 1: user 'oracle' does not exist

### ISSUE THREAD

**Issue by dylannnn** [oracle/docker-images#2273]
Run  `buildContainerImage.sh -v 21.3.0 -x -i` failed with error: 

```bash
#8 18.74 Running transaction check
#8 18.75 Running transaction test
#8 18.76 Transaction test succeeded
#8 18.76 Running transaction
#8 18.81   Installing : 1:make-3.82-24.el7.aarch64                                   1/2 
#8 19.07   Installing : 1:openssl-1.0.2k-24.0.3.el7_9.aarch64                        2/2 
#8 19.08   Verifying  : 1:make-3.82-24.el7.aarch64                                   1/2 
#8 19.09   Verifying  : 1:openssl-1.0.2k-24.0.3.el7_9.aarch64                        2/2 
#8 19.10 
#8 19.10 Installed:
#8 19.10   openssl.aarch64 1:1.0.2k-24.0.3.el7_9                                         
#8 19.10 
#8 19.10 Dependency Installed:
#8 19.10   make.aarch64 1:3.82-24.el7                                                    
#8 19.10 
#8 19.10 Complete!
#8 19.24 chpasswd: line 1: user 'oracle' does not exist
#8 19.24 chpasswd: error detected, changes ignored
```

Environment: Mac M1 Pro 12.3
Docker info: 

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.0)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.765GiB
 Name: docker-desktop
 ID: 4M7T:WNR6:5LJA:UKI3:ODFU:WZJC:7HGT:X2IV:P3NU:XOAY:O6MY:GGWC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by fAlcide** [comment]
Hey, it has been quite a long time, but have-you been able to solve this error ?
