### ISSUE TITLE
Please support Docker DB 21.3 - Apple Silicon

### ISSUE THREAD

**Issue by simonso** [oracle/docker-images#2275]
Understood that this is [a known issue](https://github.com/oracle/docker-images/commit/73258d2b56ff4d4075b224e2ad4b95b3e7da8fad).

Any update on what this would be supported?  The dev community is really adopting Apple Silicon as the dev platform of choice.  Thanks!

**Comment by Djelibeybi** [comment]
There are ongoing discussions of workarounds in https://github.com/oracle/docker-images/discussions/1951 and as you state, this is a known issue. Closing this issue in favour of the existing discussion.
