### ISSUE TITLE
Oracle Database installation failed in Kubernetes Environment (Permission Denied issue)

### ISSUE THREAD

**Issue by viju2008** [oracle/docker-images#2280]
Unable to create Oracle Database in Kubernetes

Oracle Database Express Edition 18

kubectl --kubeconfig=kube.config logs oracle-rdbms-599b96bcf9-5nh9c -n test
/bin/sh: /opt/oracle/runOracle.sh: Permission denied
/bin/sh: line 0: exec: /opt/oracle/runOracle.sh: cannot execute: Permission denied

kubectl --kubeconfig=kube.config version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.8", GitCommit:"35dc4cdc26cfcb6614059c4c6e836e5f0dc61dee", GitTreeState:"clean", BuildDate:"2020-06-26T03:43:27Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9+vmware.1", GitCommit:"f856d899461199c512c21d0fdc67d49cc70a8963", GitTreeState:"clean", BuildDate:"2021-03-19T23:57:11Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

Deployment File: 

---------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-rdbms-oradata
  namespace: test
  labels:
    app: oracle-rdbms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-rdbms-config
  namespace: test
  labels:
    app: oracle-rdbms
data:
  ORACLE_CHARACTERSET: "AL32UTF8"
  ORACLE_EDITION: "enterprise"
  ORACLE_SID: "ORCLCDB"
  ORACLE_PDB: "ORCLPDB1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-rdbms
  labels:
    app: oracle-rdbms
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-rdbms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle-rdbms
    spec:
      securityContext:
        runAsUser: 54321
        fsGroup: 54321
      containers:
        - name: rdbms
          image: harbor.dev/oracle/express
          envFrom:
            - configMapRef:
                name: oracle-rdbms-config
          securityContext:
            runAsUser: 54321
          ports:
            - containerPort: 1521
              name: oracle-listener
            - containerPort: 5500
              name: oem-express
          volumeMounts:
          - name: oradata
            mountPath: /opt/oracle/oradata
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            exec:
              command:
                - /bin/sh
                - "-c"
                - $ORACLE_BASE/$CHECK_DB_FILE
          livenessProbe:
            initialDelaySeconds: 300
            periodSeconds: 60
            exec:
              command:
                - /bin/sh
                - "-c"
                - $ORACLE_BASE/$CHECK_DB_FILE
      volumes:
        - name: oradata
          persistentVolumeClaim:
            claimName: oracle-rdbms-oradata
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: test
  labels:
    app: oracle-rdbms
spec:
  ports:
    - name: listener
      port: 1521
      targetPort: oracle-listener
  selector:
    app: oracle-rdbms

**Comment by viju2008** [comment]
I also tried 

    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 54321


However after 34% pct of the Database Creation it failed.

**Comment by viju2008** [comment]
> @viju2008 you need to clean up the failed setup. Exec into the pod and do a rm -rf /opt/oracle/oradata/* Then delete the pod using command kubectl delete pod. This will spin up a new replacement pod that should create the DB successfully
> 
> You may also want to try this https://github.com/oracle/oracle-database-operator

Hello ,

I have deleted the whole persistent volume , the deployment and then tried again.

That also dosent  help.

I cannot exec into the pod after the error comes as it goes into failed state, hence its not possible to execute rm command. We can exec into pods only in runnimg state by design of kubernetes.


Vijay

**Comment by yunus-qureshi** [comment]
@viju2008 deleting the PV may not help as the content would still reside in the volume. 

Do a kubectl edit on deployment yaml and add a command section as shown below

containers:
- name: rdbms
   command:
        - bash
      
The restarted pod should just come with the bash shell. Exec into the pod, clean up the datafiles
Now revert the change you made. Hopefully this should resolve the issue.

**Comment by viju2008** [comment]
> @viju2008 deleting the PV may not help as the content would still reside in the volume.
> 
> Do a kubectl edit on deployment yaml and add a command section as shown below
> 
> containers:
> 
> * name: rdbms
>   command:
>   - bash
> 
> The restarted pod should just come with the bash shell. Exec into the pod, clean up the datafiles Now revert the change you made. Hopefully this should resolve the issue.

Whenever a new PV is created a new volume is created in the storage VSAN.  Hence the issue will not occur

**Comment by viju2008** [comment]
The issue still persists we are unable to create the Oracle Database . We have tried few combinations of SecurityContext 

runAsUser
runAsGroup
fsGroup

Please provide a solution. Can you check if the image has some issue we have downloaded the same from Oracle official container registry

**Comment by yunus-qureshi** [comment]
Are you still seeing this FATAL error?

Configuring Oracle Database XE.
[FATAL] [DBT-06607] The data file (/opt/oracle/oradata/XE/system01.dbf) already exists on the file system.

If yes, then the PV is not clean

**Comment by viju2008** [comment]
Whenever I apply the yaml a new VMFS folder i created and the contents are created on that. 

When i delete the deployment using YAML the contents of the PV are moved to another VMFS folder.

Whenever the yaml is reapplied again  a new PV with a new GUID is created and a new VMFS folder with the same GUID (i.e. new GUID) is created hence the chance of old data being there is the PV volume is ruled out

**Comment by viju2008** [comment]
> /opt/oracle/oradata/XE is created but never deleted by runOracle.sh
> 
> If you are seeing this FATAL error, then PV is not clean for sure. The restriction with XE image is that you cannot change the SID, hence the PV has to be clean to recreate the DB with same SID.
> 
> Alternatively you may want to try the enterprise edition where you may change the SID to workaround this issue

We had tried to download enterprise image but we are getting download issues highlighted to our local Oracle ACS Team

**Comment by yunus-qureshi** [comment]
To download the enterprise image, please provide a image pull secret in your yaml file and also make sure to login and accept the licensing terms. This is a must

**Comment by viju2008** [comment]
> To download the enterprise image, please provide a image pull secret in your yaml file and also make sure to login and accept the licensing terms. This is a must

Dear Sir

It is downloading but breaking in between due to unexpected EOF

**Comment by yunus-qureshi** [comment]
@viju2008 is this still an issue? 

Btw, there is a 21.3 XE image published in container-registry. 
container-registry.oracle.com/database/express:21.3.0-xe

**Comment by yunus-qureshi** [comment]
@viju2008 plz retry with new OraOperator 0.2.0

https://github.com/oracle/oracle-database-operator
