### ISSUE TITLE
Oracle Database - Text file busy while installing oracle linux

### ISSUE THREAD

**Issue by frenchc** [oracle/docker-images#232]
Just tried to create an oracle DB image on debian jessy. It failed with 

/bin/sh: /opt/oracle/install/setupLinuxEnv.sh: /bin/bash: bad interpreter: Text file busy

Add sync to chmod fixed the issue.

**Comment by gvenzl** [comment]
I'm not sure whether `sync` is a fix to the issue or just a workaround. The error above would also be generated when the file is open for write when you try to execute it.

Is this problem consistently reproducible on your environment?

**Comment by frenchc** [comment]
Consistent problem. Fixed with sync. Doesn't work without.

See here for related discussion https://github.com/docker/docker/issues/9547

**Comment by msimion** [comment]
same os, same problem; fixed with sync; thanks!

**Comment by gvenzl** [comment]
Thanks, added the synch in both build files. PR coming soon.
