### ISSUE TITLE
Creating image for Oracle 21.3.0 SE2  very slow

### ISSUE THREAD

**Issue by ballonyi** [oracle/docker-images#2325]
I tried run ` ./buildContainerImage.sh -v 21.3.0 -s` on OpenSUSE 15 first. It finished quickly in 527 second. 
Now I try to do it on Fedora with kernel 5.16.18-200.fc35.x86_64 and I found creating image is very slow.

I can see following: 

```
...
Transaction test succeeded
Running transaction
  Installing : tcp_wrappers-libs-7.6-77.el7.x86_64                        1/121
  Installing : fipscheck-1.4.1-6.el7.x86_64                               2/121
  Installing : fipscheck-lib-1.4.1-6.el7.x86_64                           3/121
  Installing : gzip-1.5-10.el7.x86_64                                     4/121
  Installing : cracklib-2.9.0-11.el7.x86_64                               5/121
```

I got here quickly, but these steps are very slow, progress is 2-3 minute/file only. 
I have Intel core i7, 16GB RAM and SSD. 
I can see that only one core is working, but with 100% load.

Thanks in advance for your help.

**Comment by Djelibeybi** [comment]
Can you compare the output of `docker info` on the two machines? I'm betting this is a filesystem issue as openSUSE probably uses `btrfs` while Fedora may be using `overlay2` or something else entirely.

**Comment by ballonyi** [comment]
The solution: installation procedure described on the [official website](https://docs.docker.com/engine/install/fedora/) is obsoleted, you have to [install moby-engine](https://fedoramagazine.org/docker-and-fedora-35/) instead for Fedora 35.

**Comment by sant123** [comment]
The issue still persist, I'm using Fedora 36 and had to follow the [install moby-engine](https://fedoramagazine.org/docker-and-fedora-35/) post to make it work.

[Uninstall docker](https://docs.docker.com/engine/install/fedora/#uninstall-docker-engine):

```
sudo dnf remove docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras
```

Delete all images, containers, and volumes:
```
sudo rm -rf /var/lib/docker
sudo rm -rf /var/lib/containerd
```

Install moby-engine and docker compose:
```
sudo dnf install moby-engine docker-compose
sudo systemctl enable docker
```

**Comment by kapcus** [comment]
I had a same issue with RHEL 9.1. Based on [this](https://github.com/docker/buildx/issues/379) I have manually added 
`--ulimit nofile=1024000:1024000` into docker build command at the end in the  **buildContainerImage.sh** script and it has fixed the problem

**Comment by polarathene** [comment]
> `--ulimit nofile=1024000:1024000`

Use `1024:524288`, the soft limit should not be higher than `1024` unless necessary (_you'll get a failure about not enough file descriptors / FDs_), while the hard limit of `524288` is the default for systemd (except Docker service file overrides that with `LimitNOFILE=infinity` presently_).

At the very least the soft limit should be `1024`, should avoid additional surprises that may be difficult to troubleshoot, while `524288` is known to be sufficient for the majority of software.

I'm trying to push this change upstream, so eventually it'd be the same value and you would not need the workaround.
