### ISSUE TITLE
Oracle RAC kubernetes YAML file for 2 node RAC

### ISSUE THREAD

**Issue by viju2008** [oracle/docker-images#2327]
Dear Sir,

We were looking for Oracle RAC kuberentes yaml files for deploying . We need two node RAC in Kubernetes so that even in case one node is drained for patching the other node in the 2 node RAC is up .

Please provide the YAML including creation of the persistent volume that can be deployed on Kubernetes.

**Comment by yunus-qureshi** [comment]
@viju2008 RAC support on K8s is not yet available

It will be made as part of https://github.com/oracle/oracle-database-operator for release 23c
