### ISSUE TITLE
How can I implement Dataguard replication for SingleInstance Oracle Database in Kubernetes

### ISSUE THREAD

**Issue by viju2008** [oracle/docker-images#2330]
Dear Sir,

Is it possible to implement Oracle DataGuard replication for SingleInstance Oracle Database in Kubernetes for cluster to cluster replication of Oracle Databases on Kubernetes

Scenario:

We have a Single Instance Database in Cluster-1 in Data Centre 1 and We have to set up a Disaster Recovery Database in Cluster-2 in Data Centre 2 and then replicate the Database as a Physical Standby for the Database in Data Centre1 using Oracle Data Guard or Oracle Active DataGuard. 

Please inform us if the same is possible using Kubernetes. Please provide the YAML

Whenever we switch over to DR, the applications in Data Centre 2 will access the DataCentre 2 DB which would have all the data as it is being synced by Oracle DataGuard.

**Comment by yunus-qureshi** [comment]
@viju2008 DataGuard support for SIDB in K8s will be available as part of [OraOperator](https://github.com/oracle/oracle-database-operator) later this year or early next year
