### ISSUE TITLE
is it possible to wait until database is prepared on first startup?

### ISSUE THREAD

**Issue by AlBundy33** [oracle/docker-images#2338]
we're using the docker image for nightly tests and therefore we recreate the container each night.

currently we're creating the container with docker run -d ....
after that we user docker logs together with grep to wait until the output appears that the database is ready.

is there maybe some command/script inside the container that waits until the database is ready?
something like docker exec -it oracle /foo/bar/wait_until_database_is_ready.sh

or is it possible to start the container and exit after initialization tomdo a first start with docker run (without -d), wait until the first startup is done and finally start the container with docker start.

**Comment by yunus-qureshi** [comment]
@AlBundy33 do you need a use and throw database for your nighty tests?

Have you tried [prebuiltdb](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/extensions/prebuiltdb) extension?

If you are fine with express edition, the 21.3 image on container registry has a prebuiltdb
docker pull container-registry.oracle.com/database/express:21.3.0-xe

**Comment by AlBundy33** [comment]
A prebuiltdb sounds nice - this would reduce the startup time.
In our nightly tests we don't need a volume for persistence because we are deleteing the container anyway.

Is there a way to add some own settings to the image?
e.g. settings in sqlnet.ora (see #2337)

**Comment by yunus-qureshi** [comment]
@AlBundy33 is this on your Mac?  Few users reported about this issue on Mac. 

Also, to make changes to sqlnet.ora.  Simply launch the container with /bin/bash

1. docker run -it <image> /bin/bash
2. Update sqlnet.ora
3. Do a docker commit <container-id> from a 2nd terminal to create the updated image

**Comment by AlBundy33** [comment]
last output was from my mac - on another linux machine it worked as expected.

I hoped there was an easier way to get a working container. :-)

for my problem with DISABLE_OOB I'v added an idea to #2337

but what is the best way to wait until database is sucessfully prepared?
currently I'm doing this
```
  until docker logs oracle1 2>/dev/null | grep -i "ready to use"
  do
    echo "WAITING UNTIL DATABASE IS READY ($count)..."
    count=$[$count + 1]
    # 30 = 5min, 60 = 10min, 90 = 15min
    if [ $count -gt 120 ]; then
      docker logs oracle1
      echo "STOP WAITING - DATABASE MAY NOT BE READY!"
      count=-1
      break
    fi
    sleep 10s
  done
  if [ $count -ge 0 ]; then
    docker exec oracle1 "/bin/sh" -c "echo DISABLE_OOB=ON>>/opt/oracle/oradata/dbconfig/XE/sqlnet.ora"
    docker restart oracle1
  fi
```

but i my opiniom waiting for a specific logoutput is uncool :-)
is there a better way to check if the database is ready?
an integrated script would be nice (maybe with an optional timeout-parameter)

**Comment by yunus-qureshi** [comment]
@AlBundy33 have you checkout this 

https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance#running-scripts-after-setup-and-on-startup

Write a simple script that does "echo DISABLE_OOB=ON>>/opt/oracle/oradata/dbconfig/XE/sqlnet.ora" and put it the setup volume to be execute once the DB setup is complete

**Comment by AlBundy33** [comment]
the intention of this issue here is really to wait until the database is up and running because we cannot start our nightly tests until the database is available.

my current check is working but I hoped for a better solution.

**Comment by yunus-qureshi** [comment]
@AlBundy33 ok you have 2 requirements.

1. Wait for DB to to start your nightly tests
2. Add DISBALE_OOB to sqlnet.ora

For #2, you may use what I suggested above with DB startup/setup scripts

For #1, you may query the container state in loop until you get Health state to indicate DB is up and running

$> docker inspect -f {{.State.Health.Status}}  <container-id>
starting
$>docker inspect -f {{.State.Health.Status}}  <container-id>
healthy

**Comment by AlBundy33** [comment]
checking the health-status is a good idea - I'll try that 👍 
for sqlnet.ora I'll switch to #2337

**Comment by IshaanDesai45** [comment]
#2607 This PR includes the `DISABLE_OOB=ON` workaround which would solve this problem
