### ISSUE TITLE
Oracle RAC in Docker fails on Ubuntu Server 20.04.4 LTS with Error response from daemon: Your kernel does not support CPU real-time scheduler

### ISSUE THREAD

**Issue by ghost** [oracle/docker-images#2346]
Apparently, it needs a real time kernel, which involves recompiling and installing a custom kernel.
However, Ubuntu claims their low latency kernel is good enough:

https://ubuntu.com/blog/industrial-embedded-systems
https://ubuntu.com/blog/industrial-embedded-systems-ii
https://ubuntu.com/blog/industrial-embedded-systems-iii

Possibly they will have a RT kernel soon. But, the question is. is the low latency kernel good enough?
I'm am not asking for production purposes.

**Comment by psaini79** [comment]
@Altitude-Dashboard , RAC requires RT processes as of today so better to have it. RAC on Docker is supported on OL7.x. For details, please refer following:

https://docs.oracle.com/en/database/oracle/oracle-database/21/racdk/oracle-real-application-clusters-installation-guide-docker-containers-oracle-linux-x86-64.pdf

**Comment by psaini79** [comment]
Closing this issue. Please reopen if you have any question.
