### ISSUE TITLE
OracleConnectionManager fails with su: cannot open session: Permission denied

### ISSUE THREAD

**Issue by ghost** [oracle/docker-images#2349]
./buildContainerImage.sh -v 19.3.0

Loaded plugins: ovl
Cleaning repos: ol7_latest
su: cannot open session: Permission denied
Error: error building at STEP "RUN chmod 755 $INSTALL_DIR/install/*.sh &&     sync &&     $INSTALL_DIR/install/$CHECK_SPACE_FILE &&     $INSTALL_DIR/install/$SETUP_LINUX_FILE &&     $INSTALL_DIR/install/$DB_SETUP_FILE  &&     sed -e '/hard *memlock/s/^/#/g' -i /etc/security/limits.d/oracle-database-preinstall-19c.conf &&     su oracle -c "$INSTALL_DIR/install/$INSTALL_DB_BINARIES_FILE EE" &&     $INVENTORY/orainstRoot.sh &&     $DB_HOME/root.sh &&     rm -rf $INSTALL_DIR/install &&     rm -f /etc/sysctl.d/99-oracle-database-preinstall-19c-sysctl.conf &&     rm -f /etc/sysctl.d/99-sysctl.conf &&     rm -f /etc/rc.d/init.d/oracle-database-preinstall-19c-firstboot &&     rm -f /etc/security/limits.d/oracle-database-preinstall-19c.conf &&     rm -f $INSTALL_DIR/install/*  &&     chown -R oracle:oinstall $SCRIPT_DIR &&     chmod 755 $SCRIPT_DIR/*.sh &&     chmod 666 $SCRIPT_DIR/*.ora &&     chmod 777 /tmp &&     sync": error while running runtime: exit status 1
There was an error building the image.

Red Hat Enterprise Linux release 9.0 Beta (Plow)

podman info
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 3a898eb433ae426e729088ccdc2bdae44a3164da'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "9.0"
  eventLogger: journald
  hostname: nuc11.altitude-dashboard.com
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.0-70.3.1.rt21.73.el9_0.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 30125428736
  memTotal: 33117736960
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-4.el9.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 34464591872
  swapTotal: 34464591872
  uptime: 5m 56.35s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
  - docker.io
store:
  configFile: /home/codrut/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/codrut/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 22
  runRoot: /run/user/1000/containers
  volumePath: /home/codrut/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1648204539
  BuiltTime: Fri Mar 25 12:35:39 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2

**Comment by abhisbyk** [comment]
@ghost This problem is occurring because the Podman is not fully setup to work in the rootless environment. Please follow the link below to setup:
[https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md)


Additionally, you can run podman in root mode to avoid this problem, if you don't want to setup rootless podman. Hope this helps !!

Closing this issue for now. Please feel free to reopen in the problem persists.
