### ISSUE TITLE
sh: tuxedo12.1.3_silent_install.sh: No such file or directory

### ISSUE THREAD

**Issue by odedia** [oracle/docker-images#235]
It is unclear from the documentation what to do with tuxedo12.1.3_silent_install.sh.template.

just running a command like:

odedia$ ./buildDockerImage.sh -v 12.1.3 -i tuxedo121300_64_Linux_01_x86.zip -s

Fails saying it cannot find the installer.sh.

Any ideas what is missing?

Output log below.

Thanks!

=====================
Skipped MD5 checksum.
=====================
=====================
Sending build context to Docker daemon 292.2 MB
Step 1/12 : FROM oraclelinux
 ---> 4c357c6e421e
Step 2/12 : MAINTAINER Todd Little <todd.little@oracle.com>
 ---> Using cache
 ---> 48b3096d14a1
Step 3/12 : RUN yum -y install unzip gcc file; yum -y clean all &&     groupadd -g 1000 oracle; useradd -b /home -m -g oracle -u 1000 -s /bin/bash oracle &&     echo oracle:oracle | chpasswd; echo root:samplesvm | chpasswd
 ---> Using cache
 ---> 1edf14d733a5
Step 4/12 : COPY install.sh tuxedo12.1.3.rsp p*_121300_Linux-x86-64.zip tuxedo121300_64_Linux_01_x86.zip /home/oracle/Downloads/
 ---> Using cache
 ---> 0d4c107f36ed
Step 5/12 : RUN chown oracle:oracle -R /home/oracle
 ---> Using cache
 ---> 69bbdfc06087
Step 6/12 : WORKDIR /home/oracle/Downloads
 ---> Using cache
 ---> 1b28c0ec37c9
Step 7/12 : USER oracle
 ---> Using cache
 ---> b10497c2ea2d
Step 8/12 : RUN sh tuxedo12.1.3_silent_install.sh p*_121300_Linux-x86-64.zip tuxedo121300_64_Linux_01_x86.zip
 ---> Running in 2cf3890bc63e
**sh: tuxedo12.1.3_silent_install.sh: No such file or directory**
The command '/bin/sh -c sh tuxedo12.1.3_silent_install.sh p*_121300_Linux-x86-64.zip tuxedo121300_64_Linux_01_x86.zip' returned a non-zero code: 127
Build of Tuxedo Docker image failed.

**Comment by brunoborges** [comment]
Have you downloaded the actual binaries?

**Comment by odedia** [comment]
I did download the zip file, hopefully the correct one.  See in the logs the zip file name in step 4 that passed.

**Comment by odedia** [comment]
Where should it be placed, in upper folder or inside folder with version number? The documentation is not clear enough.

**Comment by brunoborges** [comment]
As you can see on [this line](https://github.com/oracle/docker-images/blob/master/OracleTuxedo/dockerfiles/12.2.2/Dockerfile#L22) the binary must be on the same directory as the Dockerfile

**Comment by odedia** [comment]
When placing the zip file inside the folder, i get:

alonbl02:dockerfiles odedsh$ ./buildDockerImage.sh -v 12.1.3 -s -i tuxedo121300_64_Linux_01_x86.zip
=====================
Skipped MD5 checksum.
=====================
Download the Tuxedo ZIP Distribution and
drop the file tuxedo121300_64_Linux_01_x86.zip in this folder before
building this Tuxedo Docker container!


Maybe I misinterpreting the meaning of the required -i entry. It is not included as required in the documentation. What should be placed there?

**Comment by brunoborges** [comment]
Can you please remove the `-s` parameter?

**Comment by jefp** [comment]
Hi @brunoborges / @odedia , it seems a bug of the Dockerfile for tuxedo 12.1.3. It never copy the file tuxedo12.1.3_silent_install.sh.
Instead, it only copy install.sh which is never [called.](https://github.com/oracle/docker-images/blob/master/OracleTuxedo/dockerfiles/12.1.3/Dockerfile#L20)

This was fixed for Dockerfile 12.2.2

**Comment by odedia** [comment]
Hi @jefp,
12.2.2 fails on the following error much earlier:

odedsh01-mac:dockerfiles odedsh$ ./buildDockerImage.sh -v 12.2.2 -s -i tuxedo122200_64_Linux_01_x86.zip 
=====================
Skipped MD5 checksum.
=====================
=====================
Sending build context to Docker daemon 292.4 MB
Step 1 : FROM oracle/serverjre:8
Pulling repository docker.io/oracle/serverjre
Error: image oracle/serverjre:8 not found
Build of Tuxedo Docker image failed.

**Comment by odedia** [comment]
I was able to resolve the above issue by building the Oracle Java 8 from this very git repo before running Oracle Tuxedo.

I recommend to update or remove 12.1.3 and also to update the documentation to describe this dependency.

Thanks for all the help!

**Comment by brunoborges** [comment]
@odedia can we close this issue?

**Comment by odedia** [comment]
Yes, thank you.
