### ISSUE TITLE
WLS domain docker build -t 1221-domain gives ...Unknown instruction: ECHO

### ISSUE THREAD

**Issue by nackie99** [oracle/docker-images#236]
There has been a subtle change in docker parsing and this error occurs due to this. The fix is simple (once you find out why!), there is extra whitespace after '\' in a continuation line, it just needs to be removed.

So in OracleWebLogic/samples/1221-domain, edit line 60 in Dockerfile to remove the extra space at the end and it will work again. 

Hope this helps save time for those using the sample WLS domain until its fixed!

**Comment by brunoborges** [comment]
Thanks @nackie99 !
