### ISSUE TITLE
ORA-12547: TNS:lost contact

### ISSUE THREAD

**Issue by Freemason-12** [oracle/docker-images#2360]
I installed your docker container by using 2 commands:
`sudo docker pull pvargacl/oracle-xe-18.4.0:latest`
`sudo docker run --name oracle18 -d -p 1521:1521 pvargacl/oracle-xe-18.4.0`

and then tried executing it with this comand:
`sudo docker exec -ti oracle18 sqlplus`

Got this:
`SQL*Plus: Release 18.0.0.0.0 - Production on Sat May 7 10:18:17 2022`
`Version 18.4.0.0.0`

`Copyright (c) 1982, 2018, Oracle.  All rights reserved.`

`Enter user-name: sys`
`Enter password:` 
`ERROR:`
`ORA-12547: TNS:lost contact`

Using Ubuntu MATE 20.04 LTS

**Comment by abhisbyk** [comment]
@Freemason-12 You have to connect as `sysdba` if you want to connect with `sys` user. Also, you have to specify the service name (i.e. XE in this case). The sample command is as follows:
```bash
sudo docker exec -it oracle18 sqlplus sys@XE as sysdba
```
It will prompt for the password. After entering the password the connection will be successful. Please let me know if this resolved you issue.

**Comment by Freemason-12** [comment]
I couldn't know that since I made a reinstall of my OS and, at least to me
issue seems irrelevant now: Database course on my course is over.
Sorry for this.

**Comment by abhisbyk** [comment]
Ok, no problem. Closing this issue.
