### ISSUE TITLE
Increasing NoSQL KVLite storage size

### ISSUE THREAD

**Issue by RVSagar** [oracle/docker-images#2365]
Hi There,

Thanks for the nice docker images. I'm testing out the NoSQL image and noticed this output `...available storage size:1023 MB...` when running this command as in the README:

```bash
docker run --rm -ti --link kvlite:store oracle/nosql:ce \
  java -jar lib/kvstore.jar runadmin -host store -port 5000 -store kvstore

kv-> ping
```

Does this mean there's only 1023 MB of storage for any tables created? Is there a way to increase this (e.g., setting some flag)?

Thanks for any help!

**Comment by dario-vega** [comment]
Glad to see that it is helpful.

This container image uses **KVLite**. KVLite is a **simplified version** of the Oracle NoSQL Database. It provides a single storage node, a single shard store, with no replication and no administration. It runs in a single process. **Note**: KVLite is not intended for production deployment or performance measurements.

The CE 21.2 version introduces a new parameter `storagedirsizegb` . This parameter can be used to control the size of the storage directory for a new KVLite instance. By default, the KVLite store created has a size of 10GB, and this flag must be used to override that. 

We are in the process of delivering the CE 21.2 version, and I will publish a new version of this container image, taking it into account this KVLite parameter -  `storagedirsizegb`. I will let you know when it is available. In the current version, 20.3, **it is not possible to change**, and the default value is `~1GB`

The Oracle NoSQL Database is a scalable, distributed NoSQL database, designed to provide highly reliable, flexible, and available data management across a configurable set of storage nodes. 

Let me know if you need more help, or want to know more about **Oracle NoSQL Database**

**Comment by RVSagar** [comment]
Hi Dario,

Thanks for getting back and providing some comprehensive info! Glad to hear that the images will be updated to CE 21.2 soon, I'll wait for that so I can increase the storage size.

A bit unrelated, but I was also poking around and came across your [draft-docker-kvlite-secure](https://github.com/dario-vega/draft-docker-kvlite-secure) and related [thread](https://community.oracle.com/tech/developers/discussion/4496876/unable-to-add-security-to-an-existing-oracle-nosql-database-ce-installation/p2). I have some interest in this setup as well, and I imagine after the updating this repo, porting over changes (CE 21.2)  to the secure setup shouldn't be too hard either?

Thanks for your help!

**Comment by RVSagar** [comment]
Thanks Dario, appreciate you looking into this. I will message you on slack with any questions or clarifications.

To answer your question here: I'm just prototyping a solution with Oracle NoSQL and want the ability to add multiple users with passwords (certificates would be nice but not required for me, but I guess for Oracle NoSQL secure setup, certificates are needed?). I'd then like to use the Python API to make and populate tables. I essentially have this working with the Oracle Cloud free tier but I need more than 25GB of storage (and hence, I'm looking for some 'on-premise' solutions). Again, this is just a prototype so I thought KVLite may be okay (and the Docker solution was attractive and simple) but perhaps I could go a step further and look into your [demo-simple-nosql-cluster](https://github.com/dario-vega/demo-simple-nosql-cluster) (although I think security is disabled there too). I really only need a minimal 1x1 setup for now.

**Comment by dario-vega** [comment]
The aim of this container image is: You can deploy a container-based Oracle NoSQL Database store first for a prototype project and move forward to the Oracle NoSQL Database cluster for a production project. It is exactly your case. This container image is what you need.

It is not related to this issue. But this is excellent feedback.  I need to finish the draft project -support secure configuration- and put it here. (It is a valid enhancement request, and we are working on it).

I am looking forward to your message on the public slack channel.

**Comment by dario-vega** [comment]
`CE 21.2` is available. Unfortunately, I need to wait before merging the last Pull Request to solve this issue. I have an unexpected behavior change that impacts the current procedure to build the container images. Working on it.

@RVSagar In the meantime, I sent you a temporary solution in slack. It allows using of CE 21.2. and fix this issue
