### ISSUE TITLE
root password of container

### ISSUE THREAD

**Issue by AlpNek** [oracle/docker-images#237]
What is the root password of the container?

**Comment by brunoborges** [comment]
More information would be helpful. There are many projects and many samples in this repository.

**Comment by Djelibeybi** [comment]
There is no root password inside a container. It's never set during the build process.

**Comment by nackie99** [comment]
You can change the sample Dockerfile's to set one or if you just want to look around, then you can use one of the many examples found with a little Googling:

docker exec -u 0 -it mycontainer bash

**Comment by belaboros** [comment]
`docker exec -u 0 -it oracledb bash
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "chdir to cwd (\"/home/oracle\") set in config.json failed: permission denied": unknown`

I am running an Oracle 12.2.0.1 DB in docker container, but cannot get root access.

**Comment by belaboros** [comment]
Found solution to root access by adding "--workdir /" explicitly:
https://rmoff.net/2018/11/30/logging-in-as-root-on-oracle-database-docker-image/

```
docker exec -u root --workdir / -ti oracledb /bin/sh
```

**Comment by macio-sap** [comment]
> Found solution to root access by adding "--workdir /" explicitly:
> https://rmoff.net/2018/11/30/logging-in-as-root-on-oracle-database-docker-image/
> 
> ```
> docker exec -u root --workdir / -ti oracledb /bin/sh
> ```

It works Thank you very much.
