### ISSUE TITLE
problem creating patch branch

### ISSUE THREAD

**Issue by itroll42** [oracle/docker-images#2379]
I've downloaded this project, and built a oracledb:19.3.0 image off the singleinstance.19.3.0 (downloading the `LINUX.X64_193000_db_home.zip` file from oracle .  Using the buildContainerImage.sh making sure to specify `'--build-arg SLIMMING=false'`.

That image built succesfully.

I have now placed the p33859194_190000_Linux-x86-64.zip file under the patching/patches/release_update folder.  and tried running the command `./buildExtensions.sh -a -b oracle:19.3.0 -t oracle:19.3.0_patched`

This results in a failed image build with the following

`#7 0.255 Unzipping /opt/install/patches/release_update/p33859194_190000_Linux-x86-64.zip
#7 25.68 No one-offs to be installed.
#7 25.68 Applying Release Update: 33859194
#7 25.68 Running: /opt/oracle/product/19c/dbhome_1/OPatch/opatchauto apply -binary -oh /opt/oracle/product/19c/dbhome_1 /opt/install/patches/33859194 -target_type rac_database
#7 29.01 OPATCHAUTO-72083: Performing bootstrap operations failed.
#7 29.01 OPATCHAUTO-72083: The bootstrap execution failed because OPATCHAUTO-72146: Failed to load patch
#7 29.01 OPATCHAUTO-72146: Failed while collecting patch information for patch /opt/install/patches/33859194.
#7 29.01 OPATCHAUTO-72146: Check the log for more information..
#7 29.01 OPATCHAUTO-72083: Fix the reported problem and re-run opatchauto.
#7 29.03 
#7 29.03  perl patching initializaion failed with error code 255.
#7 29.03 RU application failed for patchset: 33859194
`

I'm also trying to determine how to apply the 4 patch files I have to this db image.
I have these patch files that all need applied:
p33859194_190000_Linux-x86-64.zip
p33810130_190000_Linux-x86-64.zip
p33803476_190000_Linux-x86-64.zip
p6880880_190000_Linux-x86-64.zip

any help with this would be greatly appreciated.  I'm new to trying to patch an oracle container image.

**Comment by itroll42** [comment]
I've updated my buildextensions call to utilize `-x 'patching'` instead of `-a` due to the need to externalize the data for persistence.  reading the documentation it appears the prebuiltdb extension will not allow for this.

another step/question I have is once I can get this patching working.  with an externalized data persistence.  If I create a new build with new patches, how will that work with the externalized persistence?

**Comment by itroll42** [comment]
So another update on this.  of the 4 patch files I have, i noticed that the way the automated patching works the pxxxxx file name is required to create a folder when unzipped with a matching xxxxx name.  This is not the case with some of these patches.  One of the patches I have contained 2 folders, as a work around, I seperated those two folders into their own zip files, and one of the other zips contained a folder that just didn't match the number.  I updated my list of patch files to the following.

```
p6880880_190000_Linux-x86-64.zip
p33806152_190000_Linux-x86-64.zip
p33808367_190000_Linux-x86-64.zip
p33810130_190000_Linux-x86-64.zip
p33815596_190000_Linux-x86-64.zip
```

And placed all of these in the one-offs directory.  This allowed the patched db to build successfully, and it did startup successfully as well.

So the main problem is that patch zip files that contain combination patches will not work with the patching design currently in place.  This may have just been my misunderstanding of how its supposed to work.  But it's a simple work around to get this patched up.

My next test is to build our db with the 19.3 base db and create our pdb with all our schemas in it in an external volume.  Then bring down the container and start it back up using the new patched 19.15 database and see how that goes.  Again, persistence of data cross patch is what we hope to obtain, any information on good/bad/other/how-to's on this would be greatly appreciated.

**Comment by yunus-qureshi** [comment]
@itroll42 your analysis is correct. 33859194 is a combo patch of 19.15 OJVM and DB RU.  The current build scripts do not work for combo patches. So you need to download the 19.15 RU and OJVM patches separately. Place the 19.15 RU under the release_update folder and all other patches including 6880880 under one-offs folder. Now execute the build, it should go through fine. 

On the second part of your question, yes bring down the 19.3 container and start up the newly built 19.15 mounting the same external volume. Datapatch will execute automatically patching your datafiles to 19.15 as you can see from the container logs. 

Let us know how it went.

**Comment by yunus-qureshi** [comment]
Combo patch support will be added soon

**Comment by itroll42** [comment]
thank you for the confirmation of the patches themselves, and of the patching of the mounted external volumes.  
Last question I have, i placed all the patches in the one-offs folder, even the RU.  no errors occurred, and it seems to have patched.  But i'm guessing I should make sure that the RU is truely in the release_update folder even though it appeared to work with everything in one-offs?

**Comment by yunus-qureshi** [comment]
@itroll42 yes, placing the RU in the release_update folder is recommended because that will ensure that RU is applied first before the one-offs.
But if the build has succeeded with RU in the one-offs folder then there is nothing to worry.
