### ISSUE TITLE
Getting an Error message while creating a oracle db image on WSL distro ubuntu

### ISSUE THREAD

**Issue by altaf369us** [oracle/docker-images#2380]
Am i doing something wrong here. 

sudo ./buildContainerImage.sh -v 18.4.0 -x
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Checking Podman version.
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Ignored MD5 checksum.
==========================
Container runtime info:
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - devices
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 8
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: file
  hostname: amohamm1-5490c
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.4.0-19041-Microsoft
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 4532404224
  memTotal: 17032581120
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: false
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 31059124224
  swapTotal: 31604994048
  uptime: 32h 54m 53.84s (Approximately 1.33 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: <unknown>
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 29
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4

==========================
Building image 'oracle/database:18.4.0-xe' ...
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
STEP 1/8: FROM oraclelinux:7-slim
STEP 2/8: LABEL "provider"="Oracle"                                                     "issues"="https://github.com/oracle/docker-images/issues"               "volume.data"="/opt/oracle/oradata"                                     "volume.setup.location1"="/opt/oracle/scripts/setup"                    "volume.setup.location2"="/docker-entrypoint-initdb.d/setup"            "volume.startup.location1"="/opt/oracle/scripts/startup"                "volume.startup.location2"="/docker-entrypoint-initdb.d/startup"        "port.listener"="1521"                                                  "port.oemexpress"="5500"                                                "port.apex"="8080"
--> ad8f7bb39b6
STEP 3/8: ENV ORACLE_BASE=/opt/oracle     ORACLE_HOME=/opt/oracle/product/18c/dbhomeXE     ORACLE_SID=XE     INSTALL_FILE_1="https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm"     RUN_FILE="runOracle.sh"     PWD_FILE="setPassword.sh"     CONF_FILE="oracle-xe-18c.conf"     CHECK_SPACE_FILE="checkSpace.sh"     CHECK_DB_FILE="checkDBStatus.sh"     INSTALL_DIR="$HOME/install"     ORACLE_DOCKER_INSTALL="true"
--> dca2812d99b
STEP 4/8: ENV PATH=$ORACLE_HOME/bin:$PATH
--> 9772817bfa5
STEP 5/8: COPY $CHECK_SPACE_FILE $RUN_FILE $PWD_FILE $CHECK_DB_FILE $CONF_FILE $INSTALL_DIR/
--> e90e39561ba
STEP 6/8: RUN chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     cd $INSTALL_DIR &&     yum -y install expect openssl oracle-database-preinstall-18c &&     sed -i -e 's/\(oracle\s\+hard\s\+nofile\)/# \1/' /etc/security/limits.d/oracle-database-preinstall-18c.conf &&     unbuffer yum -y install $INSTALL_FILE_1 &&     yum -y remove expect &&     rm -rf /var/cache/yum &&     rm -rf /var/tmp/yum-* &&     mkdir -p $ORACLE_BASE/scripts/setup &&     mkdir $ORACLE_BASE/scripts/startup &&     ln -s $ORACLE_BASE/scripts /docker-entrypoint-initdb.d &&     mkdir -p $ORACLE_BASE/oradata /home/oracle &&     chown -R oracle:oinstall $ORACLE_BASE /home/oracle &&     mv $INSTALL_DIR/$RUN_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$PWD_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$CHECK_DB_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$CONF_FILE /etc/sysconfig/ &&     ln -s $ORACLE_BASE/$PWD_FILE / &&     cd $HOME &&     rm -rf $INSTALL_DIR &&     chmod ug+x $ORACLE_BASE/*.sh
WARN[0000] pkg/bind: error removing "/var/tmp/buildah4005439925/mnt": directory not empty
ERRO[0000] directory not empty
error running container: error bind mounting root filesystem from "/var/lib/containers/storage/overlay/dbeeb6e9836b25b3891cb820d6eae8da8dfea05d14b62d41852b0594951c71aa/merged" to "/var/tmp/buildah4005439925/mnt/rootfs": invalid argument
Error: error building at STEP "RUN chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     cd $INSTALL_DIR &&     yum -y install expect openssl oracle-database-preinstall-18c &&     sed -i -e 's/\(oracle\s\+hard\s\+nofile\)/# \1/' /etc/security/limits.d/oracle-database-preinstall-18c.conf &&     unbuffer yum -y install $INSTALL_FILE_1 &&     yum -y remove expect &&     rm -rf /var/cache/yum &&     rm -rf /var/tmp/yum-* &&     mkdir -p $ORACLE_BASE/scripts/setup &&     mkdir $ORACLE_BASE/scripts/startup &&     ln -s $ORACLE_BASE/scripts /docker-entrypoint-initdb.d &&     mkdir -p $ORACLE_BASE/oradata /home/oracle &&     chown -R oracle:oinstall $ORACLE_BASE /home/oracle &&     mv $INSTALL_DIR/$RUN_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$PWD_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$CHECK_DB_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$CONF_FILE /etc/sysconfig/ &&     ln -s $ORACLE_BASE/$PWD_FILE / &&     cd $HOME &&     rm -rf $INSTALL_DIR &&     chmod ug+x $ORACLE_BASE/*.sh": error while running runtime: exit status 1

ERROR: Oracle Database container image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the build operation.

**Comment by yunus-qureshi** [comment]
21.3 XE is also available. Do try that. 
Also, have you set the required env vars required for podman build

https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md#building-the-container-images-using-podman

**Comment by altaf369us** [comment]
Yes  i have, Following is the error i'm getting it now.

![Capture2](https://user-images.githubusercontent.com/89571078/171649150-fd91169a-de30-4cc1-81b8-c36ba93f8c96.PNG)

**Comment by altaf369us** [comment]
I have tried with the 21.3 XE, following is the error i'm getting.

![Capture3](https://user-images.githubusercontent.com/89571078/171649780-d5036002-0fdf-4613-ae31-39f05ca9cc84.PNG)

**Comment by yunus-qureshi** [comment]
If you need express edition, pass -x instead of -e

**Comment by altaf369us** [comment]
forgot to attached the SCs.
![Capture3](https://user-images.githubusercontent.com/89571078/171662631-cf0abb4f-59cd-4844-a62a-998e769bac60.PNG)
![Capture4](https://user-images.githubusercontent.com/89571078/171662634-8a2d86e8-d2c9-4a68-ae40-760f902abdd7.PNG)
![Capture1](https://user-images.githubusercontent.com/89571078/171662637-b17beb20-18bc-4c6a-bc11-8ce986d22291.PNG)
![Capture2](https://user-images.githubusercontent.com/89571078/171662639-587b281f-5144-4435-ae3c-4e3aba83468f.PNG)

I have tried it with -x also, no luck.

**Comment by altaf369us** [comment]
forgot to add the SCs, i have tried it with -x, no luck. please find the screen shots. also tried with 18 and 21 XE, getting same error.
![Capture5](https://user-images.githubusercontent.com/89571078/171663368-ec259c6a-ec8d-4afe-9a5e-648a11a799e4.PNG)
![Capture6](https://user-images.githubusercontent.com/89571078/171663370-280a8ae5-86c6-4d74-8f5b-d8608829b13f.PNG)
![Capture7](https://user-images.githubusercontent.com/89571078/171663372-2199b1b2-bf57-4980-ba2f-b278ebe9b831.PNG)
![Capture4](https://user-images.githubusercontent.com/89571078/171663373-49ed8d56-2b30-43ef-9eac-653e9a032d4c.PNG)

**Comment by yunus-qureshi** [comment]
Have you tried after setting the BUILDAH envs as documented
https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md#building-the-container-images-using-podman

**Comment by altaf369us** [comment]
i'm using ubuntu version 22.04 on windows.

**Comment by altaf369us** [comment]
You know what, i was using WSL version 1. I changed the WSL version from 1 to 2, running it rootless. seems to be working. passed that stage where i was getting an error. will share the update. currently installing. pls find SCs below.

![Capture](https://user-images.githubusercontent.com/89571078/171696707-db3937f7-086a-446d-bfe6-bccd2f1c5402.PNG)

**Comment by altaf369us** [comment]
![Capture2](https://user-images.githubusercontent.com/89571078/171776012-39f642e1-66d8-42e0-84e2-ba6817c8110e.PNG)

**Comment by yunus-qureshi** [comment]
It doesn't tell me how much free disk space is available. 
Also did you try 21.3 XE?

**Comment by altaf369us** [comment]
I have tried it, it just hang there. please find the free disk info here. 

![Capture1](https://user-images.githubusercontent.com/89571078/171783826-0370108b-cf5e-4725-8754-93f43fb6a7c9.PNG)
![Capture2](https://user-images.githubusercontent.com/89571078/171783829-7a50aa65-9ceb-4c9c-b538-254980b0dec6.PNG)

**Comment by altaf369us** [comment]
I'am able to build oracle xe 18.4.0 database image inside the container. However, I like to know does oracle have The Oracle XE Database 18c server Docker image that contains a pre-built database? like this one https://container-registry.oracle.com/ords/f?p=113:4:115087109343200:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:803,803,Oracle%20Database%20Express%20Edition,Oracle%20Database%20Express%20Edition,1,0&cs=36bdIC2zPi95OaD0_Z9htSDJqSOC3ffVUnH3H1Jrg4xnsSOYnaoRFe6zQg0Ahmjccgdsm1o412kzJyaz191UOow

**Comment by abhisbyk** [comment]
@altaf369us Oracle does not have 18.4 XE image with pre-built database. Oracle database 21.3 XE has a pre-built database and is also available on the container registry.

**Comment by yunus-qureshi** [comment]
@altaf369us is the 21.3 XE image from container-registry working for you?

docker pull  container-registry.oracle.com/database/express:latest

**Comment by altaf369us** [comment]
I have built 18.4.0 XE image container. Now, I would like to know how would i connect to it? is this the suername SYS, SYSTEM and PDBADMIN to connect to Oracle DB? Basically, I just need an assistance in connecting to the DB.

**Comment by altaf369us** [comment]
![oracle db](https://user-images.githubusercontent.com/89571078/172769396-62ec8484-b0c3-44be-9654-5607e33e9425.PNG)
![Oradba xe](https://user-images.githubusercontent.com/89571078/172769397-2009c1dc-fd7f-4807-867e-21b496a41e3a.PNG)
![Oradbcontainer](https://user-images.githubusercontent.com/89571078/172769399-a2b751d8-9aa3-46a5-a333-316b3458a426.PNG)

**Comment by abhisbyk** [comment]
To connect with the database, you can use `sqlplus`. Here, SYS, SYSADMIN and PDBADMIN are users to the DB. Sample commands for database version 18.3 XE are as follows:

```bash
sqlplus sys/<your-db-password>@//localhost:1521/XE as sysdba
sqlplus system/<your-db-password>@//localhost:1521/XE
sqlplus pdbadmin/<your-db-password>@//localhost:1521/XEPDB1
```
