### ISSUE TITLE
Docker image for Oracle Database 12c EE fails to build

### ISSUE THREAD

**Issue by zaunerc** [oracle/docker-images#239]
When using the latest clone of this repository (commit ``b4f2f00a70e60fb1b39767ff6c085546dada9bb6``) to build an Docker image for the Oracle Database 12c Enterprise Edition I get the following error:

```
christoph@nelap:~/repos/docker-images/OracleDatabase/dockerfiles$ sudo ./buildDockerImage.sh -v 12.1.0.2 -e
<...>
Step 10 : USER root
 ---> Running in 0786cd59c1b2
 ---> a4f49555ad17
Removing intermediate container 0786cd59c1b2
Step 11 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in 8a347f5bcaa0
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
Removing intermediate container 8a347f5bcaa0
The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR' returned a non-zero code: 127
There was an error building the image.
christoph@nelap:~/repos/docker-images/OracleDatabase/dockerfiles$
```

**Comment by gkgeorgiev** [comment]
That's exactly the same issue I'm struggling now! I use the latest Master version and I have the same behavior. Any break through?

**Comment by gvenzl** [comment]
Looks like the database binaries installation failed before and hence why `/opt/oracle/oraInventory` isn't created. Can you please post the entire output of the build.

Thx,

**Comment by gkgeorgiev** [comment]
Here you go...
[output.txt](https://github.com/oracle/docker-images/files/670868/output.txt)


Thanks in advance!

**Comment by gvenzl** [comment]
There you go, you don't have enough space available for the installation:

    Preparing to launch Oracle Universal Installer from /tmp/OraInstall2016-12-23_01-42-13PM. Please wait ...
    [FATAL] [INS-32021] Insufficient disk space on this volume for the selected Oracle home.
       CAUSE: The selected Oracle home was on a volume without enough disk space.
       ACTION: Choose a location for Oracle home that has enough space (minimum of 6,553MB) or free up space on the existing volume.
    A log of this session is currently saved as: /tmp/OraInstall2016-12-23_01-42-13PM/installActions2016-12-23_01-42-13PM.log. Oracle recommends that if you want to keep this log, you should move it from the temporary location.

**Comment by gkgeorgiev** [comment]
Strange, isn't there any way to exit Docker script on the first error? 

Hmm where does the space limit come from? From the unix user quota? I thought that root user doesn't have disk space quota? The VirtualBox image that my Kitematic is using, has dynamically allocated storage, which is limited only by the physical disk space (150GB free).

**Comment by zaunerc** [comment]
@gkgeorgiev, I am using Debian Stretch running Docker 1.12.5:

```
christoph@nelap:/home/docker_data$ sudo docker info
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 276
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-8:4-2883588-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 33.55 GB
 Data Space Total: 107.4 GB
 Data Space Available: 73.82 GB
 Metadata Space Used: 22.91 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.125 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/docker_data/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /home/docker_data/devicemapper/devicemapper/metadata
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.8.0-2-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.666 GiB
<...>
Docker Root Dir: /home/docker_data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
christoph@nelap:/home/docker_data$
```

@gvenzl, you are right. I took a second look at the log file of my Docker build run and it reports that there is no space left for the Oracle Universal Installer to continue ([docker_build_log.txt](https://github.com/oracle/docker-images/files/671364/docker_build_log.txt)).

Though I don't know why I ran out of hard disk space. If you take a look at the output of the `docker info` command you can see that I have plenty of disk space left.

**Comment by gkgeorgiev** [comment]
@zaunerc, you are the man! Thanks for finding this docker option! I will try it next Monday.

Marry Christmas to all of you guys!

**Comment by zaunerc** [comment]
@gkgeorgiev: After increasing the size of the base device I could successfully build the image and start the container.

**Comment by gkgeorgiev** [comment]
How did you pass the basesize option? Was it the same way like me or you have another approach?

**Comment by zaunerc** [comment]
I created the file `/etc/systemd/system/docker.service` and added the following lines:

```
christoph@nelap:~$ cat /etc/systemd/system/docker.service 
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H fd:// --storage-opt dm.basesize=25G 
christoph@nelap:~$
```

After reloading the systemd unit files and restarting the Docker daemon I verfied that the base device size has actually been increased:

```
christoph@nelap:~$ sudo docker info
<...>
Storage Driver: devicemapper
 Pool Name: docker-8:4-2883588-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 26.84 GB
<...>
christoph@nelap:~$
```

Finally I deleted all images and containers and rebuilt the Oracle 12c EE docker image. I did this to make sure that all images which are part of the Oracle Database 12c EE image build process are based on the increased base device size (see [here](http://www.projectatomic.io/blog/2016/03/daemon_option_basedevicesize/) for a more detailed explanation).

**Comment by gvenzl** [comment]
Glad to see that you managed to change the configuration and build the image. Note, Oracle recommends to use `btrfs` instead of the device mapper. As per the [Oracle Linux Docker User's Guide (4.)](https://docs.oracle.com/cd/E37670_01/E75728/html/section_kfy_f2z_fp2.html):

> Oracle recommends using btrfs because of the stability and maturity of the technology. If a new device for btrfs is not available, you should use overlay as the storage driver instead of device-mapper for performance reasons. You can configure overlay by adding the --storage-driver=overlay option to DOCKER_STORAGE_OPTIONS in /etc/sysconfig/docker-storage. The overlayfs file system is available with UEK R4.
> 
> For more information, see https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/.

**Comment by SRINIVASREDDYPV** [comment]
When using the latest clone of this repository (commit b4f2f00a70e60fb1b39767ff6c085546dada9bb6) to build an Docker image for the Oracle Database 12c Enterprise Edition I get the following error:
-----------------------------------------------------------------------------------------------------------
Checking Temp space: must be greater than 500 MB.   Actual 60288 MB    Passed
Checking swap space: must be greater than 150 MB.   Actual 23232 MB    Passed
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-07-07_05-46-05AM. Please wait ...[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
You can find the log of this install session at:
 /opt/oracle/oraInventory/logs/installActions2017-07-07_05-46-05AM.log
The installation of Oracle Database 12c was successful.
Please check '/opt/oracle/oraInventory/logs/silentInstall2017-07-07_05-46-05AM.log' for more details.

As a root user, execute the following script(s):
        1. /opt/oracle/product/12.2.0.1/dbhome_1/root.sh



Successfully Setup Software.

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

 ---> a09e25780715
Removing intermediate container 5881157eda05
Step 12/18 : USER root
 ---> Running in e7d610430de9
 ---> c9d85fa663b4
Removing intermediate container e7d610430de9
Step 13/18 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in 13e7d986cbd4
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
Removing intermediate container 13e7d986cbd4
The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR' returned a non-zero code: 127

Please find the attached build log and DB installation log
[installActions2017-07-07_02-28-42AM.txt](https://github.com/oracle/docker-images/files/1130367/installActions2017-07-07_02-28-42AM.txt)
[build.txt](https://github.com/oracle/docker-images/files/1130366/build.txt)

@gvenzl , Can you please assist me if you have some time ?

**Comment by SRINIVASREDDYPV** [comment]
[root@whf00aiv dockerfiles]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 39
Server Version: 17.03.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.1.12-61.1.27.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 29.47 GiB
Name: whf00aiv.in.oracle.com
ID: IT5E:CE7J:VM7H:U3AV:YHYB:LBZL:6OY2:WZKR:O4GS:QTCR:ZIAE:H4MY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
