### ISSUE TITLE
Error on database container initialization

### ISSUE THREAD

**Issue by Luby1917** [oracle/docker-images#2395]
Trying to deploy a express oracle database I'm facing some problems:

docker-compose.yml
```
version: '2.4'
services:
  db:
    image: container-registry.oracle.com/database/express:latest
    restart: unless-stopped
    ports:
      - 1521:1521
    environment:
      TZ: Europe/Madrid
      ORACLE_PWD: mysecurepassword
```

This configuration results in an **Authentication failure**:

```
db_1_5b84ee2e9c03 | Password: su: Authentication failure
db_1_5b84ee2e9c03 | The Oracle base remains unchanged with value /opt/oracle
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | SQL*Plus: Release 21.0.0.0.0 - Production on Wed Jun 15 16:59:18 2022
db_1_5b84ee2e9c03 | Version 21.3.0.0.0
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | Copyright (c) 1982, 2021, Oracle.  All rights reserved.
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | Connected to an idle instance.
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | SQL>       ALTER USER SYS IDENTIFIED BY "mysecurepassword"
db_1_5b84ee2e9c03 | *
db_1_5b84ee2e9c03 | ERROR at line 1:
db_1_5b84ee2e9c03 | ORA-01034: ORACLE not available
db_1_5b84ee2e9c03 | Process ID: 0
db_1_5b84ee2e9c03 | Session ID: 0 Serial number: 0
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | SQL>       ALTER USER SYSTEM IDENTIFIED BY "mysecurepassword"
db_1_5b84ee2e9c03 | *
db_1_5b84ee2e9c03 | ERROR at line 1:
db_1_5b84ee2e9c03 | ORA-01034: ORACLE not available
db_1_5b84ee2e9c03 | Process ID: 0
db_1_5b84ee2e9c03 | Session ID: 0 Serial number: 0
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | SQL>       ALTER SESSION SET CONTAINER=XEPDB1
db_1_5b84ee2e9c03 | *
db_1_5b84ee2e9c03 | ERROR at line 1:
db_1_5b84ee2e9c03 | ORA-01034: ORACLE not available
db_1_5b84ee2e9c03 | Process ID: 0
db_1_5b84ee2e9c03 | Session ID: 0 Serial number: 0
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | SQL>       ALTER USER PDBADMIN IDENTIFIED BY "mysecurepassword"
db_1_5b84ee2e9c03 | *
db_1_5b84ee2e9c03 | ERROR at line 1:
db_1_5b84ee2e9c03 | ORA-01034: ORACLE not available
db_1_5b84ee2e9c03 | Process ID: 0
db_1_5b84ee2e9c03 | Session ID: 0 Serial number: 0
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | SQL> Disconnected
db_1_5b84ee2e9c03 | The Oracle base remains unchanged with value /opt/oracle
db_1_5b84ee2e9c03 | #####################################
db_1_5b84ee2e9c03 | ########### E R R O R ###############
db_1_5b84ee2e9c03 | DATABASE SETUP WAS NOT SUCCESSFUL!
db_1_5b84ee2e9c03 | Please check output for further info!
db_1_5b84ee2e9c03 | ########### E R R O R ###############
db_1_5b84ee2e9c03 | #####################################
db_1_5b84ee2e9c03 | The following output is now a tail of the alert.log:
db_1_5b84ee2e9c03 | XEPDB1(3):Completed: ALTER DATABASE DEFAULT TABLESPACE "USERS"
db_1_5b84ee2e9c03 | 2022-03-30T10:47:02.401929+00:00
db_1_5b84ee2e9c03 | ALTER PLUGGABLE DATABASE XEPDB1 SAVE STATE
db_1_5b84ee2e9c03 | Completed: ALTER PLUGGABLE DATABASE XEPDB1 SAVE STATE
db_1_5b84ee2e9c03 | 2022-03-30T10:47:03.481932+00:00
db_1_5b84ee2e9c03 | ALTER SYSTEM SET control_files='/opt/oracle/oradata/XE/control01.ctl' SCOPE=SPFILE;
db_1_5b84ee2e9c03 | 2022-03-30T10:47:03.513390+00:00
db_1_5b84ee2e9c03 | ALTER SYSTEM SET local_listener='' SCOPE=BOTH;
db_1_5b84ee2e9c03 | ALTER PLUGGABLE DATABASE XEPDB1 SAVE STATE
db_1_5b84ee2e9c03 | Completed: ALTER PLUGGABLE DATABASE XEPDB1 SAVE STATE
```

If I try to run the container **as root**, the initialization seems to continue but after a while, it looses the connection:

```
db_1_5b84ee2e9c03 | Starting Oracle Net Listener.
db_1_5b84ee2e9c03 | Oracle Net Listener started.
db_1_5b84ee2e9c03 | Starting Oracle Database instance XE.
db_1_5b84ee2e9c03 | Oracle Database instance XE started.
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | The Oracle base remains unchanged with value /opt/oracle
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | SQL*Plus: Release 21.0.0.0.0 - Production on Wed Jun 15 17:03:40 2022
db_1_5b84ee2e9c03 | Version 21.3.0.0.0
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | Copyright (c) 1982, 2021, Oracle.  All rights reserved.
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | ERROR:
db_1_5b84ee2e9c03 | ORA-12547: TNS:lost contact
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | 
db_1_5b84ee2e9c03 | Enter user-name: SP2-0306: Invalid option.
db_1_5b84ee2e9c03 | Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
db_1_5b84ee2e9c03 | where <logon> ::= <username>[/<password>][@<connect_identifier>]
db_1_5b84ee2e9c03 |       <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
db_1_5b84ee2e9c03 | Enter user-name: SP2-0306: Invalid option.
db_1_5b84ee2e9c03 | Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
db_1_5b84ee2e9c03 | where <logon> ::= <username>[/<password>][@<connect_identifier>]
db_1_5b84ee2e9c03 |       <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
db_1_5b84ee2e9c03 | SP2-0157: unable to CONNECT to ORACLE after 3 attempts, exiting SQL*Plus
db_1_5b84ee2e9c03 | The Oracle base remains unchanged with value /opt/oracle
db_1_5b84ee2e9c03 | #####################################
db_1_5b84ee2e9c03 | ########### E R R O R ###############
db_1_5b84ee2e9c03 | DATABASE SETUP WAS NOT SUCCESSFUL!
db_1_5b84ee2e9c03 | Please check output for further info!
db_1_5b84ee2e9c03 | ########### E R R O R ###############
db_1_5b84ee2e9c03 | #####################################
db_1_5b84ee2e9c03 | The following output is now a tail of the alert.log:
db_1_5b84ee2e9c03 | Starting background process CJQ0
db_1_5b84ee2e9c03 | 2022-06-15T17:03:40.438652+02:00
db_1_5b84ee2e9c03 | CJQ0 started with pid=64, OS id=394 
db_1_5b84ee2e9c03 | Completed: ALTER DATABASE OPEN
db_1_5b84ee2e9c03 | 2022-06-15T17:03:41.123785+02:00
db_1_5b84ee2e9c03 | ===========================================================
db_1_5b84ee2e9c03 | Dumping current patch information
db_1_5b84ee2e9c03 | ===========================================================
db_1_5b84ee2e9c03 | No patches have been applied
db_1_5b84ee2e9c03 | ===========================================================
```

It do not seem be a resources constraint:
![image](https://user-images.githubusercontent.com/7126047/173861754-dd0b6b76-18b3-4d10-a5a2-d708851ec09a.png)

Sorry If it's duplicated, but I didn't find any issue related.
Thanks

**Comment by yunus-qureshi** [comment]
The container should be run as oracle user

**Comment by abhisbyk** [comment]
@Luby1917 We have made some changes regarding auth in PR #2419 
Can you please pull the latest changes from github/image from the Container-registry and test again ?

**Comment by abhisbyk** [comment]
Closing this issue for now. Please reopen if this auth issue is encountered again.

**Comment by Ran-oops** [comment]
But, another issue will be threw:

<details>
<summary>Details</summary>

oracle-oracle-1  | Starting Oracle Net Listener.
oracle-oracle-1  | Oracle Net Listener started.
oracle-oracle-1  | Starting Oracle Database instance FREE.
oracle-oracle-1  | Oracle Database instance FREE started.
oracle-oracle-1  |
oracle-oracle-1  | The Oracle base remains unchanged with value /opt/oracle
oracle-oracle-1  |
oracle-oracle-1  | SQL*Plus: Release 23.0.0.0.0 - Developer-Release on Tue May 2 15:48:01 2023
oracle-oracle-1  | Version 23.2.0.0.0
oracle-oracle-1  |
oracle-oracle-1  | Copyright (c) 1982, 2023, Oracle.  All rights reserved.
oracle-oracle-1  |
oracle-oracle-1  | ERROR:
oracle-oracle-1  | ORA-12547: TNS:lost contact
oracle-oracle-1  |
oracle-oracle-1  |
oracle-oracle-1  | Enter user-name: SP2-0306: Invalid option.
oracle-oracle-1  | Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
oracle-oracle-1  | where <logon> ::= <username>[/<password>][@<connect_identifier>]
oracle-oracle-1  |       <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
oracle-oracle-1  | Enter user-name: SP2-0306: Invalid option.
oracle-oracle-1  | Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
oracle-oracle-1  | where <logon> ::= <username>[/<password>][@<connect_identifier>]
oracle-oracle-1  |       <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
oracle-oracle-1  | SP2-0157: unable to CONNECT to ORACLE after 3 attempts, exiting SQL*Plus
oracle-oracle-1  | The Oracle base remains unchanged with value /opt/oracle
oracle-oracle-1  | #####################################
oracle-oracle-1  | ########### E R R O R ###############
oracle-oracle-1  | DATABASE SETUP WAS NOT SUCCESSFUL!
oracle-oracle-1  | Please check output for further info!
oracle-oracle-1  | ########### E R R O R ###############
oracle-oracle-1  | #####################################
oracle-oracle-1  | The following output is now a tail of the alert.log:
oracle-oracle-1  | 2023-05-02T15:48:01.707413+00:00
oracle-oracle-1  | FREEPDB1(3):Opening pdb with Resource Manager plan: DEFAULT_PLAN
oracle-oracle-1  | Completed: Pluggable database FREEPDB1 opened read write
oracle-oracle-1  | Completed: ALTER DATABASE OPEN
oracle-oracle-1  | 2023-05-02T15:48:02.483015+00:00
oracle-oracle-1  | ===========================================================
oracle-oracle-1  | Dumping current patch information
oracle-oracle-1  | ===========================================================
oracle-oracle-1  | No patches have been applied
oracle-oracle-1  | ===========================================================

</details>

**Comment by jpic** [comment]
check if /var or /var/lib/docker is mounted with nosuid, in which case removing nosuid worked for me
