### ISSUE TITLE
Timeout while trying to download  OracleLinux repodata

### ISSUE THREAD

**Issue by gkgeorgiev** [oracle/docker-images#240]
While trying to build my own Oracle 12c image, I get timeout on 
_yum -y install oracle-rdbms-server-12cR1-preinstall unzip wget tar openssl && \_

This is the log error from Docker:

> http://yum.oracle.com/repo/OracleLinux/OL7/UEKR3/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://yum.oracle.com/repo/OracleLinux/OL7/UEKR3/x86_64/repodata/repomd.xml: (28, 'Resolving timed out after 30541 milliseconds')
> Trying other mirror.
> http://yum.oracle.com/repo/OracleLinux/OL7/UEKR3/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://yum.oracle.com/repo/OracleLinux/OL7/UEKR3/x86_64/repodata/repomd.xml: (28, 'Resolving timed out after 30541 milliseconds')
> Trying other mirror.
> http://yum.oracle.com/repo/OracleLinux/OL7/UEKR3/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://yum.oracle.com/repo/OracleLinux/OL7/UEKR3/x86_64/repodata/repomd.xml: (28, 'Resolving timed out after 30541 milliseconds')
> Trying other mirror.
> http://yum.oracle.com/repo/OracleLinux/OL7/UEKR3/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://yum.oracle.com/repo/OracleLinux/OL7/UEKR3/x86_64/repodata/repomd.xml: (28, 'Resolving timed out after 30540 milliseconds')
> Trying other mirror.

I checked the URL via the browser and it seems to be working without any latency.
This is my docker version: Docker version 1.12.5, build 7392c3b
My OS is Ubuntu 16.10 LTS.

I tried even to add manually the Oracle Repos with the following commands:

> cd /etc/yum.repos.d
> wget http://public-yum.oracle.com/public-yum-ol7.repo
> yum-config-manager --disable ol7*
> yum-config-manager --enable ol7_UEKR3

But still doesn't work and I have no idea why

**Comment by gvenzl** [comment]
Are you sure that there is no firewall enabled on your OS blocking the container from reaching the YUM repo?

**Comment by gkgeorgiev** [comment]
@gvenzl , yes, It's a fresh Ubuntu installation, and the only firewall service I could find is inactive.
I've also tried wget with the URL and it downloads the XML.

Another important thing that came to my mind - could it be that the Docker storage driver I'm using is AUFS? It seems that other's with 'devicemapper' driver manage to build an image.

**Comment by gkgeorgiev** [comment]
OK, I found the issue, it was related to my docker daemon not having DNS configured. 
The solution on this post helped me: [http://stackoverflow.com/questions/25130536/dockerfile-docker-build-cant-download-packages-centos-yum-debian-ubuntu-ap](url)

**Comment by Kambaa** [comment]
Hello, today i was having the same problem while building a oracle XE, and these steps make the building process work:


> 
> For me the problem was that my ISP blocked google's DNS (8.8.8.8) which docker uses as a fallback default.
> 
> The trick here is to find out your DNS IP and tell docker to use it.
> 
> In my case (running Ubuntu 17.04), trying to get this information from /etc/resolv.conf did not work, but I used this command:
> 
> nmcli dev show | grep IP4.DNS
> 
> Then I took this IP and added in /etc/defaults/docker:
> 
> DOCKER_OPTS="--dns 192.168.50.1"
> 
> Now restart your docker daemon, and try building again.
> sudo service docker restart
