### ISSUE TITLE
How can i have prebuilt database in kubernetes?

### ISSUE THREAD

**Issue by arezvani** [oracle/docker-images#2400]
I want when my pod is running it doesn't go to create database. I want database started and running without take time for db creation.
What should I do?

**Comment by russgold** [comment]
What Oracle docker image are you using that has this behavior?

**Comment by yunus-qureshi** [comment]
This is going to be supported with OraOperator 0.2.0 release due this month end

https://github.com/oracle/oracle-database-operator

**Comment by yunus-qureshi** [comment]
OraOperator 0.2.0 is available with prebuilt DB support

https://github.com/oracle/oracle-database-operator
