### ISSUE TITLE
Error on create Weblogic Container

### ISSUE THREAD

**Issue by adelmosilva** [oracle/docker-images#2401]
Good morning. When I run the ./buildDockerImage.sh script the error is showed on Java step. 

Set- WebLogic's Version 12.2.1.3
Set- Distribution:Generic
Version= 12.2.1.3 Distribution= generic
Checking if required packages are present and valid...
fmw_12.2.1.3.0_wls_Disk1_1of1.zip: SUCESSO
md5sum: AVISO: 1 linha está formatada inapropriadamente
=====================
Building image 'oracle/weblogic:12.2.1.3-generic' ...
Building image using Dockerfile.'generic'
Sending build context to Docker daemon    839MB
Step 1/19 : FROM oracle/serverjre:8 as builder
pull access denied for oracle/serverjre, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
There was an error building the image.

Congrats for your project and thanks for your support

**Comment by mriccell** [comment]
@adelmosilva  
You need to first create the Server JRE image in https://github.com/oracle/docker-images/tree/main/OracleJava/8.  Once you have built the Server JRE image you will see in your local repo an oracle/serverjre:8 image then you can build the WebLogic image.

**Comment by mriccell** [comment]
Not sure if you are aware that we have pre-built images of WebLogic in the Oracle Container Registry https://container-registry.oracle.com/.
