### ISSUE TITLE
MAX_STRING_SIZE Extended (OracleDatabase - SingleInstance 21c)

### ISSUE THREAD

**Issue by maquejp** [oracle/docker-images#2425]
Following #399 
With Oracle 21c (AL32UTF8)

I followed all the steps but it does not works with NVARCHAR....

`
sqlplus / as sysdba
ALTER SESSION SET CONTAINER=CDB$ROOT;
ALTER SYSTEM SET max_string_size=extended SCOPE=SPFILE;
shutdown immediate;
startup upgrade;
ALTER PLUGGABLE DATABASE ALL OPEN UPGRADE;
EXIT;
cd $ORACLE_HOME/rdbms/admin
mkdir -p /home/oracle/tmp/log_utl32k
$ORACLE_HOME/perl/bin/perl $ORACLE_HOME/rdbms/admin/catcon.pl -u SYS --force_pdb_mode 'UPGRADE' -d $ORACLE_HOME/rdbms/admin -l '/home/oracle/tmp/log_utl32k' -b utl32k_cdb_pdbs_output utl32k.sql
sqlplus / as sysdba
shutdown immediate;
startup;
ALTER PLUGGABLE DATABASE ALL OPEN READ WRITE;
EXIT;
mkdir -p /home/oracle/tmp/utlrp
$ORACLE_HOME/perl/bin/perl $ORACLE_HOME/rdbms/admin/catcon.pl -u SYS --force_pdb_mode 'READ WRITE' -d $ORACLE_HOME/rdbms/admin -l '/home/oracle/tmp/utlrp' -b utlrp_cdb_pdbs_output utlrp.sql
sqlplus / as sysdba
create table testvc (name varchar2(32676));
>>Table created.
create table testnvc (name nvarchar2(4000));
>>ORA-00910: specified length too long for its datatype
`

**Comment by maquejp** [comment]
FYI, I tried different approach without success. E.G.https://connor-mcdonald.com/2020/06/25/max_string_size-stretching-the-dictionary/

**Comment by yunus-qureshi** [comment]
Please open a ticket with [Oracle Support](support.oracle.com)
