### ISSUE TITLE
Docker Hub Issues

### ISSUE THREAD

**Issue by donlinglok** [oracle/docker-images#2429]
Hi, I was trying to pull the docker image of "oracle/database-enterprise:12.2.0.1" from Docker Hub but seems the pages are deprecated.
https://hub.docker.com/_/oracle-database-enterprise-edition

and the [publisher page](https://hub.docker.com/publishers/oracle) is deprecated too.

Is it all oracle docker images will only publish to https://container-registry.oracle.com/ from now on?

**Comment by yunus-qureshi** [comment]
Yes
