### ISSUE TITLE
Oracle Database container image was NOT successfully created.

### ISSUE THREAD

**Issue by Rohittingare** [oracle/docker-images#2449]
I am trying to create docker image for oracle but getting this error. Not able to understand what to do. Please help

`Loaded plugins: ovl
Cannot open: https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm. Skipping.
Error: Nothing to do
Removing intermediate container f367240d1f0a
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     cd $INSTALL_DIR &&     yum -y install expect openssl oracle-database-preinstall-18c &&     sed -i -e 's/\(oracle\s\+hard\s\+nofile\)/# \1/' /etc/security/limits.d/oracle-database-preinstall-18c.conf &&     unbuffer yum -y install $INSTALL_FILE_1 &&     yum -y remove expect &&     rm -rf /var/cache/yum &&     rm -rf /var/tmp/yum-* &&     mkdir -p $ORACLE_BASE/scripts/setup &&     mkdir $ORACLE_BASE/scripts/startup &&     ln -s $ORACLE_BASE/scripts /docker-entrypoint-initdb.d &&     mkdir -p $ORACLE_BASE/oradata /home/oracle &&     chown -R oracle:oinstall $ORACLE_BASE /home/oracle &&     mv $INSTALL_DIR/$RUN_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$PWD_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$CHECK_DB_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$CONF_FILE /etc/sysconfig/ &&     ln -s $ORACLE_BASE/$PWD_FILE / &&     cd $HOME &&     rm -rf $INSTALL_DIR &&     chmod ug+x $ORACLE_BASE/*.sh' returned a non-zero code: 1

ERROR: Oracle Database container image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the build operation.`

**Comment by abhisbyk** [comment]
@Rohittingare It seems some networking issue. The intermediate container is not able to download the RPM file. Are you working behind some proxy or something ??

Additionally, can you please try 21.3 XE image and if the same problem exists there or not ?

**Comment by Rohittingare** [comment]
No, I have working on stable network connection and no proxy used

**Comment by Rohittingare** [comment]
I need to use only 18.4 XE

**Comment by yunus-qureshi** [comment]
@Rohittingare clearly there is a connectivity issue. 

Can you download from the host VM?
wget https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm

**Comment by Rohittingare** [comment]
@yunus-qureshi yes I downloaded the file. What to do next?

**Comment by yunus-qureshi** [comment]
You seem to have some connectivity issue from the container, check if this works

docker run -it busybox sh -c 'wget https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm'

**Comment by Rohittingare** [comment]
my `./buildContainerImage.sh -v 18.4.0 -x`   this command is failing

**Comment by Rohittingare** [comment]
for both commands mine and yours, process stalled after 85%. Please take a look. Its not network issue. I tried many times. issue occures at same location means after 85% completion.
![image](https://user-images.githubusercontent.com/52101615/188879435-832e20f5-9320-4979-a9c2-2f4a77ff21e2.png)

**Comment by Rohittingare** [comment]
> You seem to have some connectivity issue from the container, check if this works
> 
> docker run -it busybox sh -c 'wget https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm'

I used this but still I got Failure. It failed everytime after 85%....Please help to find any resolution.

Thanks in advance

**Comment by yunus-qureshi** [comment]
May be you don't have enough space locally to download the entire file. Check your docker storage. Paste the output of docker info

**Comment by Rohittingare** [comment]
Sorry but I don't have much understanding of docker. Can you help with commands. How to get these information?

**Comment by Rohittingare** [comment]
@yunus-qureshi  Is this info you wanted..
`Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 6
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-47-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.36GiB
 Name: techbulls-HP-EliteBook-840-G3
 ID: 5G4M:2U6E:CUTN:KCAI:WKAR:CLC5:6XBO:ZVSX:3ZPJ:7QKF:G3P5:L5V4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  [127.0.0.0/8](http://127.0.0.0/8)
 Live Restore Enabled: false`

**Comment by yunus-qureshi** [comment]
yes, check the available space in /var/lib/docker

df -kh /var/lib/docker

**Comment by Rohittingare** [comment]
> df -kh /var/lib/docker

38GB Available

**Comment by Rohittingare** [comment]
@yunus-qureshi  is this sufficient space? Ideally, how much space it required?

**Comment by Rohittingare** [comment]
@yunus-qureshi  is this sufficient space? Ideally, how much space it required?

**Comment by Rohittingare** [comment]
@yunus-qureshi @abhisbyk Do you guys have any solution or clue on this?

**Comment by yunus-qureshi** [comment]
Can you check if curl is able to download it completely

docker run -it busybox sh -c 'curl -vLO https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm'

**Comment by Rohittingare** [comment]
@yunus-qureshi its also checked.....same issue

**Comment by yunus-qureshi** [comment]
In one of your previous comments you mentioned that you downloaded the file successfully on the host VM. How did that work?

**Comment by Rohittingare** [comment]
@yunus-qureshi I entered that link in google chrome and it started downloading file directly

**Comment by Rohittingare** [comment]
i got .rpm package from that download

**Comment by yunus-qureshi** [comment]
You could try updating the Dockerfile and use the COPY instruction to get the rpm into the build container instead of wget

**Comment by Rohittingare** [comment]
@yunus-qureshi Thanks for help. I am able to install oracle image on docker successfully. As you told before, there might be some issues with my network which I really don't understand precisely. because I don't have proxy and any firewall to block any site or URL. But when I switched to my mobile network It worked fine and installed successfully.

I really don't know what was the issue with my router, but at last, it's resolved, when I switched to mobile network.

Thanks.

**Comment by vivek-nagre** [comment]
Hi, guys I am trying to build an Oracle DB image on Docker but getting the following error please let me know if any solution.

Cannot open: https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm. Skipping.
Error: Nothing to do
Removing intermediate container ed6d94577207
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     cd $INSTALL_DIR &&     yum -y install expect openssl oracle-database-preinstall-18c &&     sed -i -e 's/\(oracle\s\+hard\s\+nofile\)/# \1/' /etc/security/limits.d/oracle-database-preinstall-18c.conf &&     unbuffer yum -y install $INSTALL_FILE_1 &&     yum -y remove expect &&     rm -rf /var/cache/yum &&     rm -rf /var/tmp/yum-* &&     mkdir -p $ORACLE_BASE/scripts/setup &&     mkdir $ORACLE_BASE/scripts/startup &&     ln -s $ORACLE_BASE/scripts /docker-entrypoint-initdb.d &&     mkdir -p $ORACLE_BASE/oradata /home/oracle &&     chown -R oracle:oinstall $ORACLE_BASE /home/oracle &&     mv $INSTALL_DIR/$RUN_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$PWD_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$CHECK_DB_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$CONF_FILE /etc/sysconfig/ &&     ln -s $ORACLE_BASE/$PWD_FILE / &&     cd $HOME &&     rm -rf $INSTALL_DIR &&     chmod ug+x $ORACLE_BASE/*.sh' returned a non-zero code: 1

**Comment by vivek-nagre** [comment]
> for both commands mine and yours, process stalled after 85%. Please take a look. Its not network issue. I tried many times. issue occures at same location means after 85% completion. ![image](https://user-images.githubusercontent.com/52101615/188879435-832e20f5-9320-4979-a9c2-2f4a77ff21e2.png)


Hi I am facing same issue

**Comment by vivek-nagre** [comment]
Hi Following are the Output for the command 

$ **docker info**
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 16
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.27GiB
 Name: docker-desktop
 ID: 2LM2:QM5T:UDSD:Y2FU:F2SX:4BJH:DGF7:4CQR:3JZC:HLGN:ATNC:5FCQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

$ **docker system df**
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          7         3         220.9MB   138.2MB (62%)
Containers      4         0         2.361GB   2.361GB (100%)
Local Volumes   0         0         0B        0B
Build Cache     39        0         8.573GB   8.573GB

And if I try to increase the size from the step you mention I am getting error as follow 
You are using the WSL 2 backend, so resource limits are managed by Windows.

**Comment by oraclesean** [comment]
I suspect this is a space issue and not the network or a script bug. Docker stores its assets (images, containers, volumes, cache) in a protected directory on Linux systems, `/var/lib/docker`. What's the output of:
```
df -hP /var/lib/docker
```
The Oracle 18.4 image is 5.9GB:
```
# docker images
REPOSITORY                                    TAG           IMAGE ID       CREATED        SIZE
oracle/database                               18.4.0-xe     391309d85fcf   17 hours ago   5.9GB
```
To successfully build the image, you'll need at least ~6GB for the image and (probably, depending on how it builds) another 2.5GB to save the downloaded RPM into the build context. And, of course, once built, running the database as a container uses additional storage—about 4GB:
```
NAMES     SIZE                      STATUS
ORA18XE   3.8GB (virtual 9.69GB)    Up 14 minutes (healthy)
```

If the available free space reported by the `df` command above is small (less than 8-9GB), it explains why the image build fails. The output from `docker system df` shows that most of the space Docker uses on your system is build cache (8.5GB). You can safely reclaim that by running:
```
docker builder prune
```
This won't affect any existing containers or images; build cache is there to improve the performance of builds by caching layers—elements of an image—so other images that might reuse them don't have to re-run the step.

There are four stopped containers using 2.3G. Removing them would free up additional space if they're no longer needed.

**Comment by vivek-nagre** [comment]
Again same issue 
$ df -hP /mnt/wsl/docker-desktop
df: /mnt/wsl/docker-desktop: No such file or directory

**Comment by oraclesean** [comment]
Please run the correct command, including the trailing asterisk and `sudo`:
```
sudo df -hP /mnt/wsl/docker-desktop*
```
