### ISSUE TITLE
build docker-oracle by xe error sysctl 

### ISSUE THREAD

**Issue by lawmillion** [oracle/docker-images#245]
Error 
sysctl: setting key "fs.file-max": Read-only file system
sysctl: setting key "fs.file-max": Read-only file system
error: oracle-xe-11.2.0-1.0.x86_64: install failed

**Comment by gvenzl** [comment]
Those errors are epxected but should bring the build to fail. Please provide the entire build log.

**Comment by brunoborges** [comment]
Closed due to lack of more information.
