### ISSUE TITLE
[Building k8s extensions for database SingleInstance] -u option is throwing an unknown option error

### ISSUE THREAD

**Issue by mfabbri** [oracle/docker-images#2456]
Hi all, 

building the k8s extensions for the single database image, I found an issue.
The unknown option error was thrown by the 

/usr/bin/python -u

in

https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/extensions/k8s/lock.py#L1

By removing the -u, I was able to fix the issue.

Thanks

**Comment by abhisbyk** [comment]
@mfabbri For which database version have you tried building k8s extension ??

**Comment by mfabbri** [comment]
Hi @abhisbyk: 19.3 Enterprise Edition

**Comment by zsrv** [comment]
This happened to me when I cloned the docker-images git repository on a Windows machine and the line endings on some files, including lock.py, were changed to CRLF. Executing this before cloning fixed the problem:

`git config --global core.autocrlf false`

**Comment by mfabbri** [comment]
Thank you @zsrv ! This tip fixed the issue!
