### ISSUE TITLE
ORACLE DATABASE Single Instance: cannot run a container with a customized character set in Oracle XE

### ISSUE THREAD

**Issue by proietti-francesco** [oracle/docker-images#2463]
cannot run a customized container character set in Oracle XE official version. In fact, I can see in createDB.sh file the following variable substitution:
`  su -c 'sed -i -e "s|###ORACLE_CHARACTERSET###|$ORACLE_CHARACTERSET|g" /etc/sysconfig/"$CONF_FILE"'
`
but in the conf_file for XE (oracle-xe-21c.conf as provided in Dockerfile.xe) there isn't the "###ORACLE_CHARACTERSET###" pattern. Instead there are only these two rows:
```
# Character set of the database
CHARSET=AL32UTF8
```

So, I suppose eather the createDB.sh file or the oracle-xe-21c.conf file should be fixed according to each other.

After doing so, I guess one can run a db with a customized character by setting this env variable -e ORACLE_CHARACTERSET=<some_encoding> in the docker run/podman run command.

**Comment by abhisbyk** [comment]
@proietti-francesco The `oracle-xe-21c.conf` file has `###ORACLE_CHARACTERSET###` pattern. Please see the following link:
[https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/dockerfiles/21.3.0/oracle-xe-21c.conf](https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/dockerfiles/21.3.0/oracle-xe-21c.conf)

After building 21c XE image from this repo, you can customise the character set with the way you mentioned above.

**Comment by abhisbyk** [comment]
Can you please try this and let me know if this resolves the issue ?

**Comment by proietti-francesco** [comment]
Hi @abhisbyk,
Thank you for your reply.
I'm using an image pulled directly from https://container-registry.oracle.com/. I thought it was the same image as if I build it from this repo. Now, I'm following the procedure in this repo to build the linux image provided by Oracle (https://www.oracle.com/database/technologies/xe-downloads.html) and will let you know if it works.

I did a bit of confusion. Sorry for wasting your time.

If I could ask, what's the difference between an image built within this project and the one in the oracle container registry (container-registry.oracle.com/database/express:21.3.0-xe) ?

**Comment by proietti-francesco** [comment]
Hi @abhisbyk , thanks for your explanation.
I've tried to build the image from this repo and it works as expected.

However, I would like to highlight that in the description of the express image in https://container-registry.oracle.com/ website it is explicited stated that the supported parameters are:
**ORACLE_PWD**: This parameter modifies the password for the SYS, SYSTEM and PDBADMIN users. This parameter is optional, and the default value is randomly generated. Note: If you use this option, then the password will be visible as a container environment variable, and cannot be changed later on.
**ORACLE_CHARACTERSET**: This parameter modifies the character set of the database. This parameter is optional, and the default value is set to AL32UTF8. Please Note that, this parameter will set the character set only when a new database is created i.e. a host system directory is mounted using -v option while running the image (Please refer to Mounting Docker volume/host directory for database persistence section). **Which is my case** so I guess it should work also with the prebuilt image in this repo. Am I wrong?

**Comment by IshaanDesai45** [comment]
@proietti-francesco 
You can modify the character set of the "container-registry.oracle.com/database/express:21.3.0-xe" found on the oracle container registry only if you mount a volume to the database container using this image with "-v" flag 
So the command be 
```
docker run --name <container name> \
-p <host port>:1521 -p <host port>:5500 \
-e ORACLE_PWD=<your database passwords> \
-e ORACLE_CHARACTERSET=<your character set> \
-v [<host mount point>:]/opt/oracle/oradata \
container-registry.oracle.com/database/express:21.3.0-xe
```

Here we mount a volume and also modify the character set

**Comment by mattiuusitalo** [comment]
It doesn't work though. After initializing the database I can see from `SELECT * FROM nls_database_parameters;` that the database characterset is still the default.
