### ISSUE TITLE
Error building container image with ./buildContainerImage - [MacOS][oracle/database:12.1.0.2-ee]

### ISSUE THREAD

**Issue by ElaineYxp** [oracle/docker-images#2479]
Hi,

I'm trying to build a docker container image for Oracle 12.1.0.2 with `sh buildContainerImage.sh -v 12.1.0.2 -e` command but keep hit the error which interrupts the installation, attached with the complete log display in terminal.
[20220930 Build Container Image.log](https://github.com/oracle/docker-images/files/9682730/20220930.Build.Container.Image.log)

Appreciate if anyone can help to solve the issue. 
I'm using Macbook Pro which running macOS Monterey with Apple M2 chip.

**Comment by Kubiac** [comment]
I'm having the same error with Oracle version 19.3.0.

**Comment by yunus-qureshi** [comment]
Apple M1/M2 chip is not supported yet. Definitely not for 12.1.0.2.  

https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/FAQ.md#can-i-run-oracle-database-containers-on-apple-m1-arm-devices
