### ISSUE TITLE
Orale Database Image Not building from master

### ISSUE THREAD

**Issue by ashishWaghmare** [oracle/docker-images#248]
Removing intermediate container 8662d647e7f5
Step 11 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in ab1fe5200423
/bin/sh: _**/opt/oracle/oraInventory/orainstRoot.sh: No such file or directory**_
Removing intermediate container ab1fe5200423
The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR' returned a non-zero code: 127
There was an error building the image.

**Comment by gvenzl** [comment]
Can you please provide the output of the entire build log? Thanks!

**Comment by ashishWaghmare** [comment]
Skipping installation of utils/xsubpp man page.
Skipping installation of x2p/a2p.pod man page.
Skipping installation of x2p/find2perl man page.
Skipping installation of x2p/s2p man page.
[0mmake[1]: Leaving directory `/opt/oracle/install/perl-5.14.1'
[91mcp: cannot stat '../perl.old/lib/': No such file or directory
[0m[91mcp: cannot stat '../perl.old/man/': No such file or directory
[0m[91mcp: cannot stat '../perl.old/bin/dbilogstrip': No such file or directory
[0m[91mcp: cannot stat '../perl.old/bin/dbiprof': No such file or directory
[0m[91mcp: cannot stat '../perl.old/bin/dbiproxy': No such file or directory
[0m[91mcp: cannot stat '../perl.old/bin/ora_explain': No such file or directory
[0m[91m/opt/oracle/install/installPerl.sh: line 34: cd: /opt/oracle/product/12.1.0.2/dbhome_1/lib: No such file or directory
[0m[91m/opt/oracle/install/installPerl.sh: line 38: cd: /opt/oracle/product/12.1.0.2/dbhome_1/bin: No such file or directory
[0m[91m/opt/oracle/install/installPerl.sh: line 39: relink: command not found
[0m ---> e345dc2dd177
Removing intermediate container 95c866a35ce0
Step 10 : USER root
 ---> Running in e37bafc062cd
 ---> 5aa4b39b3d2a
Removing intermediate container e37bafc062cd
Step 11 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in b101b428e421
[91m/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
[0mRemoving intermediate container b101b428e421
There was an error building the image.

**Comment by gvenzl** [comment]
The **entire** build log please. I believe that the root cause is further above during the build process.

**Comment by ashishWaghmare** [comment]
Fixed issue by raising dm.basesize from 10G to 20G. Default 10G is easily exhausted with new updates
Original Disk Space
`/dev/mapper/docker-202:3-6292050-ae5dd53b9a8ed0232f04ef48a34632947f74e1714cc611d510ed540f2b7fc294   10G  3.2G  6.9G  32% /`
 
```
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-01-05_10-01-29AM. Please wait .[FATAL] [INS-32021] Insufficient disk space on this volume for the selected Oracle home.
   CAUSE: The selected Oracle home was on a volume without enough disk space.
   ACTION: Choose a location for Oracle home that has enough space (minimum of **6,553MB**) or free up space on the existing volume.
```
