### ISSUE TITLE
Docker DB 19c coming up unhealthy

### ISSUE THREAD

**Issue by jifbrodeur** [oracle/docker-images#2483]
Hi, after issuing the following command: docker  run -d --name ora19c \
--privileged \
--memory=4096M \
-p 1523:1521/tcp -p 5502:5500/tcp \
-e ORACLE_SID=ORCLCDB \
-e ORACLE_PDB=ORCLPDB \
-e ORACLE_PWD=WElcome12345## \
-e INIT_SGA_SIZE=2048M \
-e INIT_PGA_SIZE=500MB \
-e ORACLE_EDITION=EE \
-e ORACLE_CHARACTERSET=AL32UTF8 \
-e ENABLE_ARCHIVELOG=true \
-v /Users/jifbrodeur/dock_image:/opt/oracle/oradata \
container-registry.oracle.com/database/enterprise:19.3.0.0

Looking at my logs after a long time, I get the following:
docker logs ora19c
[2022:10:04 20:03:36]: Acquiring lock .ORCLCDB.create_lck with heartbeat 30 secs
[2022:10:04 20:03:36]: Lock acquired
[2022:10:04 20:03:36]: Starting heartbeat
[2022:10:04 20:03:36]: Lock held .ORCLCDB.create_lck
Relinking oracle binary for edition: EE
make -f /opt/oracle/product/19c/dbhome_1/rdbms/lib/ins_rdbms.mk edition_ee ioracle
make: *** No rule to make target `edition_ee'.  Stop.
ORACLE EDITION: EE

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 04-OCT-2022 20:03:37

Copyright (c) 1991, 2019, Oracle.  All rights reserved.

Starting /opt/oracle/product/19c/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 19.0.0.0.0 - Production
System parameter file is /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/e72ac119d42f/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))

STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Start Date                04-OCT-2022 20:03:38
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/e72ac119d42f/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007fee713362a0, pid=56, tid=0x00007fee89aa9700

 JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.201-b09 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 J 3767 C1 com.sun.org.apache.xml.internal.dtm.ref.ExpandedNameTable.getExpandedTypeID(Ljava/lang/String;Ljava/lang/String;IZ)I (272 bytes) @ 0x00007fee713362a0 [0x00007fee71336280+0x20]

 Core dump written. Default location: /home/oracle/core or core.56

 An error report file with more information is saved as:
 /home/oracle/hs_err_pid56.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

/opt/oracle/createDB.sh: line 189:    56 Aborted                 (core dumped) dbca -silent -createDatabase -enableArchive "$ENABLE_ARCHIVELOG" -archiveLogDest "$ARCHIVELOG_DIR" ${DBCA_CRED_OPTIONS} -responseFile "$ORACLE_BASE"/dbca.rsp
cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB.log: No such file or directory

It seems that the database creating assistant is failing.
Thanks for the help
Jean-François

**Comment by jifbrodeur** [comment]
Same issue with 21c but DOES NOT occur with 12c

**Comment by yunus-qureshi** [comment]
I guess you are passing the wrong string to ORACLE_EDITION. It should be enterprise and not EE or just don't pass it as enterprise is the default

**Comment by jifbrodeur** [comment]
Thanks for the follow up but in running the container for the 21c I passed it the default command indicated on Oracle registry web site container-registry.oracle.com, which is docker run -d --name <oracle-db>
container-registry.oracle.com/database/enterprise:21.3.0.0 replacing <oracle-db> by ora21c and it still come up unhealthy but the logs stopped after the listener, I might not have waited long enough. I am re-trying the creation of the 19c db container without the ORACLE_EDITION parameter and I will keep you posted. Thanks for your prompt reply.

**Comment by jifbrodeur** [comment]
Hi, I redid everything using a much simpler run command:

run -d --name ora19c \
--privileged \
--memory=6144m \
-p 1523:1521/tcp -p 5502:5500/tcp \
-e ORACLE_SID=ORCLCDB \
-e ORACLE_PDB=ORCLPDB \
-e ORACLE_PWD=oracle \
-e ORACLE_CHARACTERSET=AL32UTF8 \
-v /Users/jifbrodeur/dock_image:/opt/oracle/oradata \
container-registry.oracle.com/database/enterprise:19.3.0.0

> docker logs ora19c
[2022:10:07 13:25:22]: Acquiring lock .ORCLCDB.create_lck with heartbeat 30 secs
[2022:10:07 13:25:22]: Lock acquired
[2022:10:07 13:25:22]: Starting heartbeat
[2022:10:07 13:25:22]: Lock held .ORCLCDB.create_lck
ORACLE EDITION: ENTERPRISE

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 07-OCT-2022 13:25:22

Copyright (c) 1991, 2019, Oracle.  All rights reserved.

Starting /opt/oracle/product/19c/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 19.0.0.0.0 - Production
System parameter file is /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/bb84d6bff311/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Start Date                07-OCT-2022 13:25:23
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/bb84d6bff311/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb871621320, pid=54, tid=0x00007fb886be6700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.201-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 1751 C1 oracle.xml.parser.v2.XMLOutputStream.writeChars(Ljava/lang/String;)V (189 bytes) @ 0x00007fb871621320 [0x00007fb871621360+0xffffffc0]
#
# Core dump written. Default location: /home/oracle/core or core.54
#
# An error report file with more information is saved as:
# /home/oracle/hs_err_pid54.log
Compiled method (c1) 1279918 1751       3       oracle.xml.parser.v2.XMLOutputStream::writeChars (189 bytes)
 total in heap  [0x00007fb871620fd0,0x00007fb871624080] = 12464
 relocation     [0x00007fb8716210f8,0x00007fb871621360] = 616
 main code      [0x00007fb871621360,0x00007fb871622da0] = 6720
 stub code      [0x00007fb871622da0,0x00007fb871622f28] = 392
 oops           [0x00007fb871622f28,0x00007fb871622f30] = 8
 metadata       [0x00007fb871622f30,0x00007fb871622f58] = 40
 scopes data    [0x00007fb871622f58,0x00007fb871623a88] = 2864
 scopes pcs     [0x00007fb871623a88,0x00007fb871623fc8] = 1344
 dependencies   [0x00007fb871623fc8,0x00007fb871623fd0] = 8
 nul chk table  [0x00007fb871623fd0,0x00007fb871624080] = 176
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
/opt/oracle/createDB.sh: line 189:    54 Aborted                 (core dumped) dbca -silent -createDatabase -enableArchive "$ENABLE_ARCHIVELOG" -archiveLogDest "$ARCHIVELOG_DIR" ${DBCA_CRED_OPTIONS} -responseFile "$ORACLE_BASE"/dbca.rsp
cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB.log: No such file or directory

From what I can read dbca is failing and it seems to point to a Java error:
 SIGSEGV (0xb) at pc=0x00007fb871621320, pid=54, tid=0x00007fb886be6700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09)
Any idea what I could try to help pin down the issue?
Thanks
Jean-François

**Comment by yunus-qureshi** [comment]
Can you retry without the --memory option

**Comment by jifbrodeur** [comment]
Hi, still no luck, Thanks for your help. 
command: docker run -d --name ora19c \                                                                                                              ok  08:58:09
--privileged \
-p 1523:1521/tcp -p 5502:5500/tcp \
-e ORACLE_SID=ORCLCDB \
-e ORACLE_PDB=ORCLPDB \
-e ORACLE_PWD=oracle \
-e ORACLE_CHARACTERSET=AL32UTF8 \
-v /Users/jifbrodeur/dock_image:/opt/oracle/oradata \
container-registry.oracle.com/database/enterprise:19.3.0.0

> docker logs ora19c
[2022:10:08 11:58:46]: Acquiring lock .ORCLCDB.create_lck with heartbeat 30 secs
[2022:10:08 11:58:46]: Lock acquired
[2022:10:08 11:58:46]: Starting heartbeat
[2022:10:08 11:58:46]: Lock held .ORCLCDB.create_lck
ORACLE EDITION: ENTERPRISE

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 08-OCT-2022 11:58:47

Copyright (c) 1991, 2019, Oracle.  All rights reserved.

Starting /opt/oracle/product/19c/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 19.0.0.0.0 - Production
System parameter file is /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/1c660c9ba148/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Start Date                08-OCT-2022 11:58:47
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/1c660c9ba148/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully

 A fatal error has been detected by the Java Runtime Environment:

  SIGILL (0x4) at pc=0x00007ff2193e4c1d, pid=52, tid=0x00007ff231cba700

 JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.201-b09 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 J 2963 C1 com.sun.org.apache.xerces.internal.impl.xs.XSElementDecl.hashCode()I (30 bytes) @ 0x00007ff2193e4c1d [0x00007ff2193e4bc0+0x5d]
Core dump written. Default location: /home/oracle/core or core.52
 An error report file with more information is saved as:
 /home/oracle/hs_err_pid52.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

/opt/oracle/createDB.sh: line 189:    52 Aborted                 (core dumped) dbca -silent -createDatabase -enableArchive "$ENABLE_ARCHIVELOG" -archiveLogDest "$ARCHIVELOG_DIR" ${DBCA_CRED_OPTIONS} -responseFile "$ORACLE_BASE"/dbca.rsp
cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB.log: No such file or directory

**Comment by aditya059** [comment]
Hi @jifbrodeur

Please retry without --privileged option. (Not recommended to use). Did you set appropriate permissions for the "/Users/jifbrodeur/dock_image" (used with -v flag) before running the docker run command?

I tried the following (1) on OL8 and (2) on Ubuntu. I didn't got any error (database is healthy): 

1. podman run -d --name ora19c -p 1523:1521/tcp -p 5502:5500/tcp -e ORACLE_SID=ORCLCDB -e ORACLE_PDB=ORCLPDB -e ORACLE_PWD=WElcome12345## -e INIT_SGA_SIZE=2048M -e INIT_PGA_SIZE=500MB -e ORACLE_EDITION=enterprise -e ORACLE_CHARACTERSET=AL32UTF8 -e ENABLE_ARCHIVELOG=true -v /scratch/aditya/dock_image:/opt/oracle/oradata container-registry.oracle.com/database/enterprise:19.3.0.0 

2. docker run -d --name ora19c --memory=4096M -p 1523:1521/tcp -p 5502:5500/tcp -e ORACLE_SID=ORCLCDB -e ORACLE_PDB=ORCLPDB -e ORACLE_PWD=WElcome12345## -e INIT_SGA_SIZE=2048M -e INIT_PGA_SIZE=500MB -e ORACLE_EDITION=enterprise -e ORACLE_CHARACTERSET=AL32UTF8 -e ENABLE_ARCHIVELOG=true -v /home/aditya/dock_image:/opt/oracle/oradata container-registry.oracle.com/database/enterprise:19.3.0.0
