### ISSUE TITLE
No package oracle-instantclient-release-el7 available.

### ISSUE THREAD

**Issue by ddm1315** [oracle/docker-images#2497]
I am pretty new to docker and oracle and I am trying to set up a docker for an application that connects to an oracle database. Here is what my docker-compose.yml file looks like:

```
version: '3'
services:
  app:
    build: app
    ports:
    - 8080:8080
    environment:
      NODE_ENV: local
```

This file connects to this Dockerfile within my app subdirectory:

```
FROM oraclelinux:7-slim

RUN  yum -y install oracle-nodejs-release-el7 && \
     yum -y install nodejs && \
     rm -rf /var/cache/yum

RUN yum -y install oracle-instantclient-release-el7 && \
    yum -y install oracle-instantclient-basic && \
    rm -rf /var/cache/yum

WORKDIR /usr/app

COPY package*.json tsconfig*.json .eslintrc.js ./
COPY src ./src/

RUN npm ci --ignore-scripts

RUN npm run build
RUN npm prune --production
RUN npm install

ENV NODE_ENV='dev'
USER root
EXPOSE 8080
CMD [ "node", "dist/index.js" ]
```

I am trying to run docker-compose up --build to set up the project however it keeps failing when running `yum -y install oracle-instantclient-release-el7` telling me that `No package oracle-instantclient-release-el7 available.` I have tried adding commands to remove any pre-existing installs for oracle-instantclient-release-el7 but nothing has changed. I am using a Mac with an Apple M1 Pro chip. I have read that oracle doesn't support for Apple processors, if this is the issue, are there any workarounds?

**Comment by Djelibeybi** [comment]
You need to add `platform: "linux/amd64"` to your `docker-compose.yml` file.

**Comment by Djelibeybi** [comment]
Alternatively, you can use the older release of the Instant Client which is available for Arm by installing the `oracle-release-el7` package instead.

**Comment by cjbj** [comment]
Using `oracle-release-el7` will give you 19c Instant Client packages which had a different name format so the second install command would need to be `yum -y install oracle-instantclient19.10-basic` (at time of writing).  The page to bookmark is https://yum.oracle.com/oracle-instant-client.html

**Comment by ddm1315** [comment]
Adding the platform fixed the yum install issue. Thanks!
