### ISSUE TITLE
DB 19.3c - How to change listener port?

### ISSUE THREAD

**Issue by julwin** [oracle/docker-images#2503]
Hey everyone,

I'm currently in a situation where we need to use a different port than 1521 *inside* the docker container (btw we use the flag `--network host` in the docker run command).

I tried to change the port in listener.ora and tnsnames.ora, but couldn't get it to work. 

One of the errors I saw was:
ORA-12514, TNS: listener does not currently know of service requested in connect descriptor

Is there a way to configure the changed DB listener port?

**Comment by toondaey** [comment]
+1
Please help with this because I'm at the point of pulling my hair out

**Comment by oraclesean** [comment]
* Navigate to `$ORACLE_HOME/network/admin`.
* Edit the `listener.ora` and `tnsnames.ora` files, changing the port from 1521 to the desired port.
* At the command line, issue: `$ORACLE_HOME/bin/lsnrctl stop` followed by `$ORACLE_HOME/bin/lsnrctl start`
* Verify the port with: `$ORACLE_HOME/bin/lsnrctl status`

```
[oracle - ECO11] /u01/app/oracle/product/19c/dbhome_1/network/admin
# lsnrctl status

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 16-NOV-2022 17:22:39

Copyright (c) 1991, 2022, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
<snip>
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))          <<<<<< 1521
<snip>
```
After changing `listener.ora` and stop/start:
```
# lsnrctl start

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 16-NOV-2022 17:23:18

Copyright (c) 1991, 2022, Oracle.  All rights reserved.

Starting /u01/app/oracle/product/19c/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 19.0.0.0.0 - Production
System parameter file is /u01/app/oracle/product/19c/dbhome_1/network/admin/listener.ora
Log messages written to /u01/app/oracle/diag/tnslsnr/cdbada74d484/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1522)))          <<<<<< 1522

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
Start Date                16-NOV-2022 17:23:18
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /u01/app/oracle/product/19c/dbhome_1/network/admin/listener.ora
Listener Log File         /u01/app/oracle/diag/tnslsnr/cdbada74d484/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1522)))          <<<<<< 1522
Services Summary...
Service "ECO11" has 1 instance(s).
  Instance "ECO11", status UNKNOWN, has 1 handler(s) for this service...
The command completed successfully
```
TNS configuration:
```
# cat tnsnames.ora
ECO11 =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1522))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = ECO11)
    )
  )

LISTENER_ECO11 =
  (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1522))
```
Verify the connection with `$ORACLE_HOME/bin/tnsping`:
```
# tnsping ECO11

TNS Ping Utility for Linux: Version 19.0.0.0.0 - Production on 16-NOV-2022 17:28:10

Copyright (c) 1997, 2022, Oracle.  All rights reserved.

Used parameter files:
/u01/app/oracle/product/19c/dbhome_1/network/admin/sqlnet.ora


Used TNSNAMES adapter to resolve the alias
Attempting to contact (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1522)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = ECO11)))
OK (0 msec)
```
The endpoint is now registered at 1522.

If you ran `docker run` with `-p XXXX:1521` the new port isn't exposed from the container. You'll have to recreate it. If the `/opt/oracle/oradata` directory wasn't mapped to a container volume or local directory on the host (with `-v` or `--mount`), recreating the container removes its data and configuration.

To force these changes in all new containers created from an image, edit `.../docker-images/OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh` and change references to 1521 to the new port, then re-run the `buildContainerImage.sh` script to create a new image with the changes.

You could also add a script to the `docker-entrypoint/setup` directory that makes these one-time changes in the container following database creation. (Scripts in `startup` run every time the container starts.)

**Comment by toondaey** [comment]
Thanks for the feedback. I just tried this but didn't work.

**Comment by julwin** [comment]
> * Navigate to `$ORACLE_HOME/network/admin`.
> * Edit the `listener.ora` and `tnsnames.ora` files, changing the port from 1521 to the desired port.
> * At the command line, issue: `$ORACLE_HOME/bin/lsnrctl stop` followed by `$ORACLE_HOME/bin/lsnrctl start`
> * Verify the port with: `$ORACLE_HOME/bin/lsnrctl status`
> 
> ```
> [oracle - ECO11] /u01/app/oracle/product/19c/dbhome_1/network/admin
> # lsnrctl status
> 
> LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 16-NOV-2022 17:22:39
> 
> Copyright (c) 1991, 2022, Oracle.  All rights reserved.
> 
> Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
> STATUS of the LISTENER
> ------------------------
> <snip>
>   (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
>   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))          <<<<<< 1521
> <snip>
> ```
> 
> After changing `listener.ora` and stop/start:
> 
> ```
> # lsnrctl start
> 
> LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 16-NOV-2022 17:23:18
> 
> Copyright (c) 1991, 2022, Oracle.  All rights reserved.
> 
> Starting /u01/app/oracle/product/19c/dbhome_1/bin/tnslsnr: please wait...
> 
> TNSLSNR for Linux: Version 19.0.0.0.0 - Production
> System parameter file is /u01/app/oracle/product/19c/dbhome_1/network/admin/listener.ora
> Log messages written to /u01/app/oracle/diag/tnslsnr/cdbada74d484/listener/alert/log.xml
> Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
> Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1522)))          <<<<<< 1522
> 
> Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
> STATUS of the LISTENER
> ------------------------
> Alias                     LISTENER
> Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
> Start Date                16-NOV-2022 17:23:18
> Uptime                    0 days 0 hr. 0 min. 0 sec
> Trace Level               off
> Security                  ON: Local OS Authentication
> SNMP                      OFF
> Listener Parameter File   /u01/app/oracle/product/19c/dbhome_1/network/admin/listener.ora
> Listener Log File         /u01/app/oracle/diag/tnslsnr/cdbada74d484/listener/alert/log.xml
> Listening Endpoints Summary...
>   (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
>   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1522)))          <<<<<< 1522
> Services Summary...
> Service "ECO11" has 1 instance(s).
>   Instance "ECO11", status UNKNOWN, has 1 handler(s) for this service...
> The command completed successfully
> ```
> 
> TNS configuration:
> 
> ```
> # cat tnsnames.ora
> ECO11 =
>   (DESCRIPTION =
>     (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1522))
>     (CONNECT_DATA =
>       (SERVER = DEDICATED)
>       (SERVICE_NAME = ECO11)
>     )
>   )
> 
> LISTENER_ECO11 =
>   (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1522))
> ```
> 
> Verify the connection with `$ORACLE_HOME/bin/tnsping`:
> 
> ```
> # tnsping ECO11
> 
> TNS Ping Utility for Linux: Version 19.0.0.0.0 - Production on 16-NOV-2022 17:28:10
> 
> Copyright (c) 1997, 2022, Oracle.  All rights reserved.
> 
> Used parameter files:
> /u01/app/oracle/product/19c/dbhome_1/network/admin/sqlnet.ora
> 
> 
> Used TNSNAMES adapter to resolve the alias
> Attempting to contact (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1522)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = ECO11)))
> OK (0 msec)
> ```
> 
> The endpoint is now registered at 1522.
> 
> If you ran `docker run` with `-p XXXX:1521` the new port isn't exposed from the container. You'll have to recreate it. If the `/opt/oracle/oradata` directory wasn't mapped to a container volume or local directory on the host (with `-v` or `--mount`), recreating the container removes its data and configuration.
> 
> To force these changes in all new containers created from an image, edit `.../docker-images/OracleDatabase/SingleInstance/dockerfiles/19.3.0/createDB.sh` and change references to 1521 to the new port, then re-run the `buildContainerImage.sh` script to create a new image with the changes.
> 
> You could also add a script to the `docker-entrypoint/setup` directory that makes these one-time changes in the container following database creation. (Scripts in `startup` run every time the container starts.)

This worked for us, although being a bit too complex for my liking - this should be configured by setting an environment variable at container startup, in my opinion. 

Thanks for the help, anyways!
