### ISSUE TITLE
Oracle Linux update/latest repos

### ISSUE THREAD

**Issue by hynd** [oracle/docker-images#251]
Hello!

I've been using the wonderful oraclelinux Docker images (thanks!) for building some packages.  

In some cases, i pick a specific update version (say, oraclelinux:6.7).  It looks like the rootfs is created from a "ol6_latest/$releasever" repo, and the Yum repos are then configured with "latest" enabled.  That's been OK in most cases, and i can usually just switch the enabled repos to avoid pulling in newer packages (or upgrading the whole container to latest:
```
[root@oraclelinux:6.7 /]# yum list --disablerepo=public_ol6_latest --enablerepo=public_ol6_u7_base libuuid*
Installed Packages
libuuid.x86_64                   2.17.2-12.18.0.1.el6       @ol6_latest/$releasever
Available Packages
libuuid.i686                     2.17.2-12.18.0.1.el6       public_ol6_u7_base
libuuid-devel.i686               2.17.2-12.18.0.1.el6       public_ol6_u7_base
libuuid-devel.x86_64             2.17.2-12.18.0.1.el6       public_ol6_u7_base
```

Though in a couple of cases, the update release image has already pulled in a couple of newer packages than are available in the specific update repo, which means some downgrade hoop jumping, ie;
```
[root@oraclelinux:6.8 /]# yum list --disablerepo=public_ol6_latest --enablerepo=public_ol6_u8_base libuuid*
Installed Packages
libuuid.x86_64                   2.17.2-12.24.0.1.el6_8.1     @ol6_latest/$releasever
Available Packages
libuuid.i686                     2.17.2-12.24.0.1.el6         public_ol6_u8_base
libuuid-devel.i686               2.17.2-12.24.0.1.el6         public_ol6_u8_base
libuuid-devel.x86_64             2.17.2-12.24.0.1.el6         public_ol6_u8_base
```

How are the update release images (ie; `6.6`) associated with repos?  (maybe from "latest" at the point in time the oraclelinux-6.X.tar.xz rootfs is created?)

**Comment by Djelibeybi** [comment]
The images were created (and updated) at particular points in time, they're not base 6.x images. That means, the 6.7 image was kept up-to-date for the duration of the 6.7 lifetime and includes updated packages. Once 6.8 was released, the 6.7 image stopped being updated.

Likewise, we continually update the current (`6, 6.8, latest`) image with CVEs, so it's kept as up-to-date and secure as possible.

Every image only has a single repo enabled, which is `ol6_latest`.
