### ISSUE TITLE
Build fails when using Podman

### ISSUE THREAD

**Issue by UNiXMIT** [oracle/docker-images#2515]
I am getting an error after executing './buildContainerImage.sh -v 21.3.0 -x'

Here are the steps I took and the error:

`git clone https://github.com/oracle/docker-images.git
cd docker-images/OracleDatabase/SingleInstance/dockerfiles
export BUILDAH_FORMAT=docker
export BUILDAH_ISOLATION=chroot
./buildContainerImage.sh -v 21.3.0 -x
...
...
The system has no more ptys.  Ask your system administrator to create more.
    while executing
"spawn -noecho yum -y install https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-21c-1.0-1.ol7.x86_64.rpm"
    ("eval" body line 1)
    invoked from within
"eval [list spawn -noecho] $argv"
    invoked from within
"if {[string compare [lindex $argv 0] "-p"] == 0} {
    # pipeline
    set stty_init "-echo"
    eval [list spawn -noecho] [lrange $argv 1 end]
    clo..."
    (file "/usr/bin/unbuffer" line 13)
subprocess exited with status 1
subprocess exited with status 1
Error: error building at STEP "RUN cd $INSTALL_DIR &&     mkdir -p $ORACLE_BASE &&     mv $RUN_FILE $PWD_FILE $CHECK_DB_FILE $CREATE_DB_FILE $USER_SCRIPTS_FILE $CONFIG_TCPS_FILE $ORACLE_BASE/ &&     chmod ug+x *.sh &&     sync &&     ./$CHECK_SPACE_FILE &&     yum -y install expect &&     ./$SETUP_LINUX_FILE &&     chown -R oracle:oinstall $ORACLE_BASE /home/oracle &&     sed -i -r 's/(^session\s+include\s+system-auth)/# \1/' /etc/pam.d/su &&     unbuffer yum -y install $INSTALL_FILE_1 &&     yum -y remove expect &&     rm -rf /var/cache/yum &&     rm -rf /var/tmp/yum-* &&     mv $CONF_FILE /etc/sysconfig/ &&     cd $HOME &&     rm -rf $INSTALL_DIR &&     $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     echo 'export ORACLE_SID=XE' > .bashrc": exit status 1

ERROR: Oracle Database container image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the build operation.`

**Comment by oraclesean** [comment]
The error:
```
The system has no more ptys. Ask your system administrator to create more.
```
...looks like a system resource issue. What OS/version and version of `podman` are you using?

**Comment by UNiXMIT** [comment]
I am using CentOS Stream 8 and podman version 4.2.0
I recently switched to Podman. It used to work correctly with Docker.
I'm not familiar with the error 'The system has no more ptys.' I'll have to look it up.

**Comment by UNiXMIT** [comment]
Strangely if I build the image as root and run the container using Podman as root then it works fine. I was previously using Docker as root too where it also worked. Wonder why I can't use Podman as a standard user for this. I run other containers using Podman without having to use root.

**Comment by lapecoravolante** [comment]
It seems that the problem is old: https://github.com/containers/buildah/issues/2988

**Comment by UNiXMIT** [comment]
> It seems that the problem is old: https://github.com/containers/buildah/issues/2988

Good find. That's disappointing that it hasn't been touched in 2 years.
