### ISSUE TITLE
Permission denied when running create-domain-script.sh

### ISSUE THREAD

**Issue by SchroederMarcus** [oracle/docker-images#2519]
Hi all,
I trying to deploy Oracle Access Management 12.2.1.4 following this documentation https://oracle.github.io/fmw-kubernetes/oam/ on OCI.
For the shared storage I used File Storage in the same subnet and create PV and PVC without any errors. When I start to create the OAM domains, during the script:
cd $WORKDIR/kubernetes/create-access-domain/domain-home-on-pv
./create-domain.sh -i create-domain-inputs.yaml -o output

I run into the error:
The domain will be created using the script /u01/weblogic/create-domain-script.sh
ERROR: Unable to create folder /u01/oracle/user_projects/domains
mkdir: cannot create directory '/u01/oracle/user_projects/domains': Permission denied

kubectl describe pod <domain_job> -n <domain_namespace>
I can see that the mount is done...
    Mounts:
      /u01/oracle/user_projects from oam-infra-domain-storage-volume (rw)
      /u01/weblogic from create-oam-infra-domain-job-cm-volume (rw) etc.

Any thoughts?

Cheers

**Comment by rjeberhard** [comment]
You should try opening an issue at the GitHub project matching the sample you used: https://github.com/oracle/fmw-kubernetes.

**Comment by SchroederMarcus** [comment]
Thx, I will do!
