### ISSUE TITLE
Docker container not accessible under localhost (127.0.0.1)

### ISSUE THREAD

**Issue by thekk1** [oracle/docker-images#2526]
Deploy Container with:

`docker run -tdi -m 4096m -e INIT_SGA_SIZE=3000 -e INIT_PGA_SIZE=1000 -e ORACLE_PWD=test -e ORACLE_SID=XE -e ORACLE_PDB=PDB -p 1531:1521 --restart unless-stopped --name ora container-registry.oracle.com/database/enterprise:19.3.0.0`

Trying to connect with your preferred DB tool or application to 127.0.0.1:1531 will result in an "-1" message.

Port scan with nmap shows the port open and the service are available:

```
nmap -sV -Pn 127.0.0.1 -p1531
Starting Nmap 7.80 ( https://nmap.org ) at 2022-12-07 14:08 CET
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00010s latency).

PORT     STATE SERVICE    VERSION
1531/tcp open  oracle-tns Oracle TNS listener 1.3.0.0.0 (unauthorized)
```
Only connecting to the docker proxy directly (172.17.0.1) or to the main IP of the Host system is successful.

**Comment by thekk1** [comment]
Uhm... I see the case that is explained in in the linked article but this problem is not the case on my system or on any other system with docker that I have seen in my life.

As I showed above, the port is clearly reachable from the host system and the service type behind is detected by nmap. That means there is no problem to contact the DB service.
The problem here is some of a configuration issue in the docker container itself to not accept logins to the database from a specific IP or over a specific Route or something like that.
As an additional information, I can say that this happens first since oracle v19. The Docker containers with v12 and v18 working perfectly.

**Comment by oraclesean** [comment]
It's helpful to share discrete test cases, show commands, output, and error messages, and list the versions of tools as opposed to "your preferred DB tool." Listing examples of what does and doesn't work aids in narrowing the issue, too. For example, "it happens in 19c but not in earlier versions" is relevant to your described behavior and isn't a bug in the image or Oracle database. If anything, it's in Docker, but this behavior also exists in VirtualBox and other tools/platforms that forward ports. Oracle 19c adds checks and timeouts for out-of-band messages. When the underlying network proxy layer doesn't handle them appropriately, the connection hangs and eventually fails.

For an immediate fix, add the following line, which prevents OOB checks to the `sqlnet.ora` file in `/opt/oracle/oradata/dbconfig/$ORACLE_SID/sqlnet.ora`:
```
DISABLE_OOB=ON
```
With this entry added to `sqlnet.ora`, Instant Client connections on a system running `userland-proxy` succeed.

For a permanent fix, disable `userland-proxy` in Docker.

**Comment by thekk1** [comment]
Both options works for me. Thanks for the quick and professional help.

**Comment by IshaanDesai45** [comment]
#2607 This PR includes the `DISABLE_OOB=ON` workaround which would solve this problem
