### ISSUE TITLE
Error while creating docker instance

### ISSUE THREAD

**Issue by DuraiMuruganEKGit** [oracle/docker-images#2539]
Hi Team,

Trying to create a docker image running the command ./buildContainerImage.sh -v 18.4.0 -t oracledb-xe-test -x -i -o '--platform=linux/x86_64'

That doent create a docker image but give the below image. Same noticed with different versions of the installation. I tried with 18.3.0 and 21.3.0. Both gave the same issue.

#7 125.6   xorg-x11-xauth.x86_64 1:1.0.9-1.el7
#7 125.6   xz.x86_64 0:5.2.2-2.el7_9
#7 125.6
#7 125.6 Complete!
#7 126.1 Loaded plugins: ovl
invalid character 'c' looking for beginning of valueMB/s | 2.0 GB     00:39 ETA

ERROR: Oracle Database container image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the build operation.

**Comment by IshaanDesai45** [comment]
Can you retry with the following command 
`./buildContainerImage.sh -i -x -v 21.3.0`
