### ISSUE TITLE
Weblogic Kubernetes K8s-domain error no match for kind "Deployment" in version "apps/v1beta1" ensure CRDs are installed first

### ISSUE THREAD

**Issue by dbibiamine** [oracle/docker-images#2549]
When running Kubectl create -f k8s/wls-admin.yml
i have this error :
error: resource mapping not found for name: "admin-server" namespace: "" from "k8s/wls-admin.yml": no matches for kind "Deployment" in version "apps/v1beta1"
ensure CRDs are installed first

**Comment by rjeberhard** [comment]
Hi @dbibiamine,

Those samples are 5+ years old and are no longer valid for current versions of Kubernetes.

Instead of these samples, we now have a Kubernetes operator for WebLogic: https://github.com/oracle/weblogic-kubernetes-operator.

**Comment by rjeberhard** [comment]
We have decided to remove the outdated samples. Please consider using the WebLogic Kubernetes Operator.
