### ISSUE TITLE
"SHARED MEMORY DOES NOT EXIST" error after container stop/start

### ISSUE THREAD

**Issue by odedia** [oracle/docker-images#255]
Hi,

I am testing a docker setup with Oracle 12 ee.

I am able to run the initial docker container, connect via bash and then SQLPlus, create a schema, add users, etc. All is well.

Then I am stopping the container (the purpose is to commit the container to a new image with my initial setup).

If I try to run the container again, either with docker start <container> or by deleting the container and running the new image, I fail due to SHARED MEMORY DOES NOT EXIST error when trying to connect with SQLPlus.

I did define a specific volume for data using the -v option.

Any ideas why this is so?

Thanks for the help.

**Comment by gvenzl** [comment]
The error indicates hat your database is not running. Please provide the output of the log once you started the container.

**Comment by davidkarlsen** [comment]
Be sure to provide enough shared memory (eg. SGA space) for the db.
