### ISSUE TITLE
Docker Login for Oracle Cloud Infrastructure is Unauthorized

### ISSUE THREAD

**Issue by berbarroso** [oracle/docker-images#2551]
Greetings!

I'm having an issue logging in on docker for OCI, this is my command:

**docker login syd.ocir.io**

For Username, this is my credentials:

*Username: <tenancy-namespace>/<user-name - email address>`*

For Password, I already tried the following:
•Authorization Token from OCI Console > Profile > Resources > Auth Tokens
•Tried all the three files of Profile Config from **oci session authenticate** command
-
*C:\Users\GemberB\.oci\sessions\GemberTestProfile\oci_api_key.pem*

-
*C:\Users\GemberB\.oci\sessions\GemberTestProfile\oci_api_key_public.pem* 

-
*C:\Users\GemberB\.oci\sessions\GemberTestProfile\token*

All of the passwords that I input have unauthorized issues, I can't connect to OCI and use docker push. These are the errors:

1.)
**denied:Anonymous users are only allowed read access on public repos**

2.)
**denied: Anonymous users are only allowed read access on public repos**

What is the correct password to input? 

Thank you in advance for answering! :)

This is my reference for doing this task:
https://docs.oracle.com/en-us/iaas/developer-tutorials/tutorials/node-on-k8s/01oci-node-k8s-summary.htm#deploy-docker-image

**Comment by Djelibeybi** [comment]
This is not something we can help you with in this repo. You should use the Help option from the OCI Console to get support for OCI and OCIR.

**Comment by berbarroso** [comment]
noted on this, thanks
