### ISSUE TITLE
Docker image for Oracle should be changed to standard oracle latest repo

### ISSUE THREAD

**Issue by nddipiazza** [oracle/docker-images#2557]
when using OracleContainer it's probably better to just use Oracle's standard image: 

`container-registry.oracle.com/database/express:latest`

instead of https://hub.docker.com/r/gvenzl/oracle-xe

https://github.com/testcontainers/testcontainers-java/blob/main/modules/oracle-xe/src/main/java/org/testcontainers/containers/OracleContainer.java#L20 

Then the tag could be "latest" to pull the latest and greatest version without locking people accidentally on an older version. 

This container seems to work with no changes.

**Comment by Djelibeybi** [comment]
Why are you logging this here? It should be logged in the `testcontainers` repo. All of the images here are designed to be built by users not pulled from anywhere.
