### ISSUE TITLE
Everytime I try to run the docker container, it starts installing the oracle db

### ISSUE THREAD

**Issue by e1999b** [oracle/docker-images#2560]
even if i already have the datafiles19c volume, when i try to docker run container it starts to install database from the beginning. How can I run as much as I like containers without having to install oracle database for each container? it is very time consuming if I use this docker file for integration testing purpouses

**Comment by oraclesean** [comment]
By "install," do you mean it's creating a database?

If so, try this:
Create a database container from scratch, using a volume, eg:
```
docker run -d \ 
   --name o193 \
   -e ORACLE_SID=ORCL \
    -p 51521:1521 \
    -v ~/oradata/o193:/opt/oracle/oradata \
    oracle/database:19.3.0-ee
```
Allow it to create the database, then make a copy of the database directory:
```
cp -r ~/oradata/o193 ~/oradata/newdb
```
Create a new container, using the same `ORACLE_SID`. Map the `oradata` directory to the new directory path. You _must_ also change the container name and any mapped ports:
```
docker run -d \
        --name newdb \
        -p 52521:1521 \
        -v ~/oradata/newdb:/opt/oracle/oradata \
        oracle/database:19.3.0-ee
```
When the container starts, it recognizes the existing data directory and its database files. Instead of creating a database, it will start the existing database.

You can achieve the same thing with volumes. There are techniques for copying volumes that involve intermediate containers, but you may find it easier to create the volume as a bind mount:
```
docker volume create --opt type=none --opt o=bind \
                 --opt device=~/oradata/${CONTAINER_NAME}/data \
                 ${CONTAINER_NAME}_data
```
Replace the `-v` line in `docker run` command above with:
```
<snip>
--volume ${CONTAINER_NAME}_data:/opt/oracle/oradata \
<snip>
```
To clone with bind-mounted volumes, create a new volume for the new container, then follow the same procedure to copy the contents of the "old" directory into the new location.

Here's [more information on persistence](https://oraclesean.com/blog/oracle-on-docker-is-now-available) for Oracle databases.

**Comment by ErezaBaftiu-hub** [comment]
thank you, i think that's exactly what I needed. Each time I tried to run a container it kept installing(creating the database) and it's taking very much time in my case when i need a couple containers to run and use the same datafiles.

I will try this method and see if it is useful. Thank you very much for your fast response and your time

**Comment by ErezaBaftiu-hub** [comment]
![error](https://user-images.githubusercontent.com/78739638/217868231-9890526b-574e-4dbe-8acd-c0574d6dce84.png)
i keep getting this error when i try to run the container for the firs time

**Comment by oraclesean** [comment]
It looks like you're trying to create the data volume in `/var/lib` and Docker probably doesn't have permissions there, based on the first error, `Cannot create directory /opt/oracle/oradata/DOCKOR19C`.

Try setting the directory in the `-v` flag to something under your user's home directory and see if that resolves the error.

I see a likely typo in your command: `-p 1621:1621`. Did you mean 1521, where the Oracle Listener is running?

One final suggestion: try adding a `-d` (for detached) to the `docker run` command. It starts the container as a background process, and that way it's not "attached" to your session. Then, to follow the active log activity in the container, run:
```
docker logs -f oracle19cteeest
```
To log into the container:
```
docker exec -it oracle19cteeest bash
```
Let me know if that helps!

**Comment by ErezaBaftiu-hub** [comment]
for examle which home directory can i give there?

**Comment by ErezaBaftiu-hub** [comment]
also when im trying to run the docker container using Volumes technique 
![image](https://user-images.githubusercontent.com/78739638/217880437-b7c6335b-860a-4199-bb14-853e69a02b41.png)

i get this error

**Comment by oraclesean** [comment]
This command works for me on my Windows system running as user "Docker":
```
docker run -d --name test -v C:/Users/Docker/test:/opt/oracle/oradata oracle/database:19.3.0-ee
```
For your system, you could try:
```
... -v C:/Users/ereza.baftiu/oracle19cteeest ...
```

**Comment by oraclesean** [comment]
For the issue with the `volume` command, the directory path in the `device` option isn't on your system. Try using a path similar to the one I suggested above.

**Comment by e1999b** [comment]
I created the first container waited for database to be installed using this command:
docker run -d --name newtest -e ORACLE_SID=docker -p 52521:1521 --volume C:/Users/ereza.baftiu/newtest:/opt/oracle/oradata oracle19.3.0:or19c

when i created the second container using this command:
docker run -d --name finaltest -e ORACLE_SID=docker -p 52531:1521 --volume C:/Users/ereza.baftiu/newtest:/opt/oracle/oradata oracle19.3.0:or19c

i got this error on the second container:
![image](https://user-images.githubusercontent.com/78739638/218065736-152a27c6-0e58-419f-a879-16781c1d4e14.png)

**Comment by e1999b** [comment]
fixed it, the problem was the first container was running when it shouldn't have been. Thank you

**Comment by TWry** [comment]
> Create a new container, using the same `ORACLE_SID`. Map the `oradata` directory to the new directory path. You _must_ also change the container name and any mapped ports:
> 
> ```
> docker run -d \
>         --name newdb \
>         -p 52521:1521 \
>         -v ~/oradata/newdb:/opt/oracle/oradata \
>         oracle/database:19.3.0-ee
> ```

I'm not sure that this works for me. I would expect the startup to be very quick, but it takes about 15mins. It seems that the database is created from scratch, `newdb` is almost 8GB (NB: with no data whatsoever) and contains an additional directory `ORCLCDB` which contains a nested structure of database files. The `o193` is 3.77GB large.

The logs also don't say anything about reusing already existing database files. What's wrong here?

**Comment by TWry** [comment]
Here's the result of ls -laR of the /opt/oracle/oradata directory:

```
sh-4.2$ ls -laR oradata/
oradata/:
total 8
drwxrwxrwx 1 root   root     4096 Mar  8 12:40 .
drwxr-xr-x 1 oracle dba      4096 Mar  8 12:40 ..
-rw-r--r-- 1 oracle oinstall   25 Feb 28 06:40 .ORCL.created
-rw-r--r-- 1 oracle oinstall   25 Mar  8 12:40 .ORCLCDB.created
drwxrwxrwx 1 root   root     4096 Mar  8 12:24 ORCL
drwxr-x--- 1 oracle oinstall 4096 Mar  8 12:29 ORCLCDB
drwxrwxrwx 1 root   root     4096 Mar  8 12:40 dbconfig
 
oradata/ORCL:
total 2465556
drwxrwxrwx 1 root   root      4096 Mar  8 12:24 .
drwxrwxrwx 1 root   root      4096 Mar  8 12:40 ..
drwxrwxrwx 1 root   root      4096 Mar  8 12:24 ORCLPDB1
-rw-r----- 1 oracle dba   18726912 Feb 28 07:19 control01.ctl
-rw-r----- 1 oracle dba   18726912 Feb 28 07:19 control02.ctl
drwxrwxrwx 1 root   root      4096 Mar  8 12:24 pdbseed
-rw-r----- 1 oracle dba  209715712 Feb 28 06:40 redo01.log
-rw-r----- 1 oracle dba  209715712 Feb 28 06:40 redo02.log
-rw-r----- 1 oracle dba  209715712 Feb 28 07:19 redo03.log
-rw-r----- 1 oracle dba  534781952 Feb 28 07:19 sysaux01.dbf
-rw-r----- 1 oracle dba  933240832 Feb 28 07:19 system01.dbf
-rw-r----- 1 oracle dba   33562624 Feb 28 06:35 temp01.dbf
-rw-r----- 1 oracle dba  351281152 Feb 28 07:19 undotbs01.dbf
-rw-r----- 1 oracle dba    5251072 Feb 28 07:19 users01.dbf
 
oradata/ORCL/ORCLPDB1:
total 758824
drwxrwxrwx 1 root   root      4096 Mar  8 12:24 .
drwxrwxrwx 1 root   root      4096 Mar  8 12:24 ..
-rw-r----- 1 oracle dba  346038272 Feb 28 07:19 sysaux01.dbf
-rw-r----- 1 oracle dba  283123712 Feb 28 07:19 system01.dbf
-rw-r----- 1 oracle dba   37756928 Feb 28 06:40 temp01.dbf
-rw-r----- 1 oracle dba  104865792 Feb 28 07:19 undotbs01.dbf
-rw-r----- 1 oracle dba    5251072 Feb 28 07:19 users01.dbf
 
oradata/ORCL/pdbseed:
total 743456
drwxrwxrwx 1 root   root      4096 Mar  8 12:24 .
drwxrwxrwx 1 root   root      4096 Mar  8 12:24 ..
-rw-r----- 1 oracle dba  335552512 Feb 28 06:39 sysaux01.dbf
-rw-r----- 1 oracle dba  283123712 Feb 28 06:39 system01.dbf
-rw-r----- 1 oracle dba   37756928 Feb 28 06:35 temp012023-02-28_06-32-41-567-AM.dbf
-rw-r----- 1 oracle dba  104865792 Feb 28 06:39 undotbs01.dbf
 
oradata/ORCLCDB:
total 2465556
drwxr-x--- 1 oracle oinstall      4096 Mar  8 12:29 .
drwxrwxrwx 1 root   root          4096 Mar  8 12:40 ..
drwxr-x--- 1 oracle oinstall      4096 Mar  8 12:40 ORCLPDB1
-rw-r----- 1 oracle dba       18726912 Mar 22 15:06 control01.ctl
-rw-r----- 1 oracle dba       18726912 Mar  8 12:57 control02.ctl
drwxr-x--- 1 oracle oinstall      4096 Mar  8 12:32 pdbseed
-rw-r----- 1 oracle dba      209715712 Mar 22 15:06 redo01.log
-rw-r----- 1 oracle dba      209715712 Mar 22 15:05 redo02.log
-rw-r----- 1 oracle dba      209715712 Mar 22 15:05 redo03.log
-rw-r----- 1 oracle dba      534781952 Mar 22 15:05 sysaux01.dbf
-rw-r----- 1 oracle dba      933240832 Mar 22 15:05 system01.dbf
-rw-r----- 1 oracle dba       33562624 Mar  8 12:35 temp01.dbf
-rw-r----- 1 oracle dba      351281152 Mar 22 15:05 undotbs01.dbf
-rw-r----- 1 oracle dba        5251072 Mar 22 15:05 users01.dbf
 
oradata/ORCLCDB/ORCLPDB1:
total 748584
drwxr-x--- 1 oracle oinstall      4096 Mar  8 12:40 .
drwxr-x--- 1 oracle oinstall      4096 Mar  8 12:29 ..
-rw-r----- 1 oracle dba      335552512 Mar 22 15:05 sysaux01.dbf
-rw-r----- 1 oracle dba      283123712 Mar 22 15:05 system01.dbf
-rw-r----- 1 oracle dba       37756928 Mar 22 15:05 temp01.dbf
-rw-r----- 1 oracle dba      104865792 Mar 22 15:05 undotbs01.dbf
-rw-r----- 1 oracle dba        5251072 Mar 22 15:05 users01.dbf
 
oradata/ORCLCDB/pdbseed:
total 743456
drwxr-x--- 1 oracle oinstall      4096 Mar  8 12:32 .
drwxr-x--- 1 oracle oinstall      4096 Mar  8 12:29 ..
-rw-r----- 1 oracle dba      335552512 Mar  8 12:40 sysaux01.dbf
-rw-r----- 1 oracle dba      283123712 Mar  8 12:40 system01.dbf
-rw-r----- 1 oracle dba       37756928 Mar  8 12:35 temp012023-03-08_12-32-45-638-PM.dbf
-rw-r----- 1 oracle dba      104865792 Mar  8 12:40 undotbs01.dbf
 
oradata/dbconfig:
total 0
drwxrwxrwx 1 root   root     4096 Mar  8 12:40 .
drwxrwxrwx 1 root   root     4096 Mar  8 12:40 ..
drwxrwxrwx 1 root   root     4096 Mar  8 12:24 ORCL
drwxr-xr-x 1 oracle oinstall 4096 Mar  8 12:40 ORCLCDB
 
oradata/dbconfig/ORCL:
total 12
drwxrwxrwx 1 root   root     4096 Mar  8 12:24 .
drwxrwxrwx 1 root   root     4096 Mar  8 12:40 ..
-rw-r--r-- 1 oracle oinstall    0 Feb 28 06:26 .docker_enterprise
-rw-r--r-- 1 oracle oinstall  234 Feb 28 06:26 listener.ora
-rw-r----- 1 oracle oinstall 2048 Feb 28 06:28 orapwORCL
-rw-r--r-- 1 oracle oinstall  777 Feb 28 06:40 oratab
-rw-r----- 1 oracle dba      3584 Feb 28 06:40 spfileORCL.ora
-rw-r--r-- 1 oracle oinstall   54 Feb 28 06:26 sqlnet.ora
-rw-r----- 1 oracle oinstall  191 Feb 28 06:40 tnsnames.ora
 
oradata/dbconfig/ORCLCDB:
total 12
drwxr-xr-x 1 oracle oinstall 4096 Mar  8 12:40 .
drwxrwxrwx 1 root   root     4096 Mar  8 12:40 ..
-rw-r--r-- 1 oracle oinstall    0 Mar  8 12:27 .docker_enterprise
-rw-r--r-- 1 oracle oinstall  234 Mar  8 12:27 listener.ora
-rw-r----- 1 oracle oinstall 2048 Mar  8 12:29 orapwORCLCDB
-rw-r--r-- 1 oracle oinstall  780 Mar  8 12:40 oratab
-rw-r----- 1 oracle dba      3584 Mar 22 15:05 spfileORCLCDB.ora
-rw-r--r-- 1 oracle oinstall   54 Mar  8 12:27 sqlnet.ora
-rw-r----- 1 oracle oinstall  197 Mar  8 12:40 tnsnames.ora
```

The commands used were literally the same as in your post, ie. 
```
docker run -d \ 
   --name o193 \
   -e ORACLE_SID=ORCL \
    -p 51521:1521 \
    -v ~/oradata/o193:/opt/oracle/oradata \
    oracle/database:19.3.0-ee
```
and 
```
docker run -d \
        --name newdb \
        -p 52521:1521 \
        -v ~/oradata/newdb:/opt/oracle/oradata \
        oracle/database:19.3.0-ee
```

**Comment by oraclesean** [comment]
> The commands used were literally the same as in your post, ie.
> 
> ```
> docker run -d \ 
>    --name o193 \
>    -e ORACLE_SID=ORCL \
>     -p 51521:1521 \
>     -v ~/oradata/o193:/opt/oracle/oradata \
>     oracle/database:19.3.0-ee
> ```
> 
> and
> 
> ```
> docker run -d \
>         --name newdb \
>         -p 52521:1521 \
>         -v ~/oradata/newdb:/opt/oracle/oradata \
>         oracle/database:19.3.0-ee
> ```

This was my oversight. In the oradata directory:
> ```
> sh-4.2$ ls -laR oradata/
> oradata/:
> total 8
> drwxrwxrwx 1 root   root     4096 Mar  8 12:40 .
> drwxr-xr-x 1 oracle dba      4096 Mar  8 12:40 ..
> -rw-r--r-- 1 oracle oinstall   25 Feb 28 06:40 .ORCL.created
> -rw-r--r-- 1 oracle oinstall   25 Mar  8 12:40 .ORCLCDB.created
> drwxrwxrwx 1 root   root     4096 Mar  8 12:24 ORCL
> drwxr-x--- 1 oracle oinstall 4096 Mar  8 12:29 ORCLCDB
> drwxrwxrwx 1 root   root     4096 Mar  8 12:40 dbconfig
> ```
Notice that there are two hidden `.created` files. The first, from February 28, is for the original database with the SID of ORCL. The second is from March 28, with the SID ORCLCDB (the default). The startup scripts didn't recognize the new (default) SID when running the second container, so it created a new database. I mentioned that:
> Create a new container, using the same ORACLE_SID. Map the oradata directory to the new directory path. You must also change the container name and any mapped ports:
...but I failed to include the environment variable. I should have written:
```
docker run -d \ 
       --name o193 \
       -e ORACLE_SID=ORCL \
        -p 51521:1521 \
        -v ~/oradata/o193:/opt/oracle/oradata \
        oracle/database:19.3.0-ee
```
and
```
docker run -d \
        --name newdb \           # The container name must be unique
       -e ORACLE_SID=ORCL \     # The ORACLE_SID and ORACLE_PDB must be the same
        -p 61521:1521 \          # Any mapped port must be unique
        -v ~/oradata/newdb:/opt/oracle/oradata \ # Reference the new directory path
        oracle/database:19.3.0-ee
```
Apologies for the confusion!
