### ISSUE TITLE
Doesn't get the current version of docker correctly.

### ISSUE THREAD

**Issue by flexhamp** [oracle/docker-images#2565]
https://github.com/oracle/docker-images/blob/53ea9899593d77253aa732502a4ae155f7a8d150/OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh#L90

Doesn't get the current version of docker correctly. If the lead is '23.0.1', it will be '23.0.' (230). This will be less than the minimum.

This can be fixed by changing the script to this:
`DOCKER_VERSION=$("${CONTAINER_RUNTIME}" version --format '{{.Server.Version}}'|| exit 0)`
or this:
`DOCKER_VERSION=$("${CONTAINER_RUNTIME}" version --format '{{.Server.Version | printf "%.6s" }}'|| exit 0)`

**Comment by aditya059** [comment]
Fixed

**Comment by flexhamp** [comment]
@aditya059, @yunus-qureshi, @gvenzl You're welcome
