### ISSUE TITLE
Docker version comparison issue  

### ISSUE THREAD

**Issue by MrMoon** [oracle/docker-images#2573]
I am trying to use the script with docker `Docker version 23.0.1` 
however, I think this line produce a bug that eventually produce 

https://github.com/oracle/docker-images/blob/53ea9899593d77253aa732502a4ae155f7a8d150/OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh#L94

```
Docker version is below the minimum required version 17.09
Please upgrade your Docker installation to proceed.

```
This is very confusing, not sure if it where the exact problem is, but `echo DOCKER_VERSION` gives 230 which is wrong.

Happy to contribute with some pointers, my idea is that increasing the printf float point to more than 5, here,
https://github.com/oracle/docker-images/blob/53ea9899593d77253aa732502a4ae155f7a8d150/OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh#L90

**Comment by rafaeltribeiro** [comment]
Thanks for advising. I increased the printf to 9 and it`s worked fine.
