### ISSUE TITLE
The script (buildDockerImage.sh) is in error for version docker 23.0

### ISSUE THREAD

**Issue by jfredrv** [oracle/docker-images#2574]
When running:
`
./buildDockerImage.sh -v 18.4.0 -x -i
`

The error below is displayed:
`
 "Docker version is below the minimum required version 17.09".
` 

But my docker version is higher (Version: 23.0.1).
 
I verified that the problem is in the script buildDockerImage.sh
`
Line: DOCKER_VERSION=$(docker version --format '{{.Server.Version | printf "%.5s" }}')
`

For this version this command returns 23.0. And this is the reason for the error. 

From version 23 the second part has only one digit, not two as before.

**Comment by aditya059** [comment]
Fixed
