### ISSUE TITLE
Incorrect use of "SID" instead of "service name"

### ISSUE THREAD

**Issue by cjbj** [oracle/docker-images#2582]
https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md contains this text:

```
sqlplus sys/<your password>@//localhost:1521/<your SID> as sysdba
sqlplus system/<your password>@//localhost:1521/<your SID>
sqlplus pdbadmin/<your password>@//localhost:1521/<Your PDB name>
```

The use of "SID" is incorrect and perpetuates a myth that tricks many users trying to connect to Oracle.  Please change it. The '[Easy Connect](https://download.oracle.com/ocomdocs/global/Oracle-Net-21c-Easy-Connect-Plus.pdf)' syntax shown doesn't work with SIDs, but uses only service names.

Other places (including scripts?) may need to change to use 'service name' as well, or mention that the service name is also derived from the value passed in.

**Comment by gvenzl** [comment]
@yunus-qureshi, the mistake is also on the container-registry.oracle.com ReadMe, please fix it there too.

**Comment by gvenzl** [comment]
Fixed.
