### ISSUE TITLE
Support configTcps with parameter port number and wallet password

### ISSUE THREAD

**Issue by vaibhavkhanduja** [oracle/docker-images#2596]
The configTcps today can be executed to run TCPS support at listener level. Please extend it to support with optional parameter of port number and wallet password.

**Comment by yunus-qureshi** [comment]
@aosingh please raise a PR for this. @aditya059 please help review the PR

**Comment by aosingh** [comment]
@aditya059 let me know if you have any questions. I have raised a PR
