### ISSUE TITLE
Oracle 21c EE - ORA-01017: invalid username/password; logon denied

### ISSUE THREAD

**Issue by meenamunshi** [oracle/docker-images#2602]
SID: ORCLCDB
Service: ORCLPDB1
SQL> SELECT name, pdb FROM   v$services ORDER BY name; 
 NAME			                PDB
------------------------------ ------------------------------
ORCLCDB                            CDB$ROOT
ORCLCDBXDB                    CDB$ROOT
SYS$BACKGROUND          CDB$ROOT
SYS$USERS                       CDB$ROOT
orclpdb1                             ORCLPDB1

SQL> create user c##testaccount identified by test1234;
User created.
SQL> grant connect to c##testaccount container=all;
Grant succeeded.
SQL> alter user c##testaccount identified by test1234 container=all;
User altered.
SQL> grant dba to c##testaccount container=all;
Grant succeeded.
SQL> conn c##testaccount/test1234@//localhost:1521/ORCLPDB1 as sysdba
ERROR:
ORA-01017: invalid username/password; logon denied

Warning: You are no longer connected to ORACLE.

------LSTNR--------------
bash-4.2$ lsnrctl status

LSNRCTL for Linux: Version 21.0.0.0.0 - Production on 24-MAR-2023 16:46:40

Copyright (c) 1991, 2021, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 21.0.0.0.0 - Production
Start Date                23-MAR-2023 20:56:43
Uptime                    0 days 19 hr. 49 min. 57 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/homes/OraDB21Home1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/oracle-app-5cd56bdf4-kjprv/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=oracle-app-5cd56bdf4-kjprv)(PORT=5500))(Security=(my_wallet_directory=/opt/oracle/admin/ORCLCDB/xdb_wallet))(Presentation=HTTP)(Session=RAW))
Services Summary...
Service "ORCLCDB" has 1 instance(s).
  Instance "ORCLCDB", status READY, has 1 handler(s) for this service...
Service "ORCLCDBXDB" has 1 instance(s).
  Instance "ORCLCDB", status READY, has 1 handler(s) for this service...
Service "f798a1bdf84f096ce053c404f00a0870" has 1 instance(s).
  Instance "ORCLCDB", status READY, has 1 handler(s) for this service...
Service "orclpdb1" has 1 instance(s).
  Instance "ORCLCDB", status READY, has 1 handler(s) for this service...
The command completed successfully

**Comment by oraclesean** [comment]
The `SYSDBA` role was not granted to the user, but the failed connection is `as sysdba`.
```
SQL> create user c##testaccount identified by test1234;

User created.

SQL> grant connect to c##testaccount container=all;

Grant succeeded.

SQL> grant dba to c##testaccount container=all;

Grant succeeded.

SQL> show pdbs

    CON_ID CON_NAME			  OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
	 2 PDB$SEED			  READ ONLY  NO
	 3 PDB1 			  READ WRITE NO
SQL> conn c##testaccount/test1234@//localhost:1521/PDB1
Connected.
SQL> conn c##testaccount/test1234@//localhost:1521/PDB1 as sysdba
ERROR:
ORA-01017: invalid username/password; logon denied


Warning: You are no longer connected to ORACLE.
```
Solution: Grant the `SYSDBA` role to the user.
```
SQL> grant sysdba to c##testaccount container=all;

Grant succeeded.

SQL> conn c##testaccount/test1234@//localhost:1521/PDB1 as sysdba
Connected.
```
