### ISSUE TITLE
Enable ORDS  3.0 or later

### ISSUE THREAD

**Issue by pvsmadhukar** [oracle/docker-images#261]
Support for ORDS 3.0 or later along with the default configuration.
If not provide instructions to configure ORDS on docker.

**Comment by Djelibeybi** [comment]
What is ORDS?

**Comment by gvenzl** [comment]
Oracle REST Data Services.

**Comment by Djelibeybi** [comment]
Ah, cool. Database thing, I assume. :)

**Comment by gvenzl** [comment]
Yup, a revolutionary technology from Oracle to REST-enable data persistence and data access.

**Comment by brunoborges** [comment]
ORDS is already a docker image. closing.
