### ISSUE TITLE
Oracle 23c

### ISSUE THREAD

**Issue by doberkofler** [oracle/docker-images#2611]
I was wondering when we can expect support for Oracle 23c database container?

**Comment by yunus-qureshi** [comment]
It is already available

container-registry.oracle.com/database/free:latest

**Comment by doberkofler** [comment]
@yunus-qureshi  Sure but what about the usual script in this repository needed to create a customised container?

**Comment by yunus-qureshi** [comment]
That will be made available when 23c production release goes out.

**Comment by cjbj** [comment]
@yunus-qureshi why wait?  Users are obviously using containers for Free already, and we want testing and usage to be easy.  @gvenzl already has his image available.

**Comment by yunus-qureshi** [comment]
@cjbj ok sure.  @IshaanDesai45 please make the build scripts for for 23.2 available here
