### ISSUE TITLE
Applying Patching on oracle:19.3.0.0 got error Argument(s) Error... Patch location is not valid for apply

### ISSUE THREAD

**Issue by eyaneylii** [oracle/docker-images#2617]
when I try to appy patch on 19.3.0.0 with zip file of 19.18.0.0 I got below error :
**ZOP-51: The patch location is not valid for apply, because it doesn't have correct metadata, or it points to a patch directory.
Argument(s) Error... Patch location is not valid for apply**
How to solve it please ?

**Comment by yunus-qureshi** [comment]
Please provide the build logs. Where have you downloaded and placed the patch? Did you unzip it?

**Comment by eyaneylii** [comment]
> Please provide the build logs. Where have you downloaded and placed the patch? Did you unzip it?
I followed the steps in this [link](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/samples/applypatch) : I build the base image 19.3.0.0 and downloaded the patch 19.18.0.0 then I followed the steps of applying patch but I modified the dockerfile to get my built image and I tried both zip file and unzipped file

**Comment by yunus-qureshi** [comment]
Can you try this https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/extensions/patching

**Comment by eyaneylii** [comment]
> Can you try this https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/extensions/patching :
Thank you for your response. So the release update is the patch zip file right ? but the one-offs what does it mean please ?

**Comment by yunus-qureshi** [comment]
It is for applying one or more one-off fixes over the release update. You may leave that directory empty if you don't have any.

**Comment by yunus-qureshi** [comment]
What do you have 6880880 under the release_update folder? That has to be placed under the one-offs. We'll update the documentation to indicate that

**Comment by eyaneylii** [comment]
> Thank you it works, now.
But I need to ask you about something please. Actually I'm doing the patch to upgrade the used java version on oracle but after patching I found same java version "1.8.0_201"
