### ISSUE TITLE
Please report it at https://forums.oracle.com/ords/apexds/domain/dev-community/category/oracle-database-free

### ISSUE THREAD

**Issue by Mwilson7583** [oracle/docker-images#2655]
Please report it at https://forums.oracle.com/ords/apexds/domain/dev-community/category/oracle-database-free

_Originally posted by @cjbj in https://github.com/oracle/docker-images/issues/2654#issuecomment-1612725978_

**Comment by gvenzl** [comment]
Please open an issue at https://forums.oracle.com/ords/apexds/domain/dev-community/category/oracle-database-free
