### ISSUE TITLE
aarch64 Docker image for Oracle Database 19c

### ISSUE THREAD

**Issue by stevefan1999-personal** [oracle/docker-images#2658]
According to https://www.oracle.com/database/technologies/oracle19c-linux-arm64-downloads.html, we should be able to run 19c on aarch64 now, especially combined with Ampere A1 instances.

**Comment by oehrlis** [comment]
Hi I could successfully build a docker container on MacOS (M1) with an Oracle Linux 8.8 base image using my own Oracle Docker scripts. The times for building the container and starting/creating the database did look reasonable. I haven't looked at the performance yet. However, an Oracle 19c (aarch64) is now running on my MacBook Pro (M1) 😎. 

I assume that it is not an issue to build an Oracle 19c (aarch64) for Ampere A1 instances.

Regards, Stefan

**Comment by yunus-qureshi** [comment]
We'll raise a PR to support this soon.

**Comment by stevefan1999-personal** [comment]
@yunus-qureshi @oehrlis Much appreciated.

**Comment by gvenzl** [comment]
Just got merged as part of #2659 🥳

**Comment by osolindo** [comment]
> Hi I could successfully build a docker container on MacOS (M1) with an Oracle Linux 8.8 base image using my own Oracle Docker scripts. The times for building the container and starting/creating the database did look reasonable. I haven't looked at the performance yet. However, an Oracle 19c (aarch64) is now running on my MacBook Pro (M1) 😎.
> 
> I assume that it is not an issue to build an Oracle 19c (aarch64) for Ampere A1 instances.
> 
> Regards, Stefan

Hello Stefan,
Would you mind sharing the steps to your successful installation?
I pulled an image from GitHub but it fails to build.

Thanks

**Comment by stevefan1999-personal** [comment]
> > Hi I could successfully build a docker container on MacOS (M1) with an Oracle Linux 8.8 base image using my own Oracle Docker scripts. The times for building the container and starting/creating the database did look reasonable. I haven't looked at the performance yet. However, an Oracle 19c (aarch64) is now running on my MacBook Pro (M1) 😎.  
> > I assume that it is not an issue to build an Oracle 19c (aarch64) for Ampere A1 instances.  
> > Regards, Stefan
> 
> Hello Stefan, Would you mind sharing the steps to your successful installation? I pulled an image from GitHub but it fails to build.
> 
> Thanks

I don't have it. It was originally for my test pipeline. I think I manually installed the RPMs as a service in the end. But I do think we could just use docker pull and docker run for this now,

**Comment by oehrlis** [comment]
Hi

I’ll do as soon as I find time this week. Currently busy with project deadlines 🤪. I did not use the rpm. Just the plain software similar as I did for my x86 images.

Regards
Stefan
____________________________

Stefan Oehrli

Bühlmattenweg 6
5630 Muri
Phone: +41 56 664 90 45
Mobile: +41 79 239 84 88
***@***.***

**Comment by oraclesean** [comment]
I have a repo with options for building images on ARM/x86 here, plus documentation, if that helps: https://github.com/oraclesean/cloud-native-oracle

**Comment by osolindo** [comment]
thank you Stefan. I will check it out.

**Comment by oehrlis** [comment]
Thanks but that's more to @oraclesean  credit 😊
