### ISSUE TITLE
dbca not found error in Oracle 12c ee

### ISSUE THREAD

**Issue by rakeshm707** [oracle/docker-images#267]
Hi, I am trying to create a docker for Oracle DB 12c ee on my ubuntu 14. 
Docker version is 1.13

I can see the build was successful, i do not see any error in the build log but when i try the first run i get an error as shown below.
I am also attaching the build log and oracle install log
My run command: 
docker run  \
> -p 1521:1521 -p 5500:5500 \
> -e ORACLE_SID=orcl \
> -e ORACLE_PDB=orclpdb \
> -v /home/vagrant/ora_db:/opt/oracle/oradata \
> oracle/database:12.1.0.2-ee

**Log**: 

/opt/oracle/createDB.sh: line 55: /opt/oracle/product/12.1.0.2/dbhome_1/bin/dbca: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/orcl/orcl.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/orcl.log: No such file or directory
sqlplus: error while loading shared libraries: /opt/oracle/product/12.1.0.2/dbhome_1/lib/libclntsh.so.12.1: file too short
mkdir: cannot create directory '/opt/oracle/oradata/dbconfig': Permission denied
mv: cannot stat '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/spfileorcl.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/orapworcl': No such file or directory
mv: cannot move '/opt/orac

le/product/12.1.0.2/dbhome_1/network/admin/tnsnames.ora' to '/opt/oracle/oradata/dbconfig/orcl/': No such file or directory
cp: cannot create regular file '/opt/oracle/oradata/dbconfig/orcl/': No such file or directory
ln: failed to create symbolic link '/opt/oracle/product/12.1.0.2/dbhome_1/network/admin/tnsnames.ora': File exists
cp: cannot stat '/opt/oracle/oradata/dbconfig/orcl/oratab': No such file or directory
#########################
DATABASE IS READY TO USE!
#########################
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining

Any pointer would be helpful. Thanks

[ora install.txt](https://github.com/oracle/docker-images/files/752111/ora.install.txt)
[build.txt](https://github.com/oracle/docker-images/files/752113/build.txt)

**Comment by gvenzl** [comment]
Something went wrong during the installation of the binaries. You should see following output:

    Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-02-06_07-43-05PM. Please wait ...[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
       ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
    You can find the log of this install session at:
     /opt/oracle/oraInventory/logs/installActions2017-02-06_07-43-05PM.log
    The installation of Oracle Database 12c was successful.
    Please check '/opt/oracle/oraInventory/logs/silentInstall2017-02-06_07-43-05PM.log' for more details.
    
    As a root user, execute the following script(s):
	    1. /opt/oracle/oraInventory/orainstRoot.sh
	    2. /opt/oracle/product/12.1.0.2/dbhome_1/root.sh

In your build log however there is no message that the binaries were setup successfully:

    Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-02-02_03-21-15PM. Please wait ...[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
       ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
    You can find the log of this install session at:
     /opt/oracle/oraInventory/logs/installActions2017-02-02_03-21-15PM.log
    
    This is perl 5, version 14, subversion 1 (v5.14.1) built for x86_64-linux-thread-multi

Can you please go ahead and check the install log file within the container?

**Comment by gvenzl** [comment]
Closing the issue due to lack of response. Please reopen if this issue remains.

**Comment by krishnagkashyap** [comment]
I am facing the same issue as described above. Please help
