### ISSUE TITLE
Update container images in Oracle Container Registry

### ISSUE THREAD

**Issue by rbreejen** [oracle/docker-images#2672]
Hi,

Is it possible to update the container images in the [Oracle Container Registry](https://container-registry.oracle.com/)? These images are out-dated, see table below. There was a really nice fix to work around a Docker proxy bug, see https://github.com/oracle/docker-images/pull/2620. Currently this fix is not yet included in these images. Would like to prevent people wasting time because of this issue.

| Type | Last updated | Recent Docker image change |
|---|---|---|
| container-registry.oracle.com/database/express:21.3.0-xe | 10 months ago | last month |
| container-registry.oracle.com/database/enterprise:19.3.0.0 | 10 months ago | 2 days ago |
| container-registry.oracle.com/database/enterprise:21.3.0.0 | 10 months ago | last month |
| container-registry.oracle.com/database/free:23.2.0.0 | 4 months ago | 2 weeks ago |

Thanks in advance!

**Comment by yunus-qureshi** [comment]
container-registry.oracle.com/database/express:21.3.0-xe will no longer be updated as the 23c free supersedes it. 

Other images will be updated soon.

**Comment by rbreejen** [comment]
Thanks! Pity that express:21.3.0-xe is not updated, I was actually working with that one. Less support from downstream vendors... (i.e. [Debezium](https://issues.redhat.com/browse/DBZ-5655)). If you might see the chance to press that build button for 21.3.0-xe would be nice.

**Comment by yunus-qureshi** [comment]
Everything that you are using in 21.3.0-xe should be available in 23c Free and more. Recommend that you move to 23c Free as it has already GA'ed

**Comment by aditya059** [comment]
Hi @rbreejen 
We have republished 21.3.0-xe and 23.2.0.0 free on container registry.

**Comment by rbreejen** [comment]
@aditya059 Thanks a lot. Appreciate it!

**Comment by yunus-qureshi** [comment]
All images have been updates
