### ISSUE TITLE
Unable to login in https://container-registry.oracle.com/

### ISSUE THREAD

**Issue by marcelo-ochoa** [oracle/docker-images#268]
Once I try https://container-registry.oracle.com/ an error page with this message is shown:

> Thank you for accessing www.oracle.com
> 
> In compliance with U.S. and applicable Export laws we are unable to process your request.  Please contact RPLS-Ops_ww@oracle.com if you believe you are receiving this notice in error. 

Obliviously  docker login container-registry.oracle.com fails with:
_Account is not active. Please see the documentation of the registry https://container-registry.oracle.com/v1/ for instructions how to activate it._
Marcelo.

**Comment by Djelibeybi** [comment]
The Oracle Container Registry is only currently available for customers in the United States, United Kingdom and Australia. We're working hard to expand this as soon as possible.

**Comment by marcelo-ochoa** [comment]
Thanks for your quick reply, Marcelo.

**Comment by NoUsername** [comment]
If only someone would invent some kind of computer network that would work all over the world...

**Comment by Exordian** [comment]
>We're working hard to expand this as soon as possible.

Shouldn't the issue then remain open? It is still an issue for a lot of users.

**Comment by Djelibeybi** [comment]
It's off-topic for this git repo though: while they're both controlled by Oracle, the Container Registry and the public Dockerfiles are not managed by the same team.

**Comment by brunoborges** [comment]
@Exordian you may also pull images from the Docker Store
