### ISSUE TITLE
chmod: changing permissions of '/opt/install/installDBBinaries.sh': Operation not permitted

### ISSUE THREAD

**Issue by lejudika** [oracle/docker-images#2681]
Hi,
when running the following command:
`sudo ./buildContainerImage.sh -v 19.3.0 -s -i`
it crashes in Step 15 :
`
Step 13/25 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
 ---> 4dbf312fbbad
Step 14/25 : USER oracle
 ---> Running in 78740df6c8a5
Removing intermediate container 78740df6c8a5
 ---> 70a46086ced6
Step 15/25 : RUN chmod ug+x "$INSTALL_DIR"/*.sh &&     sync &&     "$INSTALL_DIR"/"$INSTALL_DB_BINARIES_FILE" $DB_EDITION
 ---> Running in ee08db8337f2
chmod: changing permissions of '/opt/install/installDBBinaries.sh': Operation not permitted
Removing intermediate container ee08db8337f2
The command '/bin/sh -c chmod ug+x "$INSTALL_DIR"/*.sh &&     sync &&     "$INSTALL_DIR"/"$INSTALL_DB_BINARIES_FILE" $DB_EDITION' returned a non-zero code: 1

ERROR: Oracle Database container image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the build operation.

`
I can't find any workaraound and I don't understand why this Error happens.
Any help highly appreciated, thanks in advance!

**Comment by yunus-qureshi** [comment]
Do you have enough disk space? Can you please paste the output of docker info

**Comment by OtavioRMC** [comment]
I had the same issue while trying to build it in Ubuntu 22.04.
I had with versions 19.3.0 and 21.3.0

I typed:

/docker-images/OracleDatabase/SingleInstance/dockerfiles$ ./buildContainerImage.sh -v 21.3.0 -s

Step 10/24 : FROM base AS builder
 ---> a84f769e3b8a
Step 11/24 : ARG DB_EDITION
 ---> Running in 1dc5e70c94cf
Removing intermediate container 1dc5e70c94cf
 ---> 9bf31d53be32
Step 12/24 : COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
 ---> 2cec7eab9e57
Step 13/24 : USER oracle
 ---> Running in a0697f55686e
Removing intermediate container a0697f55686e
 ---> 60711665983c
Step 14/24 : RUN chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE $DB_EDITION
 ---> Running in 317c7409c1af
chmod: changing permissions of '/opt/install/installDBBinaries.sh': Operation not permitted
Removing intermediate container 317c7409c1af
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE $DB_EDITION' returned a non-zero code: 1

ERROR: Oracle Database container image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the build operation.

I tried manually giving the necessary permissions in all folders but it didn't work.
I also tried running the terminal as root but nothing changed.

**Comment by yunus-qureshi** [comment]
May be your /var/lib/docker is mount that is not owned by your user id or has some size quota set.

**Comment by yunus-qureshi** [comment]
Try building with [podman](https://podman.io/)
