### ISSUE TITLE
Updates for Oracle Linux 9 Instant Client

### ISSUE THREAD

**Issue by Physium** [oracle/docker-images#2708]
Is there any plans to release a docker image that comes with both oracle linux 9 and instant client? There is 7 and 8, is 9 in the works?

**Comment by deepak0029** [comment]
Is there any plans to release a docker image that comes with both oracle linux 9 and instant client? There is 7 and 8, is 9 in the works?

**Comment by cjbj** [comment]
Closed via https://github.com/oracle/docker-images/pull/2790
