### ISSUE TITLE
Creation of OracleDatabase 21c errors with out of memory

### ISSUE THREAD

**Issue by reinaldorauch** [oracle/docker-images#2746]
Command (in OracleDatabase/dockerfiles folder)

```bash
sh buildContainerImage.sh -v 21.3.0 -t oracle21 -x
```

Running inside wsl2 with arch linux,  docker version 24.0.7, build afdd53b4e3

Log output: 
[build.log](https://github.com/oracle/docker-images/files/13968062/build.log)

**Comment by saurabhaahujaa** [comment]
Well, 21.3.0 RAC and Database image in this repo is documented and tested to be built with Oracle Linux 7.x and docker engine from yum repo -> https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/index.html. At the moment its not tested with Arch linux and Docker 24.x . You are welcomed to do research but if you want working image, then go with documentation. Anything else do you want to add @psaini79 ?

**Comment by reinaldorauch** [comment]
Ok then, thanks for the reply
