### ISSUE TITLE
Bash environment of _oracle_ user broke.

### ISSUE THREAD

**Issue by 3ronco** [oracle/docker-images#2775]
In _docker-images/OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile_ the line:

`RUN echo 'ORACLE_SID=${ORACLE_SID:-ORCLCDB}; export ORACLE_SID=${ORACLE_SID^^}' > .bashrc`

replaces _oracle_ user's bash environment completely. I guess `... >> .bashrc` was intended?

**Comment by yunus-qureshi** [comment]
As the oracle user is created during build there is no default .bashrc for oracle user to begin with.

**Comment by 3ronco** [comment]
In previous versions of the _oracle/database_ image this was handled correctly.
The creation of the user at image buildtime is irrelevant for this. It is used as soon as you start a new container for any _bash_ invocation, as this might be a tiny detail looking not very important, your change can issue problems for people not knowing that `~/.bashrc` in your image behaves different than in any other distro especially when you need to embed customized executables via PATH var or global settings via `/etc/bashrc` eg. when you use scripts for database initialization in `/docker-entrypoint-initdb.d/{startup,setup}`

**Comment by yunus-qureshi** [comment]
export ORACLE_SID=${ORACLE_SID^^}' > .bashrc

@3ronco what I meant was that the above cmd is what creates .bashrc as it was not existing before that so > or >> does not make a difference

**Comment by yunus-qureshi** [comment]
@3ronco i see, we'll check and get back on this. I am surprised that is even contains .kshrc as we don't install ksh.

**Comment by oraclesean** [comment]
I think there's a case for performing `>>` vs `>` should an image include a custom `.bashrc` introduced via modifications in the build scripts.

**Comment by oraclesean** [comment]
@yunus-qureshi I believe that `ksh` gets installed by `oracle-database-preinstall-*`; `ksh` is a long-standing prerequisite for Oracle databases:

```
# yum install -y oracle-database-preinstall-19c

...

Dependencies Resolved

========================================================================================================================================================================================================================
 Package                                                      Arch                                 Version                                                               Repository                                Size
========================================================================================================================================================================================================================
Installing:
 oracle-database-preinstall-19c                               x86_64                               1.0-3.el7                                                             ol7_latest                                27 k
Installing for dependencies:

...

 ksh                                                          x86_64                               20120801-144.0.1.el7_9                                                ol7_latest                               882 k

...

---> Package ksh.x86_64 0:20120801-144.0.1.el7_9 will be installed
```

**Comment by yunus-qureshi** [comment]
I see. Thank you @oraclesean

**Comment by 3ronco** [comment]
Thanks for your efforts :+1:
