### ISSUE TITLE
container-registry.oracle.com/database/enterprise:12.2.0.1-slim -e ORACLE_CHARACTERSET it does not work

### ISSUE THREAD

**Issue by hectorlavado99** [oracle/docker-images#2779]
I am booting an image with the command "docker run -d --name oracle_encoding -p 8282:1521 -e ORACLE_CHARACTERSET=WE8MSWIN1252 container-registry.oracle.com/database/enterprise:12.2.0.1-slim". This does put the environment variable in docker but the configuration is not applied

I have tried with 12.2.0.1 (not slim) and changing NLS_CHARACTERSET does not work either

**Comment by yunus-qureshi** [comment]
12.2.0.1 is no longer supported. Most likely it will be deleted from the repo soon. Try the newer versions like 19c.
