### ISSUE TITLE
Evaluate switching images to the new 7-slim base

### ISSUE THREAD

**Issue by Djelibeybi** [oracle/docker-images#278]
Image owners, please try building and testing your images using the `7-slim` image now on the Docker Hub so we can reduce the overall size of the built images.

**Comment by gvenzl** [comment]
Oracle Database runs fine, Dockerfiles changed! 👍

**Comment by mriccell** [comment]
Oracle WebLogic runs fine with OL7-slim!  I will create a pull request with new Dockerfiles.

**Comment by mriccell** [comment]
Verified that Oracle HTTP Server runs fine with OL7-slim!

**Comment by Djelibeybi** [comment]
I think we're good for now. The MySQL team are also investigating.
