### ISSUE TITLE
OutOfMemoryError: PermGen space

### ISSUE THREAD

**Issue by jkchendataman** [oracle/docker-images#281]
I have been update the JAVA memory opts like this 
`[oracle@7de1dc3910ed bin]$ env | grep MEM
MEM_MAX_PERM_SIZE_32BIT=-XX:MaxPermSize=256m
MEM_PERM_SIZE=-XX:PermSize=512m
MEM_ARGS_32BIT=-Xms512m -Xmx512m
WLS_MEM_ARGS_64BIT=-Xms2048m -Xmx4196m
USER_MEM_ARGS=-Djava.security.egd=file:/dev/./urandom
WLS_MEM_ARGS_32BIT=-Xms512m -Xmx512m
UTILS_MEM_ARGS=-Djava.security.egd=file:/dev/./urandom
MEM_PERM_SIZE_32BIT=-XX:PermSize=1024m
MEM_MAX_PERM_SIZE=-XX:MaxPermSize=1024m
MEM_ARGS_64BIT=-Xms2048m -Xmx4196m
MEM_PERM_SIZE_64BIT=-XX:PermSize=512m
MEM_MAX_PERM_SIZE_64BIT=-XX:MaxPermSize=1024m
MEM_ARGS=-Djava.security.egd=file:/dev/./urandom
MEM_DEV_ARGS=`

but still have the PermGen space error
btw: this config is bigger the my test and production environment. 

weblogic info:  weblogic12.13 + jdk1.7 

anyone who can help

**Comment by mriccell** [comment]
@jkchendataman I made changes to the 1213-domain to be based of the generic installer, also can you test with JRE 8?

**Comment by mriccell** [comment]
Will close the issue because of lack of input
