### ISSUE TITLE
/bin/sh: /u01/app/oraInventory/orainstRoot.sh: No such file or directory in creating RAC docker

### ISSUE THREAD

**Issue by Lrxc** [oracle/docker-images#2821]
![image](https://github.com/oracle/docker-images/assets/21255285/3141f11a-10eb-4602-a047-623a03506ac9)

work dir: docker-images/OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles
build command: ./buildContainerImage.sh -v 19.3.0 -o '--build-arg  BASE_OL_IMAGE=oraclelinux:7 --build-arg SLIMMING=false'

I didn't modify any files after downloading from git, What should I do?
thanks

**Comment by saurabhuja** [comment]
disable buildkit in your docker first (DOCKER_BUILDKIT=0), you are using docker latest version where it is not tested to work. Refer README.md documentation for docker version been tested successfully with.

**Comment by Lrxc** [comment]
> disable buildkit in your docker first (DOCKER_BUILDKIT=0), you are using docker latest version where it is not tested to work. Refer README.md documentation for docker version been tested successfully with.

it worked!
very thanks
