### ISSUE TITLE
[Issue][Patch]Patching script issue (patchDBBinaries.sh)

### ISSUE THREAD

**Issue by eyaneylii** [oracle/docker-images#2822]
Hi all,

While applying p36195566_190000_Linux-x86-64 on oracle/database:19.3.0.0 I had an issue due to below lines on the patchDBBinaries.sh script. I tried to change on the script instead of 6880880 I put 36195566 and that worked but is that okay or I should have the p6880880_190000_Linux-x86-64 under the one_offs directory ?
 if [[ $patch_zip =~ "6880880" ]]; then
            echo "Removing directory ${ORACLE_HOME}/OPatch";
            rm -rf "${ORACLE_HOME}"/OPatch;
            echo "Unzipping OPatch archive ${patch_zip} to ${ORACLE_HOME}";
            unzip -qo "$patch_zip" -d "$ORACLE_HOME";

**Comment by eyaneylii** [comment]
@yunus-qureshi @aditya059 any updates please

**Comment by yunus-qureshi** [comment]
@eyaneylii 6880880 goes under the oneoffs directory

**Comment by ZhangHJ1002** [comment]
11

**Comment by eyaneylii** [comment]
@yunus-qureshi Thank you for you're response but what I'm trying to say is : 
when I changed on the script the 6880880 with the new 36195566 it worked okay and the image was built so my questions are
> is the changes I made okay or not ?
> is it necessary to bring the 6880880 patch and not to change on the script ?
