### ISSUE TITLE
Support for pre-db for version 12.1.0.2 and 12.2.0.1

### ISSUE THREAD

**Issue by vkadam** [oracle/docker-images#2827]
Pre-db docker image support using any [BASE_IMAGE](https://github.com/oracle/docker-images/blob/5d3230646f5a1a954b6990a27d8e90f652750b0c/OracleDatabase/SingleInstance/extensions/prebuiltdb/Dockerfile#L42), versions like [19.3.0](url), [21.3.0](https://github.com/oracle/docker-images/blob/5d3230646f5a1a954b6990a27d8e90f652750b0c/OracleDatabase/SingleInstance/dockerfiles/21.3.0/runOracle.sh#L331) and [23.4.0](https://github.com/oracle/docker-images/blob/5d3230646f5a1a954b6990a27d8e90f652750b0c/OracleDatabase/SingleInstance/dockerfiles/23.4.0/runOracle.sh#L344) do support nowait parameter which is passed from pre-db dockerfile.

Issue is for versions [12.1.0.2](https://github.com/oracle/docker-images/blob/5d3230646f5a1a954b6990a27d8e90f652750b0c/OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/runOracle.sh#L182) and [12.2.0.1](https://github.com/oracle/docker-images/blob/5d3230646f5a1a954b6990a27d8e90f652750b0c/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/runOracle.sh#L182) dockerfile which do NOT honor nowait parameter passed from pre-db.

**Comment by yunus-qureshi** [comment]
That extn is not supported for versions prior to 19.3.0

**Comment by vkadam** [comment]
We were able to adjust the runOracle.sh file similar to 19+ version and it's working for 12.1.0.2 and 12.2.0.1.
Was planning to send the PR for same, shall I proceed?
