### ISSUE TITLE
Image build fails: /tmp/OraInstall2017-02-17_01-08-11PM/jdk/jre/lib/rt.jar: error reading zip file

### ISSUE THREAD

**Issue by m2rdikas** [oracle/docker-images#283]
Trying to build image and first i get this rt.jar problem, and in the end
/opt/oracle/install/installDBBinaries.sh: line 55: /usr/bin/rm: Input/output error
Removing intermediate container b1c3be36cfd3
The command '/bin/sh -c $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE EE' returned a non-zero code: 126
There was an error building the image.

**Comment by gvenzl** [comment]
Can you please provide the entire build log. Looks like that the `rm` Unix command had an I/O error.

**Comment by m2rdikas** [comment]
Did not manage to repeat same error, but still fails.
Build log is here:
  inflating: database/install/.oui
Starting Oracle Universal Installer...

Checking Temp space: must be greater than 500 MB.   Actual 22425 MB    Passed
Checking swap space: must be greater than 150 MB.   Actual 2047 MB    Passed
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-02-17_07-32-42PM. Please wait ...[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
You can find the log of this install session at:
 /opt/oracle/oraInventory/logs/installActions2017-02-17_07-32-42PM.log
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
/tmp/OraInstall2017-02-17_07-32-42PM/jdk/jre/lib/rt.jar: error reading zip file
Removing intermediate container 54692a25a683
The command '/bin/sh -c $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE EE' returned a non-zero code: 1
There was an error building the image.


Before unpacking no anomalies or etc

**Comment by gvenzl** [comment]
Did the zip file for the software installation unpack entirely? Looks like there is something missing.

**Comment by m2rdikas** [comment]
No errors or anything during unpacking. Downloaded zip from Oracle.

**Comment by gvenzl** [comment]
Can you please provide the entire build log for this. we need to find out which zip file cannot be read.

**Comment by m2rdikas** [comment]
[error_log.txt](https://github.com/oracle/docker-images/files/786770/error_log.txt)

**Comment by gvenzl** [comment]
Hey @m2rdikas, the build log that you have uploaded shows a core dump of the Java VM when running the Oracle Universal Installer:

    #
    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGBUS (0x7) at pc=0x00007f17e915c5e8, pid=31, tid=139740310374144
    #
    # JRE version: 6.0_75-b13
    # Java VM: Java HotSpot(TM) 64-Bit Server VM (20.75-b01 mixed mode linux-amd64 c                          ompressed oops)
    # Problematic frame:
    # V  [libjvm.so+0x73c5e8]
    #
    # Can not save log file, dump to screen..
    #

At this point we will need more information about the Docker environment to figure out what's going on.
Can you please share the output of `docker info` with me and verify that the container has enough space (at least 15GB) and enough memory (at least 2GB of RAM).

**Comment by m2rdikas** [comment]
[docker_info.txt](https://github.com/oracle/docker-images/files/792512/docker_info.txt)

I'm using Oracle Linux 7.2, and docker 1.13.1

Seems that problem is with linux distro and docker, managed to get everything running on OL 7.3

**Comment by gvenzl** [comment]
Thanks @m2rdikas, but I find it strange that OL 7.2 would cause issues with Docker 1.13.1 and OL 7.3 doesn't. @Djelibeybi, are you aware of anything like that in that area?

@m2rdikas, has your problem been solved with upgrading to OL 7.3?

**Comment by Djelibeybi** [comment]
There should be no reason why 7.2 doesn't work and 7.3 does. Though, perhaps a kernel upgrade fixed a hidden issue? Keep in mind this is using the upstream (1.13.1) client and we haven't certified that yet.

**Comment by gvenzl** [comment]
Based on @m2rdikas comment `managed to get everything running on OL 7.3` I close this issue for now until we have further clarification.
