### ISSUE TITLE
Can't start Free image

### ISSUE THREAD

**Issue by matthewtusker** [oracle/docker-images#2840]
I've pulled the free lite image, but it fails to start:

```
docker run --platform linux/amd64 container-registry.oracle.com/database/free:23.4.0.0-lite
Expanding oracle data
/home/oracle
Starting Oracle Net Listener.
Oracle Net Listener started.
Starting Oracle Database instance FREE.
Oracle Database instance FREE started.
Pluggable Database FREEPDB1 opened.

#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
  pga_aggregate_target     = 512M
  diagnostic_dest          = "/opt/oracle"
  enable_pluggable_database= TRUE
2024-07-31T15:51:47.237830+00:00
Oracle instance running with ODM in SGA: Oracle File Server ODM Library, Version: 1.0
Oracle instance running with ODM in SGA: FSDirect ODM Library Version 1.0
Broadcast on commit is enabled and is using Message mode.
--ATTENTION--
USER (ospid: 429): terminating the instance due to ORA error 442
Instance terminated by USER, PID = 429
```

ORA error 442 seems to suggest that more than one instance was started: https://docs.oracle.com/en/error-help/db/ora-00442/?r=23ai

What's going on?

**Comment by mani-mp** [comment]
What machine are you running the container on?
Could you share the /proc/cpuinfo file output

**Comment by matthewtusker** [comment]
I'm on an M1 Mac. I've read that there's issues running the x86_64 image via Docker. I'm currently in the process of trying [this blog post](https://www.dbasolved.com/2022/09/running-x86_64-docker-images-on-mac-m1-max-oracle-database-19c/) which suggests a different container runtime ([Colima](https://github.com/abiosoft/colima)), which may solve the issue.

I'm not totally clear on why Docker Desktop can't run the container, it should be using Rosetta to run the container runtime and the container itself. This is also the first Docker image that I've had any issues running.

**Comment by mani-mp** [comment]
The Oracle Free images are currently not supported on Apple silicon.
You can use the 19.19 Enterprise ARM image on Mac M1:
container-registry.oracle.com/database/enterprise:19.19.0.0

**Comment by matthewtusker** [comment]
I ended up installing Colima to get the free image to work. I'm still surprised it doesn't work with Docker Desktop (I thought the point of the container runtime was that it was a VM, so the host OS shouldn't matter, but it's working for me now so I'm happy to close this ticket off.
