### ISSUE TITLE
cant git clone this repo 

### ISSUE THREAD

**Issue by noxsas** [oracle/docker-images#2841]
I tried testing by cloning my own repo and it worked fine bu it seems that i cant clone this one I get the error:

 git clone https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/helm-charts/oracle-db
Cloning into 'oracle-db'...
fatal: repository 'https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/helm-charts/oracle-db/' not found

what am I doing wrong ?

**Comment by oraclesean** [comment]
Try cloning just to the `SingleInstance`:
```
git clone https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance
```

**Comment by noxsas** [comment]
> Try cloning just to the `SingleInstance`:
> 
> ```
> git clone https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance
> ```

same error maybie its something wrong with my system do I have to configure something ?

**Comment by oraclesean** [comment]
Sorry, my bad. You have to clone to the root of the repository:
```
git clone https://github.com/oracle/docker-images
```

**Comment by noxsas** [comment]
> Sorry, my bad. You have to clone to the root of the repository:
> 
> ```
> git clone https://github.com/oracle/docker-images
> ```

Thanks! 
I colned something I hope everything works fine :D Thanks again!
