### ISSUE TITLE
There was an error building the image

### ISSUE THREAD

**Issue by JeetQiu** [oracle/docker-images#286]
Error occur when run the command "./buildDockerImage.sh -v 12.1.0.2 -e -i" to build the image.
Installing : iputils-20160308-8.el7.x86_64                            110/119Error unpacking rpm package iputils-20160308-8.el7.x86_64

The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE' returned a non-zero code: 1

**Comment by gvenzl** [comment]
Looks like that the RPM install of a package didn't succeed. Can you please share the entire build log?

**Comment by JeetQiu** [comment]
@gvenzl Here you go. 
It looks like the privileged issue to the container file system. I tried to install the package in slim-7 container and rebuild the image base it, then I got "ln: failed to create symbolic link '/home/oracle/setPassword.sh': Permission denied"  after the database software installed.
[output.txt](https://github.com/oracle/docker-images/files/785680/output.txt)

**Comment by gvenzl** [comment]
Thanks @JeetQiu! @Djelibeybi, do you have any clue why iputils fails to install? Is that related to 7-slim or has that nothing to do with it?

**Comment by Djelibeybi** [comment]
From `output.txt` we see the error is `error: unpacking of archive failed on file /usr/bin/ping;58a8640f: cpio: cap_set_file`

Could be an `aufs` bug: https://github.com/docker/docker/issues/6980

But it's also supposed to be fixed upstream: https://github.com/docker/docker/pull/5930

I don't see any `docker info` output. If you're using `aufs`, perhaps try with `btrfs` or `overlay2` (if possible)?

**Comment by Djelibeybi** [comment]
FYI, I just successfully installed `oracle-rdbms-server-12cR1-preinstall` on `oraclelinux:7-slim` using the following Docker setup:

```
$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 28
Server Version: 1.12.6
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-61.1.27.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.14 GiB
Name: <hostname>
ID: 4NBZ:IPAL:OKWW:P4WD:H7VT:SJGT:KQL4:H4X2:EVSR:6W6D:ATKS:M6BC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: <username>
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by JeetQiu** [comment]
Thanks @Djelibeybi . Yes, I'm using AUFS storage driver, I would try to use btrfs or overlay2 and report the result asap.

**Comment by JeetQiu** [comment]
@Djelibeybi @gvenzl  I changed the storage driver to overlay2 and built the image successful, thank you very much for all your kindly help. 
@gvenzl Suggest to add the storage driver requirement to the readme file.

**Comment by drumcircle** [comment]
I'm getting a different error building XE docker.

**Step 5/9 : COPY $INSTALL_FILE_1 $CONFIG_RSP $RUN_FILE $PWD_FILE $INSTALL_DIR/
lstat oracle-xe-11.2.0-1.0.x86_64.rpm.zip: no such file or directory**

sh buildDockerImage.sh -v 11.2.0.2 -x -i
Ignored MD5 checksum.
==========================
DOCKER version:
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
==========================
Building image 'oracle/database:11.2.0.2-xe' ...
Sending build context to Docker daemon 15.36 kB
Step 1/9 : FROM oraclelinux:7-slim
7-slim: Pulling from library/oraclelinux
33a3a5e469a8: Pull complete 
Digest: sha256:f3a78afd456061bb897b9f2b54b568dec3973efccf2b086d602fabb94069fb6d
Status: Downloaded newer image for oraclelinux:7-slim
 ---> f005b5220b05
Step 2/9 : MAINTAINER Gerald Venzl <gerald.venzl@oracle.com>
 ---> Running in c66dbc2ca6b6
 ---> a0e2b16a1a18
Removing intermediate container c66dbc2ca6b6
Step 3/9 : ENV ORACLE_BASE /u01/app/oracle ORACLE_HOME /u01/app/oracle/product/11.2.0/xe ORACLE_SID XE INSTALL_FILE_1 "oracle-xe-11.2.0-1.0.x86_64.rpm.zip" INSTALL_DIR "$HOME/install" CONFIG_RSP "xe.rsp" RUN_FILE "runOracle.sh" PWD_FILE "setPassword.sh"
 ---> Running in 87383d800b6c
 ---> f3e412fb2271
Removing intermediate container 87383d800b6c
Step 4/9 : ENV PATH $ORACLE_HOME/bin:$PATH
 ---> Running in 3ef556358aea
 ---> 010f36e1fefb
Removing intermediate container 3ef556358aea
Step 5/9 : COPY $INSTALL_FILE_1 $CONFIG_RSP $RUN_FILE $PWD_FILE $INSTALL_DIR/
lstat oracle-xe-11.2.0-1.0.x86_64.rpm.zip: no such file or directory
There was an error building the image.

**Comment by gvenzl** [comment]
Looks like you didn't put the zip file into the right folder: `lstat  oracle-xe-11.2.0-1.0.x86_64.rpm.zip: no such file or directory` and you have chosen to ignore the MD5 checksum `-i`. Please copy the zip file into the 11.2.0.2 folder and rerun **without** the `-i` parameter.

**Comment by log2** [comment]
I'm trying to build a Oracle 11g Express image using the provided script. However, what I get is :
----------
This system does not meet the minimum requirements for swap space.  Based on
the amount of physical memory available on the system, Oracle Database 11g
Express Edition requires 2048 MB of swap space. This system has 1022 MB
of swap space.  Configure more swap space on the system and retry the 
installation.
------------
And of course I get, then, the dreaded: There was an error building the image.

Does this problem affects the containerized Alpine Linux image? How can I fix the image characteristics to avoid this issue?

Thanks

**Comment by brunoborges** [comment]
@log2 are you using Alpine instead of Oracle Linux base image?

**Comment by Djelibeybi** [comment]
@log2 please open a new issue. This issue has already been closed.

**Comment by log2** [comment]
@brunoborges sorry for the mistake, I'm not using Alpine Linux, just the usual Linux (Oracle Linux) that comes with Dockerfile.xe, which starts with:

> FROM oraclelinux:7-slim

@Djelibeybi you're right, I'm sorry again, moving to a new issue.

**Comment by tetardv** [comment]
Hi,
I am trying to get an oracle 12.2.0.1 image with docker-images, but I am facing this issue :
" chown: changing ownership of '/opt/oracle/install/linuxx64_12201_database.zip': Value too large for defined data type " on step 7.
I change my docker setup for 
     Storage Driver: overlay2
     Backing Filesystem: extfs
     Supports d_type: true
But I'm still issuing it.

Should I try to reboot my machine for brtfs format system?
Sorry to open back this issue, but I am a bit lost facing it.
Thanks !
