### ISSUE TITLE
Oracle 23ai Free on ARM64

### ISSUE THREAD

**Issue by oehrlis** [oracle/docker-images#2865]
Hi

Now that 23ai Free Edition is also available for ARM64, I did some tests. It turned out that additional libraries were needed to finally create a DB. I don't know if this dependency is not checked in preinstall or is simply new on ARM.

In order to successfully create an image with the config in [oracle/docker-images](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/dockerfiles), the following must be adjusted:

Update [setupLinuxEnv.sh](https://github.com/oracle/docker-images/blob/c03c373bc1ab3a92ff6f3c03b4768988e79e307d/OracleDatabase/SingleInstance/dockerfiles/23.5.0/setupLinuxEnv.sh) and add the statements to install fuse and fortan dependencies (not sure about the fuse requirement any more):

```bash
...
dnf install -y oraclelinux-developer-release-el8 && \
dnf -y install kernel-devel fuse fuse-libs libgfortran && \
dnf -y install oracle-database-preinstall-23ai openssl hostname file expect && \
...
```

Update [buildContainerImage.sh](https://github.com/oracle/docker-images/blob/c03c373bc1ab3a92ff6f3c03b4768988e79e307d/OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh) and add an additional if statment for ARM64 check:

```bash
...
  if { [ "${VERSION}" == "19.3.0" ] && [ "${ENTERPRISE}" -eq 1 ]; }; then
    BUILD_OPTS=("--build-arg" "INSTALL_FILE_1=LINUX.ARM64_1919000_db_home.zip" "${BUILD_OPTS[@]}")
  elif { [ "${VERSION}" == "23.5.0" ] && [ "${FREE}" -eq 1 ]; }; then
    BUILD_OPTS=("--build-arg" "INSTALL_FILE_1=https://download.oracle.com/otn-pub/otn_software/db-free/oracle-database-free-23ai-1.0-1.el8.aarch64.rpm" "${BUILD_OPTS[@]}")
  else
    echo "Currently only 19c enterprise edition or 23ai free edition is supported on ARM64 platform.";
    exit 1;
  fi;
...
```

I'm not sure whether the adjustments are already planned. If necessary, I can also create a pull request for this. For those who can't wait that long, you can make these adjustments locally and then create a 23ai Free Image for ARM with _buildContainerImage.sh_. RPM will be loaded from OTN.

```bash
buildContainerImage.sh -f -v 23.5.0
```

@gvenzl Are the modifications already planned? In any case, the 23ai Free Image for ARM64 is cool :-)

Regards Stefan

**Comment by yunus-qureshi** [comment]
@oehrlis Thanks. This is already being planned.
