### ISSUE TITLE
Issues when using java-8 image due to oraclelinux:7-slim dependency (missing su command)

### ISSUE THREAD

**Issue by saikek** [oracle/docker-images#287]
Commit 41c0eb2f10b6ac53793fa80ee2e8f9cc31c44f34
changes default image to `oraclelinux:7-slim`, which does not have `su` command.
It brakes Weblogic images - since they require to run installer from other user then root.

**Comment by Djelibeybi** [comment]
The WebLogic Dockerfiles were updated in commit https://github.com/oracle/docker-images/commit/ed8015d14e09369ff1dfcefee43fe52ad9d49604 to include `yum -y install util-linux && yum clean all` which adds the `su` command.

**Comment by saikek** [comment]
Can you please also check other versions of Dockerfiles except latest one, for example [12.1.3](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/dockerfiles/12.1.3/Dockerfile.generic)

**Comment by saikek** [comment]
Created pull request  #289
