### ISSUE TITLE
Missing Dockerfile in OracleDatabase/SingleInstance/dockerfiles/23.5.0

### ISSUE THREAD

**Issue by erneu** [oracle/docker-images#2877]
Hi,

I just wanted to build the latest DB Container based on 23.5.0
but actually - the Dockerfile is missing in the Version subfolder.

![image](https://github.com/user-attachments/assets/aa509fe5-bc03-4cd6-88a6-3c181747f1da)

Can you please provide it?

Thanks
Erich

**Comment by erneu** [comment]
Shall I just use it from gvenzl oci-oracle-free ?


https://[raw.githubusercontent.com/gvenzl/oci-oracle-free/refs/heads/main/Dockerfile.23](https://raw.githubusercontent.com/gvenzl/oci-oracle-free/refs/heads/main/Dockerfile.23)

**Comment by yunus-qureshi** [comment]
@erneu It is called Containerfile.free

**Comment by erneu** [comment]
Sorry - mistake on my end.
I didn't add a tag in the commandline for the image,
but the errormessage indicated: "ERROR: Dockerfile. doesn't exist" - that's why I got a wrong idea of "Dockerfile" missing.

It's all fine.
Thanks & Greetz from Vienna
