### ISSUE TITLE
Same domain for Weblogic 12.1.3 fails to start

### ISSUE THREAD

**Issue by Blackburn29** [oracle/docker-images#290]
I am trying to run the 1213-domain example extended on the 12.1.3-developer docker image and I am having some issues...

- The `PRODUCTION_MODE` variable is not being passed correctly to `create-wls-domain` (I bypassed this by just hardcoding the value)
- When trying to log into the console, the server just hangs with out-of-memory exceptions. (I've attempted to increase the JVM memory with no luck)

So I am kind of stuck.
Any help would be greatly appreciated
Thanks!

**Comment by mriccell** [comment]
@Blackburn29 please see #319 corrected the 1213-domain to accept the PRODUCTION_MODE as an ARG

**Comment by philipstaffordwood** [comment]
Managed to start the admin server using the following JVM settings:
`docker run -d -e "USER_MEM_ARGS= -Xms1024m -Xmx2048m -XX:PermSize=512m -XX:MaxPermSize=1024m" --name wlsadmin --hostname wlsadmin -p 7001:7001 1213-domain`

Otherwise it hangs with out of memory exceptions.
