### ISSUE TITLE
ELK stack Logspout make fails

### ISSUE THREAD

**Issue by mikarinneoracle** [oracle/docker-images#292]
Have forked
https://github.com/oracle/docker-images/tree/master/ContainerCloud
to
https://github.com/mikarinneoracle/docker-images

and I’m running make. While Logstash and Kibana are built fine into my Docker-hub, the Logspout gives an error:

..clip..

git clone https://github.com/gorilla/context /go/src/github.com/gorilla/context
cd /go/src/github.com/gorilla/context
git submodule update --init --recursive
cd /go/src/github.com/gorilla/context
git show-ref
cd /go/src/github.com/gorilla/context
git submodule update --init --recursive
Removing intermediate container f491cd640c6d
The command '/bin/sh -c /build.sh' returned a non-zero code: 1
make[1]: *** [image] Error 1

I’m attaching the log for logspout make. Does this work for you? I’m running OSX.
Any idea what’s going wrong ?

The same result if running make under elk or under logspout dir.

**Comment by mikarinneoracle** [comment]
Error log for make under logspout dir
[error.log.txt](https://github.com/oracle/docker-images/files/796327/error.log.txt)

**Comment by karthequian** [comment]
@mikarinneoracle sorry about that! Pushing a fix for it today.

**Comment by mikarinneoracle** [comment]
Many thanks, the make worked now.

 

Mika

**Comment by karthequian** [comment]
Thanks for verifying @mikarinneoracle! Also, really cool container work from you!!
