### ISSUE TITLE
separate yum installs from oracle install in -xe

### ISSUE THREAD

**Issue by xenoterracide** [oracle/docker-images#293]
```
RUN yum -y install unzip libaio bc initscripts net-tools openssl && \
    yum clean all 
```

the subsequent oracle installation should be a separate step I think, as it doesn't appear to remove any of these. That way if this succeeds you don't have to do it again if the oracle install fails

**Comment by gvenzl** [comment]
I just tested this out and I'm not sure whether this is practical. Agreed, the layer cannot be reused if the Oracle install fails but just by making it a separate step, it adds another 11 MB to the image size:

    [root@localhost dockerfiles]# docker images
    REPOSITORY                TAG                 IMAGE ID            CREATED              SIZE
    oracle/database           11.2.0.2-xe         816c6eae214f        4 seconds ago        1.135 GB
    oracle/database           11.2.0.2-xe.org     97a2745bf703        About a minute ago   1.124 GB

    [root@localhost dockerfiles]# docker history oracle/database:11.2.0.2-xe.org
    IMAGE               CREATED              CREATED BY                                      SIZE                COMMENT
    97a2745bf703        About a minute ago   /bin/sh -c #(nop)  CMD ["/bin/sh" "-c" "$ORAC   0 B
    86ee1e74a47a        About a minute ago   /bin/sh -c #(nop)  EXPOSE 1521/tcp 8080/tcp     0 B
    961f514d7839        2 minutes ago        /bin/sh -c #(nop)  VOLUME [/u01/app/oracle/or   0 B
    439324835ac3        2 minutes ago        |2 http_proxy=proxy:80 http                     694.1 MB
    cfe153dd1aab        2 minutes ago        /bin/sh -c #(nop) COPY multi:87df835148e73ca1   315.9 MB
    e868b8c75083        2 minutes ago        /bin/sh -c #(nop)  ENV PATH=/u01/app/oracle/p   0 B
    a5597e588852        2 minutes ago        /bin/sh -c #(nop)  ENV ORACLE_BASE=/u01/app/o   0 B
    d4936b42939e        3 minutes ago        /bin/sh -c #(nop)  MAINTAINER Gerald Venzl <g   0 B
    a1f54f65f955        11 days ago          /bin/sh -c #(nop)  CMD ["/bin/bash"]            0 B
    <missing>           11 days ago          /bin/sh -c #(nop) ADD file:972a2223d898e2d158   114.3 MB
    <missing>           6 months ago         /bin/sh -c #(nop)  MAINTAINER Oracle Linux Pr   0 B

    [root@localhost dockerfiles]# docker history oracle/database:11.2.0.2-xe
    IMAGE               CREATED              CREATED BY                                      SIZE                COMMENT
    816c6eae214f        20 seconds ago       /bin/sh -c #(nop)  CMD ["/bin/sh" "-c" "$ORAC   0 B
    ab9ed5d2a287        21 seconds ago       /bin/sh -c #(nop)  EXPOSE 1521/tcp 8080/tcp     0 B
    c3c1a13b954c        23 seconds ago       /bin/sh -c #(nop)  VOLUME [/u01/app/oracle/or   0 B
    66d8b4604a07        25 seconds ago       |2 http_proxy=proxy:80 http                     602.7 MB
    c39e1f81a4bd        41 seconds ago       |2 http_proxy=proxy:80 http                     101.9 MB
    4b55984d515b        About a minute ago   /bin/sh -c #(nop) COPY multi:87df835148e73ca1   315.9 MB
    47fb18613a3c        About a minute ago   /bin/sh -c #(nop)  ENV PATH=/u01/app/oracle/p   0 B
    1715d6f77503        About a minute ago   /bin/sh -c #(nop)  ENV ORACLE_BASE=/u01/app/o   0 B
    3079c4fa27cc        About a minute ago   /bin/sh -c #(nop)  MAINTAINER Gerald Venzl <g   0 B
    a1f54f65f955        11 days ago          /bin/sh -c #(nop)  CMD ["/bin/bash"]            0 B
    <missing>           11 days ago          /bin/sh -c #(nop) ADD file:972a2223d898e2d158   114.3 MB
    <missing>           6 months ago         /bin/sh -c #(nop)  MAINTAINER Oracle Linux Pr   0 B

I rather prefer to optimize the image for storage and runtime rather than for build time. Hopefully Docker 1.13 will change the game and we can be cleaner with `RUN` steps, etc. but for now I prefer having a smaller image size overall.

**Comment by xenoterracide** [comment]
wow, the layer itself adds that much? seems strange unless I'm missing something ran into this while dealing with #294

**Comment by gvenzl** [comment]
I think so, I literally just added another RUN instruction and the rest stayed the same.

**Comment by gvenzl** [comment]
Closing this issue for now as the additional layer adds more MBs and we prefer to optimize the image for runtime rather than build time.
