### ISSUE TITLE
There is not enough space available in the docker container when creating a 12.2 image

### ISSUE THREAD

**Issue by robertofpaf** [oracle/docker-images#310]
Hello,

I'm trying to create a docker image with the 12.2.0.1 enterprise database and it failed in this way:

```
Step 7/16 : RUN chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE
 ---> Running in 3c880c93bde4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
checkSpace.sh: ERROR - There is not enough space available in the docker container.
checkSpace.sh: The container needs at least 15 GB available.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Removing intermediate container 3c880c93bde4
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE' returned a non-zero code: 1
There was an error building the image.
```

What I did was cloning this repository, copying the linuxx64_12201_database.zip file I just downloaded into OracleDatabase/dockerfiles/12.2.0.1 and run `./buildDockerImage.sh -v 12.2.0.1 -e` from the OracleDatabase/dockerfiles directory.

How do I get out of this? Any help would be appreciated!

**Comment by tortoise4race** [comment]
it failed in the same error code

**Comment by PeeZu** [comment]
Hello,

Depending on your Docker storage, container allocated space is restricted by default to 10GB.

ref: https://blogs.oracle.com/developer/entry/creating_and_oracle_database_docker

**Comment by robertofpaf** [comment]
Yes, giving more space to the baseline worked. I would suggest that this requirement would be added to the README.md in the repository as it's a very crucial one.

**Comment by lukaseder** [comment]
Running into this problem as well... I solved it before (not like in the [referenced article above](https://blogs.oracle.com/developer/creating-an-oracle-database-docker-image), which doesn't seem to apply to docker on windows), but I forgot again how to solve this.

Couldn't this be done automatically? // @gvenzl

**Comment by lukaseder** [comment]
OK, found my original issue again: https://github.com/oracle/docker-images/issues/124.

My trick there still works also for this error here:

```
$ docker-machine create --driver virtualbox --virtualbox-disk-size "40000" --virtualbox-memory 2048 default
```

**Comment by gvenzl** [comment]
Hi @lukaseder, unfortunately there is no way inside a container to increase the storage capacity. Furthermore, it depends on which storage driver you are using. For example, the btrfs driver doesn't have the concept of a base image size and just uses all available space.
And, last but not least, changing settings like the base image size require to throw away all images and volumes and start again in order for the change to be effective. Something that should rather not be automated away to keep user satisfaction high.

**Comment by lukaseder** [comment]
You're right @gvenzl, yet a short section "caveats / workarounds / troubleshooting" in the readme would definitely be helpful :) When trying to look for my fix where I changed the base image size, I found about 20 other issues here on GitHub where similar problems were discussed, and none of the suggested solutions worked for me...

Alternatively, there could be a link to a troubleshooting page that is displayed with the error message in `checkSpace.sh`, what do you think?

**Comment by gvenzl** [comment]
And that is exactly the problem. Based on the storage driver and environment there are many solutions to your problem. Until now I couldn't find a common pattern that would make sense to document in the ReadMe, it would just be a long list of "Maybe it's this, maybe it's that".

A troubleshooting page is a more interesting, I could use that for more than just the space check one and users could start adding their own problems into the mix when they find a solution. Will explore that idea, thanks a lot!

**Comment by gvenzl** [comment]
There we go: PR #513

**Comment by stiancognite** [comment]
In case it helps someone: I was able to get around this [by following this](https://gist.github.com/stefanfoulis/5bd226b25fa0d4baedc4803fc002829e#file-docker_for_mac_disk_default_size-md) on my macOS High Sierra.

**Comment by RakeshNagarajan** [comment]
Remove the old image (Oracle-linux)
REstart the docker

Since the old image will holds the info of previous dm.base size. this can't be updated. so please pull the new latest image and work.


This worked for me
