### ISSUE TITLE
Oracle APEX Image

### ISSUE THREAD

**Issue by michael-simons** [oracle/docker-images#322]
Hello everybody,

would there be interest in having an Oracle APEX image based on 12.2? 
Thanks,
Michael.

**Comment by gvenzl** [comment]
Yes, we would love to have contributions from the community!
The APEX image should be using one of the database images as a base image.

**Comment by michael-simons** [comment]
Thanks :) Will have time for it next month. One difficulty I see is that ORDS is very interactive to install.

**Comment by gvenzl** [comment]
Actually, that has changed in recent versions and ORDS now allows installing via a parameter/config file. However, we would like to keep ORDS and APEX as separate Docker containers as ORDS does not necessarily need APEX to run and vice versa. Ideally you could provide us with an image that builds upon the latest database image and installs and configures APEX. If you feel like that ORDS really should be included in that image as well then we should further clarify on the requirements.

**Comment by avindra** [comment]
Is there a way we can remove APEX? What's the config file we have to tweak to remove components from the installation?

**Comment by gvenzl** [comment]
The APEX binaries are already removed from the Oracle home. The default seed database comes with a variety or different components, you can remove them manually by using the `setup` custom scripts facility, if you like.

**Comment by nochmu** [comment]
Not exactly an APEX image, but you could use it in combination with the database image: 
https://github.com/nochmu/apex-service
