### ISSUE TITLE
Coherence in kubernetes

### ISSUE THREAD

**Issue by shubhamitc** [oracle/docker-images#325]
Hi , How do you recommend to deploy coherence in kubernetes cluster as only unicasting is supported and pods/containers can die anytime in the process. They are immutable unit so using their ips is not a good idea. 

We tried to setup up AddressProvider but i am not sure if that is supported by cache-config. Any help will be appreciated.

**Comment by mriccell** [comment]
@shubhamitc please make reference to the blog http://thegridman.com/coherence/oracle-coherence-on-docker/ which refers how to deal with the multicast limitation in Coherence.
