### ISSUE TITLE
buildDockerImage.sh fails on 11.2.0.2 xe  (rm: cannot remove '/install': Directory not empty)  

### ISSUE THREAD

**Issue by lurodrig** [oracle/docker-images#326]
Hello there,

First thanks Gerald Venzl for this initiative, having the possibility of just running your Oracle Dabatabase without worrying about all the bits and pieces of the installation is fantastic!

However it is not working for me, but probably I am missing something...

My host:

CentOS Linux release 7.2.1511 (Core)

Linux version 3.10.0-327.10.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Tue Feb 16 17:03:50 UTC 2016

 The problem: trying...

`./buildDockerImage.sh -v 11.2.0.2 -x -i  `

...I get:

    sysctl: setting key "kernel.sem": Read-only file system  
    /var/tmp/rpm-tmp.BMFGBE: line 257: [: 18446744073692774399: integer expression expected  
    /var/tmp/rpm-tmp.BMFGBE: line 271: [: 18446744073692774399: integer expression expected  
    sysctl: setting key "fs.file-max": Read-only file system  
    Executing post-install steps...  
    You must run '/etc/init.d/oracle-xe configure' as the root user to configure the database.  
      
```
rm: cannot remove '/install': Directory not empty  
Removing intermediate container ad997f0e8856  
The command '/bin/sh -c yum -y install unzip libaio bc initscripts net-tools openssl &&     yum clean all &&     cd $INSTALL_DIR &&     unzip $INSTALL_FILE_1 &&     rm $INSTALL_FILE_1 &&        rpm -i Disk1/*.rpm &&        mkdir $ORACLE_BASE/oradata &&     chown -R oracle:dba $ORACLE_BASE &&     mv $INSTALL_DIR/$CONFIG_RSP $ORACLE_BASE/ &&     mv $INSTALL_DIR/$RUN_FILE $ORACLE_BASE/ &&     mv $INSTALL_DIR/$PWD_FILE $ORACLE_BASE/ &&     ln -s $ORACLE_BASE/$PWD_FILE / &&     cd $HOME &&     rm -rf $INSTALL_DIR &&     chmod u+x $ORACLE_BASE/$RUN_FILE &&     chmod u+x $ORACLE_BASE/$PWD_FILE' returned a non-zero code: 1  
There was an error building the image. 
``` 

In the dockerfiles folder I have:

```
[dockerfiles]$ ls -alrt 11.2.0.2/  
total 308516  
-rw-r--r--. 1 lurodrig it 315891481 Mar 15 16:33 oracle-xe-11.2.0-1.0.x86_64.rpm.zip  
-rw-r--r--. 1 lurodrig it      4661 Mar 15 16:35 runOracle.sh  
-rw-r--r--. 1 lurodrig it      2421 Mar 15 16:35 Dockerfile.xe  
-rw-r--r--. 1 lurodrig it        70 Mar 15 16:35 Checksum.xe  
-rw-r--r--. 1 lurodrig it      2943 Mar 15 16:35 xe.rsp  
-rw-r--r--. 1 lurodrig it       193 Mar 15 16:35 setPassword.sh
```

I know that this rpm  is not exactly the same version as the one stated in the project. However I can see that is the one used in the Dockerfile.xe: 
```

    # Environment variables required for this build (do NOT change)  
    # -------------------------------------------------------------  
    ENV ORACLE_BASE=/u01/app/oracle \  
        ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe \  
        ORACLE_SID=XE \  
        INSTALL_FILE_1="oracle-xe-11.2.0-1.0.x86_64.rpm.zip" \  
        INSTALL_DIR="$HOME/install" \  
        CONFIG_RSP="xe.rsp" \  
        RUN_FILE="runOracle.sh" \  
        PWD_FILE="setPassword.sh" 
``` 

Am I missing something?

Thanks in advance,

Luis

**Comment by gvenzl** [comment]
Hi @lurodrig, you are very welcome!

Seems like the build is failing because of `rm: cannot remove '/install': Directory not empty `. The errors stated above (Read-Only file system, etc) are expected and won't break the build. Just the fact that the rpm sets some settings which aren't allowed inside the container but it won't stop the install.
The weird part is that the command executed is `rm -rf $INSTALL_DIR` which shouldn't prompt this error, at least not on Oracle Linux (-f forcing the deletion).
Unfortunately I don't have a CentOS environment which limits my capabilities to debug this.

The other interesting piece is that `$HOME` doesn't seem to be set on CentOS either. $INSTALL_DIR points to `INSTALL_DIR="$HOME/install"` which turns out to become `/install`. I wonder whether that has anything to do with it.

**Comment by lurodrig** [comment]
Hello Gerald,

Thank you for your (quick!) answer!

I do believe that I can not see the forest but the trees. Trying with something like this:

```
FROM oraclelinux:7-slim

MAINTAINER batman <batman@cern.ch>

RUN echo "HOME: $HOME"

ENV INSTALL_FILE_1="dummy.file" \
        INSTALL_DIR="/root/install"

COPY $INSTALL_FILE_1 $INSTALL_DIR/

RUN ls -alrt $INSTALL_DIR

RUN rm -fr $INSTALL_DIR

CMD ls -alrt $INSTALL_DIR
```

I am getting the same error (I hardcode the install_dir path instead of using $HOME):

```
Step 7/8 : RUN rm -fr $INSTALL_DIR
 ---> Running in 13e8d1a7f434
rm: cannot remove '/root/install': Directory not empty
```
Investigating a bit more it seems that this can be a kernel issue, see: https://github.com/docker/docker/issues/27214

Thanks for your efforts and sorry for the noise

Luis

**Comment by lurodrig** [comment]
Looks like a kernel issue. I will upgrade my box (Centos 7.3) and retry.

**Comment by gvenzl** [comment]
Interesting, is issue #327 also related to that you think?

**Comment by lurodrig** [comment]
Hello @gvenzl, 

Sorry for the delay on my response.

mmm, yes, I guess that it can be related. I am coming back to this issue. I will update the issue when I have more results.

Thanks!

Luis

**Comment by lurodrig** [comment]
OK, from a freshly installed box: CentOS Linux release 7.3.1611 (Core) 

Now I am getting:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
checkSpace.sh: ERROR - There is not enough space available in the docker container.
checkSpace.sh: The container needs at least 15 GB available.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I am having a look at  [Resizing Docker containers with the Device Mapper plugin](https://jpetazzo.github.io/2014/01/29/docker-device-mapper-resize/). The _Wipe out /var/lib/docker_ looks quite brutal, but live's hard :)

Cheers,

Luis

**Comment by lurodrig** [comment]
After applying the resizing:
` Data Space Total: 107.4 GB`
However running the `./buildDockerImage.sh -v 12.2.0.1 -s -i`
```
ApplyLayer exit status 1 stdout:  stderr: unexpected EOF
There was an error building the image.
```
Cheers,

Luis
