### ISSUE TITLE
buildDockerImage.sh fails with 12.2.0.1 se (chown: changing ownership of '/opt/oracle/install/linuxx64_12201_database.zip': File too large)  

### ISSUE THREAD

**Issue by lurodrig** [oracle/docker-images#327]
Hello there,

It is me again , now trying to build Oracle Database 12.2.0.1 se, you can have a look at  buildDockerImage from https://github.com/oracle/docker-images fails with 11.2.0.2 xe

Same host:

CentOS Linux release 7.2.1511 (Core)
Linux version 3.10.0-327.10.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Tue Feb 16 17:03:50 UTC 2016

Now trying...

`./buildDockerImage.sh -v 12.2.0.1 -s -i  `

I get:
```

Complete!  
Loaded plugins: ovl  
Cleaning repos: ol7_UEKR4 ol7_latest  
Cleaning up everything  
chown: changing ownership of '/opt/oracle/install/linuxx64_12201_database.zip': File too large  
Removing intermediate container 6622686f4e18  
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE' returned a non-zero code: 1  
There was an error building the image.
``` 

Am I missing something? Apart that perhaps I can try to rename the binaries file to something shorter...

Thanks in advance,

Luis

**Comment by gvenzl** [comment]
Hi @lurodrig, I don't think that it has to do with the filename but rather with the file size. Although I have never seen `chown` failing with such an error. Perhaps this is due to some file system limitation? Which fs are you using inside your container?

**Comment by lurodrig** [comment]
Hello @gvenzl. Yes, you are right, I've just realized that it was nothing to do with the file name, I was very naive... :)

Abot the fs (thanks, good hint!):  

The host machine (Centos7):

```
[dockerfiles]$ df -T -h /dev/mapper/cc_xxxx-home
Filesystem                            Type   Size    Used   Avail   Use%   Mounted on
/dev/mapper/cc_xxxx-home  xfs      94G   11G     84G    12%      /home
```

And _inside the container_ (not 100% sure if this is you are asking me...): 

```
Step 7/17 : RUN df -T -h
 ---> Running in f80559f3fc3b
Filesystem                    Type     Size  Used Avail Use% Mounted on
overlay                              overlay   50G   34G   17G  67% /
tmpfs                                 tmpfs    2.3G     0  2.3G   0% /dev
tmpfs                                 tmpfs    2.3G     0  2.3G   0% /sys/fs/cgroup
/dev/mapper/cc_xxxx-root xfs       50G   34G   17G  67% /etc/hosts
shm                                   tmpfs     64M     0   64M   0% /dev/shm
tmpfs                                 tmpfs    2.3G     0  2.3G   0% /sys/firmware
```
Thanks in advance,

Luis

**Comment by gvenzl** [comment]
This looks good to me. @Djelibeybi, do you have any idea why `chown` would fail with this error?

**Comment by sniper66** [comment]
I have the same problem... Filesystem xfs on OL7.3...
$: chown oracle:dba linuxx64_12201_database.zip
chown: changing ownership of 'linuxx64_12201_database.zip': File too large
bash-4.2# df -hT (Inside the container...)
Filesystem          Type     Size  Used Avail Use% Mounted on
overlay             overlay   41G   17G   25G  41% /
tmpfs               tmpfs    496M     0  496M   0% /dev
tmpfs               tmpfs    496M     0  496M   0% /sys/fs/cgroup
/dev/mapper/ol-root xfs       41G   17G   25G  41% /etc/hosts
shm                 tmpfs     64M     0   64M   0% /dev/shm
tmpfs               tmpfs    496M     0  496M   0% /sys/firmware

**Comment by chrisguoado** [comment]
@sniper66 @gvenzl I'm not sure the root cause of this issue, it looks there's sufficient disk space. While we definitely should avoid `chown`'ing large files like `linuxx64_12201_database.zip` during the image building. `chown` actually adds new image layer thus makes the built image that file size larger.

**Comment by sniper66** [comment]
@chrisguoado Thank you for your reply...
I can´t do anything with that file...

Just take a look here:
bash-4.2# chmod 777 linuxx64_12201_database.zip
chmod: changing permissions of 'linuxx64_12201_database.zip': File too large
bash-4.2# mv linuxx64_12201_database.zip linuxx64_12201_database.zip_test
mv: cannot move 'linuxx64_12201_database.zip' to 'linuxx64_12201_database.zip_test': File too large
bash-4.2# cat /etc/oracle-release
Oracle Linux Server release 7.3
bash-4.2# uname -a
Linux ad0cb32cda6c 4.1.12-61.1.28.el7uek.x86_64 #2 SMP Thu Feb 23 19:55:12 PST 2017 x86_64 x86_64 x86_64 GNU/Linux

On the host OL7.3 I can do anything...

**Comment by chrisguoado** [comment]
Yes, it certainly only relates to the operations in the container. But I guess you should be able to unzip the file, and then remove it. If so, it looks like there's something wrong or limitation with the driver handling the (xfs) FS.

**Comment by sniper66** [comment]
Yes, unzipping and removing works in the container...

**Comment by sniper66** [comment]
Does anyone know which limitations that could be???

**Comment by lurodrig** [comment]
I do believe that this issue is related with #326 

@sniper66 perhaps you could try `docker info` and look for `Data Space Total`

You can have a look at https://jpetazzo.github.io/2014/01/29/docker-device-mapper-resize/

Cheers,

Luis

**Comment by sniper66** [comment]
I already changed it to overlay2...

Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: false

**Comment by lurodrig** [comment]
Hello there,

Extending the docker **Base Device Size** to 20GB did the trick for me. I configured it via `/etc/docker/daemon.json` See _**Configure the Docker daemon with specific devicemapper options.**_ on https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production

My /etc/docker/daemon.json looks like:

```
{
    "live-restore": true,
    "storage-opts": ["dm.basesize=20G"]
}
```

Hope it helps,

Luis

ps: thanks for all your responses

**Comment by gvenzl** [comment]
Another user came across a Docker bug with CentOS 7 and overlayfs, see issue #317. I believe that this is related to that.

Also the Docker documentation recommends to use overlay2: 

[Docker and OverlayFS in practice](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/)
> Since version 1.12, Docker also provides overlay2 storage driver which is much more efficient than overlay in terms of inode utilization. The overlay2 driver is only compatible with Linux kernel 4.0 and later.

Was it switching to overlay2 that fixed the issue?

**Comment by lurodrig** [comment]
Hello Gerald,

Sorry, perhaps I was not very clear. Which fixed the issue for me was to set **dm.basesize** to **20GB**.

Cheers,

Luis

**Comment by gvenzl** [comment]
Thanks @lurodrig, that is very strange to me. Why would not having enough space throw an error with `chown File too large`. Anyway, glad that the issue is solved!

Thanks!

**Comment by bjarteb** [comment]
Hi,

I don't think this is fixed. 

I am running OL 7.3 and I am still getting: 
chown: changing ownership of '/opt/oracle/install/linuxx64_12201_database.zip': File too large

```
docker info:
Server Version: 17.03.1-ce
Storage Driver: overlay2
Backing Filesystem: xfs
Supports d_type: true
Native Overlay Diff: false
```

The overlay2 does not have the option "storage-opts"

12.1.0.2 works fine.

I am not sure what to try next since overlay2 is the recommended storage driver.

Thanks,

Bjarte

**Comment by ivanmemruk** [comment]
Hi, seeing the same issue here with CentOS and overlay2, "file too large" when opening a 2.3G tablespace file while starting an Oracle database.
