### ISSUE TITLE
Oracle-xe 11g - run sql scripts at startup time

### ISSUE THREAD

**Issue by nicolimo86** [oracle/docker-images#329]
Hi all,
is there any way to provide a .sql script that runs at startup time?
Like a folder where I copy my .sql and it gets ran as soon as my container starts. 

Something similar to this:
docker run -d --shm-size=1g -p 1521:1521 -v **/local-initdb/init.sql:/etc/entrypoint-initdb.d** oracle/docker-oracle-xe-11g

I've also tried the above example but doesn't work.

**Comment by gvenzl** [comment]
Hi @nicolimo86, we do not have such a features. What kind of script would you like to run at startup time?

**Comment by nicolimo86** [comment]
@gvenzl It is a script that creates the first user in the DB and grants him all the necessary permissions.

**Comment by gvenzl** [comment]
Thanks @nicolimo86, what's wrong with just running the script once the database has been created?

**Comment by nicolimo86** [comment]
@gvenzl yeah exactly, all my team has to run it manually.

**Comment by gvenzl** [comment]
Any reason why this isn't run once and then you share the data volume with your team? That would also save time as the DB doesn't need to be created anymore.

Another way would be to extend the image by building your own on top. You just need to call the very same runOracle.sh script to get the DB up and running and then you can do anything to the DB as you wish.

And yet another possibility would be to create the DB with your scripts at image build time, similar approach to the above but you will have to remove the `VOLUME` instruction in the build file. 

Thx,

**Comment by nicolimo86** [comment]
@gvenzl thanks for your proposals, I think any of them can easily solve my problem (with a bit of googling here and there)!

**Comment by gvenzl** [comment]
@nicolimo86, you are very welcome! There is a sample for that use case under [OracleDatabase/samples/prebuiltdb](https://github.com/oracle/docker-images/tree/master/OracleDatabase/samples/prebuiltdb). Let me know how you get on and please reopen the ticket if you run into any issues.
