### ISSUE TITLE
Create multiple database on single docker image

### ISSUE THREAD

**Issue by rajeshpasupathy** [oracle/docker-images#331]
Hi,
Appreciate your valued posts. We are looking for multiple database instance on single docker image, can we create more that one database using "docker run" command after creating docker image.

Thanks

**Comment by Djelibeybi** [comment]
This entirely defeats the purpose of Docker (in my opinion). Why don't you just create multiple Docker containers?

**Comment by brunoborges** [comment]
I agree with @Djelibeybi. We design these Dockerfiles following best practices. Your use case goes against them.

**Comment by gvenzl** [comment]
Agreed! What is the use case for running multiple databases inside one container. Can you shed some light on that for us, please?

**Comment by brunoborges** [comment]
@rajeshpasupathy, mind to provide more details on your use case?

**Comment by gvenzl** [comment]
Closing this due to lack of response.
