### ISSUE TITLE
Oracle XE ORA-12547 TNS lost contact

### ISSUE THREAD

**Issue by oeMoe** [oracle/docker-images#332]
I got a ORA-12547 TNS lost contact when i tried to connect with sqlplus after building and running Oracle XE.
```$ docker exec -ti oraclexe sqlplus sys as sysdba
SQL*Plus: Release 11.2.0.2.0 Production on Fri Mar 24 05:53:11 2017
Copyright (c) 1982, 2011, Oracle.  All rights reserved.
Enter password:
ERROR:
ORA-12547: TNS:lost contact
Enter user-name:
```
Googled this and a common solution/reason for this is missing permission on files in the $ORACLE_HOME/bin folder. Checked my container:
```$ docker exec -ti oraclexe /bin/bash
bash-4.2$ ls -l $ORACLE_HOME/bin/oracle
-rwxr-x--x 1 oracle dba 165700472 Aug 29  2011 /u01/app/oracle/product/11.2.0/xe/bin/oracle
```
It is indeed missing the suid bit.
tried setting the suid bit on $ORACLE_HOME/bin/oracle
```bash-4.2# chmod u+s $ORACLE_HOME/bin/oracle```

Now sqlplus works

However the setting of suid is not persisted when the container is stopped.
Need to add this to the Dockerfile and rebuild image
..OracleDatabase/dockerfiles/11.2.0.2/Dockerfile.xe
```
chmod u+x $ORACLE_BASE/$PWD_FILE && \
chmod u+s $ORACLE_HOME/bin/oracle

VOLUME ["$ORACLE_BASE/oradata"]
EXPOSE 1521 8080
```

Is this just me?
I´m running on a mac osx Sierra
Docker version 17.03.0-ce, build 60ccb22

**Comment by gvenzl** [comment]
Hi @oeMoe, can you please share how you call SQL*Plus? Is it just `sqlplus / as sysdba`? I think the issue is related with the `root` user which is the user to be logged into the container. However, the database is running under the `oracle` user and therefore `sqlplus / as sysdba` cannot attach to the process.
However, you should be able to log on using a connection string, e.g.: `sqlplus sys/LetsDocker@//localhost:1521/XE as sysdba`

**Comment by oeMoe** [comment]
My mistake, used the wrong connection string. I am now able to connect to the database without having set the suid bit.

Thanks

**Comment by President-Temitope** [comment]
> Hi @oeMoe, can you please share how you call SQL*Plus? Is it just `sqlplus / as sysdba`? I think the issue is related with the `root` user which is the user to be logged into the container. However, the database is running under the `oracle` user and therefore `sqlplus / as sysdba` cannot attach to the process.
> However, you should be able to log on using a connection string, e.g.: `sqlplus sys/LetsDocker@//localhost:1521/XE as sysdba`

I'm having same issue and i'm not getting this solution 
what do you mean by connection string ?
