### ISSUE TITLE
Weblogic 12.2.1 AppDeploy Static Deployment Error

### ISSUE THREAD

**Issue by emregozen2** [oracle/docker-images#335]
Hi,

I have a problem with Weblogic 12.2.1 appdeploy sample,
When I try to deploy sample application, it is OK,
but when I try my application, deployment fails and the error in the log file is,

weblogic.management.DeploymentException: [Deployer:149268]Static deployment of non-versioned application "myapp" failed due to a version being defined in its manifest file.
	at weblogic.deploy.internal.targetserver.AppDeployment.staticDeployValidationForNonVersion(AppDeployment.java:200)
	at weblogic.deploy.internal.targetserver.AppDeployment.prepare(AppDeployment.java:113)
	at weblogic.management.deploy.internal.DeploymentAdapter$1.doPrepare(DeploymentAdapter.java:41)
	at weblogic.management.deploy.internal.DeploymentAdapter.prepare(DeploymentAdapter.java:193)
	at weblogic.management.deploy.internal.AppTransition$1.transitionApp(AppTransition.java:31)
	Truncated. see log file for complete stacktrace
> 

My application has its own manifest file inside EAR and WAR, it is,

Manifest-Version: 1.0
Weblogic-Application-Version: 4.1.23
SVN-Revision-Number: 45084
Archiver-Version: Plexus Archiver
Built-By: root
app-builddate: 20170329-0859
Created-By: Apache Maven 3.0.5
Build-Jdk: 1.8.0_66
app-version: 4.1.23

It looks valid and there is no reason for weblogic not being able to read manifest file, as the deployment succeed when I try to deploy application from admin console,

What might cause this, have you got any idea?

Thanks in advance.

**Comment by mriccell** [comment]
@emregozen2 are you deploying your app to the cluster?  Do you mind sharing your app and the WLST script your use to deploy?

**Comment by emregozen2** [comment]
Hi,
Actually I've tried both deploy the package to another cluster or AdminServer, they gave the same error above,
I face difficulties for only versioned apps, unversioned apps can be deployed with offline mode very well,
You can find my appdeploy file inside attachments,
[app-deploy.py.txt](https://github.com/oracle/docker-images/files/893294/app-deploy.py.txt)

For application package, I kindly expect your understanding as it's an enterprise application used by the company I work for, I will try to create a sample application which causes same error, at the same time, I will be very glad if you try any versioned application with your app-deploy.py script and share the results.

Thanks in advance.

**Comment by emregozen2** [comment]
Hi, 

I created sample project which contains version information inside its manifest file. It is successfully deployed by console, but failed with your offline deployment wlst script by the same reason I mentioned in my first entry(Static deployment of nonversioned app ....)

I tried scripts inside this,
https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/1221-domain

You can find application package(war) inside attachments,

I'm looking forward to hear from you!
Thanks in advance

[myapp-frontend-0.0.3.war.zip](https://github.com/oracle/docker-images/files/896028/myapp-frontend-0.0.3.war.zip)

**Comment by mriccell** [comment]
@emregozen2 did you set in app-deploy.py the VersionIdentifier? http://docs.oracle.com/middleware/12212/wls/WLMBR/mbeans/AppDeploymentMBean.html?skipReload=true#VersionIdentifier.  Let me know.

**Comment by emregozen2** [comment]
Hİ,
I didn't set version identifier information in app-deploy.py, 
There is a version-identifier option for "deploy" function of wlst (versionIdentifier='<application version>'), but i didn't see any option for offline deployment functions(), 

https://docs.oracle.com/middleware/1213/wls/WLSTC/reference.htm#GUID-D26FCB16-E96E-402E-94F8-FBC0E07CECCE



my app-deploy.py is like that,


# Copyright (c) 2015 Oracle and/or its affiliates. All rights reserved.
#
# WLST Offline for deploying an application under APP_NAME packaged in APP_PKG_FILE located in APP_PKG_LOCATION
# It will read the domain under DOMAIN_HOME by default
#
# author: Bruno Borges <bruno.borges@oracle.com>
# since: December, 2015
#
import os

# Deployment Information 
domainhome = os.environ.get('DOMAIN_HOME', '/u01/oracle/user_projects/domains/base_domain')
appname    = os.environ.get('APP_NAME', 'myapp-frontend-0.0.3')
apppkg     = os.environ.get('APP_PKG_FILE', 'myapp-frontend-0.0.3.war')
appdir     = os.environ.get('APP_PKG_LOCATION', '/u01/oracle')

# Read Domain in Offline Mode
# ===========================
readDomain(domainhome)

# Create Application
# ==================
cd('/')
app = create(appname, 'AppDeployment')
app.setSourcePath(appdir + '/' + apppkg)
app.setStagingMode('nostage')

# Assign application to AdminServer
# =================================
assign('AppDeployment', appname, 'Target', 'AdminServer')

# Update Domain, Close It, Exit
# ==========================
updateDomain()
closeDomain()
exit()

**Comment by mriccell** [comment]
@emregozen2 application versions are intended for "Production Redeployment".  In Docker you can not modify an image on the fly (images are in-mutable), if you want something new you create a new image.  To deploy a new application version on WebLogic container you would follow the following steps:
1- Create a new application image by using Dockerfile to extend the WLS domain image and deploy the new application (new version).
2- Shutdown gracefully the container  with the original application
3- Run a container from the image built in step 1 with the newly deployed application.
Do steps 2 and 3 for all containers running in the WLS cluster one at a time to allow for session replication.
