### ISSUE TITLE
WLS 12.2.1.2 cannot make connect() to admin jvm during container build for online wlst

### ISSUE THREAD

**Issue by ackwdw123** [oracle/docker-images#336]
Hi, I'm attempting to execute some online configurations via wlst and when trying to connect to the admin jvm the connect() fails with "java.net.ConnectException: Connection refused (Connection refused); No available router to destination.". The admin jvm is started successfully during the container build. The connect() attempt is to the t3s admin port. As a troubleshooting step, I manually stop the container build after starting up the admin jvm. I then run the container, start the admin jvm and manually excute the connect() and can successfully execute the online configuration. Has anyone else run cross this condition?

**Comment by mriccell** [comment]
@ackwdw123 How do you manually stop container build?  From where are you executing the connect?

**Comment by ackwdw123** [comment]
===Docker contianer build that fails at t3s connect()
1. Install JDK , Install WLS Binary
2. Copy jks, offline py, online py, start script (simple shell script that executes startWebLogic.sh, sends process to background, redirects the output to log)
3. Execute offline wlst : ${ORACLE_HOME}/oracle_common/common/bin/wlst.sh -skipWLSModuleScanning ${DOMAIN_CREATE_SCRIPT} -p ${DOMAIN_CREATE_PROPERTY_FILE}
4. Start Admin JVM
5. Connect to Admin JVM
	Admin JVM starts successfully
	wlst connect() fails
	
6. Execute online wlst  : ${ORACLE_HOME}/oracle_common/common/bin/wlst.sh -skipWLSModuleScanning ${DOMAIN_CREATE_ONLINE_CONFIG_SCRIPT} -p ${DOMAIN_CREATE_PROPERTY_FILE}


===Manual Verification of successful connect()

1. Install JDK , Install WLS Binary
2. Copy jks, offline py, online py, start script (simple shell script that executes startWebLogic.sh, sends process to background, redirects the output to log)
3. Execute offline wlst : ${ORACLE_HOME}/oracle_common/common/bin/wlst.sh -skipWLSModuleScanning ${DOMAIN_CREATE_SCRIPT} -p ${DOMAIN_CREATE_PROPERTY_FILE}
4. Start Admin JVM
5. End Docker build

	Run docker container
	Start Admin JVM
	Connect to Admin JVM - connect('user','pwd','t3s://fqdn.hostname.com:port')
	Execute online wlst : ${ORACLE_HOME}/oracle_common/common/bin/wlst.sh -skipWLSModuleScanning ${DOMAIN_CREATE_ONLINE_CONFIG_SCRIPT} -p ${DOMAIN_CREATE_PROPERTY_FILE}

**Comment by mriccell** [comment]
@ackwdw123 you can not start the JVM at docker build time, that is not how Docker build process works.  What you need to do is when you run the container, start the Admin Server in the background and then call a script that verifies that the Admin Server is up and invokes the WLST online script.  
I will try to submit a sample to do this.

**Comment by ackwdw123** [comment]
Thank you for the follow up, I didn't have any success executing an online script with one build. I have been able to execute an online script using the following steps:
1. ./dockerJDK-WLS-12.2.1.2-Binary.sh
2. ./dockerJDK-WLS-12.2.1.2-Domain.sh
3. docker run -h `hostname` -p 20000:20000 -ti rhelv7-wls-domain bash
	./start-adm.sh
4. Manually execute the online scripting.
6. Manually commit container changes
7. https://`hostname`:20000/console

**Comment by brunoborges** [comment]
Please post your Dockerfile

**Comment by mriccell** [comment]
@ackwdw123 Do you mind sharing your Dockerfile so that we try to reproduce and advice you.

**Comment by mriccell** [comment]
@ackwdw123 take a look at #392 for an example how to do WLST online at domain image build.  You can follow the same steps to do your WLST online configuration.
