### ISSUE TITLE
java.io.FileNotFoundException: fmw_12.2.1.2.0_wls_supplemental_quick.jar (Permission denied)

### ISSUE THREAD

**Issue by anshuggrwll** [oracle/docker-images#337]
Hi All, 

Am facing below issue when am running-> docker build -t 12212-medrec --build-arg ADMIN_PASSWORD= . 
command inside -> /docker/docker-images/OracleWebLogic/samples/12212-medrec folder

Error Detail:

Step 5/8 : RUN cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     chown oracle:oracle -R /u01 &&     echo oracle:oracle | chpasswd &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR  ORACLE_HOME=$ORACLE_HOME" - oracle &&     mv /u01/startSample.sh /u01/oracle/wlserver/samples/server/  &&     rm /u01/$FMW_PKG /u01/$FMW_JAR
 ---> Running in 25cb21255c47
java.io.FileNotFoundException: fmw_12.2.1.2.0_wls_supplemental_quick.jar (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at sun.tools.jar.Main.copy(Main.java:909)
        at sun.tools.jar.Main.extractFile(Main.java:1069)
        at sun.tools.jar.Main.extract(Main.java:981)
        at sun.tools.jar.Main.run(Main.java:311)
        at sun.tools.jar.Main.main(Main.java:1288)
The command '/bin/sh -c cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     chown oracle:oracle -R /u01 &&     echo oracle:oracle | chpasswd &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR  ORACLE_HOME=$ORACLE_HOME" - oracle &&     mv /u01/startSample.sh /u01/oracle/wlserver/samples/server/  &&     rm /u01/$FMW_PKG /u01/$FMW_JAR' returned a non-zero code: 1

**Comment by mriccell** [comment]
@anshuggrwll did you build the 12.2.1.2 base image developer version?  Did you download the supplemental installer fmw_12.2.1.2.0_wls_supplemental_quick.jar?

**Comment by anshuggrwll** [comment]
am facing the error while building the image and yes i
have fmw_12.2.1.2.0_wls_supplemental_quick_Disk1_1of1 file which contains
 fmw_12.2.1.2.0_wls_supplemental_quick.jar .

**Comment by macotonio** [comment]
It works for me

MAINTAINER Monica Riccelli <monica.riccelli@oracle.com>

RUN whoami
# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
ENV FMW_PKG="fmw_12.2.1.2.0_wls_supplemental_quick_Disk1_1of1.zip" \
    FMW_JAR="fmw_12.2.1.2.0_wls_supplemental_quick.jar" \
    MW_HOME="$ORACLE_HOME" \
    PATH="/u01:$ORACLE_HOME/wlserver/server/bin:$ORACLE_HOME/wlserver/../oracle_common/modules/org.apache.ant_1.9.2/bin:$JAVA_HOME/jre/bin:$JAVA_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$ORACLE_
HOME/oracle_common/common/bin:$ORACLE_HOME/wlserver/common/bin:$ORACLE_HOME/user_projects/domains/medrec/bin:$ORACLE_HOME/wlserver/samples/server/medrec/:$ORACLE_HOME/wlserver/samples/server/:$ORACLE_HOME/wlserver/../oracle
_common/modules/org.apache.maven_3.2.5/bin"

# Copy supplemental package and scripts
# --------------------------------
COPY $FMW_PKG startSample.sh /u01/
USER root
RUN chown oracle:oracle -R /u01
RUN chmod 775 /u01/oracle
RUN chmod 775 /u01/*.sh
RUN ls -l /u01
USER oracle
RUN whoami
# Installation of Supplemental Quick Installer
# --------------------------------------------
# wlsadmin
RUN cd /u01
RUN $JAVA_HOME/bin/jar xf /u01/$FMW_PKG

RUN pwd
RUN ls -l
RUN cd /u01

RUN $JAVA_HOME/bin/java -jar /u01/oracle/$FMW_JAR  ORACLE_HOME=$ORACLE_HOME
RUN mv /u01/startSample.sh /u01/oracle/wlserver/samples/server/
RUN rm /u01/$FMW_PKG /u01/oracle/$FMW_JAR


WORKDIR $ORACLE_HOME/wlserver/samples/server

EXPOSE 7011

CMD ["startSample.sh"]

**Comment by mriccell** [comment]
I tried as well with no problems, do not unzip just place it in the 12212-medrec directory.
