### ISSUE TITLE
How to do JMS persistance in Docker containers with servers not in a WLS cluster

### ISSUE THREAD

**Issue by mriccell** [oracle/docker-images#341]
We have WLS servers running from the same WLS domain image.  These servers are not clustered and do not communicate between them, they have JMS Server and application deployed to them.  Every server is called the same (WLServer) and the the customer FilePersistentStore volume is mapped to a different directory in the host.  
Manually when a WLS container is started the Persistent Store directory is mapped to a unique directory on the host with the -v option.  If that container is killed and a new one is started that needs to recover the persisted messages from the original container the same docker run -v directory is passed so that the server can recover the messages. 
The question is, what mechanism can be used when it is an orchestration tool that is starting and removing containers and knows nothing about where the Persistent store is or if the newly started container is replacing the one that died/shutdown previously.

**Comment by clemSeveillac** [comment]
Hi @mriccell ! Though not straightforward and not without impacts on perf or complexity, PersistentVolumes (using the right kind of volume, e.g. hostPath not being resilient to host crash) may help you reconnect your persistent store to the right pod instances, for instance via StatefulSets, cf. https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#writing-to-stable-storage . Tell us what you think about it :)

**Comment by mriccell** [comment]
Using the Docker sample at https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/1221-domain-with-resources,

1) All WebLogic servers running in containers are called the same "WL_SERVER"

2) All WebLogic server containers are started  from the same image.

3) All servers are configured with a custom JMS Persistent store in a specific directory - in my example /u01/oracle/user_projects/domain/base_domain/PersistentStore-directory

4) Using OCCS as orchestration tool of WLS containers to depict this solution.  Lets say you  run 4 different containers, I define in OCCS yaml file 4 different services WLS01, WLS02, WLS03, WLS04 each running on different VMs/host (could be the same), the data volume in the container is mapped to a unique volume in the VM/host.  Lets say WLS02 service comes down you can now re-start WLS02 service back up and it will be running in the same VMs/host mapped to the same volume; since the servers are all called the same (WL_SERVER) once the server is started it will recover the messages in the store.
