### ISSUE TITLE
Provide capability to pass on default password for database

### ISSUE THREAD

**Issue by gvenzl** [oracle/docker-images#345]
It should be possible to provide the password for the database via the environment variable. This allows to use the image for scripts or other images with no user intervention.

**Comment by brunoborges** [comment]
This is interesting, can you make something that can be applied to the other products?

**Comment by gvenzl** [comment]
Yeah, it's not hard. Just have another env variable defined and the run script has to check whether it's set and if not generate a random password. Should be only a couple of lines in the unix script.

**Comment by gvenzl** [comment]
Fixed via #356 - Allow for user defined passwords while still generating by default
