### ISSUE TITLE
Licence with Docker Container. 

### ISSUE THREAD

**Issue by mcousine** [oracle/docker-images#348]
The licence section is not clear, I’ve talk to our local Oracle REP concerning support and licencing model for Oracle Database in Docker. 

The answer is puzzling, 

Docker is not in the list of hard partitioning technologies of this document:
http://www.oracle.com/us/corporate/pricing/partitioning-070609.pdf

So this is considered soft partitioning like VMware. So the same VMware policies apply to deployment on Docker.

Meaning if you have a farm of 10 servers with Kubernetes and Oracle in a Docker Container you would need to licence ALL Physical CPU of all the servers FARM   (10 servers)? Just like in VMware Farm having a Oracle database in a Virtual Machine is equal to licence the whole ESX Farm of all the physical server that compose the farm. 

So you support Docker but your licencing model prevent it to being used in production is that it ? 

This project offers sample Dockerfiles for:
•	Oracle Database 12c Release 2 (12.2.0.1) Enterprise Edition and Standard Edition 
•	Oracle Database 12c Release 1 (12.1.0.2) Enterprise Edition and Standard Edition 
•	Oracle Database 11g Release 2 (11.2.0.2) Express Edition. 
https://support.oracle.com/epmos/faces/DocumentDisplay?_afrLoop=358003471259260&id=2216342.1&_afrWindowMode=0&_adf.ctrl-state=16vwg63yl6_105

**Comment by brunoborges** [comment]
@mcousine yes, currently that is the license model.
