### ISSUE TITLE
Can't create the Oracle Database 12.2.0.1 container (Step 7 - starting container failure)

### ISSUE THREAD

**Issue by pasimoes** [oracle/docker-images#352]
I've been trying to create the Oracle 12.2.0.1 container with no success. During Step 7 when script tried start container it failed
[docker-db-failure.txt](https://github.com/oracle/docker-images/files/924145/docker-db-failure.txt)
.
"Step 7 : RUN chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE
 ---> Running in 84c14e38c7d4
container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
Removing intermediate container 84c14e38c7d4
invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/bin/sh\\\": stat /bin/sh: no such file or directory\"\n"
There was an error building the image."

**Comment by gvenzl** [comment]
I cannot spot any obvious error here. I'm able to successfully build the image with the same Docker and kernel version. I found some issues regarding this error but they seem to be AUFS related which this container isn't using (https://github.com/docker/docker/issues/5135).

@Djelibeybi, can you shed more light on this issue?
This is my output which is working: [output.working.txt](https://github.com/oracle/docker-images/files/924495/output.working.txt)

**Comment by Djelibeybi** [comment]
Please provide the output of `docker info` on the build machine.

**Comment by gvenzl** [comment]
Docker info is provided at the top of the output for both files.

**Comment by Djelibeybi** [comment]
The only thing I recommend is to break step 7 into individual `RUN` directives so we can work out which one is failing and debug that accordingly.

**Comment by pasimoes** [comment]
Hello @gvenzl and @Djelibeybi 

I fixed the build just changing the step 7 in "Dockerfile.ee" putting each command to execute separately.

## Changed from
RUN chmod ug+x $INSTALL_DIR/*.sh && \
    sync && \
    $INSTALL_DIR/$CHECK_SPACE_FILE && \
    $INSTALL_DIR/$SETUP_LINUX_FILE

## To
RUN chmod ug+x $INSTALL_DIR/*.sh
RUN sync
RUN $INSTALL_DIR/$CHECK_SPACE_FILE
RUN $INSTALL_DIR/$SETUP_LINUX_FILE

I really don´t know why this made the difference on my side.

**Comment by pasimoes** [comment]
Thank you so much!

**Comment by gvenzl** [comment]
That's strange! @Djelibeybi, any idea why this would fail as one UNIX command `RUN` instruction but runs fine via various `RUN` steps on this particular platform?

**Comment by Djelibeybi** [comment]
No idea, but I bet it's to do with the `sync` call perhaps not actually being seen during that build step. Could be due to underlying filesystem/storage layers if this is cloud-based.

**Comment by pasimoes** [comment]
@Djelibeybi my first impression is really about sync (maybe "filesystem" didn't update correctly). My environment is an Oracle Linux 7 running in VirtualBox (Windows 7 host).
Inside OL 7 Guest, I installed docker and database image. I did this to run on my end a VBox with Middleware + Database both in same "machine".

**Comment by Djelibeybi** [comment]
@pasimoes That's odd, because I run (almost) the same setup: OS X with VirtualBox and Oracle Linux 7 and it works just fine without any issues. @gvenzl what does your setup look like?

**Comment by gvenzl** [comment]
The Docker info was pretty much the same.

This is my environment that I built it on:

```
DOCKER info:
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 54
Server Version: 1.12.6
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.1.12-61.1.34.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.795 GiB
Name: localhost.localdomain
ID: ZXSM:SBRF:GQG2:6STR:I2DS:JLOO:3PQN:W4UB:6K4O:B5CB:3TKD:FQPO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

And that's the one from @pasimoes:

```
DOCKER info:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.6
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.1.12-61.1.34.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.544 GiB
Name: bpmdv.oraclelabs
ID: U4SX:O4ZW:NM6U:5NCJ:JPPZ:HNQQ:Z62H:JZQI:BZQZ:U3BW:SL6T:RE26
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

I can't spot any significant difference.
We introduced `sync` back then because of issue #232.
