### ISSUE TITLE
Can't build the Oracle Database 12.1.0.2 image (install/.oui: cannot execute binary file)

### ISSUE THREAD

**Issue by LeSphax** [oracle/docker-images#354]
Hello, I had several problems when running the "buildDockerImage.sh" script and I am currently stuck on this last one: 
I use this command **sudo ./buildDockerImage.sh -e -v 12.1.0.2 -i**
And I get these error messages

```
/opt/oracle/install/database/runInstaller: line 472: /opt/oracle/install/database/install/.oui: cannot execute binary file
/opt/oracle/install/installDBBinaries.sh: line 62: /opt/oracle/product/12.1.0.2/dbhome_1/perl/bin/perl: No such file or directory
mv: cannot stat '/opt/oracle/product/12.1.0.2/dbhome_1/perl': No such file or directory
```
Here is the full log
[oracle-docker-build.txt](https://github.com/oracle/docker-images/files/934361/oracle-docker-build.txt)

Here are the other problems I encountered: 
1. The installation files I downloaded at http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html didn't have the same name as those in the script. 
The files I have are named **linux.zseries64_12102_database_1of2** while those in the build are named **linuxamd64_12102_database_1of2**. 
So I just changed the name in the script and ran it without the checksum.

Do I have the wrong files? In that case, where can I download the right files?

2. A package failed to install, I believe it was the same problem as this one https://github.com/oracle/docker-images/issues/286.
I also had a problem with the max container size being less than 12 GB after that one.
I solved both of those by running docker using **sudo dockerd --storage-driver=devicemapper --storage-opt dm.basesize=20G &**

Tell me if you need anything else, any help is greatly appreciated :)

**Comment by chrisguoado** [comment]
`linux.zseries64` is for IBM System z on Mainframes, you are using the wrong installer.

**Comment by LeSphax** [comment]
Ok, that is what I was expecting but I didn't manage to find any installation files for Linux that look like **linuxamd64_12102_database_1of2** by following the link on the readme page.

Do you have any idea where I can get those?

Thank you for your help :)

**Comment by chrisguoado** [comment]
I think you can go to www.google.com, and search for `linuxamd64_12102_database_1of2`, I'm sure you'll find the right OTN download page :)

**Comment by LeSphax** [comment]
Yep, I found it. I should have thought about that. Thanks for your help :)

I will close the issue if this ends up solving my problem.

**Comment by chrisguoado** [comment]
@LeSphax You are welcome.
Actually I also have no idea why `Linux x86-64` for 12cR1 download link is not even on the database download home page. There's only the one for 12cR2. Maybe this is some kind of strategy.
@gvenzl Maybe we can enhance the readme a little to include the specific download link.

**Comment by LeSphax** [comment]
It worked fine with the correct install files :p

I just had to change the name of my files from **linux.amd64_12102_database_1of2** to **linuxamd64_12102_database_1of2** but it seems like this name will depend on whether people download it from [the homepage]( https://www.oracle.com/database/index.html)(There is a button at the bottom) or from [this download page](http://www.oracle.com/technetwork/database/enterprise-edition/downloads/database12c-linux-download-2240591.html).

**Comment by gvenzl** [comment]
@chrisguoado, it is actually an error on the OTN page and we are just about to revert that. What is also not mentioned (yet) on the OTN download page is that all software can also be downloaded from [https://edelivery.oracle.com](https://edelivery.oracle.com). I just point it out for future reference but as said, the download links will come back soon!

And as a general hint: Don't skip the MD5 checksum check unless you are really sure the zip files are the correct ones and not corrupt. :) Saves you and me a lot of confusion and time spent on root cause analysis. :)

**Comment by gvenzl** [comment]
And fixed on OTN. :)
