### ISSUE TITLE
RAC support for Oracle DB container

### ISSUE THREAD

**Issue by nnewberry** [oracle/docker-images#355]
We'd like to move Oracle from bare metal to containers in production, but we use RAC.

Is there any plan to support RAC, either with direct ASM access to host iSCSI devices OR using some docker volume driver to provide shared storage to multiple containers on the same network?

**Comment by gvenzl** [comment]
As per the Support section in the ReadMe:

> Support
> 
> Oracle Database in single instance configuration is supported for Oracle Linux 7 and Red Hat Enterprise Linux (RHEL) 7. For more details please see My Oracle Support note: Oracle Support for Database Running on Docker (Doc ID 2216342.1)

Yes, there are plans to support RAC but this is still too far out to make a statement when and if.
