### ISSUE TITLE
Coherence docker

### ISSUE THREAD

**Issue by rstyczynski** [oracle/docker-images#363]
Links are wrong in Documentation:

Documentation covering the different aspects of running Oracle Coherence in Docker containers is covered in the docs section.

>>>>> it's leading to 404:
Image Usage - Usage instructions for running the Coherence image
Setup - Setting Up a Demo Docker Machine Environment
Clustering - Running Coherence Clusters in Docker
Coherence Extend - Running Coherence Extend in Docker
Federated Caching - Federated Caching in Docker
Disc Based Functionality - Elastic Data and Persistence in Docker
JMX Monitoring - Using JMX in Docker

**Comment by brunoborges** [comment]
@thegridman Jonathan, can you take a look at this please?
