### ISSUE TITLE
!! Call for Oracle !! Make Oracle database images available at docker hub for Travis like tests.

### ISSUE THREAD

**Issue by gintsgints** [oracle/docker-images#367]
Dear Oracle.

Open source community makes lot of effort on implementing oracle database support in lot of database related projects. Just naming some of them:
https://github.com/typeorm/typeorm
http://docs.sequelizejs.com/en/v3/

All thease projects suffer from luck of testing for oracle support. And all this is because driver is only aiviable whith signing to OTN.

Some workarounds exists, but nobody is sure enough they are legal to use.

Please be so kind and allow developers to use published oracle image for software testing purposes.

**Comment by Djelibeybi** [comment]
We have already published the Oracle Instant Client and Oracle Database Enterprise Edition to the Docker Store:

https://store.docker.com/images/oracle-instant-client
https://store.docker.com/images/oracle-database-enterprise-edition

These can be used at no charge after accepting the license via the Docker Store.
