### ISSUE TITLE
Db 12.2.0.1.0-se image error: LRM-00109: could not open parameter file '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/initORCLCDB.ora'

### ISSUE THREAD

**Issue by jimzucker** [oracle/docker-images#369]
I created the se image with the scripts this morning the image was created OK but it will not start up propoerly, see error below, looks like a file is missing.
```
TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/6e29d76f5d05/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=6e29d76f5d05)(PORT=1521)))

Connecting to (ADDRESS=(PROTOCOL=tcp)(HOST=)(PORT=1521))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                01-MAY-2017 15:56:49
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/6e29d76f5d05/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=6e29d76f5d05)(PORT=1521)))
The listener supports no services
The command completed successfully

SQL*Plus: Release 12.2.0.1.0 Production on Mon May 1 15:56:49 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/initORCLCDB.ora'
SQL> Disconnected
#########################
DATABASE IS READY TO USE!
#########################
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining
```

**Comment by gvenzl** [comment]
This looks like something went wrong during the build of the image.
Can you please provide the build output?

Thx,

**Comment by jimzucker** [comment]
Here is the build file, I rebuilt it and tested to verify the problem is reproducible.  FYI I am running o

**Comment by gvenzl** [comment]
Thanks @jimzucker. The image build does look fine, the software was installed just fine. How are you starting the container?

Thx,

**Comment by jimzucker** [comment]
@gvenzl I am using the docker-compose file from the samples, with some minor adjustments.  it is attached.

i added a -vx to the script so we can get a trace

➜  12201-docker-compose git:(Db_Compose) ✗ docker logs -f oracle

########### Move DB files ############
function moveFiles {

   if [ ! -d $ORACLE_BASE/oradata/dbconfig/$ORACLE_SID ]; then
      mkdir -p $ORACLE_BASE/oradata/dbconfig/$ORACLE_SID/
   fi;

   mv $ORACLE_HOME/dbs/spfile$ORACLE_SID.ora $ORACLE_BASE/oradata/dbconfig/$ORACLE_SID/
   mv $ORACLE_HOME/dbs/orapw$ORACLE_SID $ORACLE_BASE/oradata/dbconfig/$ORACLE_SID/
   mv $ORACLE_HOME/network/admin/tnsnames.ora $ORACLE_BASE/oradata/dbconfig/$ORACLE_SID/

   # oracle user does not have permissions in /etc, hence cp and not mv
   cp /etc/oratab $ORACLE_BASE/oradata/dbconfig/$ORACLE_SID/

   symLinkFiles;
}

########### Symbolic link DB files ############
function symLinkFiles {

   if [ ! -L $ORACLE_HOME/dbs/spfile$ORACLE_SID.ora ]; then
      ln -s $ORACLE_BASE/oradata/dbconfig/$ORACLE_SID/spfile$ORACLE_SID.ora $ORACLE_HOME/dbs/spfile$ORACLE_SID.ora
   fi;

   if [ ! -L $ORACLE_HOME/dbs/orapw$ORACLE_SID ]; then
      ln -s $ORACLE_BASE/oradata/dbconfig/$ORACLE_SID/orapw$ORACLE_SID $ORACLE_HOME/dbs/orapw$ORACLE_SID
   fi;

   if [ ! -L $ORACLE_HOME/network/admin/tnsnames.ora ]; then
      ln -s $ORACLE_BASE/oradata/dbconfig/$ORACLE_SID/tnsnames.ora $ORACLE_HOME/network/admin/tnsnames.ora
   fi;

   # oracle user does not have permissions in /etc, hence cp and not ln
   cp $ORACLE_BASE/oradata/dbconfig/$ORACLE_SID/oratab /etc/oratab

}

########### SIGINT handler ############
function _int() {
   echo "Stopping container."
   echo "SIGINT received, shutting down database!"
   sqlplus / as sysdba <<EOF
   shutdown immediate;
   exit;
EOF
   lsnrctl stop
}

########### SIGTERM handler ############
function _term() {
   echo "Stopping container."
   echo "SIGTERM received, shutting down database!"
   sqlplus / as sysdba <<EOF
   shutdown immediate;
   exit;
EOF
   lsnrctl stop
}

########### SIGKILL handler ############
function _kill() {
   echo "SIGKILL received, shutting down database!"
   sqlplus / as sysdba <<EOF
   shutdown abort;
   exit;
EOF
   lsnrctl stop
}

###################################
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! #
############# MAIN ################
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! #
###################################

# Check whether container has enough memory
# Github issue #219: Prevent integer overflow,
# only check if memory digits are less than 11 (single GB range and below)
if [ `cat /sys/fs/cgroup/memory/memory.limit_in_bytes | wc -c` -lt 11 ]; then
   if [ `cat /sys/fs/cgroup/memory/memory.limit_in_bytes` -lt 2147483648 ]; then
      echo "Error: The container doesn't have enough memory allocated."
      echo "A database container needs at least 2 GB of memory."
      echo "You currently only have $((`cat /sys/fs/cgroup/memory/memory.limit_in_bytes`/1024/1024/1024)) GB allocated to the container."
      exit 1;
   fi;
fi;
cat /sys/fs/cgroup/memory/memory.limit_in_bytes | wc -c
++ wc -c
++ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
+ '[' 20 -lt 11 ']'

# Set SIGINT handler
trap _int SIGINT
+ trap _int SIGINT

# Set SIGTERM handler
trap _term SIGTERM
+ trap _term SIGTERM

# Set SIGKILL handler
trap _kill SIGKILL
+ trap _kill SIGKILL

# Default for ORACLE SID
if [ "$ORACLE_SID" == "" ]; then
   export ORACLE_SID=ORCLCDB
else
  # Check whether SID is no longer than 12 bytes
  # Github issue #246: Cannot start OracleDB image
  if [ "${#ORACLE_SID}" -gt 12 ]; then
     echo "Error: The ORACLE_SID must only be up to 12 characters long."
     exit 1;
  fi;

  # Check whether SID is alphanumeric
  # Github issue #246: Cannot start OracleDB image
  if [[ "$ORACLE_SID" =~ [^a-zA-Z0-9] ]]; then
     echo "Error: The ORACLE_SID must be alphanumeric."
     exit 1;
   fi;
fi;
+ '[' '' == '' ']'
+ export ORACLE_SID=ORCLCDB
+ ORACLE_SID=ORCLCDB

# Default for ORACLE PDB
export ORACLE_PDB=${ORACLE_PDB:-ORCLPDB1}
+ export ORACLE_PDB=ORCLPDB1
+ ORACLE_PDB=ORCLPDB1

# Default for ORACLE CHARACTERSET
export ORACLE_CHARACTERSET=${ORACLE_CHARACTERSET:-AL32UTF8}
+ export ORACLE_CHARACTERSET=AL32UTF8
+ ORACLE_CHARACTERSET=AL32UTF8

ls -ltra $ORACLE_BASE/oradata
+ ls -ltra /opt/oracle/oradata
total 4
drwxr-x---  3 oracle dba  102 May  1 15:41 fast_recovery_area
drwxr-xr-x  4 oracle dba  136 May  1 15:41 .
drwxr-x---  5 oracle dba  170 May  1 15:41 ORCLCDB
drwxr-xr-x 12 oracle dba 4096 May  2 01:18 ..
# Check whether database already exists
if [ -d $ORACLE_BASE/oradata/$ORACLE_SID ]; then
	ls -ltra $ORACLE_BASE/oradata
	ls -ltra  $ORACLE_BASE/oradata/$ORACLE_SID
   symLinkFiles;

   # Make sure audit file destination exists
   if [ ! -d $ORACLE_BASE/admin/$ORACLE_SID/adump ]; then
      mkdir -p $ORACLE_BASE/admin/$ORACLE_SID/adump
   fi;

   # Start database
   $ORACLE_BASE/$START_FILE;

else
   # Remove database config files, if they exist
   rm -f $ORACLE_HOME/dbs/spfile$ORACLE_SID.ora
   rm -f $ORACLE_HOME/dbs/orapw$ORACLE_SID
   rm -f $ORACLE_HOME/network/admin/tnsnames.ora

   # Create database
   $ORACLE_BASE/$CREATE_DB_FILE $ORACLE_SID $ORACLE_PDB $ORACLE_PWD;

   # Move database operational files to oradata
   moveFiles;
fi;
+ '[' -d /opt/oracle/oradata/ORCLCDB ']'
+ ls -ltra /opt/oracle/oradata
total 4
drwxr-x---  3 oracle dba  102 May  1 15:41 fast_recovery_area
drwxr-xr-x  4 oracle dba  136 May  1 15:41 .
drwxr-x---  5 oracle dba  170 May  1 15:41 ORCLCDB
drwxr-xr-x 12 oracle dba 4096 May  2 01:18 ..
+ ls -ltra /opt/oracle/oradata/ORCLCDB
total 819208
drwxr-x--- 2 oracle dba        68 May  1 15:41 pdbseed
drwxr-x--- 2 oracle dba        68 May  1 15:41 ORCLPDB1
drwxr-xr-x 4 oracle dba       136 May  1 15:41 ..
drwxr-x--- 5 oracle dba       170 May  1 15:41 .
-rw-r----- 1 oracle dba 838868992 May  1 15:41 system01.dbf
+ symLinkFiles
+ '[' '!' -L /opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileORCLCDB.ora ']'
+ ln -s /opt/oracle/oradata/dbconfig/ORCLCDB/spfileORCLCDB.ora /opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileORCLCDB.ora
+ '[' '!' -L /opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwORCLCDB ']'
+ ln -s /opt/oracle/oradata/dbconfig/ORCLCDB/orapwORCLCDB /opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwORCLCDB
+ '[' '!' -L /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/tnsnames.ora ']'
+ ln -s /opt/oracle/oradata/dbconfig/ORCLCDB/tnsnames.ora /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/tnsnames.ora
+ cp /opt/oracle/oradata/dbconfig/ORCLCDB/oratab /etc/oratab
cp: cannot stat '/opt/oracle/oradata/dbconfig/ORCLCDB/oratab': No such file or directory
+ '[' '!' -d /opt/oracle/admin/ORCLCDB/adump ']'
+ mkdir -p /opt/oracle/admin/ORCLCDB/adump
+ /opt/oracle/startDB.sh

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 02-MAY-2017 01:23:32

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/85295ba71e37/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=85295ba71e37)(PORT=1521)))

Connecting to (ADDRESS=(PROTOCOL=tcp)(HOST=)(PORT=1521))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                02-MAY-2017 01:23:32
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/85295ba71e37/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=85295ba71e37)(PORT=1521)))
The listener supports no services
The command completed successfully

SQL*Plus: Release 12.2.0.1.0 Production on Tue May 2 01:23:32 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/initORCLCDB.ora'
SQL> Disconnected

echo "#########################"
+ echo '#########################'
echo "DATABASE IS READY TO USE!"
+ echo 'DATABASE IS READY TO USE!'
echo "#########################"
+ echo '#########################'

tail -f $ORACLE_BASE/diag/rdbms/*/*/trace/alert*.log &
#########################
DATABASE IS READY TO USE!
#########################
childPID=$!
+ childPID=23
wait $childPID
+ wait 23
+ tail -f '/opt/oracle/diag/rdbms/*/*/trace/alert*.log'
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining

**Comment by jimzucker** [comment]
Update: I cleaned up the files in my mounted oradata directory and was able to get further.

Not sure how I got into this situation.  I am going to close this thread.
