### ISSUE TITLE
OHS 12.2.1: Issue with configureWLSProxyPlugin.sh

### ISSUE THREAD

**Issue by amyles** [oracle/docker-images#370]
Hi, I have the OHS 12.2.1 image built as per docs but having an issue when supplying a custom_mod_wl_ohs.conf file to set up the WLS plug in. I see the following via docker logs:
```
root@braan:/var/lib/docker/volumes/volume# docker logs ohs

MW_HOME=/u01/oracle/ohssa
DOMAIN_NAME=ohsDomain
OHS_COMPONENT_NAME=ohs_sa1
INSTANCE_CONFIG_DIR=/u01/oracle/ohssa/user_projects/domains/ohsDomain/config/fmwconfig/components/OHS/ohs_sa1
/u01/oracle/container-scripts/configureWLSProxyPlugin.sh: line 41: cd: /u01/oracle/ohssa/user_projects/domains/ohsDomain/config/fmwconfig/components/OHS/ohs_sa1: No such file or directory
mv: cannot stat 'mod_wl_ohs.conf': No such file or directory
Copying /volume/custom_mod_wl_ohs.conf to /u01/oracle/ohssa/user_projects/domains/ohsDomain/config/fmwconfig/components/OHS/ohs_sa1 
cp: cannot create regular file '/u01/oracle/ohssa/user_projects/domains/ohsDomain/config/fmwconfig/components/OHS/ohs_sa1/mod_wl_ohs.conf': No such file or directory
Starting Node Manager and OHS server after successful configuration of WebLogic Server Proxy Plug-In 
MW_HOME=/u01/oracle/ohssa
ORACLE_HOME=/u01/oracle/ohssa
DOMAIN_NAME=ohsDomain
OHS_COMPONENT_NAME=ohs_sa1
cat: date: No such file or directory
```
OHS starts but the routing to WLS is not set up. I can go in later and manually copy the custom_mod_wl_ohs.conf file to INSTANCE_CONFIG_DIR and once the container is restarted all working as expected. 

Any idea what is up with the initial execution of configureWLSProxyPlugin.sh?

**Comment by brunoborges** [comment]
Hi @amyles, do you still have this issue ?

**Comment by mriccell** [comment]
@amyles we have submitted a new OHS image 12.2.1.2, can you verify if you still encounter a problem with the new image?

**Comment by amyles** [comment]
Hi @brunoborges and @mriccell sorry been away from this for a while. I will retest soon and let you know.

**Comment by brunoborges** [comment]
Hi @amyles, any update?
