### ISSUE TITLE
Image for 11g SE EE?

### ISSUE THREAD

**Issue by nevyen** [oracle/docker-images#374]
Hey I'm trying to run a Oracle Database 11g SE ot 11g EE as a Dockercontainer. But I can't find any dockerfile for this. Is it possible to get this work ?

**Comment by gvenzl** [comment]
Hi @nevyen, yes, it is possible to run Oracle 11g in Docker, we do that today with XE as there is no 12c XE available yet.
However, Oracle 11g Release 2 has been released 10 years ago! and we do not plan to provide any Docker images for that release anymore.
We highly encourage users to use Oracle 12c Release 2 instead.

That being said, nothing stops you from building your own Docker image for 11g or use one of the build files from the community.
