### ISSUE TITLE
Building OracleDatabase 12.2.0.1 SE fails

### ISSUE THREAD

**Issue by kaythriemer** [oracle/docker-images#375]
Hi, 
since today I am not able to build a Oracle 12c SE Docker container anymore.
I use the described procedure:
1.  git clone https://github.com/oracle/docker-images.git
2. cp linuxx64_12201_database.zip <docker_dir>/OracleDocker/docker-images/OracleDatabase/dockerfiles/12.2.0.1/linuxx64_12201_database.zip
3. cd <docker_dir>/OracleDocker/docker-images/OracleDatabase/dockerfiles/
4. sudo ./buildDockerImage.sh -v 12.2.0.1 -s

```
In step 7/16 I am faced with following problem:
Step 7/16 : RUN chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE
 ---> Running in 73cdf25d6721
Traceback (most recent call last):
  File "/usr/bin/yum", line 4, in <module>
    import yum
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 62, in <module>
    import rpmsack
  File "/usr/lib/python2.7/site-packages/yum/rpmsack.py", line 38, in <module>
    import yum.depsolve
  File "/usr/lib/python2.7/site-packages/yum/depsolve.py", line 30, in <module>
    from transactioninfo import TransactionMember
ValueError: bad marshal data (unknown type code)
Removing intermediate container 73cdf25d6721
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE' returned a non-zero code: 1
There was an error building the image.
```

I have no idea what has changed and how to solve this issue.

Kind regards,
Kay

**Comment by kaythriemer** [comment]
Hi,
temporary I changed the Dockerfile.se2 
to "FROM oraclelinux:7" instead "FROM oraclelinux:7-slim".
It seems that there is an issue with yum in oraclelinux:7-slim
Kay

**Comment by gvenzl** [comment]
That is very strange, I managed to rebuild all images just yesterday. @Djelibeybi, you are probably better with `yum` then me. The error suggests a corrupted file of some sort but any idea where this is coming from?

**Comment by Djelibeybi** [comment]
Yeah, the output suppresses the `yum` output, so I would guess that something broke during the download and `yum` wasn't able to resolve dependencies properly. Does this happen consistently? Can you try again?

**Comment by kaythriemer** [comment]
Hi gvenzl, hi Djelibeybi, 
Thank you for your fast reply. Yes I tried it several times yesterday.
But today it is working without any issue in step 7/16. Very strange.
Thank you,
Kay
