### ISSUE TITLE
Databasae data files save location?

### ISSUE THREAD

**Issue by Ijlalh90** [oracle/docker-images#376]
I want to ask when the container is up and running, where will it save the datafiles of database if persistence storage is not used?

**Comment by brunoborges** [comment]
It will save in the container layer. If you trash the container, you trash the data.

**Comment by gvenzl** [comment]
If you don't provide a mapping with the -v option Docker will create a anonymous volume for you. The data files are still stored in that volume.

**Comment by Ijlalh90** [comment]
@gvenzl can u point out in dockerfile  where it is specified that it will create volume anonymous

**Comment by gvenzl** [comment]
Hi @Ijlalh90, the `VOLUME` instruction is specified here: https://github.com/oracle/docker-images/blob/master/OracleDatabase/dockerfiles/12.2.0.1/Dockerfile.ee#L74

Whether or not Docker creates a anonymous or named volume is up to the user. For more information on volumes I recommend the [Docker documentation - Manage data in containers](https://docs.docker.com/engine/tutorials/dockervolumes/).
