### ISSUE TITLE
Connect to container using sqldevelopper

### ISSUE THREAD

**Issue by I050689** [oracle/docker-images#387]
Hello,

My container is up and working well.
I started the container with the next syntaxe : docker run --name oracle12r2 -p 1527:1521 -p 5507:5500 -e ORACLE_PWD=text oracle/database:12.2.0.1-ee

I can use sqlplus doing : docker exec -ti oracle12r2 sqlplus system@ORCLPDB1 

But I can't logon to the container from sqldevelopper.

Also, how can I modify the file sqlora or tnsname using the account oracle? All the commands like vi or nano are not reconized.

Please help.

Best regards,
Daniela

**Comment by I050689** [comment]
for the vi or nano is ok now.
I modify the script to allow to user oracle  to use yum .
But still bocked on the connection with sqldevelopper for outside the container.
Any idea?
Thank you very much!!!

**Comment by gvenzl** [comment]
Hi @I050689,

The tnsnames is stored as part of the volume and can be modified outside the container. The sqlnet.ora however is not. I would like to better understand the requirement, i.e. what parameters do you need to change in the sqlnet.ora. 

As to your SqlDeveloper connection I need more details to make a judgement on why this isn't working. As you can connect with SqlPlus just fine this is probably just an issue with the connect string configured in SqlDev. Can you share your connection details thay you use inside SqlDev, please?

**Comment by I050689** [comment]
Hello Gérald,

I create the container with oracle 12cR2 and I can execute the sqlpus when I’m on the machine were the container is located.
But if I’m trying to logon from a different machine using sql developer I have the error message : ora-28040

[cid:image001.png@01D2D0A3.C496A7A0]

The image was build as : ./buildDockerImage.sh -v 12.2.0.1 -e -i
Then the container is created like : docker run --name oracle12r2 -p 1527:1521 -p 5507:5500 -e ORACLE_PWD=bobobo oracle/database:12.2.0.1-ee

Mon tnsnames is :
[oracle@d123c71690b1 admin]$ cat tnsnames.ora
ORCLCDB=localhost:1521/ORCLCDB
ORCLPDB1=
(DESCRIPTION =
  (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
  (CONNECT_DATA =
    (SERVER = DEDICATED)
    (SERVICE_NAME = ORCLPDB1)
  )
)

I hope I gaved you all the informations.
Please come back to me if you need other information.

Thank you very much for you time and help.
Daniela

**Comment by I050689** [comment]
Also,
The tnsping from the machine wher I execute the sqldevelopper is ok :

Used TNSNAMES adapter to resolve the alias
Attempting to contact (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.47.3.
155)(PORT = 1527)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = ORCLPDB1
)))
OK (30 msec)



From: BOAMBA, Daniela
Sent: vendredi 19 mai 2017 13:33
To: 'oracle/docker-images' <reply@reply.github.com>; oracle/docker-images <docker-images@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [oracle/docker-images] Connect to container using sqldevelopper (#387)

Hello Gérald,

I create the container with oracle 12cR2 and I can execute the sqlpus when I’m on the machine were the container is located.
But if I’m trying to logon from a different machine using sql developer I have the error message : ora-28040

[cid:image001.png@01D2D0A5.A7469E10]

The image was build as : ./buildDockerImage.sh -v 12.2.0.1 -e -i
Then the container is created like : docker run --name oracle12r2 -p 1527:1521 -p 5507:5500 -e ORACLE_PWD=bobobo oracle/database:12.2.0.1-ee

Mon tnsnames is :
[oracle@d123c71690b1 admin]$ cat tnsnames.ora
ORCLCDB=localhost:1521/ORCLCDB
ORCLPDB1=
(DESCRIPTION =
  (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
  (CONNECT_DATA =
    (SERVER = DEDICATED)
    (SERVICE_NAME = ORCLPDB1)
  )
)

I hope I gaved you all the informations.
Please come back to me if you need other information.

Thank you very much for you time and help.
Daniela

**Comment by I050689** [comment]
Hello,

My error :  I used an sqldevelopper for oracle 11g. Is not working.
But with a sqldevelopper for oracle 12 is ok.

Sorry for this.

Thank you very much.
