### ISSUE TITLE
Selinux And Volumes

### ISSUE THREAD

**Issue by Ijlalh90** [oracle/docker-images#396]
Hi i am working on Selinux on oracle Linux.I installed  docker and installed one docker image of oracle database.There is one database script when i run as Selinux enabled causes issues with mounting.When i disable the container can mount but when i enable selinux it doesn't allow to create volume.I tried chchon and making selinux module.Tried with mount -v option but still the issue remains same

**Comment by craigbarrau** [comment]
I'm not an SELinux expert so not sure on the proper solution (I'd love to hear that too) but you should be able workaround this issue by using a data container mapped to the volume as it will require less permissions on the OS from SELinux perspective.

Something like this should allow you to boot the container (at least that works for MySQL - the same may or may not be true for Oracle database but worth a shot!).
```
docker run -d --name ora-data oracle/database:12.2.0.1:ee echo "data-only container"
docker run --name db --volumes-from ora-data -d oracle/database:12.2.0.1:ee
```

**Comment by Ijlalh90** [comment]
Now let me explain what  i have used and what is going on
I used a docker image of oracle database running on oracle linux 7.3 inside a virtualbox.
There is an script in image which runs itself and creates the database and mounts it in /var/lib/docker/volume/container_name
This was working fine on Linux mint 18.1.But it is creating issues with oracle linux when selinux is enabled.
https://hub.docker.com/r/alanpeng/oracledatabase-11g-r2-ee/
I have tried to use -v but still not works 
![screenshot from 2017-05-23 13-36-04](https://cloud.githubusercontent.com/assets/22050218/26345624/e47f942c-3fbc-11e7-881b-71476f0047d7.png)
![screenshot from 2017-05-23 13-35-48](https://cloud.githubusercontent.com/assets/22050218/26345625/e4b1a28c-3fbc-11e7-9414-046418fd77db.png)





![screenshot from 2017-05-23 13-35-48](https://cloud.githubusercontent.com/assets/22050218/26345625/e4b1a28c-3fbc-11e7-9414-046418fd77db.png)

**Comment by craigbarrau** [comment]
Are you able to share the exact steps you ran against Oracle Linux 7.3 to get to that point where it is showing `Permission denied`?

**Comment by Ijlalh90** [comment]
Ok  i am sending the full commands i used in it
docker run -it --name=oracle --entrypoint=/bin/bash alanpeng/oracledatabase-11g-r2-ee
Then chmod +x entrypoint.sh
./entrypoint.sh
then after that what happens is shown in screenshots.
but when i run with selinux in permissive mode it works fine and ok.

**Comment by Ijlalh90** [comment]
Issue solved with the usage of security labels
