### ISSUE TITLE
Weblogic 12c image creation error

### ISSUE THREAD

**Issue by manik-chopra** [oracle/docker-images#397]
Following the instruction to create the weblogic image however getting the following error. All the files are present and looking good.

```
sh buildDockerImage.sh -v 12.2.1.1 -i
Checking if required packages are present and valid...
parseopts.c:76: setup_check: fopen 'Checksum.infrastructure': No such file or directory
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 12.2.1.1. See *.download files for more information
```

**Comment by kocic11** [comment]
@manik-chopra This version can't build WLS infrastructure image as there are no required files (Dockerfile.infrastructure and Checksum.infrastructure). 

You can try building WLS infrastructure image for 12.2.1.2 version.
