### ISSUE TITLE
Weblogic 12.2.1.2 build image error - oracle/serverjre not found

### ISSUE THREAD

**Issue by manik-chopra** [oracle/docker-images#403]
$ ./buildDockerImage.sh -v 12.2.1.2 -s
Skipped MD5 checksum.
=====================
Proxy settings were found and will be used during build.
Building image 'oracle/weblogic:12.2.1.2-infrastructure' ...
Sending build context to Docker daemon 34.82 kB
Step 1/13 : FROM oracle/serverjre:8
repository oracle/serverjre not found: does not exist or no pull access
There was an error building the image.

**Comment by manik-chopra** [comment]
Already build the java-8 JRE image as per below. 

# uka254 @ c4b301b76b6b in ~/GIT/OracleJava/java-8 [10:30:48]
$ ./build.sh
Sending build context to Docker daemon 4.608 kB
Step 1/5 : FROM oraclelinux:7-slim
 ---> 442ebf722584
Step 2/5 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Using cache
 ---> a8d44c2aa107
Step 3/5 : ENV JAVA_PKG server-jre-8u*-linux-x64.tar.gz JAVA_HOME /usr/java/default
 ---> Using cache
 ---> c3508ce279ea
Step 4/5 : ADD $JAVA_PKG /usr/java/
No source files were specified

**Comment by Djelibeybi** [comment]
Your `serverjre:8` build failed because it couldn't actually install the Server JRE. You need to make sure you have the tarball available in the same directory before building.

**Comment by mriccell** [comment]
@manik-chopra have you fixed this problem by following Djelibeybi's comment?

**Comment by mriccell** [comment]
I will close this issue due to lack of response, if you still have a problem please reopen the issue.

**Comment by punitporwal** [comment]
Building image 'oracle/weblogic:12.2.1.3-generic' ...
Sending build context to Docker daemon 15.87 kB
Step 1/13 : FROM oracle/serverjre:8
repository oracle/serverjre not found: does not exist or no pull access
There was an error building the image.

guys getting same issue any comment on this please..

**Comment by punitporwal** [comment]
to add: I have fmw_12.2.1.3.0_wls.jar on the same location

**Comment by madhuchilipi** [comment]
i copied the tar file it worked

**Comment by gintsgints** [comment]
Get [latest image from oracle](https://container-registry.oracle.com/pls/apex/f?p=113:1:113386954124203::NO::FSP_LANGUAGE_PREFERENCE:en-us&cs=3Geb2JtKDX2VEkonNgP1gSC4GDYHmJELW53Gtk2qgrr90W0_LtD2bbJCpda7BwCFdkNk8DqQk9Svv4_AA2xaXLA)
