### ISSUE TITLE
CheckSpace Error

### ISSUE THREAD

**Issue by paulofp79** [oracle/docker-images#408]
I have 56GB free and the docker creation is stopping in this error below:

 ---> Running in 335da166f7c5
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
checkSpace.sh: ERROR - There is not enough space available in the docker container.
checkSpace.sh: The container needs at least 15 GB available.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I check the script output and it looks ok:

[root@localhost dockerfiles]# df -B 1G . | tail -n 1 | awk '{ print $4 }'
44
[root@localhost dockerfiles]#

**Comment by paulofp79** [comment]
As a workaround I just change the REQUIRED_SPACE_GB=1 instead of REQUIRED_SPACE_GB=15. 

It works.

**Comment by gvenzl** [comment]
It's not a workaround but you essentially just durned off a prerequisite check for your image build. I highly recommend **not** to change any of the provided scripts as they are there for a good reason!

**Comment by paulofp79** [comment]
Hi Gerald,

The first time I tried I commented this script but the fix was to increase the value of docker size parameter and not the OS as per recommendation on this forum. It works after I changed as per recommendation.


Thanks,
Paulo

Sent from my iPhone

On 12 Jun 2017, at 15:36, Gerald Venzl <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not a workaround but you essentially just durned off a prerequisite check for your image build. I highly recommend not to change any of the provided scripts as they are there for a good reason!

**Comment by adrien-zinger** [comment]
Hi,

I have this problem again.

df -B 1G . | tail -n 1 | awk '{ print $4 }' return 25 and docker info says that the Base Device Size is 34.36 GB
I have 38G available on the host.

I'm still increasing the Base Device Size but the script always returns : 
checkSpace.sh: The container needs at least 15 GB , but only **6** available.

What I'm doing wrong?

Thanks,
Adrien

**Comment by juakokk** [comment]
hello all a question Adrian as you did to increase the storage space on the host beforehand thanks

**Comment by adrien-zinger** [comment]
I opened a new issue for this. It was a little bit more complex. You can see  #565. Thanks anyway !

**Comment by RakeshNagarajan** [comment]
Remove the old image (Oracle-linux)
REstart the docker

Since the old image will holds the info of previous dm.base size. this can't be updated. so please pull the new latest image and work.

This worked for me
