### ISSUE TITLE
Which of these apply, if any? [linux] ./hints/linux.sh: line 174: gcc: command not found

### ISSUE THREAD

**Issue by paulofp79** [oracle/docker-images#409]
When trying to create 12.2 image I got this error:

Which of these apply, if any? [linux]
./hints/linux.sh: line 174: gcc: command not found

.
.
Use which C compiler? [cc]
./trygcc: line 10: cc: command not found
./trygcc: line 25: gcc: command not found

It seems the gcc package is missing. Where is the script that check for it? 

tks,
Portugal

**Comment by gvenzl** [comment]
Can you please share the entire output of the build? Otherwise it is hard to diagnose what may have gone wrong.

**Comment by paulofp79** [comment]
Hi Gvenzl,

Uploading the output. 

Thanks!
[Error-Build_Docker_Image_122.txt](https://github.com/oracle/docker-images/files/1055352/Error-Build_Docker_Image_122.txt)

**Comment by kocic11** [comment]
Paulo,

You have run out of space. The image size is limited to 10 GB (default
value):

Base Device Size: 10.74 GB

Increase the device size to 20GB and try again (see
http://www.projectatomic.io/blog/2016/03/daemon_option_basedevicesize/).

Regards,
Aleksandar

**Comment by paulofp79** [comment]
Hi  Aleksandar,

I just changed it but same error. It seems the command cannot find linux.sh script. 

Attached the output now with 20GB on Base Device Size: 

[new_error_oracle_db_docker.txt](https://github.com/oracle/docker-images/files/1055896/new_error_oracle_db_docker.txt)

**Comment by kocic11** [comment]
You are still running out of space:

Preparing to launch Oracle Universal Installer from
/tmp/OraInstall2017-06-02_10-49-05AM. Please wait ...[FATAL] [INS-32021]
Installer has detected that the available disk space on the volume for
Oracle home (/opt/oracle/product/12.2.0.1/dbhome_1) is insufficient.

Check your host file system:
df -h

Regards,
Aleksnadar

**Comment by paulofp79** [comment]
Hi Aleksnadar,

I have plenty space on my OS:

-bash-4.2# df -h /opt
Filesystem           Size  Used Avail Use% Mounted on
/dev/mapper/ol-root   59G   25G   35G  42% /
-bash-4.2# df -h /tmp
Filesystem           Size  Used Avail Use% Mounted on
/dev/mapper/ol-root   59G   25G   34G  43% /

I will try to remove old docker images from failed installation to free up some more and try again.

Tks anyway!

**Comment by gvenzl** [comment]
Hm, this is strange. The `checkSpace.sh` script should actually make sure that there is enough space available inside the container. In this case I would have thought it would throw an error and state that there isn't enough space available, but it doesn't. 

Can you go inside the intermediate container and run `df -h` there and see how much space you actually got?

**Comment by paulofp79** [comment]
Hi G,

Just to let you know, after I remove old images and installed again, it finished with : 

Removing intermediate container 684da19a705d
ApplyLayer signal: hangup stdout:  stderr:
There was an error building the image.

But it seems to be working. I'm doing some tests. 

Tks,

**Comment by paulofp79** [comment]
Hi Aleksandar,

I have done that yesterday as you advised.

Tks,
Portugal
Sent from my iPhone

On 6 Jun 2017, at 12:37, Aleksandar Kocic <notifications@github.com<mailto:notifications@github.com>> wrote:

Paulo,

You have run out of space. The image size is limited to 10 GB (default
value):

Base Device Size: 10.74 GB

Increase the device size to 20GB and try again (see
http://www.projectatomic.io/blog/2016/03/daemon_option_basedevicesize/).

Regards,
Aleksandar

**Comment by gvenzl** [comment]
Glad to hear @paulofp79, although you shouldn't see `There was an error building the image` on a successful build of the image. Is the problem now solved?

**Comment by gvenzl** [comment]
Closing due to lack of response.
