### ISSUE TITLE
Handling docker stop on base WLS images

### ISSUE THREAD

**Issue by aseembajaj** [oracle/docker-images#410]
(Ref @mriccell & @Djelibeybi)
Hi Monica,

Avi asked me to create this trackable issue for you. Here is the issue, as being discussed here:
https://github.com/oracle/docker-images/pull/401/files/27aede9ce9a19b938d187612ca04d966328bac62#diff-6f66197890c7328aa441744e5a168c03

docker stop isn't converted to a forceShutdown request for WLS server. Here is what I tried:

```
docker pull container-registry.oracle.com/middleware/weblogic:12.2.1.1
docker run container-registry.oracle.com/middleware/weblogic:12.2.1.1
```

And then on the side I issued a docker stop request using a generated container name

```
docker stop epic_meitner
```

I can see that shutdown hook is not invoked, and the container stopped after 10 seconds (the default difference between the time SIGTERM and SIGKILL are sent to the container process)

Had it worked, I would have expected to see something like the following on stdout of the container:

```
<Jun 5, 2017 3:18:30,533 PM PDT>  
<Jun 5, 2017 3:18:30,534 PM PDT> <Server shutdown has been requested by .>
<Jun 5, 2017 3:18:30,538 PM PDT>  
<Jun 5, 2017 3:18:30,549 PM PDT>  
<Jun 5, 2017 3:18:30,549 PM PDT>  
<Jun 5, 2017 3:18:30,561 PM PDT>  
<Jun 5, 2017 3:18:30,601 PM PDT> <JMX Connector Server stopped at service:jmx:iiop://10.147.117.136:7001/jndi/weblogic.management.mbeanservers.edit.>
<Jun 5, 2017 3:18:30,602 PM PDT> <JMX Connector Server stopped at service:jmx:iiop://10.147.117.136:7001/jndi/weblogic.management.mbeanservers.domainruntime.>
<Jun 5, 2017 3:18:30,666 PM PDT> <JMX Connector Server stopped at service:jmx:iiop://10.147.117.136:7001/jndi/weblogic.management.mbeanservers.runtime.>
Stopping Derby server...
Derby server stopped.
```

**Comment by Djelibeybi** [comment]
There are `SIGTERM` and `SIGKILL` handlers but they're not working, so this is a bug not an enhancement.

**Comment by brunoborges** [comment]
@mriccell @aseembajaj any update on this?

**Comment by aseembajaj** [comment]
Hi @brunoborges,

@mriccell and I had initially discussed some refactoring in base image so that such signal trap can be re-used in derived image. The initial plan was for me to make the change. But @mriccell said that she/someone else will make the change now. So I have simply removed my implementation of signal trap in this image.

**Comment by brunoborges** [comment]
Should I close this issue then?

**Comment by aseembajaj** [comment]
@mriccell said that she will take care of that issue. Perhaps we can wait for her to respond when she is back. Or is that too long a wait?

**Comment by brunoborges** [comment]
We can wait :-)

**Comment by mriccell** [comment]
I am on vacation starting tonight, it will have to wait ;-)
Monica

**Comment by jwryoo** [comment]
Any update on this?

**Comment by brunoborges** [comment]
@mriccell can you take a look please?

**Comment by klauern** [comment]
So I was looking at the repository and one of my linters ([shellcheck](https://github.com/koalaman/shellcheck)) said that SIGKILL could not be trapped: [SC2713](https://github.com/koalaman/shellcheck/wiki/SC2173).  In addition to this, there is a [Wikipedia reference](https://en.wikipedia.org/wiki/Signal_(IPC)#Handling_signals) that says SIGKILL and SIGSTOP cannot be trapped.
