### ISSUE TITLE
Oracle database SE docker run: how to do a clean exit?

### ISSUE THREAD

**Issue by xamebax** [oracle/docker-images#412]
I am on Ubuntu 16.04 LTS, running a container with the Oracle Database 12c Standard Edition that I built from the Oracle Dockerfile using this command:

`$ docker run --name oracle-test -p 1521:1521 -p 5500:5500 -e ORACLE_CHARACTERSET=utf8 -e ORACLE_PWD=password oracle:latest`

Running takes a while, but after a few minutes I see the following output:

```
SQL> Disconnected from Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production
#########################
DATABASE IS READY TO USE!
#########################
The following output is now a tail of the alert.log:
Completed: alter pluggable database ORCLPDB1 open
2017-06-08T11:12:05.889753+00:00
ORCLPDB1(3):CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
ORCLPDB1(3):Completed: CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
ORCLPDB1(3):ALTER DATABASE DEFAULT TABLESPACE "USERS"
ORCLPDB1(3):Completed: ALTER DATABASE DEFAULT TABLESPACE "USERS"
2017-06-08T11:12:07.701215+00:00
ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORCLCDB/control01.ctl' SCOPE=SPFILE;
   ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
Completed:    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE

2017-06-08T11:21:42.809202+00:00
ORCLPDB1(3):Resize operation completed for file# 10, old size 337920K, new size 358400K
```

After 15 minutes of inactivity, I stopped the container using CTRL-C. I could then start it again without errors and it is still running, but is stopping the container after the first run and then starting it again the only way to have the container run in the background? I am using Chef to administer docker images and containers across our infrastructure and I have no way to perform such an exit in an automated way, without a failed Chef run. Am I missing something?

**Comment by gvenzl** [comment]
@xamebax, the database will be created the very first time you start up the container. Once this is done you will see a `tail` of the alert log, see message `The following output is now a tail of the alert.log:`.

If you want to run the container in the background, you can do so by using the [Docker `detach (-d or --detach)` option](https://docs.docker.com/engine/reference/commandline/run/#options):

```
[root@localhost ~]# docker run -d --name oracle-test -p 1521:1521 -p 5500:5500 -e ORACLE_CHARACTERSET=utf8 -e ORACLE_PWD=password oracle/database:12.2.0.1-ee
2a1cf74b632321323c7d186e875c625106f5d869ba212714d96482609aee4205
[root@localhost ~]# docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                            NAMES
2a1cf74b6323        oracle/database:12.2.0.1-ee   "/bin/sh -c 'exec $OR"   17 seconds ago      Up 12 seconds       0.0.0.0:1521->1521/tcp, 0.0.0.0:5500->5500/tcp   oracle-test
```
