### ISSUE TITLE
Oracle database 12.2.0.1 EE build fails - chown error

### ISSUE THREAD

**Issue by gdrobish** [oracle/docker-images#413]
Error during build is:
```
chown: changing ownership of '/opt/oracle/install/linuxx64_12201_database.zip': File too large
Removing intermediate container d581497c401d
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE' returned a non-zero code: 1
```

OS Oracle Linux 7.3
Docker version 17.05

I was using overlay2 storage driver with xfs backing fs.  I switched to overlay and encountered the same error.

I accessed the failed container and ran the chown command manually which fails in the same way.
```
bash-4.2# ls -ltra
total 3372784
-rwxr-xr-x 1 oracle dba         876 Jun  7 18:22 setupLinuxEnv.sh
-rwxr-xr-x 1 oracle dba        1065 Jun  7 18:22 installPerl.sh
-rwxr-xr-x 1 oracle dba        2057 Jun  7 18:22 installDBBinaries.sh
-rw-r--r-- 1 oracle dba        6878 Jun  7 18:22 db_inst.rsp
-rwxr-xr-x 1 oracle dba         839 Jun  7 18:22 checkSpace.sh
-rw-r--r-- 3 root   root 3453696911 Jun  7 18:45 linuxx64_12201_database.zip
drwxr-xr-x 2 oracle dba        4096 Jun  8 04:03 .
drwxr-xr-x 4 oracle dba        4096 Jun  8 04:26 ..
bash-4.2# chown -v oracle:dba linuxx64_12201_database.zip
chown: changing ownership of 'linuxx64_12201_database.zip': File too large
failed to change ownership of 'linuxx64_12201_database.zip' from root:root to oracle:dba
bash-4.2# df -h
Filesystem                   Size  Used Avail Use% Mounted on
overlay                      8.8T   32G  8.7T   1% /
tmpfs                        252G     0  252G   0% /dev
tmpfs                        252G     0  252G   0% /sys/fs/cgroup
/dev/mapper/docker_base-var  8.8T   32G  8.7T   1% /etc/hosts
shm                           64M     0   64M   0% /dev/shm
tmpfs                        252G     0  252G   0% /sys/firmware
bash-4.2#
```

Making a copy of the 12.2.0.1 install file to the same directory and running the same chown command on that works without issue.

**Comment by gvenzl** [comment]
@Djelibeybi, any ideas why the `chown` command fails and works on a copy of the file?

@gdrobish is this issue always reproducible? Can you provide the output of `docker info`?

**Comment by gdrobish** [comment]
@gvenzl, 
Yes it appears that this issue is always reproducible with overlay or overlay2 (and xfs backing fs).

```
docker info
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 0
Server Version: 17.05.0-ee
Storage Driver: overlay2
Backing Filesystem: xfs
Supports d_type: true
Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
seccomp
  Profile: default
Kernel Version: 4.1.12-94.3.5.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 503.6GiB
ID: PQQZ:N2D7:OKKM:LKOJ:AVYI:JPYV:YRWR:LEHB:AGFN:O74N:MSAE:PVEM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
```
I decided to switch to devicemapper to workaround this issue.  I can now successfully build the image with devicemapper storage driver using a thin pool  and dm.basesize=20g.  In retrospect, devicemapper may be a better choice for me anyways.

Observations:
Prior to switching to devicemapper, I tried to check for a possible bug in chown.  coreutils 8.22 is standard in ol7_latest.  I tried rerunning the manual chown command with the newest coreutils 8.27 but it still failed in the same way.  

I also tried moving the source db zip file to same xfs filesystem prior to running the build (my thoughts were that it might avoid any potential issue with cross-device links or something along those lines during the Dockerfile copy) but it still failed in the same way.

As mentioned above, the chown root:root to oracle:dba works on a cp of the zip file but fails on the original when accessing the failed container and running the command manually.

Also, the entire build process works okay when using devicemapper which is  now what I am using.

**Comment by gvenzl** [comment]
Thanks for the update @gdrobish. It sounds very strange and almost as if there is an issue with the underlying `overlay2` driver or `xfs`. If you feel like it, perhaps you can open another issue for Docker to track that on their end but in any case, given that your problem is solved I will close this issue for now.
