### ISSUE TITLE
Support for creating Fusion Middleware Domain using Docker

### ISSUE THREAD

**Issue by VijayMalapaka** [oracle/docker-images#416]
Hi,

The dockerfiles that are provided are very useful.

We are working on ADF applications.
For our applications, we create fusion middleware domain using configuration wizard by executing "config.sh" located at "/u01/oracle/oracle_common/common/bin".
Once we create a domain, a set of libraries will be available and these libraries are needed for our application deployment and runtime.

So could you please provide us the solution for this using docker. 

Thanks in advance.

**Comment by brunoborges** [comment]
You can create a domain template, and then import it using command line tools (WLST) while building the image. Since this is not really an issue, I will close it, but we may continue the conversation.

**Comment by mriccell** [comment]
There is a push request just waiting for review for a new  FMW Infrastructure image.  One of the purposes of this  image is to extend it and deploy ADF applications.  As part of the image there are WLST scripts to create a base domain  that extends the WLS domain and applies the JRF templates.  Please use this image as an example for your work.
