### ISSUE TITLE
Missing versions and no XE on https://container-registry.oracle.com (Oracle Database)

### ISSUE THREAD

**Issue by veqryn** [oracle/docker-images#419]
Hi,
For Dev, I am using the containers for the Enterprise and Standard editions of Oracle Database found on your container registry: https://container-registry.oracle.com

There are:
container-registry.oracle.com/database/enterprise:12.1.0.2
container-registry.oracle.com/database/standard:12.1.0.2
container-registry.oracle.com/database/instantclient:12.2.0.1

Where is the Express Edition (XE)?  Can you guys upload it to the registry please?

Also, it would be nice to fill in all versions, that way we can use the right container in dev to match the version of Oracle Database that we run in production. For example, please also create tags for EE and SE 12.2.01, and Instant Client 12.1.0.2.

thanks!

**Comment by Djelibeybi** [comment]
The Database team will not be publishing the XE image, nor are they planning to release older versions of products. We will only be publishing newer versions moving forward.

**Comment by veqryn** [comment]
Why no XE?  I'm just curious... It is a lesss heavy on the cpu/memory to run on older laptops than EE...

**Comment by Djelibeybi** [comment]
I'll let @gvenzl answer that one.

**Comment by stickycode** [comment]
So still no images 2 years later? Will there be new images in the official registry?
