### ISSUE TITLE
Unable to create database instance because of insufficient disk space

### ISSUE THREAD

**Issue by ruettimac** [oracle/docker-images#422]
On our host we are able to start 4 database instances. Starting with the fifth instance, it's not possible anymore to create an instance anymore at the same mount point. It fails with the following message:

`Jun 21 20:13:32 20208XAT02 journal: LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 21-JUN-2017 18:13:32
Jun 21 20:13:32 20208XAT02 journal: 
Jun 21 20:13:32 20208XAT02 journal: Copyright (c) 1991, 2016, Oracle.  All rights reserved.
Jun 21 20:13:32 20208XAT02 journal: 
Jun 21 20:13:34 20208XAT02 journal: Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...
Jun 21 20:13:34 20208XAT02 journal: 
Jun 21 20:13:34 20208XAT02 journal: TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Jun 21 20:13:34 20208XAT02 journal: System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Jun 21 20:13:34 20208XAT02 journal: Log messages written to /opt/oracle/diag/tnslsnr/1e5faa277aee/listener/alert/log.xml
Jun 21 20:13:34 20208XAT02 journal: Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Jun 21 20:13:34 20208XAT02 journal: Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
Jun 21 20:13:34 20208XAT02 journal: 
Jun 21 20:13:34 20208XAT02 journal: Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
Jun 21 20:13:34 20208XAT02 journal: STATUS of the LISTENER
Jun 21 20:13:34 20208XAT02 journal: ------------------------
Jun 21 20:13:34 20208XAT02 journal: Alias                     LISTENER
Jun 21 20:13:34 20208XAT02 journal: Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Jun 21 20:13:34 20208XAT02 journal: Start Date                21-JUN-2017 18:13:34
Jun 21 20:13:34 20208XAT02 journal: Uptime                    0 days 0 hr. 0 min. 0 sec
Jun 21 20:13:34 20208XAT02 journal: Trace Level               off
Jun 21 20:13:34 20208XAT02 journal: Security                  ON: Local OS Authentication
Jun 21 20:13:34 20208XAT02 journal: SNMP                      OFF
Jun 21 20:13:34 20208XAT02 journal: Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Jun 21 20:13:34 20208XAT02 journal: Listener Log File         /opt/oracle/diag/tnslsnr/1e5faa277aee/listener/alert/log.xml
Jun 21 20:13:34 20208XAT02 journal: Listening Endpoints Summary...
Jun 21 20:13:34 20208XAT02 journal:  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Jun 21 20:13:34 20208XAT02 journal:  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
Jun 21 20:13:34 20208XAT02 journal: The listener supports no services
Jun 21 20:13:34 20208XAT02 journal: The command completed successfully
Jun 21 20:13:37 20208XAT02 journal: [FATAL] [DBT-06604] The location specified for 'Fast Recovery Area Location' has insufficient free space.
Jun 21 20:13:37 20208XAT02 journal:   CAUSE: Only (9,433MB) free space is available on the location (/opt/oracle/oradata/fast_recovery_area/AFPCLASSIC/).
Jun 21 20:13:37 20208XAT02 journal:   ACTION: Choose a 'Fast Recovery Area Location' that has enough space (minimum of (12,780MB)) or free up space on the specified location.
Jun 21 20:13:37 20208XAT02 journal: cat: /opt/oracle/cfgtoollogs/dbca/AFPCLASSIC/AFPCLASSIC.log: No such file or directory
Jun 21 20:13:37 20208XAT02 journal: cat: /opt/oracle/cfgtoollogs/dbca/AFPCLASSIC.log: No such file or directory
Jun 21 20:13:38 20208XAT02 journal: 
Jun 21 20:13:38 20208XAT02 journal: SQL*Plus: Release 12.2.0.1.0 Production on Wed Jun 21 18:13:38 2017
Jun 21 20:13:38 20208XAT02 journal: 
Jun 21 20:13:38 20208XAT02 journal: Copyright (c) 1982, 2016, Oracle.  All rights reserved.
Jun 21 20:13:38 20208XAT02 journal: 
Jun 21 20:13:39 20208XAT02 journal: Connected to an idle instance.
Jun 21 20:13:39 20208XAT02 journal: 
Jun 21 20:13:39 20208XAT02 journal: SQL>    ALTER SYSTEM SET control_files='/opt/oracle/oradata/AFPCLASSIC/control01.ctl' scope=spfile
Jun 21 20:13:39 20208XAT02 journal: *
Jun 21 20:13:39 20208XAT02 journal: ERROR at line 1:
Jun 21 20:13:39 20208XAT02 journal: ORA-01034: ORACLE not available
Jun 21 20:13:39 20208XAT02 journal: Process ID: 0
Jun 21 20:13:39 20208XAT02 journal: Session ID: 0 Serial number: 0
Jun 21 20:13:39 20208XAT02 journal: 
Jun 21 20:13:39 20208XAT02 journal: 
Jun 21 20:13:39 20208XAT02 journal: SQL>    ALTER PLUGGABLE DATABASE AFPCLASSIC1 SAVE STATE
Jun 21 20:13:39 20208XAT02 journal: *
Jun 21 20:13:39 20208XAT02 journal: ERROR at line 1:
Jun 21 20:13:39 20208XAT02 journal: ORA-01034: ORACLE not available
Jun 21 20:13:39 20208XAT02 journal: Process ID: 0
Jun 21 20:13:39 20208XAT02 journal: Session ID: 0 Serial number: 0
Jun 21 20:13:39 20208XAT02 journal: 
Jun 21 20:13:39 20208XAT02 journal: 
Jun 21 20:13:39 20208XAT02 journal: SQL> Disconnected
Jun 21 20:13:39 20208XAT02 journal: mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileAFPCLASSIC.ora': No such file or directory
Jun 21 20:13:39 20208XAT02 journal: mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwAFPCLASSIC': No such file or directory
Jun 21 20:13:40 20208XAT02 journal: #####################################
Jun 21 20:13:40 20208XAT02 journal: ########### E R R O R ###############
Jun 21 20:13:40 20208XAT02 journal: DATABASE SETUP WAS NOT SUCCESSFUL!
Jun 21 20:13:40 20208XAT02 journal: Please check output for further info!
Jun 21 20:13:40 20208XAT02 journal: ########### E R R O R ###############
Jun 21 20:13:40 20208XAT02 journal: #####################################`

If I move the host volume to another mount point, I am able to create additional instances,. Restarting docker or the whole machine does not resolve the issue.

The operating system is RedHat Enterprise Linux 7.3. df -h shows me:

`Filesystem                            Size  Used Avail Use% Mounted on
/dev/mapper/rhel_20208xat02-root       18G  1.9G   17G  11% /
devtmpfs                               16G     0   16G   0% /dev
tmpfs                                  16G     0   16G   0% /dev/shm
tmpfs                                  16G   17M   16G   1% /run
tmpfs                                  16G     0   16G   0% /sys/fs/cgroup
/dev/sda1                            1014M  184M  831M  19% /boot
/dev/mapper/docker_vg-docker_lv        80G   19G   62G  23% /var/lib/docker
/dev/mapper/docker_vg-docker_vols_lv   20G   11G  9.3G  54% /var/docker/volumes
tmpfs                                 3.2G     0  3.2G   0% /run/user/0`

**Comment by saily** [comment]
I think you reached the default `10GB` container size limit. You should put your databases onto a mountpoint or increase the container size in docker by passing `--storage-opt` to your docker agent, put:

    DOCKER_STORAGE_OPTIONS=--storage-opt dm.basesize=20G

in your `/etc/sysconfig/docker-storage` file (may vary on your distro, storage backend and docker startup script). Please note you have to clear the docker storage folder and restart docker after changing this.

**Comment by ruettimac** [comment]
Thanks for the hint. That could be the case. But anyhow, there must be a bug. Because when I delete some images on the mount point, I still get the error message. But this does not happen on MacOS X with the latest docker version. The issue was detected on RedHat Enterprise Linux 7.3.

**Comment by brunoborges** [comment]
This is definitely an issue with the local Docker environment.

Thanks @saily for pointing it out.

**Comment by ramprakashr** [comment]
Reinstall the docker and initiate the oracle setup from scratch, This worked for me!
