### ISSUE TITLE
Build scripts for Windows users (.PS1)?

### ISSUE THREAD

**Issue by klauern** [oracle/docker-images#424]
I run Docker for Windows, and it's a bit difficult to translate all of the build.sh scripts to work with PowerShell.  I'm not a PowerShell developer, but I was wondering if adding a set of windows build scripts would be worthwhile or not.  Perhaps I'm missing something on how to use the shell scripts from within Windows (I do have WSL, but I have not gotten that interplay between Docker on Windows and WSL+Bash to work) that would make this easier?

**Comment by brunoborges** [comment]
Hi @klauern, 

Unfortunately no one from the team who maintains these files have a Windows machine, and therefore we can't commit to that. If all you want is to use these images, you can find pre-built ones either on the [Docker Store](https://store.docker.com/search?certification_status=certified&q=oracle&source=verified&type=image), [Docker Hub](https://hub.docker.com/u/oracle/) or on our own [Container Registry server](https://container-registry.oracle.com/).

Thanks
