### ISSUE TITLE
Oracle 11g XE: container_linux.go:262: starting container process caused "exec: "-m": executable file not found in $PATH"

### ISSUE THREAD

**Issue by paulosincos** [oracle/docker-images#428]
Hi, I'm having problems do run 11g XE.

On building, this error appears:

```
/var/tmp/rpm-tmp.XJH5CT: line 257: [: 18446744073692774399: integer expression expected
/var/tmp/rpm-tmp.XJH5CT: line 271: [: 18446744073692774399: integer expression expected
sysctl: setting key "fs.file-max": Read-only file system
```

But, a success message is showed after.

After, on try run, this error occurs:

```
container_linux.go:262: starting container process caused "exec: \"-m\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"-m\": executable file not found in $PATH".
```

I'm try in two enviroments:
Ubuntu 16.04
Windows 10 Pro

In Windows 10, building only works with the solution https://github.com/ogobrecht/docker-ora11xe-swap-check-disabler. But the error messages are the same.

Thanks for any help!

**Comment by gvenzl** [comment]
Hi @paulosincos, can you please provide the entire build output.

**Comment by gvenzl** [comment]
Closing due to lack of response.
