### ISSUE TITLE
getting errors in step 8 with cc or gcc not found altough cc/gcc exists

### ISSUE THREAD

**Issue by sd2302** [oracle/docker-images#432]
Any idea? Why Oracle product never works?

```
[oracle@ora-sna-0032 ~]$ which cc
/usr/bin/cc
[oracle@ora-sna-0032 ~]$ which gcc
/usr/bin/gcc
```

Error stack:
Error:

```
dos_djgpp     interix         newsos4           solaris_2
Which of these apply, if any? [linux]
./hints/linux.sh: line 174: gcc: command not found

You don't have an ELF gcc.  I will use dld if possible.  If you are
using a version of DLD earlier than 3.2.6, or don't have it at all, you
should probably upgrade. If you are forced to use 3.2.4, you should
uncomment a couple of lines in hints/linux.sh and restart Configure so
that shared libraries will be disallowed.


Disabling ndbm.  This will generate a Whoa There message in Configure.
Read hints/linux.sh for further information.
Operating system name? [linux]
Operating system version? [3.10.0-514.21.2.el7.x86_64]
Installation prefix to use? (~name ok)
[/opt/oracle/product/12.2.0.1/dbhome_1/perl]
Directory /opt/oracle/product/12.2.0.1/dbhome_1/perl doesn't exist.  Use that name anyway?
[y]
AFS does not seem to be running...
What installation prefix should I use for installing files? (~name ok)
[/opt/oracle/product/12.2.0.1/dbhome_1/perl]
Directory /opt/oracle/product/12.2.0.1/dbhome_1/perl doesn't exist.  Use that name anyway?
[y]
Getting the current patchlevel...
Build a threading Perl? [y]
Use which C compiler? [cc]
./trygcc: line 10: cc: command not found
Uh-oh, the C compiler 'cc' doesn't seem to be working.
./trygcc: line 25: gcc: command not found
./checkcc: line 10: cc: command not found
Uh-oh, the C compiler 'cc' doesn't seem to be working.
You need to find a working C compiler.
Either (purchase and) install the C compiler supplied by your OS vendor,
or for a free C compiler try http://gcc.gnu.org/
I cannot continue any further, aborting.
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
/opt/oracle/install/installPerl.sh: line 26: cd: /opt/oracle/product/12.2.0.1/dbhome_1/perl: No such file or directory
cp: cannot stat '../perl.old/lib/': No such file or directory
cp: cannot stat '../perl.old/man/': No such file or directory
cp: cannot stat '../perl.old/bin/dbilogstrip': No such file or directory
cp: cannot stat '../perl.old/bin/dbiprof': No such file or directory
cp: cannot stat '../perl.old/bin/dbiproxy': No such file or directory
cp: cannot stat '../perl.old/bin/ora_explain': No such file or directory
/opt/oracle/install/installPerl.sh: line 34: cd: /opt/oracle/product/12.2.0.1/dbhome_1/lib: No such file or directory
/opt/oracle/install/installPerl.sh: line 38: cd: /opt/oracle/product/12.2.0.1/dbhome_1/bin: No such file or directory
/opt/oracle/install/installPerl.sh: line 39: relink: command not found
 ---> d89319bec09f
Removing intermediate container 4e65ff3cfd96
Step 10 : USER root
 ---> Running in 5cd7e759b9c8
 ---> b740d2358dbe
Removing intermediate container 5cd7e759b9c8
Step 11 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in 9485aa3d0dda
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
Removing intermediate container 9485aa3d0dda
The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR' returned a non-zero code: 127
There was an error building the image.

gcc version:

[oracle@ora-sna-0032 ~]$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
```

**Comment by brunoborges** [comment]
Can you provide more information on what you are trying to do?

**Comment by sd2302** [comment]
I am trying to build the Oracle image using this:
git clone https://github.com/oracle/docker-images.git
download oracle_install_12.2.0.1.zip  in dockerfile/12.2.0.2
./buildDockerImage.sh -v 12.2.0.1 -e -i

**Comment by brunoborges** [comment]
What Linux are you using, and what Docker version do you have?

**Comment by sd2302** [comment]
[root@hak-dal-d007 12.2.0.1]# docker -v
Docker version 1.12.6, build 88a4867/1.12.6
[root@hak-dal-d007 12.2.0.1]# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Network"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

**Comment by brunoborges** [comment]
@gvenzl @Djelibeybi any idea what could possibly be ?

**Comment by Djelibeybi** [comment]
This is something for @gvenzl as it's part of the build process of the image itself.

**Comment by gvenzl** [comment]
This is most likely because something did go wrong further up during the software installation. Can you please provide the output of the entire build?

**Comment by SRINIVASREDDYPV** [comment]
When using the latest clone of this repository (commit b4f2f00) to build an Docker image for the Oracle Database 12c Enterprise Edition I get the following error:

-----------------------------------------------------------------------------------------------------------
Checking Temp space: must be greater than 500 MB.   Actual 60288 MB    Passed
Checking swap space: must be greater than 150 MB.   Actual 23232 MB    Passed
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-07-07_05-46-05AM. Please wait ...[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
You can find the log of this install session at:
 /opt/oracle/oraInventory/logs/installActions2017-07-07_05-46-05AM.log
The installation of Oracle Database 12c was successful.
Please check '/opt/oracle/oraInventory/logs/silentInstall2017-07-07_05-46-05AM.log' for more details.

As a root user, execute the following script(s):
        1. /opt/oracle/product/12.2.0.1/dbhome_1/root.sh



Successfully Setup Software.

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

 ---> a09e25780715
Removing intermediate container 5881157eda05
Step 12/18 : USER root
 ---> Running in e7d610430de9
 ---> c9d85fa663b4
Removing intermediate container e7d610430de9
Step 13/18 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in 13e7d986cbd4
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
Removing intermediate container 13e7d986cbd4
The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR' returned a non-zero code: 127

Please find the attached build log and DB installation log

[installActions2017-07-07_02-28-42AM.txt](https://github.com/oracle/docker-images/files/1130473/installActions2017-07-07_02-28-42AM.txt)
[build.txt](https://github.com/oracle/docker-images/files/1130474/build.txt)

[root@whf00aiv dockerfiles]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 39
Server Version: 17.03.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.1.12-61.1.27.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 29.47 GiB
Name: whf00aiv.in.oracle.com
ID: IT5E:CE7J:VM7H:U3AV:YHYB:LBZL:6OY2:WZKR:O4GS:QTCR:ZIAE:H4MY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

@gvenzl , Can you please assist me if you have some time ?

**Comment by bobbyoommen** [comment]
I have the exact issue, and trying to find a solution. Could anyone help....

Use which C compiler? [cc]  
./trygcc: line 10: cc: command not found
Uh-oh, the C compiler 'cc' doesn't seem to be working.
./trygcc: line 25: gcc: command not found
./checkcc: line 10: cc: command not found
Uh-oh, the C compiler 'cc' doesn't seem to be working.
You need to find a working C compiler.
Either (purchase and) install the C compiler supplied by your OS vendor,
or for a free C compiler try http://gcc.gnu.org/
I cannot continue any further, aborting.
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
/opt/oracle/install/installPerl.sh: line 26: cd: /opt/oracle/product/12.2.0.1/dbhome_1/perl: No such file or directory
cp: cannot stat '../perl.old/lib/': No such file or directory
cp: cannot stat '../perl.old/man/': No such file or directory
cp: cannot stat '../perl.old/bin/dbilogstrip': No such file or directory
cp: cannot stat '../perl.old/bin/dbiprof': No such file or directory
cp: cannot stat '../perl.old/bin/dbiproxy': No such file or directory
cp: cannot stat '../perl.old/bin/ora_explain': No such file or directory
/opt/oracle/install/installPerl.sh: line 34: cd: /opt/oracle/product/12.2.0.1/dbhome_1/lib: No such file or directory
/opt/oracle/install/installPerl.sh: line 38: cd: /opt/oracle/product/12.2.0.1/dbhome_1/bin: No such file or directory
/opt/oracle/install/installPerl.sh: line 39: relink: command not found
---> 4fdaa8483dbd
Removing intermediate container 1cc6c8f4b5b4
Step 10/16 : USER root
 ---> Running in 60f7f034c4d4
 ---> 317e443916be
Removing intermediate container 60f7f034c4d4
Step 11/16 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in 670f46592cef
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
Removing intermediate container 670f46592cef
The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR' returned a non-zero code: 127
There was an error building the image.

**Comment by bobbyoommen** [comment]
[docker_oracle.txt](https://github.com/oracle/docker-images/files/1140782/docker_oracle.txt)

attaching the whole output

**Comment by gvenzl** [comment]
@bobbyoommen, your installation fails because you don't have enough disk space available:

```
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-07-12_03-17-20AM. Please wait ...
[FATAL] [INS-32021] Installer has detected that the available disk space on the volume for Oracle home (/opt/oracle/product/12.2.0.1/dbhome_1) is insufficient.
   ACTION: Choose a location for Oracle home that has enough space (minimum of 7,680MB) or free up space on the existing volume.
A log of this session is currently saved as: /tmp/OraInstall2017-07-12_03-17-20AM/installActions2017-07-12_03-17-20AM.log. Oracle recommends that if you want to keep this log, you should move it from the temporary location.\
```

You need at least 15GB available for the image to build, your `docker info` output suggests that you only have 10GB per container configured:

```
Storage Driver: devicemapper\
 Pool Name: docker-253:0-85054054-pool\
 Pool Blocksize: 65.54kB\
 Base Device Size: 10.74GB\
 Backing Filesystem: xfs\
```

**Comment by bobbyoommen** [comment]
Thank you. I removed and re-installed the docker engine. but getting a new error now.

 ---> 2601ec02d4ef
Removing intermediate container b9673ad5b3d1
Step 10/16 : USER root
 ---> Running in 6fbcb13ee1bb
 ---> a37f1d78377b
Removing intermediate container 6fbcb13ee1bb
Step 11/16 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in e1459d3695bb
Changing permissions of /opt/oracle/oraInventory.
Adding read,write permissions for group.
Removing read,write,execute permissions for world.

Changing groupname of /opt/oracle/oraInventory to dba.
The execution of the script is complete.
Check /opt/oracle/product/12.2.0.1/dbhome_1/install/root_4677f42c5ed9_2017-07-12_04-03-59-457166224.log for the output of root script
rm: cannot remove '/opt/oracle/install': Directory not empty
Removing intermediate container e1459d3695bb
The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR' returned a non-zero code: 1
There was an error building the image.

**Comment by bobbyoommen** [comment]
did a ping to the container id, so I could get in and see what's going on...

Did a 'cd' to /opt/oracle/install...and noticed this..

bash-4.2# ls -ltr install
ls: cannot access install/checkSpace.sh: No such file or directory
ls: cannot access install/installDBBinaries.sh: No such file or directory
ls: cannot access install/installPerl.sh: No such file or directory
ls: cannot access install/setupLinuxEnv.sh: No such file or directory
ls: cannot access install/db_inst.rsp: No such file or directory
total 0
?????????? ? ? ? ?            ? setupLinuxEnv.sh
?????????? ? ? ? ?            ? installPerl.sh
?????????? ? ? ? ?            ? installDBBinaries.sh
?????????? ? ? ? ?            ? db_inst.rsp
?????????? ? ? ? ?            ? checkSpace.sh
bash-4.2#

**Comment by Djelibeybi** [comment]
Can you please provide the output of `docker info` on this machine? This is a filesystem issue and if you're running RHEL7 or CentOS7, there may be an issue with that. 

Can you reproduce this issue on Oracle Linux 7 with either `btrfs` or the `overlay2` storage driver on an `xfs` filesystem (with `ftype=1` set when created).

**Comment by bobbyoommen** [comment]
docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.639GiB
Name: postgresql-docker
ID: K7NW:XB45:3TWQ:AAYU:OUUR:GEEM:CXSR:ZWRX:AW2E:AJIL:KST5:G2JS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by Djelibeybi** [comment]
Wow, there's a lot of issues there. I would strongly encourage you to switch from the `overlay` to `overlay2` storage driver and to move `/var/lib/docker` to an XFS filesystem that supports `d_type`, i.e. when you run `mkfs.xfs` you add `-n ftype=1`.

**Comment by bobbyoommen** [comment]
Thank you...creating a XFS for /var/lib/docker fixed it...
hanging groupname of /opt/oracle/oraInventory to dba.
The execution of the script is complete.
Check /opt/oracle/product/12.2.0.1/dbhome_1/install/root_4677f42c5ed9_2017-07-12_17-38-46-416663258.log for the output of root script
 ---> 032d926423e5
Removing intermediate container 0ea8375cfa12
Step 12/16 : USER oracle
 ---> Running in f95af7d48c3a
 ---> 61b0420316fe
Removing intermediate container f95af7d48c3a
Step 13/16 : WORKDIR /home/oracle
 ---> 3d85945bc87e
Removing intermediate container 4049a2685974
Step 14/16 : VOLUME $ORACLE_BASE/oradata
 ---> Running in 4af2312349cc
 ---> 6e59e2eb8de2
Removing intermediate container 4af2312349cc
Step 15/16 : EXPOSE 1521 5500
 ---> Running in 557e64f71ace
 ---> ddf0d9727761
Removing intermediate container 557e64f71ace
Step 16/16 : CMD exec $ORACLE_BASE/$RUN_FILE
 ---> Running in dc3691fbb59c
 ---> c0525fbfff52
Removing intermediate container dc3691fbb59c
Successfully built c0525fbfff52
Successfully tagged oracle/database:12.2.0.1-ee

  Oracle Database Docker Image for 'ee' version 12.2.0.1 is ready to be extended: 
    
    --> oracle/database:12.2.0.1-ee

  Build completed in 916 seconds.

**Comment by Djelibeybi** [comment]
Great. Glad to hear it's resolved.
