### ISSUE TITLE
unable to prepare context: unable to evaluate symlinks in Dockerfile path

### ISSUE THREAD

**Issue by gochev** [oracle/docker-images#446]
Currenly when I try to 
`sudo ./buildDockerImage.sh -v 12.2.0.1`

I get 

```Building image 'oracle/database:12.2.0.1-xe' ...
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/gochev/Install/docker-images/OracleDatabase/dockerfiles/12.2.0.1/Dockerfile.xe: no such file or directory
There was an error building the image.
```

the installation image linuxx64_12201_database.zip is placed inside 12.2.0.1 as required

I am using Mac OS X with Docker community edition Version 17.06.0-ce-mac18

**Comment by gochev** [comment]
my bad 
it looks I had to do 

`./buildDockerImage.sh -v 12.2.0.1 -e`

and it works

**Comment by gvenzl** [comment]
Thanks @gochev, based on your second comment I'm closing the issue.

**Comment by GamesGosling** [comment]
Amazing
