### ISSUE TITLE
add 12c sample to readme.md

### ISSUE THREAD

**Issue by sho-suzuki** [oracle/docker-images#450]
Hi. everyone.
current version of readme.md describe 11g's express edition example.
Could you add 12c ee's example like below.

- how to connect default cdb/pdb

```sql
sqlplus pdbadmin/password@localhost:1521/ORCLPDB1
sqlplus system/password@localhost:1521/ORCLCDB
sqlplus sys/password@localhost:1521/ORCLCDB as sysdba
```

thanks.

**Comment by Djelibeybi** [comment]
If those examples work (I'm not a Database person, so I've assigned this to @gvenzl), you should feel free to submit a pull request that adds those examples to the appropriate `README.md`. I'm sure @gvenzl would appreciate the assistance. :)

**Comment by sho-suzuki** [comment]
OK.
I have no time now, so I'll try later and send PR.

**Comment by gvenzl** [comment]
I'm not sure I fully understand the request.

The [ReadMe of the Oracle Database Docker images](https://github.com/oracle/docker-images/blob/master/OracleDatabase/README.md) already includes this information:

```
Once the container has been started and the database created you can connect to it just like to any other database:

sqlplus sys/<your password>@//localhost:1521/<your SID> as sysdba
sqlplus system/<your password>@//localhost:1521/<your SID>
sqlplus pdbadmin/<your password>@//localhost:1521/<Your PDB name>

The Oracle Database inside the container also has Oracle Enterprise Manager Express configured. To access OEM Express, start your browser and follow the URL:

https://localhost:5500/em/
```

**Comment by gvenzl** [comment]
Closing issue due to no response.
