### ISSUE TITLE
Docker image for Oracle Database 12.2.0.1 EE fails to build

### ISSUE THREAD

**Issue by SRINIVASREDDYPV** [oracle/docker-images#454]
I am getting the below error while building the docker image for oracle 12.2.0.1 enterprise edition. I am using the latest docker files from https://github.com/oracle/docker-images/tree/master/OracleDatabase. 

```
Checking Temp space: must be greater than 500 MB.   Actual 60288 MB    Passed
Checking swap space: must be greater than 150 MB.   Actual 23232 MB    Passed
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-07-07_05-46-05AM. Please wait ...[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
You can find the log of this install session at:
 /opt/oracle/oraInventory/logs/installActions2017-07-07_05-46-05AM.log
The installation of Oracle Database 12c was successful.
Please check '/opt/oracle/oraInventory/logs/silentInstall2017-07-07_05-46-05AM.log' for more details.

As a root user, execute the following script(s):
        1. /opt/oracle/product/12.2.0.1/dbhome_1/root.sh



Successfully Setup Software.

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

 ---> a09e25780715
Removing intermediate container 5881157eda05
Step 12/18 : USER root
 ---> Running in e7d610430de9
 ---> c9d85fa663b4
Removing intermediate container e7d610430de9
Step 13/18 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in 13e7d986cbd4
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
Removing intermediate container 13e7d986cbd4
The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR' returned a non-zero code: 127
```

Please find the attached logs for the more information.

[installActions2017-07-07_02-28-42AM.txt](https://github.com/oracle/docker-images/files/1130632/installActions2017-07-07_02-28-42AM.txt)
[build.txt](https://github.com/oracle/docker-images/files/1130633/build.txt)

```
[root@whf00aiv dockerfiles]# docker info
Containers: 2
Running: 0
Paused: 0
Stopped: 2
Images: 39
Server Version: 17.03.1-ce
Storage Driver: btrfs
Build Version: Btrfs v4.4.1
Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
seccomp
  Profile: default
Kernel Version: 4.1.12-61.1.27.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 29.47 GiB
Name: whf00aiv.in.oracle.com
ID: IT5E:CE7J:VM7H:U3AV:YHYB:LBZL:6OY2:WZKR:O4GS:QTCR:ZIAE:H4MY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
```

@gvenzl,  Please help me if you have some time.

**Comment by gvenzl** [comment]
Hi @SRINIVASREDDYPV, the root cause of this is `/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory`.
That file is auto generated by the Oracle Universal Install upon successful installation. However, the log shows that the installation was indeed successful but only one file was generated. It therefore seems to be the case that the `orainstRoot.sh` is not always created by under certain circumstances. I'll have to check whether that theory of mine is true and if so amend the install scripts appropriately.

**Comment by SRINIVASREDDYPV** [comment]
Hello @gvenzl , Thanks for your quick response. I will wait for the update.

**Comment by gvenzl** [comment]
It turns out that the orainstRoot.sh is only generated when there isn't an oraInventory in place yet. That means that in a clean build from the Oracle Linux base image the file should be there as no inventory exists in that base image yet. Are you building this image from scratch and is this issue reproducible?

**Comment by SRINIVASREDDYPV** [comment]
I am just using the Docker files created by you for building the database image. Yes the issue is reproducible.

**Comment by gvenzl** [comment]
I tried to reproduce this issue but couldn't. I wonder why in your image the installer thinks that the repository is already there, on an empty Linux slim image.

```[root@localhost dockerfiles]# ./buildDockerImage.sh -e
Checking if required packages are present and valid...
linuxx64_12201_database.zip: OK
==========================
DOCKER info:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.1.12-94.3.8.el7uek.x86_64
Operating System: Oracle Linux Server 7.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: localhost.localdomain
ID: GZ5A:XQWB:F5TE:56JE:GR3J:VCXJ:I7BO:EGMY:K52K:JAS3:A7ZC:BOHQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
==========================
Building image 'oracle/database:12.2.0.1-ee' ...
Sending build context to Docker daemon 3.454 GB
Step 1/16 : FROM oraclelinux:7-slim
7-slim: Pulling from library/oraclelinux
7bd9e1692b54: Pull complete
Digest: sha256:f1388709e1ce62dfa9cf9af9746bc0cca47b2e09975a1fb6ba01c66061b2b793
Status: Downloaded newer image for oraclelinux:7-slim
 ---> 08a01cc7be97
Step 2/16 : MAINTAINER Gerald Venzl <gerald.venzl@oracle.com>
 ---> Running in 53cd87d95208
 ---> fe48ae42f12b
Removing intermediate container 53cd87d95208
Step 3/16 : ENV ORACLE_BASE /opt/oracle ORACLE_HOME /opt/oracle/product/12.2.0.1/dbhome_1 INSTALL_FILE_1 "linuxx64_12201_database.zip" INSTALL_RSP "db_inst.rsp" CONFIG_RSP "dbca.rsp.tmpl" PWD_FILE "setPassword.sh" PERL_INSTALL_FILE "installPerl.sh" RUN_FILE "runOracle.sh" START_FILE "startDB.sh" CREATE_DB_FILE "createDB.sh" SETUP_LINUX_FILE "setupLinuxEnv.sh" CHECK_SPACE_FILE "checkSpace.sh" CHECK_DB_FILE "checkDBStatus.sh" INSTALL_DB_BINARIES_FILE "installDBBinaries.sh"
 ---> Running in 48b06d55c211
 ---> 241b0248cd2c
Removing intermediate container 48b06d55c211
Step 4/16 : ENV INSTALL_DIR $ORACLE_BASE/install PATH $ORACLE_HOME/bin:$ORACLE_HOME/OPatch/:/usr/sbin:$PATH LD_LIBRARY_PATH $ORACLE_HOME/lib:/usr/lib CLASSPATH $ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib
 ---> Running in 842b6ace5774
 ---> fa99ad665212
Removing intermediate container 842b6ace5774
Step 5/16 : COPY $INSTALL_FILE_1 $INSTALL_RSP $PERL_INSTALL_FILE $SETUP_LINUX_FILE $CHECK_SPACE_FILE $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
 ---> ef98169b4205
Removing intermediate container 4c07b751f0e4
Step 6/16 : COPY $RUN_FILE $START_FILE $CREATE_DB_FILE $CONFIG_RSP $PWD_FILE $CHECK_DB_FILE $ORACLE_BASE/
 ---> c39638b0f961
Removing intermediate container 53fdbb4a767b
Step 7/16 : RUN chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE
 ---> Running in d0870b1540df
Loaded plugins: ovl
Resolving Dependencies
--> Running transaction check
---> Package openssl.x86_64 1:1.0.1e-60.0.1.el7_3.1 will be installed
--> Processing Dependency: openssl-libs(x86-64) = 1:1.0.1e-60.0.1.el7_3.1 for package: 1:openssl-1.0.1e-60.0.1.el7_3.1.x86_64
--> Processing Dependency: make for package: 1:openssl-1.0.1e-60.0.1.el7_3.1.x86_64
---> Package oracle-database-server-12cR2-preinstall.x86_64 0:1.0-2.el7 will be installed
...
...
...
  xorg-x11-xauth.x86_64 1:1.0.9-1.el7
  xz.x86_64 0:5.2.2-1.el7

Dependency Updated:
  openssl-libs.x86_64 1:1.0.1e-60.0.1.el7_3.1

Complete!
Loaded plugins: ovl
Cleaning repos: ol7_UEKR4 ol7_latest
Cleaning up everything
 ---> 36c446376743
Removing intermediate container d0870b1540df
Step 8/16 : USER oracle
 ---> Running in 18aeab6dd644
 ---> 9a2961af4173
Removing intermediate container 18aeab6dd644
Step 9/16 : RUN $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE EE
 ---> Running in b49843849003
Archive:  linuxx64_12201_database.zip
   creating: database/
   creating: database/sshsetup/
  inflating: database/sshsetup/sshUserSetup.sh
   creating: database/rpm/
  inflating: database/rpm/cvuqdisk-1.0.10-1.rpm
...
...
...
  inflating: database/stage/globalvariables/variable.properties
  inflating: database/stage/globalvariables/globalvar.xml
  inflating: database/stage/install1.jar
  inflating: database/runInstaller
Starting Oracle Universal Installer...

Checking Temp space: must be greater than 500 MB.   Actual 89353 MB    Passed
Checking swap space: must be greater than 150 MB.   Actual 8063 MB    Passed
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-07-09_05-32-32PM. Please wait ...[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
You can find the log of this install session at:
 /opt/oracle/oraInventory/logs/installActions2017-07-09_05-32-32PM.log
The installation of Oracle Database 12c was successful.
Please check '/opt/oracle/oraInventory/logs/silentInstall2017-07-09_05-32-32PM.log' for more details.

As a root user, execute the following script(s):
	1. /opt/oracle/oraInventory/orainstRoot.sh
	2. /opt/oracle/product/12.2.0.1/dbhome_1/root.sh



Successfully Setup Software.

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

 ---> 40f7f5f403d3
Removing intermediate container b49843849003
Step 10/16 : USER root
 ---> Running in 5226c9e7804a
 ---> 70ef3691e248
Removing intermediate container 5226c9e7804a
Step 11/16 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in e160cb2a7bac
Changing permissions of /opt/oracle/oraInventory.
Adding read,write permissions for group.
Removing read,write,execute permissions for world.

Changing groupname of /opt/oracle/oraInventory to dba.
The execution of the script is complete.
Check /opt/oracle/product/12.2.0.1/dbhome_1/install/root_4677f42c5ed9_2017-07-09_17-38-29-792554555.log for the output of root script
 ---> 70ce883a067c
Removing intermediate container e160cb2a7bac
Step 12/16 : USER oracle
 ---> Running in 371fdcd9a79f
 ---> 911272bd5700
Removing intermediate container 371fdcd9a79f
Step 13/16 : WORKDIR /home/oracle
 ---> 36961379d48f
Removing intermediate container 10c7dea3c2e0
Step 14/16 : VOLUME $ORACLE_BASE/oradata
 ---> Running in d2e5494cb690
 ---> f2a4a6993ed8
Removing intermediate container d2e5494cb690
Step 15/16 : EXPOSE 1521 5500
 ---> Running in 251d1bbb89ea
 ---> eea27943fd54
Removing intermediate container 251d1bbb89ea
Step 16/16 : CMD exec $ORACLE_BASE/$RUN_FILE
 ---> Running in c26b44e02f51
 ---> 7d16f7ebcaf4
Removing intermediate container c26b44e02f51
Successfully built 7d16f7ebcaf4

  Oracle Database Docker Image for 'ee' version 12.2.0.1 is ready to be extended:

    --> oracle/database:12.2.0.1-ee

  Build completed in 743 seconds.

[root@localhost dockerfiles]#
```

**Comment by SRINIVASREDDYPV** [comment]
I was getting below error while building the image.
http://yum.oracle.com/repo/OracleLinux/OL7/UEKR4/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed connect to yum.oracle.com:80; No route to host"

So i built the image with command
docker build -t oracle/database:12.2.0.1-ee -f  Dockerfile.ee  --network=host .

 --network=host  is the problem ??

**Comment by Djelibeybi** [comment]
The host's `yum.conf` is not used by the container. You need to use `--build-arg` to pass in the right proxy configuration. This is why we provide the `buildDockerImage.sh` script as you can pass in the proxy configuration as a parameter.

You'll need to run the manual build like this:

```
$ docker build -t oracle/database:12.2.0.1-ee --build-arg http_proxy=<proxy_fqdn>:<proxy_port> -f Dockerfile.ee
```

You shouldn't put your container on the same network as the host. Our guidelines strongly recommend against it and we don't accept any images that require it.

**Comment by gvenzl** [comment]
In order to use a proxy just export the `http_proxy` and/or `https_proxy` environment variable in your shell and run `buildDockerImage.sh`. The script will automatically detect the proxy settings, inform you that they have been found, and pass them onto Docker.

**Comment by SRINIVASREDDYPV** [comment]
Thank you @Djelibeybi  and @gvenzl . 
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory 
This error gone after re-imaging my machine. Could be the kernel issue.
--build-arg resolved my proxy error.
I will run the image and let you know if i am facing any issue.

**Comment by SRINIVASREDDYPV** [comment]
docker run -p 1521:1521 -p 5500:5500 -e ORACLE_SID=DOCKERDB -e ORACLE_PDB=DOCKERPDB1 -e ORACLE_PWD=DOCKERDB -v /scratch/softwares:/opt/oracle/oradata oracle/database:12.2.0.1-ee
ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: DOCKERDB

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 10-JUL-2017 18:40:05

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/0f693fface9c/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                10-JUL-2017 18:40:05
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/0f693fface9c/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
   CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
   ACTION: Select a listener to be registered or created with the database.
[WARNING] [DBT-06208] The 'SYS' password entered does not conform to the Oracle recommended standards.
   CAUSE:
a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
b.The password entered is a keyword that Oracle does not recommend to be used as password
   ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
[WARNING] [DBT-06208] The 'SYSTEM' password entered does not conform to the Oracle recommended standards.
   CAUSE:
a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
b.The password entered is a keyword that Oracle does not recommend to be used as password
   ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
[WARNING] [DBT-06208] The 'PDBADMIN' password entered does not conform to the Oracle recommended standards.
   CAUSE:
a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
b.The password entered is a keyword that Oracle does not recommend to be used as password
   ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
Copying database files
1% complete
13% complete
25% complete
Creating and starting Oracle instance
26% complete
30% complete
31% complete
35% complete
38% complete
39% complete
41% complete
Completing Database Creation
42% complete
43% complete
44% complete
46% complete
47% complete
50% complete
Creating Pluggable Databases
55% complete
75% complete
Executing Post Configuration Actions
100% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/DOCKERDB/DOCKERDB.log" for further details.

SQL*Plus: Release 12.2.0.1.0 Production on Mon Jul 10 18:46:42 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL>
System altered.

SQL>
Pluggable database altered.

SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
/opt/oracle/runOracle.sh: line 160: /opt/oracle/checkDBStatus.sh: Permission denied
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
Completed: alter pluggable database DOCKERPDB1 open
2017-07-10T18:46:42.163130+00:00
DOCKERPDB1(3):CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/DOCKERDB/DOCKERPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
DOCKERPDB1(3):Completed: CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/DOCKERDB/DOCKERPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
DOCKERPDB1(3):ALTER DATABASE DEFAULT TABLESPACE "USERS"
DOCKERPDB1(3):Completed: ALTER DATABASE DEFAULT TABLESPACE "USERS"
2017-07-10T18:46:42.865970+00:00
ALTER SYSTEM SET control_files='/opt/oracle/oradata/DOCKERDB/control01.ctl' SCOPE=SPFILE;
   ALTER PLUGGABLE DATABASE DOCKERPDB1 SAVE STATE
Completed:    ALTER PLUGGABLE DATABASE DOCKERPDB1 SAVE STATE

Copying database files
1% complete
13% complete
25% complete
Creating and starting Oracle instance
26% complete
30% complete
31% complete
35% complete
38% complete
39% complete
41% complete
Completing Database Creation
42% complete
43% complete
44% complete
46% complete
47% complete
50% complete
Creating Pluggable Databases
55% complete
75% complete
Executing Post Configuration Actions
100% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/DOCKERDB/DOCKERDB.log" for further details.

SQL*Plus: Release 12.2.0.1.0 Production on Mon Jul 10 18:46:42 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL>
System altered.

SQL>
Pluggable database altered.

SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
/opt/oracle/runOracle.sh: line 160: /opt/oracle/checkDBStatus.sh: Permission denied
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
Completed: alter pluggable database DOCKERPDB1 open
2017-07-10T18:46:42.163130+00:00
2017-07-10T18:56:35.495386+00:00
DOCKERPDB1(3):Resize operation completed for file# 10, old size 337920K, new size 358400K

Should i modify the base docker file to provide write permissions ??

**Comment by gvenzl** [comment]
Hm, I cannot reproduce the issue:

```
[root@localhost dockerfiles]# docker run -p 1521:1521 -p 5500:5500 -e ORACLE_SID=DOCKERDB -e ORACLE_PDB=DOCKERPDB1 -e ORACLE_PWD=DOCKERDB -v /scratch/softwares:/opt/oracle/oradata oracle/database:12.2.0.1-ee
ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: DOCKERDB

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 10-JUL-2017 20:20:50

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/b95d866641cb/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                10-JUL-2017 20:20:50
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/b95d866641cb/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
   CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
   ACTION: Select a listener to be registered or created with the database.
[WARNING] [DBT-06208] The 'SYS' password entered does not conform to the Oracle recommended standards.
   CAUSE:
a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
b.The password entered is a keyword that Oracle does not recommend to be used as password
   ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
[WARNING] [DBT-06208] The 'SYSTEM' password entered does not conform to the Oracle recommended standards.
   CAUSE:
a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
b.The password entered is a keyword that Oracle does not recommend to be used as password
   ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
[WARNING] [DBT-06208] The 'PDBADMIN' password entered does not conform to the Oracle recommended standards.
   CAUSE:
a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
b.The password entered is a keyword that Oracle does not recommend to be used as password
   ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
Copying database files
1% complete
13% complete
25% complete
Creating and starting Oracle instance
26% complete
30% complete
31% complete
35% complete
38% complete
39% complete
41% complete
Completing Database Creation
42% complete
43% complete
44% complete
46% complete
47% complete
50% complete
Creating Pluggable Databases
55% complete
75% complete
Executing Post Configuration Actions
100% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/DOCKERDB/DOCKERDB.log" for further details.

SQL*Plus: Release 12.2.0.1.0 Production on Mon Jul 10 20:27:35 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL>
System altered.

SQL>
Pluggable database altered.

SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
#########################
DATABASE IS READY TO USE!
#########################
The following output is now a tail of the alert.log:
Completed: alter pluggable database DOCKERPDB1 open
2017-07-10T20:27:35.024840+00:00
DOCKERPDB1(3):CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/DOCKERDB/DOCKERPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
DOCKERPDB1(3):Completed: CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/DOCKERDB/DOCKERPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
DOCKERPDB1(3):ALTER DATABASE DEFAULT TABLESPACE "USERS"
DOCKERPDB1(3):Completed: ALTER DATABASE DEFAULT TABLESPACE "USERS"
2017-07-10T20:27:35.953942+00:00
ALTER SYSTEM SET control_files='/opt/oracle/oradata/DOCKERDB/control01.ctl' SCOPE=SPFILE;
   ALTER PLUGGABLE DATABASE DOCKERPDB1 SAVE STATE
Completed:    ALTER PLUGGABLE DATABASE DOCKERPDB1 SAVE STATE
```

The Dockerfile already assigns execution permissions to the shell script, see https://github.com/oracle/docker-images/blob/master/OracleDatabase/dockerfiles/12.2.0.1/setupLinuxEnv.sh#L17

Can you go into the container and check the owner and permissions of the file and post them, please.

**Comment by SRINIVASREDDYPV** [comment]
sh-4.2$ pwd
/opt/oracle
sh-4.2$ ls -l
total 40
-rw-r--r-- 1 oracle dba      1259 Jun 29 11:22 checkDBStatus.sh
drwxr-xr-x 1 oracle oinstall    0 Jul 10 18:06 checkpoints
-rwxr-xr-- 1 oracle dba      2898 Jun 29 11:22 createDB.sh
-rw-r--r-- 1 oracle dba      9264 Jun 29 11:22 dbca.rsp.tmpl
drwxrwxr-x 1 oracle oinstall  192 Jul 10 18:06 diag
drwxrwx--- 1 oracle dba        86 Jul 10 18:06 oraInventory
drwxrwxrwx 8 root   root     4096 Jul 10 18:46 oradata
drwxr-xr-x 1 oracle oinstall   16 Jul 10 18:03 product
-rwxr-xr-- 1 oracle dba      5332 Jun 29 11:22 runOracle.sh
-rwxr-xr-- 1 oracle dba       769 Jun 29 11:22 setPassword.sh
-rwxr-xr-- 1 oracle dba       689 Jun 29 11:22 startDB.sh
sh-4.2$

**Comment by SRINIVASREDDYPV** [comment]
@gvenzl ,You have not set the permissions for checkDBStatus.sh file in  https://github.com/oracle/docker-images/blob/master/OracleDatabase/dockerfiles/12.2.0.1/setupLinuxEnv.sh#L17

**Comment by gvenzl** [comment]
Hi @SRINIVASREDDYPV, you will find that the line, now [line 20](https://github.com/oracle/docker-images/blob/master/OracleDatabase/dockerfiles/12.2.0.1/setupLinuxEnv.sh#L20) sets the execute permission flag for the user and the group of **all** files ending with .sh, including the checkDBStatus.sh file.

Given our offline chat and the fact that your issue seems to be resolved now, can we close this issue here?

**Comment by SRINIVASREDDYPV** [comment]
Thanks @gvenzl  for the support.
