### ISSUE TITLE
Oracle XE container: Not enough memory allocated

### ISSUE THREAD

**Issue by wuxian1987** [oracle/docker-images#458]
inflating: Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm  
sysctl: setting key "kernel.sem": Read-only file system
/var/tmp/rpm-tmp.Fx90Tx: line 257: [: 18446744073692774399: integer expression expected
/var/tmp/rpm-tmp.Fx90Tx: line 271: [: 18446744073692774399: integer expression expected
Executing post-install steps...
You must run '/etc/init.d/oracle-xe configure' as the root user to configure the database.

Error: The container doesn't have enough memory allocated.
A database XE container needs at least 1 GB of shared memory (/dev/shm).
You currently only have 64 MB allocated to the container.

**Comment by brunoborges** [comment]
There's some issue with your local environment and Docker installation. My guess is that it doesn't have sufficient disk space and RAM memory.

**Comment by gvenzl** [comment]
@wuxian1987, please post the entire output of the build. I think your issue is that you haven't specified the `--shm-size=1g` parameter when you started the container. Please have a look at the ReadMe for further details.

**Comment by Gerromie** [comment]
Is the end user supposed to send additional commands to docker during the 'sh buildDockerImage.sh -x -v 11.2.0.2' command using the -o option? If so, those are not specified clearly in the ReadMe. There is information for running the container, but it suggests adding --shm-size=1g. However, these commands do not seem to be useful during the creation of the initial image.

The command:

`sh buildDockerImage.sh -x -v 11.2.0.2 -o --shm-size=1g`

results in the following while the image is being built. 

Loaded plugins: ovl
Cleaning repos: ol7_UEKR4 ol7_latest
Cleaning up everything
Archive:  oracle-xe-11.2.0-1.0.x86_64.rpm.zip
   creating: Disk1/
   creating: Disk1/upgrade/
  inflating: Disk1/upgrade/gen_inst.sql  
   creating: Disk1/response/
  inflating: Disk1/response/xe.rsp   
  inflating: Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm  

This system does not meet the minimum requirements for swap space.  Based on
the amount of physical memory available on the system, Oracle Database 11g
Express Edition requires 2048 MB of swap space. This system has 857 MB
of swap space.  Configure more swap space on the system and retry the 
installation.

error: %pre(oracle-xe-11.2.0-1.0.x86_64) scriptlet failed, exit status 1
error: oracle-xe-11.2.0-1.0.x86_64: install failed

**Comment by gvenzl** [comment]
No, the user is not supposed to provide any Docker options unless he knows what he is doing.

The buildDockerImage.sh adds necessary options for the builds, like XE, automatically.

**Comment by Gerromie** [comment]
I receive the same error I posted above if I provide no options to the buildDockerImage.sh scripts beyond the -x and -v options.

**Comment by gvenzl** [comment]
@Gerromie, the error above states the following:

```
This system does not meet the minimum requirements for swap space. Based on
the amount of physical memory available on the system, Oracle Database 11g
Express Edition requires 2048 MB of swap space. This system has 857 MB
of swap space. Configure more swap space on the system and retry the
installation.
```

It means that the container does not have enough swap space configured. It only has 857MB but you need 2GB in order to build that image. Unfortunately, as of today there is no way with Docker to control swap space inside the container. The only solution is to make sure that your system has enough swap configured in the first place. There are already some threads around that on various forums like that one: [Docker & swap space](https://forums.docker.com/t/docker-swap-space/3908)

Also, please note that your error is different from the original error above, which is about not having enough shared memory provided.

**Comment by Gerromie** [comment]
@gvenzl I know that you said this was the wrong issue to make my comment in, but since I have found that the following solution during the buildDockerImage.sh step resolves my issue, I thought I would leave the info here in case you would like to add it to the documents.

`sh buildDockerImage.sh -x -v 11.2.0.2 -o "--memory=1g --memory-swap=2g"`

**Comment by gvenzl** [comment]
Thanks a lot @Gerromie, I was not aware that Docker now supports the `--memory-swap` option. Will test and add it to the build script. Do you think that `--memory` is required as well (`--shm-size` is already automatically added)?

**Comment by Gerromie** [comment]
Docker seems to require that --memory is provided when --memory-swap is used.

**Comment by grahamehorner** [comment]
what is required to get this to build on a Windows system using docker ?

**Comment by eyp** [comment]
I have the same problem, I've tried several things like: 
./buildDockerImage.sh -x -v 11.2.0.2 -o "--memory=1g --memory-swap=2g"
or
./buildDockerImage.sh -x -v 11.2.0.2 -o --shm-size=2g

but without success :(

**Comment by proskehy** [comment]
@grahamehorner @eyp Using the workaround suggested in PR https://github.com/oracle/docker-images/pull/638 helped for me.

**Comment by kmlprtsng** [comment]
Try passing the `--shm-size` flag to docker run i.e.  `docker run --shm-size="2g" -d oracle/database:11.2.0.2-xe`

**Comment by eyp** [comment]
@kmlprtsng that doesn't work. For Windows 10 is needed to apply the patch https://github.com/oracle/docker-images/pull/638, although I've already read that the patch has been applied in the trunk.

**Comment by kmlprtsng** [comment]
I have the latest changes from the trunk but still had the same problem so `shm-size` worked for me. I am on a mac. Hopefully somebody else will find it useful.

**Comment by Ray-Gill** [comment]
@kmlprtsng thanks, that worked for me on Linux (Ubuntu)

```
docker run --name oracle-xe \
-p 1521:1521 -p 5500:5500 \
-e ORACLE_PWD=mypassword \
--shm-size="2g" \
-v oracle-xe-volumne:/opt/oracle/oradata \
-d oracle/database:11.2.0.2-xe```

**Comment by ptomulik** [comment]
If you use docker-compose, the trick that worked for me is to use '3.5'  version of configuration and then set ``shm_size: '2gb'``. See [this](https://docs.docker.com/compose/compose-file/#shm_size).

**Comment by gvenzl** [comment]
Closing this issue as various solutions have been provided.
Also 18c XE will no longer perform a swap check altogether.
