### ISSUE TITLE
Need an OracleLinux image with updated python support for data science applications

### ISSUE THREAD

**Issue by draikes30** [oracle/docker-images#463]
For all OracleLinux images, the latest version of python available seems to be python 2.7.5 for python 2.7.

Many times it is necessary to run python scripts that require packages which are not compatible with such an old version of python.

I propose that an oracleLinux image for data science be created that will incorporate anaconda python which allows the user to setup an environment with whatever 2.7 or 3.x version of python he needs through the use of some console  commands in a running container.  The environment could also be configured in a Dockerfile extending the image.

**Comment by Djelibeybi** [comment]
Oracle Linux provides Python 2.7, 3.3, 3.4 and 3.5 via Software Collections. It's straightforward to create a base Python image that extends `7-slim` using the Software Collections:

```
FROM oraclelinux:7-slim
RUN yum-config-manager --enable ol7_software_collections && \
   yum-config-manager --enable ol7_optional_latest && \
   yum install -y rh-python35 && \
   yum clean all

ENTRYPOINT ["scl", "enable", "rh-python35", "--"]
CMD ["python", "--version"]
```

Build an image from that and run it and it should output as follows:

```
$ docker run python35
Python 3.5.1
```

By using the `ENTRYPOINT`/`CMD` combo, anything you provide on the Docker command-line is appended to the `scl enable rh-python35 --`, which means the Software Collection is automatically enabled, e.g.

```
$ docker run --rm -ti python35 python -i
Python 3.5.1 (default, Dec  6 2016, 17:54:30)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

You can substitute `python27`, `python33`, `rh-python34` into the Dockerfile for different Python versions to be installed. You can find a list of all available [Software Collections](http://docs.oracle.com/cd/E52668_01/E59096/html/index.html) in the documentation.
