### ISSUE TITLE
Changing sqlnet.ora parameter ??

### ISSUE THREAD

**Issue by AH0HA** [oracle/docker-images#468]
https://community.oracle.com/thread/4062527

changing sqlnet.ora parameter after the docker image is built WITHOUT rebuilding the docker image ?

Thanks for all the help

**Comment by Djelibeybi** [comment]
Just to clarify: are you using an image from Oracle Container Registry or the Docker Store, or are you manually building an image using the `Dockerfile` from this repository?

**Comment by AH0HA** [comment]
manual built.

**Comment by gvenzl** [comment]
This is currently not supported as the file is not being exposed via the volume. However, that will only be a minor change. Stay tuned!
