### ISSUE TITLE
ERROR: ORA-12162: TNS:net service name is incorrectly specified

### ISSUE THREAD

**Issue by petrucioata** [oracle/docker-images#470]
Hi guys, 

After I start the container and issue the following command: 

`docker exec -ti <container name> sqlplus pdbadmin@ORCLPDB1`

I get the following error: 

`ERROR: ORA-12162: TNS:net service name is incorrectly specified`

Any idea how to fix this? 

Thanks, 
Petru

**Comment by gvenzl** [comment]
Hm, works for me:

```
[root@localhost ~]# docker exec -ti oracle-ee sqlplus pdbadmin@ORCLPDB1

SQL*Plus: Release 12.2.0.1.0 Production on Wed Jul 12 18:02:11 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Enter password:

Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL> select sysdate from dual;

SYSDATE
---------
12-JUL-17

SQL> exit
Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
```
On which image are you trying to do this? I use the latest 12.2.0.1-ee one.

Thx,

**Comment by gvenzl** [comment]
Closing this due to lack of response.

**Comment by mdfaramawy** [comment]
Thanks too much, It helped me !
