### ISSUE TITLE
This images doesnt work in Kubernetes, works in Docker

### ISSUE THREAD

**Issue by sd2302** [oracle/docker-images#483]
Hello, I can run the image via docker but when i try to run this in Kubernetes, I get the following error:

Note: In Kuberntes, Listener starts up fine but it fails at dbca copy database files step.

```
kubectl logs -f <pod_name> show this...
```

Any idea how to debug this?

```
2017-07-16T06:01:40.139706352Z Copying database files
2017-07-16T06:01:43.537243159Z 1% complete
2017-07-16T06:03:52.132511258Z /opt/oracle/createDB.sh: line 62:    26 Killed                  dbca -silent -createDatabase -responseFile $ORACLE_BASE/dbca.rsp
2017-07-16T06:03:52.142426973Z cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log: No such file or directory
2017-07-16T06:03:52.233572773Z cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB.log: No such file or directory
```

Docker runs fine: so Image built is good.

```
[root@hak-dal-d007 sd2302]# docker ps| grep -i oracle
91d29b30199f        oracle/database:12.2.0.1-ee   "/bin/sh -c 'exec $OR"   2 weeks ago         Up 10 days          0.0.0.0:1521->1521/tcp, 0.0.0.0:5500->5500/tcp   oracle12-ee
```

**Comment by Djelibeybi** [comment]
I'm assuming that `docker ps` output is from the same machine that's running Kubernetes? The only thing that springs to my mind is if there is some sort of timeout value for deploying a pod in Kubernetes that's being hit? I see the `26 Killed` error and that feels like something is issuing a `SIGKILL` to the script.

**Comment by brunoborges** [comment]
I agree this seems likely to be timeout. In which by the way I suspect is of 2 minutes. Look at the timestamps.

```
2017-07-16T06:01:43.537243159Z 1% complete
2017-07-16T06:03:52.132511258Z /opt/oracle/createDB.sh: line 62:    26 Killed     
```

**Comment by gvenzl** [comment]
Closing this due to lack of response.

**Comment by sd2302** [comment]
My fault for lack of response. I was not able to figure out which timeout parameter should I look?

**Comment by jameshcovington** [comment]
Curious, did you ever figure out this issue? I'm running into a similar issue with Oracle DBCA after shifting to a new version of Open Shift.

**Comment by rjeberhard** [comment]
This is just a hypothesis... I'm from the WebLogic Team and don't have any particular knowledge of the database startup scripts or containerization. We had similar issues when running on OpenShift. The default OpenShift security context (restricted) runs containers as a random UID that is part of the root group (wheel). Most Oracle containerizations expect to run as the oracle:oracle user and the file-permissions are set with that in mind.
