### ISSUE TITLE
Clearer documentation

### ISSUE THREAD

**Issue by rafaelosoto** [oracle/docker-images#492]
Hi I'm trying to get the ODB to work in docker running on ubuntu. I'm still very unclear about what files I need to place where. 

I know I need 12cR2 http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html

but what flavor? Is it based on my own OS or the docker base image you guys are using? 

I downloaded the linux zip and placed it in the right directory and made sure not to decompress the file but I just get a checksum error complaining about the right files.

**Comment by Djelibeybi** [comment]
You need to download the file for Linux, as per the `.download` file in the repository itself. But, you're not providing the actual error, so it's difficult to tell you how to fix it.

Does the build complete if you bypass the MD5 check?

**Comment by rafaelosoto** [comment]
Not sure what .download file you are talking about could you provide a link?

I downloaded the linux zip here and left it uncompressed:

`waffleiron ॐ  ~/git/oracle/OracleDatabase/dockerfiles/12.2.0.1:(1d6h18m|git@master!)
9398 ± tree                                                                                                                                                                                                      ✭
.
├── checkDBStatus.sh
├── checkSpace.sh
├── Checksum.ee
├── Checksum.se2
├── createDB.sh
├── dbca.rsp.tmpl
├── db_inst.rsp
├── Dockerfile.ee
├── Dockerfile.se2
├── installDBBinaries.sh
├── installPerl.sh
├── linuxx64_12201_database.zip
├── runOracle.sh
├── runUserScripts.sh
├── setPassword.sh
├── setupLinuxEnv.sh
└── startDB.sh

`

this is the error:

`
waffleiron ॐ  ~/git/oracle/OracleDatabase/dockerfiles:(1d6h18m|git@master!)
9401 ± ./buildDockerImage.sh -v 12.2.0.1                                                                                                                                                                         ✭
Checking if required packages are present and valid...
md5sum: Checksum.xe: No such file or directory
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 12.2.0.1.
`

thanks for the help!

**Comment by Djelibeybi** [comment]
You've downloaded Oracle Database 12.2 Enterprise Edition but you're not passing `-e` to `./buildDockerImage.sh`, so it's trying to build the default XE image.

**Comment by rafaelosoto** [comment]
I see, stuff is happening now, thanks a lot!
