### ISSUE TITLE
ORA-12541: no listener for Oracle Database Docker image on Ubuntu

### ISSUE THREAD

**Issue by rafaelosoto** [oracle/docker-images#493]
Hey Guys, getting this error when using OracleDatabase 12.2 on an ubuntu host. 

The instance comes up fine:

```
9692 ± docker-compose up odb                                                                        ✹ ✭
Recreating ebiscontainer_odb_1
Attaching to ebiscontainer_odb_1
odb_1   | ASSWORD FOR SYS, SYSTEM AND PDBADMIN: password
odb_1   | 
odb_1   | LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 18-JUL-2017 20:09:00
odb_1   | 
odb_1   | Copyright (c) 1991, 2016, Oracle.  All rights reserved.
odb_1   | 
odb_1   | Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...
odb_1   | 
odb_1   | TNSLSNR for Linux: Version 12.2.0.1.0 - Production
odb_1   | System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
odb_1   | Log messages written to /opt/oracle/diag/tnslsnr/120bfb89449e/listener/alert/log.xml
odb_1   | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
odb_1   | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
odb_1   | 
odb_1   | Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
odb_1   | STATUS of the LISTENER
odb_1   | ------------------------
odb_1   | Alias                     LISTENER
odb_1   | Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
odb_1   | Start Date                18-JUL-2017 20:09:00
odb_1   | Uptime                    0 days 0 hr. 0 min. 0 sec
odb_1   | Trace Level               off
odb_1   | Security                  ON: Local OS Authentication
odb_1   | SNMP                      OFF
odb_1   | Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
odb_1   | Listener Log File         /opt/oracle/diag/tnslsnr/120bfb89449e/listener/alert/log.xml
odb_1   | Listening Endpoints Summary...
odb_1   |   (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
odb_1   |   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
odb_1   | The listener supports no services
odb_1   | The command completed successfully
odb_1   | [WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
odb_1   |    CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
odb_1   |    ACTION: Select a listener to be registered or created with the database.
odb_1   | [WARNING] [DBT-06208] The 'SYS' password entered does not conform to the Oracle recommended standards.
odb_1   |    CAUSE: 
odb_1   | a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
odb_1   | b.The password entered is a keyword that Oracle does not recommend to be used as password
odb_1   |    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
odb_1   | [WARNING] [DBT-06208] The 'SYSTEM' password entered does not conform to the Oracle recommended standards.
odb_1   |    CAUSE: 
odb_1   | a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
odb_1   | b.The password entered is a keyword that Oracle does not recommend to be used as password
odb_1   |    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
odb_1   | [WARNING] [DBT-06208] The 'PDBADMIN' password entered does not conform to the Oracle recommended standards.
odb_1   |    CAUSE: 
odb_1   | a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
odb_1   | b.The password entered is a keyword that Oracle does not recommend to be used as password
odb_1   |    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
odb_1   | Copying database files
odb_1   | 1% complete
odb_1   | 13% complete
odb_1   | 25% complete
odb_1   | Creating and starting Oracle instance
odb_1   | 26% complete
odb_1   | 30% complete
...
```

when connecting via cx_Oracle for python I get:

```
  File "/home/waffles/virtualenvs/ebis/local/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 214, in get_new_connection
    return Database.connect(conn_string, **conn_params)
django.db.utils.DatabaseError: ORA-12541: TNS:no listener
```

My client is on the host and I'm forwarding both ports:
```
  File "/home/waffles/virtualenvs/ebis/local/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 214, in get_new_connection
    return Database.connect(conn_string, **conn_params)
django.db.utils.DatabaseError: ORA-12541: TNS:no listener
```

**Comment by rafaelosoto** [comment]
here is the compose file I'm using:

version: '3'

services:

  odb:
    image: oracle/database:12.2.0.1-ee
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./odata:/opt/oracle/oradata
    environment:
      - ORACLE_SID=sid
      - ORACLE_PWD=password
    tty: true

**Comment by gvenzl** [comment]
Hi @rafaelosoto, it could be that there went something wrong during the container startup. Can you please provide the entire output of the startup log.

Also, can you please share what your `conn_string` and `conn_params` contain.

**Comment by rafaelosoto** [comment]
Here's the full output

10160 ± docker-compose up odb                                                                                                                                                                                  ✹ ✭
Recreating ebiscontainer_odb_1
Attaching to ebiscontainer_odb_1
odb_1   | ASSWORD FOR SYS, SYSTEM AND PDBADMIN: password
odb_1   | 
odb_1   | LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 20-JUL-2017 14:41:26
odb_1   | 
odb_1   | Copyright (c) 1991, 2016, Oracle.  All rights reserved.
odb_1   | 
odb_1   | Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...
odb_1   | 
odb_1   | TNSLSNR for Linux: Version 12.2.0.1.0 - Production
odb_1   | System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
odb_1   | Log messages written to /opt/oracle/diag/tnslsnr/97679205d5ba/listener/alert/log.xml
odb_1   | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
odb_1   | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
odb_1   | 
odb_1   | Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
odb_1   | STATUS of the LISTENER
odb_1   | ------------------------
odb_1   | Alias                     LISTENER
odb_1   | Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
odb_1   | Start Date                20-JUL-2017 14:41:27
odb_1   | Uptime                    0 days 0 hr. 0 min. 0 sec
odb_1   | Trace Level               off
odb_1   | Security                  ON: Local OS Authentication
odb_1   | SNMP                      OFF
odb_1   | Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
odb_1   | Listener Log File         /opt/oracle/diag/tnslsnr/97679205d5ba/listener/alert/log.xml
odb_1   | Listening Endpoints Summary...
odb_1   |   (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
odb_1   |   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
odb_1   | The listener supports no services
odb_1   | The command completed successfully
odb_1   | [WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
odb_1   |    CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
odb_1   |    ACTION: Select a listener to be registered or created with the database.
odb_1   | [WARNING] [DBT-06208] The 'SYS' password entered does not conform to the Oracle recommended standards.
odb_1   |    CAUSE: 
odb_1   | a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
odb_1   | b.The password entered is a keyword that Oracle does not recommend to be used as password
odb_1   |    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
odb_1   | [WARNING] [DBT-06208] The 'SYSTEM' password entered does not conform to the Oracle recommended standards.
odb_1   |    CAUSE: 
odb_1   | a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
odb_1   | b.The password entered is a keyword that Oracle does not recommend to be used as password
odb_1   |    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
odb_1   | [WARNING] [DBT-06208] The 'PDBADMIN' password entered does not conform to the Oracle recommended standards.
odb_1   |    CAUSE: 
odb_1   | a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
odb_1   | b.The password entered is a keyword that Oracle does not recommend to be used as password
odb_1   |    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
odb_1   | Copying database files
odb_1   | 1% complete
odb_1   | 13% complete
odb_1   | 25% complete
odb_1   | Creating and starting Oracle instance
odb_1   | 26% complete
odb_1   | 30% complete
odb_1   | 31% complete
odb_1   | 35% complete
odb_1   | 38% complete
odb_1   | 39% complete
odb_1   | 41% complete
odb_1   | Completing Database Creation
odb_1   | 42% complete
odb_1   | 43% complete
odb_1   | 44% complete
odb_1   | 46% complete
odb_1   | 47% complete
odb_1   | 50% complete
odb_1   | Creating Pluggable Databases
odb_1   | 55% complete
odb_1   | 75% complete
odb_1   | Executing Post Configuration Actions
odb_1   | 100% complete
odb_1   | Look at the log file "/opt/oracle/cfgtoollogs/dbca/ebis/ebis.log" for further details.
odb_1   | 
odb_1   | SQL*Plus: Release 12.2.0.1.0 Production on Thu Jul 20 14:46:46 2017
odb_1   | 
odb_1   | Copyright (c) 1982, 2016, Oracle.  All rights reserved.
odb_1   | 
odb_1   | 
odb_1   | Connected to:
odb_1   | Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
odb_1   | 
odb_1   | SQL> 
odb_1   | System altered.
odb_1   | 
odb_1   | SQL> 
odb_1   | Pluggable database altered.
odb_1   | 
odb_1   | SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
odb_1   | #########################
odb_1   | DATABASE IS READY TO USE!
odb_1   | #########################
odb_1   | The following output is now a tail of the alert.log:
odb_1   | Completed: alter pluggable database ORCLPDB1 open
odb_1   | 2017-07-20T14:46:45.429939+00:00
odb_1   | ORCLPDB1(3):CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/ebis/ORCLPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
odb_1   | ORCLPDB1(3):Completed: CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/ebis/ORCLPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
odb_1   | ORCLPDB1(3):ALTER DATABASE DEFAULT TABLESPACE "USERS"
odb_1   | ORCLPDB1(3):Completed: ALTER DATABASE DEFAULT TABLESPACE "USERS"
odb_1   | 2017-07-20T14:46:46.067708+00:00
odb_1   | ALTER SYSTEM SET control_files='/opt/oracle/oradata/ebis/control01.ctl' SCOPE=SPFILE;
odb_1   |    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
odb_1   | Completed:    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
odb_1   | 2017-07-20T14:56:39.303488+00:00
odb_1   | ORCLPDB1(3):Resize operation completed for file# 10, old size 337920K, new size 358400K


for conn_string you mean my django connection string?

**Comment by gvenzl** [comment]
Hi @rafaelosoto, your database and listener are up and running so I expect something wrong with the connection string.

Yes, the one that you pass on here: ` return Database.connect(conn_string, **conn_params)`

**Comment by rafaelosoto** [comment]
Hey gvenzl, thanks again for your help.

I'm using the DATABASES configuration for Django. My settings look like the following:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'ebis',
        'USER': 'oracle',
        'PASSWORD': 'password',  
        'HOST': "",  # Set to empty string for localhost
        'PORT': "1542",  # Set to empty string for default.
    }
}

**Comment by gvenzl** [comment]
Hi @rafaelosoto,

As I expected, the config looks wrong. You are exposing port 1521 on port 1521 but the config Django config says port 1542. Also the user `oracle` is wrong if that should be a database user. Last but not least, I assume that `name` means database name but also there is no ebis in the compose file that you have referenced above.

**Comment by gvenzl** [comment]
Closing this due to lack of response.
