### ISSUE TITLE
Support applypatch for OracleDatabase 12.2.0.1

### ISSUE THREAD

**Issue by yahonda** [oracle/docker-images#496]
Thanks to https://github.com/oracle/docker-images/tree/master/OracleDatabase/samples/applypatch 
We can apply Oracle Database PSU to 12.1.0.2. 

As of right now, this feature is only available for 12.1.0.2, I wanted this feature is available for OracleDatabase 12.2.0.1.

**Comment by Djelibeybi** [comment]
Looking at the sample, it seems like it should work with 12.2 mostly unmodified, but I've assigned this to @gvenzl for confirmation.

Have you tried using the sample, but switching the `FROM` directive to the 12.2 image?

**Comment by yahonda** [comment]
Thanks for the update. I did modify [this one](https://github.com/yahonda/docker-images/commit/9e2d96551f187cffc909d1cda73a25cd4c6da686) and am able to apply this patch.

```
[oracle@5e71e34f3df1 OPatch]$ ./opatch lspatches
26123830;DATABASE RELEASE UPDATE: 12.2.0.1.170718 (26123830)

OPatch succeeded.
```
