### ISSUE TITLE
ulimits/sysctls are not in effect

### ISSUE THREAD

**Issue by dglushenok** [oracle/docker-images#51]
Hello,

Dockerfile (at least for WebLogic) has following lines:
```
# Change the open file limits in /etc/security/limits.conf
RUN sed -i '/.*EOF/d' /etc/security/limits.conf && \
    echo "* soft nofile 16384" >> /etc/security/limits.conf && \ 
    echo "* hard nofile 16384" >> /etc/security/limits.conf && \ 
    echo "# EOF"  >> /etc/security/limits.conf

# Change the kernel parameters that need changing.
RUN echo "net.core.rmem_max=4192608" > /u01/oracle/.sysctl.conf && \
    echo "net.core.wmem_max=4192608" >> /u01/oracle/.sysctl.conf && \ 
    sysctl -e -p /u01/oracle/.sysctl.conf
```

But docker will ignore /etc/security/limits.conf and sysctls will not work as /proc/sys/net/core/{w|r}mem_max are not exposed to container. So, resulting container will inherit net.core.{w|r}mem_max from host and nofile from docker process.

**Comment by brunoborges** [comment]
@dglushenok do you have any pointer to Docker docs that state this?

**Comment by dglushenok** [comment]
It looks like Docker is too young to have this documented. You can see https://github.com/docker/docker/issues/4717 where people are talking about changing sysctl settings and process limits.

**Comment by brunoborges** [comment]
@dglushenok what about the --ulimit option in docker run? Should that be used instead? If yes, how?

See https://github.com/docker/docker/pull/9437

**Comment by brunoborges** [comment]
I took this in consideration and performed the adjustments. See commits 97e5845, 26e5154, and b5c8012.
