### ISSUE TITLE
SOA 'setenv.sh' should define default passwords if none are supplied OOTB

### ISSUE THREAD

**Issue by klauern** [oracle/docker-images#510]
I had to edit a couple things in the `setenv.sh` that weren't mentioned in the README.  In particular, trying to run `docker-compose up -d soaas` will fail if you don't set up some password fields.  I think these should be defaulted to something, as I just put in some generic `welcome1` password to test with.

**Comment by brunoborges** [comment]
@mriccell can you please take a look at this one, or ask someone from the SOA team to review?

**Comment by rdas76** [comment]
We decided that no default passwords will be used and it would be either have to be given by user or auto generated. Done on purpose for security reasons.
