### ISSUE TITLE
Introduce troubleshooting page

### ISSUE THREAD

**Issue by gvenzl** [oracle/docker-images#513]
A new troubleshooting page can be referenced by the individual check scripts and point the user to the web location for potential fixes.

Things that come to mind:

a) Space check
b) Swap check
c) --shm-size check / memory check

**Comment by gvenzl** [comment]
We got a new FAQ page now. :)
Feel free to PR other frequently encountered questions, issues, etc.

**Comment by hieplq** [comment]
> We got a new FAQ page now. :)
> Feel free to PR other frequently encountered questions, issues, etc. into the FAQ.md file.

link on FAQ.md to troubleshooting #124 #310 isn't clear, to apply ```--storage-opt dm.basesize=``` need some pre-condition

i suggest add some link for reference

[to understand storage option](https://docs.docker.com/storage/)

[--storage-opt isn't apply for ext4 partition format](https://www.reddit.com/r/docker/comments/71mift/how_to_increase_docker_container_storage_limit/dnlmyu6/)

[use btrfs|zfs storagedriver for auto extend store](https://docs.docker.com/storage/storagedriver/btrfs-driver/)

[use device-mapper-driver storagedriver for dm.basesize](https://docs.docker.com/storage/storagedriver/device-mapper-driver/)
