### ISSUE TITLE
Licensing of Dockerized 12c DB & Weblogic

### ISSUE THREAD

**Issue by manik-chopra** [oracle/docker-images#516]
Hi,

We are building an application that requires Oracle 12c Database and Weblogic and would like to understand how does the licensing work for dockerized DB & Weblogic. 

It was announced in Dockercon'17 by Oracle that for non prod there is no fee to use these application thus want to confirm if there is a fine print to that. Thanks in advance. 

-m

**Comment by brunoborges** [comment]
There are no changes to how Oracle Database (or any Oracle software) is licensed. Containerized software actually runs on the host kernel, so therefore the host must be licensed as usual.

**Comment by manik-chopra** [comment]
Is there a license to run in non prod?

**Comment by Djelibeybi** [comment]
Yes, you have to agree to it before you can download the software required to build these images. I suggest you go back to the download page and review that license.
