### ISSUE TITLE
Oracle Weblogic default password not working

### ISSUE THREAD

**Issue by manik-chopra** [oracle/docker-images#521]
I'm building the sample domain using following after weblogic image is ready. However, the weblogic is not taking the supplied password and its always generating random password on starting the weblogic. 

docker build -t 1221-domain --build-arg ADMIN_PASSWORD=welcome1 .

docker build -t 12212-domain --build-arg ADMIN_PASSWORD=welcome1 .
Sending build context to Docker daemon  34.82kB
Step 1/10 : FROM oracle/weblogic:12.2.1.2-developer
 ---> 7a229aa9a605
Step 2/10 : MAINTAINER Monica Riccelli <monica.riccelli@oracle.com>
 ---> Using cache
 ---> e1351ce6de5b
Step 3/10 : ENV ADMIN_HOST "wlsadmin" NM_PORT "5556" MS_PORT "8001" DEBUG_PORT "8453" ORACLE_HOME /u01/oracle SCRIPT_FILE /u01/oracle/createAndStartWLSDomain.sh CONFIG_JVM_ARGS "-Dweblogic.security.SSL.ignoreHostnameVerification=true" PATH $PATH:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/user_projects/domains/${DOMAIN_NAME:-base_domain}/bin:/u01/oracle
 ---> Using cache
 ---> 5b968cfe3cb6
Step 4/10 : ENV DOMAIN_NAME "${DOMAIN_NAME:-base_domain}" PRE_DOMAIN_HOME /u01/oracle/user_projects/domains ADMIN_PORT "${ADMIN_PORT:-7001}" ADMIN_USERNAME "${ADMIN_USERNAME:-weblogic}" ADMIN_NAME "${ADMIN_NAME:-AdminServer}" ADMIN_PASSWORD "${ADMIN_PASSWORD:-""}" CLUSTER_NAME "${CLUSTER_NAME:-DockerCluster}" DEBUG_FLAG true PRODUCTION_MODE dev
 ---> Using cache
 ---> 8e4dbafa2518
Step 5/10 : COPY container-scripts/* /u01/oracle/
 ---> Using cache
 ---> be74ba8561e7
Step 6/10 : RUN mkdir -p $PRE_DOMAIN_HOME &&     chmod a+xr $PRE_DOMAIN_HOME &&     chown oracle:oracle -R $PRE_DOMAIN_HOME
 ---> Using cache
 ---> d92cc50fe600
Step 7/10 : EXPOSE $NM_PORT $ADMIN_PORT $MS_PORT $DEBUG_PORT
 ---> Using cache
 ---> 1a125c98a2f7
Step 8/10 : USER oracle
 ---> Using cache
 ---> dde8269dde9b
Step 9/10 : WORKDIR $ORACLE_HOME
 ---> Using cache
 ---> 571d75f4fb71
Step 10/10 : CMD /u01/oracle/createAndStartWLSDomain.sh
 ---> Using cache
 ---> a5d5508b3834
**[Warning] One or more build-args [ADMIN_PASSWORD] were not consumed
Successfully built a5d5508b3834**

**Comment by brunoborges** [comment]
hi @manik-chopra, can you please try with the latest files? Let us know if the issue remains. If it does, feel free to reopen.
