### ISSUE TITLE
DB12.1.0.2 syntax error in checkSpace.sh and an error of not enough space available building image

### ISSUE THREAD

**Issue by michael-yxf** [oracle/docker-images#523]
One typo in the checkSpace.sh:
https://github.com/oracle/docker-images/blob/master/OracleDatabase/dockerfiles/12.1.0.2/checkSpace.sh

`` if [ `df -B 1G . | tail -n 1 | awk '{print $4'}` -lt $REQUIRED_SPACE_GB ]; then``

The single quote should be after the `}`:

``if [ `df -B 1G . | tail -n 1 | awk '{print $4}'` -lt $REQUIRED_SPACE_GB ]; then``

When I build the image, I got the `There is not enough space available in the docker container` at step 5 checking the space, the required space is at least 12G, how to adjust settings to satisfy this condition? I added one line in the script to show the run-time status detected, it has 7G available. 

Docker version:

> $ docker version     
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.6.1
OS/Arch (client): linux/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.6.1
OS/Arch (server): linux/amd64

> $ docker info
Containers: 3
Images: 501
Storage Driver: devicemapper
 Pool Name: docker-252:0-215744515-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 44.86 GB
 Data Space Total: 107.4 GB
 Data Space Available: 62.51 GB
 Metadata Space Used: 39.92 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.108 GB
 Udev Sync Supported: true
 Data loop file: /scratch/.dockerdata/devicemapper/devicemapper/data
 Metadata loop file: /scratch/.dockerdata/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Execution Driver: native-0.2
Kernel Version: 3.8.13-35.3.1.el7uek.x86_64
Operating System: Oracle Linux Server 7.0

Thanks.

**Comment by gvenzl** [comment]
Thanks a lot for spotting this, @michael-yxf
PR with fix is in!

Besides that, you are using a really old version of Docker and UEK here.
Please upgrade to UEK4 to get Docker CE 17.03.
Docker 1.6.1 is very, very old with a lot of issues not fixed yet.

**Comment by michael-yxf** [comment]
Thank you, @gvenzl 

Yes, I realized the docker version issue, and got the image built successfully on OEL7.3 with UEK4 + Docker CE17.05. 

Thanks!

**Comment by gvenzl** [comment]
Merged into master.
