### ISSUE TITLE
Outdated path to custom scripts at startup/setup of Oracle DB in samples

### ISSUE THREAD

**Issue by ismarslomic** [oracle/docker-images#528]
[OracleDatabase/samples/customscripts/README.md](https://github.com/oracle/docker-images/tree/master/OracleDatabase/samples/customscripts) seems to be outdated. It is referring to `/opt/oracle/scritps` for custom startup/setup scripts while correct paths are:

- `/opt/oracle/scripts/startup`
- `/opt/oracle/scripts/setup`

as described in [OracleDatabase/README.md](https://github.com/oracle/docker-images/tree/master/OracleDatabase).

This might be the case in other README.md files in other sample folders as well.

**Comment by gvenzl** [comment]
Fixed and merged!
