### ISSUE TITLE
Weblogic online-config example failing due to non-existent dir

### ISSUE THREAD

**Issue by johnharris85** [oracle/docker-images#531]
Following the instructions for the online-config example (and backwards through the image build chain) and it fails because the empty domain is never created. This only happens via the createAndStartWLSDomain.sh script but this is never called outside of a `CMD` step. So just following the builds will never create it. 

Are we missing something?

cc @mello151

**Comment by kallisti-dev** [comment]
+1

**Comment by mriccell** [comment]
@johnharris85  Can you please provide more details of what sample you are running and what steps you follow?  What WLS image are you using to extend and create the domain?

**Comment by johnharris85** [comment]
1. Build the developer image.
2. Build the 12212-domain image.
3. Build the 12212-online-config image.

Step 3 fails because there has been no domain created.

    ./jms-wlst-online-config.sh: line 34: cd: /u01/oracle/user_projects/domains/base_domain: No such file or directory

**Comment by mriccell** [comment]
@johnharris85  I see the problem, I just recently changed 12212-domain to create the domain at run time instead of build time.  12212-online-config depends on a domain to be already created by the time we create the image.  Your solution is correct, do you mind creating a push request to make changes to 12212-online-config?

**Comment by mriccell** [comment]
@johnharris85 make sure you do not extend 12212-domain but extend 12212-developer directly.

**Comment by johnharris85** [comment]
Thanks @mriccell I will take a look. I also have a question about the `ENV` instructions in most of the Dockerfiles. A lot of them are used at build time, but there is no mechanism for setting any of them (there are no `ARG` instructions to read `--build-arg` params at build time). 

Am I missing something?

**Comment by mriccell** [comment]
That is correct all the env parameters are set during run time and you can either use the -e option or create an env file and use --env-file ./domain.properties.
