### ISSUE TITLE
Not able to run the second oracle 12.1.0.2 db container on the same host. Is it possible?

### ISSUE THREAD

**Issue by kulbhushan1** [oracle/docker-images#534]
ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/opt/oracle/product/12.1.0.2/dbhome_1/dbs/initMYDB.ora'

**Comment by gvenzl** [comment]
Please provide more information. What you are trying to do and the `docker run` instructions.

**Comment by gvenzl** [comment]
Closing this due to lack of response.
