### ISSUE TITLE
Database not persisting

### ISSUE THREAD

**Issue by SquirrelNinja** [oracle/docker-images#535]
OS is Mac Sierra
I am running:

docker run --name oraclecdb \
-p 1521:1521 -p 5500:5500 \
-e ORACLE_SID=ORCLCDB \
-e ORACLE_PDB=ORCLPDB1 \
-e ORACLE_PWD=oracle \
-v /Users/user/projects/aa_dev_db/oradata:/home/oracle/oradata \
oracle/database:12.2.0.1-ee

I have mapped /Users/user/projects/aa_dev_db/ in the docker toolkit preferences.  I can connect to the DB and create tables, however nothing is ever persisted to disk.  What am I missing?

**Comment by gvenzl** [comment]
You have a typo in your volume. Instead of `/home/oracle/oradata` it should be `/opt/oracle/oradata`

**Comment by SquirrelNinja** [comment]
That was it - thanks a bunch!!!
