### ISSUE TITLE
 ORA-01034: ORACLE not available on oracle 12.2.0.1 SE Image

### ISSUE THREAD

**Issue by BrianFlowerday** [oracle/docker-images#538]
Hi I am using windows 10
I Created my base image with the following
 ./buildDockerImage.sh -v 12.2.0.1 -s

But when creating an image of that one I had the issue where importing all myscripts and ctl & dmp files takes 30-45 minutes, and this was only being done when I run my docker container. THis way I have managed for it to start up and connect successfully

But I want to do this when I build my image, so when I run it it is quicker. So I did this by calling the runOracle.sh script in a run statement, I slightly modified the script  and removed this 2 lines from the bottom , else the build job never quits
tail -f $ORACLE_BASE/diag/rdbms/*/*/trace/alert*.log &
childPID=$!
wait $childPID

My Dockerfile

FROM db-base-12g
MAINTAINER Brian Flowerday
COPY data/* $ORACLE_BASE/admin/XE/dpdump/dpse_dump/
COPY scripts/ $ORACLE_BASE/scripts/
COPY lookup/ $ORACLE_BASE/lookup/
COPY views/ $ORACLE_BASE/views/
COPY create_db.sh $ORACLE_BASE/scripts/build/
COPY runOracle_build.sh $ORACLE_BASE/scripts/

RUN chmod -R 777 $ORACLE_BASE/admin
RUN chmod -R 777 $ORACLE_BASE/diag/rdbms
RUN chmod -R 777 $ORACLE_BASE/diag/tnslsnr
RUN chmod -R 777 $ORACLE_BASE/admin
RUN chmod -R 777 $ORACLE_BASE/lookup
RUN chmod -R 777 $ORACLE_BASE/views/

USER oracle
RUN /bin/bash -c 'source $ORACLE_BASE/scripts/runOracle_build.sh'
CMD exec $ORACLE_BASE/scripts/$START_FILE

#But when I run through my docker-compose file I get the following

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 11-AUG-2017 03:47:40
db        |
db        | Copyright (c) 1991, 2016, Oracle.  All rights reserved.
db        |
db        | Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...
db        |
db        | TNSLSNR for Linux: Version 12.2.0.1.0 - Production
db        | System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
db        | Log messages written to /opt/oracle/diag/tnslsnr/c2b85b108ae2/listener/alert/log.xml
db        | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
db        | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
db        |
db        | Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
db        | STATUS of the LISTENER
db        | ------------------------
db        | Alias                     LISTENER
db        | Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
db        | Start Date                11-AUG-2017 03:47:42
db        | Uptime                    0 days 0 hr. 0 min. 0 sec
db        | Trace Level               off
db        | Security                  ON: Local OS Authentication
db        | SNMP                      OFF
db        | Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
db        | Listener Log File         /opt/oracle/diag/tnslsnr/c2b85b108ae2/listener/alert/log.xml
db        | Listening Endpoints Summary...
db        |   (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
db        |   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
db        | The listener supports no services
db        | The command completed successfully
db        | [WARNING] [DBT-10328] Specified GDB Name (XE) may have a potential conflict with an already existing database on the system.
db        |    ACTION: Specify a different GDB Name that does not conflict with existing databases on the system.
db        | [FATAL] [DBT-10317] Specified SID Name (XE) already exists.
db        |    ACTION: Specify a different SID Name that does not already exist.
db        | [ 2017-08-10 20:11:49.022 UTC ] Copying database files
db        | DBCA_PROGRESS : 1%
db        | DBCA_PROGRESS : 13%
db        | DBCA_PROGRESS : 25%
db        | [ 2017-08-10 20:13:28.898 UTC ] Creating and starting Oracle instance
db        | DBCA_PROGRESS : 26%
db        | DBCA_PROGRESS : 30%
db        | DBCA_PROGRESS : 31%
db        | DBCA_PROGRESS : 35%
db        | DBCA_PROGRESS : 38%
db        | DBCA_PROGRESS : 39%
db        | DBCA_PROGRESS : 41%
db        | [ 2017-08-10 20:16:36.283 UTC ] Completing Database Creation
db        | DBCA_PROGRESS : 42%
db        | DBCA_PROGRESS : 43%
db        | DBCA_PROGRESS : 44%
db        | DBCA_PROGRESS : 46%
db        | DBCA_PROGRESS : 47%
db        | DBCA_PROGRESS : 50%
db        | [ 2017-08-10 20:19:02.120 UTC ] Creating Pluggable Databases
db        | DBCA_PROGRESS : 55%
db        | DBCA_PROGRESS : 75%
db        | [ 2017-08-10 20:19:08.546 UTC ] Executing Post Configuration Actions
db        | DBCA_PROGRESS : 100%
db        | [ 2017-08-10 20:19:08.547 UTC ] Database creation complete. For details check the logfiles at:
db        |  /opt/oracle/cfgtoollogs/dbca/XE.
db        | Database Information:
db        | Global Database Name:XE
db        | System Identifier(SID):XE
db        |
db        | SQL*Plus: Release 12.2.0.1.0 Production on Fri Aug 11 03:47:47 2017
db        |
db        | Copyright (c) 1982, 2016, Oracle.  All rights reserved.
db        |
db        | Connected to an idle instance.
db        |
db        | SQL>    ALTER SYSTEM SET control_files='/opt/oracle/oradata/XE/control01.ctl' scope=spfile
db        | *
db        | ERROR at line 1:
db        | ORA-01034: ORACLE not available
db        | Process ID: 0
db        | Session ID: 0 Serial number: 0
db        |
db        |
db        | SQL>    ALTER PLUGGABLE DATABASE PXE SAVE STATE
db        | *
db        | ERROR at line 1:
db        | ORA-01034: ORACLE not available
db        | Process ID: 0
db        | Session ID: 0 Serial number: 0
db        |
db        |
db        | SQL> Disconnected
db        | mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileXE.ora': No such file or directory
db        | mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwXE': No such file or directory
db        | #####################################
db        | ########### E R R O R ###############
db        | DATABASE SETUP WAS NOT SUCCESSFUL!
db        | Please check output for further info!
db        | ########### E R R O R ###############
db        | #####################################
db exited with code 0

I have tried calling the run file instead of start file but the problem I have there is in the oracleRun.sh script when it checks to see fi db exists, it goes into the loop that says db doesn't exist

Please assist

**Comment by gvenzl** [comment]
The installer throws a `FATAL` error: `db | [FATAL] [DBT-10317] Specified SID Name (XE) already exists.`

You shouldn't use `XE` as `XE` is reserved for Express Edition, which there is non for 12c. You may find that that prevents the database from starting up later on which is why the statements are failing with `ORA-01034: ORACLE not available`

**Comment by BrianFlowerday** [comment]
Hi I can use another name Sewell but the error persists. If I start and run
scripts at build time it succeeds. But if I then run that image I get that
error db already exists, and this appears to be in the runOracle.sh script
for some reason the check if db exists is failing so it tries to recreate.

I have also tried just calling the startfile and not runoracle.sh but this
also fails

**Comment by BrianFlowerday** [comment]
Ok So I have changed the SID to SE2
When it build it completes successfully
But when i then use a docker-compose file to start it up I get the following

r-compose up db
Creating db ...
Creating db ... done
Attaching to db
db        |
db        | LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 25-AUG-2017 11:53:12
db        |
db        | Copyright (c) 1991, 2016, Oracle.  All rights reserved.
db        |
db        | Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...
db        |
db        | TNSLSNR for Linux: Version 12.2.0.1.0 - Production
db        | Log messages written to /opt/oracle/diag/tnslsnr/6fdc6710259c/listener/alert/log.xml
db        | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=6fdc6710259c)(PORT=1521)))
db        |
db        | Connecting to (ADDRESS=(PROTOCOL=tcp)(HOST=)(PORT=1521))
db        | STATUS of the LISTENER
db        | ------------------------
db        | Alias                     LISTENER
db        | Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
db        | Start Date                25-AUG-2017 11:53:12
db        | Uptime                    0 days 0 hr. 0 min. 0 sec
db        | Trace Level               off
db        | Security                  ON: Local OS Authentication
db        | SNMP                      OFF
db        | Listener Log File         /opt/oracle/diag/tnslsnr/6fdc6710259c/listener/alert/log.xml
db        | Listening Endpoints Summary...
db        |   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=6fdc6710259c)(PORT=1521)))
db        | The listener supports no services
db        | The command completed successfully
db        |
db        | SQL*Plus: Release 12.2.0.1.0 Production on Fri Aug 25 11:53:12 2017
db        |
db        | Copyright (c) 1982, 2016, Oracle.  All rights reserved.
db        |
db        | Connected to an idle instance.
db        |
db        | SQL> ORA-01078: failure in processing system parameters
db        | LRM-00109: could not open parameter file '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/initSE2.ora'
db        | SQL> Disconnected
db        | 2017-08-25T09:11:40.859001+00:00
db        | Thread 1 advanced to log sequence 9 (LGWR switch)
db        |   Current log# 3 seq# 9 mem# 0: /opt/oracle/oradata/SE2/redo03.log
db        | 2017-08-25T09:12:04.549355+00:00
db        | PXE(3):Resize operation completed for file# 12, old size 5253120K, new size 5254400K
db        | 2017-08-25T09:12:04.762630+00:00
db        | PXE(3):Resize operation completed for file# 12, old size 5254400K, new size 5320960K
db        | PXE(3):Resize operation completed for file# 12, old size 5320960K, new size 5387520K
db        | PXE(3):Resize operation completed for file# 12, old size 5387520K, new size 5454080K
db        | PXE(3):Resize operation completed for file# 12, old size 5454080K, new size 5520640K

**Comment by BrianFlowerday** [comment]
Hi

I solved this, I look at this article https://github.com/oracle/docker-images/tree/master/OracleDatabase/samples/prebuiltdb but Id id not like the commit function, as I cant automate it, my scripts can take anywhere between 40 minutes and 90 minutes to complete, can't then just wait a random time and go and stop the image and commit it

So here is what I did
1. Removed the volume command in the base image
#VOLUME ["$ORACLE_BASE/oradata"]
2. Build the base image
cd docker-images/OracleDatabase/dockerfiles
sh buildDockerImage.sh -v 12.2.0.1 -s
3. Copy the runoracle.sh script , and name it runOracle_build.sh and remove these 3 lines
#tail -f $ORACLE_BASE/diag/rdbms/*/*/trace/alert*.log &
#childPID=$!
#wait $childPID
4.  Create a new dockerfile that extends from the one we just build, in here I set my SID, PDB, PSWD and run all my scripts, the last part of the docker file is the important part
5. Call the run file build with the RUN command, which means it will execute when building
6. use your CMD command when docker run or docker-compose is being used

![image](https://user-images.githubusercontent.com/30920231/29761136-0eb5e730-8bc8-11e7-864b-689d9715358c.png)
7.  Use docker run or docker-compose file to start up

**Comment by gvenzl** [comment]
Closing issue as it has been resolved.
