### ISSUE TITLE
Can't create the Oracle Database 12.1.0.2 container (DBCA failure) with db_block_size>8Кб

### ISSUE THREAD

**Issue by vitassecuriti** [oracle/docker-images#540]
By the machine from x64 Windows 7 OS Oracle VirtualBox (Ubuntu 16/04) is set.
In this virtualka docker is set. In attempt to sodat the database - I received permanently an error in logs

`ORA-01041: internal error. hostdef extension doesn't exist`

by practical consideration I clarified that to an error presence of parameter of initialization of the 

**`db_block_size=16kb`**

 database brings. In case of change of this parameter on **8 CКб** (or if not to specify generally), then the database is created and works.

In Ubuntu parameter is exposed
```
# blockdev - getbsz/dev/sda1 
4096
```

 docker info
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 26
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-58-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.041GiB
Name: talik-VirtualBox
ID: 4XXG:KXWX:74DM:5IB7:LJIO:AIJH:ZSCB:HU26:KO37:DEHV:TA5S:LMGR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

Tell how to achieve from the docker that the database of Oracle with db_block_size=16kb was created?

**Comment by vitassecuriti** [comment]
somebody tried on the systems? whether the mistake repeated?

**Comment by gvenzl** [comment]
Looks like you are facing this or an error similar to this: https://oracle-base.com/articles/misc/ora-01041-internal-error-hostdef-extension-doesnt-exist

Can you tell us which database version you are running.
And I assume I understand correctly that you are running on a Windows machine which has a VirtualBox VM running Ubuntu on it where you try to run your container?

**Comment by vitassecuriti** [comment]
> Can you tell us which database version you are running.
yes.Oracle Database 12.1.0.2 ee

> And I assume I understand correctly that you are running on a Windows machine which has a VirtualBox VM running Ubuntu on it where you try to run your container?
Yes. Host (OS Windows 7 x64 Professional). Guest (Ubuntu 16.04 from VirtualBox)

**Comment by gvenzl** [comment]
Thanks. You are trying to install Oracle on CentOS which is not a supported OS by the Oracle database. Although it is technically possible it's something that I can't diagnose as I'm not running on such a configuration. I recommend you look at https://wiki.centos.org/HowTos/Oracle12onCentos7 and https://oracle-base.com/articles/misc/ora-01041-internal-error-hostdef-extension-doesnt-exist to overcome the issue.

**Comment by vitassecuriti** [comment]
Thanks for the response. Need to check identity of behavior and an error in case of installation of the database forced to use an image of Centos7 me. On oraclelinux the error repeats.

**Comment by vitassecuriti** [comment]
Excuse me, but what does the lable "invalide" for issue? Prompt, the FS docker generally supports oracle with parametr db_block_size> 8kb? Today once again trying to unearth something on this issue found an error
```
DBCA_PROGRESS: 8%
ORA-00058: DB_BLOCK_SIZE Must be 8192 to mount this database (not 16384)
```
In the logs, when installing a clean configuration (no changes except the dbca.rsp file)

**Comment by gvenzl** [comment]
Hi @vitassecuriti,

The "invalid" label indicates that this issue is not regarding the build files themselves and/or happens on a supported configuration.

You will find that the installation happening inside the Docker container is performed using the General Purpose template. That template comes with a "seed database" which uses the 8k block size. After restoring that database the installer finds that you are trying to use a block size of 16k on a database with 8k block size and hence you receive that error.

The images do not support other block sizes per default as 8k is the default and recommended database block size. However, it is ok to build another image based on this one and using a different block size but that means that the installation process for that image is upon the user to provide.

In your case you will need to provide a template that doesn't rely on a 8k block size. You can find more information about creating a database and using templates in the [Oracle Database Documentation](http://docs.oracle.com/database/122/ADMQS/installing-oracle-database-creating-database.htm#ADMQS0231).

I'm curious though. What database dump do you have? Is that just a tablespace or a full export? Can you please elaborate a bit more on that.

**Comment by vitassecuriti** [comment]
Good evening. I not absolutely understood. I.e. the image does not support the db_block_size size&gt; 8Kb? 
In that case, I do not understand yet what parameters of an image can influence the size of the admissible db_block_size parameter?

I correctly understand that FS docker supports a possibility of creation of the database with a size of blocks over 8 KB?

`I'm curious though. What database dump do you have? Is that just a tablespace or a full export? Can you please elaborate a bit more on that`

Scripts of reconstruction of the database include:
- creations of table namespace, schemes and users, separation of grants, etc.
- restoration of structure of a DB from dumpings.
- filling with primary data, handbook data
- setup of patches and bringing version control of the database to current state.

It is all set of actions which it is made after the database with the necessary parameters is created.

**Comment by gvenzl** [comment]
> Good evening. I not absolutely understood. I.e. the image does not support the db_block_size size> 8Kb?
> In that case, I do not understand yet what parameters of an image can influence the size of the admissible db_block_size parameter?
> 
> I correctly understand that FS docker supports a possibility of creation of the database with a size of blocks over 8 KB?

It means that this image does not give you any other choice but a database with an 8k block size. There is no parameter for you to change this, it is not supported by that image. If you need a database with a different block size you need to create your own image. You can base your own image on the provided one, as the software install will remain the same. However, the database creation of a 16k block size database is up to you to provide.

> Scripts of reconstruction of the database include:
> 
> - creations of table namespace, schemes and users, separation of grants, etc.
> - restoration of structure of a DB from dumpings.
> - filling with primary data, handbook data
> - setup of patches and bringing version control of the database to current state.

None of the above have any dependency on the block size of the database.
`expdp`/`impdp` are block size agnostic, which I assume is meant by "dumpings".
You may also want to refer to [MOS Note 1011167.7 - How to Change Database Block Size](https://support.oracle.com/epmos/faces/DocumentDisplay?id=1011167.7)

**Comment by gvenzl** [comment]
Closing based on the explanation given.
