### ISSUE TITLE
No "-p" option for buildDockerImage.sh

### ISSUE THREAD

**Issue by SquirrelNinja** [oracle/docker-images#545]
I am trying to solve an issue that might be related to ticker #134.  The solution listed in that ticket is to use -p to supply an oracle password.  However these are the valid args for buildDockerImage.sh:

Usage: buildDockerImage.sh -v [version] [-e | -s | -x] [-i] [-o] [Docker build option]
Builds a Docker Image for Oracle Database.

Parameters:
   -v: version to build
       Choose one of: 11.2.0.2  12.1.0.2  12.2.0.1
   -e: creates image based on 'Enterprise Edition'
   -s: creates image based on 'Standard Edition 2'
   -x: creates image based on 'Express Edition'
   -i: ignores the MD5 checksums
   -o: passes on Docker build option

Any thoughts would be appreciated...

**Comment by gvenzl** [comment]
Please refer to the actual [ReadMe](https://github.com/oracle/docker-images/tree/master/OracleDatabase#running-oracle-database-enterprise-and-standard-edition-2-in-a-docker-container).

You have to use `-e ORACLE_PWD=<your database passwords>` during `docker run`.

**Comment by SquirrelNinja** [comment]
So I am running it that way as it turns out, so I must have just misunderstood the nature of the information in the ticket.  Thanks.
