### ISSUE TITLE
WebLogic: generic container no longer starts

### ISSUE THREAD

**Issue by lukasredynk** [oracle/docker-images#546]
I've prepared Dockerfile with app extending 12212-generic image, I've also used "container scripts" from 12212-domain sample and it worked with HEAD at Jun 15 '17, but after checking out to master 16 Aug '17 it didn't work anymore. I've tried setting env options in "domain.properties" but still server is exiting before even starting, I think relevant error is:
<Aug 17, 2017 7:58:14 AM GMT> <Info> <Security> <BEA-090065> <Getting boot identity from user.>Enter username to boot WebLogic server:<Aug 17, 2017 7:58:14 AM GMT> <Error> <Security> <BEA-090782> <Server is running in Production Mode and the System Console to read the password securely from the command line was not found. The System Console is not present if stdin, stdout, or stderr is redirected when starting WebLogic Server.>

Am I missing something here? I didn't saw information in any readme about setting extra credentials to boot server.

**Comment by mriccell** [comment]
Please try the 12213-domain image the problem has been fixed.

**Comment by willzhang** [comment]
i have the problem too,the follow is what i do:

```
docker pull store/oracle/serverjre:8
cd docker-images/OracleWebLogic/dockerfiles
sh buildDockerImage.sh -v 12.2.1 -g
cd docker-images/OracleWebLogic/samples/1221-domain/
docker build -t 1221-domain --build-arg ADMIN_PASSWORD=welcome1 --build-arg ADMIN_NAME=WL_AdminServer .

```
### run the container
```
 docker run -d --name wlsadmin --hostname wlsadmin -p 7001:7001 1221-domain
```
###got the error

```
Enter username to boot WebLogic server:<Apr 19, 2019 1:45:41 PM GMT> <Error> <Security> <BEA-090782> <Server is running in Production Mode and the System Console to read the password securely from the command line was not found. The System Console is not present if stdin, stdout, or stderr is redirected when starting WebLogic Server.> 
```
why don't you resolve the problem, i don't want to use 12213.

**Comment by mriccell** [comment]
1221 is not a supported version of WebLogic, I am about to retire all the unsupported images and samples.  All improvements and enhancements to images are made to 12.2.1.3, I recommend you run with 12.2.1.3.
Monica

**Comment by willzhang** [comment]
ok ,i know ,i will try 12.2.1.3 again ,thanks.
