### ISSUE TITLE
Oracle 12.2.0.1 EE Dockerfile build points at cleanup tip for yum install

### ISSUE THREAD

**Issue by klauern** [oracle/docker-images#555]
I was watching the Docker build for oracle/database:12.2.0.1-ee, and noticed that it mentioned something that wasn't being done in between steps 7 and 8:

```sh
...  
  systemd.x86_64 0:219-42.0.1.el7
  systemd-libs.x86_64 0:219-42.0.1.el7
  systemd-sysv.x86_64 0:219-42.0.1.el7
  sysvinit-tools.x86_64 0:2.88-14.dsf.el7
  tcp_wrappers.x86_64 0:7.6-77.el7
  tcp_wrappers-libs.x86_64 0:7.6-77.el7
  util-linux.x86_64 0:2.23.2-43.el7
  xorg-x11-utils.x86_64 0:7.5-22.el7
  xorg-x11-xauth.x86_64 1:1.0.9-1.el7
  xz.x86_64 0:5.2.2-1.el7

Complete!
Loaded plugins: ovl
Cleaning repos: ol7_UEKR4 ol7_latest
Cleaning up everything
Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos
 ---> 8b815822c42e
Removing intermediate container 8adf5f138aad
Step 8/16 : USER oracle
 ---> Running in b0422ea0152e
 ---> 36f2b6902a62
Removing intermediate container b0422ea0152e
Step 9/16 : RUN $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE EE
```

**Comment by gvenzl** [comment]
Hm, that's interesting. The script runs a `yum clean all` which was run successfully, but then it's yum printing that message. Hey @Djelibeybi, is this a common behavior of yum or is somthing missing? Wouldn't be difficult to add that rm afterwards.

**Comment by gvenzl** [comment]
Hey @Djelibeybi, do you have any more input on this one?

**Comment by gvenzl** [comment]
@Djelibeybi, any insights on why `yum` is printing the message `Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos` and whether this should be added into the standard cleanup routine?

**Comment by Djelibeybi** [comment]
It can be safely ignored. Yum doesn't actually check to see if there IS any orphaned data.

**Comment by brunoborges** [comment]
Is there a parameter we can add to yum to avoid this warning? This way we can prevent other users from reporting this same _concern_.

**Comment by Djelibeybi** [comment]
I don't think so. We could just switch to actually running `rm -rf /var/cache/yum/*` in our Dockerfiles. Probably simpler. :)

**Comment by brunoborges** [comment]
Not a bad idea =) Can you quickly and dirtily do a PR with a grep/sed changing the call on all files? :-)

**Comment by Djelibeybi** [comment]
Not right now, but I can look at doing that tomorrow. :)

**Comment by gvenzl** [comment]
Closing this in favor of PR #607. Thanks for reporting this, @klauern!
