### ISSUE TITLE
Yum repo issues?

### ISSUE THREAD

**Issue by k00p** [oracle/docker-images#557]
The oracle yum repo had a security update yesterday, and now calls to yum from oraclelinux:7-slim fail with the error:

```
http://yum.oracle.com/repo/OracleLinux/OL7/UEKR4/x86_64/repodata/primary.xml.gz: [Errno -1] Metadata file does not match checksum
```

Do new repo files need to be propagated to the image?

**Comment by Djelibeybi** [comment]
No, this is just a timing issue that will resolve itself.
