### ISSUE TITLE
Node Manager on externalized data volumes fail to start when clustering on the same host

### ISSUE THREAD

**Issue by matanders** [oracle/docker-images#558]
Working with the OracleWeblogic/samples/12212-domain, I have the admin container and a node container up and running.  When launching a second node container (to test clustering) the second node does not come up. 

error:
SEVERE: Fatal error in NodeManager server
java.io.IOException: Could not obtain exclusive lock with lockFile '/u01/oracle/user_projects/domains/my_domain/nodemanager/nodemanager.process.lck'. This most likely indicates another NodeManager process is already running in this NodeManaagerHome.

 Issue is when mapping the volume from the admin server (-volumes-from wlsadmin), the nodemanager is already running in the first node container so a lock file exists and any further nodemanagers (who use the same domain) will fail.

The Readme states : You may create more containerized Managed Servers by calling the docker command above for createServer.sh as long you link properly with the Admin Server.

How can this be done with the data volume being externalized?

**Comment by mriccell** [comment]
@matanders yes I have an error on my script I need to have a separate NM directory for every MS.  I am working on this fix.

**Comment by mriccell** [comment]
This has been resolved in the 12213-domain image.  Can you try to create the domain image for 12213?
