### ISSUE TITLE
Proxy protocol between WebLogic AdminServer and ManagedServer

### ISSUE THREAD

**Issue by vitan** [oracle/docker-images#56]
I am trying to insert a HAproxy between WebLogic AdminServer and ManagedServer, while sth is going wrong. I found there is something wrong about the protocol **t3** in  [cmd](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/1221-domain/container-scripts/add-machine.py#L37) , which seems different from tcp. 
any suggestion about that?

**Comment by Djelibeybi** [comment]
This has nothing to do with Docker or the image. This is an issue between WebLogic and HAProxy. You're probably better off using Oracle HTTP Server with the WebLogic plugin, but either way, you'll get more answers over at the WebLogic space on the Oracle Community forums: https://community.oracle.com/community/fusion_middleware/weblogic
