### ISSUE TITLE
managed server listen address is incorrect

### ISSUE THREAD

**Issue by aquasheep20** [oracle/docker-images#567]
On a managed server restart, the container may not get the same ip address.  When this occurs the managed server won’t start.  The listen address should be set to hostname when the MS_NAME variable is passed.   The current behavior will remain unchanged if MS_HOST env variable is not passed as mshost defaults to msinternal    

samples/container-scripts/add-server.py is setting ListenAddress as container ip address:
cmo.setListenAddress(msinternal) 

It should be:
cmo.setListenAddress(mshost)

**Comment by brunoborges** [comment]
Hi @aquasheep20, can you provide a PR in which we can test this change?

**Comment by aquasheep20** [comment]
PR opened

**Comment by brunoborges** [comment]
Thanks. We are look into it.

**Comment by mriccell** [comment]
Fixed and code merged
