### ISSUE TITLE
$CONTAINERCONFIG_DIR/RCU.$RCUPREFIX.suc invalid check.. 

### ISSUE THREAD

**Issue by kulbhushan1** [oracle/docker-images#574]
In the below script $CONTAINERCONFIG_DIR/RCU.$RCUPREFIX.suc is not created after successful execution of RCU. making it an invalid check.

OracleFMWInfrastructure/dockerfiles/12.2.1.2/container-scripts/createOrStartInfraDomain.sh

**Comment by mriccell** [comment]
@kulbhushan1 Make sure if RCU ran successfully but you ran into an error when you create the domain to use a new unique RCU Prefix.

**Comment by mriccell** [comment]
@kulbhushan1 are you still facing this issue?

**Comment by mriccell** [comment]
Please reopen if still facing this issue
