### ISSUE TITLE
Oracle 12cR1

### ISSUE THREAD

**Issue by I050689** [oracle/docker-images#582]
Hello,

The image is created without any issues, the container is starting and is alive for 10 seconds.
Than it's stopping.

I have no error.
Please advice.
Daniela

**Comment by I050689** [comment]
I identify the issue, but not sure how to resolve it.
If I start the container without the option -v /myspace/oracle:/opt/oracle/oradata is working.
How can I use this option?

Thank you,
Daniela

**Comment by gvenzl** [comment]
You are most likely running into a permission issue with the volume. Are you sure that the container can write to the volume? Have a look at `docker logs` for your container and also post the output here.

**Comment by I050689** [comment]
Hi Gérald,

You're right.

It is working now.

Thank you.
Daniela
