### ISSUE TITLE
/u01/oracle/container-scripts/createInfraDomainAndStartAdmin.sh: line 119: /u01/oracle/oracle_common/bin/rcu: No such file or directory

### ISSUE THREAD

**Issue by typekpb** [oracle/docker-images#584]
built base image in: `OracleJava/java-8`
via: 

    ./build.sh

built fmw image in: `OracleFMWInfrastructure/dockerfiles`

via: 

    ./buildDockerImage.sh -v 12.2.1.3

trying to run it results in:

	docker run -p 9001:7001 --env-file ./12.2.1.3/infraDomain.env.list oracle/fmw-infrastructure:12.2.1.3
	Configuring Domain for first time run
	=====================================
	CONNECTION_STRING=MYInfraDB:1521/InfraPDB1
	RCUPREFIX=INFRA6
	DOMAIN_NAME=InfraDomain
	Loading RCU Phase
	=================
	CONNECTION_STRING=MYInfraDB:1521/InfraPDB1
	RCUPREFIX=INFRA6
	DB_PASSWORD=MyDBPassword
	jdbc_url=jdbc:oracle:thin:@MYInfraDB:1521/InfraPDB1
	ADMIN_PASSWORD=MyWLSPassword
	DB_SCHEMA_PASSWORD=MyDBPassword
	DB_USERNAME=sys
	DOMAIN_HOME: /u01/oracle/user_projects/domains/InfraDomain
	Loading SOA RCU into database
	/u01/oracle/container-scripts/createInfraDomainAndStartAdmin.sh: line 119: /u01/oracle/oracle_common/bin/rcu: No such file or directory
	RCU has some error 
	RCU Loading Failed.. Please check the RCU logs

**Comment by kocic11** [comment]
Same here. A few questions:
- Where are the RCU logs and how to get them considering the container is not running?
- Who or what should run the RCU utility? Is it expected to have RCU schemas already created before running the container?

Regards,
Aleksandar

**Comment by kocic11** [comment]
I managed to get Admin server up and running by resolving a couple of issues:
- Overlay network was not configured properly and the connectivity to the DB image didn't work.
- Once it was resolved, the second issue was permission denied for the shared folder. This one required a change in the run command from

-v $HOST_VOLUME:/u01/oracle/user_projects 

to

-v $HOST_VOLUME:/u01/oracle/user_projects:z

Regards,
Aleksandar

**Comment by kocic11** [comment]
To start managed server, I had to change the domain home in OracleFMWInfrastructure/dockerfiles/12.2.1.3/container-scripts/startManagedServer.sh

from 
export DOMAIN_HOME="/u01/oracle/user_projects/domains/InfraDomain"

to 
export DOMAIN_HOME="/u01/oracle/user_projects/domains/$DOMAIN_NAME"

The domain name shouldn't be hardcoded.

Regards,
Aleksandar

**Comment by typekpb** [comment]
Any chance for pull request?

**Comment by kocic11** [comment]
@typekpb Just to make it clear. While these are small nuances, they are not the same issues as described above.

In your case, is the database up and running? Based on the connection string and passwords, it seems you have not changed the default values and the database may not be available. 

Just to check what is going on, can you run the following command if the container is running
docker exec -it <container_name> /bin/bash

If it is not running:
docker run -it oracle/fmw-infrastructure:12.2.1.3 /bin/bash

Once inside the container, run the following command and post the output:
ls -l /u01/oracle/oracle_common/bin/

Regards,
Aleksandar

**Comment by mriccell** [comment]
In the README it says that the first step is to define a network bridge $ docker network create -d bridge InfraNET where both the FMW and DB images run.  This should resolve the first issue.

I am working on a PR to fix the VOLUME to be created inside of the built image and provide the correct permissions.   This should resolve the second issue.

**Comment by mriccell** [comment]
Corrected the VOLUMES permission in #636
