### ISSUE TITLE
Misleading documentation regarding oradata volume

### ISSUE THREAD

**Issue by kaserf** [oracle/docker-images#588]
Hi,

currently the documentation mentions that the mapped volume for oradata `Has to be owned by the Unix user "oracle" or set appropriately.`

This is quite misleading, becuase the user id of any oracle user *outside* the container needs to match the user id of the oracle user *inside* the container. Just creating an oracle user on the host and having that user own the volume mount on the host is not enough. I guess it should either specify the user id the user needs to have or that the directory needs to be world read/writable.

Cheers
Felix

**Comment by gvenzl** [comment]
Hey @kaserf, thanks for reporting this! I agree, the documentation is a bit lax here and doesn't differentiate between the user `oracle` inside the container and outside of it. Plus, there are other ways to get volumes created too which aren't covered either in the ReadMe yet. Will address that shortly!

**Comment by gvenzl** [comment]
PR with fix is in!
