### ISSUE TITLE
Dockerfile.* error(weblogic)

### ISSUE THREAD

**Issue by bikboy** [oracle/docker-images#59]
Seems that oracle/oraclelinux image that downloaded by this scripts its not include jdk installed within. and weblogic creation scripts is not working. There error:
/bin/bash /usr/java/default/bin/jar : File or Directory does not exists
bin/bash /usr/java/default/bin/java : File or Directory does not exists

**Comment by brunoborges** [comment]
How are you building the image? Please provide as many details as possible.

**Comment by bikboy** [comment]
@brunoborges i just did all you by instruction, but in first step when we run script buildDockerImage.sh there first step where Dockerfile.developer(or whatever) script download oracle/oraclelinux image:
# Pull base image
# ---------------
FROM oracle/oraclelinux:latest
So problem is - this image dont include jdk installed within
I solve tihs problem by installing jdk rpm into this downloaded oraclelinux image

**Comment by Djelibeybi** [comment]
The Dockerfile.developer adds the JRE itself via the follow `ADD` command:

`ADD $JAVA_PKG /usr/java/`

You need to make sure you've downloaded `server-jre-8u65-linux-x64.gz` properly, as per the instructions before you start the build too.

**Comment by bikboy** [comment]
ofcourse i did it , but in instruction there server-jre-8u65-linux-x64.tar.gz mention(.download file) so i just tar this gz archive to tar.gz , is my problem was in that? jre not installed properly?

**Comment by Djelibeybi** [comment]
This has been fixed via an update. Please update your git repo to get the latest instructions.

**Comment by bikboy** [comment]
yap, after repo update - all work great, thx
