### ISSUE TITLE
Need to build a non-CDB Oracle database

### ISSUE THREAD

**Issue by evantill** [oracle/docker-images#592]
In need to migrate a non-CDB database to a PDB.
But before the migration, I need to install a non-CDB instance to work on it and tests.

Actually it is not possible to build an image in non-CDB mode.

see PR https://github.com/oracle/docker-images/pull/586

**Comment by pbranforn** [comment]
I had the same issue and there is actually a patch available for this, but not supported by Oracle. See the explanation and code here:
https://github.com/oracle/docker-images/pull/586

**Comment by gvenzl** [comment]
Closing this issue as comments have been provided in PR #586 which is from the same author as this issue.
