### ISSUE TITLE
How I will enable the partitioning option?

### ISSUE THREAD

**Issue by klearchos** [oracle/docker-images#597]
Hello I followed the instructions for the OracleDatabase and I managed to have a 12.1.2.0 Oracle DB up and running.
But I need to have the partitioning option enabled. How do we do this?
Thank you a lot!

**Comment by gvenzl** [comment]
Hi @klearchos, the Partitioning option is enabled by default:

```
[oracle@localhost ~]$ docker run -d -p 1521:1521 -e ORACLE_PWD=LetsDocker oracle/database:12.1.0.2-ee
56d8acbe73a3096edfacd0bc75ac7b5ef86f0f2c3533e52cad341e56847e545b
[oracle@localhost ~]$ docker exec -ti dreamy_wilson sqlplus system/LetsDocker@//localhost:1521/ORCLPDB1

SQL*Plus: Release 12.1.0.2.0 Production on Wed Oct 11 01:19:45 2017

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

SQL> grant connect, resource to test identified by test;

Grant succeeded.

SQL> alter user test quota unlimited on users;

User altered.

SQL> conn test/test@//localhost:1521/ORCLPDB1
Connected.

SQL> create table test_part (id number) partition by hash (id);

Table created.

SQL> select table_name, partition_name from user_tab_partitions;

TABLE_NAME
--------------------------------------------------------------------------------
PARTITION_NAME
--------------------------------------------------------------------------------
TEST_PART
SYS_P201
```

**Comment by klearchos** [comment]
Hi,
I created the image with the SE2. I should change this to the EE version.
Thank you a lot about your reply.

**Comment by gvenzl** [comment]
That is correct, Oracle Database Standard Edition 2 doesn't come with the Partitioning Option, only Enterprise Edition does. That is true for any option.

**Comment by agoretsky** [comment]
@gvenzl Hi, 
I am using container-registry.oracle.com/database/enterprise:12.2.0.1 prebuit docker image, but partitioning options is disabled there.

**Comment by vinmazzi** [comment]
I'm using store/oracle/database-enterprise:12.2.0.1 and partition option is also disabled on it.

**Comment by chandangupta102** [comment]
I'm using store/oracle/database-enterprise:12.2.0.1 and partition option is also disabled on it.
