### ISSUE TITLE
ora-12953

### ISSUE THREAD

**Issue by xiaoli0504** [oracle/docker-images#605]
Thank you very much for your help in the first place, but when I did the data import, I triggered 12953 error. Is this the reason why the oracle11g used by the mirror itself is free？
Is there any solution to this error?

**Comment by Djelibeybi** [comment]
I'm afraid there's no context for your question. Please provide the full information of what you tried, what data import you attempted, the full output of the error, what mirror you're referring to and what error you want a solution for.

**Comment by xiaoli0504** [comment]
I have a DMP file larger than 11g that needs to be imported into The database. When I import, ORA 12953: The request exceeds The maximum allowed database size of 11gb。
The question I want to ask is what is the cause of this? How do you solve this problem。

**Comment by brunoborges** [comment]
Maybe you better off asking on asktom.oracle.com ?

**Comment by gvenzl** [comment]
@xiaoli0504, as the error suggests your import `request exceeds the maximum allowed database size of 11GB`. Oracle Database 11g XE is limited to 11GB of total database size.
