### ISSUE TITLE
Building oracle/database:12.2.0.1-se2 image fails; oraInventory/orainstRoot.sh not found

### ISSUE THREAD

**Issue by wiyh12nf89x** [oracle/docker-images#610]
Command `uname -a` returnes 'Linux localhost.localdomain 4.10.5-1.el7.elrepo.x86_64 #1 SMP Wed Mar 22 14:46:24 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux'
Command `df` returnes '/dev/mapper/cl-root  34938196   6551004  28387192  19% /'
`dockerd` is run with the following arguments: '/usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current --default-runtime=docker-runc --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current --selinux-enabled --log-driver=journald --signature-verification=false'

Steps to reproduce:
1. `wget https://github.com/oracle/docker-images/archive/master.zip`
2. `7z x master.zip`
3. `cd docker-images-master/OracleDatabase/dockerfiles/12.2.0.1/`
4. [Put 'linuxx64_12201_database.zip' here]
Command `cksum linuxx64_12201_database.zip` returnes '4170261901 3453696911 linuxx64_12201_database.zip', therefore the archive is OK.
5. add 'set -x' at the beginning of buildDockerImage.sh for verbosity
6. `cd ..`
7. `./buildDockerImage.sh -s -v 12.2.0.1 -i > build-log0.txt  2>&1`

I also tried executing:
`docker run -ti oraclelinux:7-slim /bin/bash`
`dd if=/dev/zero of=/temp-file bs=1G count=25`
to check if the maximum container size is limited to 10Gb. I'm using overlay2 and it doesn't seem to have this issue.

Build-log:
[build-log0.txt](https://github.com/oracle/docker-images/files/1404798/build-log0.txt)

**Comment by gvenzl** [comment]
Hi @wiyh12nf89x,

Your Docker version seems to be out of date `Server Version: 1.12.6`. Note sure on CentOS but I'm running fine on 17.03-ce and 17.06-ce. The issue you are facing is that the installer never starts off.
It just finishes extracting the zip file and then moves on to the next stage:

```
  inflating: database/stage/globalvariables/variable.properties  
  inflating: database/stage/globalvariables/globalvar.xml  
  inflating: database/stage/install1.jar  
  inflating: database/runInstaller   
 ---> 49aa6b8db272
Removing intermediate container 86f8f6b69f35
Step 10 : USER root
 ---> Running in 90f711883edb
 ---> 6f03f9b1b0e9
Removing intermediate container 90f711883edb
Step 11 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in c5a33471f1b4
[91m/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
[0mRemoving intermediate container c5a33471f1b4
```

Before ` ---> 49aa6b8db272` you should be seeing the database software install. If you want to debug this further you could also put `set +x` into `installDBBinaries.sh`.
In there you will find following:

```
# Install Oracle binaries
cd $INSTALL_DIR       && \
unzip $INSTALL_FILE_1 && \
rm $INSTALL_FILE_1    && \
$INSTALL_DIR/database/runInstaller -silent -force -waitforcompletion -responsefile $INSTALL_DIR/$INSTALL_RSP -ignoresysprereqs -ignoreprereq && \
cd $HOME
```

It seems like that the line `$INSTALL_DIR/database/runInstaller -silent -force -waitforcompletion -responsefile` is never executed.

**Comment by wiyh12nf89x** [comment]
Thank you for your help.
Well, it seems that I found the problem. It was neither docker, nor Oracle scripts. The problem was in CPU overclock which led to unstable executing of `cp` and `unzip` commands. Restoring the original clock solved the problem.

But I see another implicit problem here. If you start `./buildDockerImage.sh` with `-i` option on a corrupted database archive (file 'linuxx64_12201_database.zip' in my case) (e. g. you have downloaded the file on other PC with X-server and web-browser, checked the checksum and the error appeared later, while copying to the destination), the following code:
```# Install Oracle binaries
cd $INSTALL_DIR       && \
unzip $INSTALL_FILE_1 && \
rm $INSTALL_FILE_1    && \
$INSTALL_DIR/database/runInstaller -silent -force -waitforcompletion -responsefile $INSTALL_DIR/$INSTALL_RSP -ignoresysprereqs -ignoreprereq && \
cd $HOME

# Remove not needed components
rm -rf $ORACLE_HOME/apex && \
rm -rf $ORACLE_HOME/jdbc && \
```
will never explicitly notify you about this problem. Moreover, executing `unzip` on a corrupted file will return exitcode '2' and thus script will silently skip the next 3 commands that are essential for database installation. Instead, the script will continue from `rm -rf $ORACLE_HOME/apex && \` command until it will encounter the absence of `$ORACLE_BASE/oraInventory/orainstRoot.sh` file that was not created during the install, since it was skipped. That is what actually happened in my case.

So, I propose the following solution:
Replace the following code:
```
# Install Oracle binaries
cd $INSTALL_DIR       && \
unzip $INSTALL_FILE_1 && \
rm $INSTALL_FILE_1    && \
$INSTALL_DIR/database/runInstaller -silent -force -waitforcompletion -responsefile $INSTALL_DIR/$INSTALL_RSP -ignoresysprereqs -ignoreprereq && \
cd $HOME
```
with the code:
```
# Install Oracle binaries
cd $INSTALL_DIR       && \
unzip $INSTALL_FILE_1
UNZIP_EXITCODE=$?
# Check whether unzip unpacked all files successfully
if [ "$UNZIP_EXITCODE" -ne "0" ]; then
   echo "ERROR: unzip returned non-zero exitcode!"
   echo "Check the archive integrity or access permissions of this file: $INSTALL_FILE_1!"
   exit 1;
fi
rm $INSTALL_FILE_1    && \
$INSTALL_DIR/database/runInstaller -silent -force -waitforcompletion -responsefile $INSTALL_DIR/$INSTALL_RSP -ignoresysprereqs -ignoreprereq && \
cd $HOME
```

**Comment by gvenzl** [comment]
Thanks @wiyh12nf89x, I agree with you, the error handling could be better in such case. However, the `-i` option should only be used when one is sure that the zip file is the correct one and not corrupted. So I'm tempted not to change the build files with added complexity given that this error wouldn't have occurred in the first place if the `-i` option wouldn't have been specified. Am I correct in that assumption?

**Comment by gvenzl** [comment]
Closing due to lack of response.
