### ISSUE TITLE
Unable to build Docker image from docker-images/OracleJava/java-8/

### ISSUE THREAD

**Issue by maheshbabuadapa** [oracle/docker-images#613]
[root@wiki java-8]# ./build.sh (docker build -t oracle/serverjre:8 .)
Sending build context to Docker daemon 4.608kB
Step 1/5 : FROM oraclelinux:7-slim
7-slim: Pulling from library/oraclelinux
2bf8c3d0d93d: Pull complete 
Digest: sha256:9a061cb9fba44ddb197ddf5d48b50c7127350ef2e3c26694f1e906865ffcd5fe
Status: Downloaded newer image for oraclelinux:7-slim
---> a6e9e9e5ddc1
Step 2/5 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
---> Running in 44a2d9162a03
---> 7f93aff6a4fa
Removing intermediate container 44a2d9162a03
Step 3/5 : ENV JAVA_PKG server-jre-8u*-linux-x64.tar.gz JAVA_HOME /usr/java/default
---> Running in e9b06151a946
---> c97e45c57028
Removing intermediate container e9b06151a946
**Step 4/5 : ADD $JAVA_PKG /usr/java/
ADD failed: no source files were specified"**

**Comment by brunoborges** [comment]
Please check the README.md file in this folder. You must download the Oracle Java binary from OTN.
