### ISSUE TITLE
Unable to create docker image from oracle/docker-images/Java-8

### ISSUE THREAD

**Issue by maheshbabuadapa** [oracle/docker-images#614]
[root@wiki java-8]# ./build.sh (docker build -t oracle/serverjre:8 .)
Sending build context to Docker daemon 4.608kB
Step 1/5 : FROM oraclelinux:7-slim
7-slim: Pulling from library/oraclelinux
2bf8c3d0d93d: Pull complete 
Digest: sha256:9a061cb9fba44ddb197ddf5d48b50c7127350ef2e3c26694f1e906865ffcd5fe
Status: Downloaded newer image for oraclelinux:7-slim
---> a6e9e9e5ddc1
Step 2/5 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
---> Running in 44a2d9162a03
---> 7f93aff6a4fa
Removing intermediate container 44a2d9162a03
Step 3/5 : ENV JAVA_PKG server-jre-8u*-linux-x64.tar.gz JAVA_HOME /usr/java/default
---> Running in e9b06151a946
---> c97e45c57028
Removing intermediate container e9b06151a946
Step 4/5 : ADD $JAVA_PKG /usr/java/
ADD failed: no source files were specified"

**Comment by alejandropg** [comment]
Have you download manually the Java 8 tar?
You need to download it from http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html and copy in the same directory of `Dockerfile`

**Comment by maheshbabuadapa** [comment]
Thank you,  I downloaded the office file from the link. Now I can build image **oracle/serverjre:8**
but when I trying access the container getting following errors.
Even after an image is created but java is not present in the container.

[root@wiki java-8]# docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
oracle/serverjre           8                   6b8f16ee920f        7 seconds ago       118MB
blacklabelops/confluence   latest              d76a21872a68        42 hours ago        980MB
oraclelinux                7-slim              a6e9e9e5ddc1        3 weeks ago         118MB
[root@wiki java-8]# docker run -it oracle/serverjre:8 /bin/bash
**bash-4.2# java -version**
**bash: java: command not found**
bash-4.2# which java
bash: which: command not found
bash-4.2#

**Comment by brunoborges** [comment]
Try `docker run -ti oracle/serverjre:8 java -version`

**Comment by maheshbabuadapa** [comment]
Thank you so much for your reply but still facing the same issue I tried to create new image but not working. I tried in Centos7 and Ubuntu 16.4 with Docker version 17.09.0-ce, build afdb6d4
Can you tell me which version of Docker your using and Linux 

-rw-r--r-- 1 root root 5307 Mar 20  2012 server-jre-8u152-linux-x64.tar.gz
-rw-r--r-- 1 root root  633 Oct 27 18:50 Dockerfile
-rwxr-xr-x 1 root root   47 Oct 27 18:50 build.sh
root@minion1:~/docker-images/OracleJava/java-8# docker run -ti oracle/serverjre:8 java -version
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"java\": executable file not found in $PATH".
root@minion1:~/docker-images/OracleJava/java-8# docker -v
Docker version 17.09.0-ce, build afdb6d4

**Comment by Djelibeybi** [comment]
`-rw-r--r-- 1 root root 5307 Mar 20 2012 server-jre-8u152-linux-x64.tar.gz`

This file is WAY to small to actually be the proper JRE tarball. I think you'll find it's HTML. Please note that you cannot use `wget` to just grab the tarball. You need to accept the OTN license so you must download it using a browser and then copy it into place. 

You should also check that the `md5sum` checksum is valid before building the image.

**Comment by alejandropg** [comment]
@Djelibeybi is right!
This is my file:
`-rw-r--r-- 1 alex  staff  54778257 Oct 25 11:42 server-jre-8u152-linux-x64.tar.gz`
54778257 = 52M

**Comment by brunoborges** [comment]
Can you please try update 151?

**Comment by maheshbabuadapa** [comment]
Thank you so much guys for your help. It is because of jre file I used Wget to download
