### ISSUE TITLE
Listener warning

### ISSUE THREAD

**Issue by KristjanVall** [oracle/docker-images#615]
Hello i get 
"The listener configuration is not selected for the database. EM DB Express URL will not be accessible."

and do not get the http://localhost:5500/em to work

**Comment by gvenzl** [comment]
I believe that this is a red herring. OEM is exposed via `https` and not `http`. Can you try that. Have you also exposed the port 5500 to your local environment?

**Comment by gvenzl** [comment]
Closing due to lack of response.
