### ISSUE TITLE
Nslookup doesn't work on OEL 7.4

### ISSUE THREAD

**Issue by ding-jax** [oracle/docker-images#616]
Greetings Docker Community,

I have the following issues with Docker container. Name lookup (nslookup) doesn't work.

```
[root@yumoel1]# nslookup index.docker.io
;; connection timed out; trying next origin
;; connection timed out; trying next origin
```

However, If I can pull docker image, It works.

```
[root@yumoel1]# docker version
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.6.1
OS/Arch (client): linux/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.6.1
OS/Arch (server): linux/amd64

[root@yumoel1]# docker info
Containers: 11
Images: 182
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 4.1.12-94.3.9.el7uek.x86_64
Operating System: Oracle Linux Server 7.4
CPUs: 1
Total Memory: 1.701 GiB
Name: yumoel1-m1-inf
ID: 54GM:6A2Y:5FNQ:H75K:Z767:DRAP:VJCV:XXKH:6VSF:MBCY:LCMU:EFLQ
[root@yumoel1]# 
```

**Comment by gvenzl** [comment]
Can you please be a bit more precise what you mean by "_However, If I can pull docker image, It works_". Are you perhaps behind a firewall and need a proxy?

Btw, your version of Docker seems very, very old! You may want to update to a later version as 1.6 had many bugs that are long fixed now.

**Comment by Djelibeybi** [comment]
This appears to be an issue with your host configuration, not Docker. You're running `nslookup` on the host, i.e. the same machine that's running Docker.
