### ISSUE TITLE
docker swarm is not a docker command

### ISSUE THREAD

**Issue by ding-jax** [oracle/docker-images#619]
Hi Dockers...

I am trying to create a docker swarm. According to the docker documentation, it has to have 
version 1.12 or Newer. Mine is running on 1.6.1. What Am I missing? Any pointers or help would
be very much appreciated.
 
[root@yumoel7]# docker swarm init --advertise-addr x.x.x.x
docker: 'swarm' is not a docker command. See 'docker --help'.

[root@yumoel7]# docker version
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.6.1
OS/Arch (client): linux/amd64
Server version: 1.6.1 <------
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.6.1
OS/Arch (server): linux/amd64

Thanks

**Comment by brunoborges** [comment]
I'd recommend you first try the Docker Swarm "[Getting Started](https://docs.docker.com/engine/swarm/swarm-tutorial/)" tutorial.

**Comment by BhavaniShekhar** [comment]
You must docker 1.12 version. So you could upgrade docker or you can uninstall and install latest version for testing purpose. Learning purpose you can do it on vagrant box having docker [http://wlatricksntips.blogspot.in/2017/05/learning-dockerization-for-weblogic-on.html](url)

**Comment by thegridman** [comment]
Hi,

You obviously need to get the latest Docker version and as it looks like you are using OL7 the instructions are here: https://docs.oracle.com/cd/E52668_01/E87205/html/docker_install_upgrade_upgrade.html <https://docs.oracle.com/cd/E52668_01/E87205/html/docker_install_upgrade_upgrade.html>

JK
