### ISSUE TITLE
Oracle docker database

### ISSUE THREAD

**Issue by laurentrouleau** [oracle/docker-images#620]
Hi, 
I tried tio build docker oracle dabase image with:

```
./buildDockerImage.sh -v 12.2.0.1 -s -i  
and i had the following mistake:
Step 5/16 : COPY $INSTALL_FILE_1 $INSTALL_RSP $SETUP_LINUX_FILE $CHECK_SPACE_FILE $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
COPY failed: stat /var/lib/docker/tmp/docker-builder159105154/linuxx64_12201_database.zip: no such file or directory
```

**Comment by gvenzl** [comment]
Hi @laurentrouleau, most likely you didn't copy the zip installer files into the correct directory. Please rerun **without** the `-i` option and have a look at the ReadMe file for how to build images.

**Comment by gvenzl** [comment]
Marking as invalid for now until proven otherwise.
