### ISSUE TITLE
sqlplus path needs to be fixed in the README.md

### ISSUE THREAD

**Issue by lurodrig** [oracle/docker-images#626]
Hello there,

On the step **Run sqlplus to run the DDL** of  [Run the Database container](https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12212-oradb-wlsstore#run-the-database-container) of the [Example of Image with WLS Domain](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/12212-oradb-wlsstore/README.md)

I do believe that it should be **/u01/app/oracle/product/12.2.0/dbhome_1/bin/sqlplus** instead of  /u01/app/oracle/product/12.1.0/dbhome_1/bin/sqlplus

I am using **container-registry.oracle.com/database/enterprise:latest** as specified in the README.md

Thanks in advance, 

Luis

**Comment by gvenzl** [comment]
Hi @lurodrig, sorry but I'm struggling your understand your request.

1) You are stating the same path for sqlplus that should be replace :)
2) I'm not sure to which ReadMe you are referring. The ReadMe for Oracle Database here on Github doesn't specify any path but just `sqlplus`. The same is true for the ReadMe on container-registry.oracle.com/database/enterprise:latest

Can you please clarify your statement?

Thx,

**Comment by lurodrig** [comment]
Ouch! Very sorry @gvenzl. I did update my comment

Thanks in advance,

Luis

**Comment by mriccell** [comment]
This has been corrected #650.
Thanks
Monica
