### ISSUE TITLE
Perform MD5 checksum of binaries within Dockerfiles

### ISSUE THREAD

**Issue by brunoborges** [oracle/docker-images#629]
What do you all think of performing checksum from within the Dockerfiles? 

One of the common issues we have is people not downloading the tar.gz correctly, and then attempting a manual `docker build`.

Most sets of Dockerfiles already come with the MD5 anyways. So we could potentially have this as a common practice.

**Comment by Djelibeybi** [comment]
Sounds good to me.

**Comment by gvenzl** [comment]
I don't have anything against it although I cannot confirm that experience. For Oracle Database they always use `buildDockerImage.sh`, probably because I force them to as I also print out `docker info`, etc. :) But by all means, fine by me.

**Comment by aureliogrb** [comment]
We use sha256 for the JDK rather than MD5 but I guess you meant "perform a checksum" in general rather than "using MD5!" in particular.

If so.. sounds like a good idea.

**Comment by mriccell** [comment]
I am all for it!
