### ISSUE TITLE
New HEALTHCHECK in Dockerfile is failing

### ISSUE THREAD

**Issue by DrStrangepork** [oracle/docker-images#632]
```
Step 16/17 : HEALTHCHECK --interval=1m --start-period=5m CMD "$ORACLE_BASE/$CHECK_DB_FILE" >/dev/null || exit 1
Unknown flag: start-period
There was an error building the image.
```

DOCKER info:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.51-10.52.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: ip-10-225-77-140
ID: JY6C:Y5EF:I64C:4WXC:D63C:M5QQ:YSPY:377H:55IM:PIBA:3M5S:6RT4
Docker Root Dir: /docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by DrStrangepork** [comment]
Root cause: Server Version: 17.03.2-ce

--start-period was introduced in 17.05.1. Earlier versions of Docker will all fail on this flag.

**Comment by gvenzl** [comment]
Hey @DrStrangepork, that is correct. By now quite a few features are used that aren’t supported by earlier versions of Docker. Any reason why not to upgrade to 17.06-ce?

**Comment by DrStrangepork** [comment]
Corporate decision to standardize on Amazon Linux with no custom installations, so we're stuck with 17.03.2, because that's what's in the amzn repo.

**Comment by gvenzl** [comment]
I see, in that case you can modify the `HEALTHCHECK` instruction and get rid of the `--start-period` option.

**Comment by DrStrangepork** [comment]
```
# Workaround for Docker < 17.05.1
sed -i 's/^HEALTHCHECK/#HEALTHCHECK/' 12.2.0.1/Dockerfile.se2
sed -i 's/^   CMD/#   CMD/' 12.2.0.1/Dockerfile.se2
