### ISSUE TITLE
Running scripts after setup or on startup

### ISSUE THREAD

**Issue by nicolasduminil** [oracle/docker-images#637]
Hi, 

I have the following Dockerfile:

FROM oracle/database:11.2.0.2-xe
ADD customization/customize.sql /opt/oracle/scripts/setup/customize.sql

I expect that the script customize.sql be executed after the setup. But it is not. is there any reason to that ?
Kind regards,
Nicolas

**Comment by gvenzl** [comment]
Oracle XE installs under `/u01/app/oracle` rather than `/opt/oracle`.  See https://github.com/oracle/docker-images/blob/master/OracleDatabase/dockerfiles/11.2.0.2/Dockerfile.xe#L37

Btw, there is no need to add that file into a separate Dockerfile and build a new image. You can just expose the volume to that location and the container will pick it up automatically.

If you add the file yourself you can also just run the file yourself after the database is setup.

**Comment by nicolasduminil** [comment]
Hi, I modified the Dockerfile such that to read as follows:

FROM oracle/database:11.2.0.2-xe
...
COPY customization/customize.sql /u01/app/oracle/scripts/setup/customize.sql
...

The SQL file correctly gets copied to the target directory but still nothing happens. My understanding is that it should be executed automatically by the build process as a post install/setup step. It doesn't seem to be the case.

I know that I could use volumes but I don't want this. And yes, I know that I can run the script myself but I thought that, since this is supposed to be an automatic process, to take advantage of it in order to do create users, etc. rather then running things manually.

Kind regards,
Nicolas

**Comment by gvenzl** [comment]
Hi @nicolasduminil, it is not executed automatically by the build process but by the run process. The build process doesn't setup a database yet so there is nothing to execute that script against during the build.

The script will be executed as soon as the database is setup, which happens during the first run of `docker run ... oracle/database:11.2.0.2-xe`. The line that does that is here: https://github.com/oracle/docker-images/blob/master/OracleDatabase/dockerfiles/11.2.0.2/runOracle.sh#L194

As you can see, this is the `runOracle.sh` file which is called by the `RUN` instruction here: https://github.com/oracle/docker-images/blob/master/OracleDatabase/dockerfiles/11.2.0.2/Dockerfile.xe#L82

Btw, you should just do a `COPY ... $ORACLE_BASE/scripts/setup/` to stay on the safe side and remain transparent to filesystem paths.

**Comment by nicolasduminil** [comment]
Hi Gerald, thanks for the update and for having corrected my mistake. I meant to say that the script is executed during the setup phase, not the build one, sorry.
I tried different things which I would like to show a part here. First, I'm starting the container via docker-compose, as shown below. But this shouldn't make much difference compared to the way you're running it in your example.
  ...
  db:
    image: oracle/database:11.2.0.2-xe
    volumes:
      - ./oraxe/customization:/u01/app/oracle/scripts/startup
    container_name: oraxe
    shm_size: 1g
    ports:
      - 1521:1521
      - 80:8080
    environment:
      ORACLE_PWD: ...

So, after running the file above with docker-compose and then doing the following command:

docker logs --detailed oraxe

I get the following:

ORACLE PASSWORD FOR SYS AND SYSTEM: ...
 
 Oracle Database 11g Express Edition Configuration
 -------------------------------------------------
 This will configure on-boot properties of Oracle Database 11g Express 
 Edition.  The following questions will determine whether the database should 
 be starting upon system boot, the ports it will use, and the passwords that 
 will be used for database accounts.  Press <Enter> to accept the defaults. 
 Ctrl-C will abort.
 
 Specify the HTTP port that will be used for Oracle Application Express [8080]:
 Specify a port that will be used for the database listener [1521]:
 Specify a password to be used for database accounts.  Note that the same
 password will be used for SYS and SYSTEM.  Oracle recommends the use of 
 different passwords for each database account.  This can be done after 
 initial configuration:
 Confirm the password:
 
 Do you want Oracle Database 11g Express Edition to be started on boot (y/n) [y]:
 Starting Oracle Net Listener...Done

So, as you can see, there is nothing concerning the execution of any customized script. However:

nicolas@BEL20:~$ docker exec -ti oraxe /bin/bash
bash-4.2# ls -l /u01/app/oracle/scripts/startup/ 
total 4
-rwxrwxr-x 1 1001 1001 167 Nov  7 13:58 01_customize.sql
bash-4.2# more /u01/app/oracle/scripts/startup/01_customize.sql 
CREATE USER nicolas IDENTIFIED BY ...;
GRANT CONNECT,RESOURCE TO nicolas;
GRANT CREATE SESSION TO nicolas;
ALTER USER nicolas QUOTA UNLIMITED on USERS;
exit;

So, the customization script is in the right directory. No, I'm trying to run the container as you shown, just in case it would make any difference.

nicolas@BEL20:~$ docker run --name oraxe -p 1521:1521 -p 8080:8080 -e ORACLE_PWD=California1 -v /home/nicolas/oraxe/customization:/u01/app/oracle/scripts/startup --shm-size=1g oracle/database:11.2.0.2-xe

And this is what I get:

Oracle Database 11g Express Edition Configuration
-------------------------------------------------
This will configure on-boot properties of Oracle Database 11g Express 
Edition.  The following questions will determine whether the database should 
be starting upon system boot, the ports it will use, and the passwords that 
will be used for database accounts.  Press <Enter> to accept the defaults. 
Ctrl-C will abort.

Specify the HTTP port that will be used for Oracle Application Express [8080]:
Specify a port that will be used for the database listener [1521]:
Specify a password to be used for database accounts.  Note that the same
password will be used for SYS and SYSTEM.  Oracle recommends the use of 
different passwords for each database account.  This can be done after 
initial configuration:
Confirm the password:

Do you want Oracle Database 11g Express Edition to be started on boot (y/n) [y]:
Starting Oracle Net Listener...Done
Configuring database...Done
Starting Oracle Database 11g Express Edition instance...Done
Installation completed successfully.

SQL*Plus: Release 11.2.0.2.0 Production on Wed Nov 8 12:29:23 2017

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> 
PL/SQL procedure successfully completed.

SQL> SQL> 
Database altered.

SQL> 
Database altered.

SQL> 
Database altered.

SQL> 
System altered.

SQL> 
System altered.

SQL> 
System altered.

SQL> 
Database altered.

SQL> 
Database altered.

SQL> SQL> 
System altered.

SQL> Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
#########################
DATABASE IS READY TO USE!
#########################
  Current log# 5 seq# 4 mem# 0: /u01/app/oracle/oradata/XE/redo05.log
      ALTER DATABASE DROP LOGFILE GROUP 1
Deleted Oracle managed file /u01/app/oracle/fast_recovery_area/XE/onlinelog/o1_mf_1_f05y3yv2_.log
Completed:       ALTER DATABASE DROP LOGFILE GROUP 1
      ALTER DATABASE DROP LOGFILE GROUP 2
Deleted Oracle managed file /u01/app/oracle/fast_recovery_area/XE/onlinelog/o1_mf_2_f05y3z1h_.log
Completed:       ALTER DATABASE DROP LOGFILE GROUP 2
Cleared LOG_ARCHIVE_DEST_1 parameter default value
Using LOG_ARCHIVE_DEST_1 parameter default value as /u01/app/oracle/product/11.2.0/xe/dbs/arch
ALTER SYSTEM SET db_recovery_file_dest='' SCOPE=BOTH;

Still no trace of any customization script execution and:

nicolas@BEL20:~$ docker exec -ti oraxe /bin/bash
bash-4.2# ls -l /u01/app/oracle/scripts/startup/01_customize.sql 
-rwxrwxr-x 1 1001 1001 167 Nov  7 13:58 /u01/app/oracle/scripts/startup/01_customize.sql

Sorry to insist on this point, it doesn't matter much as I can get this script executed otherwise, of course, but I would like to understand what happens here. Please advise.

Kind regards,

Nicolas

**Comment by gvenzl** [comment]
Hey @nicolasduminil,

I cannot reproduce this issue, neither with using the startup script functionality:

```
[oracle@localhost customscript]$ pwd
/home/oracle/test/customscript
[oracle@localhost customscript]$ cat 01_customize.sql
CREATE USER nicolas IDENTIFIED BY hello;
GRANT CONNECT,RESOURCE TO nicolas;
GRANT CREATE SESSION TO nicolas;
ALTER USER nicolas QUOTA UNLIMITED on USERS;
exit;
[oracle@localhost customscript]$ docker run --name oraxe -p 1521:1521 -p 8080:8080 -e ORACLE_PWD=California1 -v /home/oracle/test/customscript:/u01/app/oracle/scripts/startup --shm-size=1g oracle/database:11.2.0.2-xe
ORACLE PASSWORD FOR SYS AND SYSTEM: California1

Oracle Database 11g Express Edition Configuration
-------------------------------------------------
This will configure on-boot properties of Oracle Database 11g Express
Edition.  The following questions will determine whether the database should
be starting upon system boot, the ports it will use, and the passwords that
will be used for database accounts.  Press <Enter> to accept the defaults.
Ctrl-C will abort.

Specify the HTTP port that will be used for Oracle Application Express [8080]:
Specify a port that will be used for the database listener [1521]:
Specify a password to be used for database accounts.  Note that the same
password will be used for SYS and SYSTEM.  Oracle recommends the use of
different passwords for each database account.  This can be done after
initial configuration:
Confirm the password:

Do you want Oracle Database 11g Express Edition to be started on boot (y/n) [y]:
Starting Oracle Net Listener...Done
Configuring database...Done
Starting Oracle Database 11g Express Edition instance...Done
Installation completed successfully.

SQL*Plus: Release 11.2.0.2.0 Production on Wed Nov 8 19:01:10 2017

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL>
PL/SQL procedure successfully completed.

SQL> SQL>
Database altered.

SQL>
Database altered.

SQL>
Database altered.

SQL>
System altered.

SQL>
System altered.

SQL>
System altered.

SQL>
Database altered.

SQL>
Database altered.

SQL> SQL>
System altered.

SQL> Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
#########################
DATABASE IS READY TO USE!
#########################

Executing user defined scripts
/u01/app/oracle/runOracle.sh: running /u01/app/oracle/scripts/startup/01_customize.sql

SQL*Plus: Release 11.2.0.2.0 Production on Wed Nov 8 19:01:12 2017

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production


User created.


Grant succeeded.


Grant succeeded.


User altered.

Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production


DONE: Executing user defined scripts

The following output is now a tail of the alert.log:
  Current log# 5 seq# 4 mem# 0: /u01/app/oracle/oradata/XE/redo05.log
      ALTER DATABASE DROP LOGFILE GROUP 1
Deleted Oracle managed file /u01/app/oracle/fast_recovery_area/XE/onlinelog/o1_mf_1_f06o2on9_.log
Completed:       ALTER DATABASE DROP LOGFILE GROUP 1
      ALTER DATABASE DROP LOGFILE GROUP 2
Deleted Oracle managed file /u01/app/oracle/fast_recovery_area/XE/onlinelog/o1_mf_2_f06o2ovx_.log
Completed:       ALTER DATABASE DROP LOGFILE GROUP 2
Cleared LOG_ARCHIVE_DEST_1 parameter default value
Using LOG_ARCHIVE_DEST_1 parameter default value as /u01/app/oracle/product/11.2.0/xe/dbs/arch
ALTER SYSTEM SET db_recovery_file_dest='' SCOPE=BOTH;
```

Nor the setup functionality:

```
[oracle@localhost customscript]$ docker rm oraxe
oraxe
[oracle@localhost customscript]$ docker run --name oraxe -p 1521:1521 -p 8080:8080 -e ORACLE_PWD=California1 -v /home/oracle/test/customscript:/u01/app/oracle/scripts/setup --shm-size=1g oracle/database:11.2.0.2-xe
ORACLE PASSWORD FOR SYS AND SYSTEM: California1

Oracle Database 11g Express Edition Configuration
-------------------------------------------------
This will configure on-boot properties of Oracle Database 11g Express
Edition.  The following questions will determine whether the database should
be starting upon system boot, the ports it will use, and the passwords that
will be used for database accounts.  Press <Enter> to accept the defaults.
Ctrl-C will abort.

Specify the HTTP port that will be used for Oracle Application Express [8080]:
Specify a port that will be used for the database listener [1521]:
Specify a password to be used for database accounts.  Note that the same
password will be used for SYS and SYSTEM.  Oracle recommends the use of
different passwords for each database account.  This can be done after
initial configuration:
Confirm the password:

Do you want Oracle Database 11g Express Edition to be started on boot (y/n) [y]:
Starting Oracle Net Listener...Done
Configuring database...Done
Starting Oracle Database 11g Express Edition instance...Done
Installation completed successfully.

SQL*Plus: Release 11.2.0.2.0 Production on Wed Nov 8 19:11:53 2017

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL>
PL/SQL procedure successfully completed.

SQL> SQL>
Database altered.

SQL>
Database altered.

SQL>
Database altered.

SQL>
System altered.

SQL>
System altered.

SQL>
System altered.

SQL>
Database altered.

SQL>
Database altered.

SQL> SQL>
System altered.

SQL> Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

Executing user defined scripts
/u01/app/oracle/runOracle.sh: running /u01/app/oracle/scripts/setup/01_customize.sql

SQL*Plus: Release 11.2.0.2.0 Production on Wed Nov 8 19:11:55 2017

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production


User created.


Grant succeeded.


Grant succeeded.


User altered.

Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production


DONE: Executing user defined scripts

#########################
DATABASE IS READY TO USE!
#########################
The following output is now a tail of the alert.log:
  Current log# 5 seq# 4 mem# 0: /u01/app/oracle/oradata/XE/redo05.log
      ALTER DATABASE DROP LOGFILE GROUP 1
Deleted Oracle managed file /u01/app/oracle/fast_recovery_area/XE/onlinelog/o1_mf_1_f06oprlp_.log
Completed:       ALTER DATABASE DROP LOGFILE GROUP 1
      ALTER DATABASE DROP LOGFILE GROUP 2
Deleted Oracle managed file /u01/app/oracle/fast_recovery_area/XE/onlinelog/o1_mf_2_f06oprrt_.log
Completed:       ALTER DATABASE DROP LOGFILE GROUP 2
Cleared LOG_ARCHIVE_DEST_1 parameter default value
Using LOG_ARCHIVE_DEST_1 parameter default value as /u01/app/oracle/product/11.2.0/xe/dbs/arch
ALTER SYSTEM SET db_recovery_file_dest='' SCOPE=BOTH;
```

I wonder whether the functionality is included in the `runOracle.sh` script in your image. Can you please do a `cat` on the `runOracle.sh` script and see whether you have the setup and startup functionality showing up in the bottom:

```
[oracle@localhost ~]$ docker exec oraxe cat /u01/app/oracle/runOracle.sh
...
...
...
  # Create database
   createDB;

   # Execute custom provided setup scripts
   runUserScripts $ORACLE_BASE/scripts/setup
fi;

echo "#########################"
echo "DATABASE IS READY TO USE!"
echo "#########################"

# Execute custom provided startup scripts
runUserScripts $ORACLE_BASE/scripts/startup

echo "The following output is now a tail of the alert.log:"
tail -f $ORACLE_BASE/diag/rdbms/*/*/trace/alert*.log &
childPID=$!
wait $childPID
```

**Comment by nicolasduminil** [comment]
Hi Gerald,

Thanks again for your feedback. Here is my runOracle.sh script as included in the binaries downloaded from the oracle web site:

bash-4.2# more /u01/app/oracle/runOracle.sh 
#!/bin/bash

########### Move DB files ############
.........................
echo "#########################"
echo "DATABASE IS READY TO USE!"
echo "#########################"

tail -f $ORACLE_BASE/diag/rdbms/*/*/trace/alert*.log &
childPID=$!
wait $childPID

So yes, you we're right, this script doesn't run the customized user's scripts. I don't know wether one is supposed to customize the runOracle.sh by adding the required lines or wether it comes already with these in it. In any case, customizing the script before running it is not compliant with a docker based approach.

So my question is: did you customize runOracle.sh in order to add the lines running the user's scripts ? 

Kind regards,

Nicolas

**Comment by nicolasduminil** [comment]
Hi Gerald,

Just a short note to let you know that, after having downloaded a fresh copy of the Oracle XE 11.2.0 from the official web-site, the runOracle.sh scripts reads exactly as yours, it has everything it needs and things are okay now as the custom scripts are ran as expected. I don't know how I came in such a situation to have a non standard distribution. Many thanks for your help and support.

Kind regards,
Nicolas

**Comment by gvenzl** [comment]
Hey @nicolasduminil, the builds files do change quite a bit up here on Github. The scripts support was added on the 12th of July via PR #471. Perhaps your image was still before then?

You are very welcome, glad that it is sorted now!

Let us know if you build anything interesting. Links to blogs or slides are always appreciated! :)

**Comment by iliakp** [comment]
Hi,

Is there any way to make this happen on store/oracle/database-enterprise:12.2.0.1 image or store/oracle/database-enterprise:12.2.0.1-slim?

**Comment by Daiki-Kawanuma** [comment]
Hi, 

I have same question as @iliakp .

**Comment by Djelibeybi** [comment]
No, there isn't. You would need to build your own image using the Dockerfiles in this repo.
