### ISSUE TITLE
Question about internal & external IPs.

### ISSUE THREAD

**Issue by Batousay** [oracle/docker-images#64]
I'm quite new to docker and weblogic, so I don't really know where to comment the problem I'm having, so I'll do it here.

Okay, let's start by the environment.
the project I'm wotking at requires weblogic 12.1.3 as well as coherence 12.1.3
So I create an AdminServer and some machines for "data" and "proxy".

If I test and try to connect with the proxy docker machine from inside the "host" computer everything works flawlessly.

But when I try to connect from an outside machine (that obiously doesn't have acces to the 172.x.x.x internal docker IPS) the connection fails. 
In the first place it seems to work but In a second attempt the external machine tries to connect to an internal IP, and then fails.

I've created the proxy node with this configuration

docker run -d -v /webdav:/mnt/webdav_host -v /deploy:/mnt/deploy -v /logs:/mnt/logs_host -t -e MS_HOST=serverExternalIP -e NM_NAME=Machine-proxy1 -e MS_NAME=proxyServer-1 --lin
k wlsadmin:wlsadmin -p 7010:7001 -p 9099:9099 --name=proxy_1 weblogic/sample:12.1.3 createServer.sh

And the trace I get from the application running at the outside machine is something like this:

Connecting to ServerExternalIP:9099 --- OK
Connecting to ServerExternalIP:9099.3 --- OK
Connecting to 172.x.x.x:9099 -- Fail

There is some way to configure docker or Weblogic to show the server public IP instead of the docker machine one?

Thanks in advance.

**Comment by brunoborges** [comment]
It is a networking issue with the way Docker works. You should review the Docker Networking section in the documentation to get a better understanding.

https://docs.docker.com/engine/userguide/networking/
