### ISSUE TITLE
Database service definition for sqlplus createSchema.sql script on 12212-oradb-wlsstore sample

### ISSUE THREAD

**Issue by lurodrig** [oracle/docker-images#641]
Hello there,

I do think that the connection string of the section [Run the Database container](https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12212-oradb-wlsstore#run-the-database-container) in the [12212-oradb-wlsstore README.md](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/12212-oradb-wlsstore/README.md) is not 100% percent correct. If I try... 
`$ docker exec -ti MYInfraDb /u01/app/oracle/product/12.2.0/dbhome_1/bin/sqlplus system@infrapdb/Welcome1`
... I get: 
`ORA-12154: TNS:could not resolve the connect identifier specified`

In the other hand: `docker exec -ti MYInfraDb /u01/app/oracle/product/12.2.0/dbhome_1/bin/sqlplus system/Welcome1@//localhost:1521/infrapdb.us.oracle.com` works

I can see that there is not such service defined:

```
$ docker exec -ti MYInfraDb /u01/app/oracle/product/12.2.0/dbhome_1/bin/lsnrctl status

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 08-NOV-2017 10:05:57

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Connecting to (ADDRESS=(PROTOCOL=tcp)(HOST=)(PORT=1521))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                08-NOV-2017 08:19:31
Uptime                    0 days 1 hr. 46 min. 30 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /u01/app/oracle/product/12.2.0/dbhome_1/admin/infradb/listener.ora
Listener Log File         /u01/app/oracle/diag/tnslsnr/58d596eb6a88/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=58d596eb6a88)(PORT=5500))(Security=(my_wallet_directory=/u01/app/oracle/product/12.2.0/dbhome_1/admin/infradb/xdb_wallet))(Presentation=HTTP)(Session=RAW))
Services Summary...
Service "5d7554ef1fe7019ee053020012ac7eb4.us.oracle.com" has 1 instance(s).
  Instance "infradb", status READY, has 1 handler(s) for this service...
Service "infradb.us.oracle.com" has 1 instance(s).
  Instance "infradb", status READY, has 1 handler(s) for this service...
Service "infradbXDB.us.oracle.com" has 1 instance(s).
  Instance "infradb", status READY, has 1 handler(s) for this service...
Service "infrapdb.us.oracle.com" has 1 instance(s).
  Instance "infradb", status READY, has 1 handler(s) for this service...
The command completed successfully
```

In the [weblogic datasource definition](https://github.com/oracle/docker-images/blob/f105ab3fb9c87a248e2967b09ce87e0426300313/OracleWebLogic/samples/12212-oradb-wlsstore/container-scripts/oradatasource.properties#L13) I can see the **infradbp.us.oracle.com** one, so perhaps would be more coherent to used the same in both. 

Thanks in advance,

Luis

**Comment by mriccell** [comment]
@lurodrig I will take a look at WLS connecting to DB container and update README and properties file.

**Comment by lurodrig** [comment]
Thanks @mriccell !

**Comment by mriccell** [comment]
@lurodrig created a PR #650 to align with database 12.2.0.1 image in container registry.  Please try and let me know if you still running into problems.
Thanks
