### ISSUE TITLE
Unable to start the server MS1 : java.io.IOException: Unexpected end of stream

### ISSUE THREAD

**Issue by wggit** [oracle/docker-images#642]
I am trying to create managed server using sample build and getting error -

docker run -d  -p 5556:5556  --name MS1 --link wlsadmin:wlsadmin -e NM_NAME=servername -e DEBUG_FLAG=true -e ADMIN_PASSWORD=somepasswd -e MS_NAME=MS1 -e MS_PORT=7003 12213-domain:latest createServer.sh

####<Nov 8, 2017 3:14:32,412 PM GMT> <Error> <NodeManager> <wlsadmin> <AdminServer> <[ACTIVE] ExecuteThread: '6' for queue: 'weblogic.kernel.Default (self-tuning)'> <weblogic> <> <035cc18a-a844-4f99-983e-008567a3da89-00000011> <1510154072412> <[severity-value: 8] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-300048> <Unable to start the server MS1 : java.io.IOException: Unexpected end of stream>

I don't see much more information in any log about details of this error.
If any one has successfully created managed server with node manager running can help?

Thank you.

**Comment by mriccell** [comment]
@wggit  Are you creating the domain image using 12213-domain?  I have ran managed server using this image many times.  The 12212 has a problem which I need to fix.

**Comment by wggit** [comment]
Thank you

**Comment by mriccell** [comment]
fixed in PR #662
