### ISSUE TITLE
Request: Add Tools package to OracleInstantClient Docker image

### ISSUE THREAD

**Issue by seantreg** [oracle/docker-images#643]
Is there a plan to add the Tools package to the OracleInstantClient Docker image now that it is available in Instant Client 12.2?
Specifically, I would like to use SQL*Loader.

I should probably add that I am using the image from the Docker store.

**Comment by Djelibeybi** [comment]
We're not planning to add anything to that base image, but you can always add it yourself just by extending the image itself.

**Comment by seantreg** [comment]
Yes, I have done that.
I just thought it would be nice to be able to grab it from the Docker store with SQL*Loader included

**Comment by gvenzl** [comment]
I was thinking the same, thanks for clarification. :)

**Comment by danyfauzi** [comment]
@seantreg hi, may you help to share the script to add sql loader tool packages on oracle client instant docker?

**Comment by cjbj** [comment]
@danyfauzi I'd just add `oracle-instantclient18.3-tools` to the `yum` command in
https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/18.3.0/Dockerfile#L21

**Comment by danyfauzi** [comment]
> @danyfauzi I'd just add `oracle-instantclient18.3-tools` to the `yum` command in
> https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/18.3.0/Dockerfile#L21

Thanks @cjbj , im using 12.2 , so only need to add the rpm file for tools to be installed

**Comment by cjbj** [comment]
@danyfauzi You should be able to use 18.3.  The 18.3 release was the start of the new numbering system and it is effectively the equivalent of the 12.2.0.2 code line.  18.3 also connects to the same versions of database that 12.2 does, e.g. DB 11.2 or later.

**Comment by seantreg** [comment]
> @seantreg hi, may you help to share the script to add sql loader tool packages on oracle client instant docker?

@danyfauzi, I downloaded the 4 Oracle Instant client .rpm files and applied them to the Oracle server JRE image. 
Here are the relevant parts of our Dockerfile:
```
...
# Path to Oracle Instant Client packages
ARG ORACLE_INSTANT_CLIENT_PACKAGE_URLS=http://[hostname]/oracle-instantclient12.2-{basic,devel,sqlplus,tools}-12.2.0.1.0-1.x86_64.rpm
...

# Build a version of Oracle Instant Client that contains SQL*Loader.
# The official Oracle image, store/oracle/database-instantclient:12.2.0.1, does not include it, although it is planned.
RUN set -x \
    && pushd /tmp \
    && curl ${ORACLE_INSTANT_CLIENT_PACKAGE_URLS} \
        --output "oracle-instantclient12.2-#1-12.2.0.1.0-1.x86_64.rpm" \
        --output "oracle-instantclient12.2-#2-12.2.0.1.0-1.x86_64.rpm" \
        --output "oracle-instantclient12.2-#3-12.2.0.1.0-1.x86_64.rpm" \
        --output "oracle-instantclient12.2-#4-12.2.0.1.0-1.x86_64.rpm" \
    && popd \
    && yum -y install /tmp/oracle-instantclient*.rpm \
    && rm -rf /var/cache/yum \
    && rm -f /tmp/oracle-instantclient*.rpm \
    && echo /usr/lib/oracle/12.2/client64/lib > /etc/ld.so.conf.d/oracle-instantclient12.2.conf \
    && ldconfig
...
```
Hope that helps

**Comment by cjbj** [comment]
@seantreg thanks.  But see above - there shouldn't be a need to use 12.2.0.1 anymore!

**Comment by seantreg** [comment]
Thank you, @cjbj 
It was done some time ago, and I will certainly look to update when I revisit that Dockerfile.

**Comment by Djelibeybi** [comment]
FYI, the 18.3 (and higher) Instant Client RPMs are now available via yum.oracle.com so you don't have to install them manually anymore either. I know @cjbj is planning on updating the Instant Client Dockerfiles accordingly soon.
