### ISSUE TITLE
OracleRestDataServices/dockerfiles/buildDockerImage.sh issue with awk on MacOS

### ISSUE THREAD

**Issue by martindsouza** [oracle/docker-images#644]
When running `OracleRestDataServices/dockerfiles/buildDockerImage.sh` get the following error:

```bash
awk: syntax error at source line 1
 context is
	match ($0, >>>  /(ords\.)(.{1,2}\..{1,2}\..{1,2})\.(.+.zip)/, <<<
awk: bailing out at source line 1
```

After doing some digging it looks like the 3 parameter `awk` is only available for `gawk`. See [this](https://stackoverflow.com/questions/5466411/print-regexp-matches-in-awk) SO article, specifically the comments on the suggested fix:

> oh, it's gawk... from stackoverflow.com/questions/5536018/… "the awk match() function with three arguments only exists in gawk"

**Comment by gvenzl** [comment]
I'm closing this as the PR has been merged.
