### ISSUE TITLE
OracleRestDataServices/dockerfiles/buildDockerImage.sh oracle/serverjre:8 Issue

### ISSUE THREAD

**Issue by martindsouza** [oracle/docker-images#646]
_Note: my copy of `buildDockerImage.sh` was updated to get around a `gawk` issue in macOS. The version I am running is in PR #645 (fixing issues #644)_

When I run

``` bash
cd docker-images/OracleRestDataServices/dockerfiles
./buildDockerImage.sh -i
```

I get:
```bash
...
==========================
Building image 'oracle/restdataservices:3.0.12' ...
Sending build context to Docker daemon  47.62MB
Step 1/10 : FROM oracle/serverjre:8
pull access denied for oracle/serverjre, repository does not exist or may require 'docker login'
There was an error building the image.
```

If I then run the following to confirm no container registry issues
```bash
docker login container-registry.oracle.com

# And run
docker pull container-registry.oracle.com/java/serverjre
```

If I run `./buildDockerImage.sh -i` again I get the same error as initial shown.

**Comment by gvenzl** [comment]
This is a good discussion to have, hence assigning to @Djelibeybi. As we already have the jdk on the hub itself, why can't we just use that one directly: https://hub.docker.com/r/oracle/openjdk/
Why do we have to force users to build their own Java image first when they use the images on Github? It would make more sense to get that layer out of the way. Just like we do with the oraclelinux:7-slim base image we can do the same with the openjdk image from the hub and make it easier for folks to build their images.

**Comment by gvenzl** [comment]
Also, how do we overcome the different naming conventions? For those images on the container-registry that are built using those build files on Github, why not just keep the same label?

**Comment by martindsouza** [comment]
@gvenzl if we can use the hub image even better. But something is still wrong as I manually pulled the `server-jre` image.

**Comment by Djelibeybi** [comment]
The idea was that all the GitHub images work together. However, I think there is possibly some scope for adjusting the instructions here on GitHub to match the naming we have on Oracle Container Registry.

**Comment by gvenzl** [comment]
Hey @Djelibeybi, i was actually referring to the image that we provide on the Docker hub itself and not on the container store: https://hub.docker.com/r/oracle/openjdk/ Given that we have a fully open source image of Oracle Linux and OpenJDK I see no reason to have to push users through an additional click-through just to download it from the container-registry when all we need is the JDK on OL.

**Comment by brunoborges** [comment]
Only issue is that ServerJRE is different than OpenJDK. They are not exactly the same thing. Commercial support for ORDS is provided when running on Oracle Java (e.g. ServerJRE)

**Comment by gvenzl** [comment]
I suppose the answer to this then is:

The build files on Github depend on each other, i.e. one has to build the Java image first before building the ORDS image.

The images on the container-store depend on each other, i.e. the upcoming ORDS image will pull the serverjre from the container-registry as prerequisite.

**Comment by Djelibeybi** [comment]
The specifics are slightly different in that the GItHub ORDS image would share layers with the Java image, while the Container Registry ORDS image shares similar layers with the Java image from OCR.

But that's close enough for me to agree with you.
