### ISSUE TITLE
Poor performance on Linux

### ISSUE THREAD

**Issue by ph777** [oracle/docker-images#647]
We have a SW product that runs on top of MS SQL, MySQL or Oracle database. We run tests against each of these databases. As we want to better automate the process we would like to use docker. We use official docker images without any further tweaking. However, there is notable performance difference between running tests against dockerized db, but only for Oracle. The tests run approximately 2x slower, which is something we would not expect. The complete test suite without docker runs in about 3h, while with docker it runs for 6h.

Any advice what to check/change?

**Comment by gvenzl** [comment]
Hm, this looks like another issue as in #601. In there we see `PGA memory operation` as the main operation waiting for. Can you advise whether you see the same wait event at your end?

Can you also please share `docker info` for this environment.

**Comment by ph777** [comment]
How do you identify the main operation oracle is waiting for? I've found the v$system_event view. I guess idle class can be ignored. From the rest the top events in terms of TIME_WAITED are
- log file parallel write
- log file sync

Both of them take 10x more time then the following 'db file sequential read'.

My docker info:
```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 72
Server Version: 17.04.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.5.3+20160729
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: runc
Init Binary: 
containerd version:  (expected: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73)
runc version: N/A (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
Kernel Version: 4.4.92-31-default
Operating System: openSUSE Leap 42.3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.29GiB
Name: virteo
ID: 55ZG:V5NT:6S2T:GTKJ:GSIZ:7OAT:LGQO:UHD3:SFPF:SS2G:33RG:W6R2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support
```
Thanks for help.

**Comment by ph777** [comment]
Further info 
- disk_asynch_io is FALSE
- shm_size 2G
- local directory mounted as volume to /opt/oracle/oradata

**Comment by gvenzl** [comment]
Hi @ph777, Oracle database has so many sophisticated performance monitoring and tuning technologies that there is an entire book on it: [Database Performance Tuning Guide](https://docs.oracle.com/database/122/TGDBA/toc.htm).
A good starter is to create an AWR report between those test runs within Docker and outside of Docker and then compare the two. Then you know exactly what's going on.

However, as you have already seen that the top wait events are `log file parallel write` and `log file sync` it means that the storage layer where you store the redo logs (`$ORACLE_HOME/oradata/$ORACLE_SID/redoNN.log`) is slow. We have seen that before when the data files where put onto `btrfs` which is not a great file system for random fast writes. Which file system are you using for your redo logs?

**Comment by ph777** [comment]
Hi @gvenzl, thanks for the hint with `BTRFS`. Since Docker itself likes the `BTRFS` file system, I thought it would be the best to have my volume on it too, which was obviously a bad idea. 
I have moved Oracle's file system to `XFS`. Now, the tests run 2x faster compared to volume on `BTRFS`. To make the miracle happen I also had to switch `disk_asynch_io` to `TRUE`.
However, both MSSQL for Linux and MySQL still complete the tests much faster. Currently the ratio is 2:3 (before the move it was 1:3 or even worse). I'd like to point out that the other two databases come with the default settings.
Any tip on more optimization? Thanks for your kind support.

**Comment by gvenzl** [comment]
Hi @ph777, that's great to hear. Indeed, `btrfs` as much of a great file system as it is, it isn't great for quick random writes.

Well, again, there could be many reasons why it is slower than expected. Can you tell me what the top wait events are now?

**Comment by brunoborges** [comment]
@Djelibeybi may have some insights on `btrfs`

**Comment by Djelibeybi** [comment]
This is a known issue due to btrfs' use of copy-on-write. You could try disabling it for the directory created by the VOLUME directive that is used to store the database data:

https://wiki.archlinux.org/index.php/Btrfs#Disabling_CoW

**Comment by ph777** [comment]
@Djelibeybi thanks for `btrfs` info. However, I have no problem to run oracle volume on `xfs`. Or do you suggest to switch back to `btrfs` with COW disabled?

**Comment by ph777** [comment]
@gvenzl The top wait times are now

EVENT;TIME_WAITED;AVERAGE_WAIT
log file parallel write;12871;1.66
log file sync;9585;1.5
ADR block file write;2945;3.35
LGWR any worker group;1502;1.51

**Comment by ph777** [comment]
@gvenzl The top wait times are now

EVENT|TIME_WAITED|AVERAGE_WAIT
-----|------|-----
log file parallel write|48352|1.47
log file sync|44864|1.43
acknowledge over PGA limit|22368|1.14
ADR block file write|2945|3.35

**Comment by gvenzl** [comment]
Thanks @ph777, how do those numbers compare as to before? Looks like the `db file sequential read` is already gone, which is good. But has the `log file parallel write` dropped as well?

**Comment by gvenzl** [comment]
Closing due to lack of response.
