### ISSUE TITLE
Choose between CDB and non CDB - command line switch

### ISSUE THREAD

**Issue by wwwfreedbanl** [oracle/docker-images#652]
Hi,
Thanks for a great project. 
Would be nice if it was possible to choose between a CDB and non CDB, if possible at container creation time. 
Now it's possible by commenting the lines below in dbca.rsp.tmpl and then build a new image, but it would be great if this was possible by adding a command line switch on first container startup so you can use 1 image as a base for both CDB's and non CDB's. Any ideas on this ?

In 12.2.0.1 :
#createAsContainerDatabase
#numberOfPDBs=1
#pdbName=###ORACLE_PDB###
#pdbAdminPassword=###ORACLE_PWD###
or in 12.1.0.2
#CREATEASCONTAINERDATABASE = "true"
#NUMBEROFPDBS = 1
#PDBNAME = "###ORACLE_PDB###"
#PDBADMINPASSWORD = "###ORACLE_PWD###"

kind regards
  Bas

**Comment by brunoborges** [comment]
Hi @wwwfreedbanl, is there anyway you can customize (e.g. doing your own inherited) Docker image to accomplish this use case, or is this something that it cannot be accomplished except by providing support directly at the main image?

**Comment by wwwfreedbanl** [comment]
Hi @brunoborges 
The only way I can think of is customize the dbca.rsp.tmpl for either a CDB or a non CDB and then build an entirely new image using BuildDockerImage.sh. The newly build image then supports the template provided at build time. So there is a "work around" but it's not flexible. 
Since the database is created at container startup it would be much nicer if you could choose at that time which type of database you would like to provision. So you don't need to maintain multiple images per oracle release but just 1 (saves a lot of time and errors patching all the extra images ). Ideally you could provide a set of template files which you can choose from at container (and database) creation time so companies can provision their own base database structure in addition to the default ones.
So I can solve this issue without changing the code but it's not the best solution and I think it's a valuable addition to the base project.
I'm trying to code a better way now but fairly new to docker so will take me some effort :)

**Comment by wwwfreedbanl** [comment]
Hi @brunoborges @gvenzl 
The main reason for this request was licensing (CDB versus non CDB) but after doing some searching I found that a single tenant database does not need an extra license (I thought all CDB setups needed an addiotional license but this is  not true if you only use 1 PDB) and that non-CDB's will probably be deprecated after version 12. 
I wasn't aware of that, my bad. If you need a different starter database you can always tweak the dbca.rsp.tmpl so my request is less relevant now.
So from my point of view this issue can be closed-removed-/dev/null. 
Thanks for your thoughts on this.
Regards
  Bas

**Comment by gvenzl** [comment]
Thanks @wwwfreedbanl, that is exactly right. A single tenant configuration (one PDB of each kind) is free of charge and also available in SE2.
One correction in your statement above:

> and that non-CDB's will probably be deprecated after version 12.

The non-CDB architecture is already deprecated ever since 12.1 which is why we don't provide this option out of the box.
After version 12 it may be desupported, meaning that it is not possible at all anymore to have a non-CDB database.

**Comment by koverg70** [comment]
> Hi,
> Thanks for a great project.
> Would be nice if it was possible to choose between a CDB and non CDB, if possible at container creation time.
> Now it's possible by commenting the lines below in dbca.rsp.tmpl and then build a new image, but it would be great if this was possible by adding a command line switch on first container startup so you can use 1 image as a base for both CDB's and non CDB's. Any ideas on this ?
> 
> In 12.2.0.1 :
> #createAsContainerDatabase
> #numberOfPDBs=1
> #pdbName=###ORACLE_PDB###
> #pdbAdminPassword=###ORACLE_PWD###
> or in 12.1.0.2
> #CREATEASCONTAINERDATABASE = "true"
> #NUMBEROFPDBS = 1
> #PDBNAME = "###ORACLE_PDB###"
> #PDBADMINPASSWORD = "###ORACLE_PWD###"
> 
> kind regards
> Bas

For those who still want non-CDB images: besides commenting out the mentioned lines you also have to modify the checkDBStatus.sh file to look into the v$containers table instead of the v$pdbs.
...
#ORACLE_PDB="`ls -dl $ORACLE_BASE/oradata/$ORACLE_SID/*/ | grep -v pdbseed | awk '{print $9}' | cut -d/ -f6`"
...
   SELECT open_mode FROM v\\$containers WHERE UPPER(name) = UPPER('$ORACLE_SID');
...
