### ISSUE TITLE
Docker Images for Oracle Unified Directory 

### ISSUE THREAD

**Issue by oehrlis** [oracle/docker-images#656]
Hi

It would be great, if there will be also a docker image for Oracle Unified Directory. I've start to work on this topic and created a few custom OUD docker images (see [docker-oud](https://github.com/oehrlis/docker-oud) or [docker-oudsm](https://github.com/oehrlis/docker-oudsm). These images could be adjusted according the [contribution](https://github.com/oracle/docker-images/blob/master/CONTRIBUTING.md) guidelines. I could contribute to that.

Regards
Stefan

**Comment by brunoborges** [comment]
Hi @oehrlis,

Thanks for the proposal. We will check with the product managers and see if they are able to support this contribution. 

bb.

**Comment by oehrlis** [comment]
Hi

Is there any feedback from product management? I've updated the build scripts for miscellaneous Oracle Directory servers see [oehrlis/docker](https://github.com/oehrlis/docker) on GitHub

The GitHub repository contains the Dockerfiles and build scripts to setup Docker images for the following Oracle Products:
- Oracle Unified Directory 12.2.1.3.0 to setup and run Oracle Unified Directory [OUD](https://github.com/oehrlis/docker/tree/master/oud).
* Collocated Oracle Unified Directory 12.2.1.3.0 and Oracle Fusion Middleware Infrastructure 12.2.1.3.0 to setup and run an Oracle Unified Directory Server Manager [OUDSM](https://github.com/oehrlis/docker/tree/master/oudsm).
* Oracle Directory Server Enterprise Edition 11.1.1.7.2 to setup and run Oracle Directory Server Enterprise Edition [ODSEE](https://github.com/oehrlis/docker/tree/master/odsee).

Regards
Stefan

**Comment by Djelibeybi** [comment]
Bruno was going to check on this, but I guess this must've been missed somehow. Sorry about that! Let me reassign it to myself and get in contact with the product team (possibly for a second time).

**Comment by Illydth** [comment]
Just wanted to drop a "me too" into this. We're looking at deploying OUD in docker container as well.  Have already done some work with @oehrlis archive, but it would be nice to have an official image available...or at least an official build process for it.

**Comment by Djelibeybi** [comment]
No news, I'm afraid. I know the Identity Management folk have it on their radar but I don't have an ETA unfortunately. 

Have you signed a CLA? If so, why not submit your build as a PR to this repo? Just be sure to mark it as unofficial the in the documentation, please. :)

**Comment by Djelibeybi** [comment]
Unfortunately, we can't accept any code without a signed CLA and you don't seem to appear on the list: http://www.oracle.com/technetwork/community/oca-486395.html

**Comment by oehrlis** [comment]
Hi

I'm finally on the OCA list. Unfortunately, my contributor name is still wrong,  _oehrli_ instead of _oehrlis_. But I'm working on this, as well as on a pull request for OUD.

Stefan

**Comment by oehrlis** [comment]
Initial release of Oracle Unified Directory has been added. I'll open new issues for enhancements.
