### ISSUE TITLE
Name of the JRE download should be "server-jre-8u71-linux-x64.gz"

### ISSUE THREAD

**Issue by mustafau** [oracle/docker-images#66]
The files downloaded from Oracle's Server JRE page ends with ".gz" not ".tar.gz".

**Comment by brunoborges** [comment]
@mustafau I'm sorry, but seems that you are having issues. The package should be downloaded from here: 

- http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html

And the packages end with .tar.gz

**Comment by mustafau** [comment]
That is the URL I used. Although it reads .tar.gz in that page actual downloaded file is a .gz

**Comment by brunoborges** [comment]
The file downloaded comes from this URL:

- http://download.oracle.com/otn-pub/java/jdk/8u71-b15/server-jre-8u71-linux-x64.tar.gz

        $ file server-jre-8u71-linux-x64.tar.gz
        server-jre-8u71-linux-x64.tar.gz: gzip compressed data, last modified: Tue Dec 22 18:33:48 2015, from Unix

Least to say, if the filename is not entirely related to the actual content, on Unix environments that does not matter. And the Docker images are built without any issue. So again, the name of the file must be what comes from the download site. That's what is important, so users don't have to manually rename the file.

**Comment by mustafau** [comment]
Seems like there are other people facing same issue. 

http://superuser.com/a/607248

I just renamed the file to get it working.

**Comment by brunoborges** [comment]
What OS and browser are you using? Just curious...

**Comment by mustafau** [comment]
Latest Chrome, tried on both Mac and Windows. Could be a regional thing I think.
