### ISSUE TITLE
Docker image for Oracle Database 11g EE

### ISSUE THREAD

**Issue by antuspenskiy** [oracle/docker-images#660]
Hello!

Are there any restrictions for creating an image for version 11.2.0.4 EE?  I see that there are images for 11g XE, but not for EE. Maybe i can make PR for 11.2.0.4 EE based on 12c EE files.

**Comment by brunoborges** [comment]
As far as I know, there are no plans to provide images for 11g. @gvenzl can provide more details.

**Comment by gvenzl** [comment]
Hi @antuspenskiy, 11g R2 is not supported to run inside Docker, hence we won't provide any images or build files for it.
