### ISSUE TITLE
Ability to turn off no-cache

### ISSUE THREAD

**Issue by craigbarrau** [oracle/docker-images#67]
Taking Bruno's suggestion to raise tickets for enhancement requests :)

Would it be possible to have a flag that turns on the Docker build cache during the execution of buildDockerImages.sh ? 

At the moment it is hardcoded as no-cache=true. This means that subsequent builds will be slower than they need to be (e.g. 10 minutes instead of 10 seconds). The cache feature in docker is usually turned on by default but the buildDockerImages.sh is overriding it for some reason. Not sure why you'd want to do this...

Alternatively to allowing the cache to be turned on, if you could simply have the cache turned on by default (i.e. remove the no-cache=true line) that would be great.

Thanks in advance!

**Comment by craigbarrau** [comment]
Also should mention.... without having cache enabled, every CI server build will be new image (i.e. several Gigabytes in size) even if it doesn't need to be. This has the potential to fill up space quickly and even take down the CI server in a worst case scenario.

**Comment by Djelibeybi** [comment]
:+1 from me. I didn't realise this was even set.

**Comment by brunoborges** [comment]
The build shell script is a utility. Expert users are welcome to use native "docker build" call

**Comment by Djelibeybi** [comment]
Can you explain your reasoning behind using this option in the script? I don't understand why it's the default.

**Comment by brunoborges** [comment]
Initially because there were bugs with the Docker layer cache system. 

But then to ensure the image will be always clean. Docker caches layers based on what the command looks like, not what it does internally. For example:

        RUN wlst.sh createDomain.py

The command above may generate files to represent a unique domain (or in the case of base image, a WLS installation). If cached, doesn't matter if the output is different every time the command is called, Docker will use the cached layer.

So yeah, I advocate for not using cache by default, unless you really know what you are doing.

**Comment by craigbarrau** [comment]
Hi Bruno,

Will an Oracle customer still be supported / certified for WebLogic on Docker if they don't use the utility script which is documented in the Oracle whitepaper?

Thanks,
Craig

**Comment by brunoborges** [comment]
Absolutely

**Comment by craigbarrau** [comment]
Phew *wipes sweat from face*

**Comment by craigbarrau** [comment]
Based on the previous comment, I’m happy to go down the no utility script path although I would have liked to have stuck to that as it is what is in the Oracle Whitepaper and it could be perceived as deviating from the best wishes of Oracle even if that is not reality.

Regarding your comments on caching, I just wanted to clarify some things...

Firstly, this ticket was raised in the context of this file -> https://github.com/oracle/docker-images/blob/master/OracleWebLogic/dockerfiles/buildDockerImage.sh

Here we are dealing with an installation of binaries. The cache is always enabled by default in Docker for good reason. I think if it wasn't stable or was a feature used by "experts" it wouldn't be the default behaviour.

The problem with having `no-cache=true` set is that the execution will not be idempotent. For example, if you run the buildDockerImage.sh job for infrastructure once it will result in 3.752 GB of space used. If you run it again, it will result in another 3.752 GB of space used even though nothing has changed and there is no need to rebuild a reusable Docker image that already exists....

If we take a simple example, when you run the following it will do the build for the first time which could take several minutes
`docker build .`
But if you run the above again it sees that all the inputs are the same and skips creating reusable Docker images that exist. This helps the developer or operations person by not using up disk space unnecessarily with redundant images when it can safely and reliably reuse the ones that already exist.

Secondly, your example of createDomain.py relates to the sample Dockerfiles that create the domain which is not what I raised the ticket about. However, since we are on the topic I just wanted to mention some things in relation to your point.

In your samples, the createDomain.py gets passed in via the Docker build context when you execute this:
`COPY container-scripts/* /u01/oracle/`

What that means is that if you ever change the createDomain.py or any other files it will invalidate the build cache for all subsequent steps after they are copied into the container. Docker **always** does this even when you **don’t** have `no-cache=true` set. Docker is smart enough to know the input has changed and make sure that it turns caching off from that point. This is not an advanced feature this is just the way Docker works to save developers or operations people time and effort. If you have `no-cache=true` set as a blanket rule the developer and/or operations person may end up needing to run clean up scripts[1] often to get rid of all your redundant images that are serving no value.

[1] Like this one -> https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/clean-up-docker.sh

**Comment by brunoborges** [comment]
Hi @craigbarrau,

About your concern on user space, the utility script combines `--force-rm=true` with `--no-cache=true`, so no layer will be stored after the build.

About your concern with `RUN wlst.sh createDomain.py` example, indeed that happens only on samples. But it is important to clarify that even though `createDomain.py` does not change at all, the output of that call generates random hashes internally, as part of the domain metadata.

To be safe, cache **should** be disabled for the base image (WLS + JDK installation), and **must** be disabled for building domains.

**Comment by craigbarrau** [comment]
Thanks Bruno,

If I understand correctly, the cache "must be disabled for building domains" if you are building derivative images from the same WebLogic domain and want to ensure each domain has different password entropy. That's very important, I agree.

As for the WLS + JDK installation, to be honest I'm not really convinced but I'm happy to agree to disagree on this one because the drawbacks of the cache disablement can be easily and safely worked around. Thanks again for your prompt responses Bruno! :)

**Comment by brunoborges** [comment]
No worries. :-)
