### ISSUE TITLE
Unable to build the docker image for WLS 12.2.1.3

### ISSUE THREAD

**Issue by Mpurushotham** [oracle/docker-images#671]
Error:
Step 7/12:
Removing intermediate container bacfcb59e107
ApplyLayer exit status 1 stdout:  stderr: write /tools/u01/fmw_12.2.1.3.0_wls_Disk1_1of1.zip: no space left on device
There was an error building the image.

even manually copied to /tools/u01 location binaries. 

Kindly help in building docker images.

Regards,
Purushotham

**Comment by brunoborges** [comment]
Check your local filesystem used by Docker. This issue is unrelated to our images.

**Comment by mriccell** [comment]
@Mpurushotham were you able to verify your local file system?

**Comment by brunoborges** [comment]
Closing for now. If/when @Mpurushotham responds, we can reopen.
