### ISSUE TITLE
oracle 12 Non PDB DB

### ISSUE THREAD

**Issue by BrianFlowerday** [oracle/docker-images#674]
Hi I have this working

But s there a way to create a normal non PDB database?
Our DBA's are insisting  we go non PDB  as there is a license cost implciation

**Comment by brunoborges** [comment]
I believe that if you are going to have a single PDB, then there is no license cost implication. @gvenzl may confirm.

**Comment by gvenzl** [comment]
@BrianFlowerday, your DBAs have to do their homework! We allow a single tenant configuration free of charge, both for EE and SE2. That means that you can have one PDB of each kind, please see the [Database Licensing Information User Manual](https://docs.oracle.com/database/122/DBLIC/Licensing-Information.htm#DBLIC-GUID-0F9EB85D-4610-4EDF-89C2-4916A0E7AC87) for more information. In there you will find:

> The number value in each column indicates the maximum number of pluggable databases (PDBs) that can be created for each offering.
> 
> For all offerings, if you are not licensed for Oracle Multitenant, then the container database architecture is available in single-tenant mode, that is, with one user-created PDB, one user-created application root, and one user-created proxy PDB.

Furthermore, please educate your DBAs that the *traditional database architecture aka non-CDB architecture* has been deprecated with the release of 12.1. In the 12.1 [Database Upgrade Guide](https://docs.oracle.com/database/121/UPGRD/deprecated.htm#BABDBCJI) you will find:

> The non-CDB architecture is deprecated in Oracle Database 12c, and may be desupported and unavailable in a release after Oracle Database 12c Release 2. Oracle recommends use of the CDB architecture.

Oracle highly recommends everybody to move to the CDB architecture as soon as possible before it will make the decision for them, i.e. desupport the non-CDB architecture!
