### ISSUE TITLE
Can not build image for 11.2.0.2

### ISSUE THREAD

**Issue by xiaoyan1985** [oracle/docker-images#675]
I met errors as followings, as building images for 11.2.0.2 in centos7

```
sysctl: setting key "kernel.sem": Read-only file system
/var/tmp/rpm-tmp.2c2oCv: line 257: [: 18446744073692774399: integer expression expected
/var/tmp/rpm-tmp.2c2oCv: line 271: [: 18446744073692774399: integer expression expected
sysctl: setting key "fs.file-max": Read-only file system
Executing post-install steps...
You must run '/etc/init.d/oracle-xe configure' as the root user to configure the database.
```

docker version:  1.10.3
Can you help me to solve it ? Thanks #

**Comment by gvenzl** [comment]
None of those are actually errors that will break the image build. As you can see, the install goes happily on to `Executing post-install steps...`. Can you please share the entire output of the build so that I can see where the actual error is?

**Comment by xiaoyan1985** [comment]
Thanks for your reply. 
Currently, the ORACLE image is not used, so you can close the problem. 
Thank you very much.
