### ISSUE TITLE
OracleDatabase HEALTHCHECK Unknown flag: start-period

### ISSUE THREAD

**Issue by JeremyVV** [oracle/docker-images#676]
CentOs 7.4 with docker version 1.12.6, build 85d7426/1.12.6
`./buildDockerImage.sh -v 12.1.0.2 -s -i`
results in 
```Step 16 : HEALTHCHECK --interval=1m --start-period=5m CMD "$ORACLE_BASE/$CHECK_DB_FILE" >/dev/null || exit 1
Unknown flag: start-period
There was an error building the image.
```

**Comment by clemSeveillac** [comment]
If you cannot upgrade to docker 17.06 or above, @gvenzl advises you here https://github.com/oracle/docker-images/issues/632#issuecomment-342253088 to simply remove that option in the `HEALTHCHECK` line of the `Dockerfile`.

**Comment by gvenzl** [comment]
That is correct, you should upgrade to the latest version or at least 17.05-ce. If you can't do that, btw, 1.12 is a rather old version of Docker, then you can happily either remove the `HEALTHCHECK` option altogether or just the `--start-period` parameter of it (in case that `HEALTHCHECK` itself is already supported by the version you are using).
