### ISSUE TITLE
Oracle Database 12c docker image

### ISSUE THREAD

**Issue by typekpb** [oracle/docker-images#68]
I'd love to see official Oracle Database 12c docker image available. Any chance for that?

**Comment by brunoborges** [comment]
As soon as it exists :-)

But thanks for sharing your interest!

**Comment by typekpb** [comment]
Just curious. Is it planned? Some timeline available? Thx.

**Comment by Djelibeybi** [comment]
We do not comment on future product releases or ETAs, so we can't answer that question. I will point out that Database 12c was recently certified in an LXC container as an indicator, though.

**Comment by typekpb** [comment]
Thanks a lot for answer. Sounds promissing :)

**Comment by Vanuan** [comment]
Is there a particular reason to ban images provided by the community?
https://github.com/wscherphof/oracle-12c/issues/24

**Comment by Djelibeybi** [comment]
Because it's a violation of Oracle's licensing terms to distribute Oracle proprietary software.

**Comment by brunoborges** [comment]
As a comparison, other even open source products (i.e. JBoss EAP [1]) do not publish their proprietary binaries due to similar licensing terms.

[1] https://hub.docker.com/u/jboss/

**Comment by Vanuan** [comment]
Is it because it would be easy to violate the license terms if it were published on Docker Hub? Maybe some "I agree" checkbox could be added to Docker Hub to mitigate that problem?

**Comment by Djelibeybi** [comment]
No. There are many issues including no rights to distribute. It's not possible to host Oracle binaries outside of Oracle.
