### ISSUE TITLE
tnsnames.ora with extra spaces fail to resolve service in 11gXE DB image

### ISSUE THREAD

**Issue by marcelo-ochoa** [oracle/docker-images#680]
runOracle.sh have extra spaces before SQLNet string name for XE entry, so it fail to resolve the service when using for example:
bash-4.2$ sqlplus "sys/oracle@XE as sysdba"

SQL*Plus: Release 11.2.0.2.0 Production on Fri Dec 8 23:17:14 2017

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

ERROR:
ORA-12154: TNS:could not resolve the connect identifier specified

removing spaces before XE string works OK, see example:

bash-4.2$ sqlplus "sys/oracle@XE as sysdba"

SQL*Plus: Release 11.2.0.2.0 Production on Fri Dec 8 23:20:18 2017

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> 

bash-4.2$ cat tnsnames.ora 
# tnsnames.ora Network Configuration File:

XE =
           (DESCRIPTION =
             (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
             (CONNECT_DATA =
               (SERVER = DEDICATED)
               (SERVICE_NAME = XE)
             )
           )

EXTPROC_CONNECTION_DATA =
           (DESCRIPTION =
             (ADDRESS_LIST =
               (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC_FOR_XE))
             )
             (CONNECT_DATA =
               (SID = PLSExtProc)
               (PRESENTATION = RO)
             )
           )

**Comment by marcelo-ochoa** [comment]
Do I need special privileges at the repo to do do that?

**Comment by Djelibeybi** [comment]
No. Just fork the repo, make the changes on your fork and then submit those changes as a pull request.

**Comment by Djelibeybi** [comment]
However, also assigning @gvenzl to review this.

**Comment by marcelo-ochoa** [comment]
OK, I am looking the docs to do the steps.

**Comment by gvenzl** [comment]
Fixed via PR #682

**Comment by marcelo-ochoa** [comment]
Thanks
