### ISSUE TITLE
OracleWebLogic/samples/wls-k8s-domain permission denied error at startadmin.sh

### ISSUE THREAD

**Issue by lurodrig** [oracle/docker-images#686]
Hello there,

I am testing the [wls-k8s-domain](https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/wls-k8s-domain) sample.

After I [deploy all the kubernetes resources](https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/wls-k8s-domain#3-deploy-all-the-kubernetes-resources) I can see that my AdminServer did not start. Having a look at the admin-server pod log I see:

```
mkdir: cannot create directory '/u01/wlsdomain/servers': Permission denied
starting admin server...
create domain with no leasing...
/u01/oracle/startadmin.sh: line 21: admin.out: Permission denied
```
Am I missing something?

I am running my cluster in a [minikube](https://github.com/kubernetes/minikube) (single node kubernetes cluster) in my laptop.

minikube version: v0.24.1
Kubernetes v1.8.0

Thanks in advance,

Luis

**Comment by lilyhe123** [comment]
This is caused that no proper permission is set to the external directories of persistent volumes.

Refer to Section '2. Prepare Volume Directories' of README:
'The first two persistent volumes pv1 and pv2 will be used by WebLogic server pods. All processes in WebLogic server pods are running with UID 1000 and GID 1000 by default, so proper permissions need to be set to these two external directories to make sure that UID 1000 or GID 1000 have permission to read and write the volume directories. '

What's the permission to your external directories of 'pv1' ane 'pv2'? The robust way is to set the permission to 777. 
Assuming the two external directories are '$ROOR_FOLDER/v1' and '$ROOR_FOLDER/v1', do as following:
$ cd $ROOR_FOLDER
$ sudo chmod 777 v1 v2

**Comment by mriccell** [comment]
@lurodrig could you please confirm that setting the correct permissions on the volumes corrects your problem?

**Comment by lurodrig** [comment]
Hello there,

Thanks for your answer and sorry for my late response.

I must be still missing something because my external directories permissions look like these:

```
lurodrig@:wls-k8s-domain$ ls -ln
total 12
drwxrwxrwx 2 1000 1000 4096 Jan  4 13:53 pv1
drwxrwxrwx 2 1000 1000 4096 Jan  4 13:33 pv2
drwxrwxrwx 2 1000 1000 4096 Jan  4 13:33 pv3
```
In the other hand I can see that inside the admin pod, the **/u01/wlsdomain** belongs to **root**. Shouldn't it belong to **oracle** instead?

Thanks in advance,

Luis

**Comment by mriccell** [comment]
@lurodrig Yes it should belong to oracle user and not root you are correct.

**Comment by simon-meng-cn** [comment]
@lurodrig I want to know the access mode of wls-k8s-domain directory. Can you execute the following commands and show result to me?

cd wls-k8s-domain
pwd
cd ..
ls -ln

**Comment by lilyhe123** [comment]
@lurodrig Sorry for the late response.

Since shared pool of uid and gid are used by containers and the host, you should see the same uid&gid to the same folder between inside and outside of the container/pod. But in you env per your description, the uid&gid are different between inside and outside of the admin pod. The possible reason is that the external directories you looked at are not the same folder mapped to the admin pod. To verify this, you can check the contents of the external directory 'pv1' whether they are the same as what you see in /u01/wlsdomain within the admin pod.

 If no external folder found as the volume folder when admin pod running, k8s will create a new folder based on the host path you provided in pv.yml. The folder is owned by 'root' since in the Dockerfile we initially use 'root' to copy files etc and then change to user 'oracle' to starting weblogic server. That's why you got 'Permission denied' in admin pod.

I notice you used minikube. One thing you need to know about minikube is that minikube creates a VM on your local machine to deploy k8s cluster. When using persistent volume with minikube the pv needs to be mapped to a directory inside the minikube VM, NOT a directory in your host. Basically you need to go into minikube VM via run 'minikube ssh' and then create the directory to be used by persistent volume. Refer here for more details: https://myjavabytes.wordpress.com/2017/03/12/getting-a-host-path-persistent-volume-to-work-in-minikube-kubernetes-run-locally/.

**Comment by lurodrig** [comment]
Hello @simon-meng-cn,

Sorry for my late response.

mmm I amnot sure if I am following you, nevertheless here you have:

```
lurodrig@:wls-k8s-domain$ pwd
/media/hdd/tech17-demo/docker-images/OracleWebLogic/samples/wls-k8s-domain
lurodrig@:wls-k8s-domain$ cd ..
lurodrig@:samples$ ls -ln
total 84
drwxrwxr-x 3 1000 1000 4096 Dec 17 17:21 1213-domain
drwxrwxr-x 2 1000 1000 4096 Dec 17 17:21 12211-medrec
drwxrwxr-x 2 1000 1000 4096 Dec 17 17:21 12211-patch
drwxrwxr-x 3 1000 1000 4096 Dec 17 17:21 12212-domain
drwxrwxr-x 3 1000 1000 4096 Dec 17 17:21 12212-domain-online-config
drwxrwxr-x 2 1000 1000 4096 Dec 17 17:21 12212-medrec
drwxrwxr-x 5 1000 1000 4096 Dec 17 17:21 12212-msiserver
drwxrwxr-x 3 1000 1000 4096 Dec 17 17:21 12212-oradb-medrec
drwxrwxr-x 3 1000 1000 4096 Dec 17 17:21 12212-oradb-wlsstore
drwxrwxr-x 3 1000 1000 4096 Dec 17 17:21 12213-domain
drwxrwxr-x 3 1000 1000 4096 Dec 17 17:21 1221-appdeploy
drwxrwxr-x 2 1000 1000 4096 Dec 17 17:21 1221-docker-compose
drwxrwxr-x 3 1000 1000 4096 Dec 17 17:21 1221-domain
drwxrwxr-x 3 1000 1000 4096 Dec 17 17:21 1221-domain-with-resources
drwxrwxr-x 2 1000 1000 4096 Dec 17 17:21 1221-medrec
drwxrwxr-x 2 1000 1000 4096 Dec 17 17:21 1221-multihost
drwxrwxr-x 2 1000 1000 4096 Dec 17 17:21 1221-webtier-apache
-rwxrwxr-x 1 1000 1000 1242 Dec 17 17:21 clean-up-docker.sh
-rwxrwxr-x 1 1000 1000  153 Dec 17 17:21 rm-containers.sh
drwxrwxr-x 5 1000 1000 4096 Dec 17 17:21 wls-K8s
drwxrwxr-x 4 1000 1000 4096 Jan  4 14:05 wls-k8s-domain
```
Thanks,

Luis

**Comment by lurodrig** [comment]
Hello @lilyhe123 

Sorry, again, for the late response

> check the contents of the external directory 'pv1' whether they are the same as what you see in /u01/wlsdomain within the admin pod.

My `pv` manifest for `pv1` looks like this:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
  labels:
    app: wls-domain
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle  # Retain, Recycle, Delete
  hostPath:
    path: "/media/hdd/wls-k8s-domain/pv1" 
```

The contents of the `hostPath`:
```
$ ls -alrt /media/hdd/wls-k8s-domain/pv1
total 8
drwxrwxr-x 5 lurodrig lurodrig 4096 Jan  4 13:33 ..
drwxrwxrwx 2 lurodrig lurodrig 4096 Jan  4 13:53 .
```

And the contents of `/u01/wlsdomain` in the admin pod:
```
$ ls -alrt
total 4
drwxr-xr-x 1 oracle oracle 4096 Dec 17 17:29 ..
drwxr-xr-x 2 root   root      0 Mar  6 14:16 .
```

> go into minikube VM via run 'minikube ssh' and then create the directory to be used by persistent volume

The directory has been already created 

$ ls -alrt /media/hdd/wls-k8s-domain/
total 0
drwxr-xr-x 2 root root 0 Mar  6 14:16 pv1
drwxr-xr-x 3 root root 0 Mar  6 14:16 ..
drwxr-xr-x 2 root root 0 Mar  6 14:16 pv2
drwxr-xr-x 4 root root 0 Mar  6 14:16 .
$ ls -alrt /media/hdd/wls-k8s-domain/pv
pv1/ pv2/ 
$ ls -alrt /media/hdd/wls-k8s-domain/pv1/
total 0
drwxr-xr-x 2 root root 0 Mar  6 14:16 .
drwxr-xr-x 4 root root 0 Mar  6 14:16 ..
$ ls -alrt /media/hdd/wls-k8s-domain/pv2/
total 0
drwxr-xr-x 4 root root 0 Mar  6 14:16 ..
drwxr-xr-x 2 root root 0 Mar  6 14:16 .

Thanks,

Luis

**Comment by lurodrig** [comment]
Hello @simon-meng-cn 

Sorry, again :(, for my late response.

```
lurodrig@:wls-k8s-domain$ pwd
/media/hdd/wls-k8s-domain
lurodrig@:wls-k8s-domain$ cd ..
lurodrig@:hdd$ ls -ln
.../...
drwxrwxr-x  5 1000 1000  4096 Jan  4 13:33 wls-k8s-domain
```

Thanks in advance,

Luis

**Comment by lilyhe123** [comment]
Hi Luis,

```
$ ls -alrt /media/hdd/wls-k8s-domain/
total 0
drwxr-xr-x 2 root root 0 Mar 6 14:16 pv1
drwxr-xr-x 3 root root 0 Mar 6 14:16 ..
drwxr-xr-x 2 root root 0 Mar 6 14:16 pv2
drwxr-xr-x 4 root root 0 Mar 6 14:16 .
```
Based on the info you provided as above, in your minikube VM the access mode of pv1 and pv2  is '755' and owner of these folders are 'root'. When the admin server started in pod, the user is 'oracle'. User 'oracle' has no access to pv1 and pv2 based on your current configuration. This can explain why you got 'Permission denied' in admin pod.

My suggestion is that you need to first create /media/hdd/wls-k8s-domain/pv1/ and /media/hdd/wls-k8s-domain/pv1/ in the minikube VM and change the access mode to '777' before deploying k8s resources of the sample domain.

**Comment by lilyhe123** [comment]
Forgot to mention that the folder /media/hdd/wls-k8s-domain in your host is not used by minikube. Only the folder with the same path in minikube VM is used as pv.

**Comment by lurodrig** [comment]
Hello @lilyhe123,

Thanks a lot, it works!

Sorry I completely _"forgot"_ to create the directory in my minikube. I should have gone through [Configure a Pod to Use a PV for storage](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-pod) first

> change the access mode to '777' before deploying k8s 
Perhaps this point should be clarified in the  [README.md](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/wls-k8s-domain/README.md)

Cheers,

Luis
