### ISSUE TITLE
Errors after container startup

### ISSUE THREAD

**Issue by agoretsky** [oracle/docker-images#688]
Hello, I built container using Ubuntu bash on Windows 10, then I started container:
 `docker run -d -it --name oracle-db -p 1521:1521 -e ORACLE_SID=ORCLCDB -e ORACLE_PWD=oracle oracle/database:12.2.0.1-ee`
docker container logs output:

> ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: oracle
> 
> LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 20-DEC-2017 08:26:57
> 
> Copyright (c) 1991, 2016, Oracle.  All rights reserved.
> 
> Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...
> 
> TNSLSNR for Linux: Version 12.2.0.1.0 - Production
> System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
> Log messages written to /opt/oracle/diag/tnslsnr/9882d4ba02fd/listener/alert/log.xml
> Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
> Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
> 
> Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
> STATUS of the LISTENER
> ------------------------
> Alias                     LISTENER
> Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
> Start Date                20-DEC-2017 08:26:58
> Uptime                    0 days 0 hr. 0 min. 0 sec
> Trace Level               off
> Security                  ON: Local OS Authentication
> SNMP                      OFF
> Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
> Listener Log File         /opt/oracle/diag/tnslsnr/9882d4ba02fd/listener/alert/log.xml
> Listening Endpoints Summary...
>   (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
>   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
> The listener supports no services
> The command completed successfully
> [WARNING] [DBT-11209] Current available physical memory is less than the required physical memory (2,048MB) for creating the database.
> [WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
>    CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
>    ACTION: Select a listener to be registered or created with the database.
> [WARNING] [DBT-06208] The 'SYS' password entered does not conform to the Oracle recommended standards.
>    CAUSE:
> a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
> b.The password entered is a keyword that Oracle does not recommend to be used as password
>    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
> [WARNING] [DBT-06208] The 'SYSTEM' password entered does not conform to the Oracle recommended standards.
>    CAUSE:
> a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
> b.The password entered is a keyword that Oracle does not recommend to be used as password
>    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
> [WARNING] [DBT-06208] The 'PDBADMIN' password entered does not conform to the Oracle recommended standards.
>    CAUSE:
> a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
> b.The password entered is a keyword that Oracle does not recommend to be used as password
>    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
> Copying database files
> 1% complete
> 2% complete
> DBCA Operation failed.
> Look at the log file "/opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log" for further details.
> [ 2017-12-20 08:28:57.940 UTC ] Copying database files
> DBCA_PROGRESS : 1%
> [ 2017-12-20 08:28:58.414 UTC ] ORA-12547: TNS:lost contact
> 
> DBCA_PROGRESS : 2%
> [ 2017-12-20 08:28:58.552 UTC ] Error while cataloging RMAN Backups
> [ 2017-12-20 08:28:58.693 UTC ] DBCA_PROGRESS : DBCA Operation failed.
> 
> SQL*Plus: Release 12.2.0.1.0 Production on Wed Dec 20 08:28:59 2017
> 
> Copyright (c) 1982, 2016, Oracle.  All rights reserved.
> 
> ERROR:
> ORA-12547: TNS:lost contact
> 
> 
> Enter user-name: SP2-0306: Invalid option.
> Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
> where <logon> ::= <username>[/<password>][@<connect_identifier>]
>       <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
> Enter user-name: SP2-0306: Invalid option.
> Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM|SYSBACKUP|SYSDG|SYSKM|SYSRAC}] [edition=value]]
> where <logon> ::= <username>[/<password>][@<connect_identifier>]
>       <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
> SP2-0157: unable to CONNECT to ORACLE after 3 attempts, exiting SQL*Plus
> mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileORCLCDB.ora': No such file or directory
> mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwORCLCDB': No such file or directory

**Comment by elijahgagne** [comment]
I'm on Windows 10 and seeing something similar:

```
C:\Users\egagn> docker run -d -it --name oracle-db -p 1521:1521 -e ORACLE_SID=ORCLCDB -e ORACLE_PWD=oracle oracle/database:12.2.0.1-ee
94f6e33293db05d6d8c609187da4e21cec13d66b9d62c2d5f173c8bda3f7038b
C:\Users\egagn> docker logs --tail 100 -f oracle-db
ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: oracle

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 01-JAN-2018 14:02:30

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/94f6e33293db/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                01-JAN-2018 14:02:30
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/94f6e33293db/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[WARNING] [DBT-11209] Current available physical memory is less than the required physical memory (2,048MB) for creating the database.
[WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
   CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
   ACTION: Select a listener to be registered or created with the database.
[WARNING] [DBT-06208] The 'SYS' password entered does not conform to the Oracle recommended standards.
   CAUSE:
a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
b.The password entered is a keyword that Oracle does not recommend to be used as password
   ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
[WARNING] [DBT-06208] The 'SYSTEM' password entered does not conform to the Oracle recommended standards.
   CAUSE:
a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
b.The password entered is a keyword that Oracle does not recommend to be used as password
   ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
[WARNING] [DBT-06208] The 'PDBADMIN' password entered does not conform to the Oracle recommended standards.
   CAUSE:
a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
b.The password entered is a keyword that Oracle does not recommend to be used as password
   ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
Copying database files
1% complete
13% complete
25% complete
Creating and starting Oracle instance
26% complete
27% complete
31% complete
32% complete
DBCA Operation failed.
Look at the log file "/opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log" for further details.
[ 2018-01-01 14:04:46.845 UTC ] Copying database files
DBCA_PROGRESS : 1%
DBCA_PROGRESS : 13%
DBCA_PROGRESS : 25%
[ 2018-01-01 14:06:12.893 UTC ] Creating and starting Oracle instance
[ 2018-01-01 14:06:26.933 UTC ] ORA-03113: end-of-file on communication channel

DBCA_PROGRESS : 26%
DBCA_PROGRESS : 27%
[ 2018-01-01 14:06:28.155 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.159 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.163 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.166 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.168 UTC ] ORA-01012: not logged on

DBCA_PROGRESS : 31%
[ 2018-01-01 14:06:28.172 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.177 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.180 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.193 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.196 UTC ] ORA-01012: not logged on

DBCA_PROGRESS : 32%
[ 2018-01-01 14:06:29.273 UTC ] ORA-01034: ORACLE not available

[ 2018-01-01 14:06:29.285 UTC ] ORA-01034: ORACLE not available

[ 2018-01-01 14:06:35.082 UTC ] DBCA_PROGRESS : DBCA Operation failed.

SQL*Plus: Release 12.2.0.1.0 Production on Mon Jan 1 14:06:35 2018

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Connected to an idle instance.

SQL>    ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORCLCDB/control01.ctl' scope=spfile
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL>    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> Disconnected
mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileORCLCDB.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwORCLCDB': No such file or directory
```

Looking at the log file does not provide any new insight
```
C:\Users\egagn> docker exec oracle-db cat /opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log
[ 2018-01-01 14:04:46.845 UTC ] Copying database files
DBCA_PROGRESS : 1%
DBCA_PROGRESS : 13%
DBCA_PROGRESS : 25%
[ 2018-01-01 14:06:12.893 UTC ] Creating and starting Oracle instance
[ 2018-01-01 14:06:26.933 UTC ] ORA-03113: end-of-file on communication channel

DBCA_PROGRESS : 26%
DBCA_PROGRESS : 27%
[ 2018-01-01 14:06:28.155 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.159 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.163 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.166 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.168 UTC ] ORA-01012: not logged on

DBCA_PROGRESS : 31%
[ 2018-01-01 14:06:28.172 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.177 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.180 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.193 UTC ] ORA-01012: not logged on

[ 2018-01-01 14:06:28.196 UTC ] ORA-01012: not logged on

DBCA_PROGRESS : 32%
[ 2018-01-01 14:06:29.273 UTC ] ORA-01034: ORACLE not available

[ 2018-01-01 14:06:29.285 UTC ] ORA-01034: ORACLE not available

[ 2018-01-01 14:06:35.082 UTC ] DBCA_PROGRESS : DBCA Operation failed.
```

**Comment by whisdom** [comment]
Have you noticed the warning: Current available physical memory is less than the required physical memory (2,048MB) for creating the database.

How much memory is available on your system.

**Comment by agoretsky** [comment]
increasing memory removes this warning, but the result is the same

**Comment by thtechnology** [comment]
same issue ... trying to find a way to run a docker oracle image on windows 10.   there must be a way ...

**Comment by gvenzl** [comment]
The database session process crashed while creating the database, indicated by `ORA-03113: end-of-file on communication channel`. A next step would be to find the trace file of the session process to find out why it crashed.

**Comment by sangohan** [comment]
https://dba.stackexchange.com/questions/49682/ora-03113-end-of-file-on-communication-channel-on-startup

mentions something about the db recovery file size is full, and fixing that should remove this problem.

**Comment by gvenzl** [comment]
Closing due to lack of response.
