### ISSUE TITLE
rand_pwd does not adhere to Oracle DB password requirements

### ISSUE THREAD

**Issue by klauern** [oracle/docker-images#689]
I've been using the OracleSOASuite docker buildout to generate some containers, but I have had numerous occasions where the password it generates doesn't conform to Oracle's DB password requirements.  I get this error somewhat regularly:

> A valid password must be specified. Password should be alpha numeric only and can contain the following special characters: $, # , _ .Password should not start with a number or a special character.
> ERROR - RCU-6091 Component validation failed.
> CAUSE - RCU-6091 One or more component specific validation failed.
> ACTION - RCU-6091 Check log for more details and fix the validation error.

https://github.com/oracle/docker-images/blob/fd77c82807429e9c0ec20ee9d1eed22269f43404/OracleSOASuite/dockerfiles/12.2.1.3/container-scripts/createDomainAndStart.sh#L36-L48

I've taken the function out and called it ~10 times, and this is the output:

```
INFO: Password does not Match the criteria, re-generating...
INFO: hR95KNQQ
INFO: 1KROmBDi
INFO: NIIEFf5B
INFO: ico1bHaQ
INFO: cQhuFNr4
INFO: Password does not Match the criteria, re-generating...
INFO: Password does not Match the criteria, re-generating...
INFO: 6VmsdXJg
INFO: aJbRhUL7
INFO: ZHDg02rm
INFO: wiqAU65A
INFO: Password does not Match the criteria, re-generating...
INFO: 5kPNu0Hc
```

**Comment by klauern** [comment]
I forgot to mention, but it says that it **shouldn't start with a number**, yet it appears to generate that at least 3 times in my simple test.

**Comment by rdas76** [comment]
Fixed in PR : https://github.com/oracle/docker-images/pull/1317

Closing the issue.
