### ISSUE TITLE
java.io.FileNotFoundException: fmw_12.2.1.0.0_wls_supplemental_quick_Disk1_1of1.zip (Permission denied)

### ISSUE THREAD

**Issue by mustafau** [oracle/docker-images#69]
I was trying to build 1221-medrec image when I encountered this exception.

**bash-3.2$** docker build -t 1221-medrec .
Sending build context to Docker daemon 234.5 MB
Step 1 : FROM oracle/weblogic:12.2.1-developer
 ---> dccb61bb75ef
Step 2 : MAINTAINER Monica Riccelli <monica.riccelli@oracle.com>
 ---> Using cache
 ---> 41fc7332de65
Step 3 : ENV FMW_PKG "fmw_12.2.1.0.0_wls_supplemental_quick_Disk1_1of1.zip" MW_HOME "$ORACLE_HOME" ANT_OPTIONS "-Djava.security.egd=file:/dev/./urandom -Xms512m -Xmx1024m -XX:MaxPermSize=2048m" EXAMPLES_HOME "/u01/oracle/wlserver/samples/server" CLASSPATH "$JAVA_HOME/lib/tools.jar:$ORACLE_HOME/wlserver/modules/features/wlst.wls.classpath.jar" PATH "$ORACLE_HOME/wlserver/server/bin:$ORACLE_HOME/wlserver/../oracle_common/modules/org.apache.ant_1.9.2/bin:$JAVA_HOME/jre/bin:$JAVA_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$ORACLE_HOME/oracle_common/common/bin:$ORACLE_HOME/wlserver/common/bin:$ORACLE_HOME/user_projects/domains/medrec/bin:$ORACLE_HOME/wlserver/samples/server/medrec/:$ORACLE_HOME/wlserver/../oracle_common/modules/org.apache.maven_3.2.5/bin"
 ---> Using cache
 ---> fa414f1aec55
Step 4 : COPY $FMW_PKG weblogic.properties startSample.sh ./
 ---> Using cache
 ---> 8586bff258ae
Step 5 : RUN jar xvf $FMW_PKG &&     java -jar $(ls -1 *.jar) ORACLE_HOME=$ORACLE_HOME &&     mkdir -p /u01/oracle/wlserver/samples/server/medrec/ &&     mv weblogic.properties startSample.sh /u01/oracle/wlserver/samples/server/medrec/ &&     rm $FMW_PKG $(ls -1 *.jar)
 ---> Running in aa3fca985c35
java.io.FileNotFoundException: fmw_12.2.1.0.0_wls_supplemental_quick_Disk1_1of1.zip (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.tools.jar.Main.run(Main.java:307)
	at sun.tools.jar.Main.main(Main.java:1288)
The command '/bin/sh -c jar xvf $FMW_PKG &&     java -jar $(ls -1 *.jar) ORACLE_HOME=$ORACLE_HOME &&     mkdir -p /u01/oracle/wlserver/samples/server/medrec/ &&     mv weblogic.properties startSample.sh /u01/oracle/wlserver/samples/server/medrec/ &&     rm $FMW_PKG $(ls -1 *.jar)' returned a non-zero code: 1

**Comment by brunoborges** [comment]
You must download file `fmw_12.2.1.0.0_wls_supplemental_quick_Disk1_1of1.zip`, as per documentation indicates in the README file of this sample, as well the .download placeholder file in this folder.

**Comment by mustafau** [comment]
I downloaded and put the file in place before running into this exception.

**Comment by brunoborges** [comment]
Then there is something wrong with your environment. Please note the exception:

        java.io.FileNotFoundException: fmw_12.2.1.0.0_wls_supplemental_quick_Disk1_1of1.zip (Permission denied)

**Comment by mustafau** [comment]
Commit 3d58a517792778c4e2670fda7f6c7ee3689894d5 (https://github.com/oracle/docker-images/commit/3d58a517792778c4e2670fda7f6c7ee3689894d5) introduced this regression. The Java process does not have enough permissions to the zip file thus throws FileNotFoundException. Before that commit everything works fine.

**Comment by mustafau** [comment]
Here are zip files permissions inside container:

Step 5 : RUN ls -alh $FMW_PKG
-rw-r----- 1 root root 224M Feb  1 22:21 fmw_12.2.1.0.0_wls_supplemental_quick_Disk1_1of1.zip

**Comment by mustafau** [comment]
Chmodding local file fixed the problem inside the container. Was not a regression, sorry.

chmod 644 fmw_12.2.1.0.0_wls_supplemental_quick_Disk1_1of1.zip

**Comment by brunoborges** [comment]
I'm sorry, @mustafau... I did not understand. Is there a problem with the current code or not?

**Comment by mustafau** [comment]
There is not a problem with the current code. 

One should check permissions of the zip file after downloading it. It has to be "644".
