### ISSUE TITLE
# dockerfiles$ ./buildDockerImage.sh -v 12.2.1.3 -g

### ISSUE THREAD

**Issue by punitporwal** [oracle/docker-images#694]
Building image 'oracle/weblogic:12.2.1.3-generic' ...
Sending build context to Docker daemon 15.87 kB
Step 1/13 : FROM oracle/serverjre:8
repository oracle/serverjre not found: does not exist or no pull access
There was an error building the image.

fi: I have place the fmw_12.2.1.3.0_wls.jar onto the same directory..

**Comment by mriccell** [comment]
You must build the Server JRE image before building the WebLogic image, refer to https://github.com/oracle/docker-images/tree/master/OracleJava/java-8
