### ISSUE TITLE
Cannot create datasource in weblogic 

### ISSUE THREAD

**Issue by nalinisriv3** [oracle/docker-images#700]
Hi,
I am using Docker 17.09.0-ce-win33 on Windows machine with JAVA - jdk1.8.0_141. I am new to Oracle Weblogic.
I am trying to deploy an application war in Weblogic server 12.2.1.2 and connect it to Oracle Database 12.1.0.2 through DataSources created from oipa-ds-deploy.py file. I am not getting any error on build / run. Weblogic is starting fine but I can't see the datasources created here in Admin Console and even though I am giving domain_name as oipa domain that got create is base_domain. 
I have imported a database dump file into the database container(dbname-oipa) and following is my dockerfile.
Dockerfile-
`FROM store/oracle/weblogic:12.2.1.2
MAINTAINER Nalini Srivastava <nalini.srivastava@oracle.com>
ENV FMW_PKG="fmw_12.2.1.2.0_wls_supplemental_quick_Disk1_1of1.zip" \
    FMW_JAR="fmw_12.2.1.2.0_wls_supplemental_quick.jar" \
    MW_HOME="$ORACLE_HOME" \ 
   PATH="$ORACLE_HOME/wlserver/server/bin:$ORACLE_HOME/wlserver/../oracle_common/modules/org.apache.ant_1.9.2/bin:$JAVA_HOME/jre/bin:$JAVA_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$ORACLE_HOME/oracle_common/common/bin:$ORACLE_HOME/wlserver/common/bin:$ORACLE_HOME/user_projects/domains/oipa/bin:$ORACLE_HOME/wlserver/samples/server/:$ORACLE_HOME/wlserver/samples/server/oipa/:$ORACLE_HOME/wlserver/../oracle_common/modules/org.apache.maven_3.2.5/bin"
COPY $FMW_PKG /u01/
USER root
COPY container-scripts/*  /u01/oracle/
USER oracle
RUN cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - && \
    $JAVA_HOME/bin/java -jar /u01/$FMW_JAR  ORACLE_HOME=$ORACLE_HOME && \
    echo $USER && \
    mv /u01/oracle/startSample.sh /u01/oracle/wlserver/samples/server/  && \
    rm /u01/$FMW_PKG /u01/$FMW_JAR
USER root 
RUN chmod 777 /u01/oracle/wlserver/samples/*.*
WORKDIR $ORACLE_HOME/wlserver/samples/server/
EXPOSE 7001
CMD ["startSample.sh"]
`
oipa-ds-deploy.py

`import os
domain_name  = os.environ.get("DOMAIN_NAME", "oipa")
admin_name  = os.environ.get("ADMIN_NAME", "OIPAServer")
admin_username  = os.environ.get("ADMIN_USERNAME", "weblogic")
admin_pass  = "welcome1"
admin_port   = int(os.environ.get("ADMIN_PORT", "7001"))
domain_path  = '/u01/oracle/user_projects/domains/%s' % domain_name
production_mode = os.environ.get("PRODUCTION_MODE", "prod")

readTemplate("/u01/oracle/wlserver/common/templates/wls/wls.jar")

set('Name', domain_name)
setOption('DomainName', domain_name)

cd('Servers/AdminServer')
set('ListenAddress','')
set('ListenPort', 7001)

create('AdminServer','SSL')
cd('SSL/AdminServer')
set('Enabled', 'True')
set('ListenPort', 7002)

cd('/')
cd('Security/base_domain/User/weblogic')
cmo.setPassword('welcome1')

cd('/')
create('myDataSource', 'ADMINSERVERDS')
cd('ADMINSERVERDS/myDataSource/JdbcResource/myDataSource')
create('myJdbcDriverParams','JDBCDriverParams')
cd('JDBCDriverParams/NO_NAME_0')
set('DriverName','oracle.jdbc.xa.client.OracleXADataSource')
set('URL','jdbc:oracle:thin:@localhost:1521/nalini')
set('PasswordEncrypted', 'PBPUBLIC')
create('myProps','Properties')
cd('Properties/NO_NAME_0')
create('user', 'Property')
cd('Property/user')
cmo.setValue('PBPUBLIC')

cd('/ADMINSERVERDS/myDataSource/JdbcResource/myDataSource')
create('myJdbcDataSourceParams','JDBCDataSourceParams')
cd('JDBCDataSourceParams/NO_NAME_0')
set('JNDIName', java.lang.String("ADMINSERVERDS"))

cd('/ADMINSERVERDS/myDataSource/JdbcResource/myDataSource')
create('myJdbcConnectionPoolParams','JDBCConnectionPoolParams')
cd('JDBCConnectionPoolParams/NO_NAME_0')
set('TestTableName','ASBUSINESSRULES')
cd('/')
assign('ADMINSERVERDS', 'myDataSource', 'Target', 'AdminServer')
setOption('OverwriteDomain', 'true')

cd('/NMProperties')
set('ListenAddress','')
set('ListenPort',5556)
set('CrashRecoveryEnabled', 'true')
set('NativeVersionEnabled', 'true')
set('StartScriptEnabled', 'false')
set('SecureListener', 'false')
set('LogLevel', 'FINEST')

cd('/SecurityConfiguration/base_domain')
set('NodeManagerUsername', 'weblogic')
set('NodeManagerPasswordEncrypted', admin_pass)

writeDomain(domain_path)
closeTemplate()
exit()`

startSample.sh

`USERNAME=${USERNAME:-weblogic}
PASSWORD=${PASSWORD:-welcome1}
export DOMAIN_HOME=/u01/oracle/user_projects/domains/$DOMAIN_NAME
ADD_DOMAIN=1
if [ ! -f ${DOMAIN_HOME}/servers/AdminServer/logs/AdminServer.log ]; then
    ADD_DOMAIN=0
fi

if [ $ADD_DOMAIN -eq 0 ]; then

if [ -z $ADMIN_PASSWORD ]; then
   while true; do
     s=$(cat /dev/urandom | tr -dc "A-Za-z0-9" | fold -w 8 | head -n 1)
     if [[ ${#s} -ge 8 && "$s" == *[A-Z]* && "$s" == *[a-z]* && "$s" == *[0-9]*  ]]; then
         break
     else
         echo "Password does not Match the criteria, re-generating..."
     fi
   done

   echo ""
   echo "    Oracle WebLogic Server Auto Generated Empty Domain:"
   echo ""
   echo "      ----> 'weblogic' admin password: $s"
   echo ""
else
   s=${ADMIN_PASSWORD}
   echo "      ----> 'weblogic' admin password: $s"
fi 
sed -i -e "s|ADMIN_PASSWORD|$s|g" /u01/oracle/create-wls-domain.py

wlst.sh -skipWLSModuleScanning /u01/oracle/create-wls-domain.py
mkdir -p ${DOMAIN_HOME}/servers/AdminServer/security/ 
echo "username=${ADMIN_USERNAME}" > /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security/boot.properties 
echo "password=$s" >> /u01/oracle/user_projects/domains/$DOMAIN_NAME/servers/AdminServer/security/boot.properties 
${DOMAIN_HOME}/bin/setDomainEnv.sh 
fi

${DOMAIN_HOME}/startWebLogic.sh
touch ${DOMAIN_HOME}/servers/AdminServer/logs/AdminServer.log
tail -f ${DOMAIN_HOME}/servers/AdminServer/logs/AdminServer.log &
childPID=$!
wait $childPID
wlst.sh -loadProperties /u01/oracle/oradatasource.properties /u01/oracle/oipa-ds-deploy.py 
${ORACLE_HOME}/wlserver/samples/domains/oipa/startWebLogic.sh
`

oradatasource.properties - 

`domainname=oipa
domainhome=/u01/oracle/wlserver/samples/domains/oipa
admin_name=OIPAServer
dsname=ADMINSERVERDS
dsdbname=nalini	
dsjndiname=ADMINSERVERDS
dsdriver=oracle.jdbc.xa.client.OracleXADataSource
dsurl=jdbc:oracle:thin:@//localhost:1521/nalini
dsusername=oipa
dspassword=oipa
dstestquery=SELECT * FROM ASBUSINESSRULES
dsmaxcapacity=1
`

I also tried creating domain from config.sh file in $ORACLE_HOME/oracle_common/common/bin/config.sh by executing command 
`./config.sh` 
but nothing is happening.

bash-4.2# ./config.sh
bash-4.2# chmod 777 config.sh
bash-4.2# ./config.sh
bash-4.2#

Please help me out here.
Thanks in advance.
Nalini Srivastava

**Comment by nalinisriv3** [comment]
Hi,
If you need more info then please ask for it or please help me out here if you have any clue. Its been a week since I posted this question.  Can someone from the contributor please add the label 'Help wanted'? Thanks.

**Comment by brunoborges** [comment]
This is a WebLogic issue, not related to Docker. Please post it to the WebLogic forum on community.oracle.com.

I also suggest posting it to StackOverflow with the WebLogic tag.
