### ISSUE TITLE
rm: cannot remove ‘/opt/oracle/install’: Directory not empty

### ISSUE THREAD

**Issue by sujoys** [oracle/docker-images#701]
Hi All,
I am creating an Oracle 12.1.0.2 docker image on RHEL 7.4.
However, during the installation, I get the below error message at Step 11:
The directory /opt is empty and there is no oracle folder, do let me know if I am missing something?
Also, the user with which I am running this installation has sudo access and is added to docker group.

Thanks a lot for all your help on this issue.

Below is the execution snippet:
```
Step 11/17 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh && $ORACLE_HOME/root.sh && rm -rf $INSTALL_DIR
—> Running in 461871045fa5
Changing permissions of /opt/oracle/oraInventory.
Adding read,write permissions for group.
Removing read,write,execute permissions for world.

Changing groupname of /opt/oracle/oraInventory to dba.
The execution of the script is complete.
Check /opt/oracle/product/12.1.0.2/dbhome_1/install/root_461871045fa5_2018-01-05_10-48-10.log for the output of root script
rm: cannot remove ‘/opt/oracle/install’: Directory not empty
Removing intermediate container 461871045fa5
The command ‘/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh && $ORACLE_HOME/root.sh && rm -rf $INSTALL_DIR’ returned a non-zero code: 1
There was an error building the image.
```

**Comment by gvenzl** [comment]
Hi @sujoys, can you please share the output of `docker info` please.

**Comment by sujoys** [comment]
Hi Gvenzl,

Please find below the output of docker info:
Do let me know if you require any other details.
Thanks,
```Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.06.2-ee-5
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.1.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56GiB
Name: bnglxscb01.temenosgroup.com
ID: 4GHH:K6JL:DLPW:YZLR:CLBM:HRYT:KCHH:3A5M:PECJ:FVY6:CWGA:XN3U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
```

**Comment by gvenzl** [comment]
Thanks @sujoys. Your issue is highly likely to be related to the old `overlay` storage driver which should no longer be used.

As the warning at the very end prints:

```
WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
```
Can you please switch to either `overlay2` or `btrfs` as storage engine and check whether the issue still occurs?

**Comment by Djelibeybi** [comment]
Actually, @sujoys and @gvenzl: that error will appear when using `overlay2` as well if the underlying XFS filesystem is not formatted with `d_type` support. You will need to format the filesystem used for `/var/lib/docker` with `ftype=1` on the `mkfs.xfs` line. 

If you're using the default root filesystem, then you should reinstall using the Oracle Linux 7 Update 4 installation media that does this automatically for you.

**Comment by sujoys** [comment]
@Djelibeybi: Thanks a lot for your inputs on this. However for the original issue with the deployment failure is this file system format responsible?

**Comment by Djelibeybi** [comment]
@sujoys possibly. You're also running a very new version of Docker (17.06-ee) on a very old kernel (3.10.0). 

As a test, could you please try exactly the same steps but on Oracle Linux 7 with UEK4? If that works, you'll need to engage either Docker or Red Hat to work out why it doesn't work on their combination.

**Comment by sujoys** [comment]
@Djelibeybi : Thanks a lot for your prompt response, appreciate it!
 I will try these out.

**Comment by gvenzl** [comment]
Closing this for now, please reopen if the issue remains.
