### ISSUE TITLE
outdated versions

### ISSUE THREAD

**Issue by davidkarlsen** [oracle/docker-images#71]
Looking at 
https://github.com/oracle/docker-images/blob/master/OracleJDK/java-8/Dockerfile
the images seem old and updated - no u74 for example.
Would it not make sense to have individual git repos per image, and have according tags to provide versioned/tagged images?
oracle/java:8u74 f.ex?

**Comment by brunoborges** [comment]
Hi @davidkarlsen, thank you for bringing this to our attention. I will update these files asap.

We do not keep individual repos per image/tag because these files are examples.
