### ISSUE TITLE
Clarify in CONTRIBUTING.md about Dockerfile ownership

### ISSUE THREAD

**Issue by brunoborges** [oracle/docker-images#710]
The CONTRIBUTING file must clarify how Oracle engineers and PMs must request code ownership to be responsible for the Dockerfiles they contribute to (brand new ones) this repository, and how to communicate if there is a change in the ownership.

**Comment by Djelibeybi** [comment]
I assume you'll be providing this clarification? :)

**Comment by brunoborges** [comment]
Absolutely... just not now. This is literally a TODO for myself :D

**Comment by gvenzl** [comment]
Hey @Djelibeybi, given the latest circumstances, do you have any clue what @brunoborges meant with this TODO? :)

**Comment by Djelibeybi** [comment]
Yeah, vaguely. Let me write something up and I'll get you and @mriccell to review via PR.

**Comment by gvenzl** [comment]
Merged --> Closing issue
