### ISSUE TITLE
After upgrading Docker/Linux Database Assistant can't evaluate free memory using  12cR2 image

### ISSUE THREAD

**Issue by marcelo-ochoa** [oracle/docker-images#711]
I recently build a new 12cR2 image from scratch and try to create a fresh database using:
`[mochoa@localhost dockerfiles]$ docker run -e ORACLE_SID=TEST -e ORACLE_PDB=PDB1 --privileged --name test_env --hostname test_env -p 1521:1521 -p 5500:5500 -v /dev/shm --tmpfs /dev/shm:rw,nosuid,nodev,exec,size=2g  -v /home/data/tmp/test:/opt/oracle/oradata -v /home/mochoa/tmp/test:/opt/oracle/scripts/setup oracle/database:12.2.0.1-ee`
Docker container start but Database Configuration Assistant can't find how much memory is free in my system, here the output:
```
ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: ImBxMQaASOw=1

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 11-JAN-2018 20:10:08

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/test_env/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                11-JAN-2018 20:10:16
Uptime                    0 days 0 hr. 0 min. 8 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/test_env/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[FATAL] [DBT-08001] Unable to check for available memory.
[FATAL] [DBT-08002] Unable to check the value of kernel parameter {0}
cat: /opt/oracle/cfgtoollogs/dbca/TEST/TEST.log: No such file or directory
....
```
my oracle images are:
```
oracle/database                                       12.1.0.2-se2             7de3eeaf611b        5 hours ago         10.5GB
oracle/database                                       12.1.0.2-ee              4cdd6bc17b71        22 hours ago        10.6GB
oracle/database                                       12.2.0.1-ee              e194b38516ec        29 hours ago        13.3GB
oracle/database                                       11.2.0.2-xe              b012e54c0a0d        3 weeks ago         1.13GB
```
Oracle 12c R1 EE and SE start without any problem and creates a fresh database using same command line.
My Docker Linux environment is:
```
[mochoa@localhost dockerfiles]$ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 717
Server Version: 17.12.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: btrfs local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: bonsq8mqqpr431xy0tmcujp8h
 Is Manager: true
 ClusterID: 2yg8s8m7g1tbow00nrhst4l3f
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.1.168
 Manager Addresses:
  192.168.1.168:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.64GiB
Name: localhost
ID: YPLV:BNYY:3RJN:S7WD:L2G7:RQ4T:YJYJ:KCHT:UIWR:UXDP:Z4AR:OSQO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mochoa
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
any hint to solve this problem will be great, I am using 12cR2 for a long time on this environment, this is new and I can't find on the web what the message:
```
[FATAL] [DBT-08001] Unable to check for available memory.
[FATAL] [DBT-08002] Unable to check the value of kernel parameter {0}
```
means and how to fix that. Marcelo.

**Comment by marcelo-ochoa** [comment]
I started manually the Docker container to see more in details what happen with DBCA, using:
```
[mochoa@localhost OracleDatabase]$ docker run -e ORACLE_SID=TEST -e ORACLE_PDB=PDB1 --privileged --name test_env --hostname test_env -p 1521:1521 -p 5500:5500 -ti -v /dev/shm --tmpfs /dev/shm:rw,nosuid,nodev,exec,size=2g  -v /home/data/tmp/test:/opt/oracle/oradata -v /home/mochoa/tmp/test:/opt/oracle/scripts/setup oracle/database:12.2.0.1-ee /bin/bash
[oracle@test_env oracle]$ pwd
/opt/oracle
[oracle@test_env oracle]$ /opt/oracle/runOracle.sh 
....
```
and found these warning messages after DBCA stop:

> INFO: Jan 12, 2018 1:24:21 PM oracle.assistants.common.base.util.InitParamCollectionUtil getInitParam
> INFO: Could not find the init param (cpu_count) from init params. So creating one.
> 
> 
> [main] [ 2018-01-12 13:24:21.724 UTC ] [ClusterVerification.getInstance:509]  Method Entry
> [main] [ 2018-01-12 13:24:21.724 UTC ] [CVUVariables.getCVUVariable:556]  The variable name : <CVU_CHECK_AGAIN> is not listed
> [main] [ 2018-01-12 13:24:21.724 UTC ] [sVerificationUtil.resolve:1200]  condition variable CVU_CHECK_AGAIN not handled 
> [main] [ 2018-01-12 13:24:21.725 UTC ] [CVUVariables.setValue:325]  CVUVarConstant : CVU_CHECK_AGAIN
> [main] [ 2018-01-12 13:24:21.725 UTC ] [CVUVariables.getCVUVariable:556]  The variable name : <CVU_CHECK_AGAIN> is not listed
> [main] [ 2018-01-12 13:24:21.725 UTC ] [CVUVariables.setValue:353]  Unable to set value for variable : CVU_CHECK_AGAIN
> [main] [ 2018-01-12 13:24:21.726 UTC ] [CVUVariables.secureVariableValueTrace:711]  getting CVUVariableConstant : VAR = CVU_CHECK_AGAIN VAL = null
> [main] [ 2018-01-12 13:24:21.728 UTC ] [ClusterVerification.checkAvailableMemory:4201]  Method Entry. size=2048 unit=MB
> WARNING: Jan 12, 2018 1:24:21 PM oracle.assistants.common.lib.CVUHelper checkAvailableMemory
> WARNING: Could not check if the alloted memory 2048 is available oracle.cluster.verification.VerificationException: PRVG-11322 : One or more node names "test_env" contain one or more of the following invalid characters "_"

So my first change was not to use as  **container hostname** _test_env_, instead of it use directly _test_, and the DBCA works without any problem.
I think that there will be necessary to put and advice at [README.md](https://github.com/oracle/docker-images/blob/master/OracleDatabase/README.md) file to suggest not using flag **--hostname** including _

**Comment by gvenzl** [comment]
Note to myself: The scripts should validate the host name for invalid characters and prevent the creation of a container with such invalid host name.
