### ISSUE TITLE
Even if database creation fail 11gXE script shows "DATABASE IS READY TO USE!"

### ISSUE THREAD

**Issue by marcelo-ochoa** [oracle/docker-images#715]
If the Database script fail to create a fresh database, for example due to insufficient permissions at _datafile_ directory, startup script shows "DATABASE IS READY TO USE!".
Here tail  of the output:

> #########################
> DATABASE IS READY TO USE!
> #########################
> The following output is now a tail of the alert.log:
> Fri Jan 12 12:40:24 2018
> ALTER DATABASE   MOUNT
> ORA-00210: cannot open the specified control file
> ORA-00202: control file: '/u01/app/oracle/oradata/XE/control.dbf'
> ORA-27037: unable to obtain file status
> Linux-x86_64 Error: 2: No such file or directory
> Additional information: 3
> ORA-205 signalled during: ALTER DATABASE   MOUNT...
> Fri Jan 12 12:40:28 2018
> Checker run found 1 new persistent data failures

also there is no mention at [README.md](https://github.com/oracle/docker-images/blob/master/OracleDatabase/README.md) that, unlike 12c which _datafile_ directory owner should be 54321:54321, in 11g Database image must be 1000:1000.
Best regards, Marcelo.

**Comment by gvenzl** [comment]
Implemented

**Comment by marcelo-ochoa** [comment]
Thanks!!
