### ISSUE TITLE
The size of image is too big

### ISSUE THREAD

**Issue by xiaoyan1985** [oracle/docker-images#728]
I made an image for 12.2.0.1-se, it's size is 13.3G.
Is there any way to reduce the size of the image?

thanks.

**Comment by gvenzl** [comment]
Hi @xiaoyan1985, you can use the `--squash` option to reduce the image size to half. Have a look at https://geraldonit.com/2017/11/13/how-to-create-small-docker-images/

Furthermore, you can also use one of the prebuilt images on container-registry.oracle.com which tend to be smaller but also have less functionality included.

**Comment by clemSeveillac** [comment]
Hi @gvenzl , could you be more specific on those pre-built images? How are they built? What do they miss compared to what we build by default through this github repo?

**Comment by gvenzl** [comment]
Hey @clemSeveillac, the details are documented with the prebuilt images on container-registry.oracle.com

>Caveats
> This docker image has the following restrictions:
>
> 1. This Docker image release supports only single database instance.
> 2. Dataguard feature is not supported.
> 3. It does not support enabling of extra options and patching

Furthermore:

> Oracle Database Server 12.2.0.1 Enterprise Edition Slim Variant.
The slim (12.2.0.1-slim) version of EE does not have support for Analytics, Oracle R, Oracle Label Security, Oracle Text, Oracle Application Express and Oracle DataVault. The commands to run the Oracle Database Server 12.2.0.1 Enterprise Edition Slim variant should use the same commands as above with the slim docker image (denoted in the tag)
