### ISSUE TITLE
Check DB status based on PDB status

### ISSUE THREAD

**Issue by gvenzl** [oracle/docker-images#729]
Today the database health status is checked on instance level rather than PDB level.
However, during setup it doesn't make sense to check on instance level as the instance will be up long before the PDB is ready to use.

--> Change the check to check on PDB status instead.

**Comment by gvenzl** [comment]
Implemented

**Comment by wakko978** [comment]
I recently started using this code base to initiate an Oracle 12.2.0.1 database specifically NOT using PDBs. This change breaks in cases where a PDB is not used.

Steps to create might be a bit much for me to take on, however, I modified dbca.rsp.tmpl as follows:
```
createAsContainerDatabase=false
numberOfPDBs=0
# pdbName=###ORACLE_PDB###
# pdbAdminPassword=###ORACLE_PWD###
```

Starting the container fails:
```
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
```

**Comment by gvenzl** [comment]
See issue #791 for follow up.
