### ISSUE TITLE
oraclelinux:7-slim failing yum update

### ISSUE THREAD

**Issue by g10chy** [oracle/docker-images#735]
Hi,

I am running Docker Engine on Oracle Linux instance in Oracle Cloud that has internet access.
During the Docker Image build, it is erroring as the oracleinux:7-slim is unable to perform yum update.

What could be causing this?

Thanks,
Chris

**Comment by Djelibeybi** [comment]
Can the Oracle Linux host run yum updates successfully? I'm betting that Oracle Cloud has internal mirrors and the Docker image is trying to connect to the external service.

You may need to replace `/etc/yum.repo.s/public-yum-ol7.repo` during your build phase with a copy of the one from the host.

**Comment by g10chy** [comment]
Yes, the Oracle Linux host can run yum updates successfully and the public-yum-ol7.repo is pointing to http://yum.oracle.com

**Comment by Djelibeybi** [comment]
In which case, I would bet it's something to do with name resolution in the Oracle Cloud environment. As you're running an Oracle Linux host, you have full support, so I'd open a support request with the Cloud team for investigation.

**Comment by Djelibeybi** [comment]
What does `/etc/resolv.conf` look like on the host? Docker bind mounts that into a guest, but if it's empty, that would explain things. You may have to provide specific DNS server addresses.

**Comment by g10chy** [comment]
opc@gooch yum.repos.d]$ more /etc/resolv.conf
; Created by cloud-init on instance boot automatically, do not edit.
;
; generated by /usr/sbin/dhclient-script
search goochnetwork.oraclevcn.com sub01261101050.goochnetwork.oraclevcn.com
nameserver 169.254.169.254

**Comment by g10chy** [comment]
And just proving it has connection to the outside world:

```
[opc@gooch yum.repos.d]$ ping www.bbc.co.uk
PING www.bbc.net.uk (212.58.244.67) 56(84) bytes of data.
64 bytes from bbc-vip112.telhc.bbc.co.uk (212.58.244.67): icmp_seq=1 ttl=58 time=10.3 ms
```

**Comment by Djelibeybi** [comment]
`nameserver 169.254.169.254` won't work inside a Docker container, because it's a multicast address and the container is behind NAT. You'll have to override it within the build process before you run the yum command.

**Comment by g10chy** [comment]
Overriding the DNS server in the Docker daemon config resolved the issue.
Thanks Avi for pointing me in the right direction.

**Comment by Djelibeybi** [comment]
Glad it's fixed. I'll also point our Cloud guys at this, so that they can consider doing that automatically perhaps.
