### ISSUE TITLE
repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by maheoasic** [oracle/docker-images#739]
Step 1/13 : FROM oracle/serverjre:8
pull access denied for oracle/serverjre, repository does not exist or may require 'docker login'

Gave my Docker Login, Password, but still getting Above Error.

**Comment by Djelibeybi** [comment]
I'm not sure what image you're trying to build, but you need to build the [`oracle/serverjre:8`](https://github.com/oracle/docker-images/tree/master/OracleJava) image first.

**Comment by Djelibeybi** [comment]
Can you let me know what image you were trying to build so I can make sure the documentation is clear that the Java image needs to be built first?

**Comment by Djelibeybi** [comment]
Closing due to lack of response.

**Comment by amiteshCoder** [comment]
Getting the same error while running "docker run hello-world"

**Comment by Djelibeybi** [comment]
Please do not comment on closed issues. If you're experiencing a problem, please open a new issue and provide the exact steps you're following and the error being generated.
