### ISSUE TITLE
Error in building Docker image for WebLogic

### ISSUE THREAD

**Issue by ElhadiC** [oracle/docker-images#74]
Hi Bruno,

when trying to build fmw12.1.3 dev using the script BuildDockerImage.sh i have the following error: 
error: unpacking of archive failed on file /usr/bin/ping: cpio: cap_set_file
Error unpacking rpm package iputils-20121221-7.el7.x86_6

iputils-20121221-6.el7_1.1.x86_64 was supposed to be removed but is not!

and finally,
Failed:
  iputils.x86_64 0:20121221-6.el7_1.1      iputils.x86_64 0:20121221-7.el7     

Complete!
Removing intermediate container 015ec659d7b6
The command '/bin/sh -c chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     ln -s $(ls -1 /usr/java) /usr/java/default &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file &&     yum -y update && rm -rf /var/cache/yum/*' returned a non-zero code: 1
There was an error building the image.

How to debug these errors or to find out what's wrong ?

Here is my configuration:
OS:ubuntu 14
karnel 3.13.0-24-generic
docker version:
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Best,
H.

**Comment by brunoborges** [comment]
Just built it here and worked fine. I did on Docker 1.10 + Ubuntu 15.10

**Comment by Djelibeybi** [comment]
If you're using `aufs`, you might want to try either `btrfs` or `overlayfs` instead. There are some issues with various VFS layers in Docker.
