### ISSUE TITLE
WCS: Need to create `wcs-wls-docker-install.jar` before running `buildDockerImage.sh`

### ISSUE THREAD

**Issue by Makopo** [oracle/docker-images#741]
Since the build script doesn't have `mvn` command at all, I believe you will need to run following commands before launching `buildDockerImage.sh`.

```
cd ../docker-images-master/OracleWebCenterSites/dockerfiles/12.2.1.3/wcs-wls-docker-install/
mvn package
cp target/wcs-wls-docker-install.jar .
```

Otherwise, the following errors will appear in docker log when docker run WCSitesAdminContainer container.

```
Error: Unable to access jarfile wcs-wls-docker-install.jar
```

**Comment by Djelibeybi** [comment]
@ashishchalak you should build the `wcs-wls-docker-install.jar` either during build or on first launch of the container. You should update the `Dockerfile` accordingly.

**Comment by ashishchalak** [comment]
This is fixed. Can we please close this.

**Comment by Makopo** [comment]
Thank you.
