### ISSUE TITLE
WCS: An extra slash on DB_CONNECTSTRING format

### ISSUE THREAD

**Issue by Makopo** [oracle/docker-images#742]
README.md says like that and I confirmed it works:

> This is the Database connection string:
> DB_CONNECTSTRING=<hostname/containername>:1521/ORCLPDB1.localdomain

Though `wcsitesadminserver.env.list`has following format with an extra `/`:

https://github.com/oracle/docker-images/blob/24d81205939961f330028f1b6f78d675d53851d4/OracleWebCenterSites/dockerfiles/wcsitesadminserver.env.list#L11

**Comment by Djelibeybi** [comment]
@ashishchalak this looks like something you should fix.

**Comment by ashishchalak** [comment]
This is fixed. Can we please close this issue.

**Comment by Makopo** [comment]
Thank you.
