### ISSUE TITLE
devmapper: input/output error while building Database 12.1.0.2 image

### ISSUE THREAD

**Issue by abhishektripathydba** [oracle/docker-images#747]
I am using the following command to build the database image .

./buildDockerImage.sh -v 12.1.0.2 -e

However it is failing with the following error .

```
Step 4/17 : ENV INSTALL_DIR $ORACLE_BASE/install PATH $ORACLE_HOME/bin:$ORACLE_HOME/OPatch/:/usr/sbin:$PATH LD_LIBRARY_PATH $ORACLE_HOME/lib:/usr/lib CLASSPATH $ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib
 ---> Running in f19c5fc4a6ec
 ---> 3fed2f7d7458
Removing intermediate container f19c5fc4a6ec
Step 5/17 : COPY $INSTALL_FILE_1 $INSTALL_FILE_2 $INSTALL_RSP $PERL_INSTALL_FILE $SETUP_LINUX_FILE $CHECK_SPACE_FILE $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
Removing intermediate container f6a053631abd
devmapper: Error mounting '/dev/mapper/docker-253:3-6292555-d8a22e7866427d7232a3ab403380a6de78d8d898ecc59e79628d8740b1871be5' on '/var/lib/docker/devicemapper/mnt/d8a22e7866427d7232a3ab403380a6de78d8d898ecc59e79628d8740b1871be5': input/output error

ERROR: Oracle Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.
```

**Comment by gvenzl** [comment]
Hi @abhishektripathydba, you are facing a Docker internal error:

`devmapper: Error mounting '/dev/mapper/docker-253:3-6292555-d8a22e7866427d7232a3ab403380a6de78d8d898ecc59e79628d8740b1871be5' on '/var/lib/docker/devicemapper/mnt/d8a22e7866427d7232a3ab403380a6de78d8d898ecc59e79628d8740b1871be5': input/output error`

Can you please share your `docker info` with us?

**Comment by abhishektripathydba** [comment]
{/home/oracle}: docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 32
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:3-6292555-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 793.9MB
 Data Space Total: 107.4GB
 Data Space Available: 2.753GB
 Metadata Space Used: 1.589MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.146GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 62.72GiB
Name: orf-elk-15
ID: MXQY:AMDM:CHCN:NH2N:SOWY:LCA6:BQEL:GF23:Q2PK:BWP7:2NPM:MLGH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://webproxy.int.westgroup.com:80/
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by gvenzl** [comment]
Hm, nothing that looks out of the ordinary. @Djelibeybi, do you spot anything that could be the reason for this issue?

**Comment by Djelibeybi** [comment]
I don't see anything obvious either, but this is a Docker issue on RHEL, so I suggest you contact either Docker or Red Hat for further support unless you can reproduce the issue on Oracle Linux 7 running our build of `docker-engine` from the `ol7_addons` repository.
