### ISSUE TITLE
which version of installer we need oracle Database

### ISSUE THREAD

**Issue by josselinchevalay** [oracle/docker-images#749]
Hello all, 

In Oracle database documentation you specify to need a binaries of installer in same directory of your Dockerfile. I have question which version of your installer you need to that with Activation or without ? 

Regards

**Comment by gvenzl** [comment]
Hi @josselinchevalay, assuming that you are referring to the Oracle Database Docker image, please have a look at the [ReadMe](https://github.com/oracle/docker-images/tree/master/OracleDatabase#building-oracle-database-docker-install-images).

**Comment by josselinchevalay** [comment]
thx it's works 👍
