### ISSUE TITLE
would you please publish OracleJDK docker image on hub.docker.com

### ISSUE THREAD

**Issue by netroby** [oracle/docker-images#75]
https://hub.docker.com/r/oracle/

would you please publish OracleJDK docker image on hub.docker.com

**Comment by Djelibeybi** [comment]
Product licensing prevents us from publishing the JDK binaries. This is not possible.

**Comment by netroby** [comment]
You are Oracle , right? Oracle JDK was your self product.
Why not you limit your self publish your self product?
Any way to ask your CEO or CTO to make some change ?
Today the cloud will be more and more popular, why not prevent us using your products?

**Comment by ivankrylov** [comment]
You can check out openjdk builds in Docker.
This one  is from the company I work for:
https://hub.docker.com/r/azul/zulu-openjdk/

**Comment by brunoborges** [comment]
OpenJDK builds with Oracle Linux are also provided: https://hub.docker.com/r/oracle/openjdk/
