### ISSUE TITLE
tfactl does not work in Oracle Database Docker container

### ISSUE THREAD

**Issue by davelindquist-egistix** [oracle/docker-images#751]
Running Oracle in a docker container (with the scripts in this issue) works great, but unfortunately the TFA tool does not work, apparently because perl is not installed in the container:

```
$ docker exec -it oracle_database /bin/bash
[oracle@71a0f99ecc9a oracle]$ tfactl diagcollect -srdc ora600
tfactl: line 97: perl: command not found
tfactl: tfactl.pl: /usr/bin/perl: bad interpreter: No such file or directory
```

Since this tool is the Oracle-recommended way to report details for ORA-600 errors, can we have the image updated to include perl and any other necessary tools for running tfactl?

**Comment by gvenzl** [comment]
@davelindquist-egistix, perl is shipped as part of the Oracle installation itself. You just have to set the `PATH` accordingly: 

```
[oracle@0b3c4e9cd1af ~]$ /opt/oracle/product/12.2.0.1/dbhome_1/perl/bin/perl -v

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

[oracle@0b3c4e9cd1af ~]$ export PATH=/opt/oracle/product/12.2.0.1/dbhome_1/perl/bin:$PATH
[oracle@0b3c4e9cd1af ~]$ perl -v

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

That being said, you should never, ever go into the container directly. The method above for example won't work when your container is running somewhere in a huge K8s cluster for example. What you should rather do is to expose the `diag` directory into a volume and then run `tfactl` against the trace files within at volume.

**Comment by davelindquist-egistix** [comment]
Ah, I see -- it never occurred to me that it wouldn't be pathed in the normal location.  Sorry about that!

I hadn't thought about exposing the diag directory as a volume -- so ``tfactl`` does not require Oracle libraries/etc in order to run?  It's just a simple perl utility?  That's a good tip, thanks!

Since it looks like I have two ways to do tfactl successfully, I'll close this issue.

Thanks again!
