### ISSUE TITLE
Password for 'oracle' user created  

### ISSUE THREAD

**Issue by Rssingh3** [oracle/docker-images#753]
Hi all,

I need password for default oracle user created for OrcaleJava Docker image. Can anyone suggest how can I find that ?

**Comment by Djelibeybi** [comment]
There isn't one. Why do you think you need it?

**Comment by Djelibeybi** [comment]
There is no `oracle` user in the Oracle Java image.

**Comment by gvenzl** [comment]
The question really is: Why do you need the `oracle` user password to begin with, @Rssingh3? What is it that you are trying to do?

**Comment by Rssingh3** [comment]
I just wanted to login in winscp so that I can see all the files. This will make my life lot easier. And, I can see that user is oracle when we are inside the container. So, user 'oracle' must have a password.

**Comment by gvenzl** [comment]
Hi @Rssingh3, now I see. Indeed debugging or just seeing what's going on inside a container is rather cumbersome. This is why Oracle for example also provides projects like [Crashcart](https://github.com/oracle/crashcart).
Furthermore, note that Unix users don't necessarily have to have passwords. In such way you for example can prevent logon with a given user while still having the user running some binaries. A common example would be the `apache` user for running your webserver.
