### ISSUE TITLE
How can the weblogic path be set in the docker container?

### ISSUE THREAD

**Issue by edwint88** [oracle/docker-images#758]
Is there a way to set the weblogic classpath in the docker container? I've tried to enter into the container and change the env variable WEBLOGIC_CLASSPATH and then restart the docker container and then it was reseted to default.

If I try to stop the weblogic from the inside the container I get this error:

````
[oracle@wlsadmin base_domain]$ sh bin/stopWebLogic.sh
Stopping Weblogic Server...

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Connecting to t3://e62eff83579f:7001 with userid weblogic ...
This Exception occurred at Thu Feb 15 16:14:03 GMT 2018.
javax.naming.ServiceUnavailableException: e62eff83579f: Temporary failure in name resolution [Root exception is java.net.UnknownHostException: e62eff83579f: Temporary failure in name resolution]
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/user_projects/domains/base_domain/shutdown-WL_AdminServer.py", line 3, in ?
  File "<iostream>", line 19, in connect
  File "<iostream>", line 553, in raiseWLSTException
WLSTException: Error occurred while performing connect : e62eff83579f: Temporary failure in name resolution
Use dumpStack() to view the full stacktrace :

Done
Stopping Derby Server...
Derby server stopped.
````

So this is also no option for me (to stop and start again).

What can I do more is maybe to run the docker with a command like [here](https://stackoverflow.com/a/37292526/1595977)

Did I miss something in the READ.me of how this is done?

**Comment by mriccell** [comment]
Sorry what WebLogic image (version) are you trying to create?

**Comment by edwint88** [comment]
The version is 12.2.1. In the docker container the stop Weblogic script doesn't stops the server, this is another problem that I have with the image.

Extra info:
`
[
    {
        "Id": "844efc6e1c4c8d0213bb12a775d1ed15b0e01beaa3dc0d1730b388d37ba9ce71",
        "Created": "2018-02-16T14:17:24.9994176Z",
        "Path": "startWebLogic.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 70889,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-02-16T14:17:26.1713871Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:c7360991aaa49fc4322677a936568478a641346dfe42a18f27a1de59f035d819",
        "ResolvConfPath": "/var/lib/docker/containers/844efc6e1c4c8d0213bb12a775d1ed15b0e01beaa3dc0d1730b388d37ba9ce71/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/844efc6e1c4c8d0213bb12a775d1ed15b0e01beaa3dc0d1730b388d37ba9ce71/hostname",
        "HostsPath": "/var/lib/docker/containers/844efc6e1c4c8d0213bb12a775d1ed15b0e01beaa3dc0d1730b388d37ba9ce71/hosts",
        "LogPath": "/var/lib/docker/containers/844efc6e1c4c8d0213bb12a775d1ed15b0e01beaa3dc0d1730b388d37ba9ce71/844efc6e1c4c8d0213bb12a775d1ed15b0e01beaa3dc0d1730b388d37ba9ce71-json.log",
        "Name": "/wlsadmin",
        "RestartCount": 0,
        "Driver": "overlay2",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "test:/u01/oracle/oracle_common/modules/test"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "7001/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7001"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                59,
                208
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "overlay2",
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/9afe9b275f97f10c3b2533209e0a4c894d9fa8e07ffba3abe6311a6325e94bd1-init/diff:/var/lib/docker/overlay2/de0823fa7fd38a7cdc7e6f23ac3eac23787ba68765d4740f1ca4323e757a38ac/diff:/var/lib/docker/overlay2/b8ed08dbe71aeb62a17bd49cb6ff8f465800697c375e4a4dbdeb5534dc308d91/diff:/var/lib/docker/overlay2/fd1225bb7e5eadb5bc9de1bc0d8f6f7a8bb273296bc114aab071402beaceed36/diff:/var/lib/docker/overlay2/f6a98bcd88b82f6bbebbf31a2971e6a43d50e08d8ca20a7b06ae46d6ceb1718a/diff:/var/lib/docker/overlay2/61815f39afe1a0e3954d408769d67fe1411c3431d35435ac81635a4eb1d1389f/diff:/var/lib/docker/overlay2/44dd892043e95b8084a6617ecd7d4b5a3e44d30d42ffda79549c690887c71a63/diff:/var/lib/docker/overlay2/c7ef870ed40bb4077a9a8942570784d95f76b44fe767b7eb76c3f05c8cd6d7c2/diff:/var/lib/docker/overlay2/3d69c34a2d6a86bbb897159b4ac3f9fc4ca222caed87241bb3975557dfdb5d62/diff:/var/lib/docker/overlay2/771f2014f61aed269f85fee1ee497d7de613dd64ab114ae1aad17812505fefde/diff:/var/lib/docker/overlay2/6a756d518defef890440302248b7cae3eadeb6261def360451d2007bb0fcfcf5/diff",
                "MergedDir": "/var/lib/docker/overlay2/9afe9b275f97f10c3b2533209e0a4c894d9fa8e07ffba3abe6311a6325e94bd1/merged",
                "UpperDir": "/var/lib/docker/overlay2/9afe9b275f97f10c3b2533209e0a4c894d9fa8e07ffba3abe6311a6325e94bd1/diff",
                "WorkDir": "/var/lib/docker/overlay2/9afe9b275f97f10c3b2533209e0a4c894d9fa8e07ffba3abe6311a6325e94bd1/work"
            }
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "test",
                "Source": "/var/lib/docker/volumes/test/_data",
                "Destination": "/u01/oracle/oracle_common/modules/test",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "wlsadmin",
            "Domainname": "",
            "User": "oracle",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5556/tcp": {},
                "7001/tcp": {},
                "7002/tcp": {},
                "8453/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/user_projects/domains/base_domain/bin:/u01/oracle",
                "JAVA_PKG=server-jre-8u*-linux-x64.tar.gz",
                "JAVA_HOME=/usr/java/default",
                "ORACLE_HOME=/u01/oracle",
                "USER_MEM_ARGS=-Djava.security.egd=file:/dev/./urandom",
                "FMW_PKG=fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip",
                "FMW_JAR=fmw_12.2.1.0.0_wls_quick.jar",
                "DEBUG_FLAG=true",
                "PRODUCTION_MODE=dev",
                "ADMIN_HOST=wlsadmin",
                "NM_PORT=5556",
                "MS_PORT=7002",
                "DEBUG_PORT=8453",
                "CONFIG_JVM_ARGS=-Dweblogic.security.SSL.ignoreHostnameVerification=true",
                "DOMAIN_NAME=base_domain",
                "DOMAIN_HOME=/u01/oracle/user_projects/domains/base_domain",
                "ADMIN_NAME=WL_AdminServer",
                "ADMIN_PORT=7001",
                "CLUSTER_NAME=DockerCluster",
                "debugFlag=true",
                
            ],
            "Cmd": [
                "startWebLogic.sh"
            ],
            "ArgsEscaped": true,
            "Image": "1221-domain",
            "Volumes": null,
            "WorkingDir": "/u01/oracle/user_projects/domains/base_domain",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "58fe9c8c80c7a637792624fb23a07c9477ce6e8884ffd2f89853a1f4e35390a7",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5556/tcp": null,
                "7001/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7001"
                    }
                ],
                "7002/tcp": null,
                "8453/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/58fe9c8c80c7",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "eb7da74f410af82e8ef5715f4fd24e7d45714012e2ad34917e33bca07d0399b0",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "2c20dad3ed681e16f32411da172b5c9363f5f77a5a322071d241ba4e3174c96e",
                    "EndpointID": "eb7da74f410af82e8ef5715f4fd24e7d45714012e2ad34917e33bca07d0399b0",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]

`

**Comment by mriccell** [comment]
This is because the domain and all the settings are created at image build time.  If you follow the model of the 12.2.1.2 or 12.2.1.3 domain where the domain is created at runtime (docker run) you can change any of the ENV variables before the domain is created and the servers are ran.

**Comment by edwint88** [comment]
I understand, then the only solution is to change the dockerfile if I want to use this version. But the other problem remains: When I try to restart the weblogic server from the scripts, that are inside the container, I get that error (stopWebLogic.sh).

**Comment by mriccell** [comment]
Are you referring still to the 12.2.1 image?  In 12.2.1.3 since the domain home and the env is created at run time of the container you have the opportunity to set any env var like PATH in the Dockerfile and that env is set in all scripts that run the weblogic servers.  In the case of 12.2.1 the domain is created when you build the image and the env is set in all scripts at the build time of the image and you can not make any changes post build time (example in the running container).
In Docker you should not be bashing into the container and running scripts to start WebLogic servers.

**Comment by mriccell** [comment]
Thank you for your suggestion I will add  the CLASSPATH as an ENV to the Dockerfile.
