### ISSUE TITLE
Providing Oracle JDK Docker images on Dockerhub

### ISSUE THREAD

**Issue by ioft** [oracle/docker-images#76]
Dear Oracle Team,

the OpenHAB team is currently [discussing](https://github.com/openhab/openhab-docker/pull/1) the possibility to provide OpenHAB as a Docker image in order to support a wide range of devices. Unfortunately using OpenJDK still has some disadvantages compared to the OracleJDK, so I'd like to know if there is any chance to use the Oracle JDK in combination with OpenHAB without getting in conflict with Oracle`s licensing terms & conditions. I believe the smartest way to do this is using a Docker Java image provided by Oracle itself.

Any Ideas?

**Comment by Djelibeybi** [comment]
Our legal team have advised that the Oracle JDK license does not permit us to ship the JDK as a container at this time. Therefore, we will not be shipping a complete container.

However, we do provide a Dockerfile that can be used to build your own Oracle JDK container and assuming you meet the terms and conditions of the JDK distribution license (as determined by your own legal team), that should be fine.

**Comment by Djelibeybi** [comment]
Sample Dockerfiles for Oracle JDK here: https://github.com/oracle/docker-images/tree/master/OracleJDK

**Comment by ioft** [comment]
But you are Oracle, aren't you?

BTW: The Dockerfile you are providing doesn't work on ARM / ARM64 and many other architectures≠x64

**Comment by Djelibeybi** [comment]
We are Oracle, yes. But the distribution license for the JDK only permits distribution with a Java application. Distributing the JDK by itself is not permitted. Therefore a container with only the JDK and no application is not permitted, but a container with the JDK+application is (probably) fine.

However, I am not a lawyer and I'm paraphrasing the advice I was given by our legal team. You should seek your own legal advice for shipping the Oracle JDK with your application.

Note that Oracle Linux is not supported on non-Intel hardware, so it's not surprising the Dockerfile doesn't work on ARM/ARM64. You'll have to use a different base image anyway, as we have no plans to release non-Intel Dockerfiles, i.e. Dockerfiles that don't use Oracle Linux as the base userspace.

**Comment by cyberkov** [comment]
Hello @Djelibeybi and thank you for the clarification. If I understand it correctly, it would be ok to put the Oracle JDK into the same Dockerfile as my Java App (in that case openHAB), but not into it's own layer as this would go against the license?

**Comment by ioft** [comment]
> But the distribution license for the JDK only permits distribution with a Java application. ... but a container with the JDK+application is (probably) fine.

So if we distribute the OrcaleJDK + OpenHAB within one Docker image it should be fine (meaning that it doesn't violate Oracle's licensing T&C)? Which person within your organization might be able to confirm this statement? The OpenHAB project is driven by volunteers (mostly engineers but not lawyers).

**Comment by Djelibeybi** [comment]
Oracle does not provide legal advice to projects, unfortunately. You might be able to get a statement from the Java Product team via the Java forums/mailing lists though.

**Comment by brunoborges** [comment]
@ioft, @cyberkov, if you know a JUG, ask your JUG Leader about this matter. He has the right communication channel with the Java Product team.

**Comment by kaikreuzer** [comment]
> as we have no plans to release non-Intel Dockerfiles

This is indeed the biggest issue, since probably 99% of openHAB users are running it on some ARM-based system.
So is the statement "but a container with the JDK+application is (probably) fine" still valid if we would build a Docker image for ARM with JDK+openHAB ourselves or is this a completely different situation so that there is anyhow no chance not to violate the license terms?

**Comment by umiddelb** [comment]
@kaikreuzer Could you get in touch with some JUG leader / representative?

**Comment by kaikreuzer** [comment]
@umiddelb No need, I already directly talked to Donald Smith. But the answer is the same: Oracle does not give any legal advice...

**Comment by mattnelson** [comment]
Sorry for bouncing an old issue, but I wanted to restart the conversion within the context of the previous discussions.

Now that Oracle OpenJDK is licensed with NFTC, can this discussion be revisited to start distributing 17+ images?

https://blogs.oracle.com/java/post/free-java-license
https://www.oracle.com/downloads/licenses/no-fee-license.html
