### ISSUE TITLE
OracleDatabase 12.2.0.1 Step 11/17 /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory

### ISSUE THREAD

**Issue by fernandohackbart** [oracle/docker-images#762]
During the execution of the creation of the image...
```
Step 11/17 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in 4b23ea786280
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
```

Full output...
[output.txt](https://github.com/oracle/docker-images/files/1733578/output.txt)

**Comment by fernandohackbart** [comment]
Thx, checking...

**Comment by fernandohackbart** [comment]
Fixed with bigger disk space, thank you

**Comment by nadamien** [comment]
I am running a docker build on a bitbucket pipeline, I am getting the same issue I have enough space 

Filesystem      Size  Used Avail Use% Mounted on
overlay         274G   99G  162G  38% /

Step 32/36 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh
 ---> Running in a1e670cd8a0e
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh' returned a non-zero code: 127
2022-09-09T05:40:18.820345879Z stdout P

**Comment by Dinmukhamet** [comment]
any updates?
