### ISSUE TITLE
Pull Access denied for oracle/weblogic 

### ISSUE THREAD

**Issue by karan-kapoor90** [oracle/docker-images#763]
Hi

Getting the following error when I try to pull

`
docker build --build-arg ADMIN_PASS=welcome1 --build-arg ADMIN_USER=weblogic -t wls-12213-domain .
Sending build context to Docker daemon   1.86MB
Step 1/12 : FROM oracle/weblogic:12.2.1.3-developer
pull access denied for oracle/weblogic, repository does not exist or may require 'docker login'
`
I've accepted the license agreements for pulling images from the container-registry and last time I modified the Dockerfile to pick from the Container registry as well.. so 2 things:

1. How and where do I login for access to the oracle repo so i can pull oracle/weblogic?
2. Is it alright to change the Dockerfile image URL to pull from container-registry.oracle.com or is there anything specific in the oracle/weblogic image that's needed for this?

**Comment by mriccell** [comment]
To pull the image from the oracle container registry you must go to your browser and enter URL https://container-registry.oracle.com sign in, accept license, Note that acceptance of the license agreement is required to download images using the Docker command-line tool and that acceptance only persists for eight hours.
Navigate to middleware->weblogic
From your command window
docker login container-registry.oracle.com
docker pull container-registry.oracle.com/middleware/weblogic:12.2.1.3 (look at tags for available images)

**Comment by mriccell** [comment]
@karan-kapoor90 are you still having problems?

**Comment by mriccell** [comment]
@Djelibeybi can you close this issue

**Comment by karan-kapoor90** [comment]
Apologies for not responding. The dockerfile says 
`FROM oracle/weblogic.....`
whereas it should be 
'container-registry.oracle.com/weblogic...`

That's what I meant.

**Comment by Djelibeybi** [comment]
@karan-kapoor90 the files on GitHub expect you to build all the images in the hierarchy. In this case, you first need to build the [Server JRE 8](https://github.com/oracle/docker-images/tree/master/OracleJava/java-8) image as `oracle/serverjre:8` then you can build the WebLogic image.

**Comment by czar82** [comment]
@mriccell For the version 12.1.3? It's not on https://container-registry.oracle.com
Running this: docker build -t samplewls:12.1.3-domain --build-arg ADMIN_PASSWORD=welcome1 .
I get the same error of @karan-kapoor90 

And this:
 `docker pull container-registry.oracle.com/middleware/weblogic:12.1.3`
Error response from daemon: manifest for container-registry.oracle.com/middleware/weblogic:12.1.3 not found

**Comment by Folcky** [comment]
> @mriccell @Djelibeybi For the version 12.1.3? It's not on https://container-registry.oracle.com
> Running this: `docker build -t samplewls:12.1.3-domain --build-arg ADMIN_PASSWORD=welcome1 .`
> or this: `docker build -t 1213-domain --build-arg ADMIN_PASSWORD=welcome1 .`
> I get the same error of @karan-kapoor90
> 
> And the docker login is fine:
> `docker login container-registry.oracle.com`
> But this give me error (I suppose because 12.1.3 doesn't exist):
> `docker pull container-registry.oracle.com/middleware/weblogic:12.1.3`
> Error response from daemon: manifest for container-registry.oracle.com/middleware/weblogic:12.1.3 not found
> 
> How can I build the sample for 12.1.3?

Type 12.2.1.3 or latest instead of 12.1.3

12.1.3 is realyy does not exist

**Comment by Djelibeybi** [comment]
The 12.1.3 image was removed from the Oracle Container Registry due to a security vulnerability.

Ping @mriccell to determine what to do with the samples.

**Comment by mriccell** [comment]
The image that we pulled from container registry were 12.2.1.1 and 12.2.1.2, the 12.1.3 has never been in the container registry.  For now you need to manually create the image using the files in GitHub https://github.com/oracle/docker-images/tree/master/OracleWebLogic/dockerfiles/12.1.3.  
Since 12.1.3 is still a supported release of WebLogic (extended support ends in Dec 2019) I will work to fix the image (JDK 8 only) and post it to the Oracle Container Registry.
Is there a reason why you would not use the 12.2.1.3 image?
Thanks
Monica

**Comment by czar82** [comment]
Just because in my company somebody decided that all must use this version. So no valid reason at all :D

**Comment by mriccell** [comment]
Maybe you should suggest that you should develop on WebLogic 12.2.1.3 since 12.1.3 will not be supported for much longer.  WebLogic 12.2.1.3 is the latest version of WLS and is rich in features that make it easier to containerize WLS application and manage them in a orchestration framework.

**Comment by sandeepm152** [comment]
Hi Monica,

I'm trying to deploy an ADF application into Weblogic Docker container. I'm able to run Standalone WebLogic Docker container. However, it does not have any ADF libraries. I have tried to run fmw-middleware docker. But it requires RCU to be setup.

Can you please let me know me how I can have a WebLogic Docker Container with JRF/ ADF Runtime libraries installed?

Thanks
Sandeep

**Comment by ankushgarg28794** [comment]
Hi Mricell,

I am getting the below error, while using oracle weblogic 12.2.1.3. Please help me for the below error. As i am using the latest version of weblogic still facing the issues.

[root@localhost 1213-domain]# docker build -t 1223-domain --build-arg ADMIN_PASSWORD=welcome1 .
Sending build context to Docker daemon 52.74 kB
Step 1/13 : FROM oracle/weblogic:12.1.3-developer
Trying to pull repository docker.io/oracle/weblogic ...
**repository docker.io/oracle/weblogic not found: does not exist or no pull access**
[root@localhost 1213-domain]#

Thanks in advance....

**Comment by mriccell** [comment]
The sample to build the WebLogic domain image extends the WebLogic 12.2.1.3 intall/binary image you have pre-built under  https://github.com/oracle/docker-images/tree/master/OracleWebLogic/dockerfiles/12.2.1.3.  You could pull one of the pre-built images of WebLogic from Container Registry https://container-registry.oracle.com called container-registry.oracle.com/middleware/weblogic:12.2.1.3.  In the case you pull a prebuilt image of WebLogic then yuou must change the FROM clause in the Dockerfile to be "FROM container-registry.oracle.com/middleware/weblogic:12.2.1.3"

**Comment by mriccell** [comment]
Please take a look at the README in the 12213-domain sample
"A prerequisite to building the 12213-weblogic-domain-in-volume image is having an Oracle WebLogic 12.2.1.3 install image. The Dockerfile and scripts to build the image are under the folder, ../../OracleWebLogic/dockerfile/12.2.1.3. For more information, see the README file."

**Comment by mriccell** [comment]
@sandeepm152 please follow the sample https://github.com/oracle/docker-images/tree/master/OracleFMWInfrastructure/samples/12213-domain-in-volume.  This sample requires you construct the  FMW Infrastructure install/binary image first.  The README indicates
"A prerequisite to building the 12213-domain-in-volume image is having an Oracle Fusion Middleware Infrastructure 12.2.1.3 binary image. The Dockerfile and scripts to build the image are under the folder, ../../OracleFMWInfrastructure/dockerfile/12.2.1.3. For more information, see the README file."
There is also a pre-built image in Oracle Container Registry.

**Comment by ankushgarg28794** [comment]
Hi Mricell,

Now I am facing the below error. I did the login also to container registry.

[root@localhost 12213-domain]# docker build -t 12213-domain --build-arg ADMIN_PASSWORD=welcome1 --build-arg DOMAIN_NAME=developer_domain .
Sending build context to Docker daemon 113.2 kB
Step 1/10 : FROM container-registry.oracle.com/middleware/weblogic:12.2.1.3
Trying to pull repository container-registry.oracle.com/middleware/weblogic ...
repository container-registry.oracle.com/middleware/weblogic not found: does not exist or no pull access
[root@localhost 12213-domain]#


Thanks in adavance

**Comment by mriccell** [comment]
You need to register credentials and accept licenseon Oracle Container Registry see documentation https://docs.oracle.com/cd/E37670_01/E75728/html/oracle-registry-server.html

**Comment by mriccell** [comment]
You need to pull the image first
docker login container-registry.oracle.com
docker pull container-registry.oracle.com/middleware/weblogic:12.2.1.3

**Comment by ankushgarg28794** [comment]
Thanks for your precious support, but still i am not able to figure out the solution:-

After the successful login i am getting the below error. Kindly help:-

[root@localhost 12213-domain]# docker pull container-registry.oracle.com/middleware/weblogic:12.2.1.3-dev
Trying to pull repository container-registry.oracle.com/middleware/weblogic ...
repository container-registry.oracle.com/middleware/weblogic not found: does not exist or no pull access
[root@localhost 12213-domain]# docker pull container-registry.oracle.com/middleware/weblogic:12.2.1.3
Trying to pull repository container-registry.oracle.com/middleware/weblogic ...
repository container-registry.oracle.com/middleware/weblogic not found: does not exist or no pull access
[root@localhost 12213-domain]#

**Comment by ankushgarg28794** [comment]
Do i need any pull access on my credentials or its something else.

**Comment by mriccell** [comment]
Can you log on to the Container Registry from your browser?  Try navigating to the middleware/weblogic and at the end you should see all the tags.

**Comment by mriccell** [comment]
If you register your credentials and accept the license to pull the image then from the command line do the docker login, docker pull you should be able to pull the image.

**Comment by ankushgarg28794** [comment]
![Capture](https://user-images.githubusercontent.com/51917060/60046253-8172b900-96e4-11e9-91f9-4ab06c6b87e9.PNG)
I am able to navigate via browser but can you please share me the command to accept the license .

**Comment by mriccell** [comment]
See if these instructions help you https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-in-image/base-images/#creating-or-obtaining-weblogic-docker-images

**Comment by ankushgarg28794** [comment]
Hi Mriccell,

I am not able to proceed with the steps suggested by you. Kindly provide me any way out to resolve my problem.
Here I am able to login into container registry via both command line and browser , but i am getting the below error after sucessful login.

 **repository container-registry.oracle.com/middleware/weblogic not found: does not exist or no pull access**

Or can you please provide place the image on github itself for oracle weblogic -12.2.1.3.  


Thanks in advance.

**Comment by mriccell** [comment]
Are you adding the correct tag to the image?  docker pull container-registry.oracle.com/middleware/weblogic:12.2.1.3
Sorry I can not place the image on github itself.  It must be that either you are not adding the tag to the pull command.

**Comment by mriccell** [comment]
This image container-registry.oracle.com/middleware/weblogic without tag is the same as container-registry.oracle.com/middleware/weblogic:latest which does not exist in Oracle Container Registry

**Comment by ankushgarg28794** [comment]
@mriccell I have the below images created for running weblogic server. Please help me for the below error. As i completely stuck with the installation of weblogic server.

[root@localhost 12213-domain]# docker images
REPOSITORY                        TAG                  IMAGE ID            CREATED             SIZE
**12213-weblogic-domain-in-volume   latest               8a58cb28fe10        41 minutes ago      1.42GB
oracle/weblogic                   12.2.1.3-developer   ceb0b3392320        44 minutes ago      1.42GB
oracle/serverjre                  8                    ab3a09742865        About an hour ago   270MB**
oraclelinux                       7-slim               d94f4e9e5c13        24 hours ago        118MB
hello-world                       latest               fce289e99eb9        5 months ago        1.84kB

While i am running the below command to run image as container,

**docker run -d --name wlsadmin --hostname wlsadmin -p 7001:7001 -e ADMIN_PASSWORD=welcome1 12213-weblogic-domain-in-volume**

Getting below error, can you please suggest for the below error.

[root@localhost 12213-domain]# docker logs 15f61fdcac4d204a855f0519bc2e2276dc3962644e791377aff23a6398512491

**Domain Home is:  /u01/oracle/user_projects/domains/base_domain
/u01/oracle/properties/domain_security.properties
A properties file with the username and password needs to be supplied.**

Can you please edit the below command to avoid above error.

**docker run -d --name wlsadmin --hostname wlsadmin -p 7001:7001 -e ADMIN_PASSWORD=welcome1 12213-weblogic-domain-in-volume**

Thanks in advance...

**Comment by mriccell** [comment]
Please take a look at the README file https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain/README.md, the admin user and password need to be supplied via a properties file.  I also have provided a couple of run scripts run_admin_server.sh and run_managed_server.sh as an example in addition to facilitate the setting of the different environment variables to define things such as domain name, server names, cluster type etc.

**Comment by ankushgarg28794** [comment]
Thanks Mricell for the help, I have run the below command and now i am able to start weblogic in docker container:--

docker run -d --name wlsadmin --hostname wlsadmin -p 7001:7001 -e ADMIN_PASSWORD=welcome1 -v /home/parent/oracle/docker-images/OracleWebLogic/samples/12213-domain/properties:/u01/oracle/user_projects 12213-weblogic-domain-in-volume

docker ps

CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                              NAMES

c73276964f12        12213-weblogic-domain-in-volume   "/u01/oracle/contain…"   9 days ago          Up 11 hours         0.0.0.0:7001->7001/tcp             wlsadmin

Now i have created weblogic jms queues and and deploy a java war file inside the weblogic console and i am committing the changes for the particular docker container. but my changes are not getting reflected into the newely created image. Can you please help on this.Please find the below commands.

docker commit c73276964f12   mynewcodeweblogic1

I have got the docker image with *mynewcodeweblogic1* . And when i run the new image ,i didn't find the changes in new weblogic. Getting plain weblogic only.

Thanks in advance.....

**Comment by ankushgarg28794** [comment]
Hi Mricell,

Could you please help me for the below query.

Can I commit the changes done in docker weblogic running container as a new image.  Here when i run the below command. I have got the new images of plain weblogic but i didn't find the changes in the new container.

docker container commit c73276964f12 myweblogic1

Thanks in advance....

**Comment by ssarraju** [comment]
> To pull the image from the oracle container registry you must go to your browser and enter URL https://container-registry.oracle.com sign in, accept license, Note that acceptance of the license agreement is required to download images using the Docker command-line tool and that acceptance only persists for eight hours.
> Navigate to middleware->weblogic
> From your command window
> docker login container-registry.oracle.com
> docker pull container-registry.oracle.com/middleware/weblogic:12.2.1.3 (look at tags for available images)

This solved the issue but appreciate if you fix the error message to suggest the same. Without the help of google and this issue, no way we can guess that the repo doesn't exist error is coming due to not accepting the agreement.
