### ISSUE TITLE
Different version of java.mail.jar in 12.2.1.2

### ISSUE THREAD

**Issue by winster** [oracle/docker-images#765]
In the documentation of 12.2.1.2 and 12.2.1, its given that weblogic uses 1.4 version of java.mail API whereas after the domain is built, com.sun.mail.javax.mail.jar in oracle_common/modules is having 1.5.6.
Replacing with older version throws following error. 
Caused By: java.lang.ClassNotFoundException: javax.mail.MailSessionDefinition

Above class is available only 1.5 onwards. Is there any way to use 1.4.x version?

**Comment by mriccell** [comment]
@winster I think this a documentation bug, WebLogic 12.2.1.x is Java EE 7 compatible, which means it needs JavaMail 1.5.6.

**Comment by winster** [comment]
Thanks @mriccell  I found a way to set custom java-mail version.
ENV  EXT_PRE_CLASSPATH=/u01/oracle/user_projects/domains/base_domain/libpre/mail-1.4.1.jar

**Comment by mriccell** [comment]
Glad you found a way, I have opened a request to change the documentation.
Thanks for raising the issue.

**Comment by mriccell** [comment]
@winster I worry that you are using a version of Java Mail that is not supported with WLS 12.2.1.x (Java EE 7).

**Comment by mriccell** [comment]
@djelibeybi can you close this issue

**Comment by Djelibeybi** [comment]
Sure.
