### ISSUE TITLE
Error while building OracleDatabase 12.2.0.1 in Alpine: Permission denied on 'runInstaller'

### ISSUE THREAD

**Issue by Outrigger047** [oracle/docker-images#769]
When attempting to build OracleDatabase 12.2.0.1 in Alpine I am getting a 'permission denied' error during step 9 (install DB binaries).

I am calling the build script like this:

```
./buildDockerImage.sh -v 12.2.0.1 -s -i -o --rm=false
```
During step 9, after necessary files are inflated, I get my 'permission denied' error when installDBBinaries.sh runs

```
[91m/opt/oracle/install/installDBBinaries.sh: line 54: /opt/oracle/install/database/runInstaller: Permission denied
[0m ---> 5f47c9d7030e
Step 10/17 : USER root
 ---> Running in 00b9f0f177ca
 ---> 064aa507fa3d
Step 11/17 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in 140eb0e36766
[91m/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
[0m
ERROR: Oracle Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.
```

I have attached my full build log here:
[out.txt](https://github.com/oracle/docker-images/files/1752822/out.txt)

**Comment by gvenzl** [comment]
For some reason the runInstaller file doesn't have the right permissions, probably lack of execute permissions on itself. That should be there by default. Just to avoid red herrings, can you please reexecute this without the `-i` option, not skipping the MD5 checksum, to make sure that the zip file is intact?

**Comment by gvenzl** [comment]
Hi @Outrigger047, if you have more information on whether and/or how you fixed the issue, please post it here for reference for future users.

Thanks!

**Comment by Outrigger047** [comment]
Thanks for replying, @gvenzl. Our team unfortunately doesn't have the bandwidth to commit time to this project at the moment. I may reopen at a later date with more information.

**Comment by gvenzl** [comment]
Thanks for the update, @Outrigger047
