### ISSUE TITLE
cannot run container

### ISSUE THREAD

**Issue by solaMai** [oracle/docker-images#771]
when I run container, I encounter the situation as below:

      ----> 'weblogic' admin password: Password1

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

domain_name     : [base_domain]
admin_port      : [7001]
domain_path     : [/weblogic/oracle/user_projects/domains/base_domain]
production_mode : [prod]
admin password  : [Password1]
admin name      : [AdminServer]
admin username  : [weblogic]

it will hang on that.
I found it hang on 
**readTemplate("/u01/oracle/wlserver/common/templates/wls/wls.jar")**
weblogic version is 12.2.1.2

**Comment by solaMai** [comment]
I use the weblogic version is 12.2.1.2

**Comment by mriccell** [comment]
could you show me the command you are running?

**Comment by mriccell** [comment]
@solaMai are you still experiencing this problem?

**Comment by mriccell** [comment]
@solaMai I am closing this issue due to lack of feedback, please reopen if you are still experiencing the same issue.
