### ISSUE TITLE
Error while building OracleDatabase 12.2.0.1: SEVERE:/etc/oraInst.loc (Permission denied)

### ISSUE THREAD

**Issue by dsendkowski** [oracle/docker-images#773]
I get `PermissionDenied` error while building OracleDatabase 12.2.0.1 in OpenSUSE 42.3:

```
buildDockerImage.sh -s -v 12.2.0.1
```

```
Checking Temp space: must be greater than 500 MB.   Actual 2556786 MB    Passed
Checking swap space: must be greater than 150 MB.   Actual 65362 MB    Passed
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2018-02-28_10-15-14PM. Please wait ...[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
SEVERE:/etc/oraInst.loc (Permission denied)
[FATAL] 
A log of this session is currently saved as: /tmp/OraInstall2018-02-28_10-15-14PM/installActions2018-02-28_10-15-14PM.log. Oracle recommends that if you want to keep this log, you should move it from the temporary location.
 ---> b01139f5a193
Removing intermediate container 0fd2f8b370f1
Step 10/17 : USER root
 ---> Running in fd119043336a
 ---> b88c62228aed
Removing intermediate container fd119043336a
Step 11/17 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR
 ---> Running in cdf8f2410d3f
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
Removing intermediate container cdf8f2410d3f
The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh &&     rm -rf $INSTALL_DIR' returned a non-zero code: 127

ERROR: Oracle Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.
```

**Comment by dsendkowski** [comment]
Full build log attached:
[output.txt](https://github.com/oracle/docker-images/files/1769124/output.txt)

**Comment by gvenzl** [comment]
Hi @dsendkowski, are there any security features enabled that may prevent the container from accessing `/etc`?

**Comment by dsendkowski** [comment]
None that I am aware of. Any specific features you have in mind?

**Comment by gvenzl** [comment]
`SELinux` sometimes prevents certain things to be allowed but in your scenario I didn't spot any `SELinux` related issues.

In my container I see the file to be owned by `root`, so I'm struggling to understand where the error comes from:

```
-rw-r--r-- 1 root   root         54 Sep 22 16:51 oraInst.loc
-rw-r--r-- 1 root   root         32 Aug  4  2017 oracle-release
-rw-rw-r-- 1 oracle oinstall    789 Mar 21 02:34 oratab
```

Any chance you can have a look at `/tmp/OraInstall2018-02-28_10-15-14PM/installActions2018-02-28_10-15-14PM.log` and see what it complains? It probably will tell you to look into the according trace file.

**Comment by dsendkowski** [comment]
I set both `--rm=false` and `--force-rm=false` so that no intermediate container is removed. Unfortunately, I could not find this log file (`/tmp/OraInstall2018-03-21_08-48-59AM/installActions2018-03-21_08-48-59AM.log`) in any intermediate container in the specified location for my current session.

**Comment by gvenzl** [comment]
Thanks @dsendkowski, could it be that you got a different folder as the one above contains the date and time. Every time a new install is kicked off you will find a new folder under `/tmp`.

**Comment by tonyyao81** [comment]
I got the same issue with OpenSuse 42.3

**Comment by gvenzl** [comment]
Hi @tonyyao81, can you provide the output from the log file please?

**Comment by gvenzl** [comment]
Closing due to lack of response.

**Comment by tranmh** [comment]
I can reproduce it on SLES 12.3 and I cannot provide you a log file. 
ls /tmp
tells me that /tmp is complete empty. Any idea how to proceed? Thx.
