### ISSUE TITLE
oraclelinux:7 vs oraclelinux:latest

### ISSUE THREAD

**Issue by calam1** [oracle/docker-images#775]
I started to experience some odd issues that I resolved awhile back about systemctl on oracle linux / redhat.  Things were working fine until recently.  I realized in my Dockerfile when i either had

```FROM oraclelinux:7``` 
or
```FROM oraclelinux:latest```

I would always get the same image, I believe, unless I am reading the output incorrectly.  I always get the 7.4 version.  I looked in the /etc/redhat-release file for both containers and saw

```Red Hat Enterprise Linux Server release 7.4 (Maipo)```

Here is some of the standard out for oraclelinux:7 run
```
Sending build context to Docker daemon  25.09kB
Step 1/17 : FROM oraclelinux:7
7: Pulling from library/oraclelinux
09c4e42bdb0a: Pull complete
Digest: sha256:66f50e19e8456c3893adc47f82b6c84475d81590947e4657cbdee259cd03fa06
Status: Downloaded newer image for oraclelinux:7
 ---> 738555b05d00
```

Here is some of the standard out for oraclelinux:latest run
```
Sending build context to Docker daemon  25.09kB
Step 1/17 : FROM oraclelinux:latest
latest: Pulling from library/oraclelinux
09c4e42bdb0a: Pull complete
Digest: sha256:66f50e19e8456c3893adc47f82b6c84475d81590947e4657cbdee259cd03fa06
Status: Downloaded newer image for oraclelinux:latest
 ---> 738555b05d00
```

As you see from above the sha(sha256:66f50e19e845...) and image ids(09c4e42bdb0a) are the same.  Shouldn't the oraclelinux:7 tag be pulling the 7.0 and not the 7.4 version?   According to this https://github.com/oracle/ol-container-images/blob/74409877de8c1ca942904ff77dd5d002a3dac360/7.0/Dockerfile  it seems to be the case.  Once again I may be misinterpreting, so please forgive me if that is the case.

Thanks,

Chris

**Comment by calam1** [comment]
I was using a Dockerfile written by somebody else, and a friend of mine noticed that the tag should be 7.0 and not 7,  that is probably the problem

**Comment by Djelibeybi** [comment]
No, the tag should definitely be 7 unless you really want years of security bugs.

**Comment by calam1** [comment]
Yeah, I understand that 7 pulls the latest.  The problem is that what version I get can be non-deterministic.  So if something use to work for 7.3, there is no guarantee that it works for 7.4  I started to see some weird issues on oracle patches that sometimes fail on 7.4 but were tested by some other team on an earlier version 7, like maybe 7.3  etc.  Not sure what their env is.
