### ISSUE TITLE
No metrics or targets on Prometheus UI

### ISSUE THREAD

**Issue by maryjomcguinness** [oracle/docker-images#778]
The issue was seen when trying to monitor an existing Kubernetes cluster using Prometheus. After connecting to the cluster ok and creating a namespace called 'monitoring', I used the following config-map.yaml file and then ran kubectl create -f ./config-map.yaml -n monitoring

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'kubernetes-apiservers'

        kubernetes_sd_configs:
        - role: endpoints
        scheme: https

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https

      - job_name: 'kubernetes-nodes'

        scheme: https

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics

      
      - job_name: 'kubernetes-pods'

        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

      - job_name: 'kubernetes-cadvisor'

        scheme: https

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      
      - job_name: 'kubernetes-service-endpoints'

        kubernetes_sd_configs:
        - role: endpoints

        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name

I also created a Prometheus deployment by using this prometheus-deployment.yaml file below running the following command: kubectl create  -f prometheus-deployment.yaml --namespace=monitoring

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.1.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  
        - name: prometheus-storage-volume
          emptyDir: {}

I can see that the deployment has been created by running:
./kubectl get deployments --namespace=monitoring
NAME                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
prometheus-deployment   1         1         1            1           4d

And when running the following I see the pod:
./kubectl get pods --namespace=monitoring
NAME                                     READY     STATUS    RESTARTS   AGE
prometheus-deployment-5cfdf8f756-mpctk   1/1       Running   0          4d

However when I drop the --namespace command, it doesn't find it:
./kubectl get pods
NAME                READY     STATUS    RESTARTS   AGE
cassandra-0         1/1       Running   0          5d
cassandra-1         1/1       Running   0          5d
cassandra-2         1/1       Running   0          5d
metricgen-0         1/1       Running   0          5d
metricrest-0        1/1       Running   0          5d
metricsummarise-0   1/1       Running   0          5d
monitor-0           1/1       Running   0          5d

Is this what might be causing my problem with the missing metrics and targets? I also noticed that in another defect raised, that the accountServiceName needs to be defined somewhere. Could you let me know whether I should put this in the config-map.yaml file or the prometheus-deployment.yaml file and where in the file please?

I tried to place it in the deployment file here:

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
  serviceAccounName: prometheus
spec:
  replicas: 1
  template:

but it gave me an error.

One more thing to note is when I try to find the logs I get the following:

./kubectl logs prometheus-deployment-5cfdf8f756-mpctk
Error from server (NotFound): pods "prometheus-deployment-5cfdf8f756-mpctk" not found

**Comment by marinakog** [comment]
HI @maryjomcguinness  , if you have deployment in specific namespace to review all data related to that, you always need to specify namespace as well, so to get log ./kubectl logs prometheus-deployment-5cfdf8f756-mpctk -n monitoring, or to get pods you need to add -n .monitoring. If you don't it will print only everything related to default namespace.

Could you please try to delete Prometheus pod and delete namespace monitoring just to clean your env and try to : 1. create namespace monitoring,
2. use this as an example for prometheus deployment 
https://github.com/karan-kapoor90/wls-K8s/blob/master/prometheus/prometheus-kubernetes.yml. 
Make sure   basic_auth:
       username: weblogic
       password: welcome1 in the yaml matches your WLS  authorized user

**Comment by mriccell** [comment]
@maryjomcguinness have you been able to apply @marinakog suggestion?

**Comment by mriccell** [comment]
Closing due to lack of input
