### ISSUE TITLE
Update images on store and oracle registry

### ISSUE THREAD

**Issue by gschrader** [oracle/docker-images#784]
I was looking to utilize the startup scripts that were added in https://github.com/oracle/docker-images/pull/471 but noticed that the images on the docker store and on https://container-registry.oracle.com are about 6 months old and don't have the startup script support. Can these be updated?

I know I can build these myself but it makes life easier to be able to pull from a registry.

Thanks!

**Comment by Djelibeybi** [comment]
For reasons that are many, varied, complex and mostly lost in the mists of time*, the Oracle Database images on the Container Registry are not built using the same Dockerfiles as we publish here. If you need that sort of customization, you will need to build the image yourself.

**Comment by gschrader** [comment]
ok thanks, it makes me a little sad but I will work around it.

**Comment by Djelibeybi** [comment]
I will prod @gvenzl to document this so that it's more clear for future users too.

**Comment by gschrader** [comment]
Yes good idea, my assumption was that they were the same
