### ISSUE TITLE
Glassfish 5 + ajp doesn't work

### ISSUE THREAD

**Issue by beus** [oracle/docker-images#790]
Like this stackOverflow post, the connexion in ajp via mod_jk or mod_proxy_aim didn't week.
https://stackoverflow.com/questions/49108190/org-glassfish-grizzly-http-ajp-ajphandlerfilter-encodehttppacketajphandlerfilte

Thanks to help us

**Comment by arindam-bandyopadhyay** [comment]
@beus It's a product bug. It's not a GlassFisg docker image bug. Please log this bug in GlassFish issue tracker https://github.com/javaee/glassfish/issues . Closing this as this is not a GlassFish docker image bug.
