### ISSUE TITLE
Check DB status based on PDB status #729 fails to address a non-PDB environment

### ISSUE THREAD

**Issue by wakko978** [oracle/docker-images#791]
I recently started using this code base to initiate an Oracle 12.2.0.1 database specifically NOT using PDBs. This change breaks in cases where a PDB is not used. Not sure if I'm the target market, but I'm modeling a production environment which cannot use PDBs.

Steps to create might be a bit much for me to take on, however, I modified dbca.rsp.tmpl as follows:
```
createAsContainerDatabase=false
numberOfPDBs=0
# pdbName=###ORACLE_PDB###
# pdbAdminPassword=###ORACLE_PWD###
```

Starting the container fails:
```
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
```

**Comment by gvenzl** [comment]
Hi @wakko978, indeed those scripts are all geared towards a single PDB/CDB environment as the [Non-CDB architecture is deprecated](https://docs.oracle.com/database/121/UPGRD/deprecated.htm#BABDBCJI). That being said, all you have to do is to provide your own database check script (either overwrite `checkDBStatus.sh` or point the `CHECK_DB_FILE` environment variable to a new file. A simple `select status from $vinstance;` should be enough for a non-CDB environment.

**Comment by gvenzl** [comment]
Closing this issue as I expect the thumbs up means the issue creator is ok with that explanation.

**Comment by ByronLudwig** [comment]
Having had to do this recently myself please note there is also the statement _ALTER PLUGGABLE DATABASE $ORACLE_PDB SAVE STATE;_ to open the PDB in the createDB script which you need to remove.
