### ISSUE TITLE
FMW and OBIEE 12.2.1.3 containers failed to start

### ISSUE THREAD

**Issue by jwryoo** [oracle/docker-images#792]
When I tried FMW Infra 12.2.1.3 and OBIEE 12.2.1.3 images (both built using the files from GIT or from the container-registry), it seems the started container is producing the problem described in the notes below.
https://support.oracle.com/knowledge/Middleware/2308193_1.html
http://blog.sysco.no/weblogic,/jdbc/WLS-12.2.1.3.0-JDBC-fails-with-ONS-configuration-failed/

For Weblogic 12.2.1.3, I could apply the workaround, but for OBIEE image, I could not. At first, it failed to create the repo using RCU. After applying the workaround, the container managed to run RCU but at the next step it failed somewhere for essbase etc.

Is there any way to overcome or avoid this issue if this happens to all?

**Comment by sjvp** [comment]
The configuration tooling for BI is probably not transporting external environment JAVA_OPTIONS through to the various tools it runs, of which there are many, and/or the tools do not respect JAVA_OPTIONS.

If you've managed to get through RCU, then you might be able to inject this option in wlst.sh (by editing or setting environment var) - the variable is different:

  WLST_PROPERTIES="-Doracle.jdbc.fanEnabled=false"

Even if this works, you'll need to make sure these are set for future usages of wlst.sh, domain start scripts etc.

So you could probably instead try the other option listed in the support note:

 "(ii)  Drop either ons.jar or simplefan.jar from CLASSPATH"

i.e. remove these from ORACLE_HOME.

**Comment by sjvp** [comment]
Not heard back on whether the other workaround was successful, thus closing. Please reopen if you still have no success.
