### ISSUE TITLE
jar binary missing from serverjre, which is required for OracleWebLogic 

### ISSUE THREAD

**Issue by ncuster** [oracle/docker-images#797]
- I built the serverjre image from docker-images/OracleJava/java-8
- no 'jar' command exists in the resulting image (even though the Dockerfile tries to set the alternatives for jar)
- The build of a Weblogic image, from docker-images/OracleWebLogic/12.2.1.3  requires the jar binary be available, so it is failing.  

Taking a step back I looked at the server-jre from OTN, which I'm using server-jre-8u161-linux-x64.tar.gz, and if you look in that tarball you can see it doesn't have the jar utility:

>  gzip -dc server-jre-8u161-linux-x64.tar.gz | tar -tvf - | grep bin
drwxr-xr-x  0 java_re java_re     0 Dec 19 18:21 jre1.8.0_161/bin/
-rwxr-xr-x  0 java_re java_re  7949 Dec 19 18:21 jre1.8.0_161/bin/rmiregistry
-rwxr-xr-x  0 java_re java_re 231482 Dec 19 18:21 jre1.8.0_161/bin/unpack200
-rwxr-xr-x  0 java_re java_re   6264 Dec 19 18:21 jre1.8.0_161/bin/jcontrol
-rwxr-xr-x  0 java_re java_re   7965 Dec 19 18:21 jre1.8.0_161/bin/servertool
-rwxr-xr-x  0 java_re java_re   7997 Dec 19 18:21 jre1.8.0_161/bin/policytool
-rwxr-xr-x  0 java_re java_re   7941 Dec 19 18:21 jre1.8.0_161/bin/jjs
-rwxr-xr-x  0 java_re java_re   8149 Dec 19 18:21 jre1.8.0_161/bin/orbd
-rwxr-xr-x  0 java_re java_re   7957 Dec 19 18:21 jre1.8.0_161/bin/pack200
-rwxr-xr-x  0 java_re java_re   7941 Dec 19 18:21 jre1.8.0_161/bin/rmid
-rwxr-xr-x  0 java_re java_re   8181 Dec 19 18:21 jre1.8.0_161/bin/tnameserv
-rwxr-xr-x  0 java_re java_re   7941 Dec 19 18:21 jre1.8.0_161/bin/keytool
-rwxr-xr-x  0 java_re java_re 132911 Dec 19 18:21 jre1.8.0_161/bin/javaws
lrwxrwxrwx  0 java_re java_re      0 Dec 19 18:21 jre1.8.0_161/bin/ControlPanel -> jcontrol
-rwxr-xr-x  0 java_re java_re   7734 Dec 19 18:21 jre1.8.0_161/bin/java
-rwxr-xr-x  0 java_re java_re    49341 Dec 19 18:21 jre1.8.0_161/lib/amd64/libinstrument.so

**Comment by aureliogrb** [comment]
Not sure how you built your image but server-jre-8u161-linux-x64.tar.gz (SHA256: eb5776cacfd57fbf0ffb907f68c58a1cc6f823e761f4e75d78a6e3240846534e) when uncompressed does contain jar.

find . -name jar
./bin/jar

What you shouldn't have, yet you show in your results, is  either javaws or jcontrol.  I'd recommend downloading the serverJRE again, manually uncompressing, and seeing if you can find jar.

**Comment by ncuster** [comment]
I apologize, I think someone may have taken some other jdk/jre download and renamed it so that the java-8 build would pick it up.  I re-downloaded serverjre, rebuilt java-8 and all was fine.
