### ISSUE TITLE
Jenkins Build giving buildDockerImage.sh as not found

### ISSUE THREAD

**Issue by mkvijay** [oracle/docker-images#803]
I want to automate the process of creating oracle docker image so i created a jenkinsfile and trying to build the oracledb docker image. Here is the file
stage('Build Image') {
            steps {
                s3Download(file: 'linuxx64_12201_database.zip', bucket: xxx', path: 'linuxx64_12201_database.zip', force: true)
                git url: 'https://github.com/oracle/docker-images.git'
                // build the image
                sh 'sudo ./buildDockerImage.sh  -v 12.2.0.1 -s' (here tried with all tags -g, -x, -s)
            }
        }

**Comment by Djelibeybi** [comment]
I'm not sure what the problem is here?

**Comment by mkvijay** [comment]
Thanks for your response on this. I resolved the above error, but now I get another error 

first I got this error then i changed the to -s, yet i got the error also i tried with -x it didnt work 
buildDockerImage.sh  -v 12.2.0.1 -e'

line 121: cd: 12.2.0.1: No such file or directory
20:46:05 Checking if required packages are present and valid...
20:46:05 md5sum: Checksum.ee: No such file or directory
20:46:05 MD5 for required packages to build this image did not match!
20:46:05 Make sure to download missing files in folder 12.2.0.1.

buildDockerImage.sh  -v 12.2.0.1 -s

buildDockerImage.sh: line 121: cd: 12.2.0.1: No such file or directory
20:27:43 Checking if required packages are present and valid...
20:27:43 md5sum: Checksum.se2: No such file or directory
20:27:43 MD5 for required packages to build this image did not match!
20:27:43 Make sure to download missing files in folder 12.2.0.1.

**Comment by Djelibeybi** [comment]
Looks like you don't have the right binary tarballs available.

**Comment by gvenzl** [comment]
Hi @mkvijay, the `buildDockerImage.sh` is just a helper shell script to avoid the user having to understand how `docker build` works. However, as a helper script it is tailored against this GitHub repository structure. The error you get is `line 121: cd: 12.2.0.1: No such file or directory`. The script will `cd` into the version folder based on the version that you have chosen. In your scenario there is no `12.2.0.1` folder that the script can `cd` into.

Alternatively, you can also just call `docker build` directly if you know the syntax. The default one is `docker build -t oracle/database:12.2.0.1-ee -f Dockerfile.ee .` for the 12.2.0.1 EE Docker image.

**Comment by mkvijay** [comment]
I re-downloaded the binaries and ran the build it didnt help. I am was able to create docker images on my local but not able to do using Jenkinsfile. I wanted to automate this using jenkins, How should I proceed here ?

**Comment by Djelibeybi** [comment]
This seems more like a Jenkins problem. You'll have to get support from Jenkins experts, I think.

**Comment by gvenzl** [comment]
Without more information it will be tricky to help you further, @mkvijay. What is the error that you are getting, what is your Jenkinsfile? Why do you execute the `buildDockerImage.sh` script and not just use something like:

```
node {
    checkout scm
    def customImage = docker.build("my-image:${env.BUILD_ID}")
    ...
```
as the [Docker pipeline plugin](https://jenkins.io/doc/book/pipeline/docker/#building-containers) for example allows you to do?

**Comment by mkvijay** [comment]
yes my Jenkinsfile looks similar to this,
node {
    git url : https://github.com/oracle/docker-images.git
    sh 'sudo ./buildDockerImage.sh -v 12.2.0.1 -s'
    }
 error:
checkSpace.sh: ERROR - There is not enough space available in the docker container.
14:21:03 checkSpace.sh: The container needs at least 15 GB, but only 6 GB are available.
14:21:03 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mkvijay** [comment]
Thanks! I resolved it.

**Comment by gvenzl** [comment]
That's great @mkvijay!
Would you like to perhaps write your setup up and publish it on the OracleDevs channel to share your work with others? :)
