### ISSUE TITLE
I run "docker build -t oracle/serverjre:8 " in java-8 folder but not i expected

### ISSUE THREAD

**Issue by oHao** [oracle/docker-images#806]
There is the error：Get https://registry-1.docker.io/v2/:  EOF。
it means it's a network problem?

**Comment by Djelibeybi** [comment]
Please provide the full output.

**Comment by oHao** [comment]
localhost:java-8 luhao$ docker build -t oracle/serverjre:8 .
Sending build context to Docker daemon   54.8MB
Step 1/5 : FROM oraclelinux:7-slim
Get https://registry-1.docker.io/v2/: EOF
there is all，thanks

**Comment by Djelibeybi** [comment]
Yes, you have a network issue. You need to be able to pull the `oraclelinux:7-slim` base image from the Docker Hub.

**Comment by oHao** [comment]
I will try it，very appreciate
