### ISSUE TITLE
Weblogic docker image does not work on Mac

### ISSUE THREAD

**Issue by skoky** [oracle/docker-images#81]
I am trying to run WebLogic build script on Mac and it does not work as there is no `md5sum` installed by default:

> ./buildDockerImage.sh -d
> Checking if required packages are present and valid...
> ./buildDockerImage.sh: line 39: md5sum: command not found
> MD5 for required packages to build this image did not match!
> Make sure to download missing files in folder 12.2.1. See *.download files for more information

If I install `md5sum` by `brew remove md5sha1sum` I see this error:

> ./buildDockerImage.sh -d
> Checking if required packages are present and valid...
> ./buildDockerImage.sh: line 39: md5sum: command not found
> MD5 for required packages to build this image did not match!
> Make sure to download missing files in folder 12.2.1. See *.download files for more information
> SkokanMacPro:dockerfiles skoky$ ./buildDockerImage.sh -d
> Checking if required packages are present and valid...
> Could not parse check file 'Checksum.developer' (2)
> MD5 for required packages to build this image did not match!
> Make sure to download missing files in folder 12.2.1. See *.download files for more information

Ok, so I ave skipped md5 check inside the script by `SKIPMD5=1` and I see this result:

> SkokanMacPro:dockerfiles skoky$ ./buildDockerImage.sh -d
> Skipped MD5 checksum.
> `=====================`
> Building image 'oracle/weblogic:12.2.1-developer' ...
> Sending build context to Docker daemon 20.99 kB
> Step 1 : FROM oraclelinux:latest
> latest: Pulling from library/oraclelinux
> a3ed95caeb02: Pull complete 
> ffe36b360c6d: Pull complete 
> Digest: sha256:43e43dbbb960b1658a3514342e52dd4ff01e5195cddb6f05b23af273caf07135
> Status: Downloaded newer image for oraclelinux:latest
>  ---> adf2d3d00fce
> Step 2 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
>  ---> Running in c796094d1d82
>  ---> ab8eb0ebf539
> Removing intermediate container c796094d1d82
> Step 3 : ENV JAVA_PKG server-jre-8u*-linux-x64.tar.gz JAVA_HOME /usr/java/default FMW_PKG fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip FMW_JAR fmw_12.2.1.0.0_wls_quick.jar ORACLE_HOME /u01/oracle USER_MEM_ARGS "-Djava.security.egd=file:/dev/./urandom" PATH $PATH:$JAVA_HOME/bin:$ORACLE_HOME/oracle_common/common/bin
>  ---> Running in 44ac759cfee6
>  ---> 96740365c291
> Removing intermediate container 44ac759cfee6
> Step 4 : COPY $FMW_PKG install.file oraInst.loc /u01/
> lstat fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip: no such file or directory
> There was an error building the image.
> 

Any advice how to move forward?

**Comment by brunoborges** [comment]
It seems you didn't download the WLS and Server JRE binaries.

**Comment by jasonberanek** [comment]
@skoky I ran into a similar problem to your first md5sum portion of the issue, even with having the actual files.  It appears the version of the md5sum tool installed by brew doesn't tolerate the comments in the *.download files packaged in this repo, which results in the md5sum checks failing.

I cannot speak to your latter issues, assuming you did in fact have the files in the right directory.  I was running the OHS build steps and ran into a different error (related to the copy command trying to copy to a read only file system), though I suspect I was asking my base system to do more than it was capable of since my entire system got hit with heavy memory pressure and I had to force quit the headless VM Docker Toolbox was using.

**Comment by therealcmj** [comment]
I had the same issue as @jasonberanek - md5sum on Mac (installed from "brew install md5sha1sum" doesn't like the comments in the checksum files. Homebrew installs http://www.microbrew.org/tools/md5sha1sum/ which doesn't support comments.

I worked around it by tweaking the script to grep -v the specific Checksum.X file, pipe the result into a temp file, and then use that in the "md5sum -c", removing it afterward. Happy to provide patch/pull request if you'd like it @brunoborges

**Comment by SuprabhaSharma** [comment]
above solution works for me
