### ISSUE TITLE
can't pull the image:oracle/weblogic:12.1.3-generic

### ISSUE THREAD

**Issue by oHao** [oracle/docker-images#810]
there is all output:
 pull access denied for oracle/weblogic, repository does not exist or may require 'docker login'
and i m sure i had login

**Comment by oHao** [comment]
i had weblogic-12.1.3-devloper ,serverjre8,oracleLinux 7-slim image.there is the command:
docker build -t 1213-domain --build-arg ADMIN_PASSWORD=123 .
and i run it in 1213-domain folder

**Comment by Djelibeybi** [comment]
You need to build the `weblogic:12.1.3-generic` image first. Also, these images use version old versions of WebLogic. You should be using WebLogic 12.2.1.3 not, 12.1.3.

**Comment by oHao** [comment]
em...i need to remove all images i had build and try it with weblogic:12.1.3-generic?

**Comment by Djelibeybi** [comment]
You don't need to remove any images. You just need to build the `weblogic:12.1.3-generic` image because that's what the `1213-domain` sample requires.

**Comment by mriccell** [comment]
@oHao did you resolve your problem?

**Comment by mriccell** [comment]
closing due to lack of response, please open again if you still need help.
