### ISSUE TITLE
Disabled partitioning for store/oracle/database-enterprise:12.2.0.1

### ISSUE THREAD

**Issue by kczulko** [oracle/docker-images#811]
Statement:
```
create table test_part (id number) partition by hash (id);
```
returns:
```
Error starting at line : 1 in command -
create table test_part (id number) partition by hash (id)
Error at Command Line : 1 Column : 1
Error report -
SQL Error: ORA-00439: feature not enabled: Partitioning
00439. 00000 -  "feature not enabled: %s"
*Cause:    The specified feature is not enabled.
*Action:   Do not attempt to use this feature.
```

**Comment by kczulko** [comment]
Found that information:
https://github.com/oracle/docker-images/issues/685
but nevertheless it is misleading (as @veqryn wrote there) that Oracle EE docker image has partitioning disabled.

**Comment by gvenzl** [comment]
Thanks @kczulko! I agree, it's misleading but also raised a question. If you get a chance please have a look at #685 and post your requests on this.
