### ISSUE TITLE
./startNodeManager.sh: 28: .: Can't open /u01/oracle/user_projects/domains/base_domain/bin/setNMJavaHome.sh

### ISSUE THREAD

**Issue by kushortiz** [oracle/docker-images#812]
When I try to start node manager on weblogic 12.2.1.3 from /bin I get below error. I am running this on docker. I have the admin server up and running, want to start node manager and managed server.

root@cloudshell:/var/lib/docker/aufs/mnt/9eaa9d2a333b7a8c54b3ead39fcc69a01991de9680ab922ef69283ab41af805a/u01/oracle/user_projects/domains/base_domain/bin$ ./startNodeManager.sh
**./startNodeManager.sh: 28: .: Can't open /u01/oracle/user_projects/domains/base_domain/bin/setNMJavaHome.sh**
root@cloudshell:/var/lib/docker/aufs/mnt/9eaa9d2a333b7a8c54b3ead39fcc69a01991de9680ab922ef69283ab41af805a/u01/oracle/user_projects/domains/base_domain/bin$

**Comment by Djelibeybi** [comment]
I've assigned this to @mriccell as she's the WebLogic expert, but I'm pretty sure you can't start the NodeManager from outside Docker; you need to start a container that has WebLogic installed inside and then connect to the Admin Server.

**Comment by mriccell** [comment]
@kushortiz why would you start the NM and MS by invoking a script?  If you run the container from the 12213-domain image with the following command
$ docker run -d --name MS1 --link wlsadmin:wlsadmin -p 8001:8001 --env-file ./container-scripts/domain.properties -e ADMIN_PASSWORD=<admin_password> -e MS_NAME=MS1 --volumes-from wlsadmin 12213-domain createServer.sh
The NM and MS start automatically. 
What are you trying to do?

**Comment by mriccell** [comment]
@kushortiz I am closing this issue due to lack of feedback, please re open if the problem persists.
