### ISSUE TITLE
[WCS step 6.C.2] starting DB docker - ERROR : untar DB bits failed

### ISSUE THREAD

**Issue by Alcold** [oracle/docker-images#814]
As title I get an error when I try to run for the first time Oracle DB docker. Here are the logs...
- [WCSites12212Database.log](https://github.com/oracle/docker-images/files/1852171/WCSites12212Database.log)
- [untarDB.log](https://github.com/oracle/docker-images/files/1852174/untarDB.log)
I checked inside the docker and I see the file "/tmp/dbsetup/dbtar/dbf_12201.tar.gz" is empty. I downloaded this docker from Oracle repository, should I change something?

**Comment by ashishchalak** [comment]
Can you give steps in details that you have followed to start the database container.

**Comment by Alcold** [comment]
I followed exactly what is written [here](https://github.com/oracle/docker-images/blob/master/OracleWebCenterSites/README.md)

In particular steps:
- 4.B
- 6.C

and the following command (as described in guide)
```
$ docker run -d --name WCSites12212Database --network=WCSitesNet -p 1521:1521 -p 5500:5500 --env-file ./db.env.list database/enterprise:12.2.0.1
```

**Comment by stewartbryson** [comment]
I'm seeing this as well.

**Comment by ashishchalak** [comment]
I was able to install without any error. Please find attached screenshot for the steps followed.

**Comment by ashishchalak** [comment]
I was able to install without any error. Please find attached screenshot for the steps followed.

![db container startup](https://user-images.githubusercontent.com/29303273/38409866-9ca7220e-3972-11e8-80c2-ebad63da6c1b.JPG)

**Comment by ashishchalak** [comment]
It could be a bad pull, a timeout during transfer, or something else causing the truncation. Can you remove the image and try pulling again. Can you also check on storage space.

**Comment by Alcold** [comment]
Ok, I will try... Thank you for now :)

**Comment by Alcold** [comment]
I confirm that was a bad pull. I retried to pull and now it works.

Thank you  @ashishchalak
