### ISSUE TITLE
Cgroup issue i.e. RAC container is not coming up because of RT settings

### ISSUE THREAD

**Issue by largefp2018** [oracle/docker-images#837]
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 95000 to cpu.rt_runtime_us: write /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-7855dc62aa673ffa14ca7d9271ae571b818e628b9fb586ba4604aba55afe2c34.scope/cpu.rt_runtime_us: invalid argument\\\"\"": unknown
Error: failed to start containers: racnode1

**Comment by psaini79** [comment]
Please try following:

echo 950000 > /sys/fs/cgroup/cpu/cpu.rt_runtime_us
echo 1000000> /sys/fs/cgroup/cpu/cpu.rt_period_us
echo 95000 > /sys/fs/cgroup/cpu,cpuacct/system.slice/cpu.rt_runtime_us

Retstart container and let me know if you face any issue.

**Comment by Djelibeybi** [comment]
Please can you provide more information, like the output from `docker info` on this host?

**Comment by largefp2018** [comment]
Hi Djelibeybi,

[root@nodec ~]# docker info
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 62
Server Version: 17.06.2-ee-7
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 462c82662200a17ee39e74692f536067a3576a50
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.1.12-112.16.4.el7uek.x86_64
Operating System: Oracle Linux Server 7.4
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 19.08GiB
Name: nodec
ID: OBQJ:DYCP:BAR4:C2BF:ZXZ6:YBY2:ITPE:CZRI:U6XR:IA3L:YO4S:TJAQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
 
Thank you very much.

**Comment by Djelibeybi** [comment]
Is this still an issue? Your other issues have been resolved?

**Comment by largefp2018** [comment]
This is not issue， other issues have been resolved.

**Comment by Djelibeybi** [comment]
Great. Closing this because it is not an issue.
