### ISSUE TITLE
 RAC installation is failing on cent OS UEK3

### ISSUE THREAD

**Issue by donjoxie** [oracle/docker-images#840]
In host：
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# 
....
In Docker Container：
bash-4.2# uname -a
Linux racnode-storage 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
bash-4.2# sysctl -p
sysctl: setting key "fs.file-max": Read-only file system
sysctl: setting key "kernel.sem": Read-only file system
sysctl: setting key "kernel.shmmni": Read-only file system
sysctl: setting key "kernel.shmall": Read-only file system
sysctl: setting key "kernel.shmmax": Read-only file system
sysctl: setting key "kernel.panic_on_oops": Read-only file system
sysctl: cannot stat /proc/sys/net/core/rmem_default: No such file or directory  <<<<<<<<<Can not get /proc/sys/net/core/rmem_default
sysctl: cannot stat /proc/sys/net/core/rmem_max: No such file or directory      <<<<<<<<<Can not get /proc/sys/net/core/rmem_max
sysctl: cannot stat /proc/sys/net/core/wmem_default: No such file or directory  <<<<<<<<<Can not get /proc/sys/net/core/wmem_default
sysctl: cannot stat /proc/sys/net/core/wmem_max: No such file or directory      <<<<<<<<<Can not get /proc/sys/net/core/wmem_max
sysctl: setting key "net.ipv4.conf.all.rp_filter": Read-only file system
sysctl: setting key "net.ipv4.conf.default.rp_filter": Read-only file system
sysctl: setting key "fs.aio-max-nr": Read-only file system
sysctl: setting key "net.ipv4.ip_local_port_range": Read-only file system
bash-4.2#

**Comment by Djelibeybi** [comment]
That's not UEK3. That's the CentOS RHCK. UEK3 is 3.8 and we don't support Docker on that kernel anyway. Can you reproduce this issue on Oracle Linux 7 running UEK4 (4.1.12)?

**Comment by donjoxie** [comment]
HI Djelibeybi

Thanks for your update.

You are right. l don't reproduce this issue on  UEK4.   It can work.

In host:
[root@localhost ~]# uname -a
Linux localhost.localdomain 4.1.12-103.10.1.el7uek.x86_64 #2 SMP Tue Dec 5 15:42:37 PST 2017 x86_64 x86_64 x86_64 GNU/Linux

In Docker Container:
bash-4.2# uname -a
Linux racnode1 4.1.12-103.10.1.el7uek.x86_64 #2 SMP Tue Dec 5 15:42:37 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
bash-4.2# sysctl -p
sysctl: setting key "fs.file-max": Read-only file system
sysctl: setting key "kernel.sem": Read-only file system
sysctl: setting key "kernel.shmmni": Read-only file system
sysctl: setting key "kernel.shmall": Read-only file system
sysctl: setting key "kernel.shmmax": Read-only file system
sysctl: setting key "kernel.panic_on_oops": Read-only file system
sysctl: setting key "net.core.rmem_default": Read-only file system
sysctl: setting key "net.core.rmem_max": Read-only file system
sysctl: setting key "net.core.wmem_default": Read-only file system
sysctl: setting key "net.core.wmem_max": Read-only file system
sysctl: setting key "net.ipv4.conf.all.rp_filter": Read-only file system
sysctl: setting key "net.ipv4.conf.default.rp_filter": Read-only file system
sysctl: setting key "fs.aio-max-nr": Read-only file system
sysctl: setting key "net.ipv4.ip_local_port_range": Read-only file system
bash-4.2#

**Comment by Djelibeybi** [comment]
Great. Closing this as it works on our supported platform.
