### ISSUE TITLE
Oracle RAC Create racnode1 failed

### ISSUE THREAD

**Issue by largefp2018** [oracle/docker-images#842]
Hi,

docker create -t -i --hostname racnode1 ...

docker logs -f racnode1
----------------------------------------------------------------------
04-11-2018 18:44:44 UTC :  : Running cluvfy Checks
04-11-2018 18:44:44 UTC :  : Performing Cluvfy Checks
04-11-2018 18:45:34 UTC :  : Cluster Verfication Check failed! Removing failure statement related to /etc/resov.conf, DNS and ntp.conf checks as you may not have DNS or NTP Server
04-11-2018 18:45:34 UTC :  : Checking Again /tmp/cluvfy_check.txt
04-11-2018 18:45:34 UTC :  : Pre Checks failed for Grid installation, ignoring failure related to SCAN and /etc/resolv.conf
04-11-2018 18:45:34 UTC :  : Running Grid Installation
04-11-2018 18:46:08 UTC :  : Checking Cluster Status
04-11-2018 18:46:08 UTC :  : Checking Cluster
04-11-2018 18:46:08 UTC : : Cluster Check failed  <<<<<<==================
04-11-2018 18:46:08 UTC : : Error has occurred in Grid Setup, Please verify! 
--------------------------------------------------------------
more /tmp/cluvfy_check.txt

04-11-2018 00:25:35 UTC :  : Checking Cluster Status
04-11-2018 00:25:35 UTC :  : Checking Cluster
04-11-2018 00:25:35 UTC : : Cluster Check failed
04-11-2018 00:25:35 UTC : : Error has occurred in Grid Setup, Please verify!

Verifying File system mount options for path /var ...PASSED
Verifying zeroconf check ...PASSED
Verifying ASM Filter Driver configuration ...PASSED

Pre-check for cluster services setup was unsuccessful on all the nodes. 

Failures were encountered during execution of CVU verification request "stage -p
re crsinst".

PRVG-11826 : DNS resolved IP addresses "218.205.57.154" for SCAN name   <===========
"racnode-scan" not found in the name service returned IP addresses "172.15.1.70"
PRVG-11827 : Name service returned IP addresses "172.15.1.70" for SCAN name
"racnode-scan" not found in the DNS returned IP addresses "218.205.57.154"  <<<<=======

racnode1: PRVF-4664 : Found inconsistent name resolution entries for SCAN name
          "racnode-scan"

**Comment by psaini79** [comment]
What docker engine are you using? Did you Oracle docker engine installation guide. Please review README.md.

**Comment by largefp2018** [comment]
Hi psaini79,

[root@noded ~]# docker -v
Docker version 18.03.0-ce, build 0520e24
[root@noded ~]# docker info|grep -i storage
Storage Driver: overlay2
[root@noded ~]# uname -r
4.14.32-1.el7uek.x86_64

**Comment by psaini79** [comment]
It seems to be docker engine problem. Please check with your docker vendor. I would request if you can try with Oracle/Docker engine and let me know if you face any issue. To install Oracle docker engine, please refer following:

https://docs.oracle.com/cd/E52668_01/E87205/html/ol_about_docker.html

**Comment by largefp2018** [comment]
Hi ,
04-14-2018 11:50:18 UTC :  : Checking Again /tmp/cluvfy_check.txt
04-14-2018 11:50:18 UTC :  : Pre Checks failed for Grid installation, ignoring failure related to SCAN and /etc/resolv.conf
04-14-2018 11:50:18 UTC :  : Running Grid Installation
04-14-2018 11:51:03 UTC :  : Checking Cluster Status
04-14-2018 11:51:03 UTC :  : Checking Cluster
04-14-2018 11:51:03 UTC : : Cluster Check failed
04-14-2018 11:51:03 UTC : : Error has occurred in Grid Setup, Please verify!

Verifying ASM Integrity ...
  Verifying Node Connectivity ...
    Verifying Hosts File ...PASSED
    Verifying Check that maximum (MTU) size packet goes through subnet ...PASSED
  Verifying Node Connectivity ...PASSED
Verifying ASM Integrity ...PASSED
Verifying Device Checks for ASM ...
  Verifying ASM device sharedness check ...
    Verifying Package: cvuqdisk-1.0.10-1 ...PASSED
    Verifying Shared Storage Accessibility:/oradata/asm_disk01.img,/oradata/asm_disk02.img,/oradata/asm_disk03.img,/oradata/asm_disk
05.img,/oradata/asm_disk04.img ...PASSED
  Verifying ASM device sharedness check ...PASSED
Verifying Device Checks for ASM ...PASSED
Verifying I/O scheduler ...
  Verifying Package: cvuqdisk-1.0.10-1 ...PASSED
Verifying I/O scheduler ...PASSED
  Verifying '/etc/ntp.conf' ...PASSED
  Verifying '/var/run/ntpd.pid' ...PASSED
  Verifying '/var/run/chronyd.pid' ...PASSED
Verifying Same core file name pattern ...PASSED
Verifying User Mask ...PASSED
Verifying User Not In Group "root": grid ...PASSED
Verifying Time zone consistency ...PASSED
Verifying VIP Subnet configuration check ...PASSED
  Verifying Name Service Switch Configuration File Integrity ...PASSED
Verifying Single Client Access Name (SCAN) ...PASSED
Verifying Domain Sockets ...PASSED
Verifying /boot mount ...PASSED
Verifying Daemon "avahi-daemon" not configured and running ...PASSED
Verifying Daemon "proxyt" not configured and running ...PASSED
Verifying loopback network interface address ...PASSED
Verifying Oracle base: /u01/app/grid ...
  Verifying '/u01/app/grid' ...PASSED
Verifying Oracle base: /u01/app/grid ...PASSED
Verifying User Equivalence ...PASSED
Verifying Network interface bonding status of private interconnect network interfaces ...PASSED
Verifying File system mount options for path /var ...PASSED
Verifying zeroconf check ...PASSED
Verifying ASM Filter Driver configuration ...PASSED

Pre-check for cluster services setup was unsuccessful on all the nodes. 


Failures were encountered during execution of CVU verification request "stage -pre crsinst".

PRVG-1101 : SCAN name "racnode-scan" failed to resolve


CVU operation performed:      stage -pre crsinst
Date:                         Apr 14, 2018 11:49:11 AM
CVU home:                     /u01/app/12.2.0/grid/
User:                         grid

My Env:
[root@noded asm_vol]# docker -v
Docker version 17.06.2-ee-7, build 925df35
[root@noded asm_vol]# uname -r
4.1.12-112.16.4.el7uek.x86_64

**Comment by psaini79** [comment]
Please share following details:

Docker Host:
=============
1) Which Linux distribution are you using?
2) docker inspect racnode1
3) cat /etc/resov.conf
4) getenforce
5) systemctl status firewalld
6) systemctl status iptables

From RACNODE1 Container
======================
1) cat /etc/resolv.conf
2) out of /etc/hosts

**Comment by largefp2018** [comment]
[root@noded ~]# docker exec -i -t -u root racnode1 /bin/bash bash-4.2# ping 127.0.0.11 PING 127.0.0.11 (127.0.0.11) 56(84) bytes of data.
64 bytes from 127.0.0.11: icmp_seq=1 ttl=64 time=0.057 ms
64 bytes from 127.0.0.11: icmp_seq=2 ttl=64 time=0.131 ms
64 bytes from 127.0.0.11: icmp_seq=3 ttl=64 time=0.039 ms ^C
--- 127.0.0.11 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2052ms rtt min/avg/max/mdev = 0.039/0.075/0.131/0.041 ms bash-4.2# bash-4.2# nslookup 127.0.0.11
Server:         127.0.0.11
Address:        127.0.0.11#53

** server can't find 11.0.0.127.in-addr.arpa.: NXDOMAIN

bash-4.2# cat /etc/resolv.connf
cat: /etc/resolv.connf: No such file or directory bash-4.2# cat /etc/resolv.conf search example.com nameserver 127.0.0.11 options ndots:0 bash-4.2# nslookup racnode-scan
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   racnode-scan
Address: 218.205.57.154

bash-4.2# cat /etc/hosts
127.0.0.1       localhost.localdomain   localhost
172.15.1.150    racnode1.example.com    racnode1
192.168.17.150  racnode1-priv.example.com       racnode1-priv
172.15.1.160    racnode1-vip.example.com        racnode1-vip
172.15.1.70     racnode-scan.example.com        racnode-scan
bash-4.2#

**Comment by largefp2018** [comment]
systemctl status firewalld
systemctl status iptables
getenforce


[root@noded ~]# systemctl status firewalld ● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
[root@noded ~]# systemctl status iptables Unit iptables.service could not be found.
[root@noded ~]# getenforce
Disabled

**Comment by largefp2018** [comment]
[root@noded ~]# docker inspect racnode1
[
    {
        "Id": "97feb1e355b7b9b9b8754fb269dbb04b9d0e527ba42709fe31c0a849f5150a5f",
        "Created": "2018-04-15T04:00:43.320255665Z",
        "Path": "/usr/sbin/oracleinit",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1924,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-04-15T04:01:00.30629916Z",
            "FinishedAt": "2018-04-15T04:00:58.546077588Z"
        },
        "Image": "sha256:c430f7d9602928185ce2774e1b22614de8e505ec3ec05d65b0564f397f8f4835",
        "ResolvConfPath": "/var/lib/docker/containers/97feb1e355b7b9b9b8754fb269dbb04b9d0e527ba42709fe31c0a849f5150a5f/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/97feb1e355b7b9b9b8754fb269dbb04b9d0e527ba42709fe31c0a849f5150a5f/hostname",
        "HostsPath": "/opt/containers/rac_host_file",
        "LogPath": "/var/lib/docker/containers/97feb1e355b7b9b9b8754fb269dbb04b9d0e527ba42709fe31c0a849f5150a5f/97feb1e355b7b9b9b8754fb269dbb04b9d0e527ba42709fe31c0a849f5150a5f-json.log",
        "Name": "/racnode1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/sys/fs/cgroup:/sys/fs/cgroup:ro",
                "/boot:/boot:ro",
                "/opt/containers/rac_host_file:/etc/hosts",
                "racstorage:/oradata"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [
                "SYS_ADMIN",
                "SYS_NICE",
                "SYS_RESOURCE",
                "NET_ADMIN"
            ],
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [
                "example.com"
            ],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "Tmpfs": {
                "/dev/shm": "rw,exec,size=4G",
                "/run": ""
            },
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 95000,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": [
                {
                    "Name": "rtprio",
                    "Hard": 99,
                    "Soft": 99
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/9b40b027525c220b3c341d659357ae2263b2fa5863b302ae811f4ce0f4fb82ef-init/diff:/var/lib/docker/overlay2/a1181594e7cb1a5fec745577b7a432f9a4b282ec27286c398cd432cbbcfffdf3/diff:/var/lib/docker/overlay2/d26b048a3c6dacba327e95f3a5c9f6e0139174cc5201d0303b9c569d97c82068/diff:/var/lib/docker/overlay2/b69e14c202451ce3a270b29423dd4077550d2aca29e8fa330985ceb81d632a1f/diff:/var/lib/docker/overlay2/591f3e77db210880e756143050b8a8d10e6e5e808a6b3ebdcaa45c69ad199db8/diff:/var/lib/docker/overlay2/16164a5118793f95d9b0ca1e214e1d909fb03a375b4da07517b57ef784a4118d/diff:/var/lib/docker/overlay2/bea9c9d704545c57d6bf5342fbdc90670a46abc61c99429c59fdad09f311fdd7/diff:/var/lib/docker/overlay2/bb535173b5bfbc944458558abc8f560f76430d58e77a592f26962e40ca9040d8/diff:/var/lib/docker/overlay2/3398fc110dc634a8d4d5dd307eee1203b84ba61324472eb8052bc552516070e2/diff:/var/lib/docker/overlay2/0312f14357a7a5e4ebe7e60452b191d95b5c3c4b4b355ac87da747ea3a8bda9a/diff",
                "MergedDir": "/var/lib/docker/overlay2/9b40b027525c220b3c341d659357ae2263b2fa5863b302ae811f4ce0f4fb82ef/merged",
                "UpperDir": "/var/lib/docker/overlay2/9b40b027525c220b3c341d659357ae2263b2fa5863b302ae811f4ce0f4fb82ef/diff",
                "WorkDir": "/var/lib/docker/overlay2/9b40b027525c220b3c341d659357ae2263b2fa5863b302ae811f4ce0f4fb82ef/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/boot",
                "Destination": "/boot",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/opt/containers/rac_host_file",
                "Destination": "/etc/hosts",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "racstorage",
                "Source": "/var/lib/docker/volumes/racstorage/_data",
                "Destination": "/oradata",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "0dd612eb1597a0b64c675ab8b5f59869febef8b938a2450060181ae36ef76329",
                "Source": "/var/lib/docker/volumes/0dd612eb1597a0b64c675ab8b5f59869febef8b938a2450060181ae36ef76329/_data",
                "Destination": "/dev/shm",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "60a24758d11a445af54aa087ffb84324a369af385146e4990c16d4ae44ab4384",
                "Source": "/var/lib/docker/volumes/60a24758d11a445af54aa087ffb84324a369af385146e4990c16d4ae44ab4384/_data",
                "Destination": "/common_scripts",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/sys/fs/cgroup",
                "Destination": "/sys/fs/cgroup",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "racnode1",
            "Domainname": "",
            "User": "grid",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "NODE_VIP=172.15.1.160",
                "VIP_HOSTNAME=racnode1-vip",
                "PRIV_IP=192.168.17.150",
                "PRIV_HOSTNAME=racnode1-priv",
                "PUBLIC_IP=172.15.1.150",
                "PUBLIC_HOSTNAME=racnode1",
                "SCAN_NAME=racnode-scan",
                "SCAN_IP=172.15.1.70",
                "OP_TYPE=INSTALL",
                "DOMAIN=example.com",
                "ASM_DISCOVERY_DIR=/oradata",
                "ORACLE_PWD=Oracle_12c",
                "ASM_DEVICE_LIST=/oradata/asm_disk01.img,/oradata/asm_disk02.img,/oradata/asm_disk03.img,/oradata/asm_disk04.img,/oradata/asm_disk05.img",
                "OS_PASSWORD=Oracle_12c",
                "PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "SETUP_LINUX_FILE=setupLinuxEnv.sh",
                "INSTALL_DIR=/opt/scripts",
                "GRID_BASE=/u01/app/grid",
                "GRID_HOME=/u01/app/12.2.0/grid",
                "INSTALL_FILE_1=linuxx64_12201_grid_home.zip",
                "GRID_INSTALL_RSP=grid.rsp",
                "GRID_SETUP_FILE=setupGrid.sh",
                "FIXUP_PREQ_FILE=fixupPreq.sh",
                "INSTALL_GRID_BINARIES_FILE=installGridBinaries.sh",
                "INSTALL_GRID_PATCH=applyGridPatch.sh",
                "INVENTORY=/u01/app/oraInventory",
                "CONFIGGRID=configGrid.sh",
                "ADDNODE=AddNode.sh",
                "ADDNODE_RSP=grid_addnode.rsp",
                "SETUPSSH=setupSSH.expect",
                "GRID_PATCH=p27383741_122010_Linux-x86-64.zip",
                "PATCH_NUMBER=27383741",
                "SETUPDOCKERORACLEINIT=setupdockeroracleinit.sh",
                "DOCKERORACLEINIT=dockeroracleinit",
                "GRID_USER_HOME=/home/grid",
                "SETUPGRIDENV=setupGridEnv.sh",
                "DB_BASE=/u01/app/oracle",
                "DB_HOME=/u01/app/oracle/product/12.2.0/dbhome_1",
                "INSTALL_FILE_2=linuxx64_12201_database.zip",
                "DB_INSTALL_RSP=db_inst.rsp",
                "DBCA_RSP=dbca.rsp",
                "DB_SETUP_FILE=setupDB.sh",
                "PWD_FILE=setPassword.sh",
                "RUN_FILE=runOracle.sh",
                "STOP_FILE=stopOracle.sh",
                "ENABLE_RAC_FILE=enableRAC.sh",
                "CHECK_DB_FILE=checkDBStatus.sh",
                "USER_SCRIPTS_FILE=runUserScripts.sh",
                "REMOTE_LISTENER_FILE=remoteListener.sh",
                "INSTALL_DB_BINARIES_FILE=installDBBinaries.sh",
                "FUNCTIONS=functions.sh",
                "COMMON_SCRIPTS=/common_scripts",
                "CHECK_SPACE_FILE=checkSpace.sh",
                "EXPECT=/usr/bin/expect",
                "BIN=/usr/sbin",
                "container=true",
                "INSTALL_SCRIPTS=/opt/scripts/install",
                "SCRIPT_DIR=/opt/scripts/startup",
                "GRID_PATH=/u01/app/12.2.0/grid/bin:/u01/app/12.2.0/grid/OPatch/:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DB_PATH=/u01/app/oracle/product/12.2.0/dbhome_1/bin:/u01/app/oracle/product/12.2.0/dbhome_1/OPatch/:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GRID_LD_LIBRARY_PATH=/u01/app/12.2.0/grid/lib:/usr/lib:/lib",
                "DB_LD_LIBRARY_PATH=/u01/app/oracle/product/12.2.0/dbhome_1/lib:/usr/lib:/lib"
            ],
            "Cmd": [
                "/usr/sbin/oracleinit"
            ],
            "ArgsEscaped": true,
            "Image": "oracle/database-rac:12.2.0.1",
            "Volumes": {
                "/common_scripts": {},
                "/dev/shm": {}
            },
            "WorkingDir": "/home/grid",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "8df803a1c3d9dbb4646c7937a736e269cb475f4eee8cf15bd84f3465e5b443f9",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/8df803a1c3d9",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "rac_priv1_nw": {
                    "IPAMConfig": {
                        "IPv4Address": "192.168.17.150"
                    },
                    "Links": null,
                    "Aliases": [
                        "97feb1e355b7"
                    ],
                    "NetworkID": "fb7547e0be63a7d0385894ba39df9a9cac677414188e8116b5b4ed4b4abe2848",
                    "EndpointID": "f988387e8558ce869403e958d618216657e47087320a682ba1f3d79cf98c58b1",
                    "Gateway": "192.168.17.1",
                    "IPAddress": "192.168.17.150",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:c0:a8:11:96",
                    "DriverOpts": null
                },
                "rac_pub1_nw": {
                    "IPAMConfig": {
                        "IPv4Address": "172.15.1.150"
                    },
                    "Links": null,
                    "Aliases": [
                        "97feb1e355b7"
                    ],
                    "NetworkID": "8b3c1ffe9c9143a11f3e13141f8497604ba5eed5514ffa4f66d022f6fc7c9a89",
                    "EndpointID": "78802d113f056424a3a952df5dde8194569c46a3170979c042c7ec21d23e3f47",
                    "Gateway": "172.15.1.1",
                    "IPAddress": "172.15.1.150",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:0f:01:96",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by psaini79** [comment]
Are you still facing this issue?

**Comment by abcklocki** [comment]
Hi 
I have the same problem with Oracle RAC on docker. My machine is working on latest CentOS Linux release 7.5.1804.
I tested with docker from Centos repository and with docker from Oracle - the same result:

 ```
bash-4.2# tail -14 /tmp/cluvfy_check.txt

PRVG-11826 : DNS resolved IP addresses "" for SCAN name "racnode-scan" not
found in the name service returned IP addresses "10.15.171.131"
PRVG-11827 : Name service returned IP addresses "10.15.171.131" for SCAN name
"racnode-scan" not found in the DNS returned IP addresses ""

racnode1: PRVF-4664 : Found inconsistent name resolution entries for SCAN name
          "racnode-scan"


CVU operation performed:      stage -pre crsinst
Date:                         Aug 28, 2018 6:12:56 AM
CVU home:                     /u01/app/12.2.0/grid/
User:                         grid
```

Can You write how did you solve this problem ?
