### ISSUE TITLE
Preparing to update domain. Error: runCmd() failed. 64254: Error occurred in "OPSS Processing" phase execution

### ISSUE THREAD

**Issue by joanbaez** [oracle/docker-images#843]
Hi,

I've tride to create the soa containers but when wlst script for create domain is running i got the next error:

INFO: Creating Node Managers...
INFO: Creating Admin server...
INFO: SOA Servers created.....
INFO: Creating OSB cluster...
INFO: OSB Servers created.....
INFO: Writing base domain...
INFO: Base domain created at /u01/oracle/user_projects/domains/soa
INFO: Extending domain at /u01/oracle/user_projects/domains/soa
INFO: Applying JRF templates...
INFO: Applying SOA templates...
INFO: Extension Templates added
INFO: Configuring the Service Table DataSource...
INFO: Getting Database Defaults...
INFO: Targeting Server Groups...
INFO: Set CoherenceClusterSystemResource to defaultCoherenceCluster for server:soa_server1
INFO: Set CoherenceClusterSystemResource to defaultCoherenceCluster for cluster:soa_cluster
INFO: Set WLS clusters as target of defaultCoherenceCluster:[soa_cluster]
INFO: Preparing to update domain...
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/dockertools/createDomain.py", line 483, in ?
  File "/u01/oracle/dockertools/createDomain.py", line 115, in createDomain
  File "/u01/oracle/dockertools/createDomain.py", line 297, in extendSoaDomain
  File "/tmp/WLSTOfflineIni8683114591805883886.py", line 139, in updateDomain
  File "/tmp/WLSTOfflineIni8683114591805883886.py", line 19, in command
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: SecurityContext:
 Domain Name: soa
 JDBC URL: opss-audit-DBDS:jdbc:oracle:thin:@//soadb:1521/XE
 JDBC URL: opss-data-source:jdbc:oracle:thin:@//soadb:1521/XE
 JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
 JNDI Name: opss-data-source:jdbc/OpssDataSource
 Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
 Driver Name: opss-data-source:oracle.jdbc.OracleDriver
 Persistence Type: DATABASE
 Platform: WLS
 Scratch Dir: scratch
 Reconfig Domain: false
 Shared Secret Store: null
 Extension: true
 DisableManagementOperations: falseJDBC Properties:
user:SOA_IAU_APPEND
username:SOA_IAU_APPENDJDBC Properties:
user:SOA_OPSS
username:SOA_OPSS
64254: Check log for more detail.
null
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2983)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:735)
        at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Error updating domain:
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: SecurityContext:
 Domain Name: soa
 JDBC URL: opss-audit-DBDS:jdbc:oracle:thin:@//soadb:1521/XE
 JDBC URL: opss-data-source:jdbc:oracle:thin:@//soadb:1521/XE
 JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
 JNDI Name: opss-data-source:jdbc/OpssDataSource
 Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
 Driver Name: opss-data-source:oracle.jdbc.OracleDriver
 Persistence Type: DATABASE
 Platform: WLS
 Scratch Dir: scratch
 Reconfig Domain: false
 Shared Secret Store: null
 Extension: true
 DisableManagementOperations: falseJDBC Properties:
user:SOA_IAU_APPEND
username:SOA_IAU_APPENDJDBC Properties:
user:SOA_OPSS
username:SOA_OPSS
64254: Check log for more detail.
null

ERROR: Domain Configuration failed. Please check the logs

With any base image (created from Java 8 and image from oracle repository) i got the same errors.

Thank you in advance.

**Comment by vipinponnarath** [comment]
is there any update on this thread? I also get the exact same error if I recreate the fmw domain (domain is inside the image and I dont want to use volumes) pointing to the existing database which has the RCU already installed and loaded into the domain. The only way I can make it work is by removing both the database container and the fmw container and recreate them. Since I am not using volumes in both images, it takes pretty long, sorry, in my setup , i cannot use volumes because, i need to commit the resulting application image - any solutions would be appreciated

**Comment by renancastro** [comment]
Any update?

I'm having the same error running on Windows 10

**Comment by Djelibeybi** [comment]
Please provide the output of `docker info` from your host, but note that we do not support running on non-Linux platforms. You should first reproduce this issue on Oracle Linux 7 running Oracle Container Runtime for Docker.

**Comment by renancastro** [comment]
Here is the output:

Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d4b0100
ID: J5AN:33GY:RWW4:5OLQ:IQSE:UUN7:KPUA:I6FT:Y5DA:PEWT:DZWP:LOUF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 58
 System Time: 2019-06-05T22:14:38.6966446Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by Djelibeybi** [comment]
I also just noticed from your output that you're using overlay2 with extfs (or Docker for Windows does that automatically). There are known issues with this combination which is why we don't support it on Oracle Linux. I suggest using either the `btrfs` storage driver and file system or the `overlay2` storage driver with an `xfs` file system.

**Comment by rdas76** [comment]
From the logs we could see that this is while configuring domain type soaosb. This domain type is currently no supported. Create SOA and OSB as two separate domain types. SOAOSB combined domain type will be supported in future release.
