### ISSUE TITLE
oracecle/glassfish:5.0 error when deploy

### ISSUE THREAD

**Issue by quangvi282** [oracle/docker-images#845]
![screenshot from 2018-04-15 23-02-57](https://user-images.githubusercontent.com/7436522/38792302-2ec026b4-4101-11e8-9016-50d1dc14fcfe.png)
Help me fix issue on glassfish:5.0

**Comment by arinban** [comment]
I just tried to deploy one 'war'. It's working fine. Are you getting this issue while deploying any specific 'war' file? If yes, please give us the war file to test.

**Comment by arindam-bandyopadhyay** [comment]
@quangvi282 I just tried to deploy one 'war'. It's working fine. Are you getting this issue while deploying any specific 'war' file? If yes, please give us the war file to test.

**Comment by vitrinh282** [comment]
sr , i can't give .war

**Comment by arindam-bandyopadhyay** [comment]
As deployment is working as expected in docker image. Closing the issue. Please check if the deployment of the war fails in glassfish(non dockerized). If yes, please log a bug in https://github.com/javaee/glassfish/issues/
