### ISSUE TITLE
Change the example to development.mode

### ISSUE THREAD

**Issue by AdamBien** [oracle/docker-images#85]
Currently the weblogic sample 1221-domain (https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/1221-domain) file is shipped with production mode enabled. The mode should be either configurable, or the WLS should be shipped with "development" mode. 

The development mode enables auto-deployment, what a a convenient way to deploy applications on docker.

**Comment by brunoborges** [comment]
Yeah, we are aware of that. But due to how WLST scripts for 1221-domain sample have to be coded (with lock) to dynamically add Managed Servers during runtime, WLS must be executed in Production mode for this particlar sample.

I'll consider add another sample for development, thanks for the input!
