### ISSUE TITLE
Mount Volume not working for Docker DB

### ISSUE THREAD

**Issue by ashishWaghmare** [oracle/docker-images#853]
Post-build of below image, I am not able to start with a shared mount for persisting data permanently
https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/Dockerfile.ee

Without the mount, docker image starts correctly 

To debug I did logged in the image created using below command
docker run -it -v `pwd`/data:/opt/oracle/oradata oracle/database:12.1.0.2-ee bash
cd /opt/oracle/oradata 
touch t 
permission denied

As mentioned in documentaiton, I have given ownership of mount folder to user below
id oracle
uid=54321(oracle) gid=54321(oinstall) groups=54321(oinstall),54322(dba),54324(backupdba),54325(dgdba),54326(kmdba),54327(asmdba)

**Comment by gvenzl** [comment]
Can you please provide an `ls` on the location outside and inside the container. Note that the [Docker documentation](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems) states that the host path has to be absolute, which it doesn't seem to be in the run command above:

> -v, --volume=[host-src:]container-dest[:<options>]: Bind mount a volume.
The comma-delimited `options` are [rw|ro], [z|Z],
[[r]shared|[r]slave|[r]private], and [nocopy].
The 'host-src' is an absolute path or a name value.

**Comment by ashishWaghmare** [comment]
It worked with either z and Z appended to volume.

**Comment by ShawnMercado** [comment]
I'm having the same problem.  What do you mean "either z and Z appended to volume" ??
