### ISSUE TITLE
Location of oraInventory should be changed - outside $ORACLE_BASE - maybe to /opt/orainv or use OFA dirs under /u01/app

### ISSUE THREAD

**Issue by ghost** [oracle/docker-images#864]
ERROR MESSAGE: Currently not tested according Ubuntu docker engine - but have some patched files - that I can send you. 
INFO: Further I could not find some settings in $HOME/.bash_profile and found many files inside /etc/sysctl.d/*.conf.

````
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2018-05-05_03-43-31PM. Please wait ...[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
You can find the log of this install session at:
 /opt/oracle/oraInventory/logs/installActions2018-05-05_03-43-31PM.log
The installation of Oracle Database 12c was successful.
````

**Comment by gvenzl** [comment]
Hi @jochen-halwachs,

I don't quite follow your first to lines and what you mean.

As to the message below, this is a warning only. Why do you care where the `oraInventory` sits within a container? You should not care about anything that's inside the container, it's not a VM.

Or do you just want to get rid of the warning message?

**Comment by jochen-halwachs** [comment]
Yes only the warning message of oraInventory Location. 

By the way - it workes also on ubuntu 16.04 with overlay2 and deinstall docker that comes with normal apt-get installation.

**Comment by gvenzl** [comment]
Fair enough, I will look at it.

**Comment by gvenzl** [comment]
Closing the issue as these image and database versions have been superseded.
