### ISSUE TITLE
Setting filesystemio_options=SETALL causing log file sync latency increase and excessive kworker processes

### ISSUE THREAD

**Issue by Restomi** [oracle/docker-images#868]
Is there any guideline on setting Oracle database parameter filesystemio_options?

In most cases Oracle suggesting setting it to SETALL which implies using both Direct IO and Async IO if available. But I understand the default Oracle docker image does not have this value set.

We have oracle 12c database running on Docker 1.12.6 running in Redhat 7.4 server.
Database storage is built from locally attached nvme devices (12 devices configured as mdadm RAID10), and presented as ext4 filesystem to Oracle container.

Oracle parameter filesystemio_options is set to 'SETALL'.

We observed during benchmarking using Hammerdb, "log file sync" latency kept increasing over the benchmark run time (started from 0.x ms up-to 3.x ms), and regularly there will be a massive KWORKER processes consuming 60-80% of total system CPUs (out of 56 CPU cores). In some occurrences these KWORKER kept hogging CPU usage for about 30 minutes even though there's no more running workload.

This behaviour did not occur if we set parameter filesystemio_options to other values (directIO, Asynch, or None).

Any thoughts?

**Comment by gvenzl** [comment]
Hi @Restomi, I do not know enough about the Docker internals to make a statement whether `Direct IO` and/or `asynchronous IO` should or does work, or whether it can cause any issues.

What I can tell you is that Docker 1.12.6 is considered quite old in Docker terms ([released 10th of Jan 2017](https://docs.docker.com/release-notes/docker-engine/)).

My suggestion would be to try to reproduce this on the latest version and see whether you still have the issue.
If yes, then my next suggestion would be to talk to RedHat Support.

Or, if you can reproduce it on OL7 UEK4, we can check with the Oracle Linux and Docker guys.

**Comment by gvenzl** [comment]
Closing due to lack of response.
