### ISSUE TITLE
md5sum doesn't appropriately interpret comment lines in Checksum.* files

### ISSUE THREAD

**Issue by Makopo** [oracle/docker-images#87]
When I run with vanilla Checksum files:
<pre>
$ sh buildDockerImage.sh -v 12.2.1 -g
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_Disk1_1of1.zip: OK
md5sum: can't open '- http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html': No such file or directory
- http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html: FAILED
server-jre-8u77-linux-x64.tar.gz: OK
md5sum: WARNING: 8 of 10 computed checksums did NOT match
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 12.2.1. See *.download files for more information
</pre>

I modified a line in Checksum.generic
```
#  - http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html
```
by removing a space after a sharp
```
# - http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html
```

It helped somewhat, but the issue still persists.

<pre>
$ sh buildDockerImage.sh -v 12.2.1 -g
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_Disk1_1of1.zip: OK
server-jre-8u77-linux-x64.tar.gz: OK
md5sum: WARNING: 8 of 10 computed checksums did NOT match
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 12.2.1. See *.download files for more information
</pre>

I deleted all comment lines in Checksum.generic. It works fine now.

Environments:
Boot2Docker version 1.10.3, build master : 625117e - Thu Mar 10 22:09:02 UTC 2016
Docker version 1.10.3, build 20f81dd

**Comment by brunoborges** [comment]
Can you provide the version output of md5sum of your env?

**Comment by Makopo** [comment]
Docker Toolbox creates busybox environment in a docker machine...
md5sum command seems to have limited options.

```
$ md5sum --help
BusyBox v1.23.1 (2015-02-22 15:53:49 UTC) multi-call binary.

Usage: md5sum [-c[sw]] [FILE]...

Print or check MD5 checksums

	-c	Check sums against list in FILEs
	-s	Don't output anything, status code shows success
	-w	Warn about improperly formatted checksum lines
```

**Comment by brunoborges** [comment]
Then skip the MD5 check with `-s` in the buildDockerImage.sh call.
