### ISSUE TITLE
Oracle OSA 18.1 Image

### ISSUE THREAD

**Issue by sblack4** [oracle/docker-images#871]
# Oracle Stream Analytics

Hey, I'm pumped for  OSA 18.1 - http://www.oracle.com/technetwork/middleware/complex-event-processing/overview/index.html - and want a lightweight environment to learn about it/build demos in

I saw the download had been posted for v18.1 - http://www.oracle.com/technetwork/middleware/complex-event-processing/downloads/index.html, and I don't mind contributing the image & associated files. You can contact me at steven.black@oracle.com for the contributor agreement and whatnot. 

Thanks! 

---
I also noticed the startling lack of OSA for v12 but was able to find [a workable copy](https://github.com/gschmutz/dockerfiles)

**Comment by sblack4** [comment]
https://github.com/sblack4/docker-images/tree/871-osa

**Comment by Djelibeybi** [comment]
I will follow up with you via email.
