### ISSUE TITLE
Can't login to container-registry with DockerMachine for macOS - registry v2 is required

### ISSUE THREAD

**Issue by amad** [oracle/docker-images#874]
I don't have this issue on my Linux machine but it doesn't work on macOS DockerMachine.
I think you are using legacy auth which is now broken in DockerMachine.

```
$ docker login container-registry.oracle.com
Username (****@gmail.com):
Password: 
Login Succeeded

$ docker pull container-registry.oracle.com/instantclient:12.2.0.1
Error response from daemon: pull access denied for container-registry.oracle.com/instantclient, repository does not exist or may require 'docker login'

```

How to reproduce: try to pull any Oracle image with the latest stable DockerMachine.

**Comment by Djelibeybi** [comment]
This is not the right place to report issues with Oracle Container Registry. Please open an SR with Oracle Support for this issue.
