### ISSUE TITLE
Oracle 12C with Win 2016

### ISSUE THREAD

**Issue by GillIntergraph** [oracle/docker-images#890]
Hi

I am trying to create a container  Oracle 12C using microsoft/windowsservercore image. 

I am able to install the Oracle software silently. Below are the steps 

1) Install Oracle 12C Database  -- Success
`start-process setup.exe -WorkingDirectory X:\Oracledatabase_12010002\database  -ArgumentList  "-responseFile X:\db_install.rsp -noconfig -nowelcome -silent" -wait`

2) Configure netca  -- Success 
`start-process netca -ArgumentList  "-silent -responseFile X:\netca.rsp" -wait`

3) Crate Database -- Failed

`Start-Process X:\ora12010002\database64\BIN\dbca.bat -ArgumentList " -silent -createDatabase -SystemPassword oracle123 -SysPassword oracle123 -listeners listener -databaseType DATA_WAREHOUSING -templateName X:\setup\OracleDatabase_12010002\Instance_Creation\DBBUILD.dbc -gdbname DBBUILD -sid DBBUILD -initparams db_recovery_file_dest_size=50G -initparams pga_aggregate_target=1G-initparams sga_target=3G -initparams sga_max_size=5G -initparams processes=5 -initparams open_cursors=50"  -Wait`

form the log found below

Unique database identifier check passed.

C:\ has enough space. Required space is 2050 MB , available space is 11787 MB.
File Validations Successful.
Cleaning up failed steps
DBCA_PROGRESS : 5%
Copying database files
DBCA_PROGRESS : 7%
DBCA_PROGRESS : 8%
**ORA-03113: end-of-file on communication channel**
DBCA_PROGRESS : 9%
DBCA_PROGRESS : 10%
ORA-03114: not connected to ORACLE
ORA-03114: not connected to ORACLE
DBCA_PROGRESS : DBCA Operation failed.

Any help

Thanks

**Comment by gvenzl** [comment]
You will have to have a look at the trace files of the installation why the database installation failed.
