### ISSUE TITLE
Re-running this against same db gives error

### ISSUE THREAD

**Issue by oeresundsgruppen** [oracle/docker-images#892]
How to deal with : Caused by: oracle.security.opss.tools.lifecycle.LifecycleException: The schema OEDQ_OPSS is already in use for security store(s).  Please create a new schema. - without running rcu twice... Drop and Create ?

**Comment by oeresundsgruppen** [comment]
Must be a simple update on OPSS schema to reset it to new....

**Comment by Djelibeybi** [comment]
I'm sorry, but can you provide more information, starting with which image you're having an issue with in the first place?

**Comment by oeresundsgruppen** [comment]
OEDQ WLST installation cannot be re-run.... Oracle products are truely a nightmare...

**Comment by rdas76** [comment]
Not able to reproduce this. This could only come if there is any residue in the DB or the volume..
Since this is on the docker and its for development, pls simply cleanup the volume and create a new DB and recreate the instance.
