### ISSUE TITLE
SOA managed server started by 'startMS.sh' get wrong status

### ISSUE THREAD

**Issue by anti996sz** [oracle/docker-images#895]
[logs.zip](https://github.com/oracle/docker-images/files/2083826/logs.zip)
Wehn I following SOA Suite Docker image build [readme file](https://github.com/oracle/docker-images/blob/master/OracleSOASuite/dockerfiles/README.md) to build image for version 12.2.1.3, get to the last step to 'Creating a container for SOA Server', it works when set ADMIN_HOST with AdminServer container name 'soaas' in the file 'soaserver.env.list'. After that, I have a test and found the SOA managed server State in AdminServer Web Console is 'SHUTDOWN', Health is 'Not reachable'. 
In EM Console, SOA managed server State is 'Running', but Health is 'Unknown'.
I also found the value of Machine field of SOA managed server is same as Admin server, I think since they are running in deffrent Docker containers, the Machine value should be deffrent also, isn't correct? How to fix my problem?
I also raised a discussion for help in Oracle community, more details can be seen [there](https://community.oracle.com/thread/4150732).
All the logs file are attached.

**Comment by scottwan** [comment]
Finally get the temporary solution from [Maarten Smeets's blog](http://javaoraclesoa.blogspot.com/2018/05/soa-suite-12c-in-docker-containers-only.html). Whatever, I'd like this issue can be solved from the root, so that SOA managed server support mutilple deployment in a single Docker host or cross Docker hosts.

**Comment by rdas76** [comment]
Not reproduced when the documentation is followed.
