### ISSUE TITLE
Build image from Windows 10 over docker-machine fails because of wrong file encoding of shell scripts

### ISSUE THREAD

**Issue by suikast42** [oracle/docker-images#897]
Hi guys,

I build the 11g image with the Dockerfile. But oracle doesn't start with the error message 

`/bin/bash^M:: No such file or directory`

The reason is that the run script in to the docker container with not unix encoding for EOF. 

The folowing steps solves my problem. 
1. Install vi
2. Add further RUN command after the fat piped RUN in the Dockerfile
  `RUN  vi +':w ++ff=unix' +':q' $ORACLE_BASE/$RUN_FILE `
 `RUN  vi +':w ++ff=unix' +':q' $ORACLE_BASE/$PWD_FILE `
 `RUN  vi +':w ++ff=unix' +':q' $ORACLE_BASE/$CHECK_DB_FILE  `

**Comment by gvenzl** [comment]
Hi @suikast42, I believe this is a problem on your machine and happened perhaps when cloning the repo.
The files are all in Unix character encoding in the repo:

```
gvenzl-mac:11.2.0.2 gvenzl$ cd ~/git/docker-images/OracleDatabase/SingleInstance/dockerfiles/11.2.0.2/
gvenzl-mac:11.2.0.2 gvenzl$ file runOracle.sh
runOracle.sh: Bourne-Again shell script text executable, ASCII text
gvenzl-mac:11.2.0.2 gvenzl$ file -I runOracle.sh
runOracle.sh: text/x-shellscript; charset=us-ascii
gvenzl-mac:11.2.0.2 gvenzl$ file checkDBStatus.sh
checkDBStatus.sh: Bourne-Again shell script text executable, ASCII text
gvenzl-mac:11.2.0.2 gvenzl$ file setPassword.sh
setPassword.sh: Bourne-Again shell script text executable, ASCII text
```

If they were Windows `file` would print an output `ASCII text, with CRLF line terminators`.

**Comment by gvenzl** [comment]
Closing due to lack of response.
