### ISSUE TITLE
Wish domain type 'soaosbb2b' also supported in SOA Suite docker image

### ISSUE THREAD

**Issue by anti996sz** [oracle/docker-images#900]
When I study the scripts in 'docker-images/OracleSOASuite/dockerfiles/12.2.1.3/container-scripts', and find domainType "soaosb" also supported,  I get this from the file '[createDomain.py](https://github.com/oracle/docker-images/blob/master/OracleSOASuite/dockerfiles/12.2.1.3/container-scripts/createDomain.py)' Line 161.

I wish domain type 'soaosbb2b' also supported, this means I needn't create three AdminServer for SOA, OSB and B2B managed servers respectively, they will share the same AdminServer, and running in a same domain.

**Comment by rdas76** [comment]
B2B templates are not applied and hence B2B is not available. Hence, this is not supported. However, it may be supported in future release.
