### ISSUE TITLE
Split repo into multiple repos, per product

### ISSUE THREAD

**Issue by jesstruck** [oracle/docker-images#902]
It would be really nice if this repository could be split into many repositories, one per product.
So that we could depend, on the product that we use, and avoid getting the ones that we do not use.

**Comment by Djelibeybi** [comment]
What's wrong with getting Dockerfiles for products you don't use? The entire repo is 22MB and clones in under 20 seconds for me in Australia. 

I'm sorry, but I don't see any benefit in splitting this repo considering how the extra effort that would be required to manage so many individual repos.
