### ISSUE TITLE
pull access denied for oracle/client-cman..//

### ISSUE THREAD

**Issue by smbptnk** [oracle/docker-images#909]
##docker-images/OracleDatabase/RAC/OracleConnectionManager/README.md

During setup of Oracle Connection Manager on Docker got below error . I tried cleaning docker images for fresh install. Still getting this error every time. Any pointers will be highly appreciated.
---
Login Succeeded
root@xxx:~#    /usr/bin/docker run -d --hostname racnode-cman1 --dns-search=example.com \
>   --network=rac_pub1_nw --ip=172.15.1.15 \
>   -e DOMAIN=example.com -e PUBLIC_IP=172.15.1.15 \
>   -e PUBLIC_HOSTNAME=racnode-cman1 -e SCAN_NAME=racnode-scan \
>   -e SCAN_IP=172.15.1.70 --privileged=false \
>   -p 1521:1521 --name racnode-cman oracle/client-cman:12.2.0.1
Unable to find image 'oracle/client-cman:12.2.0.1' locally
/usr/bin/docker: Error response from daemon: pull access denied for oracle/client-cman, repository does not exist or may require 'docker login'.
See '/usr/bin/docker run --help'.

**Comment by psaini79** [comment]
Please send me the output of following:

docker images
docker ps -a
systemctl status docker
docker info

**Comment by smbptnk** [comment]
Hi

Please find the detail as requested - 

root@rolex:~# docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
hello-world                        latest              e38bc07ac18e        2 months ago        1.85kB
store/oracle/database-enterprise   12.2.0.1            12a359cd0528        10 months ago       3.44GB
root@rolex:~# docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                    PORTS                NAMES
d0bbf8b88b54        store/oracle/database-enterprise:12.2.0.1   "/bin/sh -c '/bin/ba…"   34 hours ago        Up 10 hours (healthy)     1521/tcp, 5500/tcp   orclcdb
269887843efa        hello-world                                 "/hello"                 34 hours ago        Exited (0) 34 hours ago                        boring_volhard
62b54ffdea45        hello-world                                 "/hello"                 35 hours ago        Exited (0) 35 hours ago                        gallant_kirch
9104ea9edcea        hello-world                                 "/hello"                 35 hours ago        Exited (0) 35 hours ago                        heuristic_aryabhata
221af531ca81        hello-world                                 "/hello"                 36 hours ago        Exited (0) 36 hours ago                        upbeat_chebyshev
root@rolex:~# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-06-26 10:17:52 IST; 9h ago
     Docs: https://docs.docker.com
 Main PID: 4026 (dockerd)
    Tasks: 35
   Memory: 82.4M
      CPU: 1min 43.677s
   CGroup: /system.slice/docker.service
           ├─ 2374 ora_w004_ORCLCDB
           ├─ 2427 ora_w000_ORCLCDB
           ├─ 2652 ora_w001_ORCLCDB
           ├─ 2658 ora_w002_ORCLCDB
           ├─ 2665 ora_w003_ORCLCDB
           ├─ 2853 ora_w007_ORCLCDB
           ├─ 4026 /usr/bin/dockerd -H fd://
           ├─ 4044 docker-containerd --config /var/run/docker/containerd/containerd.toml
           ├─ 4524 docker-containerd-shim -namespace moby -workdir /mnt/b2/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/d0bbf8b88b54990596ade127c9c7186b391ed8dd81d713f670c76216160
           ├─ 4542 /bin/bash /home/oracle/setup/dockerInit.sh
           ├─ 4940 /u01/app/oracle/product/12.2.0/dbhome_1/bin/tnslsnr LISTENER -inherit
           ├─ 4997 tail -f /u01/app/oracle/diag/rdbms/orclcdb/ORCLCDB/trace/alert_ORCLCDB.log
           ├─ 6266 bash -c source /home/oracle/.bashrc; sqlplus /nolog
           ├─ 6287 sqlplus       
           ├─27511 ora_pmon_ORCLCDB
           ├─27513 ora_clmn_ORCLCDB
           ├─27515 ora_psp0_ORCLCDB
           ├─27517 ora_vktm_ORCLCDB
           ├─27521 ora_gen0_ORCLCDB
           ├─27523 ora_mman_ORCLCDB
           ├─27527 ora_gen1_ORCLCDB
           ├─27531 ora_diag_ORCLCDB
           ├─27533 ora_ofsd_ORCLCDB
           ├─27537 ora_dbrm_ORCLCDB
           ├─27539 ora_vkrm_ORCLCDB
           ├─27541 ora_svcb_ORCLCDB
           ├─27543 ora_pman_ORCLCDB
           ├─27545 ora_dia0_ORCLCDB
           ├─27547 ora_dbw0_ORCLCDB
           ├─27549 ora_lgwr_ORCLCDB
           ├─27551 ora_ckpt_ORCLCDB
           ├─27553 ora_lg00_ORCLCDB
           ├─27555 ora_smon_ORCLCDB
           ├─27557 ora_lg01_ORCLCDB
           ├─27559 ora_smco_ORCLCDB
           ├─27561 ora_reco_ORCLCDB
           ├─27565 ora_lreg_ORCLCDB
           ├─27569 ora_pxmn_ORCLCDB
           ├─27573 ora_mmon_ORCLCDB
           ├─27575 ora_mmnl_ORCLCDB
           ├─27577 ora_d000_ORCLCDB
           ├─27579 ora_s000_ORCLCDB
           ├─27581 ora_tmon_ORCLCDB
           ├─27590 oracleORCLCDB (DESCRIPTION=(LOCAL=YES)(ADDRESS=(PROTOCOL=beq)))
           ├─27592 ora_p000_ORCLCDB
           ├─27594 ora_p001_ORCLCDB
           ├─27597 ora_tt00_ORCLCDB
           ├─27599 ora_tt01_ORCLCDB
           ├─27601 ora_tt02_ORCLCDB
           ├─27603 ora_aqpc_ORCLCDB
           ├─27607 ora_p002_ORCLCDB
           ├─27609 ora_p003_ORCLCDB
           ├─27611 ora_p004_ORCLCDB
           ├─27613 ora_p005_ORCLCDB
           ├─27615 ora_p006_ORCLCDB
           ├─27617 ora_p007_ORCLCDB
           ├─27768 ora_qm02_ORCLCDB
           ├─27772 ora_q002_ORCLCDB
           ├─27774 ora_q003_ORCLCDB
           ├─27822 ora_cjq0_ORCLCDB
           └─28444 ora_w005_ORCLCDB

Jun 26 10:17:50 rolex dockerd[4026]: time="2018-06-26T10:17:50.999197878+05:30" level=info msg="Loading containers: start."
Jun 26 10:17:52 rolex dockerd[4026]: time="2018-06-26T10:17:52.016188997+05:30" level=info msg="Removing stale sandbox ca84a282932de410a107772c439498d6e0be6d32aa81a09828963899b9f4f15d (d0bbf8b88b
Jun 26 10:17:52 rolex dockerd[4026]: time="2018-06-26T10:17:52.100796348+05:30" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint d29a57995794
Jun 26 10:17:52 rolex dockerd[4026]: time="2018-06-26T10:17:52.282561337+05:30" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be u
Jun 26 10:17:52 rolex dockerd[4026]: time="2018-06-26T10:17:52.414444450+05:30" level=info msg="Loading containers: done."
Jun 26 10:17:52 rolex dockerd[4026]: time="2018-06-26T10:17:52.564324615+05:30" level=info msg="Docker daemon" commit=9ee9f40 graphdriver(s)=overlay2 version=18.03.1-ce
Jun 26 10:17:52 rolex dockerd[4026]: time="2018-06-26T10:17:52.565002123+05:30" level=info msg="Daemon has completed initialization"
Jun 26 10:17:52 rolex dockerd[4026]: time="2018-06-26T10:17:52.575819108+05:30" level=info msg="API listen on /var/run/docker.sock"
Jun 26 10:17:52 rolex systemd[1]: Started Docker Application Container Engine.
Jun 26 10:20:30 rolex dockerd[4026]: time="2018-06-26T10:20:30+05:30" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/d0bbf8b88b54990596ade127c9c7186b391ed8dd8
root@rolex:~# docker info
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 2
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-39-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.812GiB
Name: rolex
ID: LY7A:467Q:I2DX:RJQ5:TBS7:KIVE:DKEP:HYF6:MPOP:R64C:UNIR:ZBN5
Docker Root Dir: /mnt/b2/docker
Debug Mode (client): false
Debug Mode (server): false
Username: smbptnk
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

Is it something to do with OCA signoff. Not sure though

Thanks

**Comment by smbptnk** [comment]
Any pointers.. and suggestions. My RAC installation is stuck due to this error

**Comment by psaini79** [comment]
Hi,

This is strange as I tried again and I did not encounter this issue.
Please see the docker image output from my env
bash-4.2# docker images
REPOSITORY                                                      TAG                 IMAGE ID            CREATED             SIZE
oracle/client-cman                                              12.2.0.1            c11c4b01dcae        6 hours ago         4.58GB
oracle/database-rac                                             12.2.0.1            aa06aa1d577c        8 days ago          32.8GB

In your case I do not see oracle/client-cman  image. Where did you create it?

**Comment by psaini79** [comment]
Are you trying to pull it from OCR?

**Comment by psaini79** [comment]
Oracle Container Registry?

**Comment by smbptnk** [comment]
Hi  Saini,

while I'm trying to run the below command, I got this error though I'm have successfully logged in
--Unable to find image 'oracle/client-cman:12.2.0.1' locally
/usr/bin/docker: Error response from daemon: pull access denied for oracle/client-cman, repository does not exist or may require 'docker login'.

command: 
Oracle Connection Manager on Docker - Create Containers in

    Execute following command as root user to create connection manager container.

       /usr/bin/docker run -d --hostname racnode-cman1 --dns-search=example.com \
      --network=rac_pub1_nw --ip=172.15.1.15 \
      -e DOMAIN=example.com -e PUBLIC_IP=172.15.1.15 \
      -e PUBLIC_HOSTNAME=racnode-cman1 -e SCAN_NAME=racnode-scan \
      -e SCAN_IP=172.15.1.70 --privileged=false \
      -p 1521:1521 --name racnode-cman oracle/client-cman:12.2.0.1

Earlier I as you mentioned oracle/client-cman 12.2.0.1 was in my local image directory. But due to some issue with later steps , I removed all images using docker rmi. May be I need a clean install again.

Could you please suggest,  steps to uninstall uninstall everything and start again.

Thanks is adv.

**Comment by psaini79** [comment]
Please try to create image locally and test it again as issue might have disappeared after deleting all the images.

If the issue persist, I would suggest please follow the install section (Chapter 2) of Oracle Docker install guide.

https://docs.oracle.com/cd/E52668_01/E87205/html/index.html

For cleaning up:
1) Remove existing RPMs of docker 
2) Remove docker file system from /var/lib/docker and recreate a new one.
3) Remove docker conf files from /etc. You can search them and remove before installation.

**Comment by smbptnk** [comment]
Thank you!!
