### ISSUE TITLE
Internal Error: File Copy failed. Aborting Install while installing oracle FMW

### ISSUE THREAD

**Issue by jobsforprabu** [oracle/docker-images#915]
Hi Team,

we are seeing the below issue while installing oracle FMW

Copyright (c) 1996, 2017, Oracle and/or its affiliates. All rights reserved.
Reading response file..
Skipping Software Updates
Validations are disabled for this session.
Verifying data
Copying Files
Percent Complete : 10
Percent Complete : 20
Internal Error: File Copy failed. Aborting Install

The log(s) can be found here: /tmp/OraInstall2018-06-28_09-38-05AM.
Removing intermediate container 8b86ddd9b530
The command '/bin/sh -c cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     $JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE="WebLogic Server" &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 1
There was an error building the image.

**Comment by mriccell** [comment]
@jobsforprabu  Are you building using the buildDockerImage.sh with -s option to check the MD5 sum of the install file?

**Comment by mriccell** [comment]
@jobsforprabu are you still seeing this error?

**Comment by mriccell** [comment]
Closing the issue due to lack of activity.

**Comment by lizhibing** [comment]
@mriccell I found the same problem here. See the following log Step 10/19 : RUN cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     $JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE="WebLogic Server" &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file
 ---> Running in 230610d535aa
/
Launcher log file is /tmp/OraInstall2019-02-28_06-25-09AM/launcher2019-02-28_06-25-09AM.log.
Extracting the installer . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Done
Checking if CPU speed is above 300 MHz.   Actual 2593.994 MHz    Passed
Checking swap space: must be greater than 512 MB.   Actual 2046 MB    Passed
Checking if this platform requires a 64-bit JVM.   Actual 64    Passed (64-bit not required)
Checking temp space: must be greater than 300 MB.   Actual 1900 MB    Passed
Preparing to launch the Oracle Universal Installer from /tmp/OraInstall2019-02-28_06-25-09AM
Log: /tmp/OraInstall2019-02-28_06-25-09AM/install2019-02-28_06-25-09AM.log
Setting ORACLE_HOME to /u01/oracle
Setting INSTALL_TYPE to WebLogic Server
Copyright (c) 1996, 2017, Oracle and/or its affiliates. All rights reserved.
Reading response file..
Skipping Software Updates
Validations are disabled for this session.
Verifying data
Copying Files
Percent Complete : 10
Percent Complete : 20
Percent Complete : 30
Percent Complete : 40
Percent Complete : 50
Internal Error: File Copy failed. Aborting Install

The log(s) can be found here: /tmp/OraInstall2019-02-28_06-25-09AM.
Removing intermediate container 230610d535aa
The command '/bin/sh -c cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     $JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE="WebLogic Server" &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 1
There was an error building the image.

**Comment by ganesh5756** [comment]
Got the same issue 

Removing intermediate container 2601688f6c3f
 ---> 8cfc245d4a27
Step 10/13 : USER oracle
 ---> Running in c9310fc9627b
Removing intermediate container c9310fc9627b
 ---> 55ab63afeaca
Step 11/13 : RUN cd /u01 && ${JAVA_HOME}/bin/jar xf /u01/$FMW_PKG && cd - &&     ${JAVA_HOME}/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file
 ---> Running in 13533e1921de
/
Launcher log file is /tmp/OraInstall2019-05-09_08-44-20PM/launcher2019-05-09_08-44-20PM.log.
Extracting the installer . . . . . . Done
The current user is root or has superuser privilege.
The Oracle Universal Installer cannot continue.
The log is located here: /tmp/OraInstall2019-05-09_08-44-20PM/launcher2019-05-09_08-44-20PM.log.
The command '/bin/sh -c cd /u01 && ${JAVA_HOME}/bin/jar xf /u01/$FMW_PKG && cd - &&     ${JAVA_HOME}/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 1
There was an error building the image.

**Comment by siddharth2006** [comment]
Hi , Were you all able to fix the issue ? I am facing the same
