### ISSUE TITLE
tuxedo container don't run

### ISSUE THREAD

**Issue by esteve01** [oracle/docker-images#921]
hi, when i try to run the tuxedo container, it won't start, i only see the message of the init.sh file, i thing that i'm missing something
file init.sh:
#!/bin/bash

cat <<EOF
This sample Docker image is provided by Oracle and is designed to be used as a base image from which you can build Tuxedo-based applications.
To help you get started customizing this image, we've provided two sample applications ("shm" and "mp") in the Oracle Docker Images GitHub repository. These samples demonstrate how to deploy applications, source code, configuration files and the other necessary settings to build Tuxedo-enabled application containers.
For more information on this image, please visit the Oracle Docker Images GitHub repository at https://github.com/oracle/docker-images.
For more information on Tuxedo, please read the Oracle Tuxedo documentation at http://docs.oracle.com/cd/E72452_01/tuxedo/docs1222/index.html.
EOF

and i try to run with:
docker run -it <image> 

when i run docker ps -a:
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                      PORTS               NAMES
84b05357aa43        oracle/tuxedo:12.2.2          "/u01/oracle/init.sh "   12 seconds ago      Exited (0) 9 seconds ago                        awesome_lumiere

can anyone help me please??

**Comment by toddinpal** [comment]
Hi,
You have to customize the image with your own Tuxedo servers and customize the init script so it doesn't exit.  Normally in the init.sh script you would boot your Tuxedo application and then sleep forever or something similar so the container doesn't exit.

**Comment by esteve01** [comment]
i see, you' re right, ok, thank you for helping me, i'm gonna try to config any app and the init.sh file, thanks again  :)
