### ISSUE TITLE
weblogic12c Service always shut down while run weblogic:12.2.1.3-generic container

### ISSUE THREAD

**Issue by wend1989** [oracle/docker-images#923]
Here is my steps to build weblogic:12.2.1.3-generic container！
1. build a local/oraclelinux7.5 image successfully
2. build a oracle/serverjre:8 image successfully
3. build a oracle/weblogic:12.2.1.3-generic image successfully by buildDockerImage.sh
$ sh buildDockerImage.sh -v 12.2.1.3 -g
4. run the container 
$ docker run -d -p 7001:7001 -p 9002:9002 --name weblogic12c -v /u01/oracle/properties:/u01/oracle/properties oracle/weblogic:12.2.1.3-generic

Here comes the problem:
container run well ，but weblogic service cant get up！
-----------------------------------------
Here is weglogic logs：
###########
<Cannot find identity keystore file /u01/oracle/user_projects/domains/base_domain/security/DemoIdentity.jks on server AdminServer> 
<Jul 6, 2018 4:37:07,660 PM CST> <Error> <WebLogicServer> <BEA-000297> <Inconsistent security configuration, weblogic.management.configuration.ConfigurationException: Cannot find identity keystore file /u01/oracle/user_projects/domains/base_domain/security/DemoIdentity.jks on server AdminServer> 
<Jul 6, 2018 4:37:07,704 PM CST> <Emergency> <Security> <BEA-090034> <Not listening for SSL, weblogic.management.configuration.ConfigurationException: Cannot find identity keystore file /u01/oracle/user_projects/domains/base_domain/security/DemoIdentity.jks on server AdminServer.> 
<Jul 6, 2018 4:37:07,790 PM CST> <Notice> <Security> <BEA-090946> <Security pre-initializing using security realm: myrealm> 
<Jul 6, 2018 4:37:08,076 PM CST> <Notice> <Security> <BEA-090947> <Security post-initializing using security realm: myrealm> 
<Jul 6, 2018 4:37:08,554 PM CST> <Notice> <Security> <BEA-090082> <Security initialized using administrative security realm: myrealm> 
<Jul 6, 2018 4:37:08,572 PM CST> <Critical> <Security> <BEA-090402> <Authentication denied: Boot identity not valid. The user name or password or both from the boot identity file (boot.properties) is not valid. The boot identity may have been changed since the boot identity file was created. Please edit and update the boot identity file with the proper values of username and password. The first time the updated boot identity file is used to start the server, these new values are encrypted.> 
<Jul 6, 2018 4:37:08,675 PM CST> <Critical> <WebLogicServer> <BEA-000362> <Server failed
##############

I know it caused by this is no DemoIdentity.jks file and SSL configuration isn‘t configurated，but shouldn‘t it be created and  configurationed by default ？Then we can update the WebLogic server SSL configuration  with a custom identity certificate though console web？
-----------------------------------------

I juts know how to configurate ssl though console web ，but service cant get up without default ssl configuration then cant login the console web！ What  can i do for SSL configuration for weblogic12c without  console web？ @Djelibeybi

**Comment by mriccell** [comment]
@wend1989  The problem with the generation of the Demo Key, DemoIdentity.jks  is resolved in PSU 12.2.1.3.180417.  Please download the PSU patch and apply it after you have built the 12.2.1.3 image.  You can follow the sample https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12211-patch to see how to patch.  An alternative is to not enable Administration port when you do the docker run, e.g:
$docker run -d -p 7001:7001 -v `HOST PATH where the domain.properties file is`:/u01/oracle/properties -e ADMINISTRATION_PORT_ENABLED=false -e DOMAIN_HOME=/u01/oracle/user_projects/domains/abc_domain -e DOMAIN_NAME=abc_domain oracle/weblogic:12.2.1.3-developer

Hope this helps, I will edit the README to provide this information.

**Comment by wend1989** [comment]
I'm really appreciate for your help!-------- 原始邮件 --------主题：Re: [oracle/docker-images] weblogic12c Service always shut down while run weblogic:12.2.1.3-generic container (#923)发件人：Monica Riccelli 收件人：oracle/docker-images 抄送：wend1989 <504916946@qq.com>,Mention @wend1989  The problem with the generation of the Demo Key, DemoIdentity.jks  is resolved in PSU 12.2.1.3.180417.  Please download the PSU patch and apply it after you have built the 12.2.1.3 image.  You can follow the sample https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12211-patch to see how to patch.  An alternative is to not enable Administration port when you do the docker run, e.g:
$docker run -d -p 7001:7001 -v HOST PATH where the domain.properties file is:/u01/oracle/properties -e ADMINISTRATION_PORT_ENABLED=false -e DOMAIN_HOME=/u01/oracle/user_projects/domains/abc_domain -e DOMAIN_NAME=abc_domain oracle/weblogic:12.2.1.3-developer
Hope this helps, I will edit the README to provide this information.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/oracle/docker-images","title":"oracle/docker-images","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/oracle/docker-images"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mriccell in #923: @wend1989  The problem with the generation of the Demo Key, DemoIdentity.jks  is resolved in PSU 12.2.1.3.180417.  Please download the PSU patch and apply it after you have built the 12.2.1.3 image.  You can follow the sample https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12211-patch to see how to patch.  An alternative is to not enable Administration port when you do the docker run, e.g:\r\n$docker run -d -p 7001:7001 -v `HOST PATH where the domain.properties file is`:/u01/oracle/properties -e ADMINISTRATION_PORT_ENABLED=false -e DOMAIN_HOME=/u01/oracle/user_projects/domains/abc_domain -e DOMAIN_NAME=abc_domain oracle/weblogic:12.2.1.3-developer\r\n\r\nHope this helps, I will edit the README to provide this information."}],"action":{"name":"View Issue","url":"https://github.com/oracle/docker-images/issues/923#issuecomment-405336597"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/oracle/docker-images/issues/923#issuecomment-405336597",
"url": "https://github.com/oracle/docker-images/issues/923#issuecomment-405336597",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [oracle/docker-images] weblogic12c Service always shut down while run weblogic:12.2.1.3-generic container (#923)",
"sections": [
{
"text": "",
"activityTitle": "**Monica Riccelli**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@mriccell",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"oracle/docker-images\",\n\"issueId\": 923,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"oracle/docker-images\",\n\"issueId\": 923\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/oracle/docker-images/issues/923#issuecomment-405336597"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353666612\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mriccell** [comment]
@wend1989 Please see PR #936 for resolution.
Thanks
Monica

**Comment by little-fish** [comment]
What is the purpose of hiding patch behind paid support.oracle.com?

**Comment by Djelibeybi** [comment]
Patches for WebLogic require an active Oracle support subscription regardless of deployment method.

**Comment by willzhang** [comment]
it help me for turn off the port
```
docker run -d -p 7001:7001 -p 9002:9002 \
	-v /data/weblogic:/u01/oracle/properties \
	-e ADMINISTRATION_PORT_ENABLED=true \
	-e DOMAIN_NAME=base_domain \
	oracle/weblogic:12.2.1.3-generic
```
i find the patch for three days ,nothing get!!
