### ISSUE TITLE
Code owner for Tuxedo is wrong?

### ISSUE THREAD

**Issue by gvenzl** [oracle/docker-images#925]
Code owner for Tuxedo shows @toddinpal, however, he is not in the docker-images team nor can I assign issue to him.

**Comment by toddinpal** [comment]
Hi Gerald, how do I change the owner?  Once I know that, I'll change it to someone in the Tuxedo team.

**Comment by gvenzl** [comment]
Hey @toddinpal, you can just PR an updated codeowners file over. You are gone from the team so I don't think you can still write into this repo but you should always be able to clone & PR. Alternatively, you can just tell @Djelibeybi or myself who the new owner is and we adjust accordingly. :)
