### ISSUE TITLE
Pre-built DB container created another instance on start-up

### ISSUE THREAD

**Issue by lkiii** [oracle/docker-images#927]
I have an image of [Pre-built DB](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/prebuiltdb#example-of-creating-an-image-with-pre-built-db) and the issue is that after running this image another instance `DB` is created. I have custom schema created during image preparation and I would like to keep only one instance running inside the container. How can I solve this issue?

**Comment by gvenzl** [comment]
Hey @lkiii, have you made sure that the `VOLUME` instruction is gone? Otherwise, your custom DB would have ended up in a anonymous volume and not persisted into the image.

**Comment by lkiii** [comment]
Yes. Volume was commented out for image preparation. When I am starting db I am getting during the startup:
```
......
db_1  | Copying database files
db_1  | 1% complete
db_1  | 2% complete
db_1  | 18% complete
db_1  | 33% complete
db_1  | Creating and starting Oracle instance
.....
```

Also custom schema created during the image preparation is present in the container created, but DB instance is additionally created. `grep $ORACLE_HOME /etc/oratab` returns 
```
DB:/opt/oracle/product/12.2.0.1/dbhome_1:N
mycustomschema:/opt/oracle/product/12.2.0.1/dbhome_1:N
```

**Comment by gvenzl** [comment]
Hi @lkiii, can you confirm with image you are using? The output above looks a lot like the output from the image of the container-registry, not the image that you can/have to build from GitHub to disable the `VOLUME` instruction. Can you also share the output from the `docker build` please?

**Comment by lkiii** [comment]
I am using `./buildDockerImage.sh  -s -v 12.2.0.1` for building, and I am using [this dockerfile](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles)

Log: [build.log](https://github.com/oracle/docker-images/files/2248731/build.log)

**Comment by gvenzl** [comment]
Hey @lkiii, in the output looks fine indeed. When you run the container initially, I assume you are passing on a custom `$ORACLE_SID`, hence why you get `mycustomschema` in the `/etc/oratab` file. However, when you are starting a new container after having commit the original container into the new image, are you still passing on the `$ORACLE_SID`?
I think what bites you here is the default value of `$ORACLE_SID=ORCLCDB`. But that doesn't explain why you get just a `DB` in your `/etc/oratab`

**Comment by gvenzl** [comment]
Closing the issue as these image and database versions have been superseded.
Please reopen if this issue still persists.
