### ISSUE TITLE
jre path issue when buidling FMW 12.2.1.2 Image

### ISSUE THREAD

**Issue by smanjithaya** [oracle/docker-images#930]
I get the below error when I build the FMW 12.2.1.2 image with the script:
Step 11/13 : RUN  cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     $JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE="WebLogic Server" &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file
 ---> Running in 49c061ffc187
/bin/sh: /usr/java/default/bin/jar: Not a directory
Removing intermediate container 49c061ffc187
The command '/bin/sh -c cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     $JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE="WebLogic Server" &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 126
There was an error building the image.

Any pointers ?

**Comment by mriccell** [comment]
@smanjithaya how did you build your server jre image? Can you bash into the image and do java -version?  You can also see under what directory the java binaries are.
You can also pull the Server JRE image from the Docker store or Oracle Container Registry and try building the image.

**Comment by mriccell** [comment]
Closing due to lack of response
