### ISSUE TITLE
startms.sh can't resolve admin-server (sample name: wls-k8s-domain)

### ISSUE THREAD

**Issue by sanjeevgopinath** [oracle/docker-images#933]
[SAMPLE LINK](https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/wls-k8s-domain)

In this sample, [startms.sh](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/wls-k8s-domain/container-scripts/startms.sh) expects the WLS Admin Server to be available under "admin-server" hostname/dns name.

When using the [wls-admin.yml](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/wls-k8s-domain/k8s/wls-admin.yml) to create the admin server, the admin server thus created doesn't have a kube-dns entry for "admin-server".

The reason is because the listen address of "admin-server:8001" is actually created by a headless service that is explicitly declared in the YML.

If this was expected to be accomplished by the kubernetes administrator/dev manually, then this needs to be called out in the documentation.

Since wls-admin.yml doesn't create the headless service, users may find that their managed servers are unable to communicate to admin-server.

Workaround is to convert the wls-admin.yml from a deployment to a stateful set and then declaring a headless service to accept requests on "admin-server:8001"

**Comment by lilyhe123** [comment]
In  wls-admin.yml we define a service named 'admin-server' that's the exact service from which the managed servers connect to admin server.  I don't think we need to define any headless service.

@sanjeevgopinath, did you encounter the issue that managed servers were unable to communicate to admin-server? If yes, can you provide the detail steps and errors?

**Comment by mriccell** [comment]
@sanjeevgopinath  can we get information to help?

**Comment by mriccell** [comment]
Closing due to lack of response
