### ISSUE TITLE
Problems with pre-built DBs

### ISSUE THREAD

**Issue by AFulgens** [oracle/docker-images#938]
In #205 an example has been created for creating docker images containing a pre-built DB, the [example is here](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/prebuiltdb) (note: the links in the original issue are broken).

I tried to run the example (namely I'm not creating a volume, commenting current line 74 in the Dockerfile), but get the following error, when trying to instantiate with the proper docker run command:

```
[...]
50% complete
Creating Pluggable Databases
75% complete
Executing Post Configuration Actions
DBCA Operation failed.
Look at the log file "/opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log" for further details.
[...]
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
ORA-65169 signalled during: CREATE PLUGGABLE DATABASE ORCLPDB1 ADMIN USER PDBADMIN IDENTIFIED BY * ROLES=(CONNECT)  file_name_convert=('/opt/oracle/oradata/ORCLCDB/pdbseed/temp012018-07-17_08-57-56-939-AM.dbf','/opt/oracle/oradata/ORCLCDB/ORCLPDB1/temp01.dbf',
'/opt/oracle/oradata/ORCLCDB/pdbseed/sysaux01.dbf','/opt/oracle/oradata/ORCLCDB/ORCLPDB1/sysaux01.dbf',
'/opt/oracle/oradata/ORCLCDB/pdbseed/undotbs01.dbf','/opt/oracle/oradata/ORCLCDB/ORCLPDB1/undotbs01.dbf',
'/opt/oracle/oradata/ORCLCDB/pdbseed/system01.dbf','/opt/oracle/oradata/ORCLCDB/ORCLPDB1/system01.dbf')  STORAGE ( MAXSIZE UNLIMITED MAX_SHARED_TEMP_SIZE UNLIMITED)...
alter pluggable database ORCLPDB1 open
ORA-65011 signalled during: alter pluggable database ORCLPDB1 open...
2018-07-17T09:11:25.591800+00:00
ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORCLCDB/control01.ctl' SCOPE=SPFILE;
   ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
ORA-65011 signalled during:    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE...
```

When I do create a volume with `VOLUME ["$ORACLE_BASE/oradata"]`, the docker image can be created and the DB is up and running.

```
[...]
50% complete
Creating Pluggable Databases
55% complete
75% complete
Executing Post Configuration Actions
100% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log" for further details.
[...]
#########################
DATABASE IS READY TO USE!
#########################
[...]
```

Any help / ideas are welcome.

**Comment by gvenzl** [comment]
Hi @AFulgens, you most likely ran out of space inside the container. Can you please provide the output of `docker info` in your environment?

**Comment by AFulgens** [comment]
@gvenzl Any ideas, pointers? I'm kind stuck at this point.

**Comment by gvenzl** [comment]
Hey @AFulgens, sorry got distracted with the 18.3 release, hence the lack of response!

To your question, it's good that you are using `btrfs`. If you were using `overlay2` there is in fact a `Base Image Size`, see (dockerd Documentation)[https://docs.docker.com/engine/reference/commandline/dockerd/]:

> dm.basesize
> Specifies the size to use when creating the base device, which limits the size of images and containers. The default value is 10G. Note, thin devices are inherently “sparse”, so a 10G device which is mostly empty doesn’t use 10 GB of space on the pool. However, the filesystem will use more space for the empty case the larger the device is.
> 
> The base device size can be increased at daemon restart which will allow all future images and containers (based on those new images) to be of the new base device size.

But because you are using `btrfs` you don't have that issue, so that's good! :)

I'm afraid next we need to do a bit of debugging to find out what the actual error is.
Can you please hop into the container (via `docker exec -ti <container name|id> /bin/bash`) , `cd` into `/opt/oracle/cfgtoollogs/dbca/ORCLCDB` and do a `cat` on the `ORCLCDB.log` file?
That file might not be there anymore at this point or might not contain enough information. There will also be a `.trc` file that will have loads of information but also the error. If you have an easy way of posting that one, then please post that one, too.

Thx,

**Comment by AFulgens** [comment]
As I wanted to reproduce the issue, I deleted the container, then the image. I re-created the image (w/o VOLUME), then started the container, and now it's working.

Afterwards I had some problems (e.g., ORA-65096, ORA-27090), but those have been straightforward to solve.

Sorry for the false-positive issue, I do not know why it's working now and it hasn't before. If I find a way to reproduce the issue, I'll re-open the issue and drop a comment.

**Comment by MIDFlELDER** [comment]
hello , after creating my image with ./build image , the opt/oracle/oradata still empty in my computer 
is this normal ? if no what can i do ? because i can not find the  *.
sh files
