### ISSUE TITLE
difference with oracle docker images in success center docker

### ISSUE THREAD

**Issue by MaxCCC** [oracle/docker-images#943]
The image of oracle 12.2.0.1 is huge. So' I'm searching for an alternative. What's the difference between the images build here and those images: https://store.docker.com/images/oracle-database-enterprise-edition ?

Can I provide startup scripts (.sql files)?
It seems I can persist the data of a container derived from the image: https://store.docker.com/images/oracle-database-enterprise-edition/plans/08cf8677-bb8f-453c-b667-6b0c24a388d4?tab=instructions

**Comment by gvenzl** [comment]
The images up on Docker Store are not quite the same as the one that you get when building it yourself. Those on the store are tuned for size and startup time but come with the downside of limited functionality that is available.

You will see in the Setup Instructions:

> Caveats
>This Docker image has the following restrictions.
>
>Supports a single instance database.
>Dataguard is not supported.
>Database options and patching are not supported.

Now if you can live with no options available and no way to ever build a patched image (i.e. you are not using these for production), then you can go ahead with these instead.

Another difference is that the images on GitHub are usually more up to date with general enhancements, such as the startup scripts facility which has been contributed by the community. It also allows for easier extension of the image, if desired.

Unfortunately, the way Docker works, it wastes a lot of space when building images, such as the space required by copying in the installer zip file, the space required by the extracted files, etc. None of this space is claimed back after the files are deleted, even if all the operations are preformed in one `RUN` instruction. And it doesn't look like Docker is going to bring enhancements in space management anytime soon, either.
However, there is one way that easily let's you cut in half the image size, which is by using the `experimental` `--squash` option. That option will create a new image after the build that will only contain one filesystem layer where all the wasted space has been claimed back. I highly recommend using this option to build the image, however, you will have to turn `experimental` on first.

You can find more about this here: https://geraldonit.com/2017/11/13/how-to-create-small-docker-images/
