### ISSUE TITLE
How to run custom scripts during container startup against PDB instead of SID

### ISSUE THREAD

**Issue by lvthillo** [oracle/docker-images#947]
I was able to build the oracle database container 12.1.0.2. It works as expected.
Now I try to execute custom scripts during container setup/startup as described in the [sample](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/customscripts).
But when I try to add a custom script it's executed on the `ORACLE_SID `and not the `ORACLE_PDB`.
(when it's added to the entrypoint directory)

I was searching for a way to edit this. I was looking [here](https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/runUserScripts.sh).

It works of course when I execute a .sql script like this:
```
CONNECT sys/pass@//localhost:1521/pdb as SYSDBA;
CREATE USER TESTER IDENTIFIED BY TESTER;
```

But we have already a lot of .sql scripts. The main goal is to test them against the Docker Oracle (locally) and execute them against the real database (where it is not necessary to make the connection to the pdb first). I don't want to update the existing scripts.

Is there a way to execute .sql scripts which are copied to `/docker-entrypoint-initdb.d/startup` or `/docker-entrypoint-initdb.d/setup` (in the dockerfile), against the PDB instead of the SID?

Update:
I thought to update this line:
` *.sql) echo "$0: running $f"; echo "exit" | $ORACLE_HOME/bin/sqlplus -s "/ as sysdba" @"$f"; echo ;;`

to

` *.sql) echo "$0: running $f"; echo "exit" | $ORACLE_HOME/bin/sqlplus -s "sys/$ORACLE_PWD@//localhost:1521/$ORACLE_PDB as SYSDBA" @"$f"; echo ;;`
but it didn't work.

**Comment by lvthillo** [comment]
Okay made some typo in my script. It works now. Hope this is the recommended way to do it?

**Comment by gvenzl** [comment]
Hi @lvthillo 

I'm not sure I fully understand your ask. You can always have a wrapper script that connects to the target and then calls the other scripts. But, of course, as soon as you have a connect string within the script, you will lose that ability.

Not sure whether I can help you more. If so, please let me know. If not, please close the issue.
