### ISSUE TITLE
failed to dial gRPC: unable to upgrade to h2c, received 502 context canceled

### ISSUE THREAD

**Issue by deepanshurana** [oracle/docker-images#948]
when i try to run the `buildDockerImage.sh` using:
`./buildDockerImage.sh -v 12.2.0.1 -e` 
i get the following error: 

`Ignored MD5 sum, 'md5sum' command not available.`
`==========================`
`DOCKER info:`
`Error response from daemon: Bad response from Docker engine`
`==========================`
`Building image 'oracle/database:12.2.0.1-ee' ...`
`ERRO[0000] failed to dial gRPC: unable to upgrade to h2c, received 502
context canceled`

`ERROR: Oracle Database Docker Image was NOT successfully created.`
`ERROR: Check the output and correct any reported problems with the docker build operation.`

Can you please help me in it?
I have a database zip file already downloaded in specified version folder.

**Comment by gvenzl** [comment]
That is a Docker internal error that you are getting, nothing to do with the build itself.
The issue is referenced over here, maybe that helps: https://github.com/docker-library/docker/issues/71

**Comment by prahamurali** [comment]
You must wait for some minutes before the docker starts
