### ISSUE TITLE
Scripts are not working out of the box as repositories changed. 

### ISSUE THREAD

**Issue by OmerCeliker** [oracle/docker-images#95]
Can you help with this issue? I installed the docker but having issue with pulling the jdk from repo.
If I switch to 

celiker@host1 dockerfiles]$ sudo sh buildDockerImage.sh  -g
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_Disk1_1of1.zip: OK
=====================
Building image 'oracle/weblogic:12.2.1-generic' ...
Sending build context to Docker daemon 1.103 GB
Step 0 : FROM oracle/jdk:8
Trying to pull repository registry.access.redhat.com/oracle/jdk ... not found
Trying to pull repository docker.io/oracle/jdk ... not found
Error: image oracle/jdk:8 not found
There was an error building the image.

If I switch to 
FROM docker.io/dgageot/java8
Then I am getting the following error.

[celiker@host1 dockerfiles]$ sudo sh buildDockerImage.sh  -g
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_Disk1_1of1.zip: OK
=====================
Building image 'oracle/weblogic:12.2.1-generic' ...
Sending build context to Docker daemon 1.103 GB
Step 0 : FROM docker.io/dgageot/java8
 ---> c62a758b3554
Step 1 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in c64eb855ec6f
 ---> 41f0ccddb208
Removing intermediate container c64eb855ec6f
Step 2 : ENV FMW_PKG fmw_12.2.1.0.0_wls_Disk1_1of1.zip FMW_JAR fmw_12.2.1.0.0_wls.jar ORACLE_HOME /u01/oracle USER_MEM_ARGS "-Djava.security.egd=file:/dev/./urandom" PATH $PATH:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin
 ---> Running in 75e51c868ae0
 ---> c4bb6f1ee5c6
Removing intermediate container 75e51c868ae0
Step 3 : COPY $FMW_PKG install.file oraInst.loc /u01/
 ---> fc82f2f39ca0
Removing intermediate container 00eb5bbb3472
Step 4 : RUN chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE=\"WebLogic Server\"" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file
 ---> Running in 972be044269e
/bin/sh: useradd: not found
Removing intermediate container 972be044269e
The command '/bin/sh -c chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE=\"WebLogic Server\"" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 127
There was an error building the image.
[celiker@host1 dockerfiles]$

**Comment by brunoborges** [comment]
You have to build [oracle/java:8](https://github.com/oracle/docker-images/tree/master/OracleJDK/java-8/) image.

**Comment by OmerCeliker** [comment]
The initial issue is fixed but there is a problem still.

[celiker@host1 dockerfiles]$ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                    <none>              f51d8d827601        55 seconds ago      1.098 GB
oracle/jdk                8                   ee5dd3c6087d        10 minutes ago      276.1 MB
<none>                    <none>              3f7a284d0c2c        12 minutes ago      276.1 MB
<none>                    <none>              fc82f2f39ca0        50 minutes ago      1.202 GB
<none>                    <none>              94e6393b21cc        About an hour ago   1.202 GB
<none>                    <none>              c50457455bbb        About an hour ago   601.9 MB
<none>                    <none>              e162b81af068        About an hour ago   601.9 MB
oracle/weblogic           12.2.1-developer    ab00565d743a        About an hour ago   601.9 MB
<none>                    <none>              e4f3ea43f907        About an hour ago   601.9 MB
<none>                    <none>              7003077dbe09        About an hour ago   601.9 MB
<none>                    <none>              e55d52ae892f        About an hour ago   601.9 MB
<none>                    <none>              0cd98359af78        About an hour ago   601.9 MB
<none>                    <none>              a72c34b38040        About an hour ago   601.9 MB
<none>                    <none>              d8250b7b71e0        About an hour ago   601.9 MB
<none>                    <none>              da73610ce816        About an hour ago   601.9 MB
<none>                    <none>              412b02d4adfb        About an hour ago   601.9 MB
<none>                    <none>              f7c1f80aa4d8        About an hour ago   601.9 MB
<none>                    <none>              e9ae33faea60        About an hour ago   601.9 MB
<none>                    <none>              cf612bf03e4b        2 hours ago         601.9 MB
<none>                    <none>              a20e24436fa7        3 hours ago         601.9 MB
<none>                    <none>              cc7d7d9bd29f        3 hours ago         601.9 MB
<none>                    <none>              2a55cd71d1d0        3 hours ago         601.9 MB
docker.io/oraclelinux     latest              d2511708c1b4        7 days ago          276.1 MB
docker.io/hello-world     latest              f1d956dc5945        2 weeks ago         967 B
docker.io/dgageot/java8   latest              c62a758b3554        5 weeks ago         380.5 MB
[celiker@host1 dockerfiles]$
[celiker@host1 dockerfiles]$
[celiker@host1 dockerfiles]$
[celiker@host1 dockerfiles]$ sudo sh buildDockerImage.sh  -g
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_Disk1_1of1.zip: OK
=====================
Building image 'oracle/weblogic:12.2.1-generic' ...
Sending build context to Docker daemon 1.103 GB
Step 0 : FROM oracle/jdk:8
 ---> ee5dd3c6087d
Step 1 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in 7344a8dae751
 ---> 5692c09f820e
Removing intermediate container 7344a8dae751
Step 2 : ENV FMW_PKG fmw_12.2.1.0.0_wls_Disk1_1of1.zip FMW_JAR fmw_12.2.1.0.0_wls.jar ORACLE_HOME /u01/oracle USER_MEM_ARGS "-Djava.security.egd=file:/dev/./urandom" PATH $PATH:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin
 ---> Running in 3a0b6c390d66
 ---> 93cb3d07c2d2
Removing intermediate container 3a0b6c390d66
Step 3 : COPY $FMW_PKG install.file oraInst.loc /u01/
 ---> e019b2b6250a
Removing intermediate container 88b784371846
Step 4 : RUN chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE=\"WebLogic Server\"" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file
 ---> Running in 0e0144b4c1fd
/bin/sh: /usr/java/default/bin/jar: No such file or directory
Removing intermediate container 0e0144b4c1fd
The command '/bin/sh -c chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE=\"WebLogic Server\"" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 127
There was an error building the image.

**Comment by brunoborges** [comment]
Clean up your environment. I just built everything from scratch, and it is working fine.

**Comment by OmerCeliker** [comment]
The image is missing java under /usr/java

[celiker@sbx-splunk1 dockerfiles]$ docker run -it oracle/jdk:8
[root@85972e121ee4 /]# whereis java
java:[root@85972e121ee4 /]# locate java
bash: locate: command not found
[root@85972e121ee4 /]# ls -la /usr/
total 76
drwxr-xr-x. 13 root root  4096 May  9 13:57 .
drwxr-xr-x. 17 root root  4096 May 17 22:16 ..
dr-xr-xr-x.  2 root root 12288 May  9 13:58 bin
drwxr-xr-x.  2 root root  4096 Sep 11  2015 etc
drwxr-xr-x.  2 root root  4096 Sep 11  2015 games
drwxr-xr-x.  3 root root  4096 May  9 13:58 include
dr-xr-xr-x. 18 root root  4096 May  9 13:58 lib
dr-xr-xr-x. 29 root root 20480 May  9 13:58 lib64
drwxr-xr-x.  9 root root  4096 May  9 13:58 libexec
drwxr-xr-x. 12 root root  4096 May  9 13:57 local
dr-xr-xr-x.  2 root root  4096 May  9 13:58 sbin
drwxr-xr-x. 61 root root  4096 May  9 13:58 share
drwxr-xr-x.  4 root root  4096 May  9 13:57 src
lrwxrwxrwx.  1 root root    10 May  9 13:57 tmp -> ../var/tmp

**Comment by OmerCeliker** [comment]
I did what you recommended. The issue still exists. Here is log of the whole thing. 

[celiker@sbx-splunk1 java-8]$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
[celiker@sbx-splunk1 java-8]$ docker build -t oracle/jdk:8 .
Sending build context to Docker daemon 4.096 kB
Step 0 : FROM oraclelinux:latest
Trying to pull repository registry.access.redhat.com/oraclelinux ... not found
Trying to pull repository docker.io/library/oraclelinux ... latest: Pulling from library/oraclelinux
8c3e49cb06dc: Pull complete
f8d170e6238e: Pull complete
d2511708c1b4: Pull complete
Digest: sha256:3268a71c56e676806a992bf56df63ad3946839c11b87cb9fa4e4d18ab662ca11
Status: Downloaded newer image for docker.io/oraclelinux:latest

 ---> d2511708c1b4
Step 1 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in ef1a0ca4803f
 ---> 04b0529dbd03
Removing intermediate container ef1a0ca4803f
Step 2 : ENV JAVA_PKG server-jre-8u*-linux-x64.tar.gz JAVA_HOME /usr/java/default PATH $PATH:/usr/java/default/bin
 ---> Running in 41b466550aa0
 ---> 317e40a8c0a0
Removing intermediate container 41b466550aa0
Step 3 : ADD $JAVA_PKG /usr/java/
No source files were specified
[celiker@sbx-splunk1 java-8]$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                  <none>              317e40a8c0a0        39 seconds ago      276.1 MB
docker.io/oraclelinux   latest              d2511708c1b4        7 days ago          276.1 MB
[celiker@sbx-splunk1 java-8]$ docker tag 317e40a8c0a0 oracle/jdk:8
[celiker@sbx-splunk1 java-8]$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED              VIRTUAL SIZE
oracle/jdk              8                   317e40a8c0a0        About a minute ago   276.1 MB
docker.io/oraclelinux   latest              d2511708c1b4        7 days ago           276.1 MB


==============================================================================================================================================================
[celiker@host1 dockerfiles]$ !176
sudo sh buildDockerImage.sh  -g
[sudo] password for celiker:
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_Disk1_1of1.zip: OK
=====================
Building image 'oracle/weblogic:12.2.1-generic' ...
Sending build context to Docker daemon 1.103 GB
Step 0 : FROM oracle/jdk:8
 ---> 317e40a8c0a0
Step 1 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in fad6fd077c03
 ---> ea2a1618c307
Removing intermediate container fad6fd077c03
Step 2 : ENV FMW_PKG fmw_12.2.1.0.0_wls_Disk1_1of1.zip FMW_JAR fmw_12.2.1.0.0_wls.jar ORACLE_HOME /u01/oracle USER_MEM_ARGS "-Djava.security.egd=file:/dev/./urandom" PATH $PATH:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin
 ---> Running in 223a3b80de0b
 ---> 0a7af36fe546
Removing intermediate container 223a3b80de0b
Step 3 : COPY $FMW_PKG install.file oraInst.loc /u01/
 ---> 53c6b08664c0
Removing intermediate container e09d835fab01
Step 4 : RUN chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE=\"WebLogic Server\"" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file
 ---> Running in 8cbb166fde56
/bin/sh: /usr/java/default/bin/jar: No such file or directory
Removing intermediate container 8cbb166fde56
The command '/bin/sh -c chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE=\"WebLogic Server\"" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 127
There was an error building the image.
[celiker@host1 dockerfiles]$
=========================================================================================================================================


[celiker@host1 dockerfiles]$ docker run -it oracle/jdk:8
[root@e6f47c753539 /]# pwd
/
[root@e6f47c753539 /]# ls -la
total 56
drwxr-xr-x.  17 root root 4096 May 17 22:29 .
drwxr-xr-x.  17 root root 4096 May 17 22:29 ..
-rwxr-xr-x.   1 root root    0 May 17 22:29 .dockerenv
-rwxr-xr-x.   1 root root    0 May 17 22:29 .dockerinit
lrwxrwxrwx.   1 root root    7 May  9 13:57 bin -> usr/bin
dr-xr-xr-x.   2 root root 4096 Sep 11  2015 boot
drwxr-xr-x.   5 root root  380 May 17 22:29 dev
drwxr-xr-x.  55 root root 4096 May 17 22:29 etc
drwxr-xr-x.   2 root root 4096 Sep 11  2015 home
lrwxrwxrwx.   1 root root    7 May  9 13:57 lib -> usr/lib
lrwxrwxrwx.   1 root root    9 May  9 13:57 lib64 -> usr/lib64
drwxr-xr-x.   2 root root 4096 Sep 11  2015 media
drwxr-xr-x.   2 root root 4096 Sep 11  2015 mnt
drwxr-xr-x.   2 root root 4096 Sep 11  2015 opt
dr-xr-xr-x. 175 root root    0 May 17 22:29 proc
dr-xr-x---.   2 root root 4096 May  9 13:58 root
drwxr-xr-x.  13 root root 4096 May 17 22:29 run
lrwxrwxrwx.   1 root root    8 May  9 13:57 sbin -> usr/sbin
drwxr-xr-x.   2 root root 4096 Sep 11  2015 srv
dr-xr-xr-x.  13 root root    0 May 12 12:13 sys
drwxrwxrwt.   7 root root 4096 May  9 13:58 tmp
drwxr-xr-x.  13 root root 4096 May  9 13:57 usr
drwxr-xr-x.  18 root root 4096 May  9 13:58 var
[root@e6f47c753539 /]# cd /usr
[root@e6f47c753539 usr]# ls -la
total 76
drwxr-xr-x. 13 root root  4096 May  9 13:57 .
drwxr-xr-x. 17 root root  4096 May 17 22:29 ..
dr-xr-xr-x.  2 root root 12288 May  9 13:58 bin
drwxr-xr-x.  2 root root  4096 Sep 11  2015 etc
drwxr-xr-x.  2 root root  4096 Sep 11  2015 games
drwxr-xr-x.  3 root root  4096 May  9 13:58 include
dr-xr-xr-x. 18 root root  4096 May  9 13:58 lib
dr-xr-xr-x. 29 root root 20480 May  9 13:58 lib64
drwxr-xr-x.  9 root root  4096 May  9 13:58 libexec
drwxr-xr-x. 12 root root  4096 May  9 13:57 local
dr-xr-xr-x.  2 root root  4096 May  9 13:58 sbin
drwxr-xr-x. 61 root root  4096 May  9 13:58 share
drwxr-xr-x.  4 root root  4096 May  9 13:57 src
lrwxrwxrwx.  1 root root    10 May  9 13:57 tmp -> ../var/tmp
[root@e6f47c753539 usr]#

**Comment by brunoborges** [comment]
Read carefully instructions on how to build the images inside OracleJDK folder. Read the [README](https://github.com/oracle/docker-images/tree/master/OracleJDK).

**Comment by OmerCeliker** [comment]
Yes I was able to resolve it. After I saw that you were adding the contents in the Dockerfile.
In different locations you are handling the prerequisites differently.  
For example in buildDockerImage.sh since you do a checksum it fails if the file is not there..
But in the build.sh you do not.
I recommend you do the same thing for consistency.

Anyhow, Thanks for your help. 
This is resolved now.
