### ISSUE TITLE
WebLogic Dockerfile Suggestion

### ISSUE THREAD

**Issue by aquasheep20** [oracle/docker-images#961]
Docker 17.09 introduced chown to the copy command.  By changing from:

COPY $FMW_PKG install.file oraInst.loc /u01/
RUN chown oracle:oracle -R /u01

to:

RUN chown oracle:oracle -R /u01
COPY  --chown oracle:oracle  $FMW_PKG install.file oraInst.loc /u01/

The size of the generated image will be reduced by 930MB or ~30%

In the original sequence chown command creates another layer equal in size to all the files in the /U01 directory when the command is run.  In this case ~ 930MB of install files.  The chown is still needed to set ownership on the /U01 directory itself.  That command could be stacked on the end of the oracle user create earlier in the Dockerfile.

**Comment by Djelibeybi** [comment]
Yes, the addition of the `--chown` parameter will make a lot of the Dockerfiles more efficient. I suspect our efforts will ramp up once we release a version of Oracle Container Runtime that includes this feature. :)

**Comment by futurisma** [comment]
👍 Very, very useful suggestion, not sure if there is any difference between docker versions, but I needed to add a '=' after the chown to get it to work on my build which shaved 400M off the docker image size :

RUN chown oracle:oracle -R /u01 && chmod +xr $SCRIPT_FILE
COPY --chown=oracle:oracle $FMW_PKG install.file oraInst.loc /u01/

**Comment by mriccell** [comment]
Will try the suggestion to reduce image size

**Comment by mriccell** [comment]
We tried the suggestion but found no difference in image size and we encountered permission problems deleting the installer.
