### ISSUE TITLE
Dockerfile for container-registry.oracle.com/database/enterprise:12.2.0.1-slim

### ISSUE THREAD

**Issue by rahulmr** [oracle/docker-images#967]
Is it possible to get the `Dockerfile` for `container-registry.oracle.com/database/enterprise:12.2.0.1-slim` image?
The non-slim `Dockerfile` seems to be different than the slim version.
It is very difficult to create a prebuilt DB container.

slim version below env variable do not seem to work.
```
ORACLE_SID=MYDB
ORACLE_DOMAIN=dsone.3ds.com
ORACLE_CHARACTERSET=AL32UTF8
```
while below works
```
DB_SID=passdb
DB_PDB=passpdb
DB_DOMAIN=dsone.3ds.com
DB_MEMORY=1G
```

Also, I am bit confused where to keep the sql files which I want to execute after the db is created.
whether it should be `/opt/oracle/setup` or `/u02/app/oracle/setup` or is it `/home/oracle/setup`

When I create the slim container, I see that the setup folder location is  `/home/oracle/setup`
How to use my own `dbca.rsp.tmpl` ? Is it possible to use one ?

How to myself create a pre-built db container which is as slim as 2-4GB?

Any help in this regard is really appreciated.

Thanks in advance!!

**Comment by Djelibeybi** [comment]
The Database images on the Oracle Container Registry are not built from the Dockerfiles in this repo. They're the only image that differs between the GitHub version and the binary release. 

I'll let @gvenzl explain more.

**Comment by rahulmr** [comment]
@Djelibeybi so is it possible to run our own sql scripts once the database is up and running? If yes, how to do that and where to keep the `.sql` files?
Also, about the variables, which are used? `ORACLE_` ones or `DB_` ones?

**Comment by gvenzl** [comment]
Hi @rahulmr, the images on the container-registry do not have the functionality yet of running scripts after setup and/or startup. If you need that functionality, you will have to build an image yourself via the Dockerfiles provided.

**Comment by rahulmr** [comment]
Thanks @gvenzl ! Now I am able to do what I want... Explored a lot and now I am quiet comfortable how everything works.

**Comment by jahangirk** [comment]
Hi seems like I have run into the similar problem where I want to execute db scripts after healthy db. Seems like I have to create my own dockerfile for it ? do you have sample dockerfile. ?

**Comment by Djelibeybi** [comment]
This issue is closed. Please open a new issue for your question.
