### ISSUE TITLE
Pre-built DB image is slow on first use

### ISSUE THREAD

**Issue by cpenhaligon** [oracle/docker-images#968]
After following the instructions at https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/samples/prebuiltdb I managed to create a 12.2.0.1 image with the intention of using it in our Jenkins CI environment. 

It's stored in our private Docker repository but takes 10 minutes to pull so I decided to cache it on the build slaves (which are dynamically spun up and down). 

However, when we cache the image, the first container we run from it takes 10-15 minutes to reach the "Database open" stage and become usable. Oddly, if we stop and remove the first container and launch a second, that starts within 2 minutes. 

When we weren't doing the caching, the container would always start and reach the "Database open" stage within 2 minutes of the image being pulled. 

I've managed to reproduce this across Linux, MacOS and several different versions of Docker CE. 

Is anyone able to provide an explanation for this behaviour?

**Comment by rahulmr** [comment]
@cpenhaligon for me it took merely minutes for the database to be up and running on Linux RHEL7.5 docker-ce 18.03.1-ce. But in my case the DB had only few tablespaces created and no data as such.

**Comment by gvenzl** [comment]
Hi @cpenhaligon, given your description it sounds like it is related with the caching on your build slaves rather than the image itself. Perhaps the cache is first validating whether it needs to update the local copy and that is causing the delay in startup? Can you determine what's happening during these 10-13 minutes?

**Comment by gvenzl** [comment]
Closing due to lack of response.
