### ISSUE TITLE
ERROR : ORA- errors detected, config DB ora failed

### ISSUE THREAD

**Issue by mattadamson** [oracle/docker-images#975]
Hi

I tried using the 12.1.0.2 docker image with similar default execution options from the documentation and a different SID i.e.

```
docker run -d -it --name pdb2 --shm-size 4g container-registry.oracle.com/database/enterprise:12.1.0.2

 and then received this error 

ERROR : ORA- errors detected, config DB ora failed, please check log /home/oracle/setup/log/configDBora.log for details!
Docker DB configuration failed ...
PC05249s-MacBook-Pro:~ matta$ docker exec 532b87944b46 tail /home/oracle/setup/log/configDBora.log -n 10
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options
Oracle Interim Patch Installer version 12.2.0.1.8
Copyright (c) 2018, Oracle Corporation.  All rights reserved.

Please check the arguments and try again.

OPatch failed with error code 135
writing relink log to: /u01/app/oracle/product/12.1.0/dbhome_1/install/relink.log
```

Does anyone know what could be wrong or how to diagnose further? 

Many thanks

**Comment by mattadamson** [comment]
I'm not sure how to get past the error "OPatch failed with error code 135" however does anyone know other images we could try that may not have the same issue? 

Thanks

**Comment by gvenzl** [comment]
Hi @mattadamson, you can just use the scripts in this repo to build your own 12.1.0.2 image.

**Comment by mattadamson** [comment]
Thanks Gerald,

 I'm not a docker expert so not completely sure what you mean here. A few points

 1. I thought simply pulling an existing published image and running with defaults should be all that's required to start an oracle container. Why do we need to build a new image here? If I build one to correct a mistake shouldn't we simply publish this update so others can benefit?
2. What does the specific error mean and why do we see it from this image?
3. When you refer to scripts what exactly do you mean? Which scripts and are there any steps to build the image in this way? Or are you referring to a standard docker image build from a dockerfile?

Many thanks

**Comment by mattadamson** [comment]
appreciate your thoughts or has anyone got an oracle docker image working locally from another source? Thanks

**Comment by gvenzl** [comment]
Hi @mattadamson, did you ever get your image running?

Note, the image above is from the container-registry.oracle.com which is different from the ones you can build with the build files provided in this repository.
For issues with container-registry.oracle.com images, you will have to open a support ticket with Oracle Support.

Alternatively, you can try to build an image with the build files from this repository.
