### ISSUE TITLE
Switching between useres (oracle <> root)

### ISSUE THREAD

**Issue by bchennareddy** [oracle/docker-images#977]
Hi Team,

I am new to docker and linux, I built image and able to run the container but I am not able to switch between the useres oracle and root. can you please help me to solve this issue.

**Comment by gvenzl** [comment]
You shouldn't need to switch between users. What is it that you are trying to do?

**Comment by oehrlis** [comment]
root is always available / present just run the following or similar command to see root stuff.

```
docker exec -u root <CONTAINERNAME> tail -f /var/log/messages
```

or run it as oracle to see oracle stuff
```
docker exec -u oracle <CONTAINERNAME> tail -f /opt/oracle/diag/rdbms/....
```

cheers
Stefan

**Comment by bchennareddy** [comment]
thanks you

**Comment by aivl2018** [comment]
Can we switch to root user  inside container?
As i am getting permission issue after creating volume mount inside container and also my server.
