### ISSUE TITLE
How to remove useless managed servers in cluster after scale up/down?

### ISSUE THREAD

**Issue by yekki** [oracle/docker-images#98]
I use docker-compose scale up the weblogic cluster,  it works well. Then I scale down, the containers works well, but the useless managed servers in weblogic admin console are still there. Even I scale up again, docker will not use the servers anymore. How to solve this issue??  Waiting your replay, thanks!

**Comment by brunoborges** [comment]
This is a WebLogic specific question, not related to Docker actually. There are some WLST python scripts that admins write to go through a domain and check dead managed servers, and remove them.
