### ISSUE TITLE
When creating a container database convert ORACLE_SID and ORACLE_PDB to uppercase

### ISSUE THREAD

**Issue by sgaetjen** [oracle/docker-images#984]
had specified
 ORACLE_SID=db18root and ORACLE_PDB=db18 
Saw this error during creation of the container
 ls: cannot access /opt/oracle/oradata/db18root/*/: No such file or directory
Believe everything was okay with build but decided to remove it and start over using parameters in upper case  and did not see the errors

**Comment by ivansa-ru** [comment]
Why should SID be in uppercase? Using graphical OUI I can set SID to whatever I want in any case. This IS a problem. And making it simply always uppercase ain't a solution.

**Comment by AmitArie** [comment]
@gvenzl do you have answers for the @ivansa-ru's comment?
