### ISSUE TITLE
error while installing oracle 12.2.0.1 in centos 7 docker image

### ISSUE THREAD

**Issue by monojitsaba** [oracle/docker-images#986]
hi i am trying to install oracle 12c on centos 7 docker image and not on oraclelinux docker iamge
i am using FROM centos:7 in dockerfile
getting below errors while installDBBinaries.sh gets executed

Preparing to launch Oracle Universal Installer from /tmp/OraInstall2018-09-18_07-56-35AM. Please wait ...[FATAL] [INS-30131] Initial setup required for the execution of installer validations failed.
   CAUSE: Failed to access the temporary location.
   ACTION: Ensure that the current user has required permissions to access the temporary location.
*ADDITIONAL INFORMATION:*

 - PRVG-1901 : failed to setup CVU remote execution framework directory "/tmp/CVU_12.2.0.1.0_oracle/" on nodes "136d43c25f1c"
 - Cause:  An operation requiring remote execution could not complete because the attempt to set up the Cluster Verification Utility remote execution framework failed on the indicated nodes at the indicated directory location because the CVU remote execution framework version did not match the CVU java verification framework version. The accompanying message provides detailed failure information.
 - Action:  Ensure that the directory indicated exists or can be created and the user executing the checks has sufficient permission to overwrite the contents of this directory. Also review the accompanying error messages and respond to them.
Summary of the failed nodes
136d43c25f1c
 - An internal error occurred within cluster verification framework The command executed was "/tmp/CVU_12.2.0.1.0_oracle//exectask.sh -getver". The output from the command was "/tmp/CVU_12.2.0.1.0_oracle/exectask: error while loading shared libraries: libaio.so.1: cannot open shared object file: No such file or directory"
 - Cause: Cause Of Problem Not Available
 - Action: User Action Not Available
 - Version of exectask could not be retrieved from node "136d43c25f1c"
 - Cause: Cause Of Problem Not Available
 - Action: User Action Not Available
 - An internal error occurred within cluster verification framework The command executed was "/tmp/CVU_12.2.0.1.0_oracle//exectask.sh -getver". The output from the command was "/tmp/CVU_12.2.0.1.0_oracle/exectask: error while loading shared libraries: libaio.so.1: cannot open shared object file: No such file or directory"
 - Cause: Cause Of Problem Not Available
 - Action: User Action Not Available
 - Version of exectask could not be retrieved from node "136d43c25f1c"
 - Cause: Cause Of Problem Not Available
 - Action: User Action Not Available

**Comment by Djelibeybi** [comment]
> i am trying to install oracle 12c on centos 7 docker image and not on oraclelinux docker iamge

Why?

**Comment by Djelibeybi** [comment]
The `COPY --chown` command works fine with the latest release of Docker for Oracle Linux (18.03). The rest of the commands can be installed manually if you want them. We do not support CentOS as a platform for Oracle Database, so I'm closing this issue now.
