### ISSUE TITLE
Sample 12.1.3 README states it relies on 12.1.3-developer but it really 12.1.3-generic

### ISSUE THREAD

**Issue by r-giskard-reventlov** [oracle/docker-images#988]
I'm trying to get the weblogic 12.1.3 sample image created. I've followed the README for building oracle/weblogic (in my case I needed developer) however I can't create the sample as it relies on the generic image. The README for the sample states a pre-requisite of having the oracle/weblogic:12.1.3-developer image but what is really needed is oracle/weblogic:12.1.3-generic.

I would like to create the sample image in developer mode if possible.

**Comment by mriccell** [comment]
@r-giskard-reventlov I will make the change in the 1213-domain sample.
