### ISSUE TITLE
/bin/sh: /usr/java/default/bin/jar: Not a directory

### ISSUE THREAD

**Issue by prasenforu** [oracle/docker-images#99]
dockerfiles]$ git pull
Already up-to-date.
[pkar@ip-172-31-19-52 dockerfiles]$ sh buildDockerImage.sh -d -v 12.2.1
Checking if required packages are present and valid...
fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip: OK
=====================
Building image 'oracle/weblogic:12.2.1-developer' ...
Sending build context to Docker daemon 402.7 MB
Step 1 : FROM oracle/jdk:8
 ---> be2ddf461adf
Step 2 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in bf9822fd24cc
 ---> e25f5c906781
Removing intermediate container bf9822fd24cc
Step 3 : ENV FMW_PKG fmw_12.2.1.0.0_wls_quick_Disk1_1of1.zip FMW_JAR fmw_12.2.1.0.0_wls_quick.jar ORACLE_HOME /u01/oracle USER_MEM_ARGS "-Djava.security.egd=file:/dev/./urandom" PATH $PATH:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin
 ---> Running in 20c47f18fd93
 ---> 77d3e63d8faf
Removing intermediate container 20c47f18fd93
Step 4 : COPY $FMW_PKG install.file oraInst.loc /u01/
 ---> 7dd2549fcfde
Removing intermediate container a44a65971d17
Step 5 : ADD $JAVA_PKG /usr/java/
 ---> 4551748e277e
Removing intermediate container 1f7cb4162286
Step 6 : RUN chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file
 ---> Running in 9bdce9d534d7
**/bin/sh: /usr/java/default/bin/jar: Not a directory**
Removing intermediate container 9bdce9d534d7
The command '/bin/sh -c chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle &&     echo oracle:oracle | chpasswd &&     cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     su -c "$JAVA_HOME/bin/java -jar /u01/$FMW_JAR -invPtrLoc /u01/oraInst.loc -jreLoc $JAVA_HOME -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME" - oracle &&     chown oracle:oracle -R /u01 &&     rm /u01/$FMW_JAR /u01/$FMW_PKG /u01/oraInst.loc /u01/install.file' returned a non-zero code: 126
There was an error building the image.

**Comment by brunoborges** [comment]
Please rebuild the image found in [../OracleJDK/java-8]()
