### ISSUE TITLE
repository does not exist or may require 'docker login'.

### ISSUE THREAD

**Issue by jessengolab** [oracle/docker-images#999]
docker run push jessengolab/spring-boot-docker:latest
Unable to find image 'push:latest' locally
docker: Error response from daemon: pull access denied for push, repository does not exist or may require 'docker login'.

**Comment by Djelibeybi** [comment]
I am closing this issue because the error doesn't appear to have anything to do with the Dockerfiles in this repo but your problem is that you can't have both "run" and "push" in the same `docker` command-line.
